### ISSUE TITLE
@react-directory, Actual results are overriding with 

### ISSUE THREAD

**Issue by rkreddysp** [pnp/sp-dev-fx-webparts#1033]
Hi Team,
I am facing the issue when search with specific word, I can see the Actual result shows for few seconds and overridden by first letter matching results.

I believe first letter matching results call takes more time compare to complete word then it is overriding the word results as final result.

It would be great, if you can help me to fix the issues.

Example:
if I search for word "ravi", I can see the actual results for "ravi" then after it is overridden by matching results of  "r".

Thanks
Ravi Kumar

**Comment by hugoabernier** [comment]
@rkreddysp did you ever resolve this issue?

Closing this issue as incomplete. If you still need help with this issue, feel free to open a new issue. When you do, I encourage you to take the time to fill the issue template that's provided so that we can help you better.
