### ISSUE TITLE
@react-calendar, Issue with weekly recurring events for specific day

### ISSUE THREAD

**Issue by RaghavaReddy87** [pnp/sp-dev-fx-webparts#1034]
I have created weekly recurrence and selected every 1 weeks on , selected "Thursday" and start date is Oct 17,2019 and end date is Oct 28, 2019.

Issue is for the above scenario getting created extra event on Oct 31, 2019(Thursday).

Thanks,
Raghava

**Comment by hugoabernier** [comment]
@RaghavaReddy87 did you ever resolve this issue?

Closing this issue as incomplete. Feel free to open a new issue with the template provided so that we can help you better.
