### ISSUE TITLE
How to open a task module pop up in teams from SPFx web part

### ISSUE THREAD

**Issue by TarakSivakoti** [pnp/sp-dev-fx-webparts#1043]
Hello,

Is there any way to open a task module in teams from sharepoint webpart. We have added a sharepoint webpart as a tab in our team app. the site page is loading fine. but unable to call the task module when clicking on a button. Do anyone knows how to acheive this?

**Comment by TarakSivakoti** [comment]
Kindly Let us know if anyone can help with this

**Comment by hugoabernier** [comment]
@TarakSivakoti this issue list is intended for issues related to the samples in this repository.

I encourage you to open a new issue at  https://aka.ms/spdev-issues where we can hopefully get you someone to help you faster.
