### ISSUE TITLE
Is Recurrence is supported by js-modern-calendar? How can I get recurrence events in js-modern-calendar?

### ISSUE THREAD

**Issue by ganesh-sanap** [pnp/sp-dev-fx-webparts#1061]
## Category

- [x] Question
- [x] Bug

## Authors
@jcoleman-pcprofessional ,

I am using js-modern-calendar webpart to show the calendar on SharePoint modern page and It is working fine for one day events.
But, whenever I am trying to use recurrence events it is not working as expected.

So, my first question, Is recurrence events are supported by this web part as it does in SharePoint Calendar App?

(As mentioned in [PR#882](https://github.com/SharePoint/sp-dev-fx-webparts/pull/882) by @joaojmendes )

If yes, then how can I get it work by using this webpart??

## My Scenario
I am creating a recurrence event which will only be held on every Tuesday from 12 Nov 2019 to 28 Nov 2019

## Expected or Desired Behavior
It should show the event only on Tuesdays and highlight only 3 dates 12, 19 and 26 Nov.

## Observed Behavior
It shows the event starting from 12 Nov to 26 Nov and highlighting all the dates in between these two dates.

## Steps to Reproduce
Create a new event with below setup:

**Event Setup:**
 - Make this a repeating event.
 - Weekly on Every Tuesday from Start Date: 11/12/2019 to End by: 11/28/2019

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
Hey @ganesh-sanap I'm going to close this issue as it is pretty old.

If you feel that this should be a supported feature, feel free to open a new Improvement issue and make a suggestion. Hopefully, someone will volunteer to help.
