### ISSUE TITLE
react-list-form issue: SP Column Validations are Not Applied 

### ISSUE THREAD

**Issue by apcsaba** [pnp/sp-dev-fx-webparts#1112]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@DanyWyss 
Regarding **react-list-form** webpart

## Expected or Desired Behavior

SharePoint validations  such as mandatory fields or custom column validation must be applied when saving a new list item.

## Observed Behavior

I have used this web part and set the "Form Type" to "New".
When I try to save a new list item, I do not see any of the validations/error messages. The Save button just refreshes the page (or if I have set up the redirect URL, redirects to that URL). 

## Steps to Reproduce

Add this web part to a page. Link it to a list where there are mandatory fields and custom column validations. Set the Form Type to New and Publish the page. Then try to create a new list item which misses some of the mandatory fields or violates the column validations. Notice that the error messages are not displayed on the page. 

Thanks for your contribution! Sharing is caring.

**Comment by Sumitrpareek** [comment]
Same is happening with me.

Please help.

**Comment by Fnu-Avi** [comment]
@apcsaba Did you figured out on how to get around this issue?

**Comment by apcsaba** [comment]
@Fnu-Avi  No I haven't.

**Comment by PrasadKasireddy** [comment]
This issue has been resolved - https://github.com/pnp/sp-dev-fx-webparts/issues/1354 & https://github.com/pnp/sp-dev-fx-webparts/pull/1372

**Comment by bcameron1231** [comment]
Closing as this issue has been fixed https://github.com/pnp/sp-dev-fx-webparts/pull/1372/ 

Please get latest from the repo
