### ISSUE TITLE
Question:  react-page-navigator

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1124]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors
@aakashbhardwaj619 

## Expected or Desired Behavior
I am using the React PageNavigator as a component in my project.
When I click on a NavLink, I just want to render the url in an IFrame in the webpart.
Only if I CTRL-Click the nav do I want to open the link **in a new page**.  

To do this, I am using an onLinkClick callback to change my state, NOT go to the link.
In the callback, I'm using e.preventDefault(); to prevent the browser from navigating to the link.
Then if CTRL-Key is detected, it opens the link in a new page.

## Observed Behavior
The code works just fine for any Non-SharePoint link.
When in the workbench, my preventDefault() also works on links to SharePoint.

When I build and load on a real page,
Normal clicking on the nav element loads the linked page in the current browser page.

So to sum it up, **ie preventDefault(); does not seem to have any impact on SharePoint links while on a normal SharePoint page**.

I did notice that my react component does briefly render the link in an IFrame (desired behavior) before jumping to the link.

## Steps to Reproduce

```Typescript
  public onNavClick = (e?: React.MouseEvent<HTMLElement>, item?: INavLink): void => {
    e.preventDefault();
    //Code deleted which determine selectedEntity & selectedNavItem from item

    if (e.ctrlKey) {
      //Set clicked pivot as the hero pivot
        let openThisWindow = item.url;
        window.open(openThisWindow, '_blank');
        this.setState({
          selectedEntity : selectedEntity,
          selectedNavKey : item.key,
          selectedNavItem : selectedNavItem,
          lastEvent: 'Nav Click',
        });
    } else 
      this.setState({
        selectedEntity : selectedEntity,
        selectedNavKey : item.key,
        selectedNavItem : selectedNavItem,
        lastEvent: 'Nav Click',
      });
   }
}
```
Thanks for any suggestions.

**Comment by hugoabernier** [comment]
@mikezimm I would recommend filing this issue in the https://github.com/SharePoint/sp-dev-docs repo where we can help you better.

This issue list is intended for issues related to samples in this repository.

Thanks for your understanding.
