### ISSUE TITLE
News webpart (Hub News layout) - Safari MacOS and iPad

### ISSUE THREAD

**Issue by timbowes** [pnp/sp-dev-fx-webparts#1126]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

SharePoint pages using the News webpart in "Hub News" layout render quickly in IE11, Chrome 79, and Edge 79 on Windows 10 and MacOS. This includes when multiple site sources from across the hub site are being pulled in.

## Observed Behavior

In Safari 13.0.4 for MacOS 10.15.2 and in all browsers in iPadOS 13.3, any page featuring the News webpart in "Hub News" layout load either extremely slowly (up to 5 minutes) or timeout. 

Initially on MacOS, the Safari windows displays a white page, then Safari freezes followed by spinning beachball of death. This can last up to a minute. Then the page begins to load, but very slowly with long delays for webparts to render. The browser scrollbar locks until the page is fully loaded. This seems to cause intense CPU activity on Mac and causes the fans to kick in. 

On iPadOS, all apps that browse the web must use the WebKit framework, meaning this issue applies to all tested browsers: Safari, Edge, Chrome and the iOS SharePoint app.

In my tests, as soon as the News wepbart is switched from "Hub News" to another layout, performance is immediately improved. 

## Steps to Reproduce

Open a page utlizing the News webpart in "Hub News" view in Safari for MacOS or any web browser on iPadOS, including the iOS SharePoint app. 

## Impact

The "Hub News" layout is a very useful webpart, as it enables us to display multiple news items from across out tenant without taking up much space. It is invaluable on our intranet homepage, enabling our staff to view news at a glance.

Unfortunately, this issue has a negative impact on our hundreds of iPad users, who immediately run into issues when they try to access the intranet on their devices. This is therefore a major issue for us.

Note that I have raised this issue through our official tenant support channels and have attempted to have it escalated.

**Comment by ulflunqvist** [comment]
We're experiencing the exact same issue, Safari 13.0.5 on macOS 10.15.3.

**Comment by hugoabernier** [comment]
This issues list is intended for issues related to web part samples.

As your issue appears to be related an out-of-the-box web part, I encourage you to open this issue in the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs) repository.
