### ISSUE TITLE
Sharepoint-crud :  malicious unused package

### ISSUE THREAD

**Issue by sganta** [pnp/sp-dev-fx-webparts#1156]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@waldekm

## Expected or Desired Behavior

I am using  node version 10.19

"npm install" runs without error.

## Observed Behavior

While running npm install, I get the following error.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-connect'
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

This is a well-known issue with this package. It has a security vulnerability. https://stackoverflow.com/questions/53578201/npm-err-404-not-found-event-stream3-3-6

## Steps to Reproduce

npm install

**Comment by hugoabernier** [comment]
@sganta closing this issue as your pull request seems to solve this issue.

Thanks for reporting this. If you're still experiencing issues, please do not hesitate to open a new issue.
