### ISSUE TITLE
Angular Elements

### ISSUE THREAD

**Issue by vinaunder** [pnp/sp-dev-fx-webparts#1161]
## Category

- [X] Question
- [ ] Bug
- [x] Enhancement

## Expected or Desired Behavior
I created 2 components with angular elements using @ pnp / spfx, in the most current versions.

the components are working correctly, but when I add component 1 and then add component 2
The following message begins: 
`ERROR DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "app-wp-xxxx-xxxx-web-part" has already been used`

if i add 2x the same component i have no error, only when i add different components.

**Comment by hugoabernier** [comment]
@vinaunder this repository is intended for issues related to the web part samples in this repository.

Feel free to open a new issue in the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs) repository where we may be able to help you better.
