### ISSUE TITLE
react-calendar adding custom fields

### ISSUE THREAD

**Issue by essineden** [pnp/sp-dev-fx-webparts#1162]
New in SPFx React

## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors

@joaojmendes 

## Expected or Desired Behavior

If I add a field from the List Settings of the Calendar Web App, how can I have that fields reflected on this App? -- sorry, I'm still trying to understand where I need to make some changes on the code so that it shows up.

**Comment by narulasrinivas** [comment]
@essineden  -  Please provide below input

- Provide some screenshots
-  if you're referring to samples web-part, please provide the samples older link.

**Comment by hugoabernier** [comment]
@essineden try the following:
- Add your field to `src\controls\Event\event.tsx`
- Add your field to 'src\services\IEventData.ts'
- Update `src\services\spservices.ts` to use your new field
- If needed, update `src\webparts\calendar\components\Calendar.tsx` to render the event (in `renderEvent`).

I hope this will get you started in the right direction?

Let us know if that works for you, and what else you had to do -- if any.
