### ISSUE TITLE
Remove Natives 1.1.6 Dependency

### ISSUE THREAD

**Issue by TracyGH** [pnp/sp-dev-fx-webparts#1163]
## Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

## Authors
@beingdhavalshah

## Expected or Desired Behavior
Run the following without errors:
`npm install`
`gulp serve`

## Observed Behavior
After running `npm install` and `gulp serve `, I received the following error:

> ReferenceError: internalBinding is not defined

After some Googling, the overwhelming recommendation is to run this command:
`npm install natives@1.1.6`
It does fix the problem, but also generates a different/scary looking error:

> This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

[The package home page](url) confirms the news, and contains a foreboding message from the creator:

> Don't use unless you know what you're doing, or at least, are ok with the risks. Don't say I didn't warn you.

![image](https://user-images.githubusercontent.com/38665906/75938733-bc1d1b80-5e45-11ea-934a-c0a9a6df17f7.png)

**Can anyone provide guidance on how to eliminate this dependency from the affected SPFx samples?**  

## Steps to Reproduce
1. Clone the repo
2. Navigate to the samples > react-aggregated-calendar web part
3. Run `npm install`
4. Run `gulp serve`

## Additional Notes
I have reported this bug for the react-aggregated-calendar web part, but I have found related issues reported for a number of other SPFx sample extensions and web parts.

**Comment by sharepointknight** [comment]
I'll work on this.

**Comment by nanddeepn** [comment]
Hi @TracyGH , @hugoabernier 
I did `npm install` (Node version: v8.9.4) followed by `gulp serve`.

but did not get the reported error: ReferenceError: internalBinding is not defined
Rather, I get the error:

> Error - typescript - src/webparts/reactAggregatedCalendar/components/ReactAggregatedCalendar.tsx(208,16): error TS2339: Property 'fullCalendar' does not exist on type 'JQuery<HTMLElement>'.

**Comment by hugoabernier** [comment]
@TracyGH can you install the [CLI for Microsoft 365](https://pnp.github.io/cli-microsoft365/) and run `m365 spfx doctor` from the root of the project folder and let us know what you get?

**Comment by SmitaNachan** [comment]
Hi @hugoabernier 
I am also facing the same issue reported by @nanddeepn 

> Error - typescript - src/webparts/reactAggregatedCalendar/components/ReactAggregatedCalendar.tsx(208,16): error TS2339: Property 'fullCalendar' does not exist on type 'JQuery'.

Can we please address it as a part of this same issue or I am happy to create a new one for this?
