### ISSUE TITLE
Inconsistent Behavior for Tenants (Get User Display Name)

### ISSUE THREAD

**Issue by jtlivio** [pnp/sp-dev-fx-webparts#1179]
## Category

- [X] Question
- [X] Bug
- [ ] Enhancement

When getting the display name for a user, only is visible when there is an English Tenant, or is not managed by a CSP Provider

```typescript
export default class HgHello extends React.Component<IHgHelloProps, IHgHelloState> {
  
  public constructor(props: IHgHelloProps, state: IHgHelloState) {
    super(props);

 this.state = {
     userName : ""
    };

 this.getUser().then(userProps => {      
      this.setState({
        userName :  userProps.Title
      });

    });
  }
public async getUser()
   { 
    return await sp.web.currentUser.get();
  }
public render(): React.ReactElement<IHgHelloProps> {
    return (
      <div className={ styles.hgHello }>
        <div className={ styles.container }>
          <div className={ styles.row }>
            <div className={ styles.column }>
              {/* <span className={ styles.title }>Bem vindo! {this.getUser()}</span> */}
              <span className={ styles.title }>Bem vindo "{this.state.userName}"!</span>
              <p className={ styles.subTitle }>Tudo o que necissitas no Portal Colaborativo da tua Empresa</p>   
              <p className={ styles.subTitle }></p>          
            </div>
          </div>
        </div>
      </div>
    );
  }
}
```

## Expected or Desired Behavior
Claim Display Name should appear in all tenants 

## Steps to Reproduce
Build a small React WebPart that catch the display name of the logged user. Try in a Portuguese Tenant and a English Tenant.

If you get OK for both, then is a CSP Provider non compliment, or not supported behavior.

**Comment by hugoabernier** [comment]
@jtlivio this issue list is intended for issues related to sample web parts in this repo.

I recommend you open a new issue at  https://aka.ms/spdev-issues where we can hopefully get you the appropriate help.
