### ISSUE TITLE
react-calendar customization

### ISSUE THREAD

**Issue by SnehalSutar6111** [pnp/sp-dev-fx-webparts#1184]
react-calendar customization
- [ ] Question
- [ ] Bug
- [x] Enhancement

## Author
@joaojmendes 

## Expected or Desired Behavior

I want to add some buttons in the day slot, but I am not able to get the exact code to customize the slots in calendar.Can any one please guide me in this?

Thanks for your contribution! Sharing is caring.

**Comment by SnehalSutar6111** [comment]
I can see that react-big-calendar is used to display the calendar, but how can I edit the date slots in it?

**Comment by hugoabernier** [comment]
Thanks for reporting the issue. 

@joaojmendes would you be able to advise on where to start with this?

**Comment by hugoabernier** [comment]
@SnehalSutar6111, the sample is based on React-big-calendar, you should try the samples to customize the looks from their [documentation](http://jquense.github.io/react-big-calendar/examples/index.html#timeslots). 

Let us know how you did!
