### ISSUE TITLE
React Calendar - location issue

### ISSUE THREAD

**Issue by Uliii** [pnp/sp-dev-fx-webparts#1202]
React Calendar - location issue
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement
- [ ] Sample request

## Authors
@joaojmendes 

## Expected or Desired Behavior

Remove location from the form or delete default value or make possible to choose location on the map/search.

## Observed Behavior
1. While creating new item in React Calendar (webpart view) you can't change the Location.
2. When you don't type anything and save it, it sets Portugal as a default one.
As tip given in documentation: " The location and name of the list and the dates of the events to be displayed are defined in the properties of the web part." -> there is no location or list name in properties of the webpart. 
3. E.g. when you search for Gdansk it gives only one address with the whole street name and building number which is not necessary what we want.

## Steps to Reproduce

1. Add webpart
2. Choose list.
3. Add an item
4. Try to change location or save it without adding location
5. Try to search for a different location

**Comment by hugoabernier** [comment]
@Uliii, it looks like the geolocation code is located in `src\controls\Event\event.tsx`.

Lines 68-69 define default coordinates (which seem to map to Portugal).

Line 78 will detect whether your browser will support geolocation. 

So, according to the code, your browser either does not support geolocation OR your didn't accept the browser prompt for access to location.

You can confirm by looking at the console developer tools and see if you see `browser Geolocation is not available`.

I hope this helps?
