### ISSUE TITLE
Search text automatically on sharepoint iframe embed code loaded

### ISSUE THREAD

**Issue by kfir91** [pnp/sp-dev-fx-webparts#1213]
- [x] Question
- [ ] Bug
- [ ] Enhancement
- [ ] Sample request

i trying to search text automatically when the doc in the iframe loaded.

i have embed code that i took from sharepoint of some doc:

`<iframe src="https://******.sharepoint.com/personal/*******/_layouts/15/Doc.aspx?sourcedoc={55941cc0-d7ca-4af6-a989-f57e9841172b}&amp;action=embedview&amp;wdStartOn=1" width="476px" height="288px" frameborder="0">This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> document, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>`

and i want that when the doc in the iframe loaded its jump to another page by serching text event.

there is rest api of sharepoint for this? or any idea how can i do this?

tnx

**Comment by kfir91** [comment]
Any?

**Comment by bcameron1231** [comment]
Hi, Unfortunately, this question is unrelated to the samples in this repo. If you have generic development questions, please head over to the SP-Dev-Docs repository. Thanks!
