### ISSUE TITLE
js-employee-spotlight critical 

### ISSUE THREAD

**Issue by marting1010** [pnp/sp-dev-fx-webparts#1227]
- [ ] Question
- [x] Bug
- [x] Enhancement
- [ ] Sample request

I liked the look of this js-employee-spotlight web part so did a npm install on it and it highlighted a number of high and critical vulnerabilities around command injection in the open package as shown below. It sounds like an npm audit fix would break this app according to the advisory. I'm a bit of a newbie to spfx so apologies if this is not how I report these issues @hugoabernier 

 Critical        Command Injection

  Package         open

  Dependency of   @microsoft/sp-webpart-workbench [dev]

  Path            @microsoft/sp-webpart-workbench >
                  @microsoft/gulp-core-build-serve > gulp-open > open

  More info       https://npmjs.com/advisories/663

**Comment by hugoabernier** [comment]
Thank you @marting1010 , opening this ticket was the right step! Hopefully someone in the community can take this one on

**Comment by marting1010** [comment]
> Thank you @marting1010 , opening this ticket was the right step! Hopefully someone in the community can take this one on

Phew! Glad I did the right thing! Thank you @hugoabernier

**Comment by narulasrinivas** [comment]
@marting1010  - Can you please provide which node and spfx version you're using in your system?
