### ISSUE TITLE
react-youtube not displaying in browser when "gulp serve" is run

### ISSUE THREAD

**Issue by keedman4** [pnp/sp-dev-fx-webparts#1231]
After i run npm install, i run gulp serve but my browser doesn't display the workbench, rather it displays a message " Can’t connect securely to this page"

![tls](https://user-images.githubusercontent.com/37272357/79682855-a0b37780-821d-11ea-96ad-8a0ae1deb666.PNG)

**Comment by sudharsank** [comment]
Hi @keedman4 Can you please provide us with more info.
* What version of yeoman generator are you using?
* What version of node is installed?
* Is this the first time are you trying to run the SPFx project or it was working previously suddenly you are receiving this issue?

If this is the first time run, try to run the gulp trust-dev-cert to trust the dev certificate and then try to run the gulp serve

**Comment by keedman4** [comment]
@sudharsank , thanks for your response, below are answers to the question you asked

yeoman generator - 3.1.1

node - v10.19.0

This is the first i am trying to to run the SPFx project and it never work

**Comment by sudharsank** [comment]
@keedman4, I suggest you perform the steps mentioned in the below doc before trying out the samples from community. Once you are done with the environment setup and initial testing, it should be fine enough to try out the samples from the community.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
You can also go through the below article on setting up the dev environment using WSL 2 in Windows 10
https://windowssharepointserver.blogspot.com/2020/04/spfx-development-environment-setup.html

Try the above suggesstions and let us know if you have any issues.

**Comment by keedman4** [comment]
@sudharsank, I have tried what you suggested.
Here is an error i get when i run "gulp trust-dev-cert"
![Capture](https://user-images.githubusercontent.com/37272357/81323998-39574d80-908e-11ea-8442-40e5be08d8b6.PNG)

**Comment by hugoabernier** [comment]
Closing this issue as there isn't enough information to help you.

If you're still experiencing this problem, feel free to open a new issue. When you do, please take the time to fill the issue template provided so we can help you better. Information such as author and environment go a long way to route the issue to the right people.
