### ISSUE TITLE
How To Restrict PeoplePicker to show only users of the Site Collection

### ISSUE THREAD

**Issue by nikolayyordanov** [pnp/sp-dev-fx-webparts#1234]
I want to restrict the PeoplePicker to show only users who belong to at least on group in the Site Collection.

Or as a workaround - users who are members of a specific Azure AD group.

**Comment by sudharsank** [comment]
Hi @nikolayyordanov 
Have you tried **Azure Group name** on the **groupName** property of the **PeoplePicker** control?

**Comment by hugoabernier** [comment]
Hey @nikolayyordanov did @sudharsank 's advice help you resolve this issue?

I'll go ahead and close this issue as this issue list is intended for issues related to SPFx web part samples in this repository. If you still need help, feel free to open a new issue in the [sp-dev-docs](https://github.com/sharepoint/sp-dev-docs) where we may be able to help you better. When you do, I encourage you to take the time to fill the issue template provided, as incomplete issues are automatically rejected.
