### ISSUE TITLE
React-Birthday azure function

### ISSUE THREAD

**Issue by NikolaiDeket** [pnp/sp-dev-fx-webparts#1236]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement
- [ ] Sample request

Hello,

I checked the forum out and seems like i found the right forum where i can maybe get a help.

I have issues on syncing data with azure function to sharepoint list.
I've uploaded successfully funtion from vscode to azure function and i think it has also all the access's. Everything works when i fill the list on root list (birthday) manually, so theres no issue's on that side.
![tempsnip](https://user-images.githubusercontent.com/58508704/80069050-585fc680-8549-11ea-9206-ce1448464379.png)

From where i should start the troubleshooting or anyone has some idea what could be wrong?

As i understand to sync data with function app i need to give it permissions on azure and fill out local.settings.json file. Its filled out, unfortunately i cant share it here.

We are using modern sharepoint and everything is in cloud.

![Õigused](https://user-images.githubusercontent.com/58508704/80068778-de2f4200-8548-11ea-8d85-9b28ffd483e2.PNG)

I tried to provide as much information as i can, hopefully its enought.

**Comment by hugoabernier** [comment]
@NikolaiDeket is this an issue related to the react-birthday sample or a general SPFx question?

The original author of this sample is @joaojmendes. Hopefully he may be able to provide some guidance.

**Comment by sudeshkumara** [comment]
Hi @NikolaiDeket..,

Is there any update on this issue? We are facing exactly the same problem. When we fill in the SharePoint root list manually, the birthday web part populates data without any issue. But the Azure function does not seem to update the list.

Have you found any solution for this?
