### ISSUE TITLE
React-Birthday azure function how to debug locally

### ISSUE THREAD

**Issue by priyarane30** [pnp/sp-dev-fx-webparts#1244]
- [x] Question
- [ ] Bug
- [ ] Enhancement
- [ ] Sample request

Hi, 
I created a azure function timer in visual studio code using javascript, and added all provided React-Birthday azure function code in solution. I registered app permission with directory.read and updated .json in solution.But i want to debug solution  locally but i am not aware how to do it.
Please help me .

**Comment by priyarane30** [comment]
since not getting any response closing issue

**Comment by bcameron1231** [comment]
Closing on behalf of request to close.
