### ISSUE TITLE
React-Modern-Charts: Can't display Managed Metadata Value

### ISSUE THREAD

**Issue by tanweeteck** [pnp/sp-dev-fx-webparts#1252]
## Source file:
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-modern-charts

## Solution | Author(s)
react-modern-charts | Jeremy Coleman (MCP, PC Professional, Inc.)

![Chart_Show Object Object](https://user-images.githubusercontent.com/45476945/80348227-106dd600-88a0-11ea-9aed-618c5246341f.JPG)
![Chart_Show Object Object](https://user-images.githubusercontent.com/45476945/80348243-1794e400-88a0-11ea-85f7-adef0060bf0d.JPG)

There are 3 fields (Managed Metadata) created in Opportunity custom list, Client Group, Client Segment and Client Company.
I would like to display the opportunity value based on Client Group.
The React Modern Chart displayed managed metadata with Object Object instead of showing Client Group Name.

## Expected Behavior:
Showing Client Group Name

## Environment details (if applicable)
SharePoint Online (Office 365)

OS: [e.g. Windows 10
Target Environment: SharePoint Online
Framework: Node.js v6/v8/v10/v12
Browser(s): Chrome v79 | Chromium Edge v79
Tooling: VS Code
Additional details: None.

![Chart_Show Object Object](https://user-images.githubusercontent.com/45476945/80348270-1f548880-88a0-11ea-9864-12349728af93.JPG)
![Managed Metadata(Taxanomy)](https://user-images.githubusercontent.com/45476945/80348284-24b1d300-88a0-11ea-9fda-b3a33cfcff29.JPG)

**Comment by tanweeteck** [comment]
@jcoleman-pcprofessional, any clue of correcting the taxanomy field (Managed Metadata) value for displaying name and value?
Thanks.

**Comment by petkir** [comment]
@hugoabernier  please assign this issue to me

**Comment by Swapra** [comment]
Just created another post for new issue of managed metadata fields. 

https://github.com/pnp/sp-dev-fx-webparts/issues/2077

![chart-settings](https://user-images.githubusercontent.com/92086366/137325504-cbc3821e-16d0-4bc2-80a3-808cf1c5f6b4.JPG)
![Pie-chart-error-managed metadata-fields](https://user-images.githubusercontent.com/92086366/137325512-a629db54-066a-4bee-baf3-39b69a71c289.JPG)
