### ISSUE TITLE
Facing Issue in Installing an Spfx Webpart App from Add an App in Site Content in SharePoint 2019 On-Prem 

### ISSUE THREAD

**Issue by AbhishekK2** [pnp/sp-dev-fx-webparts#1254]
Hello All,
I am facing an issue in installing an Spfx Webpart in SharePoint 2019 on prem which I have deployed in App Catalog and also can be seen in Add an App page App Gallery from the Site Contents. I am using this SharePoint 2019 Farm which I have hosted on a Virtual Machine. I have only configured the Application and Search Server. I have all the configuration steps which are required to configure the App Environment.
 
## Expected or Desired Behavior

When I select the App which I have to install so this takes me back to Site Contents page and show me my App in a dimmed/disabled form and after that the App should get highlighted as another list or libraries showing in site contents. 
## Observed Behavior

But when I select the App which I have to install then after selection this takes me back to Site Contents page and there my Spfx Webpart(App) is only showing in dimmed/disabled form and remains as it is. And it never gets installed. The Webpart is also not shown in selection of Webparts Gallery in Page.

Please Let me know what I am missing. 

## Steps to Reproduce
1. Upload an App to App Catalog.
2. Go to Site where you want to install the App.
3. Go to Site Contents.
4. Add an App.
5. Choose the App which you want to add.
6.After choosing, automatically redirects to Site Contents page where it is showing a dimmed App forever and nothing seems to happen after that.

## Expected behavior
The Spfx Webpart (App) should be shown normally without any disabled/dimmed look. And can be added to Site Page.

## Screenshots
![Issue](https://user-images.githubusercontent.com/64418128/80380743-9ba99480-88bd-11ea-9562-b8fb549443d2.png)

**Comment by Harshagracy** [comment]
Hi, If you click the three-dot next to the webpart name, you can see the monitor option

![image](https://user-images.githubusercontent.com/14230498/80457942-bcb9c600-894d-11ea-8d97-0fdc23786e61.png)

it will take you the Appmoniterdetails page - 
![image](https://user-images.githubusercontent.com/14230498/80458085-e8d54700-894d-11ea-88f9-0e81b6d0abab.png)

do you see any error details there? if yes, could you please share it?

**Comment by AbhishekK2** [comment]
Hi @Harshagracy Thanks for your reply. I have checked what you mentioned. There are no Install, Upgrade or Runtime errors. But displaying a warning message for Search service. 

![image](https://user-images.githubusercontent.com/64418128/80460219-27203580-8951-11ea-840e-d807f65572a9.png)
I don't think that the problem is occurring because of this warning.

**Comment by Harshagracy** [comment]
Thanks, @AbhishekK2 for checking.

1. - Are there any feature deployment code written in the webpart?
2. - is the list creation getting failed, post-installation of the webpart?
3. - or are the list/libraries already present in the site?

Also, can you pls try to remove the webpart from the site and try to add it again? before adding the second time, please remove it from all the recycle bin(including admin recycle bin) so that we make sure there is no version conflict?

**Comment by AbhishekK2** [comment]
@Harshagracy Thanks for the information. As you mentioned the above points.
For Point 1, I have not added or changed any code for the webpart. I have followed this blog https://www.c-sharpcorner.com/article/spfx-with-sharepoint-2019/
This is a demo webpart.
For Point 2, I do not know how to check whether the list is getting created or not.
For Point 3, As the Site which I created is a New site so there will be no old list/libraries present.
And also as you have said to remove and re-add the webpart from site. But the webpart is not fully installed so I cannot remove it. And also I have tried to uploaded new webpart in the App Catalog. But then also same issue. For more information as I switch the Site content page from Modern Experience to Classic Experience so then the Webpart is shown as
![image](https://user-images.githubusercontent.com/64418128/80469096-b895a480-895d-11ea-834e-54c1b4fdd7f8.png)
But nothing is happening.

**Comment by rquanx** [comment]
Same  issue.

I developed the SPFX Webpart last year and deployed it normally,but recently it cannot be added to the website.

I also tried to create a new part and couldn't add it.

**Environmental information**: ```Windows Service 2016 Standard```、```SP2019```

![image](https://user-images.githubusercontent.com/36622981/82516789-407e6100-9b4e-11ea-8fa2-e10d31643a5a.png)



Add and remove are not available
![image](https://user-images.githubusercontent.com/36622981/82517893-b84d8b00-9b50-11ea-9c50-e33596c3200e.png)



Installed in may 
![image](https://user-images.githubusercontent.com/36622981/82517952-d3b89600-9b50-11ea-8e51-f8c274d24398.png)

![image](https://user-images.githubusercontent.com/36622981/82517992-e632cf80-9b50-11ea-9af8-aaf938eee07c.png)



Installed today
![image](https://user-images.githubusercontent.com/36622981/82518260-8f79c580-9b51-11ea-87af-5845cc1b49f3.png)


**Project  Info**
```npm -v @microsoft/generator-sharepoint```: 6.4.1

package.json
```json
{
  "name": "document-search",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test",
    "bundle": "gulp bundle --ship",
    "package": "gulp package-solution --ship",
    "new" : "yo @microsoft/sharepoint"
  },
  "dependencies": {
    "@microsoft/decorators": "~1.4.0",
    "@microsoft/sp-application-base": "~1.4.0",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-dialog": "~1.4.0",
    "@types/es6-promise": "0.0.33",
    "@types/node": "^14.0.4",
    "@types/webpack-env": "1.13.1",
    "file-saver": "^2.0.2",
    "jszip": "^3.2.1",
    "jszip-utils": "^0.0.2",
    "rc-notification": "^3.3.1",
    "typescript": "^3.9.3"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "terser-webpack-plugin-legacy": "1.2.3",
    "webpack-merge": "4.2.1"
  }
}
```

.yo-rc.json
```json
{
  "@microsoft/generator-sharepoint": {
    "isCreatingSolution": true,
    "environment": "onprem19",
    "version": "1.8.2",
    "libraryName": "document-search",
    "libraryId": "4ca383dd-35dc-413f-95bc-a7e07945368d",
    "packageManager": "npm",
    "componentType": "extension",
    "extensionType": "ApplicationCustomizer"
  }
}
```

**Comment by rquanx** [comment]
@Harshagracy

**Comment by hugoabernier** [comment]
@AbhishekK2 this issue list is intended for issues related to web part samples in this repository.

Did you try to reboot the server as per #5786?

If you still need help with this issue, I recommend you open a new one at  https://aka.ms/spdev-issues where we can hopefully help you better.
