### ISSUE TITLE
Can I use the Modern Script Editor in Communication Sites?

### ISSUE THREAD

**Issue by arctouch-joseclua** [pnp/sp-dev-fx-webparts#1255]
I was able to deploy and successfully use the Modern Script Editor (react-script-editor) in Team Sites.

in Communication Sites I can add the web part in the app contents page but the web part does not appear when I try to add it on a page.

Is it possible to use this web part in communication sites?

Thanks

**Comment by Harshagracy** [comment]
hi @arctouch-joseclua , Can you please check if this comment helps you?

> https://github.com/SharePoint/sp-dev-fx-webparts/issues/660#issuecomment-438787547

**Comment by cluckinchicken** [comment]
I've had some communication sites where I can add the web part, but others I cannot.  Can't figure the rhyme or reason for when it works and when it doesn't.

I looked at the comment above, but I don't have a config/tslint.json so ???
