### ISSUE TITLE
Script Content is not login for User having Read access to page

### ISSUE THREAD

**Issue by anandkumar0289** [pnp/sp-dev-fx-webparts#1275]
I have added this webpart to one page and added simple alert inside script tag
It is working fine for all user having edit permission
But user having Read or Visitor permission it is not throwing error
I am suspecting this is something to do with user permission.

let me know what condition i should change to make it working for all users

**Comment by Harshagracy** [comment]
@hugoabernier : This is a duplicate issue of #1276

**Comment by anandkumar0289** [comment]
I tried some alternate way and it is working. thanks
