### ISSUE TITLE
Read access user not able to see the content of this script editor

### ISSUE THREAD

**Issue by anandkumar0289** [pnp/sp-dev-fx-webparts#1276]
Hi,
I need help regarding SPFx react editor webpart.
This might not be issue with the webpart you have created
sp-dev-fx-webparts/samples/react-script-editor

But it will be great helpful if you can help me here.

Issue: User having Read only permission not able to see the content that i have added in react script editor webpart. User having higher access able to see the content.

**Comment by Harshagracy** [comment]
Hi @anandkumar0289 , did you check if the script you added is blocking the permission? because the script editor webpart only loads the script. It will not do anything based on users permission. 

Also, it would be great, if you could share the script to help you :)

**Comment by anandkumar0289** [comment]
I fixed the issue thanks for help
