### ISSUE TITLE
Is there a way of uploading a link to document to a document library?

### ISSUE THREAD

**Issue by SaraKlein** [pnp/sp-dev-fx-webparts#1279]
react-file-upload

I am using the react-file-upload web part in one of my projects and it works very well.
I want to use it in another project but in that one I have a requirement to enable also uploads of link to document (using that content type). I tried uploading them like I've uploaded it in a different project using javasript - it didn't work properly here. It created the item in the dcument library but didn't create it as a link.
Is there a way of doing this? 

Thanks.

**Comment by hugoabernier** [comment]
Closing this issue as incomplete. Feel free to open a new issue and fill the issue template that's provided so that we can help you accordingly.

Please note that sample authors do not get automatically notified unless you follow the template. 

Thanks for your understanding
