### ISSUE TITLE
Is there a way/example to bring Github Issues into SPFx webpart?

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1281]
I had an idea for a webpart that would benefit from being able to read issues from a github repo... ie use an API to get information.

Is there an example somewhere that has done this?

Just not sure where to start.

Thanks!

**Comment by hugoabernier** [comment]
@mikezimm if you look at the [GitHub Badge](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-github-badge) sample, you'll see a similar concept.

Also, if you look at the [Chart control](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-chartcontrol/) mega-sample, you'll see that there is a [GitHub service](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-chartcontrol/src/services/GitHubService) -- designed to load contributors to a repo, but you could easily change it to load issues.

In that same sample, the GitHub contributors web part shows what we do with the data:
![image](https://user-images.githubusercontent.com/13972467/81965951-c77b8880-95e6-11ea-83b2-d42affe13743.png)

I hope this helps?

**Comment by mikezimm** [comment]
Thanks for the suggestion Hugo!

I think if you want, please close the issue.  I think I have a thread to start with and will just ask a new question if I need some more help.

Appreciate all your efforts!
