### ISSUE TITLE
Include VSCode remote/codespace configuration in repository

### ISSUE THREAD

**Issue by pschaeflein** [pnp/sp-dev-fx-webparts#1282]
## Sample

Entire repo

## Authors

@hugoabernier 

## Expected or Desired Behavior

Visual Studio Codespaces provides for configuring an environment using files in the referenced repository. I believe it would be help to configure this repo. The steps are document on my blog at https://www.schaeflein.net/using-visual-studio-codespaces-for-spfx-development/.

If approved, I am happy to have this issue assigned to me.

**Comment by hugoabernier** [comment]
Hey @pschaeflein how would you feel about adding instructions how to open the samples in VS Codespaces in the documentation for aka.ms/spfx-webparts? 

If you add the `.MD` file in `https://github.com/pnp/sp-dev-fx-webparts/tree/Docs/docs/gettingstarted`, I can make sure it shows up in the documentation. Just make sure to target the `Docs` branch.

**Comment by pschaeflein** [comment]
Well, the steps are already documented in the referenced blog post. I feel the benefit would be to have the repo already configured with the .devcontainer folder.

**Comment by hugoabernier** [comment]
@pschaeflein do you want to set one up as a sample and do a pull request? I'm not having much luck setting up codespaces on my side.

**Comment by andrewconnell** [comment]
IMHO... 

I would only add this as docs... not implementing on the samples individually or on the project as a whole.

Samples are used for references... stuff like this can confuse what is required for samples vs. what's "extra for a sample setup".

Also... what about the debate "why would I use VS Codespaces vs. GitHub Codespaces?"

My $0.02: don't add this to the repo... add docs at most.

**Comment by hugoabernier** [comment]
Closing this issue as codespaces will be retired. Let's revisit when fully transitioned to GitHub  codespaces.

**Comment by andrewconnell** [comment]
[Codespaces is already going to be retired](https://www.neowin.net/news/microsoft-is-retiring-visual-studio-codespaces-users-being-migrated-to-github-codespaces) after being announced just a few months ago?!?!?!

![](https://media.giphy.com/media/RgtzODxYuGIes/giphy.gif)

**Comment by pschaeflein** [comment]
"Retiring" is click-bait used at the reference site.

If you read the official blog post (https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), you will see that Codespaces are alive and well, and will be hosted under the GitHub service only.

The VSCode extension, (and the future Visual Studio extension) will work the same. And I would argue that a button on the GH Repo to create/launch a codespace is much simplier than filling out a form (as was done on the online.visualstudio.com site).

The only difference is the billing. Instead of Azure subscription, it will likely be slotted into GitHub tiers.
