### ISSUE TITLE
Theme Manager 2019 - no action occurs when execute apply

### ISSUE THREAD

**Issue by haticapp** [pnp/sp-dev-fx-webparts#1286]
##  Sample
js-theme-manager-2019

## Authors 
@PopWarner 
@bcameron1231 

## Expected or Desired Behavior
Applying the new the to the site

## Observed Behavior

After intalling installing the webpart on my sharepoint server 2019, and add the webpart to the homepage of a team site I'm unable to get any action when I click the apply theme button,.

## Additional context
Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
In order to help you, we'll need more detail information.

Please try again and take the time to fill the issue template.
