### ISSUE TITLE
react-kanban-board dont work properly on IE. Locked on "Loading tasks"

### ISSUE THREAD

**Issue by ewidance** [pnp/sp-dev-fx-webparts#1288]
## Authors

@westerdaled 
@RamPrasadMeenavalli 

A working kanban on most navigators.

## Observed Behavior

Internet explorer 11 (tested on 11.836.18362.0 / 11.0.190) can't load  kanban webpart deployed on a sharepoint tenant. IE is blocked on "Loading Tasks". 

Works fine on FF, Chrome and Edge.

## Steps to Reproduce
- npm install
- gulp bundle --ship
- gulp package-solution --ship
- Deploy solution on tenant.
- Load IE and insert a kanban on the page, connect it to a task list and save.
- Kankan tasks will not be displayed.

# Environment Details (*Development & Target environment*)
- Sharepoint Online
-  Windows 10 Pro 64 latest with All navigator updated to latests versions.

**Comment by hugoabernier** [comment]
@ewidance the authors of this sample are @westerdaled and @RamPrasadMeenavalli. Hopefully they can help you.

**Comment by petkir** [comment]
Hi @ewidance,

I have taken a look at **react-kanban-board**.
there are 2 problems with IE11
One can be easily fixed some polyfills are missing
_npm install @pnp/polyfill-ie11 --save_
KanbanBoardWebPart.ts add _import "@pnp/polyfill-ie11";_

The second problem is not so easy to fix, because the component used in this webpart solution, does not work in my IE11 Browser.
Link from external component demo page:
https://www.jqwidgets.com/react/react-kanban/react-kanban-kanbanevents.htm

The jQkanban component (for Javascript/jQuery or Angular or Vue) works great in IE11.

**Comment by westerdaled** [comment]
@ewidance thanks for looking at this. Are you advocating swapping out the existing component for the JQkanban component?

**Comment by ewidance** [comment]
Yes, that sould be great! I confirm react-canban dont work on IE11, and even with polyfill, demo still don't work. JQkanban Seems to work fine (tested on https://www.jqwidgets.com/angular/angular-kanban/#https://www.jqwidgets.com/angular/angular-kanban/angular-kanban-defaultfunctionality.htm works fine on IE.

**Comment by westerdaled** [comment]
@ewidance  Unfortunately, their React version version does not  work in IE [https://www.jqwidgets.com/react/react-kanban/index.htm#https://www.jqwidgets.com/react/react-kanban/react-kanban-defaultfunctionality.htm](https://www.jqwidgets.com/react/react-kanban/index.htm#https://www.jqwidgets.com/react/react-kanban/react-kanban-defaultfunctionality.htm) .  Anyone up for doing this Angular - I am heading for the door😐!

**Comment by petkir** [comment]
@westerdaled do you like to change this? Or should i charge the react component to jquery or angular component?

**Comment by westerdaled** [comment]
@petkir  Please go ahead. I guess jQuery has wider appeal than say Angular ( even AC has stopped promoting it).

**Comment by hugoabernier** [comment]
@westerdaled and @petkir Would it make sense to look into something that does not have any licenses associated to it? Keep in mind that all our samples are MIT licensed, but while jqWidgets has an open license for open-source projects, it would require anyone using this in their commercial environments to acquire licenses for jqWidgets.

I'd even be happy to collaborate on a full Office UI version with you.

And yes, we can make it support IE.

**Comment by westerdaled** [comment]
Hi @hugoabernier .
Is see what you mean . So you are advocating rolling our own office fabric react Kanban component?
If so,  this woud be a great learning excercise.  Depending how much work iis involved,  also make it able to render Planner ( and or ToDo)  tasks  with a property switch.

**Comment by hugoabernier** [comment]
@westerdaled maybe I'm biased,  but I believe that all SharePoint web parts should look and feel like SharePoint -- including support for themes and section backgrounds. And all samples in this repo should not require additional licenses. 

If there is another open-source react- based library that supports IE and provides full support for customizing look and field, we should use it... if not, it would definitely be fun to do our own, and definitely a great learning experience for everyone -- not just the authors. 

I'm happy to work on it, but don't want to steal anyone's thunder. Maybe worth a collaboration?

**Comment by ewidance** [comment]
Unfortulately, Sharepoint people **HAS TO** use IE until Microsoft will raise Edge to the same functionnality level. When working with Sharepoint, unfortunately only IE allow opening document list in explorer, proper connexion to excel, word and powerpoint files, proper copy/paste on a quick edit and much more....

**Comment by petkir** [comment]
Hi 

@hugoabernier I understand your point and it's ok, I haven't looked for the component licenses.
@westerdaled in my opinion first goal should be the SharePoint Tasks-List and IE11 :)  I'm a big fan of small steps. 

After I read your posts I was thinking about it. 
Fluent UI Components usage in a Kanban Component ... sounds good in my ears

> I'm happy to work on it, but don't want to steal anyone's thunder. Maybe worth a collaboration?

Why not?

[I pushed my first idea in a brunch](https://github.com/petkir/sp-dev-fx-webparts/tree/petkir-IE11Support-1288/samples/react-kanban-board/src/kanban)

**Comment by RamPrasadMeenavalli** [comment]
I like @hugoabernier 's idea of making it more SharePointy.
When I was initially developing this sample, I looked for some libraries which support customizing the UI. There are few libraries which allow that, but only to some extent. I found react-dnd (https://github.com/react-dnd/react-dnd) has many customization options possible. But I had issues using that in IE11.

On a different note, the most scary requirement I hear is "support for IE" :)

**Comment by petkir** [comment]
Hi @RamPrasadMeenavalli 
> When I was initially developing this sample, I looked for some libraries which support customizing the UI. There are few libraries which allow that but only to some extent. I found react-dnd (https://github.com/react-dnd/react-dnd) has many customization options possible. But I had issues using that in IE11.

after some hours playing around with Drag events I know why 
``` event.dataTransfer.setData```  allows only ```'text'``` and the value has to be also a ```string```
[MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/getData)

> On a different note, the most scary requirement I hear is "support for IE" :)

It's sometimes a challenge, but it's a common requirement [Browser Support](https://support.microsoft.com/en-ie/office/which-browsers-work-with-office-for-the-web-ad1303e0-a318-47aa-b409-d3a5eb44e452?ui=en-us&rs=en-ie&ad=ie)

@ewidance @westerdaled  @RamPrasadMeenavalli 
I have rewritten the Control without any 3rd party lib. 
UX of the Kanban Control is not finished, but the functionality.
It works in **my** IE (It works on my Maschine)
Source:
https://github.com/petkir/sp-dev-fx-webparts/tree/petkir-IE11Support-1288/samples/react-kanban-board
![kanban](https://user-images.githubusercontent.com/13123689/85338621-ee30b700-b4e2-11ea-9e39-4bf32b3aa424.gif)

Please give me Feedback

**Comment by westerdaled** [comment]
Wow , that looks impressive. Good use of reusable controls too.   Were you able to add fluent framework support ( not sure if that is in prevew yet ).

**Comment by petkir** [comment]
> Wow , that looks impressive. Good use of reusable controls too. Were you able to add fluent framework support ( not sure if that is in prevew yet ).

Hi @westerdaled , yes it's possible. 
[Fluet UI](https://developer.microsoft.com/en-us/fluentui#/)

Currently, it's React 16 and office-ui-fabric 6. 
SharePoint 2019 it's React 15 and office-ui-fabric 5. Iwas  think about downgrade this project to Support 2019, what's your opinion? cloud-only or also on-premise support?

**Comment by westerdaled** [comment]
Personally, I would be looking forward and not backwards unless there data to back up real high demand for  [SharePoint 2019 support ](https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.7-release-notes#2019-support)/ .

**Comment by petkir** [comment]
Thanks for your Inputs

@westerdaled I let it stay at ' office-UI-fabric 6'. I'm not sure about Fluent Ui (Fabric 7) support in SharePoint.

@RamPrasadMeenavalli @ewidance @westerdaled  @hugoabernier  can you take a look over the functionality and documentation, before I make a Pull-Request.  Every kind of feedback is welcome!

https://github.com/petkir/sp-dev-fx-webparts/tree/petkir-IE11Support-1288/samples/react-kanban-board

**Comment by westerdaled** [comment]
I guess fluentui could be added in the next release .   _Note. the fluent UI  sample React Starter App in the link you provided, won''t even build with a known [jest issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44714#issuecomment-650633787)._

Not sure how much I can add as I'm still learning React .  I did notice the link in the readme is invalid. 

[Read More about the implementation of this Board](https://github.com/petkir/sp-dev-fx-webparts/blob/petkir-IE11Support-1288/samples/react-kanban-board/src/kanban/Readme.md)

I would be very interested in how you went about designing the KanbanBoard component whilst still ensuring that it has IE11 support - a podcast or blog post or whatever,
