### ISSUE TITLE
Can't display react-accordion

### ISSUE THREAD

**Issue by S-kay84** [pnp/sp-dev-fx-webparts#1290]
react-accordion

@hugoabernier 

## Question
I have followed the guidelines and created a custom list and ran react-accordion in our workbench. When I add the webpart it shows 'Ready' instead of listing the content. Why would it not be showing the list items? Should there be a dropdown for me to pick which list it displays?

**Comment by hugoabernier** [comment]
@S-kay84 i didn't write the sample,  but looking at the code, you should use the property pane to set the list you wish to use.

You can get to the property pane through the edit button on the left of the web part. 

I hope this helps?

**Comment by S-kay84** [comment]
Thank you, my mistake the author is @gautamdsheth 
I have tried setting the list in the property pane but it still didn't show the contents and not really sure where else to look. I'm pretty sure the list is set up correctly and it has content.

**Comment by gautamdsheth** [comment]
Hello @S-kay84 , in the list that you created, you also need to create a `Description` column. It will be of type multiline - Enhanced rich text. After that, you can create list item and populate the list. It should show the list items. 

Additionally, if it still doesn't work, can you check the browser console for any errors, maybe that can help us identify the issue ?
