### ISSUE TITLE
React Content Query Online PageFieldValue query string support

### ISSUE THREAD

**Issue by parmira5** [pnp/sp-dev-fx-webparts#1291]
## Sample
React Content Query WP (Online)

## Authors
@PopWarner 
@hugoabernier 
@PaoloPia 

## Question

Is the PageFieldValue query string expression supported? Can't seem to get it to work. Thanks.

**Comment by ValerasNarbutas** [comment]
@hugoabernier  i can check this.

**Comment by hugoabernier** [comment]
@ValerasNarbutas I've assigned you to this. Thanks for your help!

**Comment by ValerasNarbutas** [comment]
hi @parmira5 ,
id does work for me.
my set up in filter - 
![image](https://user-images.githubusercontent.com/16476453/86758415-86cf4700-c04c-11ea-93f2-6dc3a4372a07.png)

Inpage URL I have ?**itemId**=1 itemId is parameter. result:
![image](https://user-images.githubusercontent.com/16476453/86758650-ae261400-c04c-11ea-9b51-4bf1cfbe127a.png)

@hugoabernier looks like working as expected.

**Comment by JohnMoor** [comment]
I also tested and found that filtering on [PageQueryString] is working, but didn't get the [PageFieldValue:<propertyname>] to work.

@BrinaD1 did you manage to find a solution?

**Comment by xdogoxd** [comment]
PageFieldValue indeed does not work. debugging shows that it sends the entire expression [PageFieldValue:FieldName] as text in the query. is there any workaround?
