### ISSUE TITLE
Getting "Something Went Wrong error" for Other users except Site Collection Admin Who Added the WebPart

### ISSUE THREAD

**Issue by KattaRajendra** [pnp/sp-dev-fx-webparts#1295]
HI,
I have added basic Welcome Message in the Modern Script Editor Web part in SharePoint Online Modern Site Page. It is working fine for Site Admin Who is created. But When I tried to load the same page with Other Users (Site Owners, Members, Visitors, Even Site Admins) I am getting below error message:

**"Something went wrong"**
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "3a328f0a-99c4-4b28-95ab-fe0847f657a3" (ScriptEditorWebPart). Original error: Failed to load entry point from component "3a328f0a-99c4-4b28-95ab-fe0847f657a3" (ScriptEditorWebPart). Original error: Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_1.0.0
http://requirejs.org/docs/errors.html#scripterror

INNERERROR:
Failed to load entry point from component "3a328f0a-99c4-4b28-95ab-fe0847f657a3" (ScriptEditorWebPart). Original error: Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_1.0.0
http://requirejs.org/docs/errors.html#scripterror
CALLSTACK:
Error
    at r.t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c5b6b2a9a7d83a840441a5da7bb3274f.js:1:868365)
    at new r (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c5b6b2a9a7d83a840441a5da7bb3274f.js:1:1220742)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c5b6b2a9a7d83a840441a5da7bb3274f.js:1:1277337)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c5b6b2a9a7d83a840441a5da7bb3274f.js:1:1273370)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c5b6b2a9a7d83a840441a5da7bb3274f.js:1:1266922

![error](https://user-images.githubusercontent.com/66011218/83010803-759b1f80-a036-11ea-955e-6c4ef91d20dd.JPG)

**Comment by hugoabernier** [comment]
Closing this issue as incomplete. Feel free to open a new issue and use the issue template provided.

Please note that sample authors do not get notified of issues unless you fill the issue template, greatly reducing your chances of getting help.

Thanks for your understanding.
