### ISSUE TITLE
Let's make react-my-groups even better

### ISSUE THREAD

**Issue by ekstam** [pnp/sp-dev-fx-webparts#1303]
Sample (which sample are you talking about)
react-my-groups

## Authors
@zachroberts8668 @LauraKokkarinen 

## Suggestion (the more details, the better)
For me as a beginner in GIT as well as creating/compiling sppkg-packages I struggled a bit to get react-my-groups to connect to Graph API before realizing that I had to specify the desired access my self. 

Is it a good idea to add these lines to "package-solution.json", because that's what got me over the "bump":
`"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      },
	  {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      }
    ]`

My version of package-solution.json:
`{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "react-my-groups-client-side-solution",
    "id": "f059557f-c4d2-4eaa-9f8d-3c5d97dbb576",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
	"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      },
	  {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/react-my-groups.sppkg"
  }
}`

**Comment by zachroberts8668** [comment]
Hello @ekstam ,

Good catch, not sure if those were missed when I published the first time, must've forgot to make a push. I will get this updated for that change, I also have some updates that are coming to this webpart soon 😊

Thanks,
Zach

**Comment by ekstam** [comment]
> Hello @ekstam ,
> 
> Good catch, not sure if those were missed when I published the first time, must've forgot to make a push. I will get this updated for that change, I also have some updates that are coming to this webpart soon 😊
> 
> Thanks,
> Zach

Nice! I got it to work for now but a "nice to have" would be some design-options if that's possible :) I'll keep myself updated regarding your webpart, it really filled a gap in the current SharePoint build I'm setting up! Thanks!

**Comment by zachroberts8668** [comment]
> > Hello @ekstam ,
> > Good catch, not sure if those were missed when I published the first time, must've forgot to make a push. I will get this updated for that change, I also have some updates that are coming to this webpart soon 😊
> > Thanks,
> > Zach
> 
> Nice! I got it to work for now but a "nice to have" would be some design-options if that's possible :) I'll keep myself updated regarding your webpart, it really filled a gap in the current SharePoint build I'm setting up! Thanks!

@ekstam ,
Ok just made a pull request to add those changes! Yeah I was planning on adding some different visual views that could be configured. What 'nice to have' options were you looking for? I can certainly look into implementing them in my update to this webpart.

**Comment by ekstam** [comment]
@zachroberts8668 ,
If I just could wish for what ever feature I want and then just have you implement it I would probably go for this:  😊

1. Have the div "styles.reactMyGroups" in "ReactMyGroups.tsx" set to 
`span role="heading" aria-level="2"` instead of `<H1>` and be able to set the headline from within SharePoint after deployment instead of having it hard coded into the webpart ("My Office 365 Groups"). <-- I really don't know if I get my point across here, my coding skills are limited and my terminology may very well be of by a mile here! 

![github2](https://user-images.githubusercontent.com/58424442/83563391-57905c00-a51b-11ea-891d-180ed820713d.png)

As of now, I just worked around the problem and removed the headline and placed a image beside the webpart to get it integrated into the overall design of the site I'm currently working on, and that sort of works.. (It's in Swedish and says "My Websites") 😊

![github6](https://user-images.githubusercontent.com/58424442/83564002-50b61900-a51c-11ea-8cde-f91a41f75785.png)

2. It would be really nice to be able to change the layout from "Compact" to something else, right now I just wish that I could change to "Grid" instead, but it's really nice that I'm able to show anything right now and for that; I'm greatful! 😊

![github5](https://user-images.githubusercontent.com/58424442/83563742-d9808500-a51b-11ea-9ccd-5affff717139.png)
![github1](https://user-images.githubusercontent.com/58424442/83563758-deddcf80-a51b-11ea-8114-a4e5f9f4acd7.png)

**Comment by hugoabernier** [comment]
@zachroberts8668 and @ekstam , I have created controls to make it easy to implement compact, grid, and filmstrip views that you can borrow from my samples. Take a look at the react-calendar-feed sample to get started, but I can point you to other samples in other repos that can help.

Feel free to DM me for more info.

Let's talk!

**Comment by zachroberts8668** [comment]
> @zachroberts8668 and @ekstam , I have created controls to make it easy to implement compact, grid, and filmstrip views that you can borrow from my samples. Take a look at the react-calendar-feed sample to get started, but I can point you to other samples in other repos that can help.
> 
> Feel free to DM me for more info.
> 
> Let's talk!

That's awesome! I'll check that out 😊,
Thanks for the help @hugoabernier 

@ekstam , with the help from Hugo I should be able to get this updated soon, stay tuned 😊

**Comment by ekstam** [comment]
> > @zachroberts8668 and @ekstam , I have created controls to make it easy to implement compact, grid, and filmstrip views that you can borrow from my samples. Take a look at the react-calendar-feed sample to get started, but I can point you to other samples in other repos that can help.
> > Feel free to DM me for more info.
> > Let's talk!
> 
> That's awesome! I'll check that out 😊,
> Thanks for the help @hugoabernier
> 
> @ekstam , with the help from Hugo I should be able to get this updated soon, stay tuned 😊

Cool! I'll keep myself posted! 😜👍

**Comment by zachroberts8668** [comment]
> > > @zachroberts8668 and @ekstam , I have created controls to make it easy to implement compact, grid, and filmstrip views that you can borrow from my samples. Take a look at the react-calendar-feed sample to get started, but I can point you to other samples in other repos that can help.
> > > Feel free to DM me for more info.
> > > Let's talk!
> > 
> > 
> > That's awesome! I'll check that out 😊,
> > Thanks for the help @hugoabernier
> > @ekstam , with the help from Hugo I should be able to get this updated soon, stay tuned 😊
> 
> Cool! I'll keep myself posted! 😜👍

@ekstam , Sorry for the delay but I just created a pull request to get that grid layout implemented in this webpart, I also cleaned up the compact layout a bit. Wasn't quite sure on how to get the recent activity for a site (still looking into this) but didn't want to hold it up any longer 😊

**Comment by ekstam** [comment]
> > > > @zachroberts8668 and @ekstam , I have created controls to make it easy to implement compact, grid, and filmstrip views that you can borrow from my samples. Take a look at the react-calendar-feed sample to get started, but I can point you to other samples in other repos that can help.
> > > > Feel free to DM me for more info.
> > > > Let's talk!
> > > 
> > > 
> > > That's awesome! I'll check that out 😊,
> > > Thanks for the help @hugoabernier
> > > @ekstam , with the help from Hugo I should be able to get this updated soon, stay tuned 😊
> > 
> > 
> > Cool! I'll keep myself posted! 😜👍
> 
> @ekstam , Sorry for the delay but I just created a pull request to get that grid layout implemented in this webpart, I also cleaned up the compact layout a bit. Wasn't quite sure on how to get the recent activity for a site (still looking into this) but didn't want to hold it up any longer 😊

Oh! Cool! 🙂
I'm currently on vacation but I'll look into this as soon as I'm back at work! 😋👍

**Comment by ekstam** [comment]
> > > > @zachroberts8668 and @ekstam , I have created controls to make it easy to implement compact, grid, and filmstrip views that you can borrow from my samples. Take a look at the react-calendar-feed sample to get started, but I can point you to other samples in other repos that can help.
> > > > Feel free to DM me for more info.
> > > > Let's talk!
> > > 
> > > 
> > > That's awesome! I'll check that out 😊,
> > > Thanks for the help @hugoabernier
> > > @ekstam , with the help from Hugo I should be able to get this updated soon, stay tuned 😊
> > 
> > 
> > Cool! I'll keep myself posted! 😜👍
> 
> @ekstam , Sorry for the delay but I just created a pull request to get that grid layout implemented in this webpart, I also cleaned up the compact layout a bit. Wasn't quite sure on how to get the recent activity for a site (still looking into this) but didn't want to hold it up any longer 😊

@zachroberts8668 Thanks for your work with this! Great job! It works just as I intended now! 👍
