### ISSUE TITLE
Do we need  any permission for the webpart(react-taxonomypicker) to access the term store

### ISSUE THREAD

**Issue by RubenHerrera86** [pnp/sp-dev-fx-webparts#1306]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    npm -v    6.14.4     ]

Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

Hello, 

I downloaded the samples(sp-dev-fx-webparts-master) and I'm checking this sample: react-taxonomypicker, because  I'm interested in use taxonomy picker for some react forms.

So I'm able to open the sample in VS code and I updated the term set id as below:

protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTaxonomyPicker("Language", {
                  key: "Language_Field",
                  name: "Language",
                  displayName: "Language",
                  multi: true,
                  termSetGuid: "**1f016867-6b8b-4f95-8e47-f2c8ec7b2d00**",
               
Then I was able to run the sample with below commands:

- npm install
- gulp serve
- go to https://mydevtenant.sharepoint.com/_layouts/15/workbench.aspx and i can see the webpart but it's not showing any term set.

My question is: Do we need  any permission for the webpart to access the term store?

Here a screenshot for my term store:
![image](https://user-images.githubusercontent.com/65619346/83574207-9fe75400-a4f2-11ea-9c70-c153f3465c4f.png)

Thank you so much for your help!!!!

**Comment by RubenHerrera86** [comment]
Hello,

I also tried with Taxonomy picker but still unable to access to terms. 

Below taxonomy piker url and the code used on render method:

https://pnp.github.io/sp-dev-fx-controls-react/controls/TaxonomyPicker

<TaxonomyPicker allowMultipleSelections={false}  termsetNameOrID="1f016867-6b8b-4f95-8e47-f2c8ec7b2d00"
              panelTitle="Select City"
              label="TaxonomyPicker"
              context={this.props.context}
              onChange={this._onTaxPickerChange}
              isTermSetSelectable={false} />

**Comment by petkir** [comment]
Hi @RubenHerrera86,

Thank you for making a Screenshot of your TermStore with the TermSet I marked with A it works like expected. with your React code
![image](https://user-images.githubusercontent.com/13123689/84188866-903cb200-aa94-11ea-9c26-c8edd3a6f3cd.png)
at the control documentation page, I found the Property anchorId this can help you
```
<TaxonomyPicker allowMultipleSelections={false} 
              termsetNameOrID="c8952ad4-42c7-42eb-8ea7-43073b365fe5"
              anchorId="42f9b542-d3d4-476a-8b20-17ebaf263bc4"
              panelTitle="Select City"  label="TaxonomyPicker" context={this.props.context} 
              onChange={this.onTaxPickerChange.bind(this)}
              isTermSetSelectable={true} />
```
termsetNameOrID="c8952ad4-42c7-42eb-8ea7-43073b365fe5" **Political Geography**
anchorId="42f9b542-d3d4-476a-8b20-17ebaf263bc4" **City**

![image](https://user-images.githubusercontent.com/13123689/84190018-81ef9580-aa96-11ea-89ab-3a44b5d8a964.png)

I hope this helps you

**Comment by hugoabernier** [comment]
@RubenHerrera86 did @petkir 's suggestion help you solve your issue?

**Comment by RubenHerrera86** [comment]
Wow!!!!!! It's working!!!!!!!!!!!!!!

so thankfully with you guys!!!!!!

here my updated code with your code changes!!!

<TaxonomyPicker allowMultipleSelections={false} 
              termsetNameOrID="4f5e7b8b-2a7d-4e93-a0f0-411de8c24e51"
              anchorId="1f016867-6b8b-4f95-8e47-f2c8ec7b2d00"
              panelTitle="Select City"
              label="City"
              //initialValues={this.state.selectedTerms}
              context={this.props.context}
              onChange={this._onTaxPickerChange}
              isTermSetSelectable={false} />

**Comment by hugoabernier** [comment]
@RubenHerrera86 I'm glad you were able to resolve the issue!

Thanks @petkir for your help!
