### ISSUE TITLE
js-workbench-customizer Full Width option

### ISSUE THREAD

**Issue by thomasberman** [pnp/sp-dev-fx-webparts#1308]
## Sample (which sample are you talking about)

js-workbench-customizer

## Authors

@joelfmrodrigues 

## Suggestion (the more details, the better)

Hi Joel, can you think of any way we could mimic a "full-width column" using the workbench customizer? Maybe another CSS override that you can toggle on and off in the web part settings?

**Comment by joelfmrodrigues** [comment]
Hi @thomasberman 
I never looked into that before, but it definitely is a good suggestion for improvement. Will have a look and let you know about my findings.

**Comment by joelfmrodrigues** [comment]
@thomasberman I think I found a way to do this.
Any chance you could try the version on [this dev branch of my fork](https://github.com/joelfmrodrigues/sp-dev-fx-webparts/tree/workbench-full-width) and provide feedback?

I added a new web part property to enable full-width mode (disabled by default). Let me know if you find any issues testing it.

![image](https://user-images.githubusercontent.com/19577724/83696636-dd340a80-a5f4-11ea-9fad-7b4f8b96c6ae.png)
