### ISSUE TITLE
js-modern-calendar external CDN reference issue

### ISSUE THREAD

**Issue by SmitaNachan** [pnp/sp-dev-fx-webparts#1310]
## Authors
@jcoleman-pcprofessional 

## Expected or Desired Behavior
The web part should display the modern calendar view after deployment to app catalog. It works fine on local workbench, but not when deployed to tenant app catalog.

## Observed Behavior
Web part when deployed refers to some CDN location for theme and errors out.
![error](https://user-images.githubusercontent.com/65232102/83759524-49fce280-a691-11ea-9dba-88cc02fb3cc2.png)

## Steps to Reproduce

1. package the solution as .sppkg.
2. Add sppkg to tenant level app catalog. 
3. Add the app to site.
4. Add "Modern calendar" web part on the page.

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8 and v10
- **Browser(s)**: Chrome v79 | Edge 
- **Tooling**: VS Code | SPFx v1.6.0

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
I can look in to this bug.
