### ISSUE TITLE
React-script-editor: Script src files are not loaded when inside div containers

### ISSUE THREAD

**Issue by stmccartney** [pnp/sp-dev-fx-webparts#1325]
## Sample
react-script-editor

## Authors 
@wobba 

## Expected or Desired Behavior
Source files within a script tag should be loaded regardless of where they are in the DOM

## Observed Behavior
When inside a div tag, source files are not loaded by the browser

## Steps to Reproduce
1. Add the modern script editor web part to a SharePoint Online page, and edit it
2. Edit HTML code and add the below:
```
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="tradingview_1780b"></div>
  <div class="tradingview-widget-copyright"><a href="https://uk.tradingview.com/symbols/LSE-MTO/" rel="noopener" target="_blank"><span class="blue-text">MTO Quotes</span></a> by TradingView</div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
<script type="text/javascript">
new TradingView.widget(
{
"autosize": true,
"container_id": "tradingview_1780b"
}
);
</script>
</div>
<!-- TradingView Widget END -->
```
3. Click Save and then "save as draft on the page"
4. The widget does not load, and looking at the browser network load, it does not even download the js file
5. Now re-edit the script part, and replace the html code with the following:
```
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="tradingview_1780b"></div>
  <div class="tradingview-widget-copyright"><a href="https://uk.tradingview.com/symbols/LSE-MTO/" rel="noopener" target="_blank"><span class="blue-text">MTO Quotes</span></a> by TradingView</div>
</div>
<script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
<script type="text/javascript">
new TradingView.widget(
{
"autosize": true,
"container_id": "tradingview_1780b"
}
);
</script>
<!-- TradingView Widget END -->
```
6. When you click save and "Save as draft", the widget now loads correctly.

# Environment Details (*Development & Target environment*)
The react-script-editor app was built as per the "minimal path to awesome" instructions, with requiresCustomScript set to false.
Tooling was nodeJS 10.21.0, everything compiled from the command line
The app was deployed using the site collection app catalog to a SharePoint modern site

## Additional context
This issue is relevant because the newest version of the TradingView stock widget requires the script block to be within the container div as per below, otherwise it will not load.
```
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div class="tradingview-widget-container__widget"></div>
  <div class="tradingview-widget-copyright"><a href="https://uk.tradingview.com/symbols/LSE-MTO/" rel="noopener" target="_blank"><span class="blue-text">MTO Quotes</span></a> by TradingView</div>
  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-single-quote.js" async>
  {
  "symbol": "LSE:MTO",
  "width": "100%",
  "colorTheme": "light",
  "isTransparent": false,
  "locale": "uk",
  "largeChartUrl": "https://uk.tradingview.com/chart/?symbol=LSE%3AMTO"
}
  </script>
</div>
<!-- TradingView Widget END -->
```
When I try and put in the above code to the script editor widget I get the same issue, that the js file isn't loaded at all by the browser.

**Comment by AbhishekGarg** [comment]
@wobba Currently, the sample code uses `element.childNodes` (webpart element) and searches for `script` nodes. Issue might be resolved if `getElementsByTagName` can be used instead. 

Unfortunately, I am not aware of the performance trade-off, particularly if there is a large html content in the webpart. Hopefullly, it should not be too much due to use of native function.

If this seems like a good idea, I can send in a pull request, or you can implement it directly.

**Comment by wobba** [comment]
@AbhishekGarg  feel free to submit a PR for it.
