### ISSUE TITLE
React-AccordionFAQ

### ISSUE THREAD

**Issue by Abiman194** [pnp/sp-dev-fx-webparts#1331]
Thank you for asking a question! Use the sections below to submit a question ONLY if it's related to samples in this repo. If you have an issue or question about the SharePoint Framework or its documentation, please submit it at https://aka.ms/spdev-issues

- Questions that do not follow the below template will automatically be closed
- All questions are welcome - let us know what's on your mind!
- This repo is maintained by volunteers (not Microsoft). Please be courteous and patient. 🙂
- Include sufficient details and context.
- If you have multiple questions please submit them separately so we can track resolution.
- Screenshots are always helpful (just paste any images right here in the question)

DELETE EVERYTHING ABOVE AFTER READING - THANKS!

## Sample (which sample are you talking about)
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-accordion

## Authors
@gautamdsheth - React Accordion from Rapid Circle

## Question (the more details, the better)
The react Accordion FAQ renders perfectly the way it is supposed to display the default List view of the FAQ List entries. My question is around displaying the list entries based on the created date, no matter I change the default list view to sort the list items by created date, the web part displays only the faq entries by the default SharePoint list ID. What is the code change to display the FAQ by the most recent ones?

![reactaccordionList](https://user-images.githubusercontent.com/23061338/84298848-a5512980-ab04-11ea-9eb5-bca3859637ef.png)

**Comment by Harshagracy** [comment]
Hi @abhiman

You have to add the order by in the Rest API line number 69:
```
//instead of this url
 let restAPI = this.props.siteUrl + `/_api/web/Lists/GetByTitle('${this.props.listName}')/items?$select=Title,Description`;
//add the order by to sort based on created
 let restAPI = this.props.siteUrl + `/_api/web/Lists/GetByTitle('${this.props.listName}')/items?$select=Title,Description&$orderby=Created desc`;

```
![image](https://user-images.githubusercontent.com/14230498/84350909-e2d2b700-abd7-11ea-9656-d966eb3ca347.png)

**Comment by Harshagracy** [comment]
Hi @Abiman194 , 

> Hi @Abiman194
> 
> You have to add the order by in the Rest API line number 69:
> 
> ```
> //instead of this url
>  let restAPI = this.props.siteUrl + `/_api/web/Lists/GetByTitle('${this.props.listName}')/items?$select=Title,Description`;
> //add the order by to sort based on created
>  let restAPI = this.props.siteUrl + `/_api/web/Lists/GetByTitle('${this.props.listName}')/items?$select=Title,Description&$orderby=Created desc`;
> ```
> 
> ![image](https://user-images.githubusercontent.com/14230498/84350909-e2d2b700-abd7-11ea-9656-d966eb3ca347.png)

Hi @Abiman194 , if this comment has helped you to solve your issue, please make the issue as resolved/closed. :)

**Comment by Abiman194** [comment]
Resolved. Thank you
