### ISSUE TITLE
Broken Web Parts: react-adaptivecards and react-adaptivecards-hooks 

### ISSUE THREAD

**Issue by AHTei** [pnp/sp-dev-fx-webparts#1332]
## Sample (which sample are you having trouble with)
react-adaptivecards and react-adaptivecards-hooks 

## Authors
hugoabernier & petkir

## Additional context
Both of the mentioned sample SPFx web parts are broken since the Adaptive Cards Template code has been recently updated.

This issue has been notified to one of the authors ( hugoabernier ) 2 weeks ago and there has not been any update yet.

**Comment by hugoabernier** [comment]
The issue is still present in the react-adaptivecards-hooks.
