### ISSUE TITLE
Unable to modify the React_Accordion Theme color

### ISSUE THREAD

**Issue by Abiman194** [pnp/sp-dev-fx-webparts#1336]
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-accordion

## Authors
@gautamdsheth 

## Question (the more details, the better)
The react accordion app by default sets the FAQ background color as the site theme color. Is there a way to override the color?
tried the below from src>webparts>reactaccordion>accordion.css and does not work as expected.

.accordion__item .accordion__title {
padding: 5px 20px;;
/* background-color: "[theme: themePrimary, default: #0078d7]"; */
background-color: "[theme: themePrimary, default: #dfdedd]";

**Comment by Harshagracy** [comment]
The default will be applied only if the theme colour failed to apply. instead, you could directly apply the colour in that case. 
`background-color:#dfdedd;`

If this answers your question, please close this issue. :)

**Comment by Abiman194** [comment]
> The default will be applied only if the theme colour failed to apply. instead, you could directly apply the colour in that case.
> `background-color:#dfdedd;`
> 
> If this answers your question, please close this issue. :)

Thank you.
