### ISSUE TITLE
React-Birthdays : Not visible in SharePoint Mobile (iOS & Android) - webviewer issue

### ISSUE THREAD

**Issue by DeWoete** [pnp/sp-dev-fx-webparts#1341]
Hi,
first of all a big thank you for the many samples. It has been very helpful.

We are currently reviewing the 'React-birthdays' webpart sample, and just wanted to let you know it works very well on browsers, **however it doesn't work on mobile webviewers.** We believe the webviewer of iOS & Android doesn't allow/can't work with a part of the code.

Kind regards

Link to webpart sample
- https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-birthdays

Tests
- Show on mobile & desktop browsers -> Perfect
- show on webviewer Android or iOs -> Doesn't show content, only title
- show in SharePoint mobile app -> Doesn't show content, only title

**Comment by hugoabernier** [comment]
@DeWoete, thanks for filing the issue and the kind comments.

However, we'll need you to kindly use the issue template that is provided so that we can help you.

Sample authors don't get notified unless you fill the template as requested.

Thanks for your understand.
