### ISSUE TITLE
Inconsistent documentation for aadHttpClientFactory causes problems

### ISSUE THREAD

**Issue by nigel-dewar** [pnp/sp-dev-fx-webparts#1344]
I have an SPFX webpart which doesnt work, and I will figure out why in my own time,

In meantime, I want to report this as a bug.

you have this article here
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient

Which says you must use the webapi endpoint to get a client
![image](https://user-images.githubusercontent.com/9402456/84903864-f6a77d00-b0f1-11ea-8860-02d353172ff2.png)

Then in this article https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi

its says this

![image](https://user-images.githubusercontent.com/9402456/84903933-0de66a80-b0f2-11ea-8f5f-1cdcc1dec4be.png)

So which is it?  the url or the guid? confusing and very annoying

**Comment by hugoabernier** [comment]
@nigel-dewar I can absolutely understand your frustration.

Unfortunately, this issue list is intended for issues related to SharePoint web part samples in this repository and there is nothing that we can do about this issue from here.

I would suggest that you copy this issue to https://aka.ms/spdev-issues where you'll be able to get the attention of the folks who can actually solve this issue for you.

I would have transferred the issue for you, but it is in a completely different GitHub organization and I don't have access to it.

Thanks again for raising the issue. I hope that someone will be able to fix it for you.
