### ISSUE TITLE
Using Action.Submit: react-adaptivecards

### ISSUE THREAD

**Issue by cconrado** [pnp/sp-dev-fx-webparts#1349]
## Sample (which sample are you talking about)
react-adaptivecards

## Authors
@hugoabernier 
@pschaeflein 

## Question (the more details, the better)
I'm not clear on setting up your own event handler.
![image](https://user-images.githubusercontent.com/9168464/85214612-b5ea7680-b332-11ea-9d20-92e9513c6d9c.png)
Do you mean where the request is going?

**Comment by hugoabernier** [comment]
@cconrado the sample we part shows an example of how to handle actions. 

You can define an event handler in the component:

```typescript
 <AdaptiveCard
            template={template}
            data={data}
            useTemplating={useTemplating}
            themeVariant={themeVariant}

//BEGIN: Handler
            onExecuteAction={this._executeActionHandler}
//END: Handler

            className={styles.adaptiveCardHost}
          /></>);
```

And your handler can do whatever you want with the action:

```typescript
private _executeActionHandler = (action: IAdaptiveCardActionResult) => {
    console.log("Action", action);

    // Feel free to handle actions any way you want -- these are just examples
    switch (action.type) {
      case "Action.OpenUrl":
        window.open(action.url);
        break;
      case "Action.Submit":
        alert(action.title);
        break;
      default:
        break;
    }
  }
```

I hope this helps?

**Comment by cconrado** [comment]
I think I just lack knowledge and I'll continuing researching thanks.

**Comment by hugoabernier** [comment]
Let us know how we can help!
