### ISSUE TITLE
In react-list-form webpart, validation doesn't fire for mandatory fields before saving the list item

### ISSUE THREAD

**Issue by shrirampophali** [pnp/sp-dev-fx-webparts#1352]
Thank you for reporting a bug! Use the sections below to submit a bug ONLY if it's related to samples in this repo. If you have an issue or question about the SharePoint Framework or its documentation, please submit it at https://aka.ms/spdev-issues

- Bugs that do not follow the below template will automatically be closed
- All bug reports are welcome - we want to fix them!
- This repo is maintained by volunteers (not Microsoft). Please be courteous and patient. 🙂
- Include sufficient details and context.
- If you have multiple bugs please submit them separately so we can track resolution.
- Screenshots are always helpful (just paste any images right here in the bug report)
- We accept pull requests. If you know how to fix it - go ahead!

DELETE EVERYTHING ABOVE AFTER READING - THANKS!

## Sample (which sample are you having trouble with)
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-list-form

## Authors

> Because of the way this repository is configured, samples authors do not get a notification when you create an issue. *It makes it less likely for you to get your issue resolved or to get help*. For the section above **@mention any author of the sample**. Authors' GitHub handle can be found on the main sample documentation page, under the "solution" section. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Steps to Reproduce

# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by hugoabernier** [comment]
@shrirampophali  in order to help you, we need you to fill the issue template provided, including repro steps, author, etc.

Please try again with a new issue so we can get you the help you deserve.

Thanks for understanding
