### ISSUE TITLE
In react-list-form webpart, validation not firing for required list fields before saving the item

### ISSUE THREAD

**Issue by shrirampophali** [pnp/sp-dev-fx-webparts#1354]
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-list-form
Sample: #react-list-form
Author: @DanyWyss 

## Expected or Desired Behavior
List form should perform validation of all required fields before saving

## Observed Behavior
List form saving the form without any validation of required fields

## Steps to Reproduce
If I leave "Title" field empty, it just shows me message as "Item Added Successfully" after click on save button

![image](https://user-images.githubusercontent.com/8651602/85293932-a8142d00-b4bb-11ea-838d-ad92be2c1f4a.png)

1. Add the webpart to Modern SharePoint Site
2. Select sample SharePoint List from Properties
3. Try to Save without filling required fields
4. It will show "Item Saved Successfully" message

![image](https://user-images.githubusercontent.com/8651602/85293932-a8142d00-b4bb-11ea-838d-ad92be2c1f4a.png)

# Environment Details (*Development & Target environment*)
- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8
- **Browser(s)**: Chrome v83
- **Tooling**: VS Code | SPFx v1.9.1
- **Additional details**: *It shows required error message for DateTime Field and not for Title*

**Comment by Harshagracy** [comment]
Hi @hugoabernier, I will look into this issue. Could you please assign my name?

**Comment by hugoabernier** [comment]
Thank you @Harshagracy, you are now assigned!

**Comment by shrirampophali** [comment]
Thank you @Harshagracy for fixing the issue 👍  and @hugoabernier for merging! 👍 

Would be nice to have unsupported fields supported in future as well! :) 

- Person Group
- Managed Metadata
- HyperLink or Picture
