### ISSUE TITLE
Specifying Result Source Identifier in search results configuration not reflecting results

### ISSUE THREAD

**Issue by manishkaushal2015** [pnp/sp-dev-fx-webparts#1355]
[x]Question
I am configuring search results webpart to get results from a search result source. The source shows all records from a specific library. When I specify the source GUID in search results configuration it has no effect on results. All results are showing up rather than from the result source.
Version: 3.13.0.0
Search Results connected to SearchBox, Search Refiners, Search Vertical webparts. 
Environment: SP Online

##Questions #2: I created search-extensibility-library to add additional attributes to searchTerm e.g. 

 `${query.queryText} Path:{Site}`

After enabling this configuration in the webpart. This does not effect search results. Can you please help me in getting this working. I need to get either one these options working. Kindly advise.

**Comment by manishkaushal2015** [comment]
@wobba Can you please help me with this. Prompt help will be highly appreciated as I am bit stuck on this one since couple of days.

**Comment by wobba** [comment]
PnP modern search web parts issues should be logged at: https://github.com/microsoft-search/pnp-modern-search. Also check samples of extensibility https://microsoft-search.github.io/pnp-modern-search/search-query-enhancer/getting-started/

**Comment by manishkaushal2015** [comment]
Sure will log it in the right location. I found the bug. It is in SearchVerticals webpart. Will post it over there.
