### ISSUE TITLE
react-calendar add toggle for All Day Event

### ISSUE THREAD

**Issue by pap1723** [pnp/sp-dev-fx-webparts#1361]
## Sample (which sample are you talking about)

react-calendar

## Authors

@joaojmendes 
@derhallim 
@hugoabernier 

## Question (the more details, the better)

I am trying to add a Toggle Field that will set the event as an All Day Event. I have found `fAllDayEvent?: boolean;` in IEventData, but I am not understanding how to add it to the right side Add/Edit Event window in event.js.

Thanks for your help!

**Comment by hugoabernier** [comment]
@nanddeepn it's all yours!

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Submitted PR. Please review.

**Comment by hugoabernier** [comment]
Thanks @nanddeepn! I get automatically notified when a PR is submitted.
