### ISSUE TITLE
react-events-dynamicdata - map web part gets an error: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by MarkusLanger** [pnp/sp-dev-fx-webparts#1362]
## Sample (which sample are you having trouble with)
react-events-dynamicdata

## Authors
@waldekm

## Expected or Desired Behavior
Show the map of the selected event.

## Observed Behavior
Receive an error "Cannot read property 'address' of undefined"

![image](https://user-images.githubusercontent.com/12131918/86212094-b9260380-bb77-11ea-8ed5-126632d697b5.png)

## Steps to Reproduce

Build and deployed the solution as described in the documentation => https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-events-dynamicdata#minimal-path-to-awesome

# Environment Details (*Development & Target environment*)

- **OS**: MacOS 10.15.5
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8.17.0
- **Browser(s)**: Chrome Version 83.0.4103.116
- **Tooling**: VS Code

**Comment by ValerasNarbutas** [comment]
@hugoabernier , i can check this one.

**Comment by hugoabernier** [comment]
@ValerasNarbutas thanks for volunteering. I've assigned you to it.

**Comment by ValerasNarbutas** [comment]
@MarkusLanger , @hugoabernier , @waldekmastykarz .
Looks like its a bug, 
might be related to the version of spfx and current modern version of SP. SPFX used 1.7 and i see solution should work correctly as long dynamic properties will be returned with correct type.
i will investigate further.

**Comment by hugoabernier** [comment]
@ValerasNarbutas do you want me to try upgrading the sample?

I know a quick way 🤫

**Comment by ValerasNarbutas** [comment]
> @ValerasNarbutas do you want me to try upgrading the sample?
> 
> I know a quick way 🤫

yes :) of course!!!! Would be great, my way usually is quite long :)

**Comment by ValerasNarbutas** [comment]
@hugoabernier , thanks man. did you intended to close this issue? this could also be related to #5947 https://github.com/SharePoint/sp-dev-docs/issues/5947
