### ISSUE TITLE
react-multimedia-gallery npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.2.tgz

### ISSUE THREAD

**Issue by keedman4** [pnp/sp-dev-fx-webparts#1363]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.2.tgz
npm ERR! 404
npm ERR! 404  'websocket-driver@0.7.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-multimedia-gallery'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by petkir** [comment]
Hi @hugoabernier you can close this issue #1363 #1364  are duplicate Issues and solved by merge #1383

**Comment by hugoabernier** [comment]
Thank you @petkir !
