### ISSUE TITLE
react-calendar custom toolbar or Views

### ISSUE THREAD

**Issue by coolvijaymca** [pnp/sp-dev-fx-webparts#1367]
Hi All, 

Requesting to check if someone has implemented a custom Toolbar on [react-calendar](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-calendar), with additional button.

Also is there any possibility to have additional year view in this calendar like this . This is also using react-big-calendar 
 
https://codesandbox.io/s/priceless-mclean-jjmky5047y?file=/src/Year.js:0-3849

-VJ

**Comment by kumavds** [comment]
I am having a similar issue trying to implement a custom view.  I can successfully create a custom view using react big calendar outside of sharepoint but not using the spfx web part.

**Comment by Abderahman88** [comment]
I succeeded to recreate your year-view in SharePoint. (hacky way because of a limitation in react-big-calendar)
If still needed, I will create a PR. 

![yearCalendar](https://user-images.githubusercontent.com/36161889/96508075-59ed1b80-125a-11eb-8d0e-cc3864fad8c8.PNG)

**Comment by coolvijaymca** [comment]
> I succeeded to recreate your year-view in SharePoint. (hacky way because of a limitation in react-big-calendar)
> If still needed, I will create a PR.
> 
> ![yearCalendar](https://user-images.githubusercontent.com/36161889/96508075-59ed1b80-125a-11eb-8d0e-cc3864fad8c8.PNG)

Can you post your example here on github

Thank You

**Comment by Abderahman88** [comment]
I have created a PR @coolvijaymca 

Let me know if you have any questions.

**Comment by Abderahman88** [comment]
@hugoabernier  I think this issue can be closed.
