### ISSUE TITLE
react-yammer-api, Log in with Yammer button opens the popup but never closes it.

### ISSUE THREAD

**Issue by magarma** [pnp/sp-dev-fx-webparts#1385]
Hi,

This is happening to us from some days ago and it was working properly before. It's happening in the react-yammer-api sample but also in a custom spfx webpart. Both started to fail at the same time. So I assume that something has changed in the log-in process.

Here are the details:

- Having the react-yammer-api deployed and added into a page
![image](https://user-images.githubusercontent.com/8925463/87423805-32434300-c5db-11ea-87f2-ab3beb352052.png)

- First time that I visit the page, the Log In button is being shown properly, and when clicking on it, the pop-up window with the yammer.com/session/new is presented.
![image](https://user-images.githubusercontent.com/8925463/87424156-c8776900-c5db-11ea-9d4e-edfa0feeb0cf.png)

- When filling the user address, the popup does usual the redirections, but stucks in this page
![image](https://user-images.githubusercontent.com/8925463/87430100-00cf7500-c5e5-11ea-9550-6e88dd4ff067.png)

- And checking the console in the popup window, it shows some errors:
![image](https://user-images.githubusercontent.com/8925463/87425121-61f34a80-c5dd-11ea-8480-67f0fe26b8cf.png)
- Checking the page where the webpart is placed, also shows some errors:
![image](https://user-images.githubusercontent.com/8925463/87429554-3fb0fb00-c5e4-11ea-9675-064c71a8e0ae.png)

If we close the pop-up window manually and refresh the page, then the webpart works, it seems that the token is already present, but in any case, it's a bit frustrating to have to close manually that window.

Is there any change in the Yammer API? 
Should we change the way we are logging?
Any advice?

Thanks in advance

**Comment by PowellT** [comment]
Did you ever find a fix or work around for this?

**Comment by magarma** [comment]
Hi, 
I managed to get the token using ADAL and configuring an app in AD with Yammer - user impersonation permissions.
After that, I could add yam.platform.setAuthToken.
Maybe there is a better approach, but this was the easier way for us.
