### ISSUE TITLE
react-graph-telephonedirectory SPFx WebPart after Deployment: login.microsoftonline.com refused to connect.

### ISSUE THREAD

**Issue by schneika** [pnp/sp-dev-fx-webparts#1388]
When i place the SPFx WebPart on a modern Page i get the error:

login.microsoftonline.com refused to connect.

I have API Access Consent and sppkg Package with --ship

**Comment by hugoabernier** [comment]
@schneika thanks for filling this issue, but you'll need to fill the issue template that is provided in order for us to be able to help you. 

Please note that sample authors do not get notified of your issue unless you take the time to fill the issue template. 

Thanks for your understanding
