### ISSUE TITLE
gulp bundle --ship fails (and possibly assets list creation)

### ISSUE THREAD

**Issue by BassemNKhalil** [pnp/sp-dev-fx-webparts#1389]
## Sample (which sample are you having trouble with)
[react-adaptive-cards-image-gallery](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-adaptive-cards-image-gallery)

## Authors
@nanddeepn 

## Expected or Desired Behavior
Unable to run - [Minimal-path-to-awesome not sufficient](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-adaptive-cards-image-gallery#minimal-path-to-awesome)

## Observed Behavior
gulp bundle --ship throws warning and fails (had to {/* tslint:disable-next-line */} to be able to bundle ship)
Line 107 in [AdaptiveCardsImageGallery.tsx](https://github.com/pnp/sp-dev-fx-webparts/blob/79cb00178af01549deccfd4d1252dd820775ec5a/samples/react-adaptive-cards-image-gallery/src/webparts/adaptiveCardsImageGallery/components/AdaptiveCardsImageGallery.tsx#L107)

Furthermore, following [Minimal-path-to-awesome](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-adaptive-cards-image-gallery#minimal-path-to-awesome) I wasn't able to see the control - diving deeper, it seemed like the list wasn't created properly as it didn't have the extra columns (Image Link, Navigation Link and Sort Order).

Since the first run using the tenant workbench (not the local one) creates the list, I had to delete both the app and the list then add the app again - this time things worked out, presumably because I provisioned the list by adding the app to the SharePoint site instead to running gulp serve

## Steps to Reproduce
1. git clone ...
2. npm install ...
3. gulp bundle --ship (returns warning and exits without completing bundle task)
4. gulp serve --nobrowser then opening a tenant workbench (webpart does not show the gallery)

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
I can look into this.
