### ISSUE TITLE
[react-graph-telephonedirectory] WebPart overlays the bottom page control with like\view\save for later when search returns more than one result

### ISSUE THREAD

**Issue by BassemNKhalil** [pnp/sp-dev-fx-webparts#1393]
## Sample (which sample are you having trouble with)
[react-graph-telephonedirectory](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-graph-telephonedirectory)

## Authors
@dips365

## Expected or Desired Behavior
UI should respect the bottom area with like\views\save for later - works for single item
![image](https://user-images.githubusercontent.com/11630074/87752520-e6df9d80-c843-11ea-9915-2845db7b7d14.png)

## Observed Behavior
![image](https://user-images.githubusercontent.com/11630074/87752541-f19a3280-c843-11ea-8574-7477b4b49ca8.png)

## Steps to Reproduce
Followed the [Minimal Path to Awesome](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-graph-telephonedirectory#minimal-path-to-awesome)

**Comment by dips365** [comment]
Thanks @BassemNKhalil  for your feedback.
I will work on it and release it very soon.

**Comment by Abderahman88** [comment]
Is this still an issue?

**Comment by BassemNKhalil** [comment]
No, it's not - I tested the same version of the webpart without updating - same tenant and page etc.
Would that indicate an update on Microsoft's end or just a bad repro step on my end the first time?

![image](https://user-images.githubusercontent.com/11630074/101440829-c8517e80-396b-11eb-85c9-1fa9746f6160.png)

**Comment by Abderahman88** [comment]
Don't know exactly what went wrong, but good to hear it's solved.

@hugoabernier I think this one can be closed 👍

**Comment by hugoabernier** [comment]
Thank you @Abderahman88 for your help with this one.
