### ISSUE TITLE
SharePoint Online Sharing Options - Looking for a Way to Point to Native Outlook

### ISSUE THREAD

**Issue by tejasthite** [pnp/sp-dev-fx-webparts#1394]
## Sample Description (what should it do)

It would be Great to have this as a solution, I would like to control to customize, If that can be done, Currently the Outlook Option in there is pointing to OWA, But would like the control to customize so that that can be pointed to Native Outlook 
Thank you, Appreciate all your help.

![image](https://user-images.githubusercontent.com/38923482/87758510-3618d480-c82a-11ea-9627-36eea5640b55.png)

## Are you Willing to Help?
No, I am not that great with Programming

**Comment by tejasthite** [comment]
@hugoabernier - It would be a pleasure to get you help with this, Thank you

**Comment by tejasthite** [comment]
Is there anyone who could help with this? Thank you

**Comment by PopWarner** [comment]
We believe you are referring to out of the box functionality, which is not controlled by the samples in this repository, nor is customizable. 

If this is referring to a specific sample, can you please submit a new issue, including all the data requested in the issue template.

Thank you! 🧡💜
