### ISSUE TITLE
react-content-query-webpart not detect subsites correctly

### ISSUE THREAD

**Issue by albegut** [pnp/sp-dev-fx-webparts#1395]
## Sample (which sample are you having trouble with)

react-content-query-webpart

## Authors

@PopWarner, @hugoabernier, @PaoloPia, @spplante

## Expected or Desired Behavior

Webpart allow to select site and subsite at the webpart properties

## Observed Behavior

The webpart detects other site collections and sub sites correctly but in the site collection where the webpart are inserted only detects current web.

## Steps to Reproduce

1. Go to one site with subsites
2. Start to configure the webpart
3. In the web url property check that only shows the current web

# Environment Details (*Development & Target environment*)

- **Target Environment**: SharePoint Online
- **Additional details**:  WebPart version: 1.0.13.0

## Additional context

Example: Sites infoclick_dev5 and infoclick_dev6 have the same subsites.
 The Webpart is in the root web of infoclick_dev5 and it detects all webs of site infoclick_dev6 but only detects the current root web for site infoclick_dev5

![contentQueryWebPart](https://user-images.githubusercontent.com/9661096/87759056-ee844f80-c80d-11ea-9789-72e1d12f18f9.gif)

**Comment by spplante** [comment]
@albegut the webparts uses the search in order to find available sites and sub sites. Did you make sure that the particular subsite was searchable and well indexed?

**Comment by hugoabernier** [comment]
@albegut did @spplante's answer help you resolve the issue?

**Comment by albegut** [comment]
Yes! @hugoabernier I reindex the site and the problem is solved. Thanks @spplante!
