### ISSUE TITLE
REACT-GLOBAL-NEWS only displaying on microsoft edge and not other browsers

### ISSUE THREAD

**Issue by keedman4** [pnp/sp-dev-fx-webparts#1397]
I get this error from the the react-global news webpart when i open  my intranet site on chrome or opera or anyother browser apart from microsoft edge
"Requests from the browser are not allowed on the Developer plan, except from localhost."

Please how do i solve it @joaojmendes

**Comment by joaojmendes** [comment]
hello,

Please go to the newsapi.org site and register new key , that message are returned by the API. the WebPart don't have any browser restrictions.

If you go to FireFox e runs OK.

<img width="1650" alt="Screenshot 2020-07-17 at 17 31 48" src="https://user-images.githubusercontent.com/12551125/87809578-86f0f300-c853-11ea-9212-e3494a613517.png">

Thanks.

**Comment by keedman4** [comment]
okay thanks
