### ISSUE TITLE
Error when running npm install - React Calendar Feed Web Part

### ISSUE THREAD

**Issue by philip-rj** [pnp/sp-dev-fx-webparts#1398]
## Question

After downloading the latest version (5.2), I tried to execute "npm install".
However, this results in an enormous amount of warnings and the end result are errors.

"gulp serve" also gives errors.

- I'm running VSCode  as administrator 
- node.js version: v10.20.1

Do you have any idea how I can solve this problem?

Thank you in advance!

## Error detail

   **First Warn:**
   `warn tarball tarball data for office-ui-fabric-react@7.106.3 (sha512-1KaBF8tWhn6AnBkl791dOMvXRmbTXdjamsv0ztDaZE0gnPphiU5yA7sThq1XyA2g+SyoUd7ZkTzf4rzLjsHzaA==) seems to be corrupted. Trying one more time.`

   ![warn1](https://user-images.githubusercontent.com/69641/87853169-5f933800-c8de-11ea-9895-c51fa20ed3fa.png)

**Final error:**   
  ![erro](https://user-images.githubusercontent.com/69641/87853234-f102aa00-c8de-11ea-92d3-25ac8c2f6ab0.png)

**Gulp Serve:**
  ![gulp](https://user-images.githubusercontent.com/69641/87853245-fe1f9900-c8de-11ea-8db4-77544f318d8c.png)

## Sample
**React Calendar Feed Web Part**
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-calendar-feed#react-calendar-feed-web-part
@hugoabernier , @petkir

**Comment by petkir** [comment]
Hi @philip-rj 

I had never before this problem, you can try this

* Delete the ```node_modules``` folder
* Running ```npm install``` again

I hope this will help you.

**Comment by philip-rj** [comment]
Hi @petkir , 
I've tried again more or error remains. 

npm WARN tarball tarball data for office-ui-fabric-react@7.106.3 (sha512-1KaBF8tWhn6AnBkl791dOMvXRmbTXdjamsv0ztDaZE0gnPphiU5yA7sThq1XyA2g+SyoUd7ZkTzf4rzLjsHzaA==) seems to be corrupted. Trying one more time.


![image](https://user-images.githubusercontent.com/69641/87875765-e8c37100-c9a9-11ea-9e60-926d4757a536.png)

**Comment by philip-rj** [comment]
Hi, @petkir .

I don't know why, but after repeating the process a few more times, it now worked.

Thank you for your attention.
