### ISSUE TITLE
React-pages-hierarchy - Orientation of icons in breadcrum in mobile view

### ISSUE THREAD

**Issue by eldoro80** [pnp/sp-dev-fx-webparts#1403]
@bogeorge 

Hi there, I've used your webpart in an demo for a collegue. She is very happy with the breadcrum :-) So thanks again. Gonna us it for an implementation.

The thing that we noticed however when viewing the page on a mobile phone, is the orientation of the icons in the breadcrum. They point down. See screen:

![afbeelding](https://user-images.githubusercontent.com/48433541/88173945-b6bd4380-cc23-11ea-87b4-0faf20e8a65b.png)

Any ideas how to fix this problem?

**Comment by bogeorge** [comment]
@eldoro80, so the down arrow was me trying to get fancy when the web part was in a narrow zone.  If you want to change it Line 48 in the BreadcrumbLayout.tsx is where I swap the icon.  You should just be able to replace ChevronDown with ChevronRight and rebuild and deploy.
```
<Icon iconName="ChevronDown" className={styles.breadcrumbLayoutVerticalIcon} />
```

**Comment by eldoro80** [comment]
@bogeorge thanks! It's very fancy indeed (-: Maybe a bit to fancy (-;

**Comment by hugoabernier** [comment]
@eldoro80 I hope that @bogeorge 's answer works for you. I'll go ahead and close this issue for now.  Thank you @bogeorge for your help!
