### ISSUE TITLE
React Graph Calendar - Recurring Events

### ISSUE THREAD

**Issue by elpinto007** [pnp/sp-dev-fx-webparts#1414]
## Expected or Desired Behavior
When a group has a recurring event, the events should show 

## Observed Behavior
Recurring group calendar events do not show after the 1st item. Only the 1st item is showing and the rest do not show in the react graph calendar. We tested this with creating the even within the Group Calendar, as well as inviting the group to a recurring event.

## Steps to Reproduce
1. Create a recurring event in the Group calendar
2. Check the React Graph Calendar to see the events
3. The first event should show up, but all subsequent events dont.

**Comment by sebastienlevert** [comment]
This is definitely the case. We accept PRs on that web part if you have time or I might find time before the end of the summer to add support for recurring events. 

Thanks for noticing, though!

**Comment by sympmarc** [comment]
Getting recurring events is a bit of a pain, but it's important when they exist to give true fidelity. The OOB Events Web Part does NOT handle this, either. 

There's a[ UserVoice asking for recurring event handling in the API](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/15147117-provide-csom-and-rest-api-for-recurring-calendar-e), and even though I love the guy, @VesaJuvonen declined the suggestion.

To get recurring events, we're forced to CAML with `<ExpandRecurrence>TRUE</ExpandRecurrence>`. See my [old blog posts](https://sympmarc.com/?s=recurring+events) about this topic.

**Comment by elpinto007** [comment]
Thanks @sebastienlevert for the response. I have actually not done much coding in the last few years so I will need to touch up on my skills again. 

Thanks @sympmarc . I had a look at your post. Sounds like it is achievable with this workaround. I wonder if there is something in the GraphAPI which lets us pull this information.

**Comment by Abderahman88** [comment]
@sebastienlevert I'm working on this functionality. When I'm done, I'll create a PR.

![recEvents](https://user-images.githubusercontent.com/36161889/97310567-a8ef0e00-1863-11eb-8697-7ae0f0057ff5.PNG)

**Comment by sebastienlevert** [comment]
Amazing! That is great @Abderahman88!

**Comment by Abderahman88** [comment]
Still room for improvement, but it's a start 😄

**Comment by sebastienlevert** [comment]
That's an amazing improvement! This is really, super, super useful! Well done 😄

**Comment by sebastienlevert** [comment]
@hugoabernier you can definitely close this issue now! Thanks!
