### ISSUE TITLE
Cannot use same field to filter multiple times

### ISSUE THREAD

**Issue by rajmucharla** [pnp/sp-dev-fx-webparts#1418]
Results are not shown when same column is filtered twice.
![CQEW_Filter](https://user-images.githubusercontent.com/68555031/88993853-ac96e700-d2ac-11ea-86e4-951622c389f5.png)

**Comment by hugoabernier** [comment]
@rajmucharla please fill the issue template that is provided so that we can help you accordingly. 

Thanks for your understanding
