### ISSUE TITLE
LinkTitle column does not display any value

### ISSUE THREAD

**Issue by rajmucharla** [pnp/sp-dev-fx-webparts#1419]
Trying to generate a link (for Title column) using LinkTitle column from SharePoint list. Tried using properties (textValue, rawValue, htmlValue), still does not show any value.

**Comment by hugoabernier** [comment]
@rajmucharla this issue list is intended for issues related to samples in this repository. 

You may want to create an issue with the sp-dev- docs.  When you do, I encourage you to follow the template that is provided to you so you can get the help you need.
