### ISSUE TITLE
react-page-navigator HTML formatting bug

### ISSUE THREAD

**Issue by JaggB** [pnp/sp-dev-fx-webparts#1427]
When the react-page-navigator webpart is placed into the page, there's seems to be a bug which reads the HTML code. The image shows one of the issues, but sometimes there are also other issues such as <Span/>. At this time, it shows the <br> at the end of each line.

I've also tried reformatting and editting the text to Header1, Header2, etc and it's not making any difference.

![image](https://user-images.githubusercontent.com/26111527/89270939-f167a880-d633-11ea-8fe6-14b238a53e1f.png)

**Comment by hugoabernier** [comment]
This issue was closed as invalid as it fails to provide the information required. Please try again using the new issue template and provide all the information required.
