### ISSUE TITLE
react-accordion search function not working

### ISSUE THREAD

**Issue by sheiknaveed87** [pnp/sp-dev-fx-webparts#1428]
Authors
@AbhishekGarg , @gautamdsheth 

Expected or Desired Behavior
react-accordion search function searches title and description for keyword entered and returns only items that match.

Observed Behavior
Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at react-accordion-web-part_0ce60a9a8601814b00d2b4dd2ffaac20.js:1
    at Array.filter (<anonymous>)
    at t.searchTextChange (react-accordion-web-part_0ce60a9a8601814b00d2b4dd2ffaac20.js:1)
    at t._callOnChange (react-accordion-web-part_0ce60a9a8601814b00d2b4dd2ffaac20.js:1)
    at n._onInputChange (react-accordion-web-part_0ce60a9a8601814b00d2b4dd2ffaac20.js:1)
    at Object.m (sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1)
    at k (sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1)
    at sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
    at C (sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1)
    at N (sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1)
(anonymous) @ react-accordion-web-part_0ce60a9a8601814b00d2b4dd2ffaac20.js:1
t.searchTextChange @ react-accordion-web-part_0ce60a9a8601814b00d2b4dd2ffaac20.js:1
t._callOnChange @ react-accordion-web-part_0ce60a9a8601814b00d2b4dd2ffaac20.js:1
n._onInputChange @ react-accordion-web-part_0ce60a9a8601814b00d2b4dd2ffaac20.js:1
m @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
k @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
(anonymous) @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
C @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
N @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
S @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
z @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
Un @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
An @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
CO/T.t.unstable_runWithPriority @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
dl @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
vo @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1
In @ sp-pages-assembly_en-us_2f138c7077e71d8001064884dc9f6c91.js:1

Steps to Reproduce
1. Install the in app catalog
2. Add webpart to site and create the list.
3. Search with a word. No error found , above mentioned error got from the browser developer tool

**Comment by hristochr** [comment]
I had the exact same issue. Double-check the source columns and content

`Uncaught TypeError: Cannot read property 'toLowerCase' of null` means there is no string to search for.

**Comment by nanddeepn** [comment]
@sheiknaveed87 @hristochr 
The search seems to be working fine. 
Is it possible for you to share your list schema and sample data you are testing against?
Probably, that will help to reproduce the issue. Thanks!
