### ISSUE TITLE
my personal apps url not saved

### ISSUE THREAD

**Issue by hristochr** [pnp/sp-dev-fx-webparts#1430]
## Expected or Desired Behavior

When clicking on a saved link, the link should open in a new tab. 

![pab1](https://user-images.githubusercontent.com/22388580/89624987-bb2e6100-d89f-11ea-8e9c-a0efc85c00b6.PNG)

## Observed Behavior

The new tab opens blank, while there is a link saved

![pab2](https://user-images.githubusercontent.com/22388580/89624992-bc5f8e00-d89f-11ea-87d8-e8431f60b143.PNG)

## Steps to Reproduce

1. I have bundled and deployed the solution
2. Approved API Access from SPO admin center
3. Deployed on my site.

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10 
- **Target Environment**:  SharePoint Online
- **Framework**: Node.js v8.17
- **Browser(s)**: Chrome v79 
- **Tooling**: SPFx v1.10.0 

## Additional context
There is no anchor element at all when I inspect the button created by the webpart:
![pab3](https://user-images.githubusercontent.com/22388580/89625847-2c224880-d8a1-11ea-98a3-246a8c4d4dec.PNG)

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Can I take this up?

**Comment by hugoabernier** [comment]
@nanddeepn be my guest!

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Submitted PR for this. Please review.
