### ISSUE TITLE
react-tiles

### ISSUE THREAD

**Issue by keedman4** [pnp/sp-dev-fx-webparts#1433]
hi @hugoabernier ,
When i run npm install i get the following 

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\DELL\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\DELL\package.json'
npm WARN @uifabric/utilities@7.23.0 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN office-ui-fabric-react@7.59.0 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN office-ui-fabric-react@7.59.0 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN office-ui-fabric-react@7.59.0 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN office-ui-fabric-react@7.59.0 requires a peer of react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN office-ui-fabric-react@7.59.0 requires a peer of react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/foundation@7.7.33 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/foundation@7.7.33 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/foundation@7.7.33 requires a peer of react@>=16.8.0 <17.0.0 but none is installed. You
must install peer dependencies yourself.
npm WARN @uifabric/foundation@7.7.33 requires a peer of react-dom@>=16.8.0 <17.0.0 but none is installed.
You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/react-hooks@7.4.12 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/react-hooks@7.4.12 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/react-hooks@7.4.12 requires a peer of react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/react-hooks@7.4.12 requires a peer of react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.23.0 requires a peer of react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-star-rating-component@1.4.1 requires a peer of react@^16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN DELL No description
npm WARN DELL No repository field.
npm WARN DELL No README data
npm WARN DELL No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\webpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

How do i get the package.json and install all dependencies

**Comment by hugoabernier** [comment]
@keedman4 please use the issue template  and fill the sections provided when creating an issue so we can help you accordingly. 

I'm not the author of the sample. 

From the errors you listed, it looks like the version of spfx/ nodejs you are using may be incompatible with the version in the sample. 

Try office35cli spfx doctor to diagnose the issues. 

If you're still experiencing issues, feel free to open a new issue with the requested information
