### ISSUE TITLE
Error create or Update Extension

### ISSUE THREAD

**Issue by keedman4** [pnp/sp-dev-fx-webparts#1436]
Dear @joaojmendes,
I get this error when i try saving added link to the "my-personal-apps" webpart on my site.
![Capture](https://user-images.githubusercontent.com/37272357/89907406-8cd4bc80-dbe4-11ea-9964-dcf5a8b7fe05.PNG)

Is there a way to have it fixed.

Regards

**Comment by hugoabernier** [comment]
Thank you @keedman4 for submitting the issue, however in order to help you we need you to fill the issue template that is provided.
