### ISSUE TITLE
The security validation for this page has timed out

### ISSUE THREAD

**Issue by MohammadSafar** [pnp/sp-dev-fx-webparts#1445]
Hello there,

I have a WebPart developed using the spfx. This WebPart has a long running process where I keep posting batches of records to be inserted to a list. After about 30 minutes, the process is stopped and I receive the following error: "The security validation for this page has timed out". I know that this issue can be solved with the onprem version of the SharePoint, but is there a workaround with the online version?

Thank you in advance.

**Comment by Harshagracy** [comment]
How many records are you trying to save in the list? Also could you please share the snippet of code that you are using to save ?

**Comment by sudharsank** [comment]
Hi @MohammadSafar, can you try using Power Automate for the long-running process or maybe logic apps, instead of having all the logics in the SPFx web part.

**Comment by MohammadSafar** [comment]
Thanks a lot for your replies. What I am trying to achieve is that I have an excel file with around 12,000 rows and I want to update the records in my SharePoint list with the values from the excel file. I first compare the ID column from the excel sheet with the ID column in the SharePoint list. I do this in a batch of 50 records size. If any record is found in the SharePoint list, I add it to an array in which I use to delete those items in another batch. And then I insert all the 12,000 records again. I am doing this because I can not delete all the records since the excel sheet might not include old records which I need to keep. I am reaching around 7500 records and then receive the timeout error.

**Comment by sudharsank** [comment]
Hi, @MohammadSafar the entire logic should move to **Power Automate** or you can try **splitting the excel file into multiple.** Since it is running for around 7500 records, if you still want to achieve using the SPFx web part alone, I suggest you split the excel file of 12000 into 3 or 4 files with 3K or 4K records each and upload to your web part.

**Comment by bcameron1231** [comment]
It looks like this question has been answered. Unfortunately, what you are trying to do client-side will be very difficult for such a longrunning process. The digest token in SharePoint is valid for 30 minutes. After thirty minutes, you would need to call the SharePoint API to renew your context token (_api/web/contextinfo). 

Alternatively, @sudharsank  has some good information about maybe moving your logic to PowerAutomate instead or some other server side service for doing this work.
