### ISSUE TITLE
react-yammer-praise Teams issue

### ISSUE THREAD

**Issue by PowellT** [pnp/sp-dev-fx-webparts#1448]
## Authors
@petkir 

## Expected or Desired Behavior
Sample should work as Teams app

## Observed Behavior
Works fine in Sharepoint, when added as a team app, I get "applicationFailedToInitializeError"

## Steps to Reproduce
Deploy webpart as normal, add as a Teams app, 
Click on app/tab on left hand side of teams

![image](https://user-images.githubusercontent.com/8559249/90411696-259e8880-e07a-11ea-9787-938e00ce7521.png)

**Comment by petkir** [comment]
HI @PowellT, thanks for the issue
I'm not the author of this sample @AhmadiRamin made it. I hope he can help you.

**Comment by AhmadiRamin** [comment]
Hi @PowellT 
To solve the problem follow these steps:

ACCESS AAD SECURED ENDPOINT NOT WORKING ON TEAMS TAB

You may face this issue when trying to use AadHttpClient or AadTokenProvider class to get access to a secured endpoint like api.yammer.com.

To solve this problem:

Go to Azure portal.
Go to App Registrations.
Select “SharePoint Online Client Extensibility Web Application Principal“.
Select Manifest from left navigation.
Click Download.
Open the manifest.
Copy the id from the oAuth2Permission array.

Replace “preAuthorizedApplications” entry with the following json.

"preAuthorizedApplications": [
    {
        "appId": "00000003-0000-0ff1-ce00-000000000000",
        "permissionIds": [
            "7b30d829-354d-43b6-89f7-1f6ff27129d9"
        ]
    }
]
Replace PermissionIds with the Id from last step.
Save the file.
Upload the manifest.
Click Save.
It takes a while so you can see the result so give it some time

**Comment by hugoabernier** [comment]
@PowellT I hope @AhmadiRamin's solution solved your issues? 

I'll mark this issue as closed, but feel free to re-open it if you need more help.
