### ISSUE TITLE
Best way how to analyze child components properties with mocks?

### ISSUE THREAD

**Issue by Link631** [pnp/sp-dev-fx-webparts#1449]
## Authors
@VelinGeorgiev
@VesaJuvonen

Hi, 

did you develpe a strategy, how to best mock child components of a tested component,, so that you do not consume the origin components while still being able to analyze consumed properties of each consumed child component and also trigger events such as onChange, onClick, onClose or even custom events in custom child controls?

The reason why I am asking is, that I am not happy with my current aproach and no framework seems to help me getting out.

My current aproach:

Szenario:

Your IceCreamShop component uses simple buttons. Imagine you would now want to use fluent ui Buttons or use another library. In my progress, i do not want my mounted component to render the origin Button controls, but instead own defined mocks where I can analyze the used properties.

```
import React from "react";
import { IButtonProps} from "@fluentui/react";

export class ButtonMockHelper{
    public static usedProperties: IButtonProps| undefined;
}

class ButtonMock extends React.Component<IButtonProps, {}> {
    render(): JSX.Element {
        ButtonMockHelper.usedProperties = this.props;
        return (
            <div>
                Button   {this.props.children}
            </div>
        );
    }
}


const Button: React.FunctionComponent<IButtonProps> = (props: IButtonProps) => {
    return <ButtonMock{...props}></ButtonMock>;
};

export { Button};

```
And using it in a test like so:

beforeEach....
```

ButtonMockHelper.usedProperties = undefined;
const actualModule = require.requireActual("@fluentui/react");
const buttonMock= require("./mocks/ButtonMock");
actualModule.Button= buttonMock.Button;
...
 jest.mock("@fluentui/react", () => {
            return actualModule;
 });

...

it()....

expect(ButtonMockHelper.usedProperties).toMatchSnapshot();

...
```
I now also can easily trigger events which are defined within the properties:

ButtonMockHelper.usedProperties.onClick(....) 

When more instances of a component are getting consumed, then I simply do add the properties into an array and analyze the array later on.

I have tests with complex components like DetailsList, etc. where I can simulate selection,  trigger onSelectionChanged, test drag drop events and so on.

I am able to cover 100 % with this approach.

But:
I have following disadvantages which I want to get rid of:

1. Threadsafety with ButtonMockHelper.usedProperties: 
I walk around this issue by knowing, that each describe runs tests synchronously but more describes can run parallel.
So each describe has to use its own mockClasses with its own static Helpers to make sure that other tests do not ovrerwrite the properties.
2. Due to point one I have to copy for each test class the mocks I want to use, which makes mock classes redundant like hell.

I tried to solve this with sinonSpy, but here I am not able to spy on properties or even spy on a constructor.

What would you do to solve the disadvantages? 

Do you know someone else who is using mocks for real child components and checks its properties during testrun?

I could do in render: return json.stringify (this.props)... so the rendered component will contain the props as a string, but then I  am not able to call each event regardless which kind of event it is, and that in fact is a big advantage i do not want to miss. Many scenarios are complicated with simulate functionalities. Simple once with click do work, but more complex once are really tricky like SelectionChanged in a DetailsList. Simply getting the passed properties of a DetailsList and call the events are quite easy. 

Thanks for reading:-)

Regards...

**Comment by Link631** [comment]
I could checkin a sample test with that aproach into your repository if you want, so you can see how it would work.

**Comment by hugoabernier** [comment]
Hi @Link631, this question would be better suited to https://github.com/SharePoint/sp-dev-docs/issues/new as it relates to general development questions. 

I'll go ahead and close it, but if you have any more issues related to samples in this repository, feel free to open a new issue.
