### ISSUE TITLE
React list form does not redirect on submit in Internet Explorer 11

### ISSUE THREAD

**Issue by JenniferUXWeb** [pnp/sp-dev-fx-webparts#1450]
Sample (which sample are you having trouble with)
**React list form**

Authors
**Dany Wyss** @harshagracy

Expected or Desired Behavior
When a form is submitted using the React list form the page should successfully redirect to the page specified in the web part settings. 
![image](https://user-images.githubusercontent.com/68618534/90568077-16ffc080-e1a3-11ea-8aaa-7807321ce9b9.png)

Observed Behavior
Form does not redirect to specified page. the following error is returned:
**Error on loading lists: TypeError: Object doesn't support property method 'find'**
![image](https://user-images.githubusercontent.com/68618534/90567492-24687b00-e1a2-11ea-8a0f-af18c346fbed.png)

This feature works perfectly well in Google Chrome. 

## Steps to Reproduce

1. Deploy React list form to App catalog
2. Add web part to page
3. Configure settings and include a SharePoint page for the form to redirect to.
4. Fill in form and submit. Error message above returned. 

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: IE v11 
- **Tooling**: SPFx v1.10.0 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by PathToSharePoint** [comment]
I am not the author, but allow me to step in as I have done some work with React and IE11.

React support for IE browsers is not guaranteed, and even for IE11 you might need a polyfill. See the React documentation:
https://reactjs.org/docs/javascript-environment-requirements.html

I looked at the source code of this sample and didn't see a polyfill. Typically that could generate the type of error you are getting.

**Comment by JenniferUXWeb** [comment]
> I am not the author, but allow me to step in as I have done some work with React and IE11.
> 
> React support for IE browsers is not guaranteed, and even for IE11 you might need a polyfill. See the React documentation:
> https://reactjs.org/docs/javascript-environment-requirements.html
> 
> I looked at the source code of this sample and didn't see a polyfill. Typically that could generate the type of error you are getting. To be more specific, it seems that the code is looking for the array find method, which is not supported in IE11.
> 
> It's also worth mentioning that IE11 support in SharePoint Online is ending next year anyway.

Thank you so much for this info @PathToSharePoint , it's very helpful. Unfortunately, this isn't something I can do myself and it sounds like alot of work is required to update this!!!

**Comment by PathToSharePoint** [comment]
Same comment here, let's see what @Harshagracy thinks of that. If it's just about the find method, it might simply be a matter of rewriting a line or two to in ES5.

Again, keeping in mind that IE11 is retiring soon anyway it might not be worth the effort.
