### ISSUE TITLE
React list form: Support for People Picker, Attachments and Managed Metadata fields 

### ISSUE THREAD

**Issue by JenniferUXWeb** [pnp/sp-dev-fx-webparts#1452]
Sample (which sample are you talking about)
**React list form**

Authors
**Dany Wyss, @Harshagracy** 

Suggestion (the more details, the better)

**Firstly, a big thank you to the authors of this solution for all the hard work you put in to developing this fantastic web part. I'm sure it has helped many organisations where PowerApps is currently not an available option. 

I know that this has been requested quite a few times by different contributors but it would be really helpful if support for 'Person or Group' (people picker), 'Attachments' and 'Managed Metadata' fields were added to this solution.

It would literally be a game changer!!!** 

![image](https://user-images.githubusercontent.com/68618534/90570084-ed489880-e1a6-11ea-84a6-0a506bf8c94b.png)

**Comment by sharepointknight** [comment]
The current version already has support for attachments, but I will work on this and add person and managed metadata support

**Comment by JenniferUXWeb** [comment]
> The current version already has support for attachments, but I will work on this and add person and managed metadata support

Thank you so much! Greatly appreciated :)

**Comment by JenniferUXWeb** [comment]
@sharepointknight thank you so much for completing this – a knight you are indeed!!!
