### ISSUE TITLE
Sample missing from web parts gallery

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/sp-dev-fx-webparts#1456]
## Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-pnpjs-project-online

## Authors

(me) Joel Rodrigues

## Expected or Desired Behavior

Sample to be listed in the samples gallery

## Observed Behavior

Sample missing from the gallery

## Steps to Reproduce

Open https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-pnpjs-project-online
Search for "project online"

## Additional context

Not sure if this is something I can help with as I don't know how the gallery is maintained. If this is something I can do, please let me know and I will submit a PR

Thanks!

**Comment by hugoabernier** [comment]
Thanks, I'll take a look at it and make sure to add it

**Comment by hugoabernier** [comment]
Thank you @joelfmrodrigues , it looks like the sample was listed at some point in the past but I must've somehow copied over the entry in the sample browser -- probably due to subconscious being jealous of you for being such an awesome contributor 😁

The issue is fixed now.

**Comment by joelfmrodrigues** [comment]
Loool 😄 I will my samples were as cool as yours! 
Thanks for adding it. It this located within the project or a different open source repo? I was not able to find it
