### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-webparts#1459]
#974  Sample (which sample are you having trouble with)
react-enhanced-powerapps

## Authors
N/A

## Expected or Desired Behavior
Clone without error

## Observed Behavior
When I clone the repository, I get a "Filename too long" error for several files in the following folder:
samples/react-enhanced-powerapps/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/components/mobilePreview/mobilePreviewHeaderBar/mobilePreviewDeviceTypeSelector/

## Steps to Reproduce
git clone https://github.com/pnp/sp-dev-fx-webparts.git

# Environment Details (*Development & Target environment*)
- **OS**: Windows 10

**Comment by hugoabernier** [comment]
Hey @PathToSharePoint this is a common issue with operating systems such as Windows 10, especially if you're cloning your repos to your personal profile or OneDrive synched folder.

Instead, try cloning your repo to a shorter path (e.g.: c:\spfx or c:\github).

Let us know if this solves the issue.

**Comment by PathToSharePoint** [comment]
Got it, thanks. I was a bit surprised because the path I used is not that long: C:\Users\chris\Documents\My Git
