### ISSUE TITLE
js-modern-calendar npm install error!

### ISSUE THREAD

**Issue by dandansoy2004** [pnp/sp-dev-fx-webparts#1469]
PS C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar> npm install
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\duplexer2-b6a9c302\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\duplexer2-b6a9c302\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\duplexer2-b6a9c302\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\csso-a4997dc9\lib\cli.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\duplexer2-b6a9c302\example.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\csso-a4997dc9\lib\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\duplexer2-b6a9c302\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\duplexer2-b6a9c302\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\duplexer2-b6a9c302\LICENSE.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-14.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-2.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-3.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-13.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-4.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-5.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-6.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\blockScopeAwareRuleWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-7.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\blockScopeAwareRuleWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-8.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\index.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-12.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\programAwareRuleWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-9.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\programAwareRuleWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-11.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\ruleWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\ruleWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-10.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\icon-aliases.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\scopeAwareRuleWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-1.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\scopeAwareRuleWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\iconAliases.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\syntaxWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-0.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\syntaxWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\IconNames.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-4.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\walkContext.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\fabric-icons-14.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\walkContext.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\icons-b0de93fe\lib-es2015\IconNames.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\walker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\language\walker\walker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\blockExclusion.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\blockExclusion.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\classExclusion.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\classExclusion.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\exclusion.d.ts'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-e3dba6b3\lib\cli\logic\test\repo'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\exclusion.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\exclusionDescriptors.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\exclusionDescriptors.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\exclusionFactory.d.ts'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-e3dba6b3\lib\cli'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\exclusionFactory.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\tagExclusion.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\tslint-9d6f50c2\lib\rules\completed-docs\tagExclusion.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\csso-a4997dc9\lib\compressor\compress\property\background.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\csso-a4997dc9\lib\compressor\compress\property\font-weight.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\csso-a4997dc9\lib\compressor\compress\property\font.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\csso-a4997dc9\lib\compressor\restructure'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-e3dba6b3\lib\cli\logic\test\repo\f'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-e3dba6b3\lib\cli'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\websockets'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\window\BarProp-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\window\External-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\window\History-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\window\History.webidl'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\window\Location-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\window\navigation.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\window\Screen-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\window\SessionHistory.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\xhr-sync-worker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\jsdom-4e94338c\lib\jsdom\living\xhr-utils.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\styling-619291c4\lib\common\tests.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\styling-619291c4\lib\common\tests.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\styling-619291c4\lib\common\tests.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\styling-619291c4\lib\MergeStyles.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\styling-619291c4\lib\MergeStyles.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\styling-619291c4\lib\index.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\injectWrapperMethod.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\setRenderSpy.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\index.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\index.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\injectWrapperMethod.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\injectWrapperMethod.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\setRenderSpy.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\test\setRenderSpy.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\warn.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\Customizer.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\lib-es2015\warn.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\package-deps.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@uifabric\utilities-9355e4e0\utilities.build.log'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-e3dba6b3\lib\cli\logic'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.classNames.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.styles.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.checklist.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.types.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItemPage.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.styles.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.styles.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.classNames.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.checklist.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-e3dba6b3\lib\cli\logic\test\packages\a\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\@microsoft\rush-lib-e3dba6b3\lib\cli\logic\test\packages\a\CHANGELOG.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.types.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.classNames.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.types.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItemPage.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItem.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\ActivityItem\ActivityItemPage.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\FocusTrapZone.types.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\FocusTrapZone.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\FocusTrapZonePage.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\FocusTrapZonePage.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\FocusTrapZone.types.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\FocusTrapZone.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\FocusTrapZone.types.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\FocusTrapZone\FocusTrapZonePage.js.map'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\danab\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\.staging\office-ui-fabric-react-0a746da5\lib\components\Shimmer\ShimmerLine'
npm ERR! code E404
npm ERR! 404 Not Found: event-stream@3.3.6

**Comment by SmitaNachan** [comment]
Hello @dandansoy2004 
Since this web part is built with SPFx v1.6.0, please try by using node version 8.x for `npm install`

**Comment by hugoabernier** [comment]
Hey @dandansoy2004, I hope that @SmitaNachan 's reply helped you solve the issue. I'll go ahead and close the issue.

Feel free to open a new issue if you're still experiencing problems. If you do, please make sure to fill all the sections of the issue template so we can help you accordingly!

Thanks @SmitaNachan for your help!
