### ISSUE TITLE
select primary  theme color in react-enhanced-powerapps

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-webparts#1470]
How do I select the primaryThemeColor in the react-emhanced-powerapps sample webpart? Looking at the docs at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations it seems to say that themePrimary is the 'default' color for my sites, bit that is not an option in the  react-enhanced-powerapps.

I'm looking to use the background color of the new button here:
![image](https://user-images.githubusercontent.com/2412956/91779223-e1a39b80-ebc2-11ea-9daf-8d82382e1901.png)

Which option do I use?

**Comment by hugoabernier** [comment]
Hey @russgove,

Take a look at this post which lists all the colors available for semantic colors:
https://tahoeninjas.blog/2020/07/28/adding-support-for-theme-variants-in-spfx-web-parts/

It may help?

**Comment by russgove** [comment]
Thanks hugo. menuHeader seems to work for me. 
This webpart rocks! thanks
