### ISSUE TITLE
Exclude or hide the webpart from in the SPFx provisioning project

### ISSUE THREAD

**Issue by alexabramkin** [pnp/sp-dev-fx-webparts#1473]
## Sample 
sp-dev-fx-webparts/samples/react-provision-assets

## Authors
@VelinGeorgiev 

## Question 
In the react-provision-assets sample boilerplate "Welcome Web part" is also provisioned - is there a way to only provision assets and:
- exclude the Web part from the SPFx project altogether?

I understand we can hide the SPFx Web part from the "web part toolbox" on the  modern pages by using hiddenFromToolbox property in web part manifest, but it leaves lingering hidden web part that never will be and/or need to be used.

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Can I work on this?

**Comment by hugoabernier** [comment]
@nanddeepn be my guest!

Thanks for doing this

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Submitted PR.
Removed the web part completely. Adjusted the package creation by creating a custom gulp task.
Please review and let me know, if this approach looks good. Open for discussion :)
