### ISSUE TITLE
Add SP User/Groups to react-check-user-group or create new sample?

### ISSUE THREAD

**Issue by danwatford** [pnp/sp-dev-fx-webparts#1476]
## Sample (which sample are you talking about)
react-check-user-group

## Authors
@aakashbhardwaj619 

## Question (the more details, the better)
While trying to better understand how the ids stored in a SP Person/Group column map to SP Site Users, SP Site Groups and AAD Security Groups I created a webpart to view Site User/Group information.

I was going to submit this webpart as a sample, but wondered if it would be more appropriate to extend react-check-user-group instead.

Both webparts look up AAD group information for a user, but the react-check-user-group doesn't lookup SP Site Groups and it may not be appropriate to modify it to do so.

The new webpart displays the SP Site User used to represent an AAD security group.

The branch containing the new webpart can be found at https://github.com/danwatford/sp-dev-fx-webparts/tree/react-check-user-sp-site-groups

Please let me know if it appropriate to submit the webpart and, if so, whether it should be done as a new sample or as part of react-check-user-group.

Thanks,

Dan.

**Comment by hugoabernier** [comment]
@danwatford it looks like it would be a great sample. Why do you go ahead and submit as its own sample. Just make sure to refer to @aakashbhardwaj619 's sample from your README so that users looking for samples have the choice.
