### ISSUE TITLE
React  list form: Cascading dropdown list

### ISSUE THREAD

**Issue by clewmas** [pnp/sp-dev-fx-webparts#1487]
## Sample

Cascading dropdown list

## Authors

@Harshagracy
@hugoabernier

## Question

I have created a list on my SharePoint page with multiple dropdown menus when a new list is created. However, I was wondering that when an option is selected in the first drop down menu, if there was a way so that in the second drop down menu only certain options can be selected.

Currently my first dropdown menu is title projects and has all the main projects listed to choose (like 4 or 5 options). The second is for sub project. What I want to be able to do so say option 1 is chosen in the first drop down, only the certain sub projects that are related to option 1 in the first drop down appear in the second dropdown.

I wonder if this functionality is implemented in the web part.

## Question 2

After adding the web part to the page with the option new / edit / display item, I can change the functionality for the given list from that if I click on "New item" I will see the page on which the web part with the option new item is added? Currently NewForm.aspx is displayed. (SharePoint 2019 Onpremise)

**Comment by PathToSharePoint** [comment]
@clewmas could you share the link to the sample? I am interested to take a look as I am also building cascading dropdowns right now. I just did something similar, except that it was to sort fruit from veggies ;-)

**Comment by clewmas** [comment]
@PathToSharePoint 

**Sample**

_Main Project list:_

![image](https://user-images.githubusercontent.com/60599150/92570714-8472ae80-f282-11ea-8fdd-47ba83fe9c84.png)


_Sub Project list_ (Main project column is lookup from Main Project list):

![image](https://user-images.githubusercontent.com/60599150/92571180-14185d00-f283-11ea-9e4b-5b9857dccc4d.png)


_Projects list:_

When I want to create new item, I select Main Project 1 a then show me only subproject for Main Project 1 (like SubProject 11 / SubProject 12)

![image](https://user-images.githubusercontent.com/60599150/92572664-049a1380-f285-11ea-960c-92c790d9aaba.png)

**Comment by PathToSharePoint** [comment]
@clewmas thanks for the screenshots. The scenario makes perfect sense.

I was actually hoping for a link to the code itself (which according to your original question was authored by @Harshagracy and @hugoabernier). I couldn't find it in the repository.

**Comment by clewmas** [comment]
@PathToSharePoint 

At first I wanted to know if it is already implemented in the code because I also didn't find it. Based on the answer, I would deal with that further.

@Harshagracy @hugoabernier 

I have been dealing with this web part for a long time, I have tried various others. I just don't understand how it should really work. When I am a user and open the list, I want to create a new item and therefore I click on "New" in the ribbon. I don't know that it would be possible to modify this button. It should also work for the edit / display item as well. I would like to replace InfoPath in SharePoint 2019 OnPremise in this way, but it still doesn't seem like a suitable solution. Can anyone tell me if this is a suitable solution to replace InfoPath and in what way I could incorporate it as a "redirect" on the page where the webpart from the SharePoint list is ready?

**Comment by bcameron1231** [comment]
@clewmas  This would be a great feature, however is not something that is currently supported by the Web Part. This would definitely need to be an enhancement.

**Comment by sharepointknight** [comment]
I'm working on adding the cascading lookup functionality.
