### ISSUE TITLE
Sample "react-securitygrid" show AAD groups

### ISSUE THREAD

**Issue by kilicantplay** [pnp/sp-dev-fx-webparts#1488]
## Sample (which sample are you talking about)

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-securitygrid

## Authors

@russgove 
@hugoabernier 

## Question (the more details, the better)

Just looking to make an improvement to the Security Grid so that it can show AAD groups on it as well as named users, I don't actually have any users given permissions on my SPO sites it is all managed with SharePoint Groups with an AAD Group inside.

I'd be happy to surface the SharePoint Group name as well which from https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee541430(v=office.15) should be principaltype 8.

I'm fairly new to working with ts but looking to improve my skills as SpFx is far more flexible than anything else :D 

## Question

Is this possible to achieve, and are there any resources i can use to help figure out and implement the improvement?

**Comment by hugoabernier** [comment]
@kilicantplay maybe the code from this sample will help you? 
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-sp-site-user-groups

Let us know if you need more help?

**Comment by russgove** [comment]
@kilicantplay <https://github.com/kilicantplay> I think you will find some
code in the webpart that gets the AAD groups but it's commented out.  Funny
thing is when I created the webpart years ago i wanted to do that but i
could not figure out how to determine if the group i got from  the call was
an o365 group or an AAD Group (O365 groups were new back then). So years
later now we have learned that they are , in fact ,one and the same  :-).
If you uncomment that code it should be a good starting point. Happy to
help if I can (i have been trying to find time to do this myself!)

**Comment by russgove** [comment]
look at line 360 of spsecurityservice.ts.
I have some comments in there about how to do this:
for (let user of grp.Users) {
if (user.PrincipalType === 4) {
// To make this work with AD groups, I need to stop using the integer
UserId of the user as the
// key to the Users list and use UPN/Email instead. Users in an AD group
may not have a accessed the site
// yet , and so will not be in the userinfo list.
// I can get the users from the AD group using the graph HTTPClient. and
add them to the Users array
// in my state. Would also need to add a list of AD groups and their
members to my state.
// then in DoesUserHavePermission method, Just inlude permissions of any
ADQ Groups the user is in.
//
// Also should check for users that have been invited but not yet accessed
the site.
// graphHttpClient.get("v1.0/groups?$filter=displayName eq '" + user.Title
+ "'&$expand=members", GraphHttpClient.configurations.v1).then((response2)
=> {
// response2.json().then((data) => {
// //debugger;
// });
// }).catch((err) => {
// });
} else {
siteGroup.userIds.push(user.Id);
} also uncomment the getMembersOfAdGroup at line 308. hth

**Comment by russgove** [comment]
@kilicantplay ,
let me know if you need help with this.

**Comment by russgove** [comment]
hey @kilicantplay ,
I started working on this and hope to have it functional soon. would you be able to do some testing in your environment?

**Comment by russgove** [comment]
OK, got the ad groups working! @hugoabernier  or @kilicantplay  would you be able to do some testing before i issue a PR , or should I just do the PR. 

It works in my tenant, would like to make sure it works in others.

**Comment by hugoabernier** [comment]
@russgove go ahead and make the pr, I'll test it before accepting
