### ISSUE TITLE
Question: Dynamic Date required for Out of the box List View webpart

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1490]
## Question:  What props do I have to send to MSFT OOTB List View webpart to filter it?

I am making a webpart that needs to be able to send dynamic data to filter the MSFT Out of the Box List View webpart shown below:  (ID:  f92bf067-bc19-489e-a556-7fe95f508720)

![image](https://user-images.githubusercontent.com/49648086/92540330-3625c700-f212-11ea-880c-3830fe3f3705.png)

I have my webpart ready to send the data.  

Unfortunately **I just can't figure out what properties I need to send to this webpart.**

## What I have done so far:

I did do some digging… I found MSFT [sp-list-webpart_en-us.js](https://github.com/mikezimm/generic-solution/blob/ebff570146bb411a3d3cd66496ea0673f04f608f/src/webparts/genericWebpart/components/Contents/WParts/sp-list-webpart_en-us.js) in the console, beautified and copied it to my project so I could easily find what it might be looking for.  My goal was to find what properties the MSFT list component would send to another list component through dynamic properties if it were the Publisher, then just duplicate that.

I found .tryGetValues() on line 4845 of [sp-list-webpart_en-us.js](https://github.com/mikezimm/generic-solution/blob/ebff570146bb411a3d3cd66496ea0673f04f608f/src/webparts/genericWebpart/components/Contents/WParts/sp-list-webpart_en-us.js) it’s looking for this.properties.filterBy and my suspicion is that I also need to do something with this.properties.selectedTargetFieldId.  That's the 3rd line in my code shown below.

Further down around line 4853, it looks like it may be building up an object or something to create a rest call to filter the list.

Unfortunately, it’s a little to minified for me to reverse engineer what object(s) to send it.

My current theory (based on lines 4853) is that this.properties.filterBy may just be an array of “Values” if multiples were selected since on line 5015 in defineProperty filterBy is defined as “dynamicPropertyType: "object".
And this.properties.selectedTargetFieldId may be the field ID that I want to filter by.

I'm just not sure if I'm close or if I'm missing another key piece so I'm hoping someone has already done this :)

So you don't have to copy my file to VSCode to read it easily, here's the beautified MSFT code starting at my line 4843:
```typescript
if (this.properties && (this.properties.selectedListId || this.properties.showDefaultDocumentLibrary || this.properties.webRelativeListUrl)) {
    if (this._filterParams = "", this.properties.filterBy) try {
        var i = this.properties.filterBy.tryGetValues(),
            a = this.properties.filterBy._getPropertyPath(),
            o = this.properties.selectedTargetFieldId;
        if (this.properties.showFilterByControl) {
            if (i && i.length > 0 && o) {
                var d = "boolean" == typeof i[0],
                    m = "number" == typeof i[0];
                i.forEach(function(t, n) {
                    d ? t = "true" === t.toString() || "Yes" === t ? "1" : "false" === t.toString() || "No" === t ? "0" : void 0 : m && (t = t.toString()), e._filterParams = dr.a.addFilterInfoInQueryString(e._filterParams, {
                        filterField: o,
                        filterValue: t,
                        filterType: typeof e.properties.filterBy.tryGetValue(),
                        filterOperator: "In"
                    })
                })
            }
            s._TraceLogger.logVerbose(t._logSource, "** WPDD ** FILTER: " + this._filterParams + "\nSOURCE: " + a + ", TARGET: " + o + ", DATA: " + i + "\nTYPE: " + typeof this.properties.filterBy.tryGetValue() + ", ListUrl: " + this._getServerRelativeListUrl())
        }
    } catch (e) {
        s._TraceLogger.logError(t._logSource, new Error(e.message), "*** WPDD *** ERROR ERROR ERROR: " + e)
    } else s._TraceLogger.logVerbose(t._logSource, "*** WPDD *** filterBy was not set");
    this._fixUpListIfNecessary(function() {
        e._hasSetupItemScopes || e._setupItemsViewProperties();
        var t = e._getServerRelativeListUrl(),
            i = c.createElement($n, {
                pageContext: e.context.pageContext.legacyPageContext,
                listId: e.properties.selectedListId,
                webpartContext: e.context,
                serverRelativeListUrl: t,
                viewId: e.properties.selectedViewId,
                folderKey: e.properties.selectedFolderKey,
                title: e.properties.listTitle,
                isDocumentLibrary: e.properties.isDocumentLibrary,
                webpartHeight: n,
                isEditMode: r,
                forceRefresh: e.forceRefreshOnce,
                onTitleChange: e._onChangeTitle,
                onSelectionChange: e._onSelectionChange.bind(e),
                onListFieldsChange: e._onListFieldsChange.bind(e),
                currentPage: e.context.pageContext.legacyPageContext.isWebWelcomePage ? "HomePage" : void 0,
                theme: e._variantTheme,
                hideCommandBar: e.properties.hideCommandBar,
                itemsViewStore: e._store,
                itemsScopeItemKey: e._itemsScopeItemKey,
                initializer: e._initializer,
                parentItemKey: e._parentItemKey,
                filterParams: e._filterParams,
                getInitializeContextData: e._getInitializeContextData
            });
        l.render(i, e.domElement)
    })
}
```

Thanks for any help you may provide!

**Comment by hugoabernier** [comment]
@mikezimm this issue list is intended for issues regarding the sample web parts in this repository. 

You may be better served by reaching to Microsoft support or the tech community.
