### ISSUE TITLE
Filter WebPart "React Directory"

### ISSUE THREAD

**Issue by joshburns49** [pnp/sp-dev-fx-webparts#1491]
I know the webpart comes with a sort dropdown but is there a way to filter the people you see in the webpart "React Directory" so that only specific users are shown?

For example, filtering users by department or using a custom attribute?

**Comment by hugoabernier** [comment]
Thanks @joshburns49 but authors of samples don't get notified unless you take the time to fill the issue template fully.

I'll mark this issue as incomplete. Feel free to open a new issue so that we can get you the help you deserve!

Thanks for understanding!
