### ISSUE TITLE
Filter WebPart "React Directory"

### ISSUE THREAD

**Issue by joshburns49** [pnp/sp-dev-fx-webparts#1504]
## Sample (which sample are you talking about)

React directory

## Authors

@joaojmendes 

## Question (the more details, the better)

I know the webpart comes with a sort dropdown but is there a way to filter the people you see in the webpart "React Directory" so that only specific users are shown?

For example, filtering users by department or using a custom attribute?

**Comment by sudharsank** [comment]
Hi @hugoabernier,
Can you assign this issue to me? Let me enhance the web part with some features.

**Comment by joshburns49** [comment]
Thanks Sudharsan :)

**Comment by nehank08** [comment]
Can you please help me to sort them so that I don't see service accounts in the directory list? Can we do it by filtering in a way where we can say jobtitle is not null?

Please help!
