### ISSUE TITLE
Possible malware function in the library

### ISSUE THREAD

**Issue by turnikk** [pnp/sp-dev-fx-webparts#1505]
## Malware:

After the react-accordion installation to my SP website my app now gives a console warning:

Also there is a suspicious activity of the component
It calls this script:
https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_ru-ru_eab05e9a2f457ece6cfad2c5f98c1255.js

## Expected or Desired Behavior
No CSS attacks expected : )

## Observed Behavior
It looks like CSS attack
https://docs.microsoft.com/en-us/previous-versions/tn-archive/bb794823(v=technet.10)?redirectedfrom=MSDN

## Steps to Reproduce

1. Build the react-accordion.sppkg package
2. Install it
3. Open the console
4. Check the activity and watch the error

**Comment by hugoabernier** [comment]
@turnikk thanks for reporting this. Can you confirm that if you remove the react-accordion the suspicious activity goes away?

Also, can you provide the specific error message and suspicious activity that you found.

Thanks for your help!
