### ISSUE TITLE
React Manage Profile Card Properties Error

### ISSUE THREAD

**Issue by scottrayrader** [pnp/sp-dev-fx-webparts#1519]
I am working with this: [https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-manage-profile-card-properties.](url)
But, I am getting this error: 

interaction_required: AADSTS65001: The user or administrator has not consented to use the application with ID 'c021fc9d-701b-44d1-8911-19c6650b504f' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource. Trace ID: 805c1384-8c69-4227-b67e-44b8aeb6ae00 Correlation ID: 801b8098-0f36-4953-a3a0-c6d4898118c0 Timestamp: 2020-09-25 14:33:44Z

**Comment by hugoabernier** [comment]
Hey @scottrayrader, thanks for submitting this issue, but please note that unless you use the issue template that is provided, the sample author does not get notified.

As per the web part's instructions in the [Readme.md](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-manage-profile-card-properties), it looks like you need to authorize the web part by going to your SharePoint Admin center and going to **Advanced** then **API Access**.

I'll go ahead and mark this issue as closed. If you're still experiencing issues, please open a new issue and take the time to fill the issue template so we can get you the help you deserve.
