### ISSUE TITLE
react-manage-profile-card-properties error

### ISSUE THREAD

**Issue by scottrayrader** [pnp/sp-dev-fx-webparts#1524]
## Sample (which sample are you having trouble with)
react-manage-profile-card-properties
![React Manage Card Profiles Error](https://user-images.githubusercontent.com/66440860/94585370-eacd6a00-024d-11eb-9a02-e1181ea6d9bb.png)

## Authors
@joaojmendes 

## Expected or Desired Behavior
Webpart does not show up.

## Observed Behavior
Error: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.

# Environment Details (*Development & Target environment*)
SharePoint Online

## Additional context
I was receiving a previous error about API permissions. Those have since been granted.

**Comment by scottrayrader** [comment]
@hugoabernier can you add the help-wanted tag?

**Comment by PathToSharePoint** [comment]
I was trying to replicate the issue but I can't figure out how to enable API permissions for the online workbench. Does this Web Part require a full installation in order to run?

**Comment by derhallim** [comment]
@scottrayrader @PathToSharePoint Get the latest version of this webpart, it should be fixed in the new merge.

**Comment by Abderahman88** [comment]
Tested and it works. This issue can be closed @hugoabernier 

![FixWorking](https://user-images.githubusercontent.com/36161889/97177951-226cfa80-1797-11eb-9e9d-2223ff9057a1.PNG)
