### ISSUE TITLE
Let's make 'react-calendar' even better

### ISSUE THREAD

**Issue by edwardNuvision** [pnp/sp-dev-fx-webparts#1526]
## Sample (which sample are you talking about)
I'm talking about 'react-calendar'

## Authors
@hugoabernier 

## Suggestion (the more details, the better)
When a user is using React-Calendar webpart to add/edit an event, would it be possible to have a button to select whether it's a 'All Day' event? Currently, there's only an option to select if it's recurrence. 

Thank you

**Comment by hugoabernier** [comment]
Thanks @edwardNuvision, however, I'm not the author of the react-calendar sample.

It looks like a great idea. Hopefully someone in the community can help with this.

**Comment by PathToSharePoint** [comment]
I just looked at the solution, it's amazing that the author even implemented recurrence!

Is @joaojmendes the author? It would be interesting to hear from him first on why all day events were not implemented. I have spent quite some time working with classic calendar lists (the only lists that enable all day and recurrence), and the way timezones are handled is a mess.

Also a side note, we don't know how much longer those lists will be around now that Microsoft Lists have been released, with a calendar view of its own.

**Comment by PathToSharePoint** [comment]
Adding @derhallim as he is also listed as author.

**Comment by Abderahman88** [comment]
Some ideas for improvement?

**Comment by edwardNuvision** [comment]
Hello, I added 'All Day' checkbox to the app. I was kinda shy to share but hopefully find it useful. 

1. (event.tsx) file:
