### ISSUE TITLE
Ideas for React List Form improvements

### ISSUE THREAD

**Issue by hugoabernier** [pnp/sp-dev-fx-webparts#1540]
## Sample
React-List-Form

## Authors
@DanyWyss 
@Harshagracy 
@sharepointknight 

## Suggestion

It would be awesome to update this web part sample to use some more "modern" approaches. My suggestions include:
- Upgrade to SPFx 1.11
- Use PnP Reusable Controls 
	- WebPartTitle
	- Placeholder
	- ListPicker
- Use more "up-to-date" version of Fluent UI
- Fix icons
- Add better theme/section color support

Looking for volunteers! If you're interested, let me know. We can also break this issue into smaller ones to make it more manageable.

**Comment by sharepointknight** [comment]
I'll tackle these after I submit the cascading dropdown PR.

**Comment by sharepointknight** [comment]
I have this mostly complete but I am curious if you have some more information on what you are thinking for the following

- Use more "up-to-date" version of Fluent UI
- Add better theme/section color support

**Comment by AnkitSDesai** [comment]
@sharepointknight  Wandering if this webpart currently supports lookup field. or looks like you are working or already planning to do PR. this info will greatly help me to decide if I can start leverage and posibally changing per my requirement.

**Comment by sharepointknight** [comment]
Yes lookup fields are supported.
Ryan
    On Friday, October 16, 2020, 01:22:31 PM PDT, AnkitSDesai <notifications@github.com> wrote:  
 
 


@sharepointknight Wandering if this webpart currently supports lookup field. or looks like you are working or already planning to do PR. this info will greatly help me to decide if I can start leverage and posibally changing per my requirement.

**Comment by sharepointknight** [comment]
@hugoabernier This isn't done yet. I have the code mostly ready to complete this issue but finalizing the theme section support
