### ISSUE TITLE
React-Directory search filter

### ISSUE THREAD

**Issue by joshburns49** [pnp/sp-dev-fx-webparts#1542]
## Sample (which sample are you talking about)

React-directory

## Authors

@sudharsank 

## Question (the more details, the better)

I have a few users that will return when a user clicks one of the letter pivots but not when searching for their property i.e Department. They have all of the properties but just not returning when searched. I have checked the console for the array and query etc and the user is not in the array.

I have no idea why this is but I have checked their properties against users that are returning and they have identical properties. 

I don't think this is a problem with the web part as all other users who have the same department are returning, has anybody experienced a similar sort of thing or have any idea what the issue could be?

Any help would be much appreciated.

Thanks :)

**Comment by sudharsank** [comment]
Hi @joshburns49 
Maybe if you could share some screenshots with the users displaying their properties and the results based on the property search. 
- Have you checked the search query limit? 
- Have you tried to search the users based on the Firstname or Lastname property?

Please let me know the outcome.

**Comment by joshburns49** [comment]
Hi @sudharsank 

Thanks for your response :)

Maybe a stupid question but is the search query limit the row limit? if it is then 500 is nowhere near being exceeded.

When searching his FirstName he returns. We have added custom properties to the web part properties for Department and Office location (OfficeNumber) and when we search for the office it doesn't return his profile or when searching his department.

Thank you

**Comment by joshburns49** [comment]
Here is the user properties who isn't displaying in the searches. I have removed the name and Job title etc.

BaseOfficeLocation: null
Culture: "en-US"
Department: "Board of Directors, Senior Management Team"
DocId: "17592610660240"
DocumentSignature: "-7089976455908070469;4104174673123307989;5857699899413505604;4336925021035584329;2155401510302204377;-4961270880235482418"
FirstName: "G"
GeoLocationSource: "GBR"
GroupId: null
IsExternalContent: "false"
JobTitle: ""
LastName: ""
ListId: null
MobilePhone: null
OfficeNumber: "Cardiff"
PartitionId: "f07e5e75-3ef8-40db-b149-4bf7e65cde7e"
PastProjects: ""
PictureURL: ""
PreferredName: "G"
Rank: "0"
RenderTemplateId: "~sitecollection/_catalogs/masterpage/Display Templates/Search/Item_Default.js"
ResultTypeId: null
ResultTypeIdList: null
SPS-UserType: "0"
SiteId: null
Skills: ""
UniqueId: null
UrlZone: "0"
WebId: null
WorkEmail: 
WorkPhone: 
contentclass: "urn:content-class:SPSPeople"
piSearchResultId: "ARIAǂbd6b50c7-4ff5-477e-864a-f46762965d73ǂ0dc1ee41-37d7-478e-9eac-212e1c2a7a02ǂbd6b50c7-4ff5-477e-864a-f46762965d73.1000.1ǂ"

The search returns one other user with the same department and office. but should return 2 users.
![search webpart](https://user-images.githubusercontent.com/62754561/95607550-ce061300-0a53-11eb-99dc-c3f4b6baad00.png)

Thanks

Josh

**Comment by sudharsank** [comment]
@joshburns49,
Found the solution. The problem is if there is a space in the search key, we will replace it with **+**, but that was not working for **Department** but when I pass the value directly without replacing it works. Let me finalize the solution with some testing and will update the repo.

**Comment by joshburns49** [comment]
Brilliant, thanks @sudharsank 

It happens with other properties as well, he doesn't appear whilst searching officeName either. Not sure if this will be the same issue?

Thanks :)

**Comment by joshburns49** [comment]
Hi @sudharsank 

Think the problem is my custom result source, when i change the source id back to the local people results in the SPservices file. The user returns when searching for Department and Office.

Our result source is checking for departments at the moment and although the user has the department that is within the transform query in the result source he still isn't returning in the search. I have just created a site level result source to see if this will fix the problem, if not i will use the SPS-HideFromAddressLists i think. Looks to be what most other users are doing and seems to work.

Thanks for your help 👍

**Comment by sudharsank** [comment]
@joshburns49 
Glad to hear that, anyway I am working on the solution to include extra web part properties to mention the properties that should be passed directly without replacing the **spaces** to **+**

**Comment by sgtdonny** [comment]
Hello all,
i write here in this case causing i have a similar problem.
I expand the search to FirstName,LastName,PreferredName,WorkEmail,Department,**Title,Office,WorkPhone**
Title and Office doesn't work but i can search the workphone without problems.

I noticed the space problem. Here is a user profile from spo. Do you have a hint whats wrong?

Key                                Value                                                                                                                               
---                                -----                                                                                                                               
UserProfile_GUID                   7abb0324-97ec-4bc6-9c3b-f10fb7767c9a                                                                                                
SID                                i:0h.f|membership|100320007d1f6293@live.com                                                                                         
ADGuid                             System.Byte[]                                                                                                                       
AccountName                        i:0#.f|membership|erna@trainer.teams.adnlab.de                                                                                      
FirstName                          Erna                                                                                                                                
SPS-PhoneticFirstName                                                                                                                                                  
LastName                           Testos                                                                                                                              
SPS-PhoneticLastName                                                                                                                                                   
PreferredName                      Erna                                                                                                                                
SPS-PhoneticDisplayName                                                                                                                                                
WorkPhone                          **+4923271234320**                                                                                                                      
Department                         Entwicklung                                                                                                                         
Title                              **Engineer**                                                                                                                            
SPS-Department                     Entwicklung                                                                                                                         
Manager                            i:0#.f|membership|heinz@trainer.teams.adnlab.de                                                                                     
AboutMe                                                                                                                                                                
PersonalSpace                      /personal/erna_trainer_teams_adnlab_de/                                                                                             
PictureURL                         https://phoneman-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/erna_trainer_teams_adnlab_de_MThumb.jpg                     
UserName                           erna@trainer.teams.adnlab.de                                                                                                        
QuickLinks                                                                                                                                                             
WebSite                                                                                                                                                                
PublicSiteRedirect                                                                                                                                                     
SPS-JobTitle                       Engineer                                                                                                                            
SPS-Dotted-line                                                                                                                                                        
SPS-Peers                                                                                                                                                              
SPS-Responsibility                                                                                                                                                     
SPS-SipAddress                     erna@trainer.teams.adnlab.de                                                                                                        
SPS-MySiteUpgrade                                                                                                                                                      
SPS-ProxyAddresses                                                                                                                                                     
SPS-HireDate                                                                                                                                                           
SPS-DisplayOrder                                                                                                                                                       
SPS-ClaimID                        erna@trainer.teams.adnlab.de                                                                                                        
SPS-ClaimProviderID                membership                                                                                                                          
SPS-ResourceSID                                                                                                                                                        
SPS-ResourceAccountName                                                                                                                                                
SPS-MasterAccountName                                                                                                                                                  
SPS-UserPrincipalName              erna@trainer.teams.adnlab.de                                                                                                        
SPS-O15FirstRunExperience                                                                                                                                              
SPS-PersonalSiteInstantiationState 2                                                                                                                                   
SPS-DistinguishedName              CN=8e448d92-b8b4-4433-a113-015a3e3bd239,OU=f51854d4-7b77-448c-bf37-2782a77dcac3,OU=Tenants,OU=MSOnline,DC=SPODS187242,DC=msft,DC=net
SPS-SourceObjectDN                                                                                                                                                     
SPS-ClaimProviderType              Forms                                                                                                                               
SPS-SavedAccountName               i:0#.f|membership|erna@trainer.teams.adnlab.de                                                                                      
SPS-SavedSID                       System.Byte[]                                                                                                                       
SPS-ObjectExists                                                                                                                                                       
SPS-PersonalSiteCapabilities       4                                                                                                                                   
SPS-PersonalSiteFirstCreationTime  10/18/2019 11:52:25 AM                                                                                                              
SPS-PersonalSiteLastCreationTime   10/18/2019 11:52:25 AM                                                                                                              
SPS-PersonalSiteNumberOfRetries    1                                                                                                                                   
SPS-PersonalSiteFirstCreationError                                                                                                                                     
SPS-FeedIdentifier                                                                                                                                                     
WorkEmail                          erna@trainer.teams.adnlab.de                                                                                                        
CellPhone                                                                                                                                                              
Fax                                                                                                                                                                    
HomePhone                                                                                                                                                              
Office                             **3cx,AudioCodes**                                                                                                                      
SPS-Location                                                                                                                                                           
Assistant                                                                                                                                                              
SPS-PastProjects                                                                                                                                                       
SPS-Skills                                                                                                                                                             
SPS-School                                                                                                                                                             
SPS-Birthday                                                                                                                                                           
SPS-StatusNotes                                                                                                                                                        
SPS-Interests                                                                                                                                                          
SPS-HashTags                                                                                                                                                           
SPS-EmailOptin                                                                                                                                                         
SPS-PrivacyPeople                  True                                                                                                                                
SPS-PrivacyActivity                4095                                                                                                                                
SPS-PictureTimestamp               63721328012                                                                                                                         
SPS-PicturePlaceholderState        1                                                                                                                                   
SPS-PictureExchangeSyncState       1                                                                                                                                   
SPS-TimeZone                                                                                                                                                           
OfficeGraphEnabled                                                                                                                                                     
SPS-UserType                       0                                                                                                                                   
SPS-HideFromAddressLists           False                                                                                                                               
SPS-RecipientTypeDetails                                                                                                                                               
DelveFlags                                                                                                                                                             
msOnline-ObjectId                  8e448d92-b8b4-4433-a113-015a3e3bd239                                                                                                
SPS-PointPublishingUrl                                                                                                                                                 
SPS-TenantInstanceId                                                                                                                                                   
SPS-SharePointHomeExperienceState  2067                                                                                                                                
SPS-MultiGeoFlags                                                                                                                                                      
PreferredDataLocation     

Cheers 
Patrick
