### ISSUE TITLE
React-Carousel-Settings-not-working

### ISSUE THREAD

**Issue by sivanu137** [pnp/sp-dev-fx-webparts#1543]
## Carousel settings are not working
I have configured below settings
![image](https://user-images.githubusercontent.com/31919925/95672349-b34fad80-0bbd-11eb-851f-762635277e0a.png)
 but when I run this, I don't see any arrow marks, attached the output below.
![image](https://user-images.githubusercontent.com/31919925/95672394-fc076680-0bbd-11eb-91cd-25a951ef2808.png)

**Comment by hugoabernier** [comment]
@sivanu137 thanks for creating the issue, however I'm not the author of this sample.

**Comment by Harshagracy** [comment]
@sivanu137  It took me a while to figure out what is the issue in the code. The issue is with the CSS.
1) Remove overflow: 'hidden' 
![image](https://user-images.githubusercontent.com/14230498/96577780-c404cf80-12f1-11eb-9e5f-9ae4eef12361.png)
2) Add the following CSS as global css:
 ```
.slick-next,
    .slick-prev {
        background: "[theme: themePrimary, default: #0078d7]";
    }
    .slick-dots {
        position: initial;
    }
```

**Comment by sivanu137** [comment]
@Harshagracy  Thanks for your time, let me do the changes which you mentioned then revert back to you with the status :)
