### ISSUE TITLE
React Poll is not compatible with IE 11  browser

### ISSUE THREAD

**Issue by ABCSSIT** [pnp/sp-dev-fx-webparts#1547]
Hi,

This is the only POLL Webpart solution available from the SharePoint Community. Unfortunately, We are unable to add this to IE 11 as it is not supported and it is conflicting with Public CDN  Origin within SharePoint Community sites.

Any help would be much appreaciated.

**Comment by hugoabernier** [comment]
Hi @ABCSSIT , in order to get you the help you need, we need you to take the time to fill the issue template that is provided. 

Thanks for your understanding.
