### ISSUE TITLE
React Quick Poll does not render in IE 11

### ISSUE THREAD

**Issue by ccsummey** [pnp/sp-dev-fx-webparts#1548]
## Authors
@sudharsank

## Expected or Desired Behavior
React Quick Poll should render in IE 11

## Observed Behavior
React Quick Poll displays error message in IE 11 and also breaks additional web parts on page due to conflict with public CDN

## Steps to Reproduce
Add web part to modern SPO page. Publish and open in IE 11.

# Environment Details (*Development & Target environment*)
SharePoint Online - IE 11

**Comment by sudharsank** [comment]
@ccsummey 
Give me some time, I will update the solution to the latest version, and will fix the issue reported.

@hugoabernier Please assign this issue to me.
