### ISSUE TITLE
react-script-editor doest not display in the menu

### ISSUE THREAD

**Issue by MirasManica** [pnp/sp-dev-fx-webparts#1555]
Hello team, I have deployed the web part react-script-editor to our tenant for testing but I can not see it in the web part selection. First, I have tried to deploy it individually I added it to to store and then to the communication site. I could see it in the site content but I could not add it to the page. Second, I tried to change the json and automatically deploy it to the tenant anywhere and same issue. Do you have any idea what I am doing wrong? 

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor

![webparts](https://user-images.githubusercontent.com/54021786/96449889-c691f700-1215-11eb-92de-042d7a3c8451.png)
![store](https://user-images.githubusercontent.com/54021786/96449893-c72a8d80-1215-11eb-82ba-dcd2f29d9b43.png)

**Comment by Abderahman88** [comment]
Have you tried changing "ScriptEditorWebPart.manifest.json" ? (react-script-editor docs)

![deployModernScript](https://user-images.githubusercontent.com/36161889/96510178-6f177980-125d-11eb-9fc6-60c7d2c420df.PNG)

**Comment by MirasManica** [comment]
Yes, I have also tried to change this attribute and without success. Does it work on your side? If it works generally I will try it again. I am just not sure if is it just on my side or general issue.

**Comment by Abderahman88** [comment]
I installed the app with no issues on a communication site.

_Steps_
1. set "requiresCustomScript" to false
2. gulp bundle --ship / gulp package-solution --ship
3. install app in tenant app catalog
4. install react-script-editor on communication site

_Result_
![modernScript](https://user-images.githubusercontent.com/36161889/96591348-74210b00-12e7-11eb-8f59-801fb69f259c.PNG)

_Possible solution_
I found that some people had the same issue as you. They resolved it by applying some PowerShell. (see https://www.youtube.com/watch?v=Fz3NeLLKrpE - 10:30)

![reactionPowershell](https://user-images.githubusercontent.com/36161889/96591609-b6e2e300-12e7-11eb-9536-9a23826b8105.PNG)

**Comment by MirasManica** [comment]
Thank you for your help and time, it works! :)

**Comment by FoundryFounder** [comment]
Great tool...but I wish the paragraph at [https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites) said something like 'The webpart may not be available in the webpart selection menu on page insertion if "requiresCustomScript" is "true".'  

Also, note the misspelling of "available" in the following paragraph, [https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor#deploy-tenant-wide](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor#deploy-tenant-wide).
