### ISSUE TITLE
React Content Query Web part: Help or code snippet needed to format hyperlink output

### ISSUE THREAD

**Issue by JenniferUN** [pnp/sp-dev-fx-webparts#1561]
## Sample (which sample are you talking about)

React Content Query web part

## Authors
@PopWarner 
@hugoabernier 
@PaoloPia 

## Question (the more details, the better)

I've been using the content query web part for some time and it's fantastic. There is one small issue that I haven't been able to resolve and wondered if you could help.

When you display a hyperlink column it seems to output the URL and description as a single string. This means that the URL cannot be used in href tag.

Is there a way to strip away the description from the URL so that it can become a clickable link?

![image](https://user-images.githubusercontent.com/58151334/97105998-e6626880-16b6-11eb-9ab0-ce91d5a807a4.png)

**Comment by Abderahman88** [comment]
Hi @JenniferUN,

Yes, there is a way.

_Steps_
1. Open the property panel of the webpart
2. Go to 'Edit template content'
3. Change {{MyLinkField.textValue}} to {{{MyLinkField.htmlValue}}} _(use 3 curly brackets, not 2)_
4. Click on 'Save' and close

**Example**
![editHtml](https://user-images.githubusercontent.com/36161889/97122568-19444500-1727-11eb-93cc-2d53fb1d7591.png)

**Comment by JenniferUN** [comment]
> Hi @JenniferUN,
> 
> Yes, there is a way.
> 
> _Steps_
> 
> 1. Open the property panel of the webpart
> 2. Go to 'Edit template content'
> 3. Change {{MyLinkField.textValue}} to {{{MyLinkField.htmlValue}}} _(use 3 curly brackets, not 2)_
> 4. Click on 'Save' and close
> 
> **Example**
> ![editHtml](https://user-images.githubusercontent.com/36161889/97122568-19444500-1727-11eb-93cc-2d53fb1d7591.png)

Hi @Abderahman88 ,

Thank you very much! This is just what I needed!!! :)
