### ISSUE TITLE
React Content Query WebPart - lookup column additional fields value - again

### ISSUE THREAD

**Issue by Terenyeitamas** [pnp/sp-dev-fx-webparts#1570]
Hello!

Related issue: https://github.com/pnp/sp-dev-fx-webparts/issues/805
**I'm using the latest version of React Content Query webpart on Sharepoint Online.**

The fix isn't  working for me.

I have a list with one lookup field (üzletkód = shopcode in english)

![image](https://user-images.githubusercontent.com/64796596/97542535-2f703080-19c7-11eb-853e-0270d4226634.png)

![image](https://user-images.githubusercontent.com/64796596/97542568-457df100-19c7-11eb-93c0-9a71148d554c.png)

The settings works fine:

![image](https://user-images.githubusercontent.com/64796596/97542603-59c1ee00-19c7-11eb-895f-54fddb0bc9fb.png)

But in React Content Query webpart, the lookup field values are empty:

![image](https://user-images.githubusercontent.com/64796596/97542774-9b529900-19c7-11eb-92c5-78645485b77a.png)

This is the template: 

`<div class="dynamic-item-fields">
                      <span class='ms-DetailsRow-cell'><strong>shopcode: </strong>{{shopcode.textValue}}</span>
                    <span class='ms-DetailsRow-cell'><strong>shopcode_x003a_c_x00ed_m: </strong>{{shopcode_x003a_c_x00ed_m.textValue}}</span>
                    <span class='ms-DetailsRow-cell'><strong>shopcode_x003a_Ir_x00e1_ny_x00ed: </strong>{{shopcode_x003a_Ir_x00e1_ny_x00ed.textValue}}</span>
                    <span class='ms-DetailsRow-cell'><strong>shopcode_x003a_V_x00e1_ros: </strong>{{shopcode_x003a_V_x00e1_ros.textValue}}</span>
                  </div>`

When I changed textValue to rawValue or htmlValue the results are the same: nothing.

Thx,
Thomas

**Comment by Abderahman88** [comment]
I've tested this and I see the problem.

It has to do with the special characters in the field name. (à,é,...)
I think this is a bug and needs to be fixed.

![LookupFields](https://user-images.githubusercontent.com/36161889/97636630-b2ca6a00-1a39-11eb-806c-a9d88c07ca84.PNG)

**Comment by Abderahman88** [comment]
I'm working on the fix for this issue.

Almost there...

![WorkingViewField](https://user-images.githubusercontent.com/36161889/97640934-1bb5e000-1a42-11eb-94ea-07effe2c856f.PNG)

**Comment by Terenyeitamas** [comment]
For testing: "Irányítószám" = ZIP Code in English, and contains only numbers:
![image](https://user-images.githubusercontent.com/64796596/97693911-243e0300-1aa2-11eb-81a5-b7e70ab2034c.png)

**Comment by hugoabernier** [comment]
@Abderahman88 absolutely! I'll process all the pull requests later tonight,  feel free to update the Readme in your pull request. Otherwise, I'll add your name. Make sure to include your Twitter handle so we can promote the update on social media.

**Comment by kathyboilek** [comment]
Hugo,
You are such a good person 😚

**Comment by Abderahman88** [comment]
Thank you @hugoabernier 

I agree @kathyboilek 👍
