### ISSUE TITLE
react-faqapp - Entries over 100 elements are not displayed on site page

### ISSUE THREAD

**Issue by ChristianSaldivar** [pnp/sp-dev-fx-webparts#1573]
Hello Community!

first of all, thank you so much that this package exists at all, it is really a big relief!

I have noticed a strange behaviour.
Everything works fine, but if the SharePoint list has more than 100 entries, the entries above 100 will be not displayed.
e.g. entry 101, 102, ... are not displayed - all others under 100 will be displayed.

If I delete entries from the list (i.e. the entries are below 100), the newly created entries are also displayed.

Could any of you already notice the same phenomenon?
I already looked through the code but unfortunately i couldn't find anything with my investments to pass "the limit" (if it exists).

I would be very happy about feedback and help. :)

Thanks and have a nice day
Christian

**Comment by Abderahman88** [comment]
@ChristianSaldivar I've fixed the problem.

By default, the REST API showns only the first 100 items. (see documentation : https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest)

![First100](https://user-images.githubusercontent.com/36161889/97757731-9a238800-1afd-11eb-88fa-fe8756ec1736.jpg)

**Comment by ChristianSaldivar** [comment]
Hi **@Abderahman88**,

thanks for your response, fixing the problem and the explanation.
I have made the changes in my package and it works really good!! :)

Hope the package will be updated soon so more users can benefit from the changes.

Thank you very much and best
Christian
