### ISSUE TITLE
React Visio Web part not able to set the url properties

### ISSUE THREAD

**Issue by kanchankumbhar2** [pnp/sp-dev-fx-webparts#1583]
## Sample (which sample are you having trouble with)
[React Visio](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-visio)
## Authors
@joelfmrodrigues 

## Expected or Desired Behavior

After running gulp serve,It should allow to add the visio embed sample web part and should able to edit the properties to set the visio file URL

## Observed Behavior
After running gulp serve,It is allowing to add the visio embed sample web part, but after adding web part when I click on edit properties nothing is happening

## Steps to Reproduce

1. Download the source code from [here](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-visio)
2. open the solution in Visual Studio code
3. Run npm install
4. Run gulp serve
5.Add the web part on workbench page and try to edit the properties of it

# Environment Details (*Development & Target environment*)

- **OS**:  Windows 10 
- **Target Environment**:  SharePoint Online
- **Framework**:  Node.js v6/v8/v10/v12
- **Tooling**:  VS Code  and SPFx v1.10.0

**Comment by hugoabernier** [comment]
@kanchankumbhar2 thank you for filling the issue, but I'm not the author of this sample. You may get better results by tagging the actual author.

**Comment by kanchankumbhar2** [comment]
> @kanchankumbhar2 thank you for filling the issue, but I'm not the author of this sample. You may get better results by tagging the actual author.

Ya thank you. I have updated the Author

**Comment by Abderahman88** [comment]
@kanchankumbhar2 The webpart does not work in the local workbench.

![localWorkbench](https://user-images.githubusercontent.com/36161889/98403292-086dca80-2069-11eb-9808-2177469778a0.png)

If hosted on a SP-page, it works.

![hostedSP](https://user-images.githubusercontent.com/36161889/98403481-54b90a80-2069-11eb-9d35-d7fc4d6e9c48.PNG)

**Comment by hugoabernier** [comment]
@kanchankumbhar2 I hope that @Abderahman88's response helped you resolve this issue.

I'll mark the issue as closed, but don't hesitate to provide additional comments or open a new issue if you have additional issues with the solution.
