### ISSUE TITLE
Filter disabled accounts or not licensed account "React Directory"

### ISSUE THREAD

**Issue by sgtdonny** [pnp/sp-dev-fx-webparts#1584]
Sample (which sample are you talking about)
React directory

Authors
@joaojmendes 
@sudharsank 
@petkir_at 

Question (the more details, the better)

Hi,
the web part is really working fine.
But the results are showing not licensed members and disabled accounts. Also guest accounts are shown. The sharepoint search doesn't show this members.
Is there a way to hide this results?

Greeting
Patrick

**Comment by sgtdonny** [comment]
I think i have to adjust the search string that is transfered to the spo search.
Somebody now where is it set?

**Comment by sudharsank** [comment]
@sgtdonny I am afraid that there is no crawled property to check whether the user is licensed or disabled. So there is no direct method to query the search to find only the licensed and enabled users.

Maybe if someone has any ideas, please share it.

**Comment by sgtdonny** [comment]
@sudharsank 
I did some research and if it is the spo search api there is a refinement filter option. That option is blank at the moment and as i see not considered on the webpart.
i tested something liike this on another webpart with less features but finaable api string like
refinementfilters='WorkEmail:("*@contoso.com")

If we have the option to work with this filters there are many other constellations possible. This example hide guests cause it doesn't match.
