### ISSUE TITLE
React list form does not clear attachment field after save

### ISSUE THREAD

**Issue by SmitaNachan** [pnp/sp-dev-fx-webparts#1585]
## Sample (which sample are you having trouble with)
react-list-form (https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-list-form)

## Authors
Dany Wyss
Harsha Vardhini (@Harshagracy )
Ryan Schouten (@sharepointknight  )

## Expected or Desired Behavior
The list form should clear out the attachment field on save.

## Observed Behavior
The list form does not clear the attachment field. Due to this, while adding new item we have to manually remove the attachment from previous save.

## Steps to Reproduce

1. Deploy `React List Form` solution.
2. Add React List form web part to SharePoint Modern page.
3. Configure the web part to Choose list from options.
4. For `Form Type`, select the `New` option from web part property.
5. Add Attachment field.
6. Save the page.
7. Add new item with attachment using the web part
8. Click Save
9. All other fields clears out except attachment field.

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.18.0
- **Browser(s)**: Chrome v79 | FireFox v31 | Edge 
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by benkenawell** [comment]
In my quick testing, it looks like the attachment is _not_ being uploaded to the second item created, so this is probably more of the component not rerendering/updating or some state sticking around when it shouldn't.  I'd be happy to take this issue on and dive deeper into a fix if no one else is.

**Comment by hugoabernier** [comment]
@SmitaNachan this latest PR from @AriGunawan should solve the issue. Thanks @AriGunawan !
