### ISSUE TITLE
react-teams-message

### ISSUE THREAD

**Issue by nephinj** [pnp/sp-dev-fx-webparts#1592]
## Sample (which sample are you having trouble with)
react-teams-message

## Authors
@siddh_me

## Expected or Desired Behavior
Application loads as expected

## Observed Behavior
Application does not load and throws a timeout when loading

## Steps to Reproduce
npm install
gultp serve

# Environment Details (*Development & Target environment*)

-- running node:10.22.0 docker image
FROM node:10.22.0

EXPOSE 5432 4321 35729

RUN npm i -g gulp@3 yo @microsoft/generator-sharepoint@1.11.0

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx -p spfx && \
usermod -aG sudo spfx && \
chown -R spfx:spfx /usr/app/spfx 

USER spfx

CMD /bin/bash

**Comment by Abderahman88** [comment]
What error do you get? How many channels do you have?

I tried the webpart and it works. (also using node v10.22)

![loadingTeams](https://user-images.githubusercontent.com/36161889/98741969-ded8da00-23ad-11eb-8153-836cc73b7a3b.PNG)

**Comment by hugoabernier** [comment]
Hi @nephinj did you ever resolve this issue? I'll mark this issue as closed because there hasn't been any activity here for over two weeks, but feel free to open a new issue if you need more help.
