### ISSUE TITLE
react-property-bag-editor : Unable to build sspkg

### ISSUE THREAD

**Issue by svermaak** [pnp/sp-dev-fx-webparts#1596]
I have tried various different versions via NVM but not building, any ideas?
![image](https://user-images.githubusercontent.com/12259728/98598949-54ea2c00-232f-11eb-89d3-d925fcb9f3bd.png)

This is with v10.22.1 of NPM
![image](https://user-images.githubusercontent.com/12259728/98599511-291b7600-2330-11eb-8771-bc6a3f5c3d3f.png)

**Comment by Abderahman88** [comment]
Hi @svermaak,

This project is build in an old version of SharePoint Framework (1.0.0)

Based on the documentation (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility), you'll need node v6.
The first screenshot you provided, I see you running node v7. 
I suggest downloading node v6 and try again.

![nodeVersion](https://user-images.githubusercontent.com/36161889/98737766-ff516600-23a6-11eb-9881-7504daabe7c0.png)
