### ISSUE TITLE
Sample js-powerbi-embedded - unable to gulp serve or bundle without error

### ISSUE THREAD

**Issue by ShawnPOWER** [pnp/sp-dev-fx-webparts#1597]
## Sample (which sample are you having trouble with)
js-powerbi-embedded

## Authors
@rolandoldengarm 

## Expected or Desired Behavior
Desired outcome is to be able to successfully gulp serve after npm install. As well as to be able to successfully gulp bundle and package-deploy.

## Observed Behavior
An error exists in file PowerBiEmbeddedWebPart.ts

**Error received during "gulp serve", similar error during "gulp bundle --ship" which prevents package-solution from functioning:**
[12:03:51] Error - typescript - src\webparts\powerBiEmbedded\PowerBiEmbeddedWebPart.ts(9,22): error TS2656: Exported external package typings file 'C:/myPathGoesHere/sp-dev-fx-webparts/samples/js-powerbi-embedded/node_modules/powerbi-client/dist/powerbi-client.d.ts' is not a module. Please contact the package author to update the package definition.
[12:03:51] Error - 'typescript' sub task errored after 1.42 s
 "TypeScript error(s) occurred."
[12:03:51] 'serve' errored after 2.61 s

## Steps to Reproduce

1. clone repo
2. npm install
3. gulp serve (receive error)
4. or gulp bundle --ship (receive error)

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chromium Edge v86
- **Tooling**: VS Code
- **Additional details**: N\A

## Additional context
N\A

**Comment by hugoabernier** [comment]
@ShawnPOWER thanks for reporting this issue.

This sample was built on a version if SharePoint Framework before SPFx was generally available (GA). It won't work on a NodeJs v10 version.

I recommend that you create a new SPFx solution using the Yeoman generator and copy the code from [/src/webparts/powerBiEmbedded/PowerBiEmbeddedWebPart.ts](https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/js-powerbi-embedded/src/webparts/powerBiEmbedded/PowerBiEmbeddedWebPart.ts) in the sample -- minus the hard-coded access tokens to get you started.

Let us know if you need more help getting you started with your new web part.

And if you upgrade the sample, feel free to submit your upgraded sample to the repository to help others in the future!
