### ISSUE TITLE
react-graph-telephonedirectory -- InteractionRequiredAuthError in Work Bench 

### ISSUE THREAD

**Issue by m-rkhan** [pnp/sp-dev-fx-webparts#1598]
react-graph-telephonedirectory

@Dips_365 @aimery_thomas

I am trying to use the workbench in a SharePoint tenant. When I add the solution to the App Catalog and deploy it normally it works, but in the Work bench I am receiving this message: 

InteractionRequiredAuthError: AADSTS65001: The user or administrator has not consented to use the application with ID '7f674932-faa0-4eb6-8b64-0051c9101b97' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.
Trace ID: a95833c4-5c75-47b2-b8d1-3806b7865000
Correlation ID: df5be372-feb5-4d32-9b0a-b4d77203d6b7
Timestamp: 2020-11-11 22:22:01Z

I have approved the requests in the API access
![image](https://user-images.githubusercontent.com/43222645/98886341-7c3d1800-2459-11eb-9987-d9c21884a264.png)

My understanding is this should work in the work bench on the tenant and reach to graph. What can I try to troubleshoot this? 

Thanks

**Comment by Abderahman88** [comment]
I got it working on my local workbench :man_shrugging:

Are you using the latest version of the webpart?

![telephoneLocal](https://user-images.githubusercontent.com/36161889/99158183-7e5cdc00-26d0-11eb-8765-29e6af1ae4b4.PNG)

**Comment by m-rkhan** [comment]
Yes I have the latest version.

I notice you are on the local workbench. Are you able to reach microsoft graph from your local bench? 

It loads like this fine for me, but when I search it throws that error I mentioned. 

Thanks

**Comment by Abderahman88** [comment]
@m-rkhan The graph calls will not work on the local workbench. (This is normal)

It will work on the hosted workbench (https://**your-sharepoint-tenant**.sharepoint.com/_layouts/15/workbench.aspx)

Try it out 👍

**Comment by m-rkhan** [comment]
Yes exactly. I'm actually using workbench in the tenant(https://your-sharepoint-tenant.sharepoint.com/_layouts/15/workbench.aspx) and getting this error: 

MSGraphService.ts:132 InteractionRequiredAuthError: AADSTS65001: The user or administrator has not consented to use the application with ID 'f15f8a86-f10f-4d59-a6be-8de2119ae054' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.
Trace ID: 383b6d40-dce6-4eed-ab49-ce0fdf095100
Correlation ID: b51dd59c-e703-45c9-a6ed-dda0aee84fe5
Timestamp: 2020-11-19 16:02:35Z


Any idea what is causing this? Or how I can troubleshoot it.

**Comment by hugoabernier** [comment]
Hi @m-rkhan did you ever resolve this issue?

**Comment by m-rkhan** [comment]
@hugoabernier Nope, I am receiving the same issue in the tenant work bench when I try to reach microsoft graph. 

When I deploy the solution in the app catalog it works. 

I have not been able to figure out why it does not work in the work bench.

Is there anything I can provide to help troubleshoot this?

**Comment by hugoabernier** [comment]
@m-rkhan based on the error, it seems to point to API permissions that were not granted. I know you showed that the permissions are approved in the admin center, but can you confirm that you're testing this app in your own development tenant vs your employer's production tenant, and that you have full permissions to grant permissions in SharePoint and/or Azure AD?

**Comment by m-rkhan** [comment]
@hugoabernier I've just tested it in a development tenant. I am a global administrator, and the API request has been approved. 

I am currently receiving the same error.

**Comment by Abderahman88** [comment]
@m-rkhan Can you check something?

1) Go to https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade (Azure Portal -> App registrations)
Do you see the webpart 'react-graph-telephonedirectory-client-side-solution'? If yes, click on it.

![appRegs](https://user-images.githubusercontent.com/36161889/101053717-68805f80-3588-11eb-9779-05594248707c.PNG)

2) Go to 'API Permissions'

![ApiPermissons](https://user-images.githubusercontent.com/36161889/101054218-f3615a00-3588-11eb-9065-c8cbfd9e911a.png)

3) Normally you'll see the graph-permissions. Are they approved by the admin?

![PermGranted](https://user-images.githubusercontent.com/36161889/101054647-64a10d00-3589-11eb-97ce-6e60468e2087.png)

**Comment by m-rkhan** [comment]
This is what I am seeing: 
![image](https://user-images.githubusercontent.com/43222645/101114338-ddfb2880-35a6-11eb-9f58-7d92a1197cc8.png)

@Abderahman88

**Comment by Abderahman88** [comment]
Looks to me OK.

Have you also tried putting the webpart on another site?

**Comment by m-rkhan** [comment]
@Abderahman88  Yes I did try it in different sites, not working on the work bench.

 Also in different tenants, I am seeing the same behavior.

**Comment by Abderahman88** [comment]
@m-rkhan 

Can you also check the  API-permissions for 'SharePoint Online Client Extensibility Web Application Principal' ?
Is everything consented by the admin?

(portal.azure.com --> App registrations --> 'SharePoint Online Client Extensibility Web Application Principal' --> API permissions)

**Comment by m-rkhan** [comment]
@Abderahman88 
That did it! Thanks!
I added permissions to Directory.Read.All and User.Read, and granted admin consent. 

Is this something that needs to be documented some where?

**Comment by Abderahman88** [comment]
Normally this will be automatically added if API permissions are consented in the SharePoint admin center.

Maybe something went wrong behind the screen 😄 

Happy it's solved!
