### ISSUE TITLE
react-birthdays samples doesn't display Birthdays

### ISSUE THREAD

**Issue by MrFearLess98** [pnp/sp-dev-fx-webparts#1599]
## Sample (which sample are you talking about)
react-birthdays

## Authors
@joaojmendes 

## Question (the more details, the better)

I have imported the react-birthdays app to the App Catalog and approved the API permissions without any issues, and created the "Birthdays" list as required.

When I add the Birthdays web part to a page and publish the page nothing is being displayed knowing that I have created around 6 records in the Birthdays list.

## Question
I checked the **local.settings.json** file and changed the Tenant URL with Tenant ID and imported the app again with no luck.

`{
  "IsEncrypted": false,
  "Values": {
    "GraphClientId": "",
    "GraphClientSecret": "",
    "TenantId": "GUID",
    "TenantUrl": "https://212.sharepoint.com/",
    "BirthdayListTitle": "Birthdays"
  }
}`

I believe I should fill the GraphClientId and GraphClientSecret variables but where I can find these values for I fill them in the code?

Please refer to the below screenshots:
![Capture](https://user-images.githubusercontent.com/52073639/98938816-2b78fe00-24f1-11eb-8cfb-57696b333039.PNG)
![Capture1](https://user-images.githubusercontent.com/52073639/98938844-35026600-24f1-11eb-82cf-a57e355036aa.PNG)
![Capture2](https://user-images.githubusercontent.com/52073639/98938855-37fd5680-24f1-11eb-8b90-ea1bcd6649dd.PNG)

Any help will be greatly appreciated.
Thank you!

**Comment by srinubhumadi** [comment]
It  is not working for me also. Could you please upload the working sample

**Comment by Abderahman88** [comment]
I got the webpart working.

### Steps
1. Create 'Birthday'-list on the **root**-site. (see README)
2. **Very important** : create a column index on the field 'Birthday' (see README)
3. Package and deploy the webpart
4. Approve API permissions
5. Install the webpart

**Remarque**: To get the right results, you need to set the birthday's in the year 2000 (issue in the filter -> bug)

![BirthdayList](https://user-images.githubusercontent.com/36161889/99306366-6b274900-2855-11eb-805a-08481ceb8c60.PNG)

![ReactBirthday](https://user-images.githubusercontent.com/36161889/99305607-49799200-2854-11eb-8087-c154216d95d6.PNG)

**Comment by MrFearLess98** [comment]
Hello Abdedrahman,

Thanks for your reply and the details you provided.

After I have created the list on the **root site** it works as expected.

Best regards,
MrFearLess

**Comment by srinubhumadi** [comment]
How to get the user picture in the birthday webpart.
Can we create a column in List to save the profile picture?
Can you help me on displaying the profile picture

**Comment by MrFearLess98** [comment]
@srinubhumadi 

To get the user profile picture every user should upload his profile picture from [https://eur.delve.office.com/](Delve Office).
After that, automatically the user profile picture will be displayed not just in the Birthdays web part but in the whole organization.

Hope it helps.

**Comment by srinubhumadi** [comment]
Hi MrFearLess98,

Thank you for the quick response .But still after uploading in the given location unable to view it in the webpart.
Anything else we need to check
