### ISSUE TITLE
React Content Query webpart - field begins with a special character

### ISSUE THREAD

**Issue by acsaba31** [pnp/sp-dev-fx-webparts#1600]
Hi,

I would like to report a bug:
Related Issue: #1570 

I'm using the latest version of React Content Query webpart on Sharepoint Online.

I have a list with several columns with several special caracters:
![image](https://user-images.githubusercontent.com/66116839/99060121-dd6f0380-259f-11eb-9565-b0ec9b4462e8.png)

Column contains special caracter, this works fine. (example: "Ismerősöd ügyfélszáma (00-ák nélkül)" field -> Ismer_x0151_s_x00f6_d_x0020__x00 )
 
When the field begins with a special character, according above example ( Ügyfélszám -> _x00dc_gyf_x00e9_lsz_x00e1_m ) the webpart doesn't display anything. I tried to add 'OData_' prefix because it would be the "real" internal name of field but it didn't work.

![image](https://user-images.githubusercontent.com/66116839/99064172-db0fa800-25a5-11eb-9f78-dcf15168d1b8.png)

![image](https://user-images.githubusercontent.com/66116839/99064254-fed2ee00-25a5-11eb-86c3-0bb355c03b59.png)

Thanks, 
Cs.

**Comment by Abderahman88** [comment]
I'll check this out.
@hugoabernier Can you assign this to me?

**Comment by Abderahman88** [comment]
@acsaba31 I made a fix for it. ⛑️ 

![fixSpecialChar](https://user-images.githubusercontent.com/36161889/99157914-7f403e80-26cd-11eb-8554-3a8ac5fd082c.png)

**Comment by acsaba31** [comment]
many thanks for all !
