### ISSUE TITLE
React-RSSReader SPFX web part CDN deployment 

### ISSUE THREAD

**Issue by Truez** [pnp/sp-dev-fx-webparts#1604]
Can anyone advise what I need to do in order to get this web part to deploy to the Office 365 CDN please? 

Details below around my experiences! 

I've got a copy of the project and followed the guidlines around deploying an SPFX web part to a Office 365 CDN. This is on both a dev and production tenant! 

For the React-RSSReader Sample I am getting a screen that states 

This client side solution will get content from the following domains:

HTTPS://SPCLIENTSIDEASSETLIBRARY/ ; https://cdnjs.cloudflare.com

I believe this should be SharePoint online! 

I am assuming this is something to do with the web part being developed before this feature was available as I have completed the helloworld tutorials and that displays

This client side solution will get content from the following domains:

SharePoint Online 

as expected! 

I then tried the same gulp commands with the React-Rssreader and receive the following error.
Error: Your dev environment is running NodeJS version v10.23.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0

If I switch back to 8X the gulp commands work but I still cannot deploy the web part to the office 365 CDN.

Cheers 

Truez

**Comment by hugoabernier** [comment]
@Truez as you've already gathered the sample was built for an older version of SPFx. I recommend that you use

the [CLI for Microsoft 365 SPFx project upgrade](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade/) command to upgrade the project.

Once you're done, feel free to submit the updated sample as a pull request so that others in the community can benefit from your contribution.

I'll go ahead and close this issue. If you need more help, please open a new issue and take the time to fill the issue template that is provided so we can get you the help you deserve.

**Comment by Truez** [comment]
@hugoabernier after getting this project upgraded it still doesn't show SharePoint online as expected.

I assume that the https://cdnjs.cloudflare.com is because some of the JS files are referenced from this location and I am guessing the HTTPS://SPCLIENTSIDEASSETLIBRARY/  is sharepoint online.

I just assume because it was genenrated from an older version it's never going to show SharePoint online.

Does anyone know how this is set within the project? 

Cheers 

Truez

**Comment by hugoabernier** [comment]
@Truez now that the web part is upgraded, you may be seeing references to libraries that are referred from within the code. For example, `moment` is referred from `cdnjs.cloudflare.com`.

By the way, I just processed a Pull Request which upgrades the RSS Reader web part to SPFx 1.11. You can find it at https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-rss-reader.

I can confirm that the latest version stores its assets in the `CLIENTSIDELIBRARY` with the exception of external resources (like `moment`).
![With moment.js as an external resource](https://user-images.githubusercontent.com/13972467/99981461-6a237980-2d77-11eb-9847-1db4abc0bfc8.png)

If you remove the `config/config.json` section that instructs to include `moment` as an external resource, and re-build, re-bundle, and re-package the solution, you won't get the external reference anymore:

```json
  "externals": {
    "moment": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js",
      "globalName": "Moment"
    }
  },
```

![With moment.js as a bundled resource](https://user-images.githubusercontent.com/13972467/99981937-f3d34700-2d77-11eb-94ba-3065460f3e80.png)
