### ISSUE TITLE
Localisation strings not found after upgrade react-rssreader 

### ISSUE THREAD

**Issue by Truez** [pnp/sp-dev-fx-webparts#1607]
After upgrading rss reader sample import * as strings from 'RssReaderWebPartStrings'; no longer finds module. Any ideas why? 

After upgrading the React-RssReader sample gulp build is throwing the following error in multiple files.

Cannot find module 'RssReaderWebPartStrings

From what I think i know this is the module that defines the string values for the localized files.

I can see that mystrings.d.ts exists - > C:\Users\XXXX\Desktop\react-rss-reader\src\webparts\rssReader\loc\mystrings.d.ts
I can also see a en-us.js file -> C:\Users\XXXX\Desktop\react-rss-reader\src\webparts\rssReader\loc\en-us.js

Checked the cofig.json 

"localizedResources": {
    "RssReaderWebPartStrings": "lib/webparts/rssReader/loc/{locale}.js",
    "PropertyControlStrings": "node_modules/@pnp/spfx-property-controls/lib/loc/{locale}.js",
    "ControlStrings": "node_modules/@pnp/spfx-controls-react/lib/loc/{locale}.js"
  }

After checking the above I checked the lib location -> C:\Users\XXXX\Desktop\react-rss-reader\lib\webparts\rssReader\loc\en-us.js exists 

On comparison between old and new project I can't see not much(if anything) has changed in terms of where the files are located so I am left wondering why the following doesn't find the module 

import * as strings from 'RssReaderWebPartStrings';

Cheers 

Truez

**Comment by Abderahman88** [comment]
Hi @Truez 

To which version did you try to upgrade?
Did you start from a new project or used M365 CLI?

_Some things you can try:_
1) Close and re-open VS code
2) re-install node-modules

**Comment by Truez** [comment]
Hi @Abderahman88,

Upgraded to the latest using M365 Cli.

Tried the shutting down VS Code as I was wondering if it was a quirk with VS Code but nothing changed. Also tried reinstalling the node modules but still get the same issue.

Cheers 

Truez

**Comment by Abderahman88** [comment]
I will try to update this project.

**Comment by Abderahman88** [comment]
Hi @Truez,

I successfully updated the webpart.

The issue was a missing line in tsconfig.json. ("src/**/*.ts")

```
 "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
```

It was missing in the output of the M365 CLI report.

**Comment by Truez** [comment]
Hi @Abderahman88,

Thats what was missing for me also! 

Does this mean theres a bug in the M365 CLI?  I assume by missing this line it doesn't account for these files in the project? 

Cheers 

Truez

**Comment by Abderahman88** [comment]
It's not really a bug. (see discussion: https://github.com/pnp/cli-microsoft365/issues/1857)
