### ISSUE TITLE
React-Directory:  reusing in my SPFx project

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1609]
## Sample (which sample are you talking about)
[React-Directory](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-directory)

## Authors
@sudharsank  @petkir @joaojmendes 

## Question (the more details, the better)
I was looking for a component to bring into my webpart to render people info and would like to re-use portion of this sample in my project.

## In short, I want to show people based on specific SharePoint groups.
My webpart can get an array of users based on either pnp, or maybe the search query could be modified to search based on SharePoint Group if I have something to search on?

If not, I can easily get a group and the email addresses of the people and search based on that.

## More detailed questions
My main question what parts (files) of the sample do I need to copy into my project and what things don't I need?
I have not used hooks yet and my webpart which is pretty complex to start with so I'm looking for simple at this point.

## More information
In my first screenshot, I marked the things I think I need in green, the things I know I don't need in red.
Just was not sure about the DirectoryHook files.

Second screenshot highlights what parts of the sample I'm looking for
Red parts I can either do without or would re-purpose (like have group selector)
Yellow parts I could do without to make it simpler but might be helpful to have
Green parts show what I need to have.

Thanks for any input!

![image](https://user-images.githubusercontent.com/49648086/99860054-e8a5ce80-2b5f-11eb-9a19-506718d30aa0.png)

![image](https://user-images.githubusercontent.com/49648086/99860065-ee9baf80-2b5f-11eb-8fc1-bcaad38968c9.png)

**Comment by petkir** [comment]
Hi @mikezimm 

you are right, you will not need the Mock Service, this is only for testing at localhost.
loc Folder ist for multilingual support.

About the DirectoryHook:
if you look int the DirectoryWebPart.ts file you find these lines
```
 // Directory,
// {
//     title: this.properties.title,
//     context: this.context,
//     searchFirstName: this.properties.searchFirstName,
//     displayMode: this.displayMode,
//     updateProperty: (value: string) => {
//         this.properties.title = value;
//     }
// },
DirectoryHook,
{
   title: this.properties.title,
   context: this.context,
   searchFirstName: this.properties.searchFirstName,
   displayMode: this.displayMode,
   updateProperty: (value: string) => {
     this.properties.title = value;
   },
   searchProps: this.properties.searchProps,
   clearTextSearchProps: this.properties.clearTextSearchProps,
   pageSize: this.properties.pageSize
  }
````
currently, the web part use `DirectoryHook.tsx` not `Directory.tsx`
so for you can choose one file of this two. 
`IDirectoryProps.ts` and IDirectoryState.ts you will need.

I hope this will help you to make a great web part.

**Comment by sudharsank** [comment]
Hi @mikezimm,
As @petkir mentioned, the latest directory web part is using **DirectoryHook.tsx** with **IDirectoryProps.ts** and **IDirectoryState.ts**. You need the below two folders too

- **Pagination** - Paging support for the results
- **PersonaCard** - Live Persona card on hover.

**Comment by hugoabernier** [comment]
Hey @mikezimm , I hope that the information from @petkir and @sudharsank helped you solve the issue?

I'll go ahead and mark this as closed. Feel free to open a new issue if you need more help.
