### ISSUE TITLE
Possible to use Fluent UI Icons in react-content-query-webpart?

### ISSUE THREAD

**Issue by PaulieShore** [pnp/sp-dev-fx-webparts#1614]
## Sample
react-content-query-webpart

## Authors
@PopWarner 
@hugoabernier 
@PaoloPia 

## Question
First of all, thank you for this amazing repo. I'm looking to use Fluent UI icons in the react-content-query-webpart templating. 

![image](https://user-images.githubusercontent.com/1333865/100389958-47a69000-3005-11eb-976e-924606f116f4.png)

I think I need to import the icons but I'm a little lost as to what to include there. I'm also not sure what's included with ~office-ui-fabric-react/dist/sass/References.scss. Any help would be greatly appreciated. Thanks again.

**Comment by PathToSharePoint** [comment]
Did you follow the instructions here:
https://developer.microsoft.com/en-us/fluentui#/styles/web/icons

They are for both Fluent UI and UI Fabric. I believe Fluent UI is the recommended way, while UI Fabric is still working but deprecated.

**Comment by PaulieShore** [comment]
I'm attempting to use the icons with the built in template editor of the react-content-query-webpart. I tried including initializeIcons but I don't think that's going to allow me to use Fabric Core in the template editor.

**Comment by PathToSharePoint** [comment]
I see, you are talking about the Handlebars template, not the Web Part code itself.

Your template looks fine, but what seems to be missing is the stylesheet to render the icons. As far as I can tell there would be 3 ways to load it: via the Web Part, via the template, or via the page.

I am not sure what would be the best way, and the authors might want to chime in. I did a quick test with the stylesheet included at the top of the Handlebars template and it seems to work:

```
<link
  rel="stylesheet"
  href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css"
/>
```
Source: https://docs.microsoft.com/en-us/javascript/api/getstarted/getstartedpage?view=office-ui-fabric-react-latest

**Comment by hugoabernier** [comment]
@PaulieShore it looks like @PathToSharePoint 's answer should take care of the issue.

I'll go ahead and close this issue as answered. Feel free to open a new issue if you're still running into more issues.
