### ISSUE TITLE
npm install error on react-display-hierarchy

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-webparts#1615]
## Sample (which sample are you having trouble with)
react-display-hierarchy

## Authors
Nanddeep Nachan (SharePoint Consultant, @nanddeepnachan @nanddeepn  )
Ravi Kulkarni (SharePoint Consultant)

## Expected or Desired Behavior
**npm install** installs the dependencies.

## Observed Behavior
I am getting the following error:
Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.

## Steps to Reproduce

1. Open the sample in VS Code
2. Run npm install
3. See error

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: N/A
- **Framework**: N/A
- **Browser(s)**: N/A
- **Tooling**: VS Code, Node.js v10
- **Additional details**: googling tells me there are vulnerabilities associated with  'event-stream@3.3.6'

## Additional context
Side note, I am surprised to see a shrinkwrap file in the sample, I never saw that in other samples.

**Comment by nanddeepn** [comment]
Thanks for reporting. I will look into this error.

**Comment by nanddeepn** [comment]
Hi @PathToSharePoint 
I tried `npm install` and it seems to be working fine with `Node v10.19.0`
I see a note from you about shrinkwrap file. Looks like you are using old version of this web part.
Can you please try the [newer version of this web part](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-display-hierarchy) upgraded with `SPFx v1.11.0`

**Comment by PathToSharePoint** [comment]
My mistake! I ran a `git pull` but didn't notice it failed. After a complete re-cloning, npm install works just fine.

Could you explain why the shrinkwrap file was in a previous version and not the latest one? It's actually something I was wondering about: should I run `npm shrinkwrap` when creating a sample?

**Comment by nanddeepn** [comment]
Hi @PathToSharePoint 
The web part `react-display-hierarchy` was developed couple of years back with `SPFx v1.6.0` and we used `npm shrinkwrap` to lock down the npm package dependencies, but now that it is handled through `package-lock.json`

Please see if your custom `OrgChat` list is following the same schema as defined [here](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-display-hierarchy) for the `Hierarchy` list.

**Comment by PathToSharePoint** [comment]
I see, thanks for the explanation. Note that package-lock.json is not a full replacement for shrinkwrap, so both still have their place.

As for the list, I added the URL column that was missing, but that didn't make a difference. The issue is actually that the query doesn't even pick the new name in the property pane. Here is the full error message:
`Please verify webpart configuration. Error details: Error making HttpClient request in queryable [404] Not Found ::&gt; {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List 'Hierarchy' does not exist at site with URL 'https://pathto.sharepoint.com/sites/TransferRequest'."}}}`

For the record, I am working on my own org chart Web Part, that's why I was interested to see your work :-)
https://twitter.com/Path2SharePoint/status/1321212700827873281

**Comment by hugoabernier** [comment]
Hey @PathToSharePoint I've closed this issue because this issue was related to an old version of the web part.

If you'd like to continue having a discussion regarding the other issues you mention in this list, feel free to open a separate issue so we can track it accordingly.

Also, please continue using GitHub to discuss issues instead of a broadcast message on Twitter. We're trying to keep all information related to issues in one place. Thanks.
