### ISSUE TITLE
react script editor on-prem not loading 

### ISSUE THREAD

**Issue by kmarkovbsh** [pnp/sp-dev-fx-webparts#1617]
I have a issue with making the [script editor on-prem ](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor-onprem)
 work on SP2019, the issue is that the webpart isn't loading all the time.
We use custom master page in classic view and custom layouts.
all the pages have tabs that are build with jQuery and the names of the tabs come from SP columns.
When we place the webpart in the first tab it loads, when it is in other tabs it loads, but when in the tabs we have content like images it wont load it gets stuck on "loading [webpartname]" 
we checked for unclosed tags in the html but all tags are closed, we made a script to replace all img tags with divs and set background on them and the webpart works.

No errors, or warnings are displayed in the browser console it just gets stuck on loading.
Tested on IE 10/11, chrome.

In edit mode works like a charm in all browsers.
Sometimes when Cntrl F5 it loads but that's a 1 in 20 tries.
SP is with the lattes patches.

**Comment by hugoabernier** [comment]
@kmarkovbsh we need you to provide the information required in the issue template in order for us to help you.

I'm going to close this issue as incomplete. Feel free to open a new issue. And, when you do, make sure to provide all the information we ask in the [new bug template](https://github.com/pnp/sp-dev-fx-webparts/issues/new?assignees=&labels=type%3Abug&template=bug.md&title=)
