### ISSUE TITLE
Let's make SAMPLE even better

### ISSUE THREAD

**Issue by ironbeardYYC** [pnp/sp-dev-fx-webparts#1619]
## Sample (which sample are you talking about)
react-accordion-dynamic-section

## Authors
@hugoabernier 

## Suggestion (the more details, the better)
It should be made clear in the set-up instructions that the choice field needs to be explicitly titled Category.
While there is currently this instruction "The web part expects a choice type that will be used as Category.", this sounds like you just need to provide at least one choice field to be used as a category. As well the option to select a category field, makes it seem like it could be any choice field. But this does not appear to be the case as I get 500 error on /getitems request if the choice field isn't explicity titled Category.

**Comment by hugoabernier** [comment]
Updated documentation to reflect this.
