### ISSUE TITLE
react-display-hierarchy: Web Part doesn't react to property change.

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-webparts#1620]
## Sample (which sample are you having trouble with)

react-display-hierarchy

## Authors

Nanddeep Nachan (SharePoint Consultant, @nanddeepnachan @nanddeepn  )

## Expected or Desired Behavior

When the site doesn't have a list named Hierarchy, another list that follows the schema can be used.

## Observed Behavior

Once the error message gets displayed because the Hierarchy list can't be found, the error remains even after I update the list name in the property pane.

## Steps to Reproduce

1. Open the online workbench on a site that does not have a Hierarchy list.
2. Add the Web Part. An error is displayed AS EXPECTED because Hierarchy doesn't exist.
3. Open the property pane
4. Update the list name
5. Nothing happens.

Note: if I then reload the page, the Web Part works.

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: Chromium Edge
- **Tooling**: VS Code / online workbench
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

## Additional context

Follow up on issue #1615

**Comment by nanddeepn** [comment]
Thanks @PathToSharePoint for reporting.
I will look in to this.
