### ISSUE TITLE
react-my-personal-apps  links not saving

### ISSUE THREAD

**Issue by Masoodsa** [pnp/sp-dev-fx-webparts#1622]
Thank you for reporting a bug! Use the sections below to submit a bug ONLY if it's related to samples in this repo. If you have an issue or question about the SharePoint Framework or its documentation, please submit it at https://aka.ms/spdev-issues

## Sample (which sample are you having trouble with)
react-my-personal-apps
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-my-personal-apps

## Authors
João Mendes

## Expected or Desired Behavior
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-my-personal-apps
Using the above links and instructions installed the package . 
Using this users want to save their personal links 

## Observed Behavior
When saving the links it does not save .

## Steps to Reproduce

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-my-personal-apps
Use the instructions as per the package link,
1. Go to 'Edit Modern page add  spfx webpart “My Personal Apps and link” '
2. Click on ' Add link with information'
3. Click Save button , but links not saved.

# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10 
- **Target Environment**: [ SharePoint Online]
- **Framework**: []
- **Browser(s)**: [Chrome v79 ]
- **Tooling**: 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

## Additional context
![image](https://user-images.githubusercontent.com/70761043/100693054-27782780-339d-11eb-934f-2a73e251424a.png)

**Comment by SmitaNachan** [comment]
Hello @hugoabernier 
Can I work on this?

**Comment by hugoabernier** [comment]
@SmitaNachan by all means, be my guest! I've assigned this to you.

**Comment by SmitaNachan** [comment]
Hi @Masoodsa 

The personal app links are getting saved. 
Looking at the `Steps to produce` provided by you, looks you are missing a step to click the `tick` (as highlighted in below image) before clicking `Save`.

![react-my-personal-apps](https://user-images.githubusercontent.com/65232102/101063625-e9405b00-358a-11eb-8435-a6cf602db8a0.png)

**Comment by Masoodsa** [comment]
Hi Smita,

Thanks for your great support and excellent diagnose skill.

Again Thanks a lot.

Regards
Shah

**Comment by hugoabernier** [comment]
@Masoodsa I'm going to go ahead and close this issue.

If you're running into more issues, don't hesitate to reach out.

Thanks @SmitaNachan for your help with this one.
