### ISSUE TITLE
 List Form web part TypeError: Cannot read property 'map' of undefined [React List form]

### ISSUE THREAD

**Issue by ntinykumar** [pnp/sp-dev-fx-webparts#1633]
1)  It was installed in the sharepoint online in last month (Till November)
2) It was working for sharepoint list which had lookup columns availables. 
3) When I checked its not working in December months might have some bug issues. 
4) I have used breakpoint and debug its shows me below issues from the VS code 

![image](https://user-images.githubusercontent.com/19857111/101629040-bb558d80-3a46-11eb-9de4-f94013a59218.png)

TypeError: Cannot read property 'map' of undefined
    at SPFieldLookupEdit (c:\NITINKUMAR\SPFX new code\src\webparts\listForm\components\formFields\SPFieldLookupEdit.tsx:10:45)
    at Pi (:1:1163126)
    at Mo (:1:1205782)
    at ko (:1:1191480)
    at bo (:1:1188518)
    at po (:1:1187121)
    at :1:1149611
    at t.unstable_runWithPriority (:1:1224530)
    at dl (:1:1149340)
    at vl (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_94d6f4f3fcee58f3ffbdd53dca12f7b4.js:1:1149

5) Then I have checked on the sharepoint site how its throw error is mentioned below in the image 

![image](https://user-images.githubusercontent.com/19857111/101629154-e9d36880-3a46-11eb-86d8-a2fc38be3c8d.png)

Error is :  List Form web part TypeError: Cannot read property 'map' of undefined

This is very important that its worked for any sharepoint online list which does not have lookup columns but not works with the list which has lookup column. Interesting thing is it was working before. Please help me and tell me solution as soon as possible will be appreciated.

Thank you for reporting a bug! Use the sections below to submit a bug ONLY if it's related to samples in this repo. If you have an issue or question about the SharePoint Framework or its documentation, please submit it at https://aka.ms/spdev-issues

- Bugs that do not follow the below template will automatically be closed
- All bug reports are welcome - we want to fix them!
- This repo is maintained by volunteers (not Microsoft). Please be courteous and patient. 🙂
- Include sufficient details and context.
- If you have multiple bugs please submit them separately so we can track resolution.
- Screenshots are always helpful (just paste any images right here in the bug report)
- We accept pull requests. If you know how to fix it - go ahead!

DELETE EVERYTHING ABOVE AFTER READING - THANKS!

## Authors

> Because of the way this repository is configured, samples authors do not get a notification when you create an issue. *It makes it less likely for you to get your issue resolved or to get help*. For the section above **@mention any author of the sample**. Authors' GitHub handle can be found on the main sample documentation page, under the "solution" section. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Steps to Reproduce

# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by hugoabernier** [comment]
@ntinykumar in order to be able to help you, we'll need you to fill the issue template as requested (the part that you left at the bottom of your issue description).

I'll mark this issue as incomplete. Feel free to open a new issue and fill the template so that we can get you the help you deserve.

**Comment by ntinykumar** [comment]
what the template I need to fill up ?

**Comment by hugoabernier** [comment]
The text that appears when you create a new issue.  The one that begins with:

> Thank you for reporting a bug! Use the sections below to submit a bug ONLY if it's related to samples in this repo

**Comment by ntinykumar** [comment]
Thanks for the guildine. Please fine the link for new issue which I have raised .https://github.com/pnp/sp-dev-fx-webparts/issues/1635 

Let me know if this is correct now. I request you to please provide me the solution on it.

**Comment by hugoabernier** [comment]
Thanks @ntinykumar, I can see the new issue.

I noticed that you didn't fill the Authors section in your new issue. You should know that the authors section is how authors of the sample are notified that there is an issue waiting for them. Hopefully they'll notice that there is an issue and they'll be able to help.

Thanks for your patience and I hope someone in the community will be able to help you.

**Comment by ntinykumar** [comment]
Hi Pnp/Sp-Dev-Fx-Webparts,

I am sorry about  that I was missed author section to add it. I still not
able to find that section how to add the author and where ? I tried to
create new but there also I did not find it. Can you please send me screen
shot or guilde how do I do it if you dont mind.

Thanks & Regards,
Nitinkumar Kakulde
Mobile:- +44-7709977440
