### ISSUE TITLE
List Form web part TypeError: Cannot read property 'map' of undefined [React List form]

### ISSUE THREAD

**Issue by ntinykumar** [pnp/sp-dev-fx-webparts#1635]
## Sample (Issues for lookup columns in the list form)

react-list-form (https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-list-form)

## Authors

@cubidobusinesssolutions
@moersoy
Harsha Vardhini (@Harshagracy )
Ryan Schouten (@sharepointknight )

## Expected or Desired Behavior

Forms should shows with New/Display/Edit for any sharepoint online list and work but this list wepart works for parent list but not work flow child list where you have taken the lookup fields. It should work with the list which has lookup column available

## Observed Behavior

It should work with the list which has lookup column available but it does not worked at all , Its give error on the form like "List Form web part TypeError: Cannot read property 'map' of undefined" or sometime does not shows the form on the sharepoint page when we select any list at the time of configuration

## Steps to Reproduce

1. Go to '...' Click to the sharepoint online site > Edit the page > Select the List form reach SPFX list form webpart > add it on the page ? then click to configure the webpart with sharepoint list as New item add for any sharepoint list which has lookup columns avaialbles. 

2. Click on '....' Then moment you select the list in dropdown its shows error

![image](https://user-images.githubusercontent.com/19857111/101636567-87339a00-3a51-11eb-870b-66ac10069eee.png)

3. Scroll down to '....' Error has been captured on Chrome browser as well as via VS code tool.

![image](https://user-images.githubusercontent.com/19857111/101636606-961a4c80-3a51-11eb-8ce6-6cbce27f60c3.png)

4. See error > Screen shot has attached for errots 

![image](https://user-images.githubusercontent.com/19857111/101636720-bcd88300-3a51-11eb-8c03-021afd51e520.png)

# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10 |
- **Target Environment**: | SharePoint Online]
- **Framework**:  Node.js v10.16.3]
- **Browser(s)**: [e.g. Chrome v79 |
- **Tooling**: [e.g. VS Code
- **Additional details**: *NA

## Additional context
It was working before November 2020 without any issues for lookup column list and form was working fine but from the December its has started showing issues as mentioned in the title of the post.

It will be great if you sort out this issues as soon as possible for me , @wobba Federico , @LauraKokkarinen

**Comment by ntinykumar** [comment]
I have checked it on different different enviroment with different different Sharepoint list with look up columns . I have updated npm packaged and re-deployed the Reach-List-Form in sharepoint online enviroment but the issues is same. Its only working for the list which does not have look up columns.  It should be work to list which having look up columns like it was working previously before November month. Your help will be appreciated.

**Comment by ntinykumar** [comment]
I was using the React-List-Form version 1.0.3.0 and it had issue of List Form web part TypeError: Cannot read property 'map' of undefined for the sharepoint list which has the loop up column from another list which is text and one more field which is calculated text fields. 

Now I have downloaded and updated the solution form the git hub  React-List-Form version 1.0.4.0 and deployed on the same sharepoint online enviroment and this time erros are different. Now Cannot **read property 'map' of undefined**  error has gone but another error populated with "TypeError: Cannot read property 'indexOf' of undefined"

![image](https://user-images.githubusercontent.com/19857111/101775793-e6dc8480-3ae7-11eb-9298-b1ba6f720d9f.png)

Also another problem in the React-List-Form version 1.0.4.0 is that it shows the lookup column in the form and the form has no issues for laoding but the has issues loading the all items in the dropdown lookup column in the form. It does not retrive all the items of lookup column.

**Comment by hugoabernier** [comment]
@ntinykumar it looks like this web part is one of many that were affected when the `RenderListDataAsAsStream` API -- which returns list data for rendering, including lookups -- seemingly changed without notice on the Microsoft side.

To be fair, the API was undocumented and therefore not intended to be called by 3rd-party solutions, but many people -- including me -- used it liberally because it was the most efficient way to get that data.

If anyone is interested in coming up with an alternative to using `RenderListDataAsStream` that is supported, we'd love your help here.

**Comment by ntinykumar** [comment]
@hugoabernier , I really really appreciated your response on the issues which I have been raised.  

**So basically my next question would be here that even if we create our own spfx form [including dropdown to populated from lookup list data with all items] to submit the data in sharepoint list which having the lookup column would not work at the moment to get the RenderListDataAsStream data into the dropdown ?**  

****Issues Note**
1) Reach List form would only populate dropdown items from the look up column which is the Title of the another list (Only limited data is populated not straming of items happening)
2) Reach List form is not populate dropdown items from the look up column which is the other fields apart from the Title of the another list (Dropdown shows None)
3) Reach List form is not populate dropdown items from the look up column which is the calculated text fields the another list (Dropdown shows None)
4) Reach List form is not populate dropdown items from the look up column which is the calculated text fields the Site Columns**



**I would appreciate if below mentioned experts or all contributers to put some lights and achieive what we required.

@sharepointknight
@cubidobusinesssolutions
@moersoy**

**Comment by Abderahman88** [comment]
@ntinykumar 

I tested the webpart with a simple lookup-field ('Department') and it works as suspected. Is there something special with the list ('TestChild2') you're trying to show?

@hugoabernier `_api/web/GetList(@listUrl)/RenderListDataAsStream` seems to work

![ReactListForm](https://user-images.githubusercontent.com/36161889/101840970-5896eb80-3b45-11eb-8708-bc26d6b09fec.png)

**Comment by ntinykumar** [comment]
@Abderahman88 , 

Thanks you so much for your respose. I have tested the React-List-Form webpart having version 1.0.4.0 with all scenarios and here is scenarios and issues noted below for more understanding.

1) List A with columns Title (String), Department (String) , Department02 (Calculated column) content more than 100 items.
2) List B with columns Title (String) , DepartmentLC ( Lookup column "Department" from  List A  ), Department02LC ( Lookup column "Department02" from  List A )

Now from above senario issues are listed below when you access the the List B from the React-List-Form >>>>

1) DepartmentLC  dropdown in the React-List-Form only load 100 items
2) Department02LC dropdow in the React-List-Form load None
3) Error sometime TypeError: Cannot read property 'indexOf' of undefined


I would appreciate if below mentioned experts or all contributers to put some lights and achieive what we required.

@sharepointknight
@cubidobusinesssolutions
@moersoy 
@Abderahman88

**Comment by Abderahman88** [comment]
@ntinykumar I've recreated your scenario. But I don't know why you need the lookup 'Department02LC' in list B.
Because the calculated info can be retrieved from lookup 'DepartmentLC'. For the limit of 100 items, I will make a PR.

### Lists
List A contains 106 items.
![ListA](https://user-images.githubusercontent.com/36161889/101932314-e4a72280-3bda-11eb-9bbc-735b4b3a47e8.PNG)
![ListB](https://user-images.githubusercontent.com/36161889/101932991-d86f9500-3bdb-11eb-8368-69139381de60.PNG)

### Create an item
![ReactListForm](https://user-images.githubusercontent.com/36161889/101933485-9004a700-3bdc-11eb-82ef-8a8a4a18c207.gif)

![ListFormResult](https://user-images.githubusercontent.com/36161889/101934286-a9f2b980-3bdd-11eb-8e68-f3806ffc6be8.png)

**Comment by ntinykumar** [comment]
@Abderahman88 , I am really thank you that you have put effort for re-creation of the issues. 

Then how can we load or get the items after 100s in DepartmentLC column ? As you are making PR , does that mean you gonna upgrade the solution to get more than 100s or streaming of all items in the DepartmentLC ? This would be really great if you meant so. 

Department02LC is just the sample name of the column in ListB taken for understanding but column Department02 in ListA need to be have it as calculated column in ListA. This calculated column could have some different bussines logic to have items in it based on some other columns in the ListA. So basically lookup column Department02LC from ListB does not shows any values from the column Department02 from ListA. Practically its just column and can be accessible using React-List-Form. 

However at the moment DepartmentLC should fetch all items more than 100s seemlessely in dropdown would be very required and essential feature for everyone else in-order to use React-List-Form. 

Many Thanks,

**Comment by hugoabernier** [comment]
@ntinykumar I hope that you were able to resolve this issue with the updated sample and instructions from @Abderahman88.

I'll go ahead and close this issue. If you need any more help with this, please don't hesitate to open another issue so we can continue to help.

**Comment by ntinykumar** [comment]
@hugoabernier : Thanks for everything, Does the new version supporting loading more than 100 items out of the box of or do I need to work for it to get ? I will re-download new version and will check again.
