### ISSUE TITLE
Latest version of pnp-script-editor.sppkg

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/sp-dev-fx-webparts#1637]
Hello,

Can you please make available for each web parts and specically in this case the pnp-script-editor web part?

I was able to generate the sppkg file and install it sucessfully without errors in my tenant app catalog but the web part is not listed in my tenant which makes me think that my sppkg file is not correct.

Please check if the attached sppkg file is correct.

I used node v10 (node-v10.19.0-x64.msi file) and got no errors in the buld process with the following commands_

Npm install
npm install gulp --global
npm install yo --global

gulp build
gulp bundle --ship
gulp package-solution --ship

[pnp-script-editor.zip](https://github.com/pnp/sp-dev-fx-webparts/files/5672955/pnp-script-editor.zip)

**Comment by miguelisidoro** [comment]
I noticed that the "Make this solution available to all sites in the organization" is not available during deployment. Is this normal?
Can you send me a valid sppkg file for the Modern Script Editor web part?

**Comment by hugoabernier** [comment]
Sorry @miguelisidoro, we'd love to be able to help, but this repository is intended for sample code -- not for web parts to be used in production. 

We can't take the responsibility for packaging the web part and distributing it.

You'll have to download the repo and build the sample yourself or ask someone that you can trust to do so for you. Or maybe someone in the community will reach out and provide you with a built package.

You can refer to the Disclaimer section with every sample for more information.

I'll mark this issue as closed.
