### ISSUE TITLE
What are "releases"?

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-webparts#1644]
## Sample (which sample are you talking about)
Samples under the "releases" section:
https://github.com/pnp/sp-dev-fx-webparts/releases

## Authors

Not specified in the samples?

## Question (the more details, the better)

I recently found out that in addition to the "samples" section, this repository has resources under "tutorials" and "releases".

I think I understand tutorials, they are meant to be used along with a Microsoft course. But how about releases, and how do we navigate to them from the main menu?

**Comment by hugoabernier** [comment]
@PathToSharePoint **Releases** are GitHub's automated way to bundle the resources from the repository when events happen (e.g.: when a pull request is processed, etc.).

You can use the releases to download a snapshot version of the repository in a zipped package.

I hope this helps?

**Comment by PathToSharePoint** [comment]
Thanks for the reply Hugo!
So for example when I see a release called "Provision SharePoint Assets with the SPFx solution package #", what resources does it bundle?

**Comment by hugoabernier** [comment]
The release will usually tell you what pull request is related to it.

For example, the release you asked about shows

```
Provision SharePoint Assets with the SPFx solution package #
@VSC-Service-Account VSC-Service-Account released this 2 days ago · 10 commits to master since this release

Merge pull request #1641 from pnp/dependabot/npm_and_yarn/samples/react-provision-assets/ini-1.3.7
```

We don't actually create releases manually in this repo -- or rarely do. So, releases are an automated snapshot of a pull request at the time that it was accepted.

I hope this helps?
