### ISSUE TITLE
How to deploy same solution again with new id

### ISSUE THREAD

**Issue by sivanu137** [pnp/sp-dev-fx-webparts#1652]
## How I can deploy the same solution again into the app catalog with a new Product ID?

##Details: 
 I have cloned this react-carousel sample then I changed the UI based on my requirement and then implement it into my site by doing packaging it and deployed it into the tenant level app catalog, then I added this web part to my site page for example this is my site (https://abc.com/site/abcd).

Now I wanted to completely modify the react-carousel UI and implement it into another subsite example (https://abc.com/site/abcd/mysubsite). In this case, how can I install this package with slight UI modification at the tenant level app catalog, without getting an error like (solution with this package id already exists)?

Thanks in Advance!!!

**Comment by Abderahman88** [comment]
Hi @sivanu137,

You can use a tool called **M365 CLI** (https://pnp.github.io/cli-microsoft365/)

The command to use is 'spfx project rename'.

It can rename your project en give it a new id.

Try it out.

**Comment by hugoabernier** [comment]
Hey @sivanu137 I hope that you were able to solve your issue with @Abderahman88 's help?

I'll go ahead and mark this issue as closed. If you need further help, please don't hesitate to open a new issue.

Thanks @Abderahman88 for your help with this one!

**Comment by sivanu137** [comment]
@Abderahman88 , thanks for the assistance. Will check the same and revert back with the status.
