### ISSUE TITLE
React Accordion Section Web Part: Web Part Title styling does not match current OOTB Web Part Title Styles

### ISSUE THREAD

**Issue by jack-vinitsky** [pnp/sp-dev-fx-webparts#1662]
## Sample (which sample are you talking about)
react-accordion-section

## Authors
@mikezimm

## Suggestion (the more details, the better)
The styling of the typed in web part title does NOT match the new styling of OOTB web part titles.  For example on my dev tenant all OOTB web part titles are **20px** and also **Segoe UI Semibold** wheras the React Accordion Section is **24px** and **Segoe UI Light**

I think the styling should match the OOTB web part behavior. See below screenshot.

![image](https://user-images.githubusercontent.com/74683257/103574759-82220900-4e9e-11eb-86f2-77324fd492c7.png)

**Comment by hugoabernier** [comment]
Thanks @jack-vinitsky for investigating. You could try to update the reusable controls library, which should solve the issue.

I've marked this issue as **help wanted** in case someone in the community wants to update the sample and create a PR.

**Comment by Ravikadri** [comment]
@hugoabernier I have fixed this issue and created PR [1664](https://github.com/pnp/sp-dev-fx-webparts/pull/1664)

Let me know if you run into any issues. Happy to assist.

Thanks!
Ravi

**Comment by jack-vinitsky** [comment]
@hugoabernier Just submitted a PR #1665 with a fix.   Looks like @Ravikadri  submitted some also.  Do note that I updated some other dependencies as per this [guidance](https://pnp.github.io/sp-dev-fx-controls-react/guides/migrate-from-v1/).
