### ISSUE TITLE
React List Form: Move function not working. I am unable to move the list item to another location.

### ISSUE THREAD

**Issue by scscott12** [pnp/sp-dev-fx-webparts#1666]
## Sample
sp-dev-fx-webparts/samples/react-list-form/

## Authors
@Abderahman88 

## Expected or Desired Behavior
Documentation states that you can move the list item to another location in the list. 

## Observed Behavior
I compiled the code and implemented it into my tenant. When I configure a list (edit or New) and select the move icon it will not move. It appears to show that the move will work until I release the mouse button and then the item stays where it was.
All of the other functionality is working except for the move function.

## Steps to Reproduce
1. web part to the page
2. configure web part
3. select a list
4. choose either edit or new
5. if edit select an item id
6. select the move icon in the web part
7. drag to a new location 
8. release the mouse button
9. item stays were it was

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v6/v8/v10/v12
- **Browser(s)**: Chrome v87.0.4280.88 | FireFox v82.0.3 | IE v11.1246.17134 | 
- **Tooling**:  Visual Studio 2019

https://user-images.githubusercontent.com/35305550/103813826-503bae80-5026-11eb-84e2-3ccd8fa6c1e0.mp4

**Comment by Abderahman88** [comment]
Hi @scscott12,

I can confirm this issue. 
Taking a quick glance, I think something goes wrong when updating the new fields.

```
private updateField(fields: IFieldConfiguration[]): any {
    this.properties.fields = fields;
    // render web part again so that React List Form component is rerendered with changed fields
    this.render();
  }

```
Maybe the author (@DanyWyss) can take a closer look or someone in the community.
