### ISSUE TITLE
react FAQ only starts very briefly

### ISSUE THREAD

**Issue by memphis11** [pnp/sp-dev-fx-webparts#1668]
Hello, 

I have a problem with the "react-faqapp" web part.

If I upload the sppgk file in tenant after the build and then embed it on a website, it appears briefly on the page but automatically disappears again. I entered a Sharepoint list in the config.

The web part is not visible
What could that be

greetings

**Comment by Abderahman88** [comment]
Hi @memphis11,

1. Does your list contains the required fields? (Title, Answer, Category, ...)
2. Do all fields have a value? (f.e. if category is not filled in, the webpart won't work)

![missingCategory](https://user-images.githubusercontent.com/36161889/105247047-70b24f80-5b74-11eb-958a-ca29c5e49ebf.png)

Normally the webpart should work.

![faqWebpart](https://user-images.githubusercontent.com/36161889/105247391-0352ee80-5b75-11eb-94a2-15b889615236.PNG)

**Comment by hugoabernier** [comment]
@Markus-Hanisch thanks for your issue. We'd love to help you further, but we need more information.

I'll go ahead and close this issue as incomplete. If you still need help, please don't hesitate to open a new issue and take the time to fill the issue template that we provide, complete with author and environment information.

Thanks for your understanding.

**Comment by Markus-Hanisch** [comment]
@memphis11 
I guess @hugoabernier accidentally mentioned me instead of you.

**Comment by hugoabernier** [comment]
Curse you, autocomplete!
