### ISSUE TITLE
SharePoint Moderpage loads first, then my css getting applied

### ISSUE THREAD

**Issue by sivanu137** [pnp/sp-dev-fx-webparts#1669]
## Question (How to stop loading native SharePoint screen and load my customized page first?)

Hi, I'm developing a SharePoint online intranet portal, with custom UI. What happens is, when I load my page, the SharePoint default page gets loaded first (for fraction of seconds), then my custom UI page gets loading.

For reference, I have attached the behavior of the page in the video format.

https://user-images.githubusercontent.com/31919925/104265805-6927e200-54b4-11eb-927b-f8c4d3f522bf.mp4

You can see in the top HTML tag, I am adding a class **"loading-in-progress"** when the page gets load, for this class I have added the CSS with a background image (i.e., Loading GIF). Once the page loaded completely I'm removing the class "**loading-in-progress**".

What I want to achieve is, without showing SharePoint native screen directly show my customized page or show a loading gif until the page gets loaded completely.  

Thanks in Advance!!!

**Comment by hugoabernier** [comment]
@sivanu137 this repository is intended for issues related to samples in this repository. Try opening an issue in the SP Dev Docs repository (there is a link to it in the new issue page).
