### ISSUE TITLE
React-Accordion-Dynamic-Section:  Question about re-using

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1670]
## Sample (which sample are you talking about)
[React-Accordion-Dyanmic-Section](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-accordion-dynamic-section)

## Authors
@hugoabernier 

## Question
I was going to reuse the accordion part of this sample in another project and had a question.
I created a folder in my project's components folder, copied all the files from your sample's components folder over.

### The actual question/issue:
In VSCode folder view, I see only 4 files, but in the actual file folder all 5 are there.

I'm wondering if I have something in my config hiding it because I do see all 5 files in the this repo's components folder when I'm in VS Code.

Hope that make sense... here's a screenshot:
![image](https://user-images.githubusercontent.com/49648086/104660794-3852d300-5695-11eb-8cf5-1bbf11ee80ce.png)

**Comment by hugoabernier** [comment]
@mikezimm the `.scss.ts` file is generated from the `.scss` when you build the solution. This is normal behavior.

I hope this helps?
