### ISSUE TITLE
Is there a Page Viewer webpart somewhere I'm missing

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1672]
## Sample Description (what should it do)
In SP2016, we have a page viewer webpart where I can show content even from an internet page not on SharePoint.
In Teams, I can paste a link to SPO page and show it as a tab.

I can't find PageViewer as an out of the box webpart and was wondering if I'm missing something.
Something like Teams is preferred... where you can just get the page content with or without the quicklaunch and top navigation.

## Are you Willing to Help?
I would if I could but I don't know how to start this one.

Thanks

**Comment by PathToSharePoint** [comment]
On SharePoint Online, try the Embed Web Part.

You'll find out that SPO is more restrictive than SP 2016 when it comes to embedding code or pages. Check out the Microsoft documentation for proper use.

**Comment by hugoabernier** [comment]
Hey @mikezimm  I hope that @PathToSharePoint 's answer helped you? I'll go ahead and mark this issue as closed, but if you still feel that we need a sample, let us know and we'll re-open it as a sample request.

Thanks for your help!
