### ISSUE TITLE
react-list-form : Autocomplete not working with Managed Metadata

### ISSUE THREAD

**Issue by Dukeofdork** [pnp/sp-dev-fx-webparts#1673]
[SOLVED]
Solution was to update some packages.
Not sure which. It started working suddenly after fiddling around.
****

Autocomplete for Managed Metadata is not working in react-list-form

When typing/searching for a term you just get a spinning circle.

The problem seems to be that the termid variable is undefined. Se sample of request below, between `<Parameter Type="String">` and `</Parameter>`

**Endpoint**
`_vti_bin/client.svc/ProcessQuery`

**Payload**
`<Request xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName="Javascript Library"><Actions><ObjectPath Id="1" ObjectPathId="0" /><ObjectIdentityQuery Id="2" ObjectPathId="0" /><ObjectPath Id="4" ObjectPathId="3" /><ObjectIdentityQuery Id="5" ObjectPathId="3" /><ObjectPath Id="7" ObjectPathId="6" /><ObjectIdentityQuery Id="8" ObjectPathId="6" /><ObjectPath Id="10" ObjectPathId="9" /><Query Id="11" ObjectPathId="9"><Query SelectAllProperties="false"><Properties /></Query><ChildItemQuery SelectAllProperties="false"><Properties><Property Name="IsRoot" SelectAll="true" /><Property Name="Id" SelectAll="true" /><Property Name="Name" SelectAll="true" /><Property Name="PathOfTerm" SelectAll="true" /><Property Name="TermSet" SelectAll="true" /></Properties></ChildItemQuery></Query></Actions><ObjectPaths><StaticMethod Id="0" Name="GetTaxonomySession" TypeId="{981cbc68-9edc-4f8d-872f-71146fcbb84f}" /><Method Id="3" ParentId="0" Name="GetDefaultSiteCollectionTermStore" /><Method Id="6" ParentId="3" Name="GetTerm"><Parameters><Parameter Type="String">undefined</Parameter></Parameters></Method><Property Id="9" ParentId="6" Name="Terms" /></ObjectPaths></Request>`

**Comment by hugoabernier** [comment]
@Dukeofdork glad it works! I'll go ahead and close this issue, but please don't hesitate to reach out if you have any more issues.
