### ISSUE TITLE
Looking forward to get "react-search" sample to run on SP2019 on prem

### ISSUE THREAD

**Issue by BlackHawk1942** [pnp/sp-dev-fx-webparts#1675]
Greetz!

Is there any chance to get "react-search" sample to run on SP2019 OnPrem ?

gulp bundle --ship
gulp package-solution --ship

Everything is fine. cdnBasePath is sepcified. Files are copied. Unfortunately it doesn´t appear in the site collection after I uploaded the sppkg.

Could anybody help me please? Need a search WP for SP2019 OnPrem modern UI.

Thanks @ALL!

**Comment by BlackHawk1942** [comment]
Done that on my own - CLOSED

**Comment by hugoabernier** [comment]
Great work @BlackHawk1942 ! If you'd like to share your sP2019 version with the rest of the community, feel free to create a pull request.
