### ISSUE TITLE
I get 404 error

### ISSUE THREAD

**Issue by firozozman** [pnp/sp-dev-fx-webparts#1678]
I get 404 error trying to install Modern-Calendar from the samples.

Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz

'event-stream@3.3.6' is not in the npm registry.
You should bug the author to publish it.

**Comment by hugoabernier** [comment]
Thanks for your issue. However, in order to properly help you, we'll need you to fill the issue template that's provided -- complete with author information, environment information, etc.

Thanks for your understanding.
