### ISSUE TITLE
SPFX Custom web part: Top Navigation menu disappears

### ISSUE THREAD

**Issue by shibu-123** [pnp/sp-dev-fx-webparts#1686]
On a site page, when we add a custom webpart and publish the page. The top menu navigation menu of communication site disappears. The menu appears only when you scroll down the page. The menu disappears when you scroll up the page. Please let us know how the issue can be resolved.

![image](https://user-images.githubusercontent.com/45416215/105961784-fb2f0d80-60a4-11eb-9642-5283ecf1da6c.png)

**Comment by hugoabernier** [comment]
@shibu-123 this issues list is intended for issues related to samples in this repository.  For issues related to custom web parts, I would recommend using the sp-dev-docs repository.

Good luck!
