### ISSUE TITLE
react-chartcontrol: NodeJS version issue

### ISSUE THREAD

**Issue by gretchunkim** [pnp/sp-dev-fx-webparts#1689]
**```react-chartcontrol ```**

**Issue:**  The [recommended NodeJS version 10](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment) is incompatible with ```react-chartcontrol``` webpart sample where it uses NodeJs version 8.9.4 - 9.0.0 instead. 

**To reproduce** :
Follow Minimal Path to Awesome 
1. Clone this repository
2. In the command line run:
```npm install``` 
```gulp serve```

>Error: Your dev environment is running NodeJS version v10.23.2 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0

**Request**:  
1. Is there an alternative pathway to awesomeness without installing outdated NodeJs? 
2.  Can someone check to see if the compatibility section of the documentation about the NodeJs needs to be updated to reflect the current state? Indeed, if it needs outdated NodeJS I volunteer to edit the [documentation](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-chartcontrol)
![Capture](https://user-images.githubusercontent.com/8564035/106416762-2bb5d500-6420-11eb-9687-b11ba16d6970.JPG)

Thanks,
Gretchun 

additional error ref: 
> at SPWebBuildRig.initialize (\samples\react-chartcontrol\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:25:19)
    at SPWebBuildRig.initialize (\samples\react-chartcontrol\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:15:15)
    at Object.exports.initialize (\samples\react-chartcontrol\node_modules\@microsoft\sp-build-web\lib\index.js:23:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by hugoabernier** [comment]
Thanks for filing the issue. Unfortunately, we can only help you if you take the time to fill [the issue template](https://github.com/pnp/sp-dev-fx-webparts/issues/new?assignees=&labels=type%3Abug&template=bug.md&title=%5BWeb+Part+Name%5D%3A+%5BIssue+Title%5D) completely, including your environment version.

I'll go ahead and close this issue as incomplete.

**Comment by gretchunkim** [comment]
Thank you @hugoabernier. Submitted new as instructed!
