### ISSUE TITLE
does it support Content Type selection dropdown in Form (like OOB Modern SP List Form) ?

### ISSUE THREAD

**Issue by shrirampophali** [pnp/sp-dev-fx-webparts#1690]
## Sample (which sample are you talking about)

# 1501

**Comment by hugoabernier** [comment]
Thank you for your issue. However, this issues list is intended to be used for issues regarding this repository. If you need help with general SPFx development, please [create an issue in the sp-dev-docs repository](https://github.com/SharePoint/sp-dev-docs/issues/new).
