### ISSUE TITLE
Content Query: unable to access pageContext token

### ISSUE THREAD

**Issue by coupalm** [pnp/sp-dev-fx-webparts#1697]
## Sample
Content Query web part

## Authors
@hugoabernier 

## Expected or Desired Behavior

When using the {{pageContext}} token in handlebars result templates, it should return information.
Ex: If current user language code is 1036, it will return the first <h1>

        {{#compare pageContext.web.language '==' 1036}}
            <h1>This is rendered if current language is 1036</h1>
        {{else}}
            <h1>This is rendered if current language is anything else</h1>
        {{/compare}}

## Observed Behavior

It nevers detect the current user language. 
{{pageContext}} will return an object but not {{pageContext.web}}. it returns null.

## Steps to Reproduce

Create a new page
Add the content query web part
Add the following in the result template (put the language code according to your user account language)
        {{#compare pageContext.web.language '==' 1036}}
            <h1>This is rendered if current language is 1036</h1>
        {{else}}
            <h1>This is rendered if current language is anything else</h1>
        {{/compare}}
The compare will always return false.

# Environment Details (*Development & Target environment*)

- **OS**:Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: N/A
- **Browser(s)**: Chromium Edge v79
- **Tooling**: VS Code

**Comment by Terenyeitamas** [comment]
Hello @coupalm !

Try this:

```
{{#compare @root.pageContext._web.language '==' 1036}}
        This is rendered if current language is 1036
    {{else}}
        This is rendered if current language is anything else
{{/compare}}
```

Best,
Tamás
