### ISSUE TITLE
Drop and drag not working

### ISSUE THREAD

**Issue by Kman1131** [pnp/sp-dev-fx-webparts#1698]
Correcting function in DraggableComponent.tsx
from:
props.moveField(droppedKey, orignalIndex);
to:
props.moveField(droppedKey, props.index);

Sorts the issue.  - Will look at the buttons soon

  endDrag(props: IDraggableComponentProps, monitor) {
    const { key: droppedKey, originalIndex } = monitor.getItem();
    const didDrop = monitor.didDrop();
    if (!didDrop) {
      **props.moveField(droppedKey, props.index);**
    }
  },

**Comment by hugoabernier** [comment]
Thank you for your issue, but in order to help you, we'll need you to provide the information we requested in the issue template.

I'll go ahead and close this issue as incomplete. Feel free to open a new issue with all the details provided.

Thanks for your understanding.
