### ISSUE TITLE
React-content-query-online Sample - Programmatically Configure in a ClientSidePage

### ISSUE THREAD

**Issue by anisiaalexandra** [pnp/sp-dev-fx-webparts#1701]
##react-content-query-online

Hi,

I have been trying to add and configure the react content query online to a ClientSidePage programmatically.
the add works fine, but when I try to set the proprieties, nothing gets persisted.
Bellow the way I try to set the properties of the web part:
CQWebPart.PropertiesJson =
JObject.FromObject(new
{
description = "Content Query",
enableMGT = true,
itemSelectorEnabled = false,
idFieldForciblyAdded = false,
webUrl = "/",
siteUrl = "/sites/Dev",
listId = "<the list Id>",
viewFields = new JArray ( "Title" ),
externalScripts = "https://tenant.sharepoint.com/sites/Dev/SiteAssets/CQ.js",
templateUrl = "https://tenant.sharepoint.com/sites/Dev/SiteAssets/CQ.html",
hasDefaultTemplateBeenUpdated = true
}).ToString();

@spplante : What is the correct way to programmatically configure this web part?
Thank you in advance for your help.

Kind regards,
Alex

**Comment by spplante** [comment]
@anisiaalexandra Configuring WebParts programmatically should be the same for all WebParts, there shouldn't be any logic in the WebPart that makes it different than others for configuring it.

I suspect you might have one of the properties wrong, making the whole configuration fail. I am pretty sure **ExternalScripts** should be an array that's the first thing I would look at.

If it still doesn't work, I would try to configure the WebPart manually and export the provisionning template using PowerShell, that way you will see the exported WebPart with all its properties so you'll be able to validate the proper configuration.

**Comment by anisiaalexandra** [comment]
@spplante first of all thank you for the quick response. 
The configuration I am trying to do programatically is obtain exactly how you mention by first configurating manually the wp and the exporting the template. the only change I did was replace the url, which in the case of the export are params.
I believe the issue is with the fact that the weburl and siteUrl do not get persisted in any of the tryouts I had:
- relative urls
- full urls
- I even tried guids of site and web
Bellow is what I receive from the pnp export:
{
	"id": "ac515af1-4490-4c7b-8191-d49b41b26c5e",
	"instanceId": "afbdfde4-8bc8-4760-bc8e-6b3dd9d9c5e7",
	"title": "Content Query",
	"description": "A content by query web part for querying items within a site and easily displaying them using a simple yet powerful HandleBars templating engine.",
	"dataVersion": "1.0.11",
	"properties": {
		"description": "Content Query",
		"enableMGT": true,
		"webUrl": "{hosturl}{site}",
		"siteUrl": "{hosturl}{site}",
		"itemSelectorEnabled": false,
		"idFieldForciblyAdded": false,
		"listId": "{listid:Compliancy}",
		"filters": null,
		"viewFields": ["Title"],
		"templateText": "<style type=\"text/css\">\r\n .dynamic-template h2 {\r\n font-size: 20px;\r\n font-weight: 600;\r\n color: \"[theme:neutralPrimary, default:#323130]\";\r\n }\r\n\r\n .dynamic-template .dynamic-items .dynamic-item {\r\n background: \"[theme:bodyBackground, default: #fff]\";\r\n border: 1px solid \"[theme:neutralLight, default: #edebe9]\";\r\n //box-shadow: 0px 0px 6px #bfbebe;\r\n margin-bottom: 15px;\r\n }\r\n\r\n .dynamic-template .dynamic-items .dynamic-item h3 {\r\n background: \"[theme:accentButtonBackground, default:#0078d4]\";\r\n color: \"[theme:accentButtonText, default: #fff]\";\r\n padding: 5px 5px 7px 10px;\r\n margin: 0px;\r\n }\r\n\r\n .dynamic-template .dynamic-items .dynamic-item .dynamic-item-fields {\r\n padding: 10px;\r\n }\r\n\r\n .dynamic-template .dynamic-items .dynamic-item .dynamic-item-fields span {\r\n display: block;\r\n font-size: 12px;\r\n }\r\n\t \r\n .example-themePrimary a {\r\n color: {{@root.themeVariant.palette.themePrimary}};\r\n }\r\n .mythumbnail{\r\n box-sizing: border-box;\r\n width: 22px;\r\n height: 22px;\r\n font-size: 22px;\r\n line-height: 22px;\r\n flex: 0 0 auto;\r\n margin-right: 12px;\r\n margin-top: 9px;\r\n color: rgb(50, 49, 48);\r\n }\r\n.globe-icon{\r\n display: inline-block;\r\n -webkit-font-smoothing: antialiased;\r\n font-style: normal;\r\n font-weight: normal;\r\n speak: none;\r\n font-family: FabricMDL2Icons-0;\r\n}\r\n.iict-item-content\r\n{\r\n position: relative;\r\n box-sizing: border-box;\r\n width: 100%;\r\n display: flex;\r\n align-items: flex-start;\r\n}\r\n.iict-item-root{\r\n margin: 1px;\r\n display: inline-block;\r\n text-decoration: none !important;\r\n}\r\n.iict-item-textArea{\r\n margin: 10px 0px;\r\n flex: 1 1 0%;\r\n min-width: 0px;\r\n padding-right: 14px;\r\n min-height: 20px;\r\n}\r\n.iict-item-labelTextWrapper\r\n{\r\n color: rgb(50, 49, 48);\r\n line-height: 20px;\r\n margin-bottom: 2px;\r\n font-family: \"Segoe UI\", \"Segoe UI Web (West European)\", \"Segoe UI\", -apple-system, BlinkMacSystemFont, Roboto, \"Helvetica Neue\", sans-serif;\r\n -webkit-font-smoothing: antialiased;\r\n font-size: 14px;\r\n font-weight: 400;\r\n}\r\n.iict-item-css-27\r\n{\r\n overflow: hidden;\r\n display: -webkit-box;\r\n -webkit-box-orient: vertical;\r\n -webkit-line-clamp: 1;\r\n box-sizing: content-box;\r\n max-height: 1.35em;\r\n text-overflow: ellipsis;\r\n}\r\n.iict-item-template_listItem\r\n{\r\n display: -webkit-box;\r\n display: flex;\r\n display: -ms-flexbox;\r\n padding: 10px;\r\n -webkit-box-pack: justify;\r\n -ms-flex-pack: justify;\r\n justify-content: space-between;\r\n}\r\n.iict-1-webPartHeader\r\n{\r\n display: -ms-flexbox;\r\n display: flex;\r\n -ms-flex-align: baseline;\r\n align-items: baseline;\r\n}\r\n.iict-1-webPartTitle\r\n{\r\n font-size: 14px;\r\n font-weight: 100;\r\n margin-bottom: 11px;\r\n color: #323130;\r\n -ms-flex-positive: 1;\r\n flex-grow: 1;\r\n overflow-x: hidden;\r\n text-overflow: ellipsis;\r\n}\r\n.iict-icon\r\n{\r\n height: auto;\r\n width: 20px;\r\n}\r\n.iict-table-wrapper{ width:100%; /*overflow-x:scroll;*/ }\r\n.iict-table {display:table;}\r\n.iict-row { display:table-row;}\r\n.iict-cell { \r\n display: table-cell;\r\n border: none;\r\n border-width: thin;\r\n padding-left: 7px;\r\n padding-right: 7px;} \r\n .iict-title\r\n {\r\n display: table-caption;\r\n text-align: center;\r\n font-weight: bold;\r\n font-size: larger;\r\n }\r\n .iict-heading\r\n {\r\n display: table-cell;\r\n font-weight: bold;\r\n text-align: center;\r\n padding-left: 7px;\r\n padding-right: 7px;\r\n }\r\n </style>\r\n\r\n <div class=\"dynamic-template\">\r\n <div class=\"iict-1-webPartHeader\">\r\n <div class=\"iict-1-webPartTitle\">\r\n \r\n <span role=\"heading\" aria-level=\"2\">Non Comliancy Issues</span>\r\n </div>\r\n </div>\r\n <div class=\"dynamic-items\">\r\n\t <div class=\"iict-table-wrapper\">\r\n <div class=\"iict-table\">\r\n <div class=\"iict-row\">\r\n <div class=\"iict-heading\"> </div>\r\n <div class=\"iict-heading\">Name</div>\r\n <div class=\"iict-heading\">OCO</div>\r\n <div class=\"iict-heading\">Structure</div>\r\n <div class=\"iict-heading\">What</div>\r\n <div class=\"iict-heading\">Source</div>\r\n <div class=\"iict-heading\">Source info</div>\r\n <div class=\"iict-heading\">Standard</div>\r\n <div class=\"iict-heading\">Date</div>\r\n <div class=\"iict-heading\">Due date</div>\r\n <div class=\"iict-heading\">Involved People</div>\r\n <div class=\"iict-heading\"><b>Release Blocked</b></div>\r\n </div>\r\n\t\t\t\t {{#each items}}\r\n\t\t\t\t\t \r\n\t\t\t\t\t <div class=\"iict-row\">\r\n <div class=\"iict-cell\">\r\n {{#if ReleasesBlocked.textValue}}\r\n <img class=\"iict-icon\" src='{{@root.webUrl}}/SiteAssets/check_red.png' />\r\n {{/if}}\r\n {{#unless ReleasesBlocked.textValue}}\r\n <img class=\"iict-icon\" src='{{@root.webUrl}}/SiteAssets/check_orange.png' />\r\n {{/unless}}\r\n </div>\r\n <div class=\"iict-cell\">{{Title.textValue}}</div>\r\n <div class=\"iict-cell\">\r\n {{OCO.personValue.email}}\r\n <mgt-person person-query=\"{{oco.personValue.email}}\" view=\"twoLines\"></mgt-person>\r\n </div>\r\n <div class=\"iict-cell\">{{Infrastructure.textValue}}</div>\r\n <div class=\"iict-cell\">{{What.textValue}}</div>\r\n <div class=\"iict-cell\">{{Source.textValue}}</div>\r\n <div class=\"iict-cell\">{{SourceInfo.textValue}}</div>\r\n <div class=\"iict-cell\">{{Standard.textValue}}</div>\r\n <div class=\"iict-cell\">{{Date.textValue}}</div>\r\n <div class=\"iict-cell\">{{Duedate.textValue}}</div>\r\n <div class=\"iict-cell\">{{InvolvedPeople.textValue}}</div>\r\n <div class=\"iict-cell\">{{ReleasesBlocked.textValue}}</div>\r\n </div>\r\n\t\t\t\t {{/each}}\r\n\t\t </div>\r\n\t </div>\r\n </div>\r\n </div>",
		"externalScripts": "{hosturl}{site}/SiteAssets/CQ.js",
		"templateUrl": "{hosturl}{site}/SiteAssets/CQ.html",
		"hasDefaultTemplateBeenUpdated": true,
		"orderByDirection": "desc"
	},
	"serverProcessedContent": {
		"htmlStrings": {},
		"searchablePlainTexts": {},
		"imageSources": {},
		"links": {}
	},
	"dynamicDataPaths": {},
	"dynamicDataValues": {}
}
Any idea of what is wrong in my setting is greatly appreciated.

Kind regards,
Alex

**Comment by spplante** [comment]
3 things I notice in your original post, the list ID is null and the view fields are extracted from the list so not sure you can set the view fields while having no list specified.

Also, based on your export, it looks like the **webUrl** and **siteUrl** are absolute URLs while you seem to set the Web URL using a relative URL, you might want to check this out

**Comment by anisiaalexandra** [comment]
@spplante Thank you for the recommendations. After the changes you suggested it is now working. :) Thank you very much.
Just for learning purposes I leave here the configuration that works:

 {
                        description = "Content Query",
                        enableMGT = true,
                        itemSelectorEnabled = false,
                        idFieldForciblyAdded = false,
                        orderBy = "Title",
                        filters = "",
                        webUrl = "https://tenat.sharepoint.com/sites/Dev",
                        siteUrl = "https://tenant.sharepoint.com/sites/Dev",
                        listId = "1cf7a650-9056-4471-8e7d-3d13bc295b6e",
                        viewFields = new JArray ("Title"),                                         
                        externalScripts = "https://tenant.sharepoint.com/sites/Dev/SiteAssets/CQ.js",
                        templateUrl = "https://tenant.sharepoint.com/sites/Dev/SiteAssets/CQ.html",
                        hasDefaultTemplateBeenUpdated = true,
                        orderByDirection = "desc"
                    }

Have a wonderful day !

Alex
