### ISSUE TITLE
RSS Reader

### ISSUE THREAD

**Issue by vishalbsacet** [pnp/sp-dev-fx-webparts#1704]
Hello Team, 

While doing bundle --ship, i am getting below error message.

I have clean npm and install npm but it did not work.

![image](https://user-images.githubusercontent.com/69198450/107548096-3f1d2900-6bf4-11eb-876d-3b6030d21fa4.png)

Please help ASAP

**Comment by Ravikadri** [comment]
I was able to build, bundle and run the package command without any errors. Maybe just validate the dev setup you have.
Run the following command >npm list -g --depth=0  and also validate the node version

Below is what my machine has. You can ignore some of them.
+-- @microsoft/generator-sharepoint@1.11.0
+-- gulp@4.0.2
+-- http-server@0.12.3
+-- nodemon@2.0.4
+-- nodetree@0.0.3
+-- npm@6.14.6
+-- source-map-explorer@2.5.0
+-- typescript@4.0.3
+-- yo@3.1.1

Nore version: v10.22.1

**Comment by hugoabernier** [comment]
Hey @vishalbsacet. We'd love to help you with this issue, but we'll need you to fill the new issue template completely in order to help you.

I'll go ahead and close this issue as incomplete. Feel free to open a new issue with all the missing details so we can help you further.

Thanks for understanding.

**Comment by vishalbsacet** [comment]
> I was able to build, bundle and run the package command without any errors. Maybe just validate the dev setup you have.
> Run the following command >npm list -g --depth=0 and also validate the node version(>node -v)
> 
> Below is what my machine has. You can ignore some of them.
> +-- @microsoft/generator-sharepoint@1.11.0
> +-- gulp@4.0.2
> +-- http-server@0.12.3
> +-- nodemon@2.0.4
> +-- nodetree@0.0.3
> +-- npm@6.14.6
> +-- source-map-explorer@2.5.0
> +-- typescript@4.0.3
> +-- yo@3.1.1
> 
> Node version: v10.22.1


below is my details:
![image](https://user-images.githubusercontent.com/69198450/107609080-db324900-6c63-11eb-9e44-1fdda371a4a1.png)

and node version is v10.21.0

**Comment by vishalbsacet** [comment]
> I was able to build, bundle and run the package command without any errors. Maybe just validate the dev setup you have.
> Run the following command >npm list -g --depth=0 and also validate the node version(>node -v)
> 
> Below is what my machine has. You can ignore some of them.
> +-- @microsoft/generator-sharepoint@1.11.0
> +-- gulp@4.0.2
> +-- http-server@0.12.3
> +-- nodemon@2.0.4
> +-- nodetree@0.0.3
> +-- npm@6.14.6
> +-- source-map-explorer@2.5.0
> +-- typescript@4.0.3
> +-- yo@3.1.1
> 
> Node version: v10.22.1

if you can pls provide me sppkg file that will help me

**Comment by Ravikadri** [comment]
Here is the zip file. 

As hugoabernier mentioned please fill the new issue template to help you.

[react-rssreader.zip](https://github.com/pnp/sp-dev-fx-webparts/files/5967117/react-rssreader.zip)
