### ISSUE TITLE
Problem with React-Script-Editor

### ISSUE THREAD

**Issue by Kralyc** [pnp/sp-dev-fx-webparts#1705]
Hi,

i need use the react-script-editor for sharepoint online, i can test it with gulp serve, but when i make the gulp bundle --ship i get an error with 

Starting subtask 'webpack'...
(node:3980) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toJson' of undefined
    at webpack (node_modules\@microsoft\gulp-core-build-webpack\lib\WebpackTask.js:73:47)

I guess I must be making a basic mistake, I have no experience with sharepoint framework, can someone help me?

PD: sorry for my English level

**Comment by Kralyc** [comment]
Sorry it was my fault, i fix it.

**Comment by chriswithoak** [comment]
@Kralyc  what did you do to fix it?

**Comment by rachaelsingleton** [comment]
I am having the same issue. @Kralyc what did you do to fix it?

**Comment by sandro54321** [comment]
@Kralyc how did you fix it?

**Comment by sandro54321** [comment]
@rachaelsingleton did you manage to find a solution?
