### ISSUE TITLE
Filter object ID

### ISSUE THREAD

**Issue by dragan89** [pnp/sp-dev-fx-webparts#1707]
Hi,

I want to display users within an AAD group, for instance using the Object ID for the group.

Is it possible to filter this out? Or, select single users separate? 

Thanks!

**Comment by hugoabernier** [comment]
Hi @dragan89, this issues list is really intended to solve issues related to samples in this repository.

While you get help in this repo, I suggest you try the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues/new) issues instead, which is dedicated to helping solve issues like yours.

Best of luck!
