### ISSUE TITLE
react-script-editor  node_module missing folder

### ISSUE THREAD

**Issue by yalanisss** [pnp/sp-dev-fx-webparts#1710]
Hi!

I would like to get your help, I tried to user react-script-editor but it doesnt work and as far as I can see, node_module folder is missing.

Thank you in advance!

BTW do you know if I need to use an specific version of node, yo, gulp etc in order to make this works properly?

**Comment by PathToSharePoint** [comment]
Just to confirm, did you run `npm install`? If so, any error message?

**Comment by yalanisss** [comment]
yes I did
