### ISSUE TITLE
React-List-Form : Taxonomy default values

### ISSUE THREAD

**Issue by Thomasvanderbeeck** [pnp/sp-dev-fx-webparts#1711]
## Sample
react-list-form

## Authors
@sharepointknight 

## Expected or Desired Behavior

What should it do?
If a default value is added in the taxonomy site column it should be displayed correctly in the form. 
This does not work for single and for multiple values. 

## Observed Behavior

![image](https://user-images.githubusercontent.com/2164771/107823562-52f59600-6d80-11eb-896b-b09568966468.png)
 The SSPid is pulled seperately, making the form not submittable.
When removing the 1 in the screenshot above the onchange method is called which does allow the changes
This console info is not from the same item as above. (the first screenshot is a different environment) --> didn't test this scenario untill it was in production
![image](https://user-images.githubusercontent.com/2164771/107823783-a831a780-6d80-11eb-84ea-fb8322a0809b.png)

If I manipulate the code to remove the number parts than the service crashes. 

## Steps to Reproduce

1.Create a list with a taxonomy column
2. Fill in a default value in that taxonomy column
3. Create a page with react list form webpart on it. 
4. Make sure it is configured to use the correct list
5. See observed behavior.

# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10 |
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**:  Chrome 87.0.4280.88 |  Chromium Edge v 87.0.664.47
- **Tooling**: VS Code | SPFx v1.10.0 

## Additional context
I have been looking at a solution to convert the props.value into an IPickerterm but I haven't found a correct solution yet.

**Comment by fthorild** [comment]
I have just opened a PR #1725 that resolves the issue if you want to have a look at that @Thomasvanderbeeck

**Comment by Thomasvanderbeeck** [comment]
> I have just opened a PR #1725 that resolves the issue if you want to have a look at that @Thomasvanderbeeck

Thank you for your assistance. @fthorild 

I checked, but he is trimming to much in multiple values.
In my sitecolumn when I have added 3 values as default value. The form is only showing me one.

All other scenario's seem to work.

**Comment by fthorild** [comment]
Aha, gotcha - here is an updated regex that should capture what you are asking for: 

Replace
`newData[fld.InternalName] = fld.DefaultValue.replace(new RegExp("([#]?[0-9]+;#)", "g"), "")`
With
`newData[fld.InternalName] = fld.DefaultValue.replace(new RegExp("([#][0-9]+;#|^[0-9]+;#)", "g"), "")`

I'll make sure this is updated in #1711

**Comment by Thomasvanderbeeck** [comment]
It is now working for me! thanks for the assistance @fthorild
