### ISSUE TITLE
section columns 

### ISSUE THREAD

**Issue by yalanisss** [pnp/sp-dev-fx-webparts#1712]
Hi all,

Is thereIa web part that works like a section?, I mean that I can add some webparts but with columns resizeble (adjust columns width). almost like a webpart page on-premise funtionality but for Modern Pages

PFA a drawing with an example of what I'm trying to explain

Thank you
![example](https://user-images.githubusercontent.com/78982043/107835697-069a5e00-6d60-11eb-8581-4b1e9abe4230.png)

**Comment by Abderahman88** [comment]
Hi @yalanisss 

I think you're (at the moment) restricted to the sections that SharePoint provides you.

![standard](https://user-images.githubusercontent.com/36161889/107892468-91788580-6f25-11eb-8be1-b7e01498d50f.PNG)

It's possible to create a webpart with the required layout, but you have to create it from scratch. (maybe a bit overkill in this situation)

Check this simular question asked in uservoice : https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/33079264-allow-changing-the-width-of-columns-when-adding-se
