### ISSUE TITLE
adaptiveCardHost:Failed to load component

### ISSUE THREAD

**Issue by allafridman** [pnp/sp-dev-fx-webparts#1714]
Current setup :

node version v10.23.3
gulp version:
CLI version: 2.3.0
Local version: 3.9.1

1. download the web part
2. from cmd cd to the webpart location
3. npm install
4. gulp serve
5. add webpart to the workbench page

Getting error  [SPLoaderError.loadComponentError]:
***Failed to load component "778241d6-2ee8-47c8-857a-df3a3b1f1302" (AdaptiveCardHostWebPart). Original error: ***Failed to load entry point from component "778241d6-2ee8-47c8-857a-df3a3b1f1302" (AdaptiveCardHostWebPart). Original error: Cannot find module '@fluentui/react'

***INNERERROR:
***Failed to load entry point from component "778241d6-2ee8-47c8-857a-df3a3b1f1302" (AdaptiveCardHostWebPart). Original error: Cannot find module '@fluentui/react'
***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:24443:24)
    at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:42161:28)
    at Function../sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.ff4n.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:46155:21)
    at Function../sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.ff4n.ErrorBuilder.buildLoadComponentError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:46024:21)
    at https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:45362:75

**Comment by Abderahman88** [comment]
Hi @allafridman,

I've successfully duplicated the error. The issue is a missing dependency `@fluent/react` in the library `adaptivecards-fabric`

As a quick solution, I did `npm install @fluent/react`
(I think a newer version of adaptivecards-fabric is getting installed instead of the right one.)

**Comment by allafridman** [comment]
I ran npm install @fluentui/react and it fixed the issue.

**Comment by cbathis** [comment]
Node version :  v10.23.2

I tried to clone react-adaptivecards solution, npm i and then gulp serve but facing same issue as below

[SPLoaderError.loadComponentError]:
***Failed to load component "778241d6-2ee8-47c8-857a-df3a3b1f1302" (AdaptiveCardHostWebPart). Original error: ***Failed to load entry point from component "778241d6-2ee8-47c8-857a-df3a3b1f1302" (AdaptiveCardHostWebPart). Original error: Cannot find module '@fluentui/react'

Later I tried to fix by running below commands as per errors and google solutions but no luck.
npm install phantomjs-prebuilt@2.1.16 --ignore-scripts 
npm i lts office-ui-fabric-react
npm i --unsafe-perm
npm install @fluent/react

Please assist.

**Comment by devanshuGit** [comment]
> Node version : v10.23.2
> 
> I tried to clone react-adaptivecards solution, npm i and then gulp serve but facing same issue as below
> 
> [SPLoaderError.loadComponentError]:
> ***Failed to load component "778241d6-2ee8-47c8-857a-df3a3b1f1302" (AdaptiveCardHostWebPart). Original error: ***Failed to load entry point from component "778241d6-2ee8-47c8-857a-df3a3b1f1302" (AdaptiveCardHostWebPart). Original error: Cannot find module '@fluentui/react'
> 
> Later I tried to fix by running below commands as per errors and google solutions but no luck.
> npm install phantomjs-prebuilt@2.1.16 --ignore-scripts
> npm i lts office-ui-fabric-react
> npm i --unsafe-perm
> npm install @fluent/react
> 
> Please assist.

@hugoabernier  could you please help, we are trying to get solution up but at this step stuck.
As pointed out by @Abderahman88 '(I think a newer version of adaptivecards-fabric is getting installed instead of the right one.)'
is there any specific version of adaptivecards-fabric to be installed for it to work>

**Comment by hugoabernier** [comment]
@allafridman I merged some changes that should take care of the issues.

@devanshuGit you should have to do any of the extra steps you did. (In fact, I have no idea what --unsafe-perm does). If you can't do an `npm i` and `gulp build`, try using SPFx doctor to make sure your environment is configured properly and open an issue with full environment details.

**Comment by cbathis** [comment]
> @allafridman I merged some changes that should take care of the issues.
> 
> @devanshuGit you should have to do any of the extra steps you did. (In fact, I have no idea what --unsafe-perm does). If you can't do an `npm i` and `gulp build`, try using SPFx doctor to make sure your environment is configured properly and open an issue with full environment details.

Thanks @hugoabernier for updated code. It's up now :)
