### ISSUE TITLE
RSS Reader - Custom CSS

### ISSUE THREAD

**Issue by vishalbsacet** [pnp/sp-dev-fx-webparts#1715]
How can i add my own CSS to RSS Reader Web-Part Property, i have only sppkg file not full Code.

Full Code i have downloaded but it is not working, might be my config.

![image](https://user-images.githubusercontent.com/69198450/108028744-53c54b00-7052-11eb-9c54-9821fc91d599.png)

**Comment by Ravikadri** [comment]
Hi Vishal,

We would love to help. Please use the new issue template to describe your issue. Just pasting the issue/requirement without proper investigation or initial setup may delay the answer you are looking for.

Thanks!
Ravi
