### ISSUE TITLE
React-List-Items-menu: Not working with Managed Metadata Columns? Empty webpart

### ISSUE THREAD

**Issue by schneika** [pnp/sp-dev-fx-webparts#1719]
## Sample (which sample are you talking about)

sp-dev-fx-webparts/samples/react-list-items-menu/

## Authors

@joaojmendes  @joaojmendes 

## Question

It seems for me that this React Lists items Menu WebPart does not work with Managed Metadata Columns.
I dont get any results with the SharePoint Taxonomy Columns.

Is this right?

br

Karl G. Schneider

**Comment by hugoabernier** [comment]
Sorry @schneika I'm not the author of this sample. You should tag the actual author (usually listed in the README) to make sure they get notified of the issue.

**Comment by schneika** [comment]
Sorry @joaojmendes

**Comment by joaojmendes** [comment]
@schneika , I didn't tested with management metadata columns...  but I will see the code :)
Thank you for testing and report the issue! 

@hugoabernier please assign the item to me. 
Thank you!

**Comment by joaojmendes** [comment]
@hugoabernier  and @schneika , I create a PR to List-Items-Menu, Add Support to Metadata Columns, single and multivalues.
I did basic tests , please if you see any bug, reopen this issue.

Many thanks!

**Comment by joaojmendes** [comment]
sorry by mistake I remove me from assigned I wanted close this ... :)

**Comment by hugoabernier** [comment]
Closed by @joaojmendes 's PR which resolves the issue

**Comment by mohammadamer** [comment]
@hugoabernier Could you please reopen this issue again. I have issue with Managed metadata columns (TaxonomyFieldType and TaxonomyFieldTypeMulti).

I figured out where is the issue and I'll create PR for solving it.

![image](https://user-images.githubusercontent.com/19314043/137876985-ce4b9b2e-7520-46d1-9a80-49f5f12e5eb1.png)

![image](https://user-images.githubusercontent.com/19314043/137877073-f96b8ac1-9f5d-43e0-ab8f-f3c14704c401.png)
