### ISSUE TITLE
react-tree-orgchart: Specify person to start tree from

### ISSUE THREAD

**Issue by johanvandy** [pnp/sp-dev-fx-webparts#1727]
First I would like to thank everyone involved for this repository. It is absolutely invaluable to beginners\newby's like me 🙂

In our organization we have several account types, i.e. a person account, a system account (used by systems but linked to a person) etc. etc. I have already modified the web-part to exclude **system accounts** as it is a requirement of top management. In our case, these system accounts starts with 's-'

I am aware of the Organization Chart that is part of the default SharePoint solution that allow the administrator to specify a starting person, but I cannot change it to exclude these 'system accounts' as we do not have access to the source code.

It would be absolutely awesome if this web-part (react-tree-orgchart) could be modified to not automatically display the visitor's OrgChart, but allow the administrator to specify a specific starting person.

@hugoabernier @joaojmendes @VesaJuvonen @petkir @JakeStanger 

Kind regards,
Johan
johanvandy@bcx.co.za

**Comment by petkir** [comment]
Hi @johanvandy 

thanks for your input.

In your use case the PropertyToggle **Show only me team** should be changed to a DropDown with 3 options:
```
Show My Team
Show Company Hierarchy
Show Other Team
```

with the option `Show Other Team` there should be a People Field enabled where you can enter the starting point of the Hierarchy.

The other thing is you would like to have a property where can exclude User Accounts.

Are these requirements correct?

**Comment by johanvandy** [comment]
Hi @petkir 

Thanks for the quick response.
Requirement are 100% correct. It would be awesome if this can be done.

**Comment by petkir** [comment]
Hi @johanvandy 

if you like you can test the functionality, before the result is in a pull request.
[Fork branch](https://github.com/petkir/sp-dev-fx-webparts/tree/petkir-1727-react-tree-orgchart/samples/react-tree-orgchart)

Some things like Resource text are currently missing.

Thanks for feedback

**Comment by johanvandy** [comment]
Hi @petkir 

Wow, that was quick 🙂

I have forked and tested. So far it is working great.

I am assuming that  **'Some things like Resource text are currently missing'** is referring to being able to specify a starting person from a people picker.

It would be great when changing the option **Show only my team?** is switched off, a people picker is shown to select a starting person.

Excluding certain account by using Regex or something like this will also be great but is not critical at this stage.

Thank you so much for your assistance so far. It is really appreciated. 🙂

**Comment by johanvandy** [comment]
Hi @petkir 

Any progress\changes that I can test?

**Comment by petkir** [comment]
Hi @johanvandy,

I have read your suggestion, and I was thinking about combining this thing with another sample:
[React-Directory](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-directory)

In this Sample the SPComponentLoader is used:
```
const LIVE_PERSONA_COMPONENT_ID: string =
  '914330ee-2df2-4f6e-a858-30c23a812408';
SPComponentLoader.loadComponentById(.....

```
the only thing is this component does not work at the localhost workbench.

I will do this over the weekend

**Comment by johanvandy** [comment]
Hi @petkir,

Much appreciated. Localhost workbench is not a problem as I can test against one of our online sites.

Really appreciate your assistance!

**Comment by petkir** [comment]
@johanvandy 

this is the current status

![20210226225411735](https://user-images.githubusercontent.com/13123689/109359625-13ea3900-7886-11eb-881c-50901752b80d.gif)

Currently, this Sample uses the SharePoint User Profile Service EndPoint to get User data, I would be thinking about changing this to Graph API EndPoint. 
@hugoabernier what do you think UPS or **Graph**? If Graph one or two pull Requests?

**Comment by johanvandy** [comment]
Hi @petkir 

That looks great. How can I get a copy to test?

**Comment by johanvandy** [comment]
Hi @petkir 

Tried 8 times to download latest version of the repository from https://github.com/pnp/sp-dev-fx-webparts by selecting **download zipfile** from the **Code button** and every time the downloaded file size is different. Trying to extract the downloaded files, it reports that the files is corrupt.

Can you assist?

**Comment by johanvandy** [comment]
Hi @petkir 

I managed to get the latest and tested. It is working awesome. It is just a little slow to load the data when there are a lot of people in the tree.

Thank you so much for your assistance. It is much appreciated. 🙂

**Comment by petkir** [comment]
Hi @johanvandy ,

Each level requires a request, if the tree structure is bigger it will take more time.

thanks for the confirmation, that the initial issue is solved. 

@hugoabernier, please please close this issue.

**Comment by johanvandy** [comment]
Hi @petkir @hugoabernier 

Again, thank you so much. You guys are great!!!
