### ISSUE TITLE
Sample : react-script-editor

### ISSUE THREAD

**Issue by mykoupaei** [pnp/sp-dev-fx-webparts#1729]
Thanks to Mr. Mikael Svenson.
I have a some problem about the app. i discuss the following.
I could add app of web part and i check its feature in manage site feature but Modern script editor web part disappear in web part section.
Please' Help me!!!!!

**Comment by hugoabernier** [comment]
@mykoupaei I think you'll have better luck if you `@` tag the author(s) of the sample so they get notified of your question.

**Comment by Abderahman88** [comment]
Maybe this could help https://github.com/pnp/sp-dev-fx-webparts/issues/1744

**Comment by hugoabernier** [comment]
Closing this issue as resolved.
