### ISSUE TITLE
react-members-with-presence

### ISSUE THREAD

**Issue by joshburns49** [pnp/sp-dev-fx-webparts#1730]
@luismanez 

Is there a way we can get this web part working on a communication site? I have tested it in both a team site and communication site, works fine in the team site but get 403 errors in the communication site.

I am using the property pane to specify the group id instead of using the site group id property in the web part.

Thanks

Josh

**Comment by hugoabernier** [comment]
@joshburns49 I'm not the author of the sample. You may get faster help if you tag the author of the sample.

**Comment by joshburns49** [comment]
Apologies @hugoabernier

**Comment by luismanez** [comment]
What you mean by "I am using the property pane to specify the group id" ? A communication site has no Group in Microsoft 365, so you can´t get the Graph Group members. In essence the Presence API just need a User ID, so (I guess) you can use SP REST API to get the Users of the SP Site, with their IDs, and use them to get their presence.

**Comment by hugoabernier** [comment]
@joshburns49 did @luismanez 's answer solve your issue? Let us know so we can close the issue.

**Comment by joshburns49** [comment]
I have replaced the description field in the property pane with "Group ID" and altered the api call so that the call checks for the group id. 

const endpoint: string = `https://graph.microsoft.com/beta/groups/${this.props.groupId}/members?$select=id,displayName,department`;

I think this is working and can be closed. Thanks guys :)
