### ISSUE TITLE
react-list-search

### ISSUE THREAD

**Issue by kbrhoades** [pnp/sp-dev-fx-webparts#1737]
## Sample (which sample are you talking about)

react-list-search

## Authors

@albegut 

## Question

I am new to this so thank you in advance for your patience.  I have successfully installed these framework samples before on our tenant.  When I install this one & try to configure it no matter what I enter for source data all I get is "No search results".    Any advice would be appreciate, this looks like it would solve exactly what I am looking to do.  Thank you.

![image](https://user-images.githubusercontent.com/11978177/109174694-11d38d80-7753-11eb-8e88-3a604f40f4eb.png)

**Comment by albegut** [comment]
Hi @kbrhoades that control it´s a [site picker](https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldSitePicker/) control. You have to type the name of the site that contains the information that you want to retreive

**Comment by kbrhoades** [comment]
I realize it was searching by name, not URL.  Works great!
