### ISSUE TITLE
React Feeback WP: Doesn't Display Button

### ISSUE THREAD

**Issue by clohigh** [pnp/sp-dev-fx-webparts#1739]
## Sample
> Which sample are you having trouble with? 

The react feedback web part

## Authors
@PerryKankam

## Expected or Desired Behavior

> What should it do?

It should display a feedback button after running a npm install and then a gulp serve

## Observed Behavior

> What does it do?

It doesn't display the feedback button.

## Steps to Reproduce

1. Go to 'pnp/sp-dev-fx-webparts' 
2. Download or clone the solution
3. Run a npm install and gulp serve
4. It won't display the button on a local workbench or site workbench

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10  
- **Target Environment**: SharePoint Online
- **Framework**:  Node.js v8
- **Browser(s)**: Chrome v79
- **Tooling**: SPFx v1.11.0 
- **Additional details**:

**Comment by Abderahman88** [comment]
Hello @clohigh,

I can confirm the issue and I made a quick fix.
