### ISSUE TITLE
Reactive-Adaptivecards : Input.number rendering as undefined

### ISSUE THREAD

**Issue by cbathis** [pnp/sp-dev-fx-webparts#1746]
Ref - https://adaptivecards.io/explorer/Input.Number.html 
https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/react-adaptivecards/assets/UIFabric.png

"adaptivecards": "^1.2.6",
    "adaptivecards-fabric": "^1.1.1",
    "adaptivecards-templating": "1.1.0",

@hugoabernier Please assist

![image](https://user-images.githubusercontent.com/79204723/109489092-6442e000-7aac-11eb-9a34-0145f9e36374.png)

**Comment by devanshuGit** [comment]
@hugoabernier is there a way we can have short call, it might help us get answer of all queries in one.
We are trying to use the solution in bot using react web chat. But there are several input controls were we are having trouble.
Merging this solution rendering of adaptive cards with the custom middleware sample as in this sample
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/e.card-components

**Comment by jayarau** [comment]
@hugoabernier  It Seems to be issue in adaptivecards-fabric package. We are using  "adaptivecards-fabric": "^1.1.1",. When we do not use Fabric controls when rendering Adaptive Cards It works fine. But with ACFabric.useFabricComponents(); It do not allow to enter inputs.
Screenshot of working Solution:
![AdaptiveCardsIssue](https://user-images.githubusercontent.com/73291456/109616457-281a8880-7b5b-11eb-94db-27421a4fdaf3.PNG)

Can you please check adaptivecards-fabric package and update.
