### ISSUE TITLE
react-directory: Sorting

### ISSUE THREAD

**Issue by johanvandy** [pnp/sp-dev-fx-webparts#1749]
## Sample
react-directory

## Authors
@hugoabernier @petkir @joaojmendes @sudharsank 

## Expected or Desired Behavior
Selecting a **Sort People by** option has no effect. 

## Observed Behavior
None

## Steps to Reproduce
1. run gulp serve
2. Select any option from the **Sort People by** dropdown
3. Results is not sorted

# Environment Details (*Development & Target environment*)
- **OS**: Windows 10
- **Target Environment**:  SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chrome v88| IE v11 | Edge]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 ]

**Comment by Abderahman88** [comment]
@johanvandy 

I can confirm your issue and I'm working on a solution.

Stay tuned 📺 

@hugoabernier Assign to me pls 🙏

**Comment by petkir** [comment]
@Abderahman88 you are welcome to solve this. Order by in graph call is a fast and simple solution

**Comment by Abderahman88** [comment]
@johanvandy I made a quick fix for the problem.

@petkir The functionality was already implemented, but `useEffect` didn't get triggerd when setting the users-state.

**Comment by petkir** [comment]
@Abderahman88 you are right.
I looked at the wrong sample, react-tree... sorry for that.

**Comment by johanvandy** [comment]
> @johanvandy I made a quick fix for the problem.
> 
> @petkir The functionality was already implemented, but `useEffect` didn't get triggerd when setting the users-state.

@Abderahman88 

Great! Please keep me posted and let me know when\where I can get the fix

**Comment by Abderahman88** [comment]
@johanvandy You can wait when the fix is approved by the maintainers.

If you need it asap, here is my solution:
[react-directory.zip](https://github.com/pnp/sp-dev-fx-webparts/files/6102638/react-directory.zip)

**Comment by johanvandy** [comment]
Hi @Abderahman88 (@hugoabernier @petkir @joaojmendes @sudharsank)

I have tested your compiled solution (sppkg package downloaded) on our dev environment and can confirm that sorting is now working as expected.

**Comment by Abderahman88** [comment]
@johanvandy You're welcome. If you have any questions/issues, let us know 😉

**Comment by johanvandy** [comment]
Hi @Abderahman88 (@hugoabernier @petkir @joaojmendes @sudharsank )

I have noticed that another question ([https://github.com/pnp/sp-dev-fx-webparts/issues/1763](url) - displaying external users\guests) has been logged.
This is also something that I will be interested in being implemented. Maybe add on toggle option to enable the inclusion of external users\guests?
