### ISSUE TITLE
Advance comment box - Ping users

### ISSUE THREAD

**Issue by shwetashukla** [pnp/sp-dev-fx-webparts#1753]
## https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/js-advanced-commenting

> @sudharsank 

>In the comment box we can ping users , does this send a mail too . How does the functionality work apart from mention user in the comment box

**Comment by sudharsank** [comment]
Hi @shwetashukla, the ping will just capture the user info and display on the UI, there is no specific functionality to send email to the pinged users. I am working on it and soon will update the solution in the repo.
