### ISSUE TITLE
react-staffdirectory: Teams personal tab installation

### ISSUE THREAD

**Issue by bender9978** [pnp/sp-dev-fx-webparts#1762]
I tried to install this webpart as Teams personal tab.

I have modified StaffDirectoryWebPart.manifest.json with 
 "supportedHosts": ["SharePointWebPart", "TeamsPersonalApp"],

but it does not work, this is the error:

e.themeVariant is undefined

CALL STACK:
fp@https://m365x371056.sharepoint.com/sites/appCatalog/ClientSideAssets/89d7389c-be48-41e9-9f72-5eb9a1099c1f/staff-directory-web-part_d8295d19b188578bc884cf2862d99c65.js:1:1997616
Bi@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:63844
mo@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:110056
ou@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:102609
iu@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:102532
Go@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:99562
Ko@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:96330
Fu@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:117766
ju/<@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:119006
Jo@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:99909
ju@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:118992
lTeb/t.render@https://modern.akamai.odsp.cdn.office.net/files/sp-client/react-dom-16-bundle_none_aaa75c34c919346155b0.js:1:121963
lW1U/Cp</t.prototype.render@https://m365x371056.sharepoint.com/sites/appCatalog/ClientSideAssets/89d7389c-be48-41e9-9f72-5eb9a1099c1f/staff-directory-web-part_d8295d19b188578bc884cf2862d99c65.js:1:2008432
mwqp/H</t.prototype._renderWithAccessibleTitle@https://modern.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_ccc853fec82d29d728a093aa30d90dbd.js:65:545489
mwqp/H</t.prototype._onInViewport/</<@https://modern.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_ccc853fec82d29d728a093aa30d90dbd.js:65:545043

what could be the problem?

Thanks

**Comment by hugoabernier** [comment]
@bender9978 in order to be able to help you, we'll need you to fill in the issue template in full, including web part name, author, environment, etc. 

I'll go ahead and close this issue as incomplete,  but feel free to open a new issue with the details we ask.
