### ISSUE TITLE
react-content-query-online: Error running npm install

### ISSUE THREAD

**Issue by aliiamar** [pnp/sp-dev-fx-webparts#1767]
## Sample
react-content-query-online

## Authors
@PopWarner @hugoabernier @PaoloPia 

## Expected or Desired Behavior

npm install should complete without errors and correct files should be installed in node_modules

## Observed Behavior

A very long error message appears:

PS C:\Users\alia\SPFX\sp-dev-fx-webparts-master\samples\react-content-query-online> npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN tarball tarball data for @microsoft/sp-webpart-workbench@1.11.0 (sha512-I9Tder5SP2dzQuQixp4FFx4FElRXvGtjoDhkn7tWoIkIorDLrTnHNN8fCUKFezhpOVZkPkARHIy5BSHEjJQPaw==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\alia\SPFX\sp-dev-fx-webparts-master\samples\react-content-query-online\node_modules\.staging\bail-d5d19a9f\license'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\alia\SPFX\sp-dev-fx-webparts-master\samples\react-content-query-online\node_modules\.staging\bail-d5d19a9f\index.js'

Required files are not installed properly, instead only have one folder .staging
![node_module folder empty](https://user-images.githubusercontent.com/31994200/110587798-10707f00-81af-11eb-9762-ee730d86c62d.PNG)

## Steps to Reproduce

1. Download master zip file and extract to C: drive
2. Navigate to sample folder of specific web part in command prompt
3. Run npm install --global gulp
4. Run npm install
5. See error

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10 Enterprise
- **Target Environment**: SharePoint Online
- **Framework**: node.js v8/v10
- **Browser(s)**: Chrome v88
- **Tooling**: SPFx v1.11.0
- **Additional details**: I have tried both with node.js v8.x and v10.x but still issue persists

## Additional context

I have also tried with other similar sample _react-content-query-onprem_ but that one face issue during gulp serve instead

**Comment by Ravikadri** [comment]
Did an npm install, build, and don't see any issues. From the Environment Details(you mentioned) looks like you are using SPFx v1.10.0. Try with SPFX version1.11.0 and see if this error goes away.

-Ravi

**Comment by Abderahman88** [comment]
Try to delete the `node_modules`-folder and do `npm install` again. Does this help?

**Comment by aliiamar** [comment]
@Abderahman88 I have rerun `npm install` after clearing the `node-modules` folder but still same error message appears

@Ravikadri Sorry for the wrong info in the question, I have edited it. Current version is 1.11.0

![image](https://user-images.githubusercontent.com/31994200/110898534-602f8180-833a-11eb-9d9a-84c191fcb18c.png)

**Comment by Ravikadri** [comment]
By looking at the log, all the NPM install says "WARN" and not errors. Does it stop you from building and packing it? This is what i would try.

1. Delete node modules and run a gulp clean
2. Run npm install(ignore Warnings)
3. Run Gulp build
4. if no error, package it.

If you still get the issue, please share the error. 

Thanks!
Ravi

**Comment by aliiamar** [comment]
Okay I have permanently deleted the `node-module` folder, ran a `gulp clean` and receive this error:

```
PS C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online> gulp clean
[10:48:01] Local modules not found in ~\sp-dev-fx-webparts\samples\react-content-query-online
[10:48:01] Try running: npm install
```

Then after running npm install I got the same warning messages but found this at the end of the messages:

```
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\.staging\office-ui-fabric-react-8f9e6ae9\lib-amd\components\TextField\TextField.base.js'
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\.staging\@microsoft\sp-webpart-workbench-b7651e83\local-workbench\sp-default-assembly_default.js
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\.staging\@microsoft\sp-webpart-workbench-b7651e83\local-workbench\sp-default-assembly_default.js'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\.staging\@microsoft\sp-webpart-workbench-b7651e83\local-workbench\sp-default-assembly_default.js']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\.staging\@microsoft\sp-webpart-workbench-b7651e83\local-workbench\sp-default-assembly_default.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\Users\\alia\\sp-dev-fx-webparts\\samples\\react-content-query-online\\node_modules\\.staging\\@microsoft\\sp-webpart-workbench-b7651e83\\local-workbench\\sp-default-assembly_default.js' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Users\\alia\\sp-dev-fx-webparts\\samples\\react-content-query-online\\node_modules\\.staging\\@microsoft\\sp-webpart-workbench-b7651e83\\local-workbench\\sp-default-assembly_default.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\Users\\alia\\sp-dev-fx-webparts\\samples\\react-content-query-online\\node_modules\\.staging\\@microsoft\\sp-webpart-workbench-b7651e83\\local-workbench\\sp-default-assembly_default.js',
npm ERR!   parent: 'react-content-query-online' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alia\AppData\Roaming\npm-cache\_logs\2021-03-15T02_57_14_576Z-debug.log
```

I have always run all the commands by launching my PowerShell as administrator. Ignoring the messages, I ran gulp build and receive these:

```
PS C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online> gulp build
[15:15:44] Local gulp not found in ~\sp-dev-fx-webparts\samples\react-content-query-online
[15:15:44] Try running: npm install gulp
```

As you guessed, running `npm install gulp` also return the same type of warning messages.

Also had some trouble running `npm cache clean`, so I checked my npm version then run `npm cache verify`:

```
PS C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online> npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alia\AppData\Roaming\npm-cache\_logs\2021-03-15T06_37_49_915Z-debug.log
PS C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online> npm -v
6.14.11
PS C:\Users\alia\sp-dev-fx-webparts\samples\react-content-query-online> npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 3428 (343426652 bytes)
Index entries: 3911
Finished in 189.108s
```

Really appreciate all your help on this as I am still a beginner with this framework.

**Comment by Abderahman88** [comment]
@aliiamar 

Which version of node are you using (V8/V10)?
Can you please check in CMD

![checkNode](https://user-images.githubusercontent.com/36161889/111391051-1f29cb00-86b4-11eb-901c-9ea044fa3c89.PNG)

If V10, try these steps:
1) Delete `node_modules`
2) Run VSCode as administrator
3) Delete package-lock.json
4) npm install

**Comment by aliiamar** [comment]
Hi @Abderahman88 

Yes I am using node v10 and followed your steps exactly and encountered below errors:

```
PS C:\Users\alia\sp-dev-fx-webparts> node -v
v10.24.0
PS C:\Users\alia\sp-dev-fx-webparts> npm -v
6.14.11
```

```
npm WARN deprecated cryptiles@4.1.3: This module has moved and is now available at @hapi/cryptiles. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version 
is no longer maintained an may contain bugs and security issues.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version 
is no longer maintained an may contain bugs and security issues.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated es6-collections@0.5.6: not actively maintained anymore
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.      
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, 
upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js      
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN notsup Unsupported engine for open@8.0.2: wanted: {"node":">=12"} (current: {"node":"10.24.0","npm":"6.14.11"})
npm WARN notsup Not compatible with your version of node/npm: open@8.0.2

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/microsoftgraph/msgraph-typescript-typings.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alia\AppData\Roaming\npm-cache\_logs\2021-03-17T01_23_10_860Z-debug.log
```

**Comment by Abderahman88** [comment]
@aliiamar 

I downloaded, installed and ran a clean version of `react-content-query-online` with no problems.

Your node and npm versions are OK.

Can you check what version of  @microsoft/generator-sharepoint and gulp is installed globally ?

`npm list -g --depth 0`

![sharepointGen](https://user-images.githubusercontent.com/36161889/111720966-3fe25400-885f-11eb-9bc8-088782f2f5d4.png)

**Comment by aliiamar** [comment]
@Abderahman88 

My version same as yours. I tried with other samples and theres no issue. 
For this sample, I deleted the `node_modules` folder and try to run `npm install` but to no avail.

![image](https://user-images.githubusercontent.com/31994200/111760887-30542100-88da-11eb-9469-d1e3675f389a.png)

**Comment by aliiamar** [comment]
@Abderahman88 after deleting all extracted and cloned files and then cloned a new version of the `sp-dev-fx-webparts`, I am still facing issue when running `npm install` on `react-content-query-online`. Really appreciate your input on this.

![image](https://user-images.githubusercontent.com/31994200/112112537-9c8f9700-8bf0-11eb-81c4-c2652c9caaa2.png)

![image](https://user-images.githubusercontent.com/31994200/112112694-ccd73580-8bf0-11eb-8fa8-c6df0ec84c01.png)

An extract from the 2021-03-23T07_07_35_572Z-debug.log file:

![image](https://user-images.githubusercontent.com/31994200/112112645-bf21b000-8bf0-11eb-97ac-7b0781f1c0c1.png)

**Comment by Abderahman88** [comment]
@aliiamar

I think I have an idea for a solution.

The problem points to `msgraph-typescript-typings.git`. (Simular question: https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/283)

You need to have installed [Git for Windows](https://git-scm.com/download/win).

You can check this by using the command `git --version`

![gitInstalled](https://user-images.githubusercontent.com/36161889/112236368-95907500-8c40-11eb-9d4b-4697fb33baae.PNG)

**Comment by aliiamar** [comment]
@hugoabernier @Abderahman88 I believe both methods made it work for me!

I moved the project to `C:\react-content-query-online`, installed Git for Windows, but somehow still face the same error.

But after referring the solution from [here](https://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path#23179102) by adding both Git path below to Windows path, finally I was able to package the solution successfully. 

```
C:\Program Files\Git
C:\Program Files\Git\cmd
```

Thank you so much for the great support!

**Comment by Abderahman88** [comment]
@hugoabernier Should we add the `Git for Windows`-requirement to the README ?

**Comment by hugoabernier** [comment]
> @hugoabernier Should we add the `Git for Windows`-requirement to the README ?

That's a great idea. I guess in the future we should remove that dependency, but until then updating the `README.md` is probably the easiest way to solve this issue.
