### ISSUE TITLE
react-content-query-webpart: Fluent UI CSS Icons not working when News webpart also present on same SharePoint page

### ISSUE THREAD

**Issue by PaulieShore** [pnp/sp-dev-fx-webparts#1770]
I'm really not sure where to post this bug. It could SharePoint Online. It could be the way the React Content Query Webpart is loading/rendering CSS. 

## Sample
react-content-query-webpart

## Authors
@PopWarner
@hugoabernier
@PaoloPia

## Expected or Desired Behavior
Fluent UI Icons should be usable in Content Query Webpart when loading CSS file. 
`<link
  rel="stylesheet"
  href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css"
/>`

## Observed Behavior
Fluent UI Icons load but then disappear. This only occurs on pages where the News webpart is also loaded. 

## Steps to Reproduce

1. Create React Content Query Webpart on blank SharePoint page. Define a List to pull from. 
2. Insert the code below into the Template Content. 
3. Refresh the page, Fluent UI icons will load. 
4. Add a News webpart. Define a news source. 
5. Publish. Refresh the page. 
5. Fluent UI icons in Content Query Webpart load but then disappear from page. 

Template Content Code:
`<link  rel="stylesheet"  href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css" />`
`<div class="ms-Fabric">ALERT ITEM! <i class="ms-Icon ms-Icon--AlertSolid" aria-hidden="true"></i></div>`

# Environment Details (*Development & Target environment*)
- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: N/A
- **Browser(s)**: Google Chrome, Edge, IE, FireFox
- **Tooling**: N/A
- **Additional details**: Just using standard HTML loading the Fluent UI stylesheet within the React Content Query Webpart, https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css. 

## Additional context
I'm not entirely sure if it's just the News Webpart that impacts the Fluent UI icons.

**Comment by Abderahman88** [comment]
@PaulieShore 

Tested and you're correct. This bug needs a fix

**Comment by AriGunawan** [comment]
It doesn't work as well for me in the **Edit Page mode** but after republishing AND refreshing the page, it's working as expected.

Edit Page mode
![image](https://user-images.githubusercontent.com/8691985/112757194-e1f9fd00-9012-11eb-99d4-8be5bcc165f3.png)

Published mode
![image](https://user-images.githubusercontent.com/8691985/112757088-626c2e00-9012-11eb-9259-cc96ffb40823.png)

**Comment by PaulieShore** [comment]
Try adding an item to the news webpart.

**Comment by AriGunawan** [comment]
Still working as expected for me.
I tested the deployed app in Chrome and Edge.

![image](https://user-images.githubusercontent.com/8691985/112759514-7e290180-901d-11eb-86ce-ad399e0c1e2d.png)

**Comment by PaulieShore** [comment]
Here's an example of icons not loading (ignore the first icon beside "Alert", this is not a UI Fabric icon). As you can see the icon loads, then disappears. 

![SPFX Icons Not Loading](https://user-images.githubusercontent.com/1333865/112831719-bc98dd80-906a-11eb-848c-a31dfa04e89b.gif)

If I remove the News webpart, icon works as expected.

**Comment by JohnMoor** [comment]
I have the same issue. Fluent UI icons disappear after scrolling, when the News web part is placed before this web part. If you position the News web part below the Content Query web part, it works as expected. 

@PaulieShore did you find a work-around for this problem?

**Comment by PaulieShore** [comment]
> I have the same issue. Fluent UI icons disappear after scrolling, when the News web part is placed before this web part. If you position the News web part below the Content Query web part, it works as expected.
> 
> @PaulieShore did you find a work-around for this problem?

Unfortunately, it's still an issue and I never found a way to mitigate the issue. If you find a solution, please share. I'd really like to use the FluentUI icons.
