### ISSUE TITLE
react-staffdirectory: "Insufficient privileges to complete the operation." 

### ISSUE THREAD

**Issue by balaji830** [pnp/sp-dev-fx-webparts#1782]
I have followed the instructions and approved the API access on SPO Admin site as well. But still get Insufficient Privileges error? I have also looked at #1752 and I have verified Azure AD as well and looks similar what Tristian has on his screen shot. But still gets an error. Any help would be appreciated.

**Comment by hugoabernier** [comment]
Sorry, we can only accept issues that follow the issue template that is provided.

Feel free to create a new issue and take the time to fill all the required sections so we can get you the help you deserve. 

Thanks for your understanding.
