### ISSUE TITLE
react-staffdirectory: "Insufficient privileges to complete the operation"

### ISSUE THREAD

**Issue by balaji830** [pnp/sp-dev-fx-webparts#1783]
## Sample
react-staffdirectory

## Authors
João Mendes @joaojmendes

## Expected or Desired Behavior
It should render the web part.

## Observed Behavior
Displays error message as shown below
![image](https://user-images.githubusercontent.com/36411797/112177578-7279ad00-8bcf-11eb-93bd-189a3c1254e5.png)
As indicated in the Issue 1752, I also see the 403 message in the console. Below is the screen shot of the console message.
![image](https://user-images.githubusercontent.com/36411797/112177887-b1a7fe00-8bcf-11eb-907a-b354b53cdc7a.png)

## Steps to Reproduce
Deploy the web part as provided in the sample's documentation. Additionally I have also provided API access from SPO admin site and verified the Azure AD API access for SharePoint Online Client Extensibility Web Application Principal. (Below screen shot for both)
![image](https://user-images.githubusercontent.com/36411797/112178760-69d5a680-8bd0-11eb-9c7c-c1cdd4d83646.png)
![image](https://user-images.githubusercontent.com/36411797/112178860-81149400-8bd0-11eb-86d5-1ae00e6302fa.png)

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chromium Edge
- **Tooling**: VS Code
- **Additional details**:

**Comment by hugoabernier** [comment]
@balaji830 can you confirm that you're running the web part on the **hosted** workbench, _not_ the **local** workbench?

Also, you'll probably have more luck if you actually `@` mention the author of the sample instead of just saying their name. They won't get notified of this issue otherwise.

**Comment by balaji830** [comment]
It is deployed to the **App catalog and installed on the site**. So It is not running on either hosted workbench or local work bench.
