### ISSUE TITLE
react-accordion-dynamic-section: Not working in IE11

### ISSUE THREAD

**Issue by johanvandy** [pnp/sp-dev-fx-webparts#1786]
## Sample
react-accordion-dynamic-section

## Authors
@ejbenke @jerryyasir @hugoabernier 

## Expected or Desired Behavior
Currently only working in Chrome, Edge, Firefox

## Observed Behavior
Once added to a page using IE 11, it give and error as in the image below.
![react-accordion-dynamic-section_err](https://user-images.githubusercontent.com/44995057/112599138-2ff6e100-8e18-11eb-96a6-7c197daad03d.png)

When doing the same using Chrome, Edge, etc. it works as expected

## Steps to Reproduce
1. Duplicate web part from repository
2. Run gulp bundle --ship and then and run gulp package-solution --ship
3. Add .sppkg to your SharePoint App Catalog
4. Add the web part to a page using IE 11
5. If web -part is added using Chrome\Edge it works. Browsing page with IE 11, produces error as in image above.

## Environment Details (*Development & Target environment*)
- **OS**:  Windows 10.20.1
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chrome v89 |  IE v11 | Edge 
- **Tooling**: VS Code | SPFx v1.10.0 | @microsoft/generator-sharepoint@1.12.0 | @pnp/cli-microsoft365@3.7.0 | gulp@4.0.2 | yo@3.1.1

## Additional context
I have tried adding\including pnp polyfill (npm install @pnp/polyfill-ie11 --save), but it still gives an error.

**Comment by johanvandy** [comment]
Hi guys,@ejbenke @jerryyasir @hugoabernier

Any movement\feedback on this one?

**Comment by hugoabernier** [comment]
Microsoft stopped supporting IE 11 for Microsoft 365 apps and services on November 30, 2020. Closing this issue.
