### ISSUE TITLE
AdoptiveCardHost:Data Source URL

### ISSUE THREAD

**Issue by allafridman** [pnp/sp-dev-fx-webparts#1789]
I have a list in the sub-site, and it is not showing up in the drop down lists if I use webpart at the site collection level.
Can I use URL option to enter rest api call or graph calls? What is URL option is used for in Adaptive Card Host webpart?

**Comment by hugoabernier** [comment]
Hey @allafridman you can use the URL to load a different template or a data source in JSON format.

I'll close this issue as it is pretty old. If you need more help, please make sure to tag the author(s) of the sample (in this case: me!) so that we can be notified of the issue.
