### ISSUE TITLE
react-list-search CAML query issue

### ISSUE THREAD

**Issue by PiusHodel-91** [pnp/sp-dev-fx-webparts#1804]
### What's the expected behavior
Love the Webpart from @hugoabernier, I'm customizing it to use URL Parameters to further customizing the CAML Queries. However there is an issue with CAML querying the list. Following case:
I'm searching only one list, this can't be done with general search features because changes made to Metadata in the libraries must be instantly correctly filtered. Further Requirements of the customer is using CAML (and passing URL- params which I implemented but not yet deployed - so this can't be the problem). 

**With CAML queries verified with Testing Tools i should be able to filter a library and to show the desired attributes - in my case Documents with metadata - Filter for lookup values and fetch all fields I want.** 

### What's happening instead?

Here comes a weird PnP- specific (as far as I know) problem with CAML into play: only a few fields are loaded correctly and can be used for filtering. Other aren't shown no matter what tweak is made to the query (viewfields etc.). Also the non- loaded fields can't be used for filtering. Furthermore in the Code we find the following lines, which in my understanding apply the CAML filtered fetching:

`  
private async getListItemsByCamlQuery(listId: string, camlQuery: string, queryConfig: QueryHelperEntity): Promise<Array<any>> {
    try {
      const caml: ICamlQuery = {
        ViewXml: camlQuery,
      };
      return this.web.lists.getById(listId).usingCaching().getItemsByCAMLQuery(caml, queryConfig.expandFields.join(','));
    } catch (error) {
      return Promise.reject(error);
    }
}
`
According to [the Docs](https://pnp.github.io/pnpjs/sp/items/) the second parameter should load the missing fields, but they don't seem to do the trick.

Also i couldn't get a satisfying result using the PnP- Powershell command `Get-PnPListItem` with -query and -Fields applied, whereas in other Tools i got the desired result.

Did anyone experience the same or is there someone with more PnP CAML experience and has ideas to work around this problem?

Note: I'm not 100% sure that this isn't a bug, maybe your advice would be to report as bug. 

Thank you all in advance and for those of you who have easter holiday - enjoy! (all others: enjoy the coming weekend ;)

**Comment by darkrob** [comment]
I also have a Problem with views and CAML. If you put two parameters on one field with an OR clause, it fails for me with this error message:

`getData throw an exception. Error Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-2130575340, Microsoft.SharePoint.SPException","message":{"lang":"de-DE","value":"Mindestens ein Feld ist nicht richtig installiert. Wechseln Sie zur Listeneinstellungsseite, um diese Felder zu l\u00f6schen."}}}`

The German part says "A field is not installed correctly. Go to the list settings and delete that field.

This CAML Query leads to the error message:

`<View><RowLimit>10</RowLimit><Query><Where><Or><Eq><FieldRef Name='Status' /><Value Type='Text'>Suche</Value></Eq></Or><Or><Eq><FieldRef Name='Status' /><Value Type='Text'>Biete</Value></Eq></Or></Where></Query></View>`

The same goes with a list view that has two filters on one field.

**Comment by ac33y** [comment]
for those who are still having issues with Caml query. you might need to update line where this code is found

return result.replace("</RowLimit></RowLimit>", "</RowLimit>")

update it to

return result.replace("</RowLimit></RowLimit>", "</RowLimit>").replaceAll("</Value></Value>", "</Value>");

replaceAll is not applicable on this, you need to update to eslint 2021

this is what i have in tsconfig


"lib": [
      "ES2021",
      "es6",
      "dom",
      "es2015.collection",
      "es2015.promise"
    ]

rush stack compiler should be 4.x version.

for me, below is what i used

"extends": "./node_modules/@microsoft/rush-stack-compiler-4.5/includes/tsconfig-web.json",
