### ISSUE TITLE
[Web Part Name]: [Issue Title]

### ISSUE THREAD

**Issue by billieduo** [pnp/sp-dev-fx-webparts#1808]
I am trying to run react-carousel , got error when run command; npm  install
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.22.tgz failed, reason: Socket timeout

May someone tell what I should do? 

thanks!

**Comment by hugoabernier** [comment]
Closing this issue as incomplete. If you need help with this issue, feel free to open a new issue and fill the issue template with all the required sections, including author, environment information, repro steps, etc.
