### ISSUE TITLE
[Web Part Name]: [Issue Title]

### ISSUE THREAD

**Issue by billieduo** [pnp/sp-dev-fx-webparts#1809]
Which sample are you having trouble with? 
  I could not run sample: react-carousel
> Issues without a sample name will be closed automatically 
    when run command: npm install, got error: 
    npm ERR! code ERR_SOCKET_TIMEOUT
    npm ERR! errno ERR_SOCKET_TIMEOUT
     npm ERR! request to https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.22.tgz failed, reason: Socket timeout

**Comment by hugoabernier** [comment]
Thank you for reporting the issue, however we need you to fill the complete issue template so we can help you properly. 

I'm going to go ahead and close this issue as incomplete, but feel free to open a new issue with the full details, including the environment information (version of node, OS, etc.) as per the issue template.

Also, note that authors don't get notified of the issue unless you @mention them (i.e.: put an '@' in front of their GitHub username). If you wan the original author to help you, you may want to take the time to tag them in your next issue.

Thanks for your understanding!
