### ISSUE TITLE
react-list-form: attachment upload not working with iOS

### ISSUE THREAD

**Issue by goodcurtis** [pnp/sp-dev-fx-webparts#1811]
Hi guys,

thanks for this awesome form.

We see an issue with uploading attachments to a SharePoint list when submitting the form from an iOS device, while it works well on desktop.

Any ideas what could be causing a problem with uploading files from iOS devices?

EDIT: it seems to be working well when I don't make use of "URL to redirect after saving".
Is this maybe a race condition of some sort? (attachment not transferred when loading new page)

Thanks!
Curtis

**Comment by hugoabernier** [comment]
@goodcurtis it looks like a recent pull request may have resolved this issue. I'll go ahead and close this, but if you're still running into issue, please don't hesitate to open a new issue with more details and we'll continue investigating.
