### ISSUE TITLE
React Quick Poll: Issue in display response

### ISSUE THREAD

**Issue by dips365** [pnp/sp-dev-fx-webparts#1812]
## Sample
> Which sample are you having trouble with? 
react-quick-poll

## Authors
@sudharsank  

## Expected or Desired Behavior

> What should it do?
Correct Response should be displayed in web part which is actual selected by user.

## Observed Behavior

> What does it do?
User is getting different value after submitting the response.

## Steps to Reproduce

1. Deploy web part in your tenant
2. Create a question for poll. Allow multiselect while submitting response.
3. Give response on that poll by one user
4. Give response on that poll by second user
5. Second user will get wrong value.

![image](https://user-images.githubusercontent.com/40450958/113688724-37a36900-96e7-11eb-86dc-0b83c3d9f992.png)

# Environment Details (*Development & Target environment*)

- **OS**:  Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**:  Chrome Version 89.0.4389.114 
- **Tooling**: VS Code

**Comment by eldoro80** [comment]
Experienced the same issue when using the webpart. Will be following the issue(-:

**Comment by sudharsank** [comment]
Hi @dips365 & @eldoro80, let me check and get back to you on the webpart.

**Comment by dips365** [comment]
@sudharsank 

I just gone through the code and found very nominal change in getAllUsersResponse() method.

It is taking first record from the total response.
currentPollResponse: usersResponse[0].Response ? usersResponse[0].Response : usersResponse[0].MultiResponse.join(',')

It should be like 
currentPollResponse: filRes[0].Response ? filRes[0].Response : filRes[0].MultiResponse.join(',')

Hope, It might help you and save your time.

**Comment by dips365** [comment]
Could you assign this one to me ?

**Comment by hugoabernier** [comment]
Hey @dips365 sorry I just noticed that you had requested to have this assigned to you. Thanks for volunteering!

**Comment by hugoabernier** [comment]
Marking this issue as solved due to #1948
