### ISSUE TITLE
[react-list-search]: [Errors on 2019 On-Prem gulp serve]

### ISSUE THREAD

**Issue by amalwayscharan** [pnp/sp-dev-fx-webparts#1813]
react-list-search (https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-list-search)

Authors
Alberto Gutiérrez (@albertogperez)

Expected or Desired Behavior
The web part shouldn't throw any errors and be able to pull in list info on dropdown fields. 

Observed Behavior
Tried the following:
1. Added .SPPKG package file in AppCatalog throws below errors in App Package Error Messages

`There were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsDomainIsolated' attribute is not declared.' on line '1', position '293'., Xml Validation Exception: 'The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has invalid child element 'DeveloperProperties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'. List of possible elements expected: 'SupportedLocales, SettingsPage, SupportPage, UninstallingEventEndpoint, StartPage, WebTemplate, SupportedLanguages, UpgradedEventEndpoint, InstalledEventEndpoint' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '365'.`

2. Tried to download and npm install and opened the web part in 2019 workbench using gulp serve; throws below errors when tried to load the list search web part.

```
[SPLoaderError.loadComponentError]:
***Failed to load component "306e0650-db3c-443a-a698-12be6e6de1ad" (ListSearchConsumerWebPartWebPart).
Original error: ***Manifest not found for component id "974a7777-0990-4136-8fa6-95d80114c2e0" and version "1.11.0".

***INNERERROR:
***Manifest not found for component id "974a7777-0990-4136-8fa6-95d80114c2e0" and version "1.11.0".
***CALLSTACK:
Error
    at t [as constructor] (https://site/_layouts/15/next/spclient/en-us/sp-webpart-workbench-assembly.js?uniqueId=hhPtU:283:15766)
    at new t (https://site/_layouts/15/next/spclient/en-us/sp-webpart-workbench-assembly.js?uniqueId=hhPtU:914:22174)
    at Function.e.buildErrorWithVerboseLog (https://site/_layouts/15/next/spclient/en-us/sp-webpart-workbench-assembly.js?uniqueId=hhPtU:914:14408)
    at Function.e.buildLoadComponentError (https://site/_layouts/15/next/spclient/en-us/sp-webpart-workbench-assembly.js?uniqueId=hhPtU:914:10829)
    at https://site/_layouts/15/next/spclient/en-us/sp-webpart-workbench-assembly.js?uniqueId=hhPtU:914:62084
```

Steps to Reproduce:

1. npm install and gulp serve on 2019 on premise SharePoint workbench, select search web part from web parts panel. 

Environment Details (Development & Target environment)
OS: Windows 10
Target Environment: SharePoint 2019 On Premise
Framework: Node.js v10.18.0
Browser(s): Chrome v79 | FireFox v31 | Edge
Tooling: VS Code | SPFx v1.10.0

**Comment by albegut** [comment]
Hi @amalwayscharan this web part is made to work in SharePoint Online, It's not prepared to work in onPremise enviroments. This web part use SPFx version 1.11.0, in SharePoint 2019 the [SPFx last supported version is 1.4](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support#which-version-of-the-sharepoint-framework-to-use). You should downgrade the SPFx version in order to be able to fix all the errors 

Sorry for the inconvenience
