### ISSUE TITLE
React Calendar 

### ISSUE THREAD

**Issue by HeatherWaterman** [pnp/sp-dev-fx-webparts#1814]
React Calendar - Why do all the current dates show with a dark background?
<img width="1551" alt="Screen Shot 2021-04-09 at 7 30 51 AM" src="https://user-images.githubusercontent.com/29203625/114173779-b1b13900-9905-11eb-950f-c66897bb784f.png">

@joaojmendes @mohammadamer

**Comment by Abderahman88** [comment]
Hi @HeatherWaterman,

Are you talking about the blue color (all dates) or the green color (current date) ?

Do you want to change the colors?

**Comment by HeatherWaterman** [comment]
Hi @Abderahman88, yes I am talking about all the blue. Is there a way to change the colors?

**Comment by Abderahman88** [comment]
@HeatherWaterman Yes, you can change it.

Option 1) In `Calendar.module.scss`, you chould change the background-color of `dayPropGetter` directly

```
.dayPropGetter {
  //background-color: $ms-primaryBackground;
  background-color: white;
  border-radius: "0px";
  opacity: 0.8;
  color: $ms-themeAccent;
  border: "0px";
  display: "block";
}
```

Option 2) In `_themes.scss`, you could change $ms-primaryBackground from `#0078d7` to another color (Maybe you need to change this in multiple places to get the best result)

![blueColor](https://user-images.githubusercontent.com/36161889/115716569-97ea0a00-a379-11eb-8edd-20c42ed36156.png)

I tried option 1 and this is the result.

![changeColor](https://user-images.githubusercontent.com/36161889/115717019-16df4280-a37a-11eb-9663-f79a4b111cd5.PNG)

**Comment by Abderahman88** [comment]
@HeatherWaterman @hugoabernier Can we close this issue?
