### ISSUE TITLE
React Rss Reader:custom handlebars template not working

### ISSUE THREAD

**Issue by webbrewer** [pnp/sp-dev-fx-webparts#1815]
## Sample
> React rss reader
>
> 

## Authors

@eoverfield 

## Expected or Desired Behavior

> Custom template should let me add styling, customize layout

## Observed Behavior

> What does it do?
>
> When I engage custom template option, the feed is empty - no display. 

## Steps to Reproduce

1. Add rss feed reader web part
2. Open options
3. Select custom template on page 2

>

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10 
- **Target Environment**:  SharePoint Online
- **Framework**:  Node.js v10.16.3
- **Browser(s)**: . Chrome v79 
- **Tooling**: 
- **Additional details**: 

## Additional context
App version 2.0.0.0
Build tools version 3.9.26
Downloaded and built 4/6/21

**Comment by eoverfield** [comment]
I apologize for the delay, looking into this.

**Comment by abel20et** [comment]
@eoverfield What is the fix for this issue?

**Comment by hugoabernier** [comment]
Hey @webbrewer, were you able to resolve this issue with the latest version of the sample? 

I'll go ahead and close this, but if you have more questions, please do not hesitate to open a new issue and provide more information.
