### ISSUE TITLE
React-Script-Editor : Unhandled promise rejection (rejection id: 2)

### ISSUE THREAD

**Issue by sandro54321** [pnp/sp-dev-fx-webparts#1820]
Hi,

i am trying to use thereact-script-editor for sharepoint online. It works fine in my local enviroment but when i try and run gulp bundle -- ship I get an error.

(node:12668) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'toJson' of undefined

not really sure what can be causing it

**Comment by hugoabernier** [comment]
Thank you for your submission, but there isn't enough detail in the issue for us to review & move forward. The new issue template includes sections for you to fill out. Please resubmit your issue and complete the provided sections in the new item template so we can move forward on it refer to our wiki for more information: [How to Create Good Issues](https://github.com/pnp/sp-dev-fx-webparts/wiki/How-to-Create-Good-Issues)
