### ISSUE TITLE
React Script Editor for Modern Communication Hub sites

### ISSUE THREAD

**Issue by srisspfx** [pnp/sp-dev-fx-webparts#1828]
Hi Team,

Downloaded he Script Editor Webpart from the below URL
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor

This does not work on Modern Communication Hub sites, as they are No Script sites by default. We are not able see the React Script Editor Webpart after adding them from Site Contents --> Add an App.

Please help!

**Comment by Abderahman88** [comment]
@srisspfx 

Try this answer : https://sharepoint.stackexchange.com/questions/235612/sharepoint-online-modern-script-editor-webpartspfx-is-not-available-in-some-si

**Comment by srisspfx** [comment]
@Abderahman88 Thanks mate. If I have n number of communication hub sites, should run the below PS Script on each Communication Hub site individually?
Set-SPOSite -Identity "https://<URL>" -DenyAddAndCustomizePages 0
Can I run this at tenant level?

Thanks.

**Comment by Abderahman88** [comment]
@srisspfx Glad to help 👍 

You can enable custom scripts on tenant level (https://sharepoint.handsontek.net/2018/10/28/enable-custom-script-on-modern-sharepoint-sites-using-powershell/#step1), but it's not recommended.

It's better to activate it on each communication site separately.
If you have the option to replace the script editor, this is even better 😄 (for example by a custom webpart)
`

**Comment by Abderahman88** [comment]
@hugoabernier I think this one can be closed
