### ISSUE TITLE
httpClient request authorization token header not working

### ISSUE THREAD

**Issue by omarelanis** [pnp/sp-dev-fx-webparts#1840]
### Sample

Not a specific sample - sorry if this is the wrong place to post!

### Author(s)

None

### Question

I have a similar issue to https://github.com/pnp/sp-dev-fx-webparts/issues/240 whereby I have an Azure function that calls an external API to retrieve an OAuth token, this is sent back to the SPFx webpart and then I am trying to call the external 3rd part API using this authorization token, however in resulting headers the "Authorization: Bearer xxxx" header is removed

My code I am using is as below:

`private GetToken(token: string): Promise<HttpClientResponse> {

    const postURL = "https://api.badgr.io/v2/issuers";
    const requestHeaders: Headers = new Headers();
    requestHeaders.append('Content-type', 'application/json');
    requestHeaders.append('Cache-Control', 'no-cache');
    requestHeaders.append('Authorization', 'Bearer '+token);
    requestHeaders.append('Host', 'api.badgr.io');
    const httpClientOptions: IHttpClientOptions = {
      headers: requestHeaders,
      method: "GET",
      mode: "no-cors"
    };
  
    console.log("About to make REST API request.");
  
    return this.context.httpClient.get(
      postURL,
      HttpClient.configurations.v1,
      httpClientOptions)
      .then((response: HttpClientResponse): Promise<HttpClientResponse> => {
        console.log("REST API response received.");
        
        if (response.ok) {
          return response.json();
      } else {
        alert('Badgr could not authenticate you!');
      }
      });
  }`

Calling the same exact headers to the API using Postman works fine, but whenever I try from within the webpart I get an unauthorized error.

I've tried setting the value directly like this and instead the Authorization header is there but it changes the Bearer xxxxxxxx to just "name": "Authorization", "value": "Authorization" -  looking at the request being sent I can see the header is changed (this is a HAR export from Chrome)

return this.context.httpClient.get(
      postURL,
      HttpClient.configurations.v1,
      {headers: {
        'Authorization': 'Bearer xxxxxxxxxxxxxxxxxxx'
      },
        method: "GET",
        mode: "no-cors"
      })
      .then((response: HttpClientResponse): Promise<HttpClientResponse> => {
        console.log("REST API response received.");
        if (response.ok) {
          return response.json();
      } else {
        alert('Badgr could not authenticate you!');
      }
      });

![API Error](https://user-images.githubusercontent.com/35841910/116482418-07ca2a00-a87d-11eb-8b4b-6dfc471bf619.PNG)

Any guidance would be greatly appreciated as I'm just plain up banging my head against the keyboard now at what should the easy part of the request!

**Comment by hugoabernier** [comment]
Sorry, this issue list is for issues related to the samples in this repository only. You may want to try https://github.com/SharePoint/sp-dev-docs/issues/new instead.
