### ISSUE TITLE
react-list-search - 

### ISSUE THREAD

**Issue by istavnit** [pnp/sp-dev-fx-webparts#1848]
### Sample

react-list-search

### Author(s)

@albegut

### Question

When setting up react-list-search part, during configuration 
![image](https://user-images.githubusercontent.com/7511567/116953721-965ef280-ac53-11eb-90f7-813137127c46.png)
Under Source Data->Sites to Get Data [SEARCH] - not all sites are searchable. It appears only classic sites appear in search.
Does this have to do with app Permissions?

**Comment by albegut** [comment]
Hi @istavnit, there is a [PnP PropertyFieldSitePicker control](https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldSitePicker) and it should search all sites. Please, try to search by site name not by url

**Comment by hugoabernier** [comment]
Hey @istavnit i hope that @albegut 's answer solved your issue?

I'll mark this issue as answered, but feel free to mm a new issue if your run into any further issues.
