### ISSUE TITLE
react-list-search - 

### ISSUE THREAD

**Issue by frankasphaug** [pnp/sp-dev-fx-webparts#1850]
### Sample

react-list-search

### Author(s)

@albegut

### Question

Can you group elements from different lists/libraries using this sample?

IE

Item A on a meeting agenda
   File 1 on Item A
   File 2 on item A

Frank

**Comment by albegut** [comment]
Hi @frankasphaug! , I dont understand the example but yes, it's possible to group information from different lists/libraries. 

In this gif, I've grouped the items from the site name property, but you can choose any property shown in the table to group by. 
This example answer your question? 

![groupedExample](https://user-images.githubusercontent.com/9661096/116975549-1cb11e00-acc0-11eb-99a3-6ebe6cf530a3.gif)
