### ISSUE TITLE
react-list-search - no sites are being found on the configuration panel 

### ISSUE THREAD

**Issue by hsamysaab91** [pnp/sp-dev-fx-webparts#1851]
### Sample

react-list-search

### Author(s)

@albegut

### What happened?

I have uploaded the sppkg to the app catalog, added the webpart. 

However; I can t find any sites to select a source list from. Probably some requests are not working. I tried to open the developer tool but didn t find any errors.

![Capture](https://user-images.githubusercontent.com/38861691/117032193-93bad680-ad01-11eb-8903-2e50d966ab93.PNG)

### Steps to reproduce

1. Go to a new page
2. Add the webpart
3. Select Source on the configuration panel
NOthing

### Expected behavior

We should have all the sites of the tenant available or at least when I add manually a URL it should work

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.11.0

### Node.js version

14.16.1

**Comment by albegut** [comment]
Hi @hsamysaab91, there is a [PnP PropertyFieldSitePicker control](https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldSitePicker/) and it should search all sites. Please, try to search by site name not by url

**Comment by hsamysaab91** [comment]
Hi @albegut , thanks for your response; you were correct :) :)
