### ISSUE TITLE
Can't run react-datatable locally

### ISSUE THREAD

**Issue by brucelane** [pnp/sp-dev-fx-webparts#1852]
### Sample

react-datatable

### Author(s)

@Chandani_SPD

### What happened?

When I run gulp serve I got this:
ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (D:\dev\sharepoint\sp-dev-fx-webparts\samples\react-datatable\node_modules\natives\index.js:143:24)

### Steps to reproduce

1. clone the repo
2. npm i
3. gulp serve

### Expected behavior

run the sample in the browser
![spfxgulp](https://user-images.githubusercontent.com/138158/117210217-ae6f7700-adf7-11eb-9b09-48ab23fca2ae.jpg)

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.12.1

### Node.js version

v14.15.5

### Additional environment details

I did:
npm install -g npm
npm audit fix
Same result

**Comment by hugoabernier** [comment]
@brucelane, the `README.md` points that out (albeit, in a broken shield image, which I'll fix), but the sample is not designed to work on the local workbench, just hosted workbench.

As an FYI, it looks like the SPFx team is planning on removing the local workbench in future versions of SPFx 😊

**Comment by brucelane** [comment]
thank you

**Comment by trueleader** [comment]
@hugoabernier About your "FYI": Is there any further information available? 
The SPO remote workbench requires a running gulp serve task. This task was renamed to "serve-deprecated" ... Running this task works with the Remote Workbench, but the renaming indicates that it should not be used?

**Comment by hugoabernier** [comment]
The only information we have right now is according to the [SPFx 1.12.1 Release Notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.1) 
![image](https://user-images.githubusercontent.com/13972467/123133672-f7b66d00-d41d-11eb-9173-ab11984b2198.png)
