### ISSUE TITLE
React Birthday issue when change tenant url 

### ISSUE THREAD

**Issue by kodalianiruddho** [pnp/sp-dev-fx-webparts#1872]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-birthdays

### Author(s)

@joaojmendes

### Question

Hi @joaojmendes,
I facing some issue when I change the tenant url to site collection url I am not able to get the today birthday only showing next birthday .
like : 
 _results = await this.graphClient.api(`sites/root/lists('${this.birthdayListTitle}')/items?orderby=Fields/Birthday`)
it works fine
![Capture1](https://user-images.githubusercontent.com/9925873/117542845-f4b31900-b037-11eb-8bfd-193eac491859.PNG)

 But issue arrise  when I chnage with site collection id  todays birthaday not populate only next birthday:
_results = await this.graphClient.api(`sites/{site-id}/lists('${this.birthdayListTitle}')/items?orderby=Fields/Birthday`)
![Capture3](https://user-images.githubusercontent.com/9925873/117542995-7efb7d00-b038-11eb-9ea8-59ff590ad54f.PNG)

Am I missing something? please help.

**Comment by Abderahman88** [comment]
Hi @kodalianiruddho,

For me, it works on a different site collection.
A possible problem is the year of the birthday. (calculations are made with the year 2000)

### Works
![image](https://user-images.githubusercontent.com/36161889/117687697-51d5d880-b1b8-11eb-8f8a-d1433d550766.png)
![image](https://user-images.githubusercontent.com/36161889/117688069-bc871400-b1b8-11eb-8a29-d5be1c24c046.png)

### Does not work
![image](https://user-images.githubusercontent.com/36161889/117687793-6e721080-b1b8-11eb-9cb6-e14a2351fffe.png)
![image](https://user-images.githubusercontent.com/36161889/117687991-a6795380-b1b8-11eb-9d18-6ff688226473.png)

**Comment by Abderahman88** [comment]
@kodalianiruddho Has this solved you issue?

If so, @hugoabernier can close this issue.
