### ISSUE TITLE
npm i is not success

### ISSUE THREAD

**Issue by tony-philipose** [pnp/sp-dev-fx-webparts#1890]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-bot-framework

### Author(s)

@hugoabernier

### Question

I tried to install npm packages but not sucess
node version is 14.6.1
python version is 3.9 and also set it in path variable.
![image](https://user-images.githubusercontent.com/30836715/117926864-0ab22980-b317-11eb-8696-d2cfeba4f96f.png)

**Comment by hugoabernier** [comment]
Hey @tony-philipose , try opening a bug instead. 

Also, I'm not the author. You'll probably have a better chance of having your issue resolved if you tag the actual author.
