### ISSUE TITLE
React Rss Reader Not Working Properly

### ISSUE THREAD

**Issue by Peyyi** [pnp/sp-dev-fx-webparts#1894]
### Sample

React Rss Reader

### Author(s)

@ericoverfield

### Question

I am having problem installing the Rss Reader webpart on to a SharePoint Online Modern page after installing the spfx-fantastic-40.sppkg file.  The webpart stays on this holding pattern (spinning wheel) forever, not rendering any feed.
![error](https://user-images.githubusercontent.com/71794322/118551329-6cadcd00-b723-11eb-8045-05cf81fae954.PNG)
Please note that I am new to Github with no development/coding experience.  Thank you for your help!

**Comment by hugoabernier** [comment]
Thank you for your submission, but there isn't enough detail in the issue for us to review &amp; move forward.            The new issue template includes sections for you to fill out.

Please resubmit your issue and complete the provided sections in the new item template so we can move forward on it refer to our wiki for more information: [How to Create Good Issues](https://github.com/pnp/sp-dev-fx-webparts/wiki/How-to-Create-Good-Issues)
