### ISSUE TITLE
React-securitygrid what is the scope at this time 

### ISSUE THREAD

**Issue by christinemzeravica** [pnp/sp-dev-fx-webparts#1901]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-securitygrid

### Author(s)

@hugoabernier

### Question

Hi Hugo, the React-securitygrid looks very helpful. In the description you mention that it doesn't show AD Groups yet. Do you mean that it cannot peek inside Azure AD Groups such as Microsoft 365 Groups used for teams in Microsoft Teams or that those are not displayed at all yet? When do you think that it might be updated related to Groups?

**Comment by hugoabernier** [comment]
@christinemzeravica thanks for opening the issue, but I'm not the original sample creator. @russgove may be able to answer you better?

**Comment by russgove** [comment]
Hi, Thanks for asking (i need to update the docs!).
Originally the app did not look inside of azure groups when testing if a user has permissions. That was fixed recently, so now it shows users as having access if a group the user is in has access.

**Comment by russgove** [comment]
@christinemzeravica let me know if you have any issues with the webpart or see areas for improvement.

**Comment by hugoabernier** [comment]
Hi @christinemzeravica I hope that @russgove's answer helped resolve your issue? 

I'll go ahead and close this issue as answered, but if you need any further help, please don't hesitate to open a new issue.

Thanks @russgove for your help with this one.
