### ISSUE TITLE
Unabe to clone and download the webpart "sp-dev-fx-webparts"

### ISSUE THREAD

**Issue by Mavutanii** [pnp/sp-dev-fx-webparts#1902]
### Sample

PnP / sp-dev-fx-webparts

### Author(s)

@hugoabernier 

### Question

Hi, 

I have been trying to clone the webpart /sp-dev-fx-webparts and i am unable to download it and extract it. Please see the errors im getting below, hoping you will be able to assist me with this issue as i need to install the webpart Modern Script Editor webpart.

Error:

C:\Users\UserName>git clone https://github.com/pnp/sp-dev-fx-webparts.git
Cloning into 'sp-dev-fx-webparts'...
remote: Enumerating objects: 45250, done.
remote: Counting objects: 100% (3785/3785), done.
remote: Compressing objects: 100% (1621/1621), done.
effrror: RPC failed; curl 56 Send failure: Connection was reset
atal: the remote end hung up unexpectedly
atal: early EOF
fatal: index-pack failed

Thanks

**Comment by Mavutanii** [comment]
Thanks, I have managed to move past that stage now, however now im getting the below error, please have a look and advise.

I ran the npm install and get the below error
![NPM Install Error](https://user-images.githubusercontent.com/84741488/119468383-ae9fca00-bd46-11eb-9034-98add0ec9d2e.PNG)


C:\Users\Username\sp-dev-fx-webparts\samples\react-script-editor>npm install
npm WARN deprecated @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Musa Nkuna\AppData\Roaming\npm-cache\_logs\2021-05-25T08_34_31_996Z-debug.log

C:\Users\Username\sp-dev-fx-webparts\samples\react-script-editor>

**Comment by hugoabernier** [comment]
Hi @Mavutanii. We'd love to help you, but in order to do so, we'll need more information from you.

I'll close this issue, but please feel free to create a *new* bug report and take the time to fill all the information we request so that we can help you further.

Thanks for your understanding!
