### ISSUE TITLE
React-content-query-online npm install error

### ISSUE THREAD

**Issue by Yigezu1** [pnp/sp-dev-fx-webparts#1904]
### Sample

React-content-query-online npm install and build error

### Author(s)

@PopWarner @hugoabernier @PaoloPia

### What happened?

When trying to run the NPM Install the following error thrown:-

gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1

gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yigez\\workspace\\sp-dev-fx-webparts\\samples\\react-content-query-online\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\yigez\workspace\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\node-sass
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

### Steps to reproduce

1. clone github repository
2. move to the react-content-query-online sample
3. npm install

### Expected behavior

No error

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.12.1

### Node.js version

v14.16.1

**Comment by hugoabernier** [comment]
Thanks, @Yigezu1 for the issue. I can see from your environment settings that you're trying to run an SPFx 1.11 sample in a Node 14 environment, which is not compatible.

I would suggest that you take a look at the [SPFx compatibility matrix](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility) and change your environment to a version of Node that is compatible with the solution or consider using NVM.

I'll go ahead and close this issue, but if you run into more issues once you have configured your environment, please do not hesitate to open another issue.
