### ISSUE TITLE
ReferenceError: primordials is not defined  at fs.js:45:5     at req_ (C:\Projects\sp-dev-fx-webparts-main\samples\react-bot-framework\node_modules\natives\index.js:143:24)

### ISSUE THREAD

**Issue by Mwape1997** [pnp/sp-dev-fx-webparts#1905]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-bot-framework

### Author(s)

hugoabernier

### What happened?

![image](https://user-images.githubusercontent.com/32986641/119519697-ee33d980-bd79-11eb-96b3-72e63269b02e.png)

### Steps to reproduce

1. npm install --global windows-build-tools 
2. set PYTHON "C:\Users\[ME]\.windows-build-tools\python27\python.ex
e"
3. npm config set msvs_version 2017 --global
4.  npm install
![image](https://user-images.githubusercontent.com/32986641/119519430-b331a600-bd79-11eb-83bc-1e4489073d8a.png)
5. gulp serve
![image](https://user-images.githubusercontent.com/32986641/119519658-e6743500-bd79-11eb-9886-233e3381c627.png)

### Expected behavior

For gulp not to fail upon doing gulp serve or gulp build.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.12.1

### Node.js version

14.16.1

**Comment by hugoabernier** [comment]
Thanks, @Mwape1997 for your issue, however, I'm not the author of the sample. You'll probably have better luck if you tag the *actual* author.

I can see from your environment that you're using Node 14 to run a solution that was built on SPFx 1.10. As per the [compatibility matrix](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility), SPFx 1.10 is not compatible with Node 14. I would recommend that you use a compatible version of Node (or consider using NVM) and see if the issue gets resolved.

I'll go ahead and close the issue, but feel free to open a new issue once you've made those changes if you run into more issues.
