### ISSUE TITLE
Has anyone tried Staff Directory on GCC High?

### ISSUE THREAD

**Issue by jacobchris6** [pnp/sp-dev-fx-webparts#1915]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-staffdirectory

### Author(s)

@arigunawan3023 @tristian2

### Question

The webpart worked great on our sharepoint.com tenant. But I get the following error on our GCC High sharepoint.us tenant. 

      Resource 'presence' does not exist or one of its queried reference-property objects are not present.

I approved the two Microsoft Graph scopes.   In the web part properties, I disabled the "Update Presence Status?" but it didn't help

Do you think any other configs need to be done on GCCH for it to work?

Thanks for any assistance.

**Comment by DakotaWray2** [comment]
@jacobchris6 FWIW I am also receiving the presence endpoint issue working with graph in GCC-High. Looks like it hasn't been implemented yet. Came across your issue while looking into my own. Let me know if you ever resolve it.

**Comment by hugoabernier** [comment]
Marking this issue as "to be reviewed" later, as we can't control the features available in GCC.
