### ISSUE TITLE
react-groups-teams - No data shown when adding webpart to page

### ISSUE THREAD

**Issue by marschallphilipp** [pnp/sp-dev-fx-webparts#1916]
### Sample

react-groups-teams

### Author(s)

@ReactIntern

### Question

Hi there,
I followed these steps: [https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-groups-teams#minimal-path-to-awesome](url)
I guess the next steps require to go into SharePoint Admin Center and approve the permissions in "API Access" ? (This is what I did)
> You will see a message saying that solution has pending permissions which need to be approved
> Approve the permission requests.

When I run the next steps everything is fine and I see my groups / teams.
> Run $ gulp serve --nobrowser
> Open hosted workbench, i.e. https://<tenant>.sharepoint.com/sites/<your site>/_layouts/15/workbench.aspx
> Search and add O365 Groups Manager web part to see it in action

When I add the WebPart to a page though (I tried both adding the app as tenant wide and not tenant wide) I can´t see my groups / teams, no data is shown.

Do you have any idea what could be wrong?

**Comment by hugoabernier** [comment]
@marschallphilipp can you confirm that you don't have any outstanding API requests in the central admin?

**Comment by ReactIntern** [comment]
Hello, in the webApiPermissionRequests section of the package-solution.json file are both of the resources named "Microsoft Graph"? 
That might be your problem if not- I ran into this problem when deploying to different tenants.  
It should look like this:

` "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Team.ReadBasic.All"
      }
    ]`

I hope this helped! 
- Alison

**Comment by marschallphilipp** [comment]
> @marschallphilipp can you confirm that you don't have any outstanding API requests in the central admin?

Yes I can confirm.

![image](https://user-images.githubusercontent.com/6168689/120182166-55d0a580-c20e-11eb-9991-ffdba55113c2.png)

**Comment by marschallphilipp** [comment]
@ReactIntern 

> Hello, in the webApiPermissionRequests section of the package-solution.json file are both of the resources named "Microsoft Graph"?
> That might be your problem if not- I ran into this problem when deploying to different tenants.
> It should look like this:
> 
> ` "webApiPermissionRequests": [ { "resource": "Microsoft Graph", "scope": "Group.Read.All" }, { "resource": "Microsoft Graph", "scope": "Team.ReadBasic.All" } ]`
> 
> I hope this helped!
> 
> * Alison

Unfortunately this seems to bee correct in my package-solution.json file:
![image](https://user-images.githubusercontent.com/6168689/120182400-a2b47c00-c20e-11eb-8cd7-22e408860e2b.png)

**Comment by Abderahman88** [comment]
Can you check `Google Developer Tools` for the error?

**Comment by Abderahman88** [comment]
@marschallphilipp Do you still have issues with this webpart?
