### ISSUE TITLE
react accordion dynamic section Sample not working

### ISSUE THREAD

**Issue by kausarp** [pnp/sp-dev-fx-webparts#1923]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/b139ba199cb57363a88f070dd9814e5af4fc3cbd/samples/react-accordion-dynamic-section

### Author(s)

 @hugoabernier @mikezimm @jerryyasir

### Question

Hello  there - I have downloaded and tried to use React Accordion Dynamic Section Webpart from https://github.com/pnp/sp-dev-fx-webparts/tree/b139ba199cb57363a88f070dd9814e5af4fc3cbd/samples/react-accordion-dynamic-section
Not able to create node module. Getting following errors when running npm install.

`C:\demo\react-accordion-dynamic-section>npm install react-accordion-dynamic-section
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-accordion-dynamic-section - Not found
npm ERR! 404
npm ERR! 404 'react-accordion-dynamic-section@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\MyPC\AppData\Roaming\npm-cache_logs\2021-06-07T21_42_31_401Z-debug.log

**C:\demo\react-accordion-dynamic-section>npm install**

deasync@0.1.14 install C:\demo\react-accordion-dynamic-section\node_modules\deasync
node ./build.js

C:\demo\react-accordion-dynamic-section\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack at PythonFinder. (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack at exithandler (child_process.js:326:5)
gyp ERR! stack at ChildProcess.errorhandler (child_process.js:338:5)
gyp ERR! stack at ChildProcess.emit (events.js:376:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack at onErrorNT (internal/child_process.js:467:16)
gyp ERR! stack at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\demo\react-accordion-dynamic-section\node_modules\deasync
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.14 install: node ./build.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\MyPC\AppData\Roaming\npm-cache_logs\2021-06-07T21_46_49_490Z-debug.log
`

**I am on Windows 10 and using
node version : v14.17.0
npm version: 6.14.13
+-- @microsoft/generator-sharepoint@1.12.1
+-- gulp@4.0.2
`-- yo@4.2.0**

Please guide me to create node module and in using this sample web part.

Thanks & Regards,
Kausar

**Comment by kausarp** [comment]
@jerryyasir @hugoabernier  What a shame! Not happy, need clear answer. What exact version do I need? I checked the matrix and it looks like my environment does resonate with the matrix.

**Windows 10
node version : v14.17.0
npm version: 6.14.13
+-- @microsoft/generator-sharepoint@1.12.1
+-- gulp@4.0.2
`-- yo@4.2.0**

<img width="506" alt="SPFXCompatibilityMatrx" src="https://user-images.githubusercontent.com/82678124/121202375-174c7380-c82a-11eb-95a2-51a606bd635e.png">

Thanks

**Comment by hugoabernier** [comment]
@sthorley I think that you're absolutely right that it would be the best thing to do, but all our samples are contributed by and maintained by, volunteers -- including me.

We review all samples before publishing them, and the code is automatically scanned for vulnerabilities; We apply patches as soon as they are reported. Still, there can be a delay between a vulnerability being discovered and being reported in our repo.

The samples in this repo are absolutely intended to be used as samples only, and it is everyone's responsibility to make sure to apply due diligence and ensure to adhere to their organization's security guidelines --and make the appropriate modifications -- before using them in production.

That being said, we're constantly striving to improve; If you find a vulnerability, please submit a pull request or file a new security vulnerability issue and we'll use the strength of the community to try to resolve it.

If you have the time to update the `package.json` of the samples and test them, please feel free to do so. I hope that you can set the example and that it will encourage others in the community to do the same for other samples.

On a related note, if you `@mention` the author (instead of just writing their names), they'll get notified, which may significantly increase of the odds of them being aware that there is an issue.

I hope to see pull requests from you soon! And thanks again for speaking up on this issue.

**Comment by hugoabernier** [comment]
The Readme file associated with the sample says it is an spfx 1.10 sample, which does not support node 14.You'll need 8.x or 10.x for this one.
