### ISSUE TITLE
What is the purpose of Category column in react-accordion-dynamic-section?

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1928]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-dynamic-section

### Author(s)

@erikjbenke

### Question

What is the purpose of the Category column in this sample?
I see it in the property pane and it says it's required.

But don't see how it's used in the webpart.  I was expecting something like a Pivot or Dropdown box to pick the category.

Note I haven't installed it, just looked at the readme for it.

Thanks!

**Comment by AriGunawan** [comment]
Hi @mikezimm,

The category column is for filtering the items from the data source list.
The second dropdown on the Property Pane is for selecting the **column** for the filter.
The third dropdown is for selecting the **value** of the column.
Please see the below screenshot. I set the webpart to only display items with Category = "IT".

![image](https://user-images.githubusercontent.com/8691985/122671590-a0cc5000-d1f1-11eb-949f-76300ff10cc1.png)
_The left hand side is the data source and the right hand side is the webpart result_

**Comment by hugoabernier** [comment]
Hey @mikezimm I hope that @AriGunawan 's answer helped? I'll go ahead and close this issue as `answered`, but feel free to open a new issue if you have more questions.

**Comment by mikezimm** [comment]
@AriGunawan Thanks for the reply... I was just a little confused thinking it was something the end user would be able to pick.
