### ISSUE TITLE
react-datatable Export To CSV not working

### ISSUE THREAD

**Issue by sivakavuri-umg** [pnp/sp-dev-fx-webparts#1930]
### Sample

react-datatable

### Author(s)

@Chandani_SPD

### What happened?

When click on Export To CSV getting an error saying "**blob:/700e2eb7-4294-4b45-9e4d-d63324c99db2 might be having issues, or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE**"

### Steps to reproduce

1.Configure Any List
2. Select Columns
3. Click on Export To CSV

### Expected behavior

Export Data TO CSV file

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.12.0

### Node.js version

v12.21.0

**Comment by sivakavuri-umg** [comment]
Any update on this?

**Comment by Abderahman88** [comment]
Hi @sivakavuri-umg, I will take a look at it.

@hugoabernier Can you assign to me for now? Thank you.

**Comment by Abderahman88** [comment]
I made a fix for this issue. 

@chandaniprajapati Do you have any issues? If so, I'll make the PR.

![image](https://user-images.githubusercontent.com/36161889/125866942-a89ec4d8-62ba-463f-9ff3-bfdf73330a47.png)

**Comment by hugoabernier** [comment]
@Abderahman88 if you have a fix for it, feel free to post a pull request. Although @chandaniprajapati is the original author of the sample, we welcome contributions from everyone. We achieve more together than alone!

**Comment by Abderahman88** [comment]
@hugoabernier The fix uses a different third-party library for the export of the CSV. I wanted to double check with @chandaniprajapati, if the original library can be fixed/used.
I will submit the PR soon.

**Comment by chandaniprajapati** [comment]
Hi @Abderahman88,

Thanks for reporting an issue. I am able to reproduce it. You can fix it if possible with the current external library.

**Comment by Abderahman88** [comment]
@chandaniprajapati I tried to use the same library, but a different (smaller) library was an easier fix.
@hugoabernier PR is ready 👍
