### ISSUE TITLE
react adaptive card

### ISSUE THREAD

**Issue by andrewpilcher** [pnp/sp-dev-fx-webparts#1934]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-adaptivecards

### Author(s)

@bernier @paulschaeflein

### What happened?

 ~#@❯  gulp serve                                                                                ❮  2m 28s 253ms   
Build target: DEBUG
[10:41:56] Using gulpfile ~\gitFiles\sp-dev-fx-webparts\samples\react-adaptivecards\gulpfile.js
[10:41:56] Task 'serve' is not in your gulpfile
[10:41:56] Please check the documentation for proper gulpfile formatting
[10:41:56] Task 'serve' is not in your gulpfile
[10:41:56] Please check the documentation for proper gulpfile formatting
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1

### Steps to reproduce

1. cd .\gitFiles\sp-dev-fx-webparts\samples\react-adaptivecards\
2. npm install
3. gulp serve

> _npm audit fix was also run_

### Expected behavior

Starting gulp
Starting 'serve'...

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.11.0

### Node.js version

v10.23.0

**Comment by Eli-Schei** [comment]
Tried to recreate this, but I don't get any errors. The serve command starts the local server as expected. 

I'm on spfx version 1.12.1 , and changed to node v10.23.1 before running `npm install` and `gulp serve`.

**Comment by andrewpilcher** [comment]
Ran an update on on gulp  and node, still get error : 
```
[08:23:14] Using gulpfile ~\eGit\sp-dev-fx-webparts\samples\react-adaptivecards\gulpfile.js
[08:23:14] Task 'serve' is not in your gulpfile
```
Did a search in [gulpfile.js](https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-adaptivecards/gulpfile.js) for serve and nothing is present. Did I miss some sort of step somewhere?

**Comment by hugoabernier** [comment]
@andrewpilcher can you try to use **SPFx Doctor** from the [CLI for Microsoft 365](https://pnp.github.io/cli-microsoft365/cmd/spfx/spfx-doctor/) and see what results you get?

Make sure to run it from within the project folder (i.e.: you should have a `package.json` file at the same level as your command prompt).

Let us know what the results are?

**Comment by andrewpilcher** [comment]
@hugoabernier ... odd 
`Error: npm not found`
I am running nvm and a npm --version yields 6.14.10 in the project folder

**Comment by hugoabernier** [comment]
Try using the latest version of the CLI by running `npm i -g @pnp/cli-microsoft365@next` first

**Comment by andrewpilcher** [comment]
Thanks @hugoabernier 
```
× Node v10.23.1 found, v^12.0.0 || ^14.0.0 required
× yo not found
× gulp not found
```
Also weird because they are installed globally.
So I wiped node_modules and swtiched to 14.15.1  `npm install` then `gulp serve` with the following results
```
ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (C:\Users\user\gitFiles\sp-dev-fx-webparts\samples\react-adaptivecards\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\user\gitFiles\sp-dev-fx-webparts\samples\react-adaptivecards\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\user\gitFiles\sp-dev-fx-webparts\samples\react-adaptivecards\node_modules\gulp\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```
and the doctor says
```
CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.12.1
√ Node v14.15.4
√ yo v3.1.1
√ gulp v4.0.2
√ bundled typescript used
```

**Comment by hugoabernier** [comment]
Looks like you're using the wrong version of Node. Please refer to https://aka.ms/spfx-matrix to make sure that you're using a version of Node that is compatible with the solution

**Comment by Eli-Schei** [comment]
The primordial error is typically because you need gulp v4 to make it work with node v14. 
I've had this error when I had the right version of gulp globaly, but not localy. 
Have you tried  `npm update gulp@4.0.0 --save-dev` in your project? 🙂

**Comment by andrewpilcher** [comment]
So the bot is right? though 
√ SharePoint Framework v1.12.1
√ Node v14.15.4
√ yo v3.1.1
√ gulp v4.0.2
√ bundled typescript used

**Comment by andrewpilcher** [comment]
I have tried 12.22.1, 10.24.1, 14.17.1 also. It is not a node version issue

**Comment by andrewpilcher** [comment]
@Eli-Schei I ran `npm update gulp@4.0.0 --save-dev` and still same result. I tried another sample same result. Is it NVM? I can run a react sharepoint helloworld no problem.

**Comment by hugoabernier** [comment]
@andrewpilcher the solution will **only** work with Node 10. Please switch your environment to node 10 and try cloning the repository again.
