### ISSUE TITLE
react-list-search - People and lookup fields not working.

### ISSUE THREAD

**Issue by cor315** [pnp/sp-dev-fx-webparts#1935]
### Sample

react-list-search

### Author(s)

@albegut

### Question

When I try to add a people or lookup field no data shows up.

Text works fine.  Am I doing something wrong?

I'm using SPO and just updated list-search-webpart to version 1.1.0.0 because of this issue.  Obviously that wasn't the fix.

![image](https://user-images.githubusercontent.com/12423774/122499946-ab46d980-cfa6-11eb-81de-2ce1256bacf9.png)

![image](https://user-images.githubusercontent.com/12423774/122499959-b1d55100-cfa6-11eb-82f8-bc6c8f4af929.png)

**Comment by albegut** [comment]
Hi @cor315,
Sorry for the delay answering.

I've test the solution and It´s a bug when you use the list view or caml query functionality at the "Source data" -> "Select source lists" -> "List View Title" or "CAML Query"

![sourceLists](https://user-images.githubusercontent.com/9661096/124575778-f9cff100-de4b-11eb-9f53-fbf68493130d.jpg)

![sourceLists2](https://user-images.githubusercontent.com/9661096/124576632-c93c8700-de4c-11eb-8b3d-90777fb3c9c8.jpg)

Could you confirm that you are using any of this functionalitites? 


Thank you in advance!

**Comment by cor315** [comment]
Ah, yes that seemed to work. Thank you

**Comment by msalemw** [comment]
Hey there! I'm having the same issue where the column remains blank when I select a lookup field. @albegut, could you please provide some guidance on how to fix this? I'm not sure what steps to take based on the message you wrote. Any help you can provide would be greatly appreciated! Many thanks
