### ISSUE TITLE
Unable to build solution

### ISSUE THREAD

**Issue by spjeff** [pnp/sp-dev-fx-webparts#1936]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-content-query-online

### Author(s)

Abderahman88

### What happened?

Want SPPKG file for "react-content-query-online" install to App Catalog.   Error below instead.

[07:04:43] Error - [tsc] src/common/services/ContentQueryService.ts(80,13): error TS2322: Type '{ pageContext: PageContext; webUrl: string; listId: string; items: undefined[]; accessDenied: fal...' is not assignable to type 'IContentQueryTemplateContext'.

### Steps to reproduce

Have local NPM global packages 

+-- @angular/cli@11.2.5
+-- @microsoft/generator-sharepoint@1.12.0
+-- gulp@4.0.2
+-- lite-server@2.6.1
`-- yo@3.1.1

**Steps to Reproduce**
1.  Browse https://github.com/pnp/sp-dev-fx-webpart
2.  Run local cmd "https://github.com/pnp/sp-dev-fx-webparts.git"
3.  Run "npm install"
4.  Run "cd samples\react-content-query-online"
5.  Run "gulp build --ship"

### Expected behavior

Want SPPKG file for "react-content-query-online" install to App Catalog.   Error below instead.

[07:04:43] Error - [tsc] src/common/services/ContentQueryService.ts(80,13): error TS2322: Type '{ pageContext: PageContext; webUrl: string; listId: string; items: undefined[]; accessDenied: fal...' is not assignable to type 'IContentQueryTemplateContext'.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.12.0

### Node.js version

v10.23.0

### Additional environment details

PS C:\code\sp-dev-fx-webparts\samples\react-content-query-online> npm list --g --depth=0
C:\Users\Name\AppData\Roaming\npm
+-- @angular/cli@11.2.5
+-- @microsoft/generator-sharepoint@1.12.0
+-- gulp@4.0.2
+-- lite-server@2.6.1
`-- yo@3.1.1

![image](https://user-images.githubusercontent.com/5648223/122559196-a4e74a80-d004-11eb-9a5b-30e92e08120a.png)

![2021-06-18_07-12-53](https://user-images.githubusercontent.com/5648223/122559214-ab75c200-d004-11eb-82d6-fcd9c2a51e95.jpg)

**Comment by petkir** [comment]
Hi @spjeff ,

as you wrote:
3. Run "npm install"
4. Run "cd samples\react-content-query-online"
5. Run "gulp build --ship"

please  try

3. Run "cd samples\react-content-query-online"
4. Run "npm install"
5. Run "gulp build --ship"

I tried only the build and I had no error
