### ISSUE TITLE
Overlapping issue on year view in react calendar WebPart

### ISSUE THREAD

**Issue by mohammadamer** [pnp/sp-dev-fx-webparts#1937]
### Sample

react-calendar

### Author(s)

@Eli-Schei @Abderahman88 @joaojmendes

### What happened?

Year view has overlapping issue. There is an overlapping between Comments, Footer section and Year view of Calendar WebPart.

### Steps to reproduce

1. Open React Calendar view
2. Click year view
3. Scroll down to see overlapping.

### Expected behavior

Excepted behavior is to have no overlapping between Year view and SharePoint built-in sections like comments and footer sections.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.11.0

### Node.js version

v10.24.0

**Comment by Abderahman88** [comment]
@mohammadamer I will look into it

**Comment by Abderahman88** [comment]
Issue: the height of the container is a bit too small for the Year-view.
I've chosen to add a vertical scrollbar to fix it.
