### ISSUE TITLE
react-rss-reader - out-of-the-box templating doesn't show line after every ten items. 

### ISSUE THREAD

**Issue by ollij** [pnp/sp-dev-fx-webparts#1940]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-rss-reader/

### Author(s)

@hugoabernier

### What happened?

React RSS Reader doesn't have paging option but it does page items to sets of ten:
![image](https://user-images.githubusercontent.com/10028657/122915435-6c2cd580-d364-11eb-932b-96d4fab85cab.png)

Problem is that if we set the RSS Reader web part to show more than ten items, every tenth item is missing horizontal line after the item. 

### Steps to reproduce

1. Install an configure RSS Reader (and proxy service).
2. Set Show number of items to a value of greater than 10.
3. Examine the tenth item, it is missing the horizontal line.

### Expected behavior

Every tenth item should also have the horizontal line.

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

n/a

### Node.js version

n/a

**Comment by hugoabernier** [comment]
Thanks for the issue @ollij ,but I'm not the author of this sample. You'll have much better luck getting the author(s) to help you if you tag the actual authors

**Comment by Abderahman88** [comment]
I will check it out 👍

**Comment by Abderahman88** [comment]
@ollij What feed retrieval service are you using ? (Direct, Feed2Json, ...)

![image](https://user-images.githubusercontent.com/36161889/123100051-0bb89980-d433-11eb-99be-ecdeec4d071a.png)


If you are using Rss2Json, this is a normal. The `count`-parameter only works with a valid api key. (Default = 10)

![image](https://user-images.githubusercontent.com/36161889/123099991-fe031400-d432-11eb-8112-61d5ed9e72ee.png)

**Comment by ollij** [comment]
Sorry for the delayed response, and thank you so much for your help.

@Abderahman88 - we are using our own RSS Feed proxy service - basically a node.js Azure function that makes the query to RSS service and returns the XML without modifications. So the feed actually is more than 10 items and we are not restricting that in any way.

**Comment by Abderahman88** [comment]
@ollij  Tested a feed and I can show more than 10 items.

Are you getting any specific error (stuck loading screen? CORS error?)

![image](https://user-images.githubusercontent.com/36161889/124519716-63b7ae80-ddea-11eb-9038-bdb6110148bb.png)

![image](https://user-images.githubusercontent.com/36161889/124519669-44b91c80-ddea-11eb-979d-7ac7b618ebd4.png)

**Comment by Abderahman88** [comment]
@hugoabernier Can you set the label back to `Needs: Author feedback`
