### ISSUE TITLE
React-content-query. Special characters in field names not working

### ISSUE THREAD

**Issue by cjevil** [pnp/sp-dev-fx-webparts#1941]
### Sample

https://github.com/spplante/react-content-query/

### Author(s)

@PopWarner@hugoabernier @PaoloPia

### What happened?

HI,
I have sharepoint lists with columns that have a special character in the name. E.G. XT_CT_TYPEINFO

Unfortunately I only get empty values for all columns that have a _ in the name.
So as a workaround I currently use a calculated column on the source list e.g. XTCTINFO with the formula (= XT_CT_INFO) and use the calculated column in the template to display the values. This works.

Is there a way to display special characters columns as .textvalue or .rawvalue without a calculated column as workaround?
I also tried it with replacing _ by "_x005f"

sample.
<span class='ms-DetailsRow-cell'><strong>XT_CT_TYPEINFO: </strong>{{XT_CT_TYPEINFO.textValue}}</span>
                    <span class='ms-DetailsRow-cell'><strong>XT_CT_SITE: </strong>{{XT_x005f_x005f_x005f_CT_x005f_x005f_x005f_SITE.textValue}}</span>
                    <span class='ms-DetailsRow-cell'><strong>XT_CT_IS_PUBLIC: </strong>{{XT_CT_IS_PUBLIC.textValue}}</span>

### Steps to reproduce

1. Edit template
2.
3.

### Expected behavior

Special chars like _ should work 

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.1.0.0

### Node.js version

?

**Comment by Abderahman88** [comment]
Hi @cjevil, I'm looking into it 👀

**Comment by Abderahman88** [comment]
@cjevil Use the latest version of [react-content-query-online](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-content-query-online)

In the template use the `rawValue` of your field.

![image](https://user-images.githubusercontent.com/36161889/123133272-db332880-d44f-11eb-9d03-108c4b746ee8.png)


![image](https://user-images.githubusercontent.com/36161889/123133176-c48cd180-d44f-11eb-8f91-e231864112a0.png)

**Comment by hugoabernier** [comment]
@cjevil did @Abderahman88's answer help you?

I'll make this issue as answered, but feel free to open a new issue if you need further assistance with this.

**Comment by cjevil** [comment]
creat it works. thank you very much
