### ISSUE TITLE
React Save Attachment install on outlook dekstop

### ISSUE THREAD

**Issue by theogumilang** [pnp/sp-dev-fx-webparts#1945]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-save-attachments

### Author(s)

@Aaakash Bhardwaj

### Question

If I host my application to the azure app service, it should we worked for the desktop app right?

**Comment by Abderahman88** [comment]
@theogumilang Check this [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-addins-create)

![image](https://user-images.githubusercontent.com/36161889/125989593-e7f7fe90-10d3-42fa-928e-e8f12de5d51c.png)
