### ISSUE TITLE
Cancel button shows when using Display Form Type.

### ISSUE THREAD

**Issue by cor315** [pnp/sp-dev-fx-webparts#1956]
### Sample

react-list-form

### Author(s)

@DanyWyss

### What happened?

When using Display Form Type, the cancel button shows.  Seems unnecessary when the user can't edit the form and only used to display information.  I'm not sure if this is a bug or feature request.

![image](https://user-images.githubusercontent.com/12423774/124870873-3436ac80-df78-11eb-9eb6-bee9560406b2.png)

![image](https://user-images.githubusercontent.com/12423774/124870973-53353e80-df78-11eb-8eb1-db37d34833e0.png)

### Steps to reproduce

npm install
gulp serve

### Expected behavior

No Cancel button in Display form type.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

**Comment by hugoabernier** [comment]
Thanks @cor315 for the suggestion. We accept pull requests, if you feel like making that change.
