### ISSUE TITLE
react-calendar - "Edit Recurrence Series" button appears to read only members/users of sharepoint online site

### ISSUE THREAD

**Issue by mariaarcena** [pnp/sp-dev-fx-webparts#1960]
### Sample

react-calendar

### Author(s)

@Abderahman88, @Eli-Schei, @hugoabernier, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### What happened?

1. Created a site on sharepoint online
2. Downloaded and utilized react-calendar to use its functionality within the site
3. Made add an event to the react-calendar instance of the site
4. Gave permission to read-only user/member to look at calendar
5. Log on as read-only user/member
6. Go on the calendar and open the event created in step 2
7. The "Edit Recurrence Series" button appears 🤔 

Step 7 is not expected. We expected that the edit buttons within the event of an instance of a react-calendar would be shown or hidden based on the permissions/security of the user. But again, in our case it seems that the react-calendar does not reflect that. Below is a screenshot! 📸 If there is a quick workaround on this, that would be great! But of course it would also be nice for it to be fixed and resolved nicely 🥰 If any of the authors need more information, please let me know and I will be happy to help! ✨ 

![EditRecurrenceSeriesButton](https://user-images.githubusercontent.com/17426994/125538498-197948aa-bade-40a7-82bb-5654b5d93474.png)

### Steps to reproduce

1. Create a site on sharepoint online
2. Download and utilize react-calendar to use its functionality within the site
3. Make add an event to the react-calendar instance of the site
4. Give permission to read-only user/member to look at calendar
5. Log on as read-only user/member
6. Go the the calendar and open the event created in step 2
7. See the "Edit Recurrence Series" button 😔 

### Expected behavior

I expect you to see the "Edit Recurrence Series" button 🤨

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.15.4

### Additional environment details

Operating system: Windows 10

**Comment by mohammadamer** [comment]
Thanks @mariaarcena for reporting the issue. I'll will check it out.

**Comment by mohammadamer** [comment]
Hello @mariaarcena 

I have checked the issue and it seems that actually users who have readonly access can see and open Edit Recurrence button.
I have done a fix to the issue which is disabling the Edit Recurrence button when user has readonly access in this commit [540c3a8](https://github.com/pnp/sp-dev-fx-webparts/commit/540c3a8ded9419a295b4345f06d1bdd2d5137721).

Also I added a [Pull Request](https://github.com/pnp/sp-dev-fx-webparts/pull/1961) with this commit which will be approved soon.

**Comment by mariaarcena** [comment]
OMG thank you so much @mohammadamer and @hugoabernier !!! We'll test it out later and try it! I'll say our extra thanks later! 🥰 💖

**Comment by mariaarcena** [comment]
@mohammadamer @hugoabernier my team mate is asking "**what version of node.js and gulp they used to build the most recent web part?**" because he is having trouble with his build environment when it comes to rebuilding 🤔💭 If more information is needed or I need to put in another issue, let me know! 🥰

**Comment by hugoabernier** [comment]
@mariaarcena the `README.md` associate to every sample should provide you that information.

In the case of the React Calendar (https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-calendar), it shows that you should use Node.js LTS 8.x or 6.x.

![image](https://user-images.githubusercontent.com/13972467/125714215-02be58ba-a25b-44fd-9ad4-b6103e715856.png)

I hope this helps?

**Comment by mariaarcena** [comment]
@hugoabernier Yes okay, thank you for this! My team mate is going to look this over and make sure he has the same versions! We'll keep you updated on the status when we know! Thanks again Hugo! ✨

**Comment by hugoabernier** [comment]
My pleasure @mariaarcena ! Please do not hesitate to open a new ticket with more information if you continue to run into issues.

**Comment by mariaarcena** [comment]
Hello @hugoabernier! Sorry for not giving a quick update right away but everything is good now! Thanks to you both for everything! 🥰 ✨
