### ISSUE TITLE
JS-Employee-Spotlight Build Error: TypeScript

### ISSUE THREAD

**Issue by AHunt-BHP** [pnp/sp-dev-fx-webparts#1964]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/js-employee-spotlight

### Author(s)

SPS (Strategic Products and Services)

### What happened?

Have tried building this sample using Node JS LTS ver 14.x, 10.x, and 8.x, but all fail on gulp actions because they are looking for missing TypeScript files in the directory. So many TS errors display in log, only partial capture available with copy/paste. Results provided below from PowerShell:

[JS-Employee-Spotlight_ErrorLog.txt](https://github.com/pnp/sp-dev-fx-webparts/files/6826503/JS-Employee-Spotlight_ErrorLog.txt)

### Steps to reproduce

1. Clone repo
2. NPM install
3. Gulp serve

### Expected behavior

gulp serve should send test solution to web browser for workbench testing in real time. gulp bundle --ship should prepare solution for package-solution to be loaded to SharePoint app catalog for testing.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

### Additional environment details

Have tried this using Node JS LTS versions 8, 10, and 14 with the same results. Because guidance given in example documentation is to run "tsd install" (deprecated) after "npm install", the resulting error is related to missing file index.d.ts

**Comment by hugoabernier** [comment]
The sample says that it is using SPFx 1.8, but the package.json file seems to indicate that it is an earlier version of SPFX, which -- according to the matrix -- would only work with Node 6. You should try that and let us know how it went.

**Comment by AHunt-BHP** [comment]
Installed Node 6.17.1, which displays different error on tsd install command, but same errors on gulp serve or gulp bundle --ship attempt. See tsd install command error output below:
[JS-Employee-Spotlight_ErrorLog2.txt](https://github.com/pnp/sp-dev-fx-webparts/files/6831191/JS-Employee-Spotlight_ErrorLog2.txt)

**Comment by AHunt-BHP** [comment]
Got weary of waiting on the author, since my organization wants this web part functional in the next two weeks. Ran o365 spfx upgrade command from pnp library and got the below report (Markdown doc - .md). Went through step-by-step to upgrade, and I'm close, but am getting the error in the .txt file below upon gulp build command. More than happy to release this for public consumption, provided I can get it working properly in SPFx 1.12.1. Inputs welcomed and appreciated.

[upgrade-report.md](https://github.com/pnp/sp-dev-fx-webparts/files/6851703/upgrade-report.md)
[WebPartUpgradeErrorCode.txt](https://github.com/pnp/sp-dev-fx-webparts/files/6851704/WebPartUpgradeErrorCode.txt)
