### ISSUE TITLE
react-remote-event-receiver-manager - How to register RER by Rest API or CSOM outside webpart?

### ISSUE THREAD

**Issue by mostafaabdellah** [pnp/sp-dev-fx-webparts#1965]
### Sample

react-remote-event-receiver-manager

### Author(s)

@Tanddant

### Question

Hi Dan,
How to register RER using Rest API or CSOM outside the web part, I tried from postman using restapi and AAD token, RER added and return receiverId however, it never fire!

Thanks

**Comment by Tanddant** [comment]
Hi @mostafaabdellah, 

I'm not sure the question belongs here, however:
The Issue you're seeing is the exact reason I ended up creating the webpart, remote event receivers added without user authentication behaves strange - there needs to be a authenticated user, using legacy auth.

Using PnPPowerShell and -UseWebLogin seems to work.

However the proper way to do it via CSOM is connecting via an app registration that you've created and granted Sites full control via the appinv.aspx page

https://{tenant}-admin.sharepoint.com/_layouts/15/appinv.aspx

App Id = Your app registrations ClientId

Apps permissions:
```XML
<AppPermissionRequests AllowAppOnlyPolicy="true">
    <AppPermissionRequest Scope="http://sharepoint/content/tenant" 
     Right="FullControl" />
 </AppPermissionRequests>`
