### ISSUE TITLE
SPFX ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by hubghs** [pnp/sp-dev-fx-webparts#1971]
### Sample

spfx

### Author(s)

bug

### What happened?

I have updated machine with the latest version of Node.js LTS v14 with the below configurations. The latest recommended version is LTS v14.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

node -v = v14.17.3, npm -v = 7.19.1

gulp -v
CLI version: 2.3.0
Local version: 3.9.1

I have updated the gulp Local version to 4.0.2.

Now getting invalid glob function because of {allowEmpty: true}

I am looking for gulpfile.js updated file

### Steps to reproduce

https://docs.microsoft.com/en-us/answers/storage/attachments/114656-primordials.png
https://docs.microsoft.com/en-us/answers/storage/attachments/115053-gulp-build.png
https://docs.microsoft.com/en-us/answers/storage/attachments/115052-gulp-serve.png

### Expected behavior

Gulp serve and Gulp Build working

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

Node.js v14.15.0+ (Fermium)

**Comment by PathToSharePoint** [comment]
@hubghs I see that your environment is SP 2019. I suspect that you missed the important note in the docs:

> If you're building solutions for SharePoint Server 2019 or SharePoint Server 2016, refer to the additional documentation referenced in the See also section below.
