### ISSUE TITLE
Unable to configure the Script-Editor-WebPart - Configuration is blank

### ISSUE THREAD

**Issue by arturstrzalkowski** [pnp/sp-dev-fx-webparts#1972]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor

### Author(s)

@MikaelSvenson

### What happened?

![script editor wp](https://user-images.githubusercontent.com/77382746/126464784-0d4a5fb9-c972-4ebc-b7fb-8a7b0274559e.PNG)

After adding the Script-Editor-WebPart to a page, the configuration panel on the right side is not available.

### Steps to reproduce

1. Adding .sppkg to App-Cartalog after build
2. Adding app to site collection
3. enable scripts on site collection
4. adding web part to page
5. trying to configure the web part

### Expected behavior

Able to configure the web part

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

**Comment by Abderahman88** [comment]
Hi @arturstrzalkowski,

I think what you now see, is not a blank configuration from script-editor-webpart. But a new section added by SPO.

![image](https://user-images.githubusercontent.com/36161889/126639759-f4e05b2c-57e6-481f-a2ae-0cb1560031a2.png)

**Comment by Abderahman88** [comment]
I believe this is recently introduced.

**Comment by Abderahman88** [comment]
If you delete the section in `edit` mode, you have the normal behaviour.

![image](https://user-images.githubusercontent.com/36161889/126640198-afddac4d-8ca4-4d2b-afc9-b8868c1e6de9.png)
