### ISSUE TITLE
React-list-search only show placeholder

### ISSUE THREAD

**Issue by ikaroamorim** [pnp/sp-dev-fx-webparts#1976]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-list-search

### Author(s)

@albertogperez

### What happened?

When I added the webpart to a site it keeps the Configure webpart properties page (placeholder) and no matter what configurations I do it wont change

#Evidences installing
![image](https://user-images.githubusercontent.com/44349801/126897861-a9d88c11-79e5-4a5f-886e-021238eaedf7.png)
![image](https://user-images.githubusercontent.com/44349801/126897867-be32ec00-9c41-4c3a-9a1b-bb92e036e0a4.png)

#Configuration evidences
![image](https://user-images.githubusercontent.com/44349801/126897872-99486d36-b173-4d21-9db9-4345ceb8862b.png)
![image](https://user-images.githubusercontent.com/44349801/126897874-f02441d0-8eef-4612-973d-3de606a8b2a9.png)
![image](https://user-images.githubusercontent.com/44349801/126897878-43992484-584a-4fbf-bc2c-957900daae16.png)
![image](https://user-images.githubusercontent.com/44349801/126897887-09f26beb-7f6a-41bb-bef3-4c0b09ecbf04.png)
![image](https://user-images.githubusercontent.com/44349801/126897894-d13e68c3-999c-4170-a796-b1dccfd16d72.png)
![image](https://user-images.githubusercontent.com/44349801/126897897-7ca5a679-31f7-41f2-bbde-ec3b918c8898.png)
![image](https://user-images.githubusercontent.com/44349801/126897900-fb3664ed-273b-4484-9802-3b2a65bc9939.png)
![image](https://user-images.githubusercontent.com/44349801/126897904-781f58bc-f0ff-4d39-bd16-ef5c55223fe2.png)

The both list and library have items:
![image](https://user-images.githubusercontent.com/44349801/126897908-32f86064-c9c6-4b5f-9c45-bbdb92978040.png)

The warnings are shown in console
![image](https://user-images.githubusercontent.com/44349801/126897935-bba3e14e-98bc-4e5b-bc60-7c64bb494160.png)

### Steps to reproduce

1 - I Downloaded de solution .sppkg from github repository
2 - Added to App Catalog of my Tenant
2.1 - Checked the "Make this solution avilable to all sites..." box
2.2 - Clicked "Deploy"
2.3 - The deploy showed no errors
3. - Accepted all Graph permissions in Sharepoint Central Admin
4. Inserted the webpart in a page
5. Configured the webpart to show

### Expected behavior

I expected the webpart to show some results as a I saw in demo on the youtube channel.
(I'm not native speaker, don't want to look unpolite. If something I say sounds aggressive let me know to be able to improve my communication)

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

10.23.0

### Additional environment details

The tenant is not new, it has more than a year.
User is app catalog admin, site collection admin, and tenant Admin

**Comment by Abderahman88** [comment]
Hi @ikaroamorim,

Don't worry, you don't sound aggressive 😄 

I will test it out.

@hugoabernier Please assign to me ✋

**Comment by Abderahman88** [comment]
@ikaroamorim I can confirm your problem. I have the same result.

The problem lies in this function:

![image](https://user-images.githubusercontent.com/36161889/127012450-e00634fd-f83e-41f4-aee3-ebccaa78e0ec.png)

I will work on it. Stay tuned 📺

**Comment by ikaroamorim** [comment]
Oh great @Abderahman88, thank you for atention.

I will sure stay tuned

**Comment by Abderahman88** [comment]
Everything works fine. I forgot one step in the configuration, that caused the webpart not to display anything. Propably this is the same in your case. Following steps are taken to get it up and running.

As an example, I created a simple list `QuoteOfTheDay` with just a `Title` field.

![listsearchpre](https://user-images.githubusercontent.com/36161889/127059063-159d72f9-dd09-40ba-bb6c-37f106ecb96a.PNG)


### Steps taken

1. Add site(s) to get data and click on `Select source lists`
![image](https://user-images.githubusercontent.com/36161889/127057140-2e92134e-2b00-43e1-b602-ab230210ece1.png)

2. Add the list and set the correct `List View Title`. This is name of the view of your list.
![listsearch1](https://user-images.githubusercontent.com/36161889/127059493-6135054a-0877-4e14-8101-19d1095078b8.png)

3. Configure fields by clicking on `Configure fields`
![listsearch3](https://user-images.githubusercontent.com/36161889/127060384-df8cf3a6-7294-48d9-b883-8c251d25cb21.png)

4. Configure column properties. Custom column names can be provided. For example `My quote` as a header gives more meaning than just the generic word `Title`
![listsearch4](https://user-images.githubusercontent.com/36161889/127060575-8771508f-80ad-4d45-aeee-bd39749c461f.PNG)

5. Map the fields by clicking on `Select fields`
![listsearch5](https://user-images.githubusercontent.com/36161889/127061272-1d2613d8-1778-4b12-9078-0229379aedbe.png)

6. The original fields of the list can be mapped with the custom fields of the webpart.
![listsearch6](https://user-images.githubusercontent.com/36161889/127061501-2cab8302-f8fc-4c5f-b649-25444e816279.png)

### Result

![listsearch7](https://user-images.githubusercontent.com/36161889/127061757-7cf9cee6-8809-435f-a0d6-d849bee40d16.PNG)

Let me know if you have any issues.

**Comment by Abderahman88** [comment]
@hugoabernier Please change status to `Needs author feedback`

**Comment by ikaroamorim** [comment]
The webpart worked properly my error were related for leaving the field "View" in blank on step 2.
Thank you for helping
![image](https://user-images.githubusercontent.com/44349801/127246260-bb10ec7e-07dc-4895-9aff-947ed2c226ab.png)

**Comment by Abderahman88** [comment]
You're welcome. 👍
