### ISSUE TITLE
react-add-js-css-ref  Could not find Element Manifest: sharepoint/assets/

### ISSUE THREAD

**Issue by thomastkk** [pnp/sp-dev-fx-webparts#1977]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-add-js-css-ref

### Author(s)

@Siddharth Vaghasia

### What happened?

`congif/package-solution.json `
`          "elementManifests": [
            "elements.xml",
            "clientsideinstance.xml"
          ]
`

gulp package-solution --ship

[10:51:32] Reading resources...
[10:51:32] Done!
[10:51:32]
[10:51:32] Reading Sharepoint Assets & Creating XML...
[10:51:32] Error - 'package-solution' sub task errored after 58 ms
 Could not find Element Manifest: sharepoint/assets/elements.xml
[10:51:32] 'package-solution' errored after 69 ms
[10:51:32]
[10:51:32] ==================[ Finished ]==================
Error - 'package-solution' sub task errored after 58 ms
 Could not find Element Manifest: sharepoint/assets/elements.xml
[10:51:33] Project react-add-js-css-ref version:0.0.1
[10:51:33] Build tools version:3.9.26
[10:51:33] Node version:v10.24.1
[10:51:33] Total duration:2.78 s
[10:51:33] Task errors:1
The build failed because a task wrote output to stderr.
Exiting with exit code: 1

### Steps to reproduce

1.gulp clean
2.gulp build
3.gulp bundle --ship
4.gulp package-solution --ship

### Expected behavior

package build success

### Target SharePoint environment

SharePoint Online

### Developer environment

Linux

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

**Comment by siddharth-vaghasia** [comment]
@hugoabernier  - please assign this to me..I will work on this.

**Comment by SamMPita** [comment]
Hi! I have same problem.
Some elements aren't there.
I tried everything...
please help

**Comment by siddharth-vaghasia** [comment]
Hello... Simplest fix here would be to upload extract attached zip file to the root of the project folder

[sharepoint.zip](https://github.com/pnp/sp-dev-fx-webparts/files/7022687/sharepoint.zip)

Reference screenshot

![image](https://user-images.githubusercontent.com/9557557/130259299-07322318-e768-442a-8423-5351d3895cbd.png)

elements.xml file should be at below path
![image](https://user-images.githubusercontent.com/9557557/130259365-062fd328-004f-448e-bb05-aff490d5f117.png)

**Comment by siddharth-vaghasia** [comment]
@hugoabernier  - Can you please advise is there any way we can check in the SharePoint folder also to repo... I think I have also faced a similar issue in some of the web parts and fix it by putting some files as mentioned in the path.... or is there any way we can do settings that will generate this file when we do gulp build ?

**Comment by hugoabernier** [comment]
@siddharth-vaghasia I added the files to the repo. Let me know if it resolves the issue.

It wasn't listed in your `.gitignore`, so I'm not sure why it would be excluded from GitHub.

**Comment by siddharth-vaghasia** [comment]
@thomastkk  - are you able to fix this issue by adding SharePoint folder to solution ?

**Comment by hugoabernier** [comment]
Hey, @thomastkk I hope that you were able to solve this issue using @siddharth-vaghasia's recommendations?

I'll go ahead and close this issue as solved, but if you're still experiencing problems, please feel free to open a new issue with new information so we can help you further.

Thanks, @siddharth-vaghasia for your help

**Comment by Somesh2035** [comment]
Hay @siddharth-vaghasia Thank you for your solution. I am able to fix the issue by adding SharePoint folder.
