### ISSUE TITLE
react-news-banner - 

### ISSUE THREAD

**Issue by jzlsantiago** [pnp/sp-dev-fx-webparts#1989]
### Sample

react-news-banner

### Author(s)

@joaojmendes

### Question

Hi Joao,

Hope you are doing well. 
I deploy this webpart but i see the "select site" show nothing. could you please give me some tips or assitance to load this section?

Thanks in advance.

![Captura11](https://user-images.githubusercontent.com/5981069/127959290-db6b7bf7-85d2-4644-a95c-eb8a44d65d6d.JPG)

**Comment by Abderahman88** [comment]
Hi @jzlsantiago 

You need to type at least 3 letters in the searchbox before you see suggestions.

![image](https://user-images.githubusercontent.com/36161889/129590343-db21d8a2-7cd9-4986-8976-922030e3eb27.png)

**Comment by Abderahman88** [comment]
@hugoabernier Can you add `Need author feedback` ?

**Comment by hugoabernier** [comment]
Hey @jzlsantiago did @Abderahman88 's suggestion solve your issue? 

I'm going to close this issue as answered. If you're still experiencing any problems, feel free to open a new issue and provide more information so we can help you further.
