### ISSUE TITLE
react-list-search - 

### ISSUE THREAD

**Issue by AbuAmmar072001** [pnp/sp-dev-fx-webparts#2012]
### Sample

react-list-search

### Author(s)

@albegut

### What happened?

Hi,
After a lot of work, finally, the solution was built successfully and it's working fine locally.
I deployed the sppkg to App Catalog and when I embed the web part to the web page I got an error.
![image](https://user-images.githubusercontent.com/19372527/129297672-776151f3-1b21-494b-8ad5-af54fd48af23.png)

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS

[SPLoaderError.loadComponentError]:
Failed to load component "292daaa0-2-98f8-afa6ac92" (ListSearchWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/***********************/ClientSideAssets/8f088-9c15-0a26/react-list-search-propertycontrolstrings_en-us_37aab40.js' for resource 'PropertyControlStrings' in component '2-2479c92' (ListSearchWebPart). There was an error requesting the file.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/

Any recommendation?

### Steps to reproduce

1. It's working fine locally.
2.
3.

### Expected behavior

Recommandations

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

**Comment by hugoabernier** [comment]
@AbuAmmar072001 please provide more details on the steps you took to deploy the solution?

**Comment by Abderahman88** [comment]
@AbuAmmar072001 I can't re-produce the error.

![image](https://user-images.githubusercontent.com/36161889/129494800-c55ed102-d649-46b6-adeb-6987d0debb96.png)

Here is the sppkg-file I've used. 
[list-search-webpart.zip](https://github.com/pnp/sp-dev-fx-webparts/files/6988989/list-search-webpart.zip)

Like @hugoabernier said, a bit more details with be helpful.
