### ISSUE TITLE
Error to clone and download the webpart "sp-dev-fx-webparts"

### ISSUE THREAD

**Issue by Elza01** [pnp/sp-dev-fx-webparts#2018]
### Sample

https://github.com/pnp/sp-dev-fx-webparts

### Author(s)

@elza01

### Question

Hi I try clone this solution but i get error in last cloning like below 

`Cloning into 'D:\PROJECT AMMAN infimedia\Project 2\SPFX\Resource from Google\sp-dev-fx-webparts\sp-dev-fx-webparts'...
remote: Enumerating objects: 46848, done.        
remote: Counting objects: 100% (583/583), done.        
remote: Compressing objects: 100% (422/422), done.        
remote: Total 46848 (delta 300), reused 343 (delta 140), pack-reused 46265        
Receiving objects: 100% (46848/46848), 1.46 GiB | 946.00 KiB/s, done.
Resolving deltas: 100% (25652/25652), done.
error: unable to create file samples/angular-aad-webapi/api/packages/Microsoft.AspNet.WebApi.HelpPage.5.2.3/Content/Areas/HelpPage/Views/Help/DisplayTemplates/CollectionModelDescription.cshtml.pp: Filename too long
error: unable to create file samples/angular-aad-webapi/api/packages/Microsoft.AspNet.WebApi.HelpPage.5.2.3/Content/Areas/HelpPage/Views/Help/DisplayTemplates/ComplexTypeModelDescription.cshtml.pp: Filename too long
error: unable to create file samples/angular-aad-webapi/api/packages/Microsoft.AspNet.WebApi.HelpPage.5.2.3/Content/Areas/HelpPage/Views/Help/DisplayTemplates/DictionaryModelDescription.cshtml.pp: Filename too long
error: unable to create file samples/angular-aad-webapi/api/packages/Microsoft.AspNet.WebApi.HelpPage.5.2.3/Content/Areas/HelpPage/Views/Help/DisplayTemplates/EnumTypeModelDescription.cshtml.pp: Filename too long` ....

and in folder like below
![image](https://user-images.githubusercontent.com/88201547/129502198-6634625b-5972-48b6-b3df-bbdcbd8edf52.png)

if from download .zip cannot extract file.

please help

**Comment by Abderahman88** [comment]
Hi @Elza01,

Your file paths are too long.

_In editions of Windows before Windows 10 version 1607, the maximum length for a path is MAX_PATH, which is defined as 260 characters_

Instead of cloning in this directory:
` D:\PROJECT AMMAN infimedia\Project 2\SPFX\Resource from Google\sp-dev-fx-webparts\sp-dev-fx-webparts\...`

Do something like:
` D:\sp-dev-fx-webparts\...`

**Comment by Abderahman88** [comment]
@hugoabernier Can you assign to me and add `Needs author feedback` ?

**Comment by Elza01** [comment]
> @hugoabernier Can you assign to me and add `Needs author feedback` ?



> Hi @Elza01,
> 
> Your file paths are too long.
> 
> _In editions of Windows before Windows 10 version 1607, the maximum length for a path is MAX_PATH, which is defined as 260 characters_
> 
> Instead of cloning in this directory:
> ` D:\PROJECT AMMAN infimedia\Project 2\SPFX\Resource from Google\sp-dev-fx-webparts\sp-dev-fx-webparts\...`
> 
> Do something like:
> ` D:\sp-dev-fx-webparts\...`

**Comment by Elza01** [comment]
> > @hugoabernier Can you assign to me and add `Needs author feedback` ?
> 
> > Hi @Elza01,
> > Your file paths are too long.
> > _In editions of Windows before Windows 10 version 1607, the maximum length for a path is MAX_PATH, which is defined as 260 characters_
> > Instead of cloning in this directory:
> > ` D:\PROJECT AMMAN infimedia\Project 2\SPFX\Resource from Google\sp-dev-fx-webparts\sp-dev-fx-webparts\...`
> > Do something like:
> > ` D:\sp-dev-fx-webparts\...`

Hi

**Comment by Elza01** [comment]
Hi @Abderahman88 ,

thank for you solution that is works perfectly, I move folder another path.

**Comment by Abderahman88** [comment]
You're welcome @Elza01 

If you have any questions, let us know 😄

**Comment by Abderahman88** [comment]
You may also close this issue. Thnx
