### ISSUE TITLE
Regarding the Sample: react-script-editor-onprem

### ISSUE THREAD

**Issue by wei-s-h** [pnp/sp-dev-fx-webparts#2021]
### Sample

react-script-editor-onprem

### Author(s)

hugoabernier

### Question

Hi there,

I use the sample: react-script-editor-onprem for testing on my SharePoint 2019 On Premise environment. I have installed and feature was enabled successfully in my communication site as shown below:

![image](https://user-images.githubusercontent.com/63778559/129942958-32fe311e-8134-4dac-bce6-4c7538b65bae.png)
![image](https://user-images.githubusercontent.com/63778559/129942997-bd2472e5-1461-4277-881e-ba8d1343ce5f.png)
![image](https://user-images.githubusercontent.com/63778559/129943038-d90bd77d-4b35-4df6-b922-961d72f7214c.png)

But I cannot find it in my Toolbox, when I want to add it in my site page.

![image](https://user-images.githubusercontent.com/63778559/129943175-5e840b02-28d9-4aea-856b-eaf385f75655.png)

But I cannot add Webpart from Toolbox, because I cannot find it inside. Does anyone have any ideas on it ?? Thanks

**Comment by hugoabernier** [comment]
Sorry @wei-s-h  I'm not the author of this sample. You'll probably have better luck getting help if you get tag actual author of the sample.

**Comment by spoman007** [comment]
@wei-s-h I faced this issue in Sharepoint 2019. The webpart appears in the team site but does not show for communication site template.

I found out that `ScriptEditorWebPart.manifest.json` contains one setting
`"requiresCustomScript": true`

If you flip this to false, the webpart will start appearing for all 2019 templates.

**Comment by hugoabernier** [comment]
@spoman007 I'm not the author of the sample, so I can't validate whether it is a long-term fix or not. Better to @ mention the author and seek their recommendation.

I'm pretty sure that `requiresCustomScript` indicates that the web part only runs on sites where custom scripting is enabled, and you probably need custom scripting to be enabled for the script to actually execute when the page is loaded.

Can you verify that the web part not only displays on the page, but executes the script as well?

And absolutely, I look forward to your PR!

**Comment by spoman007** [comment]
@wobba Any thoughts on this ?
https://github.com/pnp/sp-dev-fx-webparts/issues/2021#issuecomment-914997201

I think enabling script execution is required only in SharePoint Online. I was able to execute the script in 2019 even with `requiresCustomScript": false`

**Comment by wobba** [comment]
It's clearly mentioned in the web parts readme. https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-script-editor-onprem/README.md#deploy-to-non-script-sites--modern-team-sites

**Comment by hugoabernier** [comment]
Hey @wei-s-h , did you ever resolve this issue using @spoman007 and @wobba 's guidance?

I'll go ahead and mark this issue as closed, but feel free to open a new issue with more details if you're still experiencing problems and we'll be happy to help!

**Comment by wei-s-h** [comment]
> Hey @wei-s-h , did you ever resolve this issue using @spoman007 and @wobba 's guidance?
> 
> I'll go ahead and mark this issue as closed, but feel free to open a new issue with more details if you're still experiencing problems and we'll be happy to help!

hi @hugoabernier, sorry for reply late. we close the issue first. these days, I haven't tested this due to some issues. in the feature, If I still have the questions, I will post this here. Thanks in advance.
