### ISSUE TITLE
Where can I store some setting for all Site Collection on tenant level. 

### ISSUE THREAD

**Issue by enti333** [pnp/sp-dev-fx-webparts#2026]
### Sample

none

### Author(s)

enti

### Question

Hello. I am preparing some SPFX application that can be used on all site collections. You just install the application from app catalog on Site Collection and you can use it. The main problem is that I want to store some settings but globally. Not for specific site collection but for the whole tenant. That means that I need to store some settings on the tenant level. 
I will configure these settings only once and all sites can use this setting. Is possible to store somewhere the settings for all site collections and I will be able to get these settings via SPFX (PNP, GraphApi). Thank you.

**Comment by hugoabernier** [comment]
Hey @enti333, this list is intended to be used for questions about samples in this repository.

However, you may want to look at the tenant-wide storage entity to store small bits of configuration.

[This code](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-smart-profile-photo-editor/src/services/StorageEntityService) shows an example of an implementation of a callable Storage Entity helper to get you started.
