### ISSUE TITLE
react-calendar Custom column issue

### ISSUE THREAD

**Issue by riddhichaplot** [pnp/sp-dev-fx-webparts#2027]
### Sample

react-calendar

### Author(s)

@NanddeepNachan

### What happened?

The add/edit form of react-calendar does not show the custom columns created on that calendar/events list in SPO

### Steps to reproduce

1. Add the react calendar on SPO
2. The list which is added to the calendar, add a custom Yes/No type of column to it.
3. Now open the calendar view webpart and click to add/edit the event, you won't see the custom column on it

### Expected behavior

I expected that the custom column would show up as it does on default forms.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v8.17.0

### Additional environment details

NA

**Comment by Abderahman88** [comment]
Hi @riddhichaplot

Custom fields are not automatically shown in the current webpart.
