### ISSUE TITLE
react-calendar - 

### ISSUE THREAD

**Issue by subwizzll** [pnp/sp-dev-fx-webparts#2029]
### Sample

react-calendar

### Author(s)

@Abderahman88, @Eli-Schei, @hugoabernier, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### Question

Hi,

I really love this webpart, I think it will be a great addition to our SharePoint/Teams sites, but I have noticed that when creating a new event, there is no way to omit/change the form fields in the panel. 

Is there currently a way to do this, am I missing something? If not what part of the code can I change to edit the field names and add or remove ones like category, location, attendees, etc...

Thanks!

**Comment by Abderahman88** [comment]
Hi @subwizzll,

To remove/add form fields on the panel, you need to edit the `render`-function in `src\controls\Event\event.tsx`

For example, you can remove the `category` field by removing/commenting out the right div.

![image](https://user-images.githubusercontent.com/36161889/131402889-8e67c921-9894-472c-bb63-d128296c6701.png)

![ev2](https://user-images.githubusercontent.com/36161889/131403499-0f117db7-a02d-4f59-93c5-3ecc4be2bc8b.PNG)

To change the labels, you need to adjust the localization files. (`src/webparts/calendar/loc/..`)

![image](https://user-images.githubusercontent.com/36161889/131403944-58be1ae3-3aef-47dc-906d-31ad7f0d7bd2.png)


![image](https://user-images.githubusercontent.com/36161889/131404144-e778b0d0-158c-4952-8c72-b033d008caa1.png)

![image](https://user-images.githubusercontent.com/36161889/131404887-cb38d6fd-6dcf-41f2-89c9-8b91f3ad3c3f.png)

![image](https://user-images.githubusercontent.com/36161889/131404805-74b4a8e4-3570-4ba1-b03c-68871f31e593.png)

If you have any questions, just ask. I'm happy to help out. 👍 

@hugoabernier Can you assign to me please 😄

**Comment by subwizzll** [comment]
@Abderahman88 thanks for the swift response, it seems I overlooked that en-us.js file! :sweat_smile:

Also, is there a way to link these fields to custom columns in the Events List?

**Comment by Abderahman88** [comment]
@subwizzll You can do anything you want, but this needs some changes in the code.

Do you want to add custom fields to the form or map the existing fields to other columns in the Events list?

If you need an example, I can help you with this.

**Comment by subwizzll** [comment]
@Abderahman88 I am interest in implementing similar functionality to what is found in `../../samples/react-list-form/ListForm.tsx` I'm just not sure where to begin, I'm am new to SPFx and the react/JS/TS stack, I am more comfortable in C#

**Comment by Abderahman88** [comment]
@subwizzll No problem. This sample will not auto-generate the fields like `react-list-form`, so unfortunately the custom fields need to be added manually in the code. But no worries, I'll guide you through it.

Do you have a lot of custom fields in your list? And of what type are they (text, boolean, choice, ...) ?

**Comment by subwizzll** [comment]
@Abderahman88 Could this type of functionality be implemented using similar code/interfaces found in `react-list-form`? If so I am happy to dive into a project like this.

Thank you for your help!

**Comment by Abderahman88** [comment]
@subwizzll I think it would be possible, but at the moment the current implementation is based on the standard fields of an event. Adding the custom fields manually (in code) would be the easier route. Dynamic rendering of custom fields (as in `react-list-form`) could be a great addition to the webpart, but could has its disadvantages/bottlenecks.

example: What if the the calendar has 30 custom fields, do you want to render them all on the form?

**Comment by subwizzll** [comment]
@Abderahman88 `react-list-form` gives you the ability to remove unwanted fields.

I will explore this in the future, currently my project involving these webparts has been put on hold, so I will close this issue as my initial problem has been addressed already.

Thanks again for your help!
