### ISSUE TITLE
Errors when attempting to debug sample webparts

### ISSUE THREAD

**Issue by subwizzll** [pnp/sp-dev-fx-webparts#2030]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-calendar

### Author(s)

@Abderahman88, @Eli-Schei, @hugoabernier, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### Question

I've been attempting to launch debugging sessions on both Local and Hosted configurations, see `.vscode\launch.json` below:

```{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Local workbench",
      "type": "chrome",
      "request": "launch",
      "url": "https://localhost:4321/temp/workbench.html",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///../../../src/*": "${webRoot}/src/*",
        "webpack:///../../../../src/*": "${webRoot}/src/*",
        "webpack:///../../../../../src/*": "${webRoot}/src/*"
      },
      "runtimeArgs": [
        "--remote-debugging-port=9222"
      ]
    },
    {
      "name": "Hosted workbench",
      "type": "chrome",
      "request": "launch",
      "url": "https://MY_TENANT.sharepoint.com/sites/Support/_layouts/15/workbench.aspx",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///../../../src/*": "${webRoot}/src/*",
        "webpack:///../../../../src/*": "${webRoot}/src/*",
        "webpack:///../../../../../src/*": "${webRoot}/src/*"
      },
      "runtimeArgs": [
        "--remote-debugging-port=9222"
      ]
    }
  ]
}
```
I have tried deleting the `C:\Users\ME\.gcb-serve-data` directory and rerunning `gulp trust-dev-cert` which seemed to stop the 

> Your web part will not appear in the toolbox. Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running.

workbench notification from appearing, however I am still left with these errors in the debug console output after launching a debug session with either configuration:

```
Could not read source map for https://localhost:4321/temp/manifests.js: Unexpected 404 response from https://localhost:4321/temp/manifestsFile.js.map: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /temp/manifestsFile.js.map</pre>
</body>
</html>

Could not read source map for https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js: Unexpected 404 response from https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-extension-base_en-us.js.map: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-extension-base_en-us.js.map</pre>
</body>
</html>

Could not read source map for https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js: Unexpected 404 response from https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js.map: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js.map</pre>
</body>
</html>
```

Thanks in advance!

**Comment by Abderahman88** [comment]
@subwizzll Do you still need help with this one?

**Comment by subwizzll** [comment]
Yes it would be helpful going forward.

**Comment by Abderahman88** [comment]
The way I do it, is with the following method (source: https://www.eliostruyf.com/how-to-debug-your-sharepoint-framework-web-part/):

![image](https://user-images.githubusercontent.com/36161889/135771027-5d99eca8-8a01-4ab2-9ea0-6661c04328ec.png)

**Comment by Abderahman88** [comment]
1) Put a `debugger` statement in your code
2) Run `gulp serve`
3) Append the following to the URL `?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js`
4) Open Chrome -> Developer tools

![image](https://user-images.githubusercontent.com/36161889/135771467-7f691557-3450-42ff-abe1-3c7559648bb1.png)


If everything went right, the code will stop at the debugger statement.

![image](https://user-images.githubusercontent.com/36161889/135771268-f6473962-bbcf-4861-a125-f5e3cc84e8b1.png)

**Comment by Abderahman88** [comment]
@hugoabernier Can you assign to me?
