### ISSUE TITLE
React - Advances page properies language issue

### ISSUE THREAD

**Issue by HamEv** [pnp/sp-dev-fx-webparts#2034]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-advanced-page-properties

### Author(s)

@Mike Homol

### What happened?

Webpart cannot be used in a german environment, because Site Pages library could not be loaded, when following code is executed:
sp.web.lists.getByTitle("Site Pages")
In german the page library Name ist "Websiteseiten" and therefore it's not working. Why isn't there a constant or any other configuration setting (best case in app within site) for the library name?

Or why is the code not executed via the URL?

Thanks,
Evelyn

### Steps to reproduce

1. Install sppkg file in app solution store
2. add solution to site
3. add advance page property webpart to page

### Expected behavior

Using the webpart in a german environment.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [X] Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.17.3

**Comment by Abderahman88** [comment]
Hi @HamEv,

This needs to be fixed. I'll take a look at it.

@hugoabernier Can you assign to me please?

**Comment by Abderahman88** [comment]
PR is made. 🚋

**Comment by HamEv** [comment]
@Abderahman88 Today I was checking the webpart once again, downloaded the latest version, deployed and installed. Unfortunatly the error still occurs. It's not working on a german page (Just the Title property is shown in webpart property panel). In the code the document library is still loaded by sp.web.lists.getByTitle("Site Pages")

Should the webpart work on a german site?

**Comment by Abderahman88** [comment]
@HamEv 

Are you sure you're using the latest code (v1.0.2.0)?

Because in the latest version  `sp.web.lists.getByTitle("Site Pages")` is replaced by `sp.web.lists.ensureSitePagesLibrary();`
This was needed to support sites in different languages. 

To answer your question, the lastest version needs to work on a german site.

**Comment by HamEv** [comment]
That's strange, I downloaded the main master zip file yesterday and the code is still wong on my pc. On GitHub everything looks good and the new function is used. I try to download the zip file once again.

**Comment by Abderahman88** [comment]
Yes, you need the main branch 👍
