### ISSUE TITLE
react-organisation-chart -error 

### ISSUE THREAD

**Issue by mujeebp24** [pnp/sp-dev-fx-webparts#2041]
### Sample

react-organisation-chart

### Author(s)

@joaojmendes

### Question

Hi,
I cloned this repository.
Executed- npm install
Executed - gulp serve (This gives following error)
I am working on SharePoint 2019.

**********Error log is given **************
[12:36:24] Error - Unknown
 Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Unexpected token {
Referenced from: C:\Apps\sp-dev\samples\react-organization-chart\.eslintrc.json
  Request: [::1] '/workbench'
  Request: '/temp/workbench.html'
  Request: '/temp/manifests.js'
  Request: '/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js'
  Request: '/node_modules/@microsoft/sp-webpart-workbench/lib/api/workbenchInit.js'
[12:36:24] ==================[ Finished ]==================
Error - Unknown
 Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Unexpected token {
Referenced from: C:/Apps/sp-dev/samples/react-organization-chart/.eslintrc.json
[12:36:25] Project react-organization-chart version: 0.0.1
[12:36:25] Build tools version: 3.2.7
[12:36:25] Node version: v8.11.4
[12:36:25] Total duration: 3.71 s
[12:36:25] Task errors: 2
[12:36:25] Error - 'undefined' errored after
 "orchestration aborted"

**Comment by joaojmendes** [comment]
Please use node version 10.xxx

From: mujeebp24 ***@***.***>
Date: Tuesday, 21 September 2021 at 10:42
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: [pnp/sp-dev-fx-webparts] react-organisation-chart -error (#2041)
Sample

react-organisation-chart

Author(s)

@joaojmendes<https://github.com/joaojmendes>

Question

Hi,
I cloned this repository.
Executed- npm install
Executed - gulp serve (This gives following error)
I am working on SharePoint 2019.

**********Error log is given **************
[12:36:24] Error - Unknown
Failed to load plugin ***@***.***<https://github.com/typescript-eslint>' declared in '.eslintrc.json': Unexpected token {
Referenced from: C:\Apps\sp-dev\samples\react-organization-chart.eslintrc.json
Request: [::1] '/workbench'
Request: '/temp/workbench.html'
Request: '/temp/manifests.js'
Request: ***@***.***/sp-loader/dist/sp-loader-assembly_en-us.js'
Request: ***@***.***/sp-webpart-workbench/lib/api/workbenchInit.js'
[12:36:24] ==================[ Finished ]==================
Error - Unknown
Failed to load plugin ***@***.***<https://github.com/typescript-eslint>' declared in '.eslintrc.json': Unexpected token {
Referenced from: C:/Apps/sp-dev/samples/react-organization-chart/.eslintrc.json
[12:36:25] Project react-organization-chart version: 0.0.1
[12:36:25] Build tools version: 3.2.7
[12:36:25] Node version: v8.11.4
[12:36:25] Total duration: 3.71 s
[12:36:25] Task errors: 2
[12:36:25] Error - 'undefined' errored after
"orchestration aborted"
