### ISSUE TITLE
react-list-search - 

### ISSUE THREAD

**Issue by OUnterweger** [pnp/sp-dev-fx-webparts#2048]
### Sample

react-list-search

### Author(s)

@albegut

### Question

A question.
For the "On click Properties" I want to select "Redirect to url". What then has to be entered in the "Item ID query param". I want to redirect to the display form of the list.
/DispForm.aspx?ID=
![image](https://user-images.githubusercontent.com/32736964/134324562-a734f26e-74a9-4e91-b13e-d5655fbd6260.png)

**Comment by albegut** [comment]
Hi @OUnterweger ,

Try the next steps:

1. At the "Configure redirect urls" button
![image](https://user-images.githubusercontent.com/9661096/134494365-50f051ef-0010-4612-91e6-546393aca760.png)
1.1. Insert for each list, the url to redirect. In this case something like this:
![image](https://user-images.githubusercontent.com/9661096/134495310-bb6ad138-eeae-4b8b-8312-c89d14957068.png)

2. At the "Item ID query param" input, insert the value "ID". (SharePoint get that query param to know the item to show)
![image](https://user-images.githubusercontent.com/9661096/134494845-c962fb40-0e27-45b8-94e7-9db48d2a1ddc.png)
