### ISSUE TITLE
react-carousel - Dropdown does not respond when click

### ISSUE THREAD

**Issue by keedman4** [pnp/sp-dev-fx-webparts#2051]
### Sample

react-carousel

### Author(s)

@joaojmendes @rahulsuryawanshi @DonKirkham @Harshagracy @giuleon

### What happened?

The Library property dropdown does not respond when clicked, How can one sort this out

### Steps to reproduce

1. I had uploaded the webpart to the app catalog
2. I had created a picture library folder with an image uploaded to it
3. I had added the webpart to the site
4. I had enabled some azure permissions
4. I had selected a site from the property pane
5. I had tried to select the document library

### Expected behavior

The Picture library drop down should come with options to select one 

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.13.0

### Additional environment details

Isn't a picture library created the same way a document library is? Or is a picture library distinct, because that is what i created to upload the picture to.. Could that be the issue??
![Screenshot (326)](https://user-images.githubusercontent.com/37272357/134525216-b0837902-2fad-4823-9dd8-e662a4f9c535.png)

**Comment by fthorild** [comment]
Hi 👋 

I took a quick look at the code and it checks for libraries of type 109 which is the classic PictureLibrary.

Append the following to your site URL **/_layouts/15/addanapp.aspx**  to get to the classic add an app/list thing.

**Comment by roberto-ajolfi** [comment]
Hi all, is there any reason why the PictureLibrary is not available on my tenant? Even going to the classic _Add an App_ view (/_layouts/15/addanapp.aspx) I cannot add it. 

Do you have any quick fix for the code to point to something different from the PictureLibrary i.e. a Docuemnt Library, a folder in the SiteAsset library ... ?
