### ISSUE TITLE
react-list-search - getData throw an exception (display sp\u00e9cifi\u00e9 is wrong)

### ISSUE THREAD

**Issue by thomas-rooty** [pnp/sp-dev-fx-webparts#2054]
### Sample

react-list-search

### Author(s)

@albegut

### What happened?

I successfully imported the .sppkg (I even tried to build one by myself using gulp bundle and gulp package-solution) but when I try to display any data into the webpart is throws me this error :

![](https://i.imgur.com/nbTG3XB.png)

**Text :** 
`getData throw an exception. Error Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"fr-FR","value":"L'affichage sp\u00e9cifi\u00e9 est incorrect."}}}`

**In english :** 
`getData throw an exception. Error Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"fr-FR","value":"The display sp\u00e9cifi\u00e9 is wrong."}}}`

### Steps to reproduce

1. Set source data to a Site
2. Select a List with documents in it 
3. Set whatever List Fields to retrieve

### Expected behavior

I expected to see the filenames listed, instead, I got the thrown error

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

### Additional environment details

Also tested on Brave

**Comment by OlivierHogue** [comment]
Hello, I have the same error. I assume that you found a solution since you closed this, could you please tell me what it is ?
Thanks
