### ISSUE TITLE
React-accordion: Add feature for sort items

### ISSUE THREAD

**Issue by aliiamar** [pnp/sp-dev-fx-webparts#2056]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion

### Author(s)

@AbhishekGarg

### Suggestion

Please add a feature to allow user to sort the list items either by ID, Modified date, etc.

This would really help when user add new items in the list with specific ordering since the web part is mainly used for FAQ

### Are you willing to help?

Yes

**Comment by fthorild** [comment]
Do you mind if I build in some sorting as you suggest and make a PR or did you want to build it @aliiamar? 

@AbhishekGarg - any objections/thoughts?

I was thinking to have options for Id, modified as you suggest but also add a custom sort field option if that makes sense?

**Comment by AbhishekGarg** [comment]
Please go ahead. Always good to have support from the community 😊

**Comment by aliiamar** [comment]
I tried it out and it works great so far! I was able to define a column to perform the sorting on. However seems it can only sort by ascending order, but nonetheless thank you so much @fthorild you're awesome!
