### ISSUE TITLE
Accordion Webpart Managed Metadata Pull

### ISSUE THREAD

**Issue by Goonie78** [pnp/sp-dev-fx-webparts#2058]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-dynamic-section

### Author(s)

@ejbenke @mikezimm @jyasir @AriGunawan

### Question

With this webpart I've been using it for different areas across many SharePoint sites. One thing that I can't figure out is instead of using single and multiline list items, but using Metadata fields instead. I've tried a few methods but I've hit a wall, anyone try to do this with metadata?
![two](https://user-images.githubusercontent.com/37123994/135177170-86039f61-831f-413a-8896-5df54d37da42.png)
![one](https://user-images.githubusercontent.com/37123994/135177172-48dc540a-060a-47d3-a404-83f833c541fe.png)
![three](https://user-images.githubusercontent.com/37123994/135177173-f4c06042-0f23-43b9-ad07-1463e395e739.png)

**Comment by hugoabernier** [comment]
Hey @Goonie78, did you have any luck solving this issue with @AriGunawan's recommended solution?

I'll go ahead and close this issue as answered. If you're still experiencing problems, please feel free to open a new issue.

**Comment by Goonie78** [comment]
Yeah there still are some issues here... unfortunately @hugoabernier ... I need some time to document some of the fun things in dealing with the item.label pulls...
