### ISSUE TITLE
react-tiles-v2 - suggestion

### ISSUE THREAD

**Issue by jacobchris6** [pnp/sp-dev-fx-webparts#2061]
### Sample

react-tiles-v2

### Author(s)

@omarelanis

### Suggestion

Hello,
Very useful webpart and good improvement over the original version. I have a request to be able to change the order of the tiles. And also have the option to set a static width of the tiles.
Thanks so much

### Are you willing to help?

No

**Comment by fthorild** [comment]
Hi! Good ideas! 

I just added sorting to another sample 😁 so I figured, why not fix this one as well (including the static width) 

@omarelanis or anyone else, please add any additional thoughts or comments, otherwise expect a PR with a fix in a few days

**Comment by omarelanis** [comment]
@fthorild thank you for taking a look!

**Comment by jacobchris6** [comment]
The update is working great for me @fthorild. Thank you so much!
