### ISSUE TITLE
Fixed colours and sizes for react-tiles-v2

### ISSUE THREAD

**Issue by CrackerboxOnline** [pnp/sp-dev-fx-webparts#2068]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-tiles-v2

### Author(s)

@omarelanis

### Suggestion

The v2 react tile web part is an excellent update to Hugo's already famous tile web part.

When using these and Hugo's tiles I keep getting asked by users to allow each tile to be a different colour but, importantly, they have all had a showstopper requirement to limit these colours to the organisations brand colours.  I'm thinking this could be managed using a term set or a list in the root site.

I'm thinking that the colours could be stored in a term set to make changes easier.  If the term set/list is missing then a set of generic colours could be stored in a strings file.

Similar to the tile colours, I'm getting feedback that users want to select from a set of predetermined sizes e.g. 1x1, 2x1, 3x1, 2x2 etc.  Naturally they also want to have different sizes of tile within the same grid and the tiles just nicely render (of course they do).  I'm not sure how easy that is in a responsive world.

I have created a solution based on Hugo's v1 that allows the user to pick a different colour for each tile based on colour options specified in a strings file.  This works but any change requires rebuilding for each installation or colour change.  I've tried to use a term set but keep running out of time and skill to make it work and honestly gave up when v2 was released with the icon picker because I'd planned to do it as well and knew I'd never get around to it.

### Are you willing to help?

Yes

**Comment by fthorild** [comment]
@CrackerboxOnline - Just wanted to highlight - I am currently working on an update on this webpart #2061 - sort order and static width is included and I will create a PR any day now. 

If you want I could take a look at the individual tile color (I was in that case thinking to do this via the wp properties though) and possibly the individual size as well (also property driven). Any thoughts on props vs having the settings on the outside?

And finally - agreed, great webpart this one!

**Comment by CrackerboxOnline** [comment]
> @CrackerboxOnline - Just wanted to highlight - I am currently working on an update on this webpart #2061 - sort order and static width is included and I will create a PR any day now.
> 
> If you want I could take a look at the individual tile color (I was in that case thinking to do this via the wp properties though) and possibly the individual size as well (also property driven). Any thoughts on props vs having the settings on the outside?
> 
> And finally - agreed, great webpart this one!

@fthorild The colour and size for each tile should be stored in the WP properties for each tile but the available colours needs to be limited so that the tenant admin can control what colours end users are able to select.  E.g to conform to organisational branding requirements.  Hence why I was thinking storing the colour options in a term set or list in the root or specific site.  I just had not got around to properly working out how to do that bit.

**Comment by CrackerboxOnline** [comment]
I could not disagree more.

This enhancement request has been raised with me by senior management of a number of my clients small and large.  In most cases allowing an end user to choose any colour for a tile or be limited to the theme colours is a showstopper.  These organisations have spent a significant amount on their branding and are effectively not able to enforce it.

These web parts are simply not installed by your average business user. They are installed by a geek who can at least follow some simple instructions to create a colour list/term set or run a prepared PowerShell script that does it for them.

Cheers,
Dave Gerrard
m: 0417 296 560
e: ***@***.***
________________________________
