### ISSUE TITLE
react-file-upload - Fatal error at npm install

### ISSUE THREAD

**Issue by thomas-rooty** [pnp/sp-dev-fx-webparts#2072]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-file-upload

### Author(s)

hugoabernier

### What happened?

I'm getting an error when running npm install, it looks like maybe node is trying to install node-sass@4.5.3 which I saw was problematic in another topic.
Don't know how to fix that though.

### Steps to reproduce

1. Clone the folder
2. Run `npm install`

### Expected behavior

It should run normally without any error :)

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

### Additional environment details

Typescript is v4.4.3

**Comment by Abderahman88** [comment]
You can use [CLI for Microsoft](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade/) to do the upgrade, if you're up for a challenge 😄

**Comment by thomas-rooty** [comment]
Yup that's what I've done this morning ! 

Also you can just downgrade your node.js version to use the NODE_MODULE 57 as it was indicated in the fatal error while building the project.

Thanks :)
