### ISSUE TITLE
React-List-Form: Date Picker Issue

### ISSUE THREAD

**Issue by kilicantplay** [pnp/sp-dev-fx-webparts#2076]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-list-form

### Author(s)

@dany Wyss, @Harshagracy, @sharepointknight, @Abderahman Moujahid, @Kman1131, @Fredrik Thorild, @fthorild

### What happened?

There was a known issue with the React-List-Form date picker which prevented users from adding a value to a date field in a form. The issue was raised in the following ticket.

- [React list form: Date picker no longer works #1451](https://github.com/pnp/sp-dev-fx-webparts/issues/1451)
- [React-List-Form: Date Picker issue has returned #1891](https://github.com/pnp/sp-dev-fx-webparts/issues/1891)

When a user attempted to enter a date in a date picker field the following error was returned on the page:

- "Error: Minified React error Initial release #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

Error appears only when Locale setting has the date format dd/mm/yyyy, for example "English (United Kingdom)" works when Locale is set to "English (United States)"

### Steps to reproduce

1. Create a SharePoint list with a Date field (Date Only)
2. Add the [React-List-Form web part 1.0.10 ](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-list-form) to a page
3. Attempt to set date
4. If Locale is set to English US this will work | If Locale is set to English UK it will fail unless the date is 1/1, 2/2, 3/3 etc
5. Switch between Locales to confirm

### Expected behavior

A user should be able to pick a date from the date picker which returns a valid date value in whatever Locale format has been set for the Site Collection

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

14.3.0

**Comment by Abderahman88** [comment]
No problem @kilicantplay. Let me know if it works 😄
