### ISSUE TITLE
Can't bundle react timeline

### ISSUE THREAD

**Issue by TonyKnibb-MakaraHealth** [pnp/sp-dev-fx-webparts#2087]
### Sample

react-timeline

### Author(s)

@NanddeepNachan

### What happened?

s\GitHub\websites - dot_net\sp-dev-fx-webparts\samples\react-timeline>gulp bundle --ship
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\TonyKnibb\Documents\GitHub\websites - dot_net\sp-dev-fx-webparts\samples\react-timeline\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\TonyKnibb\Documents\GitHub\websites - dot_net\sp-dev-fx-webparts\samples\react-timeline\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\TonyKnibb\Documents\GitHub\websites - dot_net\sp-dev-fx-webparts\samples\react-timeline\node_modules\gulp\node_modules\graceful-fs\fs.js:1:37)

### Steps to reproduce

1. npm i
2. gulp bundle --ship

### Expected behavior

npm i
gulp bundle --ship
gulp package-solution --ship
The package can be found at \react-timeline\sharepoint\solution\react-timeline.sppkg

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v12.14.1

### Additional environment details

Win10 Pro

**Comment by Abderahman88** [comment]
Hi @TonyKnibb-MakaraHealth,

`react-timeline` is build with SharePoint Framework version 1.10. This version is only compatible with Node v8/v10.

Check this [article](https://tahoeninjas.blog/2019/12/30/spfx-compatibility-matrix/) written by @hugoabernier 

If you want to use multiple Node versions on your machine, look at [nvm](https://github.com/nvm-sh/nvm)
