### ISSUE TITLE
Could not view calendars from other calendars it shows blank events on calendar page

### ISSUE THREAD

**Issue by erkindunya** [pnp/sp-dev-fx-webparts#2104]
### Sample

react-aggregated-calendar

### Author(s)

Dhaval Shah

### What happened?

It does not show calendar event, it shows below errors on Console.

1. Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 2
on activitymonitor.js: on line 15, 137, 228,

2.
content:1 GET https://Company.sharepoint.com/_api/v2.1/sites/Company.sharepoint.com,e6ae5b1d-6795-403c-8844-027b1efe5182,d3bcbd2e-3382-429a-9136-40d4cef188a2/lists/43d857cf-d359-4d42-a355-5468106517d4/items/0a07821d-4862-4ab2-858c-73018d5a1763/driveItem/thumbnails/0/c400x99999/content?preferNoRedirect=true&prefer=extendCacheMaxAge&clientType=modernWebPart 404

{error: {code: "itemNotFound", message: "Item not found"}}
error: {code: "itemNotFound", message: "Item not found"}
code: "itemNotFound"
message: "Item not found"

### Steps to reproduce

1.Add webpart on page
2. configure a SharePoint calendar
3. Refresh page and it will only show full calendar
![image](https://user-images.githubusercontent.com/4255047/139700164-fd9dd244-a471-44b5-a5ec-4db6e3ce337e.png)

### Expected behavior

in the past it shows calendar events but now nothing on calendar.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.0

**Comment by Abderahman88** [comment]
Hi @erkindunya, 

This project is build in an older version of SharePoint Framework (v1.4.1) which only supports Node v8 and under.
The best option is to upgrade this project.
