### ISSUE TITLE
chatbot directline React 

### ISSUE THREAD

**Issue by nahlaGit** [pnp/sp-dev-fx-webparts#2107]
### Sample description

This bug stops my whole project. Need at least working work around to use directline in sp site and to authenticate,
 at least how can I handle verification code?
i use this [direcline sample]( https://github.com/withum-digital/directline-bot-extension-blog)  to deply my bot in my sharpoint site but 
i get this error "Taking longer than usual to connect." when i use  the directline enhance feature
![image](https://user-images.githubusercontent.com/57720132/133598555-8874fb57-f044-4383-b172-772098c7f12e.png)

![image](https://user-images.githubusercontent.com/57720132/133598174-cf8a4915-bc4e-46b6-812c-c5d046077952.png)

![image](https://user-images.githubusercontent.com/57720132/133597920-940c1341-71e9-468b-8f69-017de5e3bc8d.png)

### Are you willing to help?

Yes

**Comment by hugoabernier** [comment]
Sorry, sample requests are intended to ask for help building new samples for the community. If you need help with an existing sample, please open a Question issue.

Please note that these samples are *not* intended to be used in production and are not supported. Of course, you're welcome to use as much of the sample as you wish in your production environment, but without any implied support or warranty from the PnP team.
