### ISSUE TITLE
issue react Bot directline 

### ISSUE THREAD

**Issue by nahlaGit** [pnp/sp-dev-fx-webparts#2108]
### Sample

https://github.com/withum-digital/directline-bot-extension-blog

### Author(s)

Phillip Demro

### Sample description

This bug stops my whole project. Need at least working work around to use directline in sp site and to authenticate,
 at least how can I handle verification code?
i use this [direcline sample]( https://github.com/withum-digital/directline-bot-extension-blog)  to deply my bot in my sharpoint site but 
i get this error "Taking longer than usual to connect." when i use  the directline enhance feature
![image](https://user-images.githubusercontent.com/57720132/133598555-8874fb57-f044-4383-b172-772098c7f12e.png)

![image](https://user-images.githubusercontent.com/57720132/133598174-cf8a4915-bc4e-46b6-812c-c5d046077952.png)

![image](https://user-images.githubusercontent.com/57720132/133597920-940c1341-71e9-468b-8f69-017de5e3bc8d.png)

**Comment by hugoabernier** [comment]
If sorry, this issue list is intended for issues related to samples in this repository. You may want to try opening an issue in the repo where you found this sample? 

In the *New issue* page, there are also some links to other community resources you may want to try for additional help.

Good luck!
