### ISSUE TITLE
react-graph-app-secret-expiration - 

### ISSUE THREAD

**Issue by JonoSuave** [pnp/sp-dev-fx-webparts#2111]
### Sample

react-graph-app-secret-expiration

### Author(s)

@a1mery

### Question

How do I use this solution in my tenant without having to run gulp serve --nobrowser?

**Comment by a1mery** [comment]
You can run the following: 

- `gulp bundle --ship`
- `gulp package-solution --ship`

And then deploy the package to your app catalog.

If you you want more information you can follow this great documentation: [Prepare web part assets to deploy](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn#prepare-web-part-assets-to-deploy)
