### ISSUE TITLE
npm install missing dependencis?

### ISSUE THREAD

**Issue by Draaxdard** [pnp/sp-dev-fx-webparts#2112]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-adaptivecards

### Author(s)

@hugoabernier

### What happened?

Hello, i'm very sorry if this is a noob question. However i'm trying to follow your instructions to test the react-adaptivecards webpart.

So I have followed the instructions here to setup a dev envorionment:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

I made a git copy navigated to the reactadaptivecards folder and ran:
terminal: npm install

After that I get loads of errors of dependencies not installed please see:
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/common@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/logging@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/odata@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/sp@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/logging@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/common@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/odata@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/sp@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN adaptivecards-fabric@1.1.2 requires a peer of @fluentui/react@^7.121.2 but none is installed. You must install peer dependencies yourself.
npm WARN adaptivecards-fabric@1.1.2 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN adaptivecards-fabric@1.1.2 requires a peer of react-dom@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.

I have tried to run npm install packagename@version however it does not seem to work for all packages, also im not sure if im doing it right.

### Steps to reproduce

1.git copy project
2.npm install

### Expected behavior

I expect all dependencies to install correctly so i can run gulp serve without errors of missing packages.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.13.0

**Comment by hugoabernier** [comment]
Hey @Draaxdard can you run [spfx doctor](https://pnp.github.io/cli-microsoft365/cmd/spfx/spfx-doctor/) from within the solution folder to diagnose incompatibility issues with your environment and reply with the results?

**Comment by Draaxdard** [comment]
> Hey @Draaxdard can you run [spfx doctor](https://pnp.github.io/cli-microsoft365/cmd/spfx/spfx-doctor/) from within the solution folder to diagnose incompatibility issues with your environment and reply with the results?

Hi @hugoabernier !
Much appreciated for your reply, I ran the spfx doctor and afterwards a npm install to get you the full picture of the problem:

`C:\Users\draax\Documents\spfx>m365 spfx doctor
" "
"CLI for Microsoft 365 SharePoint Framework doctor"
"Verifying configuration of your system for working with the SharePoint Framework"
" "
"\u001b[32m√\u001b[39m SharePoint Framework v1.11.0"
"\u001b[32m√\u001b[39m Node v10.13.0"
"\u001b[32m√\u001b[39m yo v3.1.1"
"\u001b[32m√\u001b[39m gulp v3.0.0"
"\u001b[32m√\u001b[39m bundled typescript used"

C:\Users\draax\Documents\spfx>npm install
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/common@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/logging@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/odata@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/sp@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/logging@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/common@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/odata@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/sp@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN adaptivecards-fabric@1.1.2 requires a peer of @fluentui/react@^7.121.2 but none is installed. You must install peer dependencies yourself.
npm WARN adaptivecards-fabric@1.1.2 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN adaptivecards-fabric@1.1.2 requires a peer of react-dom@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 2190 packages in 10.975s
found 337 vulnerabilities (81 low, 120 moderate, 114 high, 22 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\draax\Documents\spfx>`

**Comment by hugoabernier** [comment]
Hey @Draaxdard, can you confirm that you're running `spfx doctor` in the same project folder as `react-adaptivecards`?

**Comment by Draaxdard** [comment]
> Hey @Draaxdard, can you confirm that you're running `spfx doctor` in the same project folder as `react-adaptivecards`?

Hi @hugoabernier, I made a fork of the repo and downloaded a zip file, I created a new folder under my documents called "spfx" and extracted the contents of the react-adaptivecards folder (from the zip file) into the spfx folder.
I then ran "npm install".

when i run npm install im in the spfx folder and the files in the folder are those:
C:\Users\draax>cd C:\Users\draax\Documents\spfx

C:\Users\draax\Documents\spfx>dir
 Volume in drive C has no label.
 Volume Serial Number is AACB-4B51

 Directory of C:\Users\draax\Documents\spfx

11/07/2021  01:58 PM    <DIR>          .
11/07/2021  01:58 PM    <DIR>          ..
01/14/2021  12:56 AM            10,405 .csscomb.json
01/14/2021  12:56 AM               475 .editorconfig
01/14/2021  12:56 AM               326 .gitignore
01/14/2021  12:56 AM               172 .stylelintrc
01/14/2021  12:56 AM    <DIR>          .tours
01/14/2021  12:56 AM               684 .yo-rc.json
01/14/2021  12:56 AM    <DIR>          assets
01/14/2021  12:56 AM    <DIR>          config
11/07/2021  01:32 PM    <DIR>          dist
01/14/2021  12:56 AM             2,020 gulpfile.js
11/07/2021  01:31 PM    <DIR>          lib
11/07/2021  01:58 PM    <DIR>          node_modules
11/07/2021  01:58 PM           762,172 package-lock.json
01/14/2021  12:56 AM             1,707 package.json
01/14/2021  12:56 AM            19,560 README.md
01/14/2021  12:56 AM    <DIR>          src
01/14/2021  12:56 AM    <DIR>          teams
11/07/2021  01:32 PM    <DIR>          temp
01/14/2021  12:56 AM    <DIR>          tools
01/14/2021  12:56 AM               894 tsconfig.json
01/14/2021  12:56 AM               811 tslint.json
              11 File(s)        799,226 bytes
              12 Dir(s)  88,903,802,880 bytes free

**Comment by Draaxdard** [comment]
Hi @hugoabernier, I just figured out why it didn't work!
There ware new 1100 commits on the main repo compared to my fork, I did not know I had to fetch the latest commits.
I'm sorry for taking up your time, however you thought me about spfx doctor which is very valuable!

Thanks for your assistance!
