### ISSUE TITLE
No longer shows in web part picker

### ISSUE THREAD

**Issue by mbalcarek** [pnp/sp-dev-fx-webparts#2113]
### Sample

Modern Script Editor Web Part

### Author(s)

hugoabernier 

### What happened?

Hello,
I am using Team sites with modern pages. Your web part shows on existing pages, but when I create a new page and try to add it, I am unable to see it in the list of web parts to show. I have 1.0.0.16 version installed, and it has been working till very recently. I am also seeing this issue on one other web part (react-add-js-css-ref).
Your web part continues to work where it was already present.

### Steps to reproduce

1.create a new site page
2.click the '+' to add a new web part
3.I cannot locate your web part.

### Expected behavior

I expect to see your web part in the list of web parts.

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.20.1

### Additional environment details

none

**Comment by mbalcarek** [comment]
This issue resolved itself after a few days.

**Comment by mbalcarek** [comment]
Not sure if you can do anything about this, but the web part is often not available to choose, but then has reappeared for use on occasion. This may be a Microsoft issue.

**Comment by hugoabernier** [comment]
@mbalcarek this is an issue that many people have experienced. Take a look at [previous conversations](https://github.com/pnp/sp-dev-fx-webparts/issues?q=label%3Areact-script-editor+) to get the full details on how to configure your site collection to allow the web part to appear.

If the discussions don't help resolve the issue, please come back and provide more details so we can help you further.

**Comment by mbalcarek** [comment]
I have reviewed the previous issues, and they do not resolve my issue.
I had already run -DenyAddAndCustomizePages 0.
The issue is still present and seems intermittent. I have tried removing the web part from site contents and re-adding it. The add of the app looks normal and the web part is briefly greyed out and then becomes solid in site contents, and shows as 'Added' in the apps screen.
I notice that the site **feature is not present in the list of site features**, although the feature IS present in sites where it works correctly. I have viewed the install video. As I mentioned before, pages that already have the web part continue to function.

**Comment by mbalcarek** [comment]
Here is some more information. I have attached 2 screen shots, one is with the web part working and the other is with the web part not working.
![modern-script-editor not working](https://user-images.githubusercontent.com/21264424/144083622-8b04a506-d21b-4f90-9bdd-6e827ca953aa.png)
![modern-script-editor working](https://user-images.githubusercontent.com/21264424/144083668-ea08bff0-14b2-417e-b07c-f2957a681b4e.png)
g.

**Comment by mbalcarek** [comment]
More info: I have noticed differences between incognito and regular browser - same user - the web part does not take effect incognito, but works in regular mode.
Also for some users works in google, but not edge. Most of my testing has been in conjunction with the pnp modern search web part v4.

**Comment by mbalcarek** [comment]
Another interesting observation: we disable modern apps in order to allow "save site as a template". Then we create new sites from these templates and re-enable the modern apps in the source site and enable the modern apps in the newly created site. I have noticed that after re-enabling the modern apps, that they do not work in the source. The web part is not present in the web part picker, and the existing page in edit mode shows - see attachment. In the new site they do work as expected.
![image](https://user-images.githubusercontent.com/21264424/157301087-9eed5790-9825-48af-a68b-26c9c44c94fc.png)
![image](https://user-images.githubusercontent.com/21264424/157301144-a5e022f1-0e0b-43d4-ad37-10d30cb694ba.png)

**Comment by mbalcarek** [comment]
@[hugoabernier](https://github.com/hugoabernier) - I  am unsure how to get this assigned to the right person. I have added a lot of info that should help re-create and narrow down the issue.

**Comment by mikezimm** [comment]
@mbalcarek , You may want to post a link to the sample you are referring to.  I think there are a couple Content Editor/Script Editor samples.

I do know wobba had done this one:
https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor

Regarding some of your observations...
I do know in the last month or so I (and at least one other person in our company) has seen occasions (both in Teams and in SharePoint) where the page does not load or refresh when I open it.  Not sure if it's related but I have seen similar behavior.

Regarding the comment about incognito, it's a total long shot but in our tenant, the web parts just do not work incognito because of a policy that disables 'downloads'.  I'm guessing that's not the case because you would see an error where the web part is but thought I'd mention it just in case.

Anyway, hope you can get an answer regarding this particular web part.

**Comment by wobba** [comment]
@mbalcarek please read the docs which should explain why it's not showing by default: https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-script-editor/README.md#deploy-to-non-script-sites--modern-team-sites
