### ISSUE TITLE
react-sites-selected-admin

### ISSUE THREAD

**Issue by jvpenna1975** [pnp/sp-dev-fx-webparts#2133]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-sites-selected-admin

### Author(s)

 hugoabernier

### Question

I was able to get the app react-sites-selected-admin installed for testing but I am not seeing the webpart anywhere, is there a next step I am missing?

<img width="554" alt="site-selected-1" src="https://user-images.githubusercontent.com/94186146/141492972-a70898ec-a520-485b-ae55-e0a0ddae2786.PNG">
<img width="583" alt="site-selected-2" src="https://user-images.githubusercontent.com/94186146/141492981-a4457e39-eb5a-4fe0-b5b3-30dc00759dcf.PNG">

**Comment by jvpenna1975** [comment]
I have solved this, the issue is the app registration is missing the Short Description and Description.  Once these are added and resaved you will start seeing the webpart in the webpart add menus on modern sites.

![image](https://user-images.githubusercontent.com/94186146/141504025-55c571f0-35f4-4f07-86fd-c8b4898f0968.png)
![image](https://user-images.githubusercontent.com/94186146/141506881-429bcc43-b738-41e7-adc9-592b8b143a5a.png)

**Comment by hugoabernier** [comment]
Thanks for sharing the solution to your issue. I have closed the issue and tagged it so others can find your solution in the future.
