### ISSUE TITLE
Accordion Issue with Column Addition

### ISSUE THREAD

**Issue by Goonie78** [pnp/sp-dev-fx-webparts#2139]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-dynamic-section

### Author(s)

@ejbenke @mikezimm @jyasir @AriGunawan

### Question

Hi guys,

Based on this example...

As the return value of the Managed Metadata column is an object like below:

{
  "Label": "Development",
  "TermGuid": "332e2c99-66fa-49fb-84f6-b0623ada6cb9",
  "WssId": 1
}
So in order to get the expected value, we need to get it from its property (Label).
You can try to implement below code (location):

Single value
-   __html: item[this.props.accordianContentColumn],
+   __html: item[this.props.accordianContentColumn] ? item[this.props.accordianContentColumn].Label : '',

Multiple values
-   __html: item[this.props.accordianContentColumn],
+   __html: item[this.props.accordianContentColumn].map(item => item.Label),

Which didn't work... but by putting in the exact column into the code *via the name say M1 for Metadata 1 Columne):

__html: item["OData__x004d_M1"].map(item => item.Label),

Which works but I don't want to directly reference the column on the build (replacing the this.props.accordianContentColumn) within the build.

Looking for suggestion to why I had to reference the direct column now and not just the Content Column?

**Comment by AriGunawan** [comment]
The `__html: item[this.props.accordianContentColumn].map(item => item.Label)` works for me. I have metadata column with `Metadata` as the internal name.
![image](https://user-images.githubusercontent.com/8691985/143723692-da3e3bed-3515-4918-9c2d-01b6be2e6f62.png)
![image](https://user-images.githubusercontent.com/8691985/143723695-9a8aafc0-1c09-4638-a39a-8741a171567b.png)

Your `this.props.accordianContentColumn` should be the internal name of the selected column on the web part property.
Could you please check the internal name of the column? Is it `ODATA__x004d_M1` or `_x004d_M1`?

**Comment by Goonie78** [comment]
Your this.props.accordianContentColumn should be the internal name of the selected column on the web part property.
Could you please check the internal name of the column? Is it ODATA__x004d_M1 or _x004d_M1?

I had to change the name to  the x004d_M1 ...  without the accordianContentColumn for that to work at least on my end...

**Comment by AriGunawan** [comment]
Is the internal name `_x004d_M1`?
I'm guessing that the result from `getItems` method from REST API return `ODATA__x004d_M1` while your actual internal name is without `ODATA_` prefix. Do you know why it happens?
The REST API usually return the internal name as the property on the result.

Maybe you can use below as workaround if you can't make the REST API return the exact same label with the internal name:
`__html: item[this.props.accordianContentColumn] ? item[this.props.accordianContentColumn].Label || item['ODATA_' + this.props.accordianContentColumn].Label : '',`

**Comment by Goonie78** [comment]
It's weird that that will only work with the specific call out to ODATA... how would that work with the multi-select?

__html: item[this.props.accordianContentColumn].map(item => item.Label),
