### ISSUE TITLE
react-script-editor - Question about testing

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#2140]
### Sample

react-script-editor

### Author(s)

@wobba

### Question

For the [react-script-editor](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites):

Can this be run via gulp serve method without first running the powershell to enable scripts?

Just wasn't sure how the script blocking actually takes place.

Thanks!

**Comment by mikezimm** [comment]
I was able to build and test and learned:
If you use webpart as is, you can add to an app catalog and "Add" the app to your site.
But you are not able to add the webpart to the page.

Thanks for a great example!

**Comment by wobba** [comment]
@mikezimm It's all in the readme :) https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites
