### ISSUE TITLE
react-page-navigator - error TS1005 when trying to create sppkg

### ISSUE THREAD

**Issue by janeaujanssen** [pnp/sp-dev-fx-webparts#2155]
### Sample

react-page-navigator

### Author(s)

@aakashbhardwaj619

### What happened?

When trying 'gulp bundle --ship' command the following errors are observed.
The same errors can be seen when 'gulp serve' is run.

PS C:\react-page-navigator> gulp bundle --ship
Build target: SHIP
[21:18:56] Using gulpfile C:\react-page-navigator\gulpfile.js
[21:18:56] Starting 'bundle'...
[21:18:56] Starting gulp
[21:18:56] Starting subtask 'configure-sp-build-rig'...
[21:18:56] Finished subtask 'configure-sp-build-rig' after 2.78 ms
[21:18:56] Starting subtask 'pre-copy'...
[21:18:56] Finished subtask 'pre-copy' after 46 ms
[21:18:56] Starting subtask 'copy-static-assets'...
[21:18:56] Starting subtask 'sass'...
[21:18:56] Finished subtask 'copy-static-assets' after 30 ms
[21:18:56] Finished subtask 'sass' after 172 ms
[21:18:56] Starting subtask 'tslint'...
[21:18:57] [tslint] tslint version: 5.12.1
[21:18:57] Starting subtask 'tsc'...
[21:18:57] [tsc] typescript version: 3.7.7
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/diffLines.d.ts(8,13): error TS1005: '=' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/diffLines.d.ts(8,34): error TS1005: ';' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/index.d.ts(10,13): error TS1005: '=' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/index.d.ts(10,34): error TS1005: ';' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/index.d.ts(11,1): error TS1128: Declaration or statement expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/index.d.ts(11,13): error TS1005: ';' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/index.d.ts(11,52): error TS1005: ';' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/printDiffs.d.ts(8,13): error TS1005: '=' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/jest-diff/build/printDiffs.d.ts(8,57): error TS1005: ';' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/pretty-format/build/index.d.ts(7,13): error TS1005: '=' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/pretty-format/build/index.d.ts(7,18): error TS1005: ';' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/pretty-format/build/index.d.ts(7,31): error TS1005: ';' expected.
[21:18:59] Error - [tsc] node_modules/@types/jest/node_modules/pretty-format/build/index.d.ts(7,36): error TS1005: ';' expected.
[21:18:59] Error - 'tsc' sub task errored after 2.36 s
 exited with code 2
[21:18:59] 'bundle' errored after 3.19 s
[21:18:59]
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1

### Steps to reproduce

1. Followed steps listed here: [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

2. Installed packages status:
PS C:\react-page-navigator> npm list -g --depth 0
C:\Users\JaneauJanssen\AppData\Roaming\npm
+-- @microsoft/generator-sharepoint@1.12.1
+-- @pnp/cli-microsoft365@4.2.0
+-- gulp-cli@2.3.0
`-- yo@3.1.1

3. Run 'm365 spfx doctor --env spo' with following results:
"\u001b[32m√\u001b[39m SharePoint Framework v1.12.1"
"\u001b[32m√\u001b[39m Supported in SPO"
"\u001b[32m√\u001b[39m Node v14.18.1"
"\u001b[32m√\u001b[39m yo v3.1.1"
"\u001b[31m×\u001b[39m gulp not found"
"\u001b[32m√\u001b[39m react v16.9.0"
"\u001b[32m√\u001b[39m bundled typescript used"
" "
"Recommended fixes:"
" "
"- npm i -g gulp@4"

4. Installed gulp locally and fixed the following missing dependencies:
npm ERR! peer dep missing: jest@26.6.3, required by @voitanos/jest-preset-spfx-react16@1.5.0
npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0 || ^8.0.0, required by acorn-jsx@5.3.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: jest@>=26 <27, required by ts-jest@26.5.6
npm ERR! peer dep missing: typescript@>=3.8 <5.0, required by ts-jest@26.5.6

5. Local packages status:
PS C:\react-page-navigator> npm list --depth 0
navigator@0.0.1 C:\react-page-navigator
+-- @microsoft/rush-stack-compiler-3.3@0.1.7
+-- @microsoft/rush-stack-compiler-3.7@0.2.3
+-- @microsoft/sp-build-web@1.12.1
+-- @microsoft/sp-core-library@1.12.1
+-- @microsoft/sp-lodash-subset@1.12.1
+-- @microsoft/sp-module-interfaces@1.12.1
+-- @microsoft/sp-office-ui-fabric-core@1.12.1
+-- @microsoft/sp-property-pane@1.12.1
+-- @microsoft/sp-tslint-rules@1.12.1
+-- @microsoft/sp-webpart-base@1.12.1
+-- @microsoft/sp-webpart-workbench@1.12.1
+-- @pnp/pnpjs@1.3.11
+-- @pnp/spfx-controls-react@1.14.0
+-- @pnp/spfx-property-controls@1.16.0
+-- @types/es6-promise@0.0.33
+-- @types/react@16.9.36
+-- @types/react-dom@16.9.8
+-- @types/webpack-env@1.13.1
+-- @voitanos/jest-preset-spfx-react16@1.5.0
+-- acorn@6.0.0
+-- ajv@6.9.1
+-- gulp@4.0.2
+-- gulp-sequence@1.0.0
+-- jest@26.6.3
+-- office-ui-fabric-react@7.156.0
+-- react@16.9.0
+-- react-dom@16.9.0
`-- typescript@3.8.3

npm ERR! extraneous: @microsoft/load-themed-styles@1.10.225 C:\react-page-navigator\node_modules\@microsoft\sp-property-pane\node_modules\@microsoft\load-themed-styles
npm ERR! extraneous: @microsoft/load-themed-styles@1.10.225 C:\react-page-navigator\node_modules\@microsoft\sp-webpart-base\node_modules\@microsoft\load-themed-styles
npm ERR! extraneous: es6-promise@4.2.4 C:\react-page-navigator\node_modules\@microsoft\sp-webpart-base\node_modules\es6-promise
npm ERR! extraneous: whatwg-fetch@2.0.3 C:\react-page-navigator\node_modules\@microsoft\sp-webpart-base\node_modules\whatwg-fetch
npm ERR! extraneous: @microsoft/load-themed-styles@1.10.225 C:\react-page-navigator\node_modules\@fluentui\react-focus\node_modules\@microsoft\load-themed-styles

### Expected behavior

I'm not quite sure what was expected but not these errors.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.18.1

**Comment by phjalmarsson** [comment]
I am experiencing the same issue running node.js v14.19.0 and Edge. I have also set up the dev environment according to the same link, and I have succesfully gone through the Hello World example. That article does not explicitly mention a spfx version, although it says "The SharePoint Framework v1.14.1 is supported on the following Node.js versions", so I guess that means the artivel sets up a spfx v14 environment. This sample is based on spfx 12.1, which may or may not be the issue.
* Any updates on whether this will be fixed, and when?
* Any ideas if the issue might be the spfx version? I would be willing to set up a spfx 12.1 environment in a VM (if older versions are a possibility - I am a spfx beginner), but I would like to know if it is likely to be the problem first.

**Comment by phjalmarsson** [comment]
The page https://stackoverflow.com/questions/61783437/react-typescript-error-on-build-in-node-modules-jest-diff-build-difflines-d-ts hints that
"Type-only imports and exports is supported from Typescript 3.8.0. Set Typescript version >= 3.8.0 to resolve this error."
During gulp bundle, there is a line "[11:59:30] [tsc] typescript version: 3.7.7", so that makes sense. Now the question is how to update the project typescript version to 3.8? I tried "npm install -g typescript", which updates SOME installation to 3.8.0 (confirmed with "tsc -v"), but this does not change anyting for the project build: same result as before including the version 3.7.7 message.

**Comment by phjalmarsson** [comment]
Ok, so I think I have found it, using the information from https://www.voitanos.io/blog/use-different-typescript-versions-in-sharepoint-framework-projects/
* npm uninstall @microsof/rush-stack-compiler-3.3
* npm uninstall @microsof/rush-stack-compiler-3.7
* npm install @microsoft/rush-stack-compiler-3.8@0.4.37 --save-dev --save-exact
* Change tsconfig.json to refer to version 3.8 instead of 3.8
* Run gulp commands again
Quickly tested the end result on a site and it seems to work fine, despite some errors from "gulp bundle".

**Comment by colonelclaypoo** [comment]
> Ok, so I think I have found it, using the information from https://www.voitanos.io/blog/use-different-typescript-versions-in-sharepoint-framework-projects/
> 
> * npm uninstall @microsof/rush-stack-compiler-3.3
> * npm uninstall @microsof/rush-stack-compiler-3.7
> * npm install @microsoft/rush-stack-compiler-3.8@0.4.37 --save-dev --save-exact
> * Change tsconfig.json to refer to version 3.8 instead of 3.7
> * Run gulp commands again
>   Quickly tested the end result on a site and it seems to work fine, despite some errors from "gulp bundle".

Worked for me as well. Finally. Thank you!

**Comment by hugoabernier** [comment]
Closing issue as answered
