### ISSUE TITLE
react-calendar - 

### ISSUE THREAD

**Issue by punprom-verelogic** [pnp/sp-dev-fx-webparts#2156]
### Sample

react-calendar

### Author(s)

@Abderahman88, @Eli-Schei, @mohammadamer, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### Question

Hi,
I would like to ask a question on the react-calendar. Is it possible to add custom fields to this calendar, it would be generic field types, such as textbox, date time picker, etc. 
I tried to add into _event.js_, then build and bundled it. To my shock, after bundled it revert back to original, I guess this file is automatically re-built. Can you tell me where I can add these fields onto this calendar, as you expected I am not a great React developer so be gentle with me but can do JavaScript thanks.
Please let me know where and how I can add these input fields. Please, also lets me know how data binding as well.
Thanks for the help, look forward to hearing from you.

Punprom.

**Comment by Abderahman88** [comment]
Hi @punprom-verelogic,

This simple answer: Yes, you can add custom fields. But this needs some changes in the code.
