### ISSUE TITLE
Properties pane to choose parent page missing react-pages-hierarchy - 

### ISSUE THREAD

**Issue by PikeSal** [pnp/sp-dev-fx-webparts#2159]
### Sample

react-pages-hierarchy

### Author(s)

@bogeorge

### What happened?

Installed webpart, property pane to choose parent page missing, not visible in local workbench or Sharepoint online site page
![image](https://user-images.githubusercontent.com/73570781/144905805-f1ee2662-7d72-4f9d-9f6f-3c3c5a9adfcc.png)
![image](https://user-images.githubusercontent.com/73570781/144905836-5f414d97-9c29-4b67-bb92-5e3b947bbfae.png)

### Steps to reproduce

1.Package and upload package to app catalog
2. Inserted page heirarchy webpart into site page
3. Page property to choose parent page missing

### Expected behavior

Page property to choose parent page should be visible on page

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

### Additional environment details

node v10.24.1
gulp@3.9.1
yo@4.3.0
@microsoft/generator-sharepoint@1.10.0

**Comment by PikeSal** [comment]
Parent page property works in communication site pages, not team site pages.

**Comment by iamfromprague** [comment]
> Parent page property works in communication site pages, not team site pages.
> 
> Looks like Team sites, the default content type is a wiki page and in Communication sites it's site page. I got it to work by changing the default content type from wiki to site page for the Parent Page lookup column

In Teams its Site Page by default, if I change it to Wiki Page, the Parent Page lookup works, but then you cant edit the Site. If you change it back, you can edit the site, but you wont see the Parent Page lookup. Anyone found a solution?
