### ISSUE TITLE
js-public-unjoined-teams - 

### ISSUE THREAD

**Issue by savonia-intra** [pnp/sp-dev-fx-webparts#2160]
### Sample

js-public-unjoined-teams

### Author(s)

@LauraKokkarinen

### Suggestion

Hi!

I'm having troubles with this web part. Our organization has thousands of Teams and web part is only showing **36 out of 181** public Teams i'm not in. Does the file "\src\webparts\publicUnjoinedTeams\PublicUnjoinedTeamsWebPart.ts" line 38 **$top=999** limit the results somehow?

`var allTeams= (await this.graphGet(`https://graph.microsoft.com/beta/groups?$filter=resourceProvisioningOptions/Any(x:x eq 'Team')&$top=999`)).value;`

If i try to use bigger number than 999, the web part doesn't work anymore. If I don't use $top parameter, it show only 2 unjoined teams (same as if I use number 99).

Thanks for amazing collaboration!

### Are you willing to help?

Yes

**Comment by LauraKokkarinen** [comment]
Hi,

Paging (https://docs.microsoft.com/en-us/graph/paging) needs to be implemented for this web part for it to work in tenants with a large number of teams. There's an example of how you can implement paging in the following code file (starting at line 44): https://github.com/LauraKokkarinen/spfx-library-graphservice-template/blob/main/src/libraries/graphService/services/GraphService.ts

Laura
