### ISSUE TITLE
react-modern-charts - 

### ISSUE THREAD

**Issue by lpdevkepak** [pnp/sp-dev-fx-webparts#2161]
### Sample

react-modern-charts

### Author(s)

@jcoleman-pcprofessional @petkir @Abderahman88

### Question

Hi 
I've deployed the react modern chart webpart to my SP online tenant and deployed to a site successfully, however I'm getting an error when I add to a page saying it cant load from the https://localhost:4321/workbench.  What am I doing wrong ?

**Comment by Abderahman88** [comment]
Hi @lpdevkepak,

I've added the chart webpart sucessfully on a SP page.

Do you have an error something like this? :

![image](https://user-images.githubusercontent.com/36161889/146442696-7ef49aef-694d-4e76-b8d0-23248115069b.png)

If so, close your browser and re-open again. Make sure you're not running the app from Visual Studio.
