### ISSUE TITLE
Problem with npm install of react-directory

### ISSUE THREAD

**Issue by marting1010** [pnp/sp-dev-fx-webparts#2162]
### Sample

react-directory

### Author(s)

@sudharsank

### What happened?

I get this when I do an npm install of this sample app. 

![image](https://user-images.githubusercontent.com/55257720/145875802-028a3522-74a2-4f1f-af79-112eb7ee51ba.png)

 Having done some googling I found this `npm config set strict-ssl false` as a suggested fix but with no luck. 

Could it be a compatibility issue as I'm running it in the latest node lts v14.16.1?

I've not seen this spfx doctor before. It came back with these recommended fixes 

![image](https://user-images.githubusercontent.com/55257720/145876430-9223c9e2-b8df-4f51-bd82-2d88ec24e7c5.png)

If so, should I run something like "nvm use v10...."? 

### Steps to reproduce

1. Cloned a local repository
2. Ran `npm install`
3.

### Expected behavior

The sample would install so that I could then run a gulp serve to see it my local workbench. 

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.16.1

**Comment by Jwaegebaert** [comment]
The first problem I see here is your Node version. The WebPart _react-directory_ is running on SPFx version 1.11.0. For this version, you will need [Node.js V10.x](https://nodejs.org/dist/latest-v10.x/). Hugo Bernier has written a very useful [blog page](https://tahoeninjas.blog/2019/12/30/spfx-compatibility-matrix/) where you can see a SPFx Compatibility matrix for your development tools. Hope this helps!

![afbeelding](https://user-images.githubusercontent.com/38426621/146190357-805d8438-cb67-4587-809f-7a3fd336f21c.png)
