### ISSUE TITLE
react-tiles-v2 -i am not able to load text labels and all the fields in web part property pane

### ISSUE THREAD

**Issue by parasurammulgund** [pnp/sp-dev-fx-webparts#2170]
### Sample

react-tiles-v2

### Author(s)

fthorild @fthorild

### Question

![image](https://user-images.githubusercontent.com/86785190/146419793-fb17a51f-c0f0-4bc1-9d13-5590eeea0c3f.png)

Kindly suggest if i am missing anything as i have recreated the same solution

**Comment by omarelanis** [comment]
Hi @parasurammulgund, just seen this issue you've raised - please @mention the author when raising a request so it can be picked up

Have you modified the code sample? Can you advise the steps to reproduce the issue?

**Comment by hugoabernier** [comment]
Closing issue due to lack of response
