### ISSUE TITLE
react-script-editor - 

### ISSUE THREAD

**Issue by teixeire** [pnp/sp-dev-fx-webparts#2174]
### Sample

react-script-editor

### Author(s)

@wobba

### Question

hello, is there a way to have the ready file to upload in 'web part gallery' on site settings ?

**Comment by wobba** [comment]
You need to build the SPFx code yourself, possibly changing settings before building to make it work for your scenario.

I always have a question when people want to use the web part. What scenario does it solve for you? And if you make it available to all users, there are risks to consider.
