### ISSUE TITLE
Error in @typescript-eslint/parser package while running gulp serve in react-news-banner webpart in SharePoint 2019

### ISSUE THREAD

**Issue by DJoshi23** [pnp/sp-dev-fx-webparts#2181]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-news-banner

### Author(s)

@joaojmendes

### What happened?

Hi,

I have downloaded the react-news-banner from GitHub and After doing gulp serve below issue is occurring.

![image](https://user-images.githubusercontent.com/86624727/147250428-24130e30-c174-44d7-bdb9-6098e568d328.png)

Please find the environment details

SharePoint Version: SharePoint 2019 Server
Node Version:  8.17.0
Gulp: 3.9.1

Thank you

### Steps to reproduce

Please use below environment and do gulp serve

SharePoint Version: SharePoint 2019 Server
Node Version:  8.17.0
Gulp: 3.9.1

### Expected behavior

The webpart should be working. 

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

8.17.0

### Additional environment details

Node Version:  8.17.0
Gulp: 3.9.1

**Comment by joaojmendes** [comment]
Please se node version 10.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: msftbot[bot] ***@***.***>
Enviado: Thursday, December 23, 2021 2:08:00 PM
Para: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] Error in eslint package while running gulp serve in react-news-banner webpart in SharePoint 2019 (Issue #2181)


Thank you for reporting this issue. We will be triaging your incoming issue as soon as possible.

**Comment by DJoshi23** [comment]
Hi @joaojmendes,

I have updated my Node version from 8.17 to 10.21.1. After upgrading the node some other issues started appearing on gulp serve.

Please find the below image for your reference.

![image](https://user-images.githubusercontent.com/86624727/147331911-3fbaaa7e-3534-4a49-82e0-92a5c30687eb.png)


Thank you

**Comment by joaojmendes** [comment]
Check the version of SPFx is 1.4.1 try delete node_modules folder and package_lock.json and do npm install

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: DJoshi23 ***@***.***>
Enviado: Friday, December 24, 2021 7:58:28 AM
Para: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] Error in @typescript-eslint/parser package while running gulp serve in react-news-banner webpart in SharePoint 2019 (Issue #2181)


Hi @joaojmendes<https://github.com/joaojmendes>,

I have updated my Node version from 8.17 to 10.21.1. After upgrading the node some other issues started appearing on gulp serve.

Please find the below image for your reference.

[image]<https://user-images.githubusercontent.com/86624727/147331911-3fbaaa7e-3534-4a49-82e0-92a5c30687eb.png>

Thank you

**Comment by hugoabernier** [comment]
@DJoshi23 did you ever resolve this issue as per Joao's feedback?
