### ISSUE TITLE
react-advanced-page-properties Unable to see more than "Title" property

### ISSUE THREAD

**Issue by rgmatthes** [pnp/sp-dev-fx-webparts#2184]
### Sample

react-advanced-page-properties

### Author(s)

@mhomol

### What happened?

The Advance Page Properties addin is only showing the "Title" property, despite several other Site Columns applied on the page (of various types, e.g. People, Multi-Line, Category, Managed Metadata, etc.).

### Steps to reproduce

1. Generate demo environment from MS, create and add custom Site Columns to Site Pages library. Create a sample page and add a sample value for each of your columns.
2. Clone repo, run `npm install`, `gulp bundle --ship`. and `gulp package-solution --ship`. 
3. Uploade the packaged solution to the App Catalog in the demo environment. Trust it and then added it to the demo site.
4. On your page, add the Advanced Page Properties webpart. It contains only the Title property, no other properties.

### Expected behavior

Would expect to see the custom site columns I added available for use within this webpart.

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.13.0

### Additional environment details

Noticed when running `gulp bundle --ship`:
"Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db"
"Warning - tslint - src\webparts\advancedPageProperties\components\AdvancedPageProperties.tsx(108,18): error no-use-before-declare: variable 'RenderPagePropValue' used before declaration"
"The build failed because a task wrote output to stderr. Exiting with exit code: 1"

I tried bundling the solution with the current version of the code and also a historical version when the first version didn't work. Both had the same issue, only Title was available for use.

**Comment by Abderahman88** [comment]
@rgmatthes,

I'll check it out. 

Quick question: Which language are you using? Is your SharePoint site in English?

**Comment by rgmatthes** [comment]
Thank you so much. Yes, my site is in English.

**Comment by Abderahman88** [comment]
Found the problem. I made a bugfix for the issue. 
Thank you for reporting 👍 

![image](https://user-images.githubusercontent.com/36161889/147373808-a85f1e1d-c6a4-4cc4-8f47-0836d9d0fb23.png)
