### ISSUE TITLE
react-twitter - 

### ISSUE THREAD

**Issue by surya06** [pnp/sp-dev-fx-webparts#2192]
### Sample

react-twitter

### Author(s)

@AJIXuMuK

### Question

Is this version is compatible with spfx 1.13?

**Comment by AJIXuMuK** [comment]
Hello @surya06 - the sample is built using SPFx 1.10 and I didn't update it to 1.13.1.
But I don't think there are any issues updating it to 1.13.1.

You can use [CLI for M365](https://pnp.github.io/cli-microsoft365/) and `m365 spfx project upgrade` command to guide you through the upgrade process.
