### ISSUE TITLE
UI Fabric icon GUI ideas

### ISSUE THREAD

**Issue by jacobchris6** [pnp/sp-dev-fx-webparts#2193]
### Sample

react-tiles-v2

### Author(s)

@fthorild @omarelanis

### Suggestion

Web part is working well. Just a couple suggestions for enhancements.

1. There are so many icons, it'd be handy if the search criteria queried all portions of the icon name instead of just the beginning text.  IE. If you search for "manage" it will only return results for icons that begin with "manage****".  But will miss ones with names like "AccountManagement".  Searching full name could help zero in on a useful icon.
2. When the UI icon is initially selected, it's name appears down at the bottom of the GUI next to the "Save" button.  Say a couple months pass and you want to see the name of that icon you previously found and go into the settings and check the icon. It does not have the icon name listed like it did initially. Its blank. It'd be cool if the name was listed on subsequent viewings of the properties. 
Thanks for the consideration

### Are you willing to help?

No

**Comment by Jwaegebaert** [comment]
> There are so many icons, it'd be handy if the search criteria queried all portions of the icon name instead of just the beginning text. IE. If you search for "manage" it will only return results for icons that begin with "manage****". But will miss ones with names like "AccountManagement". Searching full name could help zero in on a useful icon.

For your first suggestion, we will have to start looking to make an enhancement to the `Property Controls` repo. Here more specifically on the IconPicker control. @hugoabernier should I make an issue there to suggest this change?

> When the UI icon is initially selected, it's name appears down at the bottom of the GUI next to the "Save" button. Say a couple months pass and you want to see the name of that icon you previously found and go into the settings and check the icon. It does not have the icon name listed like it did initially. Its blank. It'd be cool if the name was listed on subsequent viewings of the properties.

For this part, I can set up a PR to implement this enhancement. Could this issue be assigned to me?

**Comment by Jwaegebaert** [comment]
Currently this sample is on version 1.11.0 of SPFx. Is it perhaps an idea to upgrade it at the same time or is that not the intention?

**Comment by Jwaegebaert** [comment]
Hey @hugoabernier, for the first part of this issue. Is it possible to move this to the repo `sp-dev-fx-controls-react`, so that we can address the first part of this problem there? Or should I possibly just start a new issue there?

**Comment by hugoabernier** [comment]
@Jwaegebaert if I transfer the issue, it'll close it here, I would suggest that you open a new issue there and link the issue here.

You can use `pnp/repo#59` to link to another repo (59 is just a random number I picked -- use your own issue number 😉)

**Comment by Jwaegebaert** [comment]
Ow my bad. It was already patched in a later version of `@pnp/spfx-property-controls`. I just need to upgrade the package within the webpart so this feature can get completed. To do this I will need to set up a new PR here to implement it. Sorry for the inconvenience!

**Comment by Jwaegebaert** [comment]
Hey @jacobchris6, thank you for the suggestion of these enhancements. These have now been implemented and have also been merged with the `main` branch.

**Comment by jacobchris6** [comment]
@Jwaegebaert . Very nicely done. It works great. Thank you very much!
