### ISSUE TITLE
react-script-editor - 

### ISSUE THREAD

**Issue by cimares** [pnp/sp-dev-fx-webparts#2194]
### Sample

react-script-editor

### Author(s)

@wobba

### What happened?

We're using the React-Script-Editor to place a third party Live Chat widget on a single page in a Modern site collection. To do this, we've created a modern page called LiveChat.aspx, added some page content and the Script Editor webpart with the Widget code, which attaches the live chat window to the side of the page.

![image](https://user-images.githubusercontent.com/7425644/148209884-3b024057-74ff-4655-9687-c855e92fb7e7.png)

This works perfectly and achieves what was required, however when we navigate to a new page, the Widget for the live chat comes with it, and remains until the next full reload. I'm assuming this is because the page is doing a partial reload rather than a full load.

Is there anything we can change or hook into that will pick up the partial page load and allow us to evaluate the page URL and potentially ignore the JavaScript code?

### Steps to reproduce

1. Build the sample as is.
2.Add to Modern Web Part page
3. Include third party Widget code. This uses Dom manipulation to inject a live chat widget to the right hand of the screen

### Expected behavior

When the page changes to a page without the webpart, I'd expect the script not to be available or run.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.18.1

**Comment by wobba** [comment]
I assume your code injects something in the DOM outside the web part area.. so the question is how can we remove it in a generic way? If all your DOM additions are within the webpart they would be removed on navigation as the DOM is changed.

We could provide an option to execute some javascript on unload/navigation, and you have to know how to unload your code. Would that work?

**Comment by cimares** [comment]
I think that would work. I'll dig into the third party library and find out what ID they use at the top of their DOM injection. We could then use a simple exit script to pull that content out of the DOM.

**Comment by wobba** [comment]
I'll add a setting for dispose code. Coming soon :)

**Comment by cimares** [comment]
You're a diamond Mikael, I owe you a beer at the next event!

**Comment by wobba** [comment]
I'm almost done.. have to do some more testing first.

**Comment by wobba** [comment]
Seems to work ok. I tested with the below. Let me know if you have issues.

```html
<script>
document.getElementsByTagName("body")[0].firstChild.parentElement.insertAdjacentHTML("beforeBegin","<div id='abc'>asdadsasd</div>")
</script>
```

and this in dispose

```html
<script>
document.getElementById("abc").remove()
</script>
```

**Comment by cimares** [comment]
Cheers @wobba you are a Gent!.. I'll get it deployed and tested against the third party code!

**Comment by cimares** [comment]
@Wobba IS this waiting on a Merge? I'm not seeing the code changes in the sample yet?

**Comment by cimares** [comment]
@Wobba Ignore that.. I'm looking at my own fork.. 8(
