### ISSUE TITLE
react-taxonomy-file-explorer - 

### ISSUE THREAD

**Issue by DTI-SG** [pnp/sp-dev-fx-webparts#2198]
### Sample

react-taxonomy-file-explorer

### Author(s)

@mmsharepoint

### Question

Hi Markus
Thank you for that good example of the taxonomy-file-explorer. I played around with it a bit and tried to implement a "Close All" button. This could be useful if the folder list is very long and you want to get an overview of the existing folders. One solution could be to start with closed folders ... but then I would need an "Open All" button ;)
Could you give me an idea/advice how you would implement such button(s)?
Thanks a lot and kind regards, Sebastian

**Comment by mmsharepoint** [comment]
@DTI-SG That's achievable. Did you see how I set the selectedNode? That's a combination of a property which all TermLabels "hold" and is handled in the parent component TaxonomyFileExplorer:
In case a different Label is selected, all other labels need to be reset (as one TermLabel doesn't know what other TermLabel might be the former selected one to turn it off, also there is no relation between any of them except parent child.

So I always go to the parent component TaxonomyFileExplorer change a state there and this state then is a property of all TermLabel components.
So implement your Close / Open all at least as function inside TaxonomyFileExplorer and set a property to all TermLabel components Collapsed: true/false which affects those TermLabel components having children and the expand/collapse icon ...
Does that help as an idea?

**Comment by DTI-SG** [comment]
Hi Markus
Thank you for the quick esponse on my question :)
Yes, I think I understand this procedure. Will give it a try within the next days.

**Comment by DTI-SG** [comment]
Hi Markus
I tried to implement this, but I run into the problem that the React always falls into an infinite loop and chrashes....
I ended up implementing a "openAll" flag that every node watches for. Maybe not the best way, but it solves it for me.
Thanks again!

**Comment by mmsharepoint** [comment]
@DTI-SG But I think that is exactly what I suggested:
Handover a property (or what do you mean with "flag"?) to all TermLabel components.
This "prop" then initially handles the state (if open or not) and later individual open/close changes the state only ...
And don't forget to react on later change of the prop with a specific useEffect ...

**Comment by DTI-SG** [comment]
@mmsharepoint Yes, you are right :)
