### ISSUE TITLE
[react-advanced-page-properties] Showing people fields

### ISSUE THREAD

**Issue by HamEv** [pnp/sp-dev-fx-webparts#2199]
### Sample

react-advanced-page-properties

### Author(s)

Abderahman Moujahid

### Suggestion

People fields of the page library should be shown, too. My customer needs to show a lot of information about people (eg. author of the page, last modifier, ...)

Would be great, if the webpart will be extended, because in this state I cannot use it.

Thanks,
Evelyn

### Are you willing to help?

No

**Comment by Abderahman88** [comment]
I've extend my PR with the person field #2202

**Comment by HamEv** [comment]
Hi @Abderahman88,
thanks a lot for the change. Unfortunatly it's not commited to main brunch. Where can I find the whole project?
Thanks.

**Comment by HamEv** [comment]
Hi @Abderahman88,
thanks a lot for the change.

**Comment by HamEv** [comment]
@Abderahman88 
I replaced the four files you've checked in on my local environment. 
Now nothing is been shown anymore:

Versoin before (1.0.2.0)
![grafik](https://user-images.githubusercontent.com/61208008/149308510-41262fcf-9161-4a6f-99d1-9347edfc2ada.png)

Version now (1.0.3.0)
![grafik](https://user-images.githubusercontent.com/61208008/149308557-09a9ffe5-e3c3-4235-b73e-792533c811b7.png)

Do you have any idea, why that is happing?

**Comment by Abderahman88** [comment]
@HamEv What type of field is it?

**Comment by HamEv** [comment]
@Abderahman88 
Thats a taxonomy field - but it occurs on ALL field types.

**Comment by Abderahman88** [comment]
@HamEv I've tested with an English site and there is an issue with the `Title` property.
But other fieldtypes, I get my result.

![image](https://user-images.githubusercontent.com/36161889/149313274-eafc797f-6d7e-4fc8-bf69-1ed0f41fd20f.png)

**Comment by Abderahman88** [comment]
@HamEv Quick question, have you renamed the fields?

**Comment by HamEv** [comment]
@Abderahman88 No, I haven't renamed the fields. Just used the code (main brunch) from yesterday and replaced the four files, you have changed. Uploaded the solution to app catalog.

Could I somehow check where the error occurs? Chrome Dev Tools does not shown any error.

I can also wait for the new main brunch (currently your changes have not been synchronised).

**Comment by Abderahman88** [comment]
@HamEv I've added the sppkg-file in this ZIP. You can check it with this one.
[advanced-page-properties.zip](https://github.com/pnp/sp-dev-fx-webparts/files/7862088/advanced-page-properties.zip)

**Comment by HamEv** [comment]
@Abderahman88 thanks, but the same error occurs. Maybe my soluton is somehow destroyed. I'll try to uninstall and re-install die solution.

**Comment by HamEv** [comment]
@Abderahman88 
I added it to a new site and it's working now here :-)
But the existing site has problems to re-install the solution. Do you have an idea how I can force to (un)install the solution via powershell? I have no chance doing that via sharepoint default things.

**Comment by Abderahman88** [comment]
@HamEv You can use [CLI for Microsoft 365](https://pnp.github.io/cli-microsoft365/) and use [m365 spo app uninstall](https://pnp.github.io/cli-microsoft365/cmd/spo/app/app-uninstall/) command. If you need any help, let me know.

**Comment by HamEv** [comment]
Hi @Abderahman88, thanks a lot for your help. I uninstalled the app on my site, which works without an error: 
m365 spo app uninstall -i DAAE06A2-8599-445C-93C0-3BD739305F56 -s https://xxxx.sharepoint.com/sites/xxxx
Then I installed the app one again via browser in the site, but unfortunalty nothing has changed. It seems that somehow the app has references or anything else to an old version - is that possible?

When creating a new site and install the app, everything works find. Unfortunatly I have to install the app to the existing site, there is no possiblilty to re-create that site. :-(

Do you have any other ideas how I can (force) to unstall everything from a soltuion (site an app catalog), re-install the app without any references to any old versions?

Thanks!

**Comment by Abderahman88** [comment]
@HamEv Here are my latest changes.
[advanced-page-properties.zip](https://github.com/pnp/sp-dev-fx-webparts/files/7866038/advanced-page-properties.zip)

Just replace the one in your app catalog (even if it has the same version number)

![image](https://user-images.githubusercontent.com/36161889/149410053-205ef88c-5999-4e11-9794-52dee41e35d8.png)

On the site where the app is installed:
1) Go to `Details`
![image](https://user-images.githubusercontent.com/36161889/149409499-164f1126-c6fd-4139-8bf2-3203e8bd4927.png)
2) Check if you have the latest version. (If not, update it)
![image](https://user-images.githubusercontent.com/36161889/149410563-f3f104e2-62c5-43e6-b248-c2f19aff05d3.png)

**Comment by HamEv** [comment]
Hi @Abderahman88 
thanks for the update - I've installed the updated package to my app catalog. Then I removed the app from my existing site, deleted it in recycle bin and recycle bin (2nd stage). I installed the app once again, but it's still not working in this site:
![grafik](https://user-images.githubusercontent.com/61208008/149675758-cc41f7d6-d2c7-4249-b9b2-e90de16c9ec3.png)

Title is the only column which is working in this case.

In a newly created site the app is working.

**Comment by Abderahman88** [comment]
Hi @HamEv,

Have you tried to delete the properties and re-add them?

![image](https://user-images.githubusercontent.com/36161889/149676194-11f9e521-005d-455d-bc8b-af4d6916a176.png)

**Comment by Abderahman88** [comment]
Hi @HamEv, 

Do you still have problems? Or could we close this issue?

**Comment by HamEv** [comment]
Thanks, I'll close the issue, it's ok for the moment :-)
