### ISSUE TITLE
react-advanced-page-properties: incorrect currency/date/number format (language)

### ISSUE THREAD

**Issue by HamEv** [pnp/sp-dev-fx-webparts#2200]
### Sample

react-advanced-page-properties

### Author(s)

@Abderahman88

### What happened?

DateTime, Number and Currency values are formated with "en-US" and not with current site language setting.

### Steps to reproduce

1. Install solution
2. Show currency field
3. incorrct value on german site

### Expected behavior

DateTime, Number and Currency values are formated correct depending on the current site language settings.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [X] Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

**Comment by Abderahman88** [comment]
@HamEv I made a fix. Let me know if something isn't working. I've tested with different fieldtypes.

![image](https://user-images.githubusercontent.com/36161889/149231197-437328c7-fc7b-44e8-99b1-d0577f48b478.png)

![image](https://user-images.githubusercontent.com/36161889/149231257-28c70d22-6ef7-4f67-824c-de9670c3015e.png)
