### ISSUE TITLE
react-birthdays wont build

### ISSUE THREAD

**Issue by dedwardswow** [pnp/sp-dev-fx-webparts#2201]
### Sample

react-birthdays

### Author(s)

@VesaJuvonen

### What happened?

Receive following error when execute npm install

8344 error code 1
8345 error path c:\react-birthdays\node_modules\deasync
8346 error command failed
8347 error command C:\WINDOWS\system32\cmd.exe /d /s /c node ./build.js
8348 error gyp info it worked if it ends with ok
8348 error gyp info using node-gyp@3.8.0
8348 error gyp info using node@16.13.1 | win32 | x64
8348 error gyp ERR! configure error
8348 error gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
8348 error gyp ERR! stack   File "<string>", line 1
8348 error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
8348 error gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8348 error gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
8348 error gyp ERR! stack
8348 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
8348 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
8348 error gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
8348 error gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:450:11)
8348 error gyp ERR! stack     at Socket.emit (node:events:390:28)
8348 error gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
8348 error gyp ERR! System Windows_NT 10.0.19042
8348 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\react-birthdays\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
8348 error gyp ERR! cwd c:\react-birthdays\node_modules\deasync
8348 error gyp ERR! node -v v16.13.1
8348 error gyp ERR! node-gyp -v v3.8.0
8348 error gyp ERR! not ok
8348 error Build failed

### Steps to reproduce

1. run npm install within react-birthdays folder

### Expected behavior

build should be successful

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v16.13.1

**Comment by Abderahman88** [comment]
@dedwardswow 

Use a lower version of Node.

See [SPFx Compatibility Matrix](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility)
