### ISSUE TITLE
Is there a sample webpart to let people manage user custom actions on a site?

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-webparts#2254]
### Sample

n/a

### Author(s)

n/a

### Question

Is there a sample webpart to let people manage user custom actions on a site? I know i saw a webart presented in the weekly meeting years ago, but i cannot find it.

If ther is not one I will certainly make one :-)

**Comment by bcameron1231** [comment]
Hi Russ, I haven't seen one of these in our repo. We do have a sample for managing User Custom Actions for Application Customizers. 

Maybe this one could be modified to support all custom actions instead.

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-edit-applicationcustomizer

**Comment by hugoabernier** [comment]
@russgove did @bcameron1231 's answer help you solve this issue at all? 

Let us know so we can close this issue

**Comment by russgove** [comment]
closing issue. Will work on sample as time permit6s.
