### ISSUE TITLE
samples/angular2-prototype does not compile and is 5 years old. Remove it?

### ISSUE THREAD

**Issue by tonydiep** [pnp/sp-dev-fx-webparts#2344]
### Sample

samples/angular2-prototype

### Author(s)

https://github.com/dgaeta

### What happened?

npm i fails to build 

### Steps to reproduce

1. clone
2. npm i
3.

### Expected behavior

builds

### Target SharePoint environment

SharePoint Online

### Developer environment

Linux

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.19.0

**Comment by hugoabernier** [comment]
Thanks for your suggestion, however there are folks who may still find the sample useful. 

You'll also find that the sample is more likely to work with the version on Nodejs that is compatible with this solution; Node 14 is not compatible with Node 6 solutions
