### ISSUE TITLE
react/Hero-WebPart issue

### ISSUE THREAD

**Issue by walleford** [pnp/sp-dev-fx-webparts#2388]
### Sample

pnp/sp-dev-fx-webparts/tree/main/samples/react-hero-webpart

### Author(s)

@hugoabernier 

### What happened?

I am getting an issue in the HeroWebPart.ts file, on line 47:

items:this.properties.collectionData?this.properties.collectionData:[]

I am getting this error:

Property 'collectionData' does not exist on type 'IHeroWebPartProps'.ts(2339)

### Steps to reproduce

1.Once trying to use the sample, the error stops me from doing anything
2.
3.

### Expected behavior

I expected once I tried to add the property into the props file, it would fix it. 

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

14.19.0

**Comment by walleford** [comment]
Hello, I updated the author tag. Just wanted to make sure this was still pending. Thank you!

**Comment by hugoabernier** [comment]
> Hello, I updated the author tag. Just wanted to make sure this was still pending. Thank you!

I am not the author of the web part. I manage the repo. If you want the original author to be notified, you'll need to tag the author as stated in the issue template. Please [read this article](https://github.com/pnp/sp-dev-fx-webparts/wiki/How-to-Create-Good-Issues) so we can help you the best way we can.

**Comment by Abderahman88** [comment]
Hi @walleford,

I've tested the webpart and have no issues. (npm v14.15.3)

![image](https://user-images.githubusercontent.com/36161889/156849773-d8b67ee6-d5fb-43fc-ad5b-2bfc8e794324.png)

**Comment by omarelanis** [comment]
@walleford  are you still experiencing an issue with using the webpart? Can you provide some steps you followed in order for us to replicate the issue you are having?

**Comment by hugoabernier** [comment]
Closing this issue because it is flagged with the wrong author, and is unlikely to get any response.
