### ISSUE TITLE
Error using as is "react-content-query-webpart.sppkg" file

### ISSUE THREAD

**Issue by kbrhoades** [pnp/sp-dev-fx-webparts#2413]
### Sample

React-Content-Query-Online

### Author(s)

@hugoabernier  @PaoloPia @DavidWarnerII

### What happened?

 Up until recently I had an older version of this same web part working successfully.  It started pulling up " _Failed to load URL 'https://publiccdn.sharepointonline.com/spptechnologies.sharepoint.com/1107....._" errors last week so I figured I would just try updating the web part.  I am not a java developer so I really appreciate any assistance you can give.

I downloaded the code & spent 2 days trying to get a test environment working with all the correct versions, no luck.  I ended up taking the existing .sppkg file at _\samples\react-content-query-online\sharepoint\solution_ and uploaded to our tenant.  Went through the whole app catalog thing & added the 'Content Query' web part to a few pages.  This is the error I get -

**Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details. 

TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "ac515af1-4490-4c7b-8191-d49b41b26c5e" (ContentQueryWebPart). Original error: Failed to load URL 'https://localhost:4321/dist/contentQueryStrings_en-us.js' for resource 'contentQueryStrings' in component 'ac515af1-4490-4c7b-8191-d49b41b26c5e' (ContentQueryWebPart). There was a network problem. Make sure that you are running 'gulp serve' and you have run 'gulp trust-dev-cert'.

INNERERROR:
Failed to load URL 'https://localhost:4321/dist/contentQueryStrings_en-us.js' for resource 'contentQueryStrings' in component 'ac515af1-4490-4c7b-8191-d49b41b26c5e' (ContentQueryWebPart). There was a network problem. Make sure that you are running 'gulp serve' and you have run 'gulp trust-dev-cert'.

CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:70:214295)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:8874)
    at Function.e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:45955)
    at Function.e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:42072)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_c13a3fd9296251f1459f.js:1:60147**

### Steps to reproduce

1. Download .zip from https://github.com/pnp/sp-dev-fx-webparts 
2. Upload \samples\react-content-query-online\sharepoint\solution\react-content-query-webpart.sppkg to tenant app catalog
3. Add app to a site
4. Add Content Query web part to a page

### Expected behavior

A functioning web part.

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

na

**Comment by Abderahman88** [comment]
Hi @kbrhoades,

Can you test this version out? It's not the latest, but it's working on my tenant.
[react-content-query-webpart.zip](https://github.com/pnp/sp-dev-fx-webparts/files/8227275/react-content-query-webpart.zip)

**Comment by hugoabernier** [comment]
@kbrhoades did @Abderahman88 's response help you solve your issue? 

Please note that the samples in this repository are intended to be used as code samples. You should always make sure to review the code on your own to make sure that the solution meets your organization's security standards.

Although @Abderahman88 is a trustworthy person, we encourage that you avoid installing packages that you didn't review and build yourself, or that were not installed through the app store.

Thank you @Abderahman88 for helping out with this one -- and for always being there to help folks in the community.

I'm going to go ahead and mark the issue as closed, but if you run into issues building the solution, please don't hesitate to open a new issue with additional details.

**Comment by kbrhoades** [comment]
@hugoabernier @Abderahman88 
Thank you both so much for your prompt response, for some reason i had been waiting for an email notification and did not check back to this page *Doh*.   I uploaded the version @Abderahman88 included & it works, I am so relieved I am just going to quit for the day.  Thank you both so much, I love this web part!!

**Comment by PicGadm** [comment]
> 

Hello, where should he have changed the link?
I am having the same issue with another sample.

I need to strip the "publiccdn.sharepointonline.com" from the CDN url like in the example below..

https://publiccdn.sharepointonline.com/spptechnologies.sharepoint.com/1107.....
