### ISSUE TITLE
Opening a sample using a development container: Hosted workbench says that gulp serve is not running

### ISSUE THREAD

**Issue by Zerg00s** [pnp/sp-dev-fx-webparts#2415]
### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-enhanced-powerapps

### Author(s)

@bernierh

### Question

I am trying to follow the article described here: https://github.com/pnp/sp-dev-fx-webparts/wiki/Opening-a-sample-using-a-development-container. I also watched this great demo on YT: https://www.youtube.com/watch?v=TD1rw5kq8H4

**Details**
- OS: Windows 11
- WSL 2 Installed
- VS Code Remote - Containers extension is installed.
- Docker for Windows installed
- Docker settings:
![image](https://user-images.githubusercontent.com/2797648/157782313-d2a1a37d-c172-4fc5-97da-c164fe150600.png)

![image](https://user-images.githubusercontent.com/2797648/157782271-94b2ba22-6fb1-446f-9847-f2c7360bc318.png)

- Opened the sample project using container.
- The container's start-up script finished with no errors.
- Dev certificate was generated successfully. 
- I Downloaded the Dev certificate and installed it to the trusted root store.

![image](https://user-images.githubusercontent.com/2797648/157782436-66867d97-6835-4e1f-9b5c-14af64bf5059.png)

- gulp serve finishes with no errors
![image](https://user-images.githubusercontent.com/2797648/157782548-0f15f608-2496-4f4c-ba25-ef164dee3c25.png)

**Issue**

- When opening a hosted workbench, I get an error saying that gulp serve was not run even though it _is_ running.
- I order to fix it, opened the manifest file in a new browser tab:
![image](https://user-images.githubusercontent.com/2797648/157782831-255f06f2-2edf-4a7b-8345-c8cd30786f1b.png)

![image](https://user-images.githubusercontent.com/2797648/157782875-1a8c1575-2931-45e9-897f-e6c9de055e78.png)

![image](https://user-images.githubusercontent.com/2797648/157782910-706960a5-18e4-4e9c-9214-c35bca229258.png)

**Questions**
- what is the proper way to install `spfx-dev-cert.cer` certificate on Windows? Is this the right way?
![image](https://user-images.githubusercontent.com/2797648/157783465-08a0077c-58c3-4e95-b6ba-dbb5353e7127.png)
- What is the right way to deal with the `Your web part will not appear in the toolbox. Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running.` message?
![image](https://user-images.githubusercontent.com/2797648/157783579-a4005a63-c293-4726-b8d6-b707b18180f5.png)

**Comment by hugoabernier** [comment]
Thanks for reminding me that I hadn't posted the instruction to solve this issue @Zerg00s . I have documented the steps in this [wiki](https://github.com/pnp/sp-dev-fx-webparts/wiki/Opening-a-sample-using-a-development-container#debugging-with-containers).

Will close this issue as I fully expect my flawless documentation skills and infallible steps will resolve this issue. In the (highly unlikely) chance that this does not solve your issue (most likely due to a failure on your part! 😋), please feel free to re-open this issue.

**Comment by Zerg00s** [comment]
Thank you @hugoabernier. I did follow your steps. The document is very clear and easy to follow. But turned out that my issue is with the browser I was using. Turned out that my favorite browser, Brave simply does not let me get the manifest file via https no matter what. Once I switched to google and MS Edge, the workbench opened perfectly fine.
