### ISSUE TITLE
react-birthdays - support for Microsoft Teams home site app

### ISSUE THREAD

**Issue by joostvdlinden** [pnp/sp-dev-fx-webparts#2430]
### Sample

react-birthdays

### Author(s)

@smaity @joaojmendes

### Question

I have implemented this Birthday web part in February 2020.
It works fine on SharePoint Online.

But when add the Communication Site as a Home site app to Teams, it shows all web parts except the React Birthdays web part:
![2022-03-12 10_04_14-dx lounge _ Microsoft Teams](https://user-images.githubusercontent.com/47981540/158011666-6ca90b7c-cb53-4513-8e1e-9d46dc68be34.png)

Is this unsupported or how could I resolve this issue?

Many thanks!

**Comment by arturstrzalkowski** [comment]
Any update regarding this issue? We have the same problem here.

**Comment by hugoabernier** [comment]
Thank for reaching out. These samples -- and issues related to them -- are community-supported; we rely on the goodwill of those who authored the samples or those willing to spend their free time to help with issues.

From what it seems, you have tagged the authors and provided sufficient information. The authors may be too busy at the moment to help. You might want to tag the authors instead of me.

I have added a Help wanted flag to see if we can encourage others in the community to pitch in.

Best of luck with solving this issue!

**Comment by mgwojciech** [comment]
Hi @joostvdlinden I tried to reproduce it but works fine in my environment. 
I took a look in the code and the functionality is based on MSGraphClient, it's possible there are some issues related to authentication. If You can, try to open Teams Desktop in Developers preview and open dev tools (more on it here:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)
This can give You more insights into the problem. If I'm right about the authentication, I would suggest changing accessTokenAcceptedVersion in SPO Ext Principal.
To do that navigate to portal azure, go to AAD and then to App Registrations. Now in All applications find SharePoint Online Client Extensibility Web Application Principal. Go the manifest and set accessTokenAcceptedVersion to 1. Save the manifest.
From now on You should be able to authenticate to Graph in Teams client.

Hope that will help.

**Comment by joostvdlinden** [comment]
> Hi @joostvdlinden I tried to reproduce it but works fine in my environment. I took a look in the code and the functionality is based on MSGraphClient, it's possible there are some issues related to authentication. If You can, try to open Teams Desktop in Developers preview and open dev tools (more on it here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools) This can give You more insights into the problem. If I'm right about the authentication, I would suggest changing accessTokenAcceptedVersion in SPO Ext Principal. To do that navigate to portal azure, go to AAD and then to App Registrations. Now in All applications find SharePoint Online Client Extensibility Web Application Principal. Go the manifest and set accessTokenAcceptedVersion to 1. Save the manifest. From now on You should be able to authenticate to Graph in Teams client.
> 
> Hope that will help.

Hi @mgwojciech thank you for helping out!
I have discovered that in Google Chrome web browser the birthday web part actually works when I have opened the home site app, and also in Microsoft Edge Chromium. But not on Microsoft Teams desktop.

I ran the Developer Tools, which was really helpful, and through the console I could see the following error message: "Uncaught (in promise) Unable to retrieve Client Secret". Not sure if this influences your findings?

I will definitely take a look at your suggestions and I'll let you know the outcome.

**Comment by joostvdlinden** [comment]
Hi @mgwojciech, 
I have also tried changing the parameter accessTokenAcceptedVersion from null (initial value) to 1. 
Me and my colleague both fully closed Teams desktop, but it did not help.

**Comment by joostvdlinden** [comment]
So what I did is I generated a whole new sppkg package and followed the implementation steps again.
The problem got fixed after applying the API permissions from the SharePoint admin center.
The existing web part I had published now works fine.
Thanks for the help @mgwojciech
