### ISSUE TITLE
How to add a Filtering to filter user based on location or UsageLocation 

### ISSUE THREAD

**Issue by supermode** [pnp/sp-dev-fx-webparts#2433]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-directory

### Author(s)

@joaojmendes @petkir @sudharsank @Abderahman88

### Question

Hi,

Thank you for this awesome solution. Our Office 365 tenant have users from multiple country. I just wondering is there any possibility to filter result and return users from specific country or UsageLocation. ie. US and NZ when this solution loaded in the page.

Thank you

**Comment by supermode** [comment]
@joaojmendes @petkir @sudharsank @Abderahman88. Any suggestions?

**Comment by Abderahman88** [comment]
Hi @supermode 

Maybe similar as #2437 ?

**Comment by Abderahman88** [comment]
@hugoabernier I think we can close this one.
