### ISSUE TITLE
react-page-navigator - Unable to build

### ISSUE THREAD

**Issue by supermode** [pnp/sp-dev-fx-webparts#2434]
### Disclaimer

Yes

### Sample

react-page-navigator

### Author(s)

@aakashbhardwaj619

### What happened?

Hi Aakash,

Thank you for awesome solution. I tried to build the solution and I have the following errors:
![image](https://user-images.githubusercontent.com/20655527/158084879-c65a2856-f8b7-438e-99de-5bb1ad742f9e.png)

Is there any prerequisite version of Node.js, Typescript, React or other required for this solution?

Thank you

### Steps to reproduce

1. Clone the solution
2. npm i
3. gulp build then you received the error.

### Expected behavior

run gulp build and received the following error
![image](https://user-images.githubusercontent.com/20655527/158087092-9cdabf7a-1066-4015-9225-4bd06b836097.png)

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

![image](https://user-images.githubusercontent.com/20655527/158086990-90c849e0-ff18-49fe-93f4-ea6e03a0adbd.png)

### Additional environment details

Global configuration
![image](https://user-images.githubusercontent.com/20655527/158087030-c9f0a1d8-9f18-4a56-b0f5-818a8b206369.png)

**Comment by milanholemans** [comment]
Using Node v14.x, I'm able to build the solution by just removing the **package-lock.json** file and running an `npm install` afterwards, be sure to delete your node_modules folder before running `npm install`.

Not sure if this issue should be fixed?

**Comment by supermode** [comment]
Thanks Milan. It worked

**Comment by JoeAyre** [comment]
> Using Node v14.x, I'm able to build the solution by just removing the **package-lock.json** file and running `npm install` afterwards, be sure to delete your node_modules folder before running `npm install`.
> 
> Not sure if this issue should be fixed?

Did the trick for me also, using Node v14.17.0 - Thanks @milanholemans!
