### ISSUE TITLE
react-calendar - 

### ISSUE THREAD

**Issue by mrivera4** [pnp/sp-dev-fx-webparts#2435]
### Disclaimer

Yes

### Sample

react-calendar

### Author(s)

@Abderahman88, @Eli-Schei, @mohammadamer, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### Question

Hi All,

I have a question about removing unwanted fields from the new item form that is rendered when adding events. I have created a content type based on the Event CT in SPO.  I then created a list and added that CT to the list, removing everything else.  Our customer only really wants four fields to show up when adding events - Event title, Category, Start Date, End Date.  In an effort to remove all other fields, I went into the CT and the List and used PowerShell to hide all unwanted fields, however, the calendar is not reflecting those changes.  Where would I make changes to show/hide fields, and since code will need to be changed, and we wanted to use this calendar for other sites, my assumption is I'd have to create a special webpart for this customer?  

Thanks in Advance

**Comment by Abderahman88** [comment]
@mrivera4 You can copy this sample, rename it (f.e. react-calendar-custom) and remove the unwanted fields in the code.

**Comment by mrivera4** [comment]
Hi,

So I see the fields in /src/controls/Event/Event.tsx - but when I comment out the divs for the unwanted fields, they still render on the page.

**Comment by Abderahman88** [comment]
You are on the right path. You need to comment out the unused fields in `Event.tsx`. 
Normally this should work. (I've tested it) Maybe your changes were not loaded.

![image](https://user-images.githubusercontent.com/36161889/158694258-96bc869f-a81e-4814-824e-77d138587bd8.png)

![image](https://user-images.githubusercontent.com/36161889/158694495-359ec946-f871-429a-a15f-226c8b847dc4.png)

**Comment by hugoabernier** [comment]
@mrivera4 were you able to resolve your issue with @Abderahman88's solution?
