### ISSUE TITLE
Search based on office location

### ISSUE THREAD

**Issue by kodalianiruddho** [pnp/sp-dev-fx-webparts#2437]
### Disclaimer

Yes

### Sample

react-directory

### Author(s)

@joaojmendes @petkir @sudharsank @Abderahman88

### Question

Hi @joaojmendes @petkir @sudharsank @Abderahman88
I tried to add Office Location in Properties to search but it's not showing any data. Please help.

Thanks 
Ani

**Comment by kodalianiruddho** [comment]
I tried to add BaseOfficeLocation in Properties to search but it's not showing any data.

**Comment by Abderahman88** [comment]
Hi @kodalianiruddho,

Have you tried the property `Location` ?

**Comment by kodalianiruddho** [comment]
@Abderahman88 
I tried with Location and also SPS-Location but no luck.

**Comment by Abderahman88** [comment]
@kodalianiruddho I think only certain properties are synced from AD to SharePoint Online.
`Location` is not one of these fields. Maybe you can use the field `Office`?

SharePoint Online User profile property | Azure Active Directory attribute
-- | --
AccountName | msonline-UserPrincipalName
ADGuid | ObjectGuid
Department | Department
FirstName | GivenName
GroupType | GroupType
IsPublic | msOnline-IsPublic
IsUnifiedGroup | msonline-groupType
LastName | sn
Manager | Manager
msOnline-ObjectId | msOnline-ObjectId
msOnline-ObjectId | msOnline-ObjectId
Office | PhysicalDeliveryOfficeName
PreferredName | DisplayName
PublicSiteRedirect | WWWHomePage
SPO-IsSPO | SPO-IsSharePointOnlineObject
SPS-ClaimID | msonline-UserPrincipalName
SPS-Department | Department
SPS-DistinguishedName | DistinguishedName
SPS-HideFromAddressLists | msExchHideFromAddressList
SPS-JobTitle | Title
SPS-MUILanguages | PreferredLanguage
SPS-RecipientTypeDetails | msExchRecipientTypeDetails
SPS-SavedSID | ObjectSid
SPS-SIPAddress | proxyAddresses
SPS-UserPrincipalName | msonline-UserPrincipalName
SPS-UserType | msOnline-UserType
Title | Title
UserName | msonline-UserPrincipalName
WorkEmail | proxyAddresses
WorkPhone | telephoneNumber

Source: https://sharepointthoughtssite.wordpress.com/2016/12/30/default-user-profile-property-mappings-for-active-directory-domain-services/
