### ISSUE TITLE
react-graph-cascading-managed-metadata - 

### ISSUE THREAD

**Issue by ChristerRussberg** [pnp/sp-dev-fx-webparts#2508]
### Disclaimer

Yes

### Sample

react-graph-cascading-managed-metadata

### Author(s)

@anoopt

### Question

Hi

I am a beginner of using spfx but I have downloaded and compiled this webpart.
I can add it on a Team site but I get error "Error retrieving termset properties. Please contact admin." even since I have followed the the required actions (adding values in Termstore).

/Christer

**Comment by anoopt** [comment]
Hi @ChristerRussberg 

I see that the `webApiPermissionRequests` are missing in the `package-solution.json` file. Sorry about that. I will submit an updated PR.

Until then, you can add the `webApiPermissionRequests` in the `package-solution.json` filr yourself and package the solution.

The web part needs read permission to the term store. So, please add `TermStore.Read.All` permission for `Microsoft Graph` resource.

```json
"webApiPermissionRequests": [
    {
      "resource": "Microsoft Graph",
      "scope": "TermStore.Read.All"
    }
  ]
````

More details on `webApiPermissionRequests` can be found [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#configure-the-api-permissions-requests).

Once packaged, you need to approve the permission request. To do that please follow the instructions mentioned [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#deploy-the-solution-and-grant-permissions).

**Comment by anoopt** [comment]
Hmm. Any helpful error logs in the browser console?

**Comment by hugoabernier** [comment]
Closing this issue due to lack of response.
