### ISSUE TITLE
unable to delete an event

### ISSUE THREAD

**Issue by saikishore-git** [pnp/sp-dev-fx-webparts#2510]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-calendar

### Author(s)

@Abderahman88, @hugoabernier, @Eli-Schei

### What happened?

Installed the React-Calendar without any issues. Added the events works fine. However, 

1) When I try to delete an event. The event is not getting deleted, and I got the below error. 
"in t in n in Styledn in t in n in Dialog in div in div in div in div in div in t in div in div in t in div in t in Styledt in span in t in CustomizedLayer in StyledCustomizedLayer in t in Styledt in div in t in div in t in t"

![image](https://user-images.githubusercontent.com/102761671/161132836-8f08d06b-1e93-442f-97de-6c3206c98b6c.png)

![image](https://user-images.githubusercontent.com/102761671/161132966-e2562478-cde4-48d1-9d95-09ccedf85f1d.png)

### Steps to reproduce

1. Add an event using react-calendar
2. Open the event by clicking on the event on the calendar 
3. Click "Delete" at the bottom of the event panel 

### Expected behavior

It should delete the event without any issue.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

√ SharePoint Framework v1.12.1
√ Node v14.18.2
√ yo v3.1.1
× gulp not found
× react v16.9.0 found, v16.9.36 required
√ bundled typescript used

**Comment by hugoabernier** [comment]
@saikishore-git Please note that you only tagged part of the authors, which significantly reduces your chances of getting someone who contributed to this sample to be able to help you with this issue.

My recommendation: close this issue and create a new one following the link at the bottom of the sample's readme. It'll automatically tag all the authors for you.
