### ISSUE TITLE
Can't correctly load Approved Libraries in "react-cherry-picked-content" sample

### ISSUE THREAD

**Issue by yomer** [pnp/sp-dev-fx-webparts#2530]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-cherry-picked-content

### Author(s)

@PathToSharePoint

### Question

After editing ApprovedLibraries.ts and starting the workbench, I can see the list of Libraries/Lists, but when I select the one which contains the source html file, a blank space is displayed in the dropdown list (last image attached).

Maybe I'm not understanding correctly how to configure the ApprovedLibraries.ts file, or I'm not adding the correct structure on my Sharepoint site.

I've tried:
- Adding an html file inside the main Site Assets library.
- Creating a SiteAssetsHTML List and adding one item with  the html as an attachment.

This is the code inside the html

```
<h1>Hola</h1>
<script>
alert("Hola");
</script>
```

What am I missing? Any help would be appreciated.

![ApprovedLibraries](https://user-images.githubusercontent.com/1246242/161802906-8177a620-c74d-4c00-aba3-a69acfe6e674.png)
![SiteContents](https://user-images.githubusercontent.com/1246242/161802947-36004461-7983-43b8-a650-58a11369fd73.png)
![SiteAssetsLibrary](https://user-images.githubusercontent.com/1246242/161803055-686e7adc-5e29-4490-9a84-fbeb5fca7f05.png)
![SiteAssetsHTML List](https://user-images.githubusercontent.com/1246242/161803071-69c83ff8-85ea-4474-b9b7-7b8be0ff4984.png)
![Workbench](https://user-images.githubusercontent.com/1246242/161803491-8ea9d7ed-9252-4a29-9c86-319c8f16756d.png)

**Comment by PathToSharePoint** [comment]
Hi @yomer ! I see "Lists" in your library path and that doesn't look right:
![image](https://user-images.githubusercontent.com/40323257/161845966-fa1c9775-fada-4194-a182-2f71f960e7d7.png)

**Comment by yomer** [comment]
@PathToSharePoint  Thanks for responding.
The first element in approvedLibraries is indeed a List. If I don't use /Lists/ I get a 404 error and a greyed out drop down list. When selecting the first element from approvedLibraries on the properties pane, I do get an enabled dropdown list, but with a blank element. If I put a second html file inside the SiteAssetsHTML List, I get two blank options.


**This is the first element with Lists in the path**

![SiteAssetsHTML List 2 htmls](https://user-images.githubusercontent.com/1246242/161893262-62f2d0cc-bfa7-46e3-8607-5a4bc9522b57.png)

**This is the result when running in the workbench**

![SiteAssetsHTML2](https://user-images.githubusercontent.com/1246242/161893264-a221cb74-362b-4bc8-b21d-87633ec94ece.png)



I've set up more approved libraries and get the same result, a blank dropdown list.


![ApprovedLibraries2](https://user-images.githubusercontent.com/1246242/161892110-d552d427-c583-4613-9a7f-b39e56a34827.png)

**Below is the fourth element in the ApprovedLibraries file**

![HTML Code Library](https://user-images.githubusercontent.com/1246242/161892114-807bd9eb-280e-4c8c-b027-779f3ad62244.png)

**And the resulting dorpdown**

![Site Assets HTML - HTML Code Library](https://user-images.githubusercontent.com/1246242/161892115-bea7c183-a4fe-4cf0-a9e4-fda79e92e598.png)

**Comment by PathToSharePoint** [comment]
You should definitely not include a list in the choices.

Could you confirm that you are testing with the online workbench, and that your libraries are in the same SharePoint Online tenant? And if so, could you share more details on your 404 error? In particular what URL it couldn't find?

**Comment by yomer** [comment]
I was getting the 404 error because the path was wrong in some of my Approved Libraries. I already removed the List and other elements which could cause a problem and left only one library.

I am testing with the online workbench and have verified that the libraries are in the same tenant and site

If I debug the code and get the filesQuery url and paste it in a new window, I do get the following XML:

`<?xml version="1.0" encoding="utf-8"?><feed xml:base="https://{REDACTED}.sharepoint.com/sites/{REDACTED}/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml"><id>5befd1ab-4f58-4ca9-95f9-2778951fde4b</id><title /><updated>2022-04-06T16:13:01Z</updated><entry m:etag="&quot;1&quot;"><id>f7a6145a-b083-4a65-ba4e-5e6c816c7274</id><category term="SP.Data.Site_x0020_Assets_x0020_HTMLItem" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="Web/Lists(guid'59a7fa8c-0600-47dc-8cab-20d1a4fc25d5')/Items(1)" /><title /><updated>2022-04-06T16:13:01Z</updated><author><name /></author><content type="application/xml"><m:properties><d:FileLeafRef>hola2.html</d:FileLeafRef></m:properties></content></entry><entry m:etag="&quot;2&quot;"><id>a65b2267-eb07-4ad3-907d-4688afc6654f</id><category term="SP.Data.Site_x0020_Assets_x0020_HTMLItem" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="Web/Lists(guid'59a7fa8c-0600-47dc-8cab-20d1a4fc25d5')/Items(2)" /><title /><updated>2022-04-06T16:13:01Z</updated><author><name /></author><content type="application/xml"><m:properties><d:FileLeafRef>hola.html</d:FileLeafRef></m:properties></content></entry></feed>` 

![ApprovedLibrariesFinal](https://user-images.githubusercontent.com/1246242/162020489-6a2e3e7b-9d1f-4146-8c37-baaa49eaf013.png)
-----------------------------------
![AsyncLibraryQuery](https://user-images.githubusercontent.com/1246242/162020494-bbfd201c-ba37-435f-937e-ad017798be75.png)

-----------------------------------------------------------------------

![GulpServe](https://user-images.githubusercontent.com/1246242/162020497-ae02201e-2ac0-41f4-83fc-5ceb43ba3ec1.png)

-----------------------------------------------------------------------

![Libraries](https://user-images.githubusercontent.com/1246242/162021806-5228ac77-59c3-450b-ba2b-308591d88cb0.png)

------------------------------------------------------------

![Site Assetts HTML Final](https://user-images.githubusercontent.com/1246242/162020507-3ce788f9-0051-4107-8276-9030af144fe9.png)

--------------------------------------------

![OnlineWorkbench](https://user-images.githubusercontent.com/1246242/162021379-fd608e8e-e204-4265-9a63-1778520c63d9.png)

-----------------------------------------------

![HTML Code Library Prop Pane](https://user-images.githubusercontent.com/1246242/162020501-16b7ffb8-6cde-4f8c-9190-10ad627afedb.png)

--------------------------------------------

![HTML Code Library Blank Files](https://user-images.githubusercontent.com/1246242/162020499-5f3ca659-18c3-469f-942d-5a7e08340bed.png)

**Comment by PathToSharePoint** [comment]
@yomer I think I found the issue. There are two locations that update the dropdown, and when I updated the code I forgot about the second one.
Please try this:  in CherryPickedContentWebPart.ts, replace the if statement at line 148 with this:
```
          if (files.length) {
            // store items
            this.libraryItemsList = files.map(file => file.FileLeafRef)
              .filter(rf => rf.match(/\.(htm?l|txt)$/i))
              .sort()
              .map(name => ({ key: name, text: name }));
            // enable item selector
            this.itemsDropdownDisabled = false;
            // refresh the item selector control by repainting the property pane
            this.context.propertyPane.refresh();
          }
```

**Comment by yomer** [comment]
@PathToSharePoint Yes, that did it! Thanks a lot.

The test in the workbench was a success, so I'll be packaging and uploading it hopefully tomorrow.

I'll be on watch for any extra updates you make just in case. Are you going to be updating both your github and the sample on this pnp repo at the same time?

**Comment by PathToSharePoint** [comment]
@yomer The goal is to have the same version on both. But the PnP workflow is not controlled by me and can take up to a couple weeks.
Glad to hear it's working! I'll submit the update soon.

**Comment by PathToSharePoint** [comment]
@yomer I just submitted the pull request. I would recomment to test and use v0.4.1 (also published in my repo), which has another update in addition to the bug fix. Happy to assist if you run into any issues.
