### ISSUE TITLE
Unable to build react-accordion-with-richtext

### ISSUE THREAD

**Issue by agaskelluk** [pnp/sp-dev-fx-webparts#2600]
### Disclaimer

Yes

### Sample

react-accordion-with-richtext

### Author(s)

@arunkumarperumal

### What happened?

Can't complete npm install:

[       ...........] \ postinstall: sill install executeActions

It hangs here for ages then I get:

npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\agaskell\AppData\Roaming\npm-cache\_logs\2022-04-13T15_23_09_528Z-debug.log

I don't see anything useful in the log file. 

### Steps to reproduce

1. Clone or download source
2. nvm use 14.18.3
3.  npm install

### Expected behavior

npm install completes successfully.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.13.1
√ Node v14.18.3
√ yo v4.3.0
√ gulp v4.0.2
√ bundled typescript used

**Comment by arunkumarperumal** [comment]
@agaskelluk looks like the issue is with your node version. Try removing the package-lock.json file on your local version and then run npm install

**Comment by arunkumarperumal** [comment]
Can you share the versions of node you have tried and also the SPFx versions?

**Comment by arunkumarperumal** [comment]
Works for me for both node v12.13.0 and v12.22.1. I don't think node v14 works with 1.13.1. I generally use v12.13.0 for spfx 1.13.1

**Comment by arunkumarperumal** [comment]
@agaskelluk, works for me after removing the node_modules and package-lock.json with node v14.18.3. See below screenshot. 

![image](https://user-images.githubusercontent.com/39132298/163309952-2829882a-04bf-4023-bcb6-611729e4efa7.png)

**Comment by agaskelluk** [comment]
@arunkumarperumal Thank-you so much for taking the time to respond.
I managed to get it working using node 14.18.3 and spfx 1.13.1.

I removed the contents of node_modules and removed package-lock.json. I then ran npm install and all was well.

I have installed the webpart on my test tenant and its very impressive. I love it! Copy paste rtf works like a charm. 

Keep up the good work.
