### ISSUE TITLE
react-faqs adding a new item flow seems counter productive

### ISSUE THREAD

**Issue by ronkochanowski** [pnp/sp-dev-fx-webparts#2602]
### Disclaimer

Yes

### Sample

react-faqs

### Author(s)

@arunkumarperumal

### What happened?

When adding a new item, the plus sign, at the far right, is grayed out. This prevents adding more than one item at a time. The only way to add additional items is to select 'save and close', then re-configure the faqs to add another.

### Steps to reproduce

1. Configure Faqs
2. Add a new  faq
3. Cannot add more than one at a time, the plus sign is grayed out
4. Save and close
5. start over

### Expected behavior

Be able to click the plus sign at the far right and add multiple faqs at one time.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

When I try to run, `m365 spfx doctor -o json`, I get:
Error: The output option only accepts the type 'text'

**Comment by arunkumarperumal** [comment]
This is more an issue with Propertfieldcollection data. Check link for more details : [PnP so properly controls issue](https://github.com/pnp/sp-dev-fx-property-controls/issues/446) 

One change you can try us by making the ruch text field not required.

**Comment by hugoabernier** [comment]
@ronkochanowski did @arunkumarperumal 's response help you resolve this issue?

I'll go ahead and mark this issue as closed. If you need more help, please open a new issue and we'll go form there
