### ISSUE TITLE
react-birthdays - 

### ISSUE THREAD

**Issue by comigit1** [pnp/sp-dev-fx-webparts#2626]
### Disclaimer

Yes

### Sample

react-birthdays

### Author(s)

@smaity @joaojmendes

### Question

Hello,
I have followed the instructions and I built/installed successfully the webpart in SPO site collection(communication site).
I have created the list and approved the API in SPO admin center.
I have added one record with the columns according to your req, however I see the webpart empty inside the SPO page.
I use the NodeJS  12.13.0 & SPFX  1.14
Can you please advice why I cant see the cards inside the webpart.

**Comment by Abderahman88** [comment]
Hi @comigit1, 

What do you see now? Is it an error?

Important remark : the list **needs** to be created on your rootsite.

### Example
![image](https://user-images.githubusercontent.com/36161889/167701342-6a540560-ce22-4b8d-823c-3f9cd9160506.png)

![image](https://user-images.githubusercontent.com/36161889/167701525-c6cbc565-de19-41ba-b428-b11d7c12c327.png)

**Comment by Abderahman88** [comment]
@comigit1 Do you still have issues?

**Comment by comigit1** [comment]
Yes :( , as I mentioned in the previous email the default year is 2000 inside your code. So right now the only workaround for me to display birthdays is to use the 2000 as the current year. :) Could you fix this?. I use the Birthday list in SPO root site.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>

Ilias Ntokos

Senior Sharepoint Developer
Filotheis 12 Galatsi, Greece

T +30 210 2134644<tel:+30%20210%202134644>
E ***@***.******@***.***>

www.mitsishotels.com<https://www.mitsishotels.com/>


[https://www.mitsishotels.com/emails/social/email_facebook.png] <https://service.mitsishotels.com/social/redirect/facebook/GAA>         [https://www.mitsishotels.com/emails/social/email_instagram.png]  <https://service.mitsishotels.com/social/redirect/instagram/GAA>      [https://www.mitsishotels.com/emails/social/email_twitter.png]  <https://service.mitsishotels.com/social/redirect/twitter/GAA>  [https://www.mitsishotels.com/emails/social/email_youtube.png]  <https://service.mitsishotels.com/social/redirect/youtube/GAA>  [https://www.mitsishotels.com/emails/social/email_linkedin.png]  <https://service.mitsishotels.com/social/redirect/linkedin/GAA>        [https://www.mitsishotels.com/emails/social/email_blog.png] <https://service.mitsishotels.com/social/redirect/blog/GAA>




[https://www.mitsishotels.com/emails/logos/GAA.jpg]<https://www.mitsishotels.com/>


[https://cdn.mitsishotels.com/images/emails/create_your_own_story_gold.jpg]<https://www.mitsishotels.com/?utm_source=email&utm_medium=banner&utm_campaign=signature_site>





[https://cdn.mitsishotels.com/images/gifs/email_signatures_jan_v2.gif]<https://www.mitsishotels.com/?utm_source=email&utm_medium=banner&utm_campaign=signature_site>



This message (including any attachments herein) is exclusively intended for the named addressees and contains information which is privileged, confidential or protected by Law. If you are not an authorized addressee or have received this email in error, promptly notify the sender, delete it immediately and refrain from disseminating, distributing, copying or making any other use of it for any purpose, since all such acts are strictly prohibited. Our operation and any rights and remedies thereof are governed by and construed in accordance to Greek Law.
Fraud scam reminder: This is a reminder that Mitsis Hotels does not communicate changes to bank details or payment methods through Email. If you ever receive an Email that makes this request, please call your existing sales or customer service representative to verify any changes. Mitsis Hotels Group values your business and wants to ensure a safe transaction.

________________________________
From: Abderahman Moujahid ***@***.***>
Sent: Friday, May 13, 2022 10:48:33 PM
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: Ilias Ntokos | Mitsis Group IT ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [pnp/sp-dev-fx-webparts] react-birthdays - (Issue #2626)


CYBER SECURITY WARNING: This email is from external source - be careful of attachments and links. Please follow the Cyber Code and report suspicious emails.



@comigit1<https://github.com/comigit1> Do you still have issues?

**Comment by comigit1** [comment]
Hello,
I don’t see any error i just see an empty webpart. ( i have added the list in root site).
however, I realized that inside the code under services directory you have hardcoded the year to “2000”. So when i changed my list birthday date to 2000 year then I was able to see the upcoming birthdays. So the question is how to manage and fix the year from 2000 to 2022-2023 etc….
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>

Ilias Ntokos

Senior Sharepoint Developer
Filotheis 12 Galatsi, Greece

T +30 210 2134644<tel:+30%20210%202134644>
E ***@***.******@***.***>

www.mitsishotels.com<https://www.mitsishotels.com/>


[https://www.mitsishotels.com/emails/social/email_facebook.png] <https://service.mitsishotels.com/social/redirect/facebook/GAA>         [https://www.mitsishotels.com/emails/social/email_instagram.png]  <https://service.mitsishotels.com/social/redirect/instagram/GAA>      [https://www.mitsishotels.com/emails/social/email_twitter.png]  <https://service.mitsishotels.com/social/redirect/twitter/GAA>  [https://www.mitsishotels.com/emails/social/email_youtube.png]  <https://service.mitsishotels.com/social/redirect/youtube/GAA>  [https://www.mitsishotels.com/emails/social/email_linkedin.png]  <https://service.mitsishotels.com/social/redirect/linkedin/GAA>        [https://www.mitsishotels.com/emails/social/email_blog.png] <https://service.mitsishotels.com/social/redirect/blog/GAA>




[https://www.mitsishotels.com/emails/logos/GAA.jpg]<https://www.mitsishotels.com/>


[https://cdn.mitsishotels.com/images/emails/create_your_own_story_gold.jpg]<https://www.mitsishotels.com/?utm_source=email&utm_medium=banner&utm_campaign=signature_site>





[https://cdn.mitsishotels.com/images/gifs/email_signatures_jan_v2.gif]<https://www.mitsishotels.com/?utm_source=email&utm_medium=banner&utm_campaign=signature_site>



This message (including any attachments herein) is exclusively intended for the named addressees and contains information which is privileged, confidential or protected by Law. If you are not an authorized addressee or have received this email in error, promptly notify the sender, delete it immediately and refrain from disseminating, distributing, copying or making any other use of it for any purpose, since all such acts are strictly prohibited. Our operation and any rights and remedies thereof are governed by and construed in accordance to Greek Law.
Fraud scam reminder: This is a reminder that Mitsis Hotels does not communicate changes to bank details or payment methods through Email. If you ever receive an Email that makes this request, please call your existing sales or customer service representative to verify any changes. Mitsis Hotels Group values your business and wants to ensure a safe transaction.

________________________________
From: Abderahman Moujahid ***@***.***>
Sent: Tuesday, May 10, 2022 9:53:51 PM
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: Ilias Ntokos | Mitsis Group IT ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [pnp/sp-dev-fx-webparts] react-birthdays - (Issue #2626)


CYBER SECURITY WARNING: This email is from external source - be careful of attachments and links. Please follow the Cyber Code and report suspicious emails.



Hi @comigit1<https://github.com/comigit1>,

What do you see now? Is it an error?

Important remark : the list needs to be created on your rootsite.

Example

[https://user-images.githubusercontent.com/36161889/167701342-6a540560-ce22-4b8d-823c-3f9cd9160506.png]<https://user-images.githubusercontent.com/36161889/167701342-6a540560-ce22-4b8d-823c-3f9cd9160506.png>

[https://user-images.githubusercontent.com/36161889/167701525-c6cbc565-de19-41ba-b428-b11d7c12c327.png]<https://user-images.githubusercontent.com/36161889/167701525-c6cbc565-de19-41ba-b428-b11d7c12c327.png>
