### ISSUE TITLE
react-photo-sync - 

### ISSUE THREAD

**Issue by HaidariHammad** [pnp/sp-dev-fx-webparts#2646]
### Disclaimer

Yes

### Sample

react-photo-sync

### Author(s)

@sudharsank

### Question

Great article, one thing that I would like to address, it would have been wonderful if you demonstrated the Azure PnP PowerShell section and shared the PnP script to get and update the UPS. It is missing in the video or in the repository.

**Comment by gretchunkim** [comment]
@HaidariHammad Here's a video that help me how this is possible (in spfx):

  https://www.youtube.com/watch?v=BaNWS0hzUpQ
