### ISSUE TITLE
react-list-search - Columns fixed width

### ISSUE THREAD

**Issue by Luckylex78** [pnp/sp-dev-fx-webparts#2657]
### Disclaimer

Yes

### Sample

react-list-search

### Author(s)

@albegut

### Question

Hi,
I try to sort my Data in a SharePoint List with the react-list-search. 
Problem is, that the columns are all in a different width. I want them in one line and i can´t manage to do so. 

Its like this:
![image](https://user-images.githubusercontent.com/104627210/165948308-61ccebd4-ae93-4f51-9dd6-04395fe6a22d.png)

And it should look like this:
![image](https://user-images.githubusercontent.com/104627210/165948454-a68cbd7e-c66c-444a-8151-48a88d628a7b.png)

Even when I activate the "Indivitual column filter" it appears like in my first example. 
Any Ideas?

**Comment by albegut** [comment]
Hi @Luckylex78 sorry for the late answer. I've could reproduce the problem and I've found a solution

The problem it's in the configuration of the column width at the "Display fields" configuration. If you enter the min and max column width the component don´t render correctly. 

![Error](https://user-images.githubusercontent.com/9661096/172563463-fbecd2bc-f395-417f-a9c7-15bc854160f9.PNG)



If you enter only the max width the problem it's solved. I'll check if it's problem of this component or the problem it's in one of the subcomponents used in the development.
![CorrectConfiguration](https://user-images.githubusercontent.com/9661096/172563727-4979c956-7a0e-450b-ac1e-563bfa826184.PNG)

![image](https://user-images.githubusercontent.com/9661096/172563794-f9857ebc-3d41-4455-85bb-265dcb48cd52.png)

If you have any other problem or question, please let me know

Thank you in advance!
