### ISSUE TITLE
Missing IGitHubUserProfile file in the  code repository

### ISSUE THREAD

**Issue by gretchunkim** [pnp/sp-dev-fx-webparts#2691]
### Disclaimer

Yes

### Sample

Attempting to use it as an example for mock data service and notice the source code file IGitHubUserProfile is missing entire file under src/services/GitHubServices in which it's file existence is referenced in total of seven different places. 
![missing](https://user-images.githubusercontent.com/8564035/166049071-172c2059-6e45-43d7-9601-d7c90fa7cddc.PNG)

### Author(s)

Hugo Bernier; Eric Skaggs
@skaggej @hugoabernier 

### What happened?

Attempting to use it as an example for using mock data service and notice a referencing file missing entire file under src/services/GitHubServices in which it's file existence is referenced in total of seven different places. 

### Steps to reproduce

1. Go to src/services/GitHubServices 
2. Look for IGitHubUserProfile.ts in the folder. 
3. Confirm it's missing where as code is being referenced  in seven different places. 

### Expected behavior

Expect to see IGitHubUserProfile.js in src/services/GitHubServices. 

-BTW, blog article listed in readme is no longer valid: https://tahoeninjas.blog/2019/04/19/converting-spfx-from-javascript-to-react/

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [X] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

n/a as no SPFX doctor issue-  simply missing the actual file in the repository. 

### Additional environment details

using spfx 1.14 with node 14.

**Comment by gretchunkim** [comment]
Github-actions: if author is missing how could I have posted the comment since isn't it required field based on the form validation...?

**Comment by hugoabernier** [comment]
@gretchunkim imports can point to a file or a folder, provided that the folder has an `index.ts` in the root of that folder.

This is what is happening here. 

You can find the class you're looking for at https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-github-badge/src/services/GitHubServices/GitHubService.ts
