### ISSUE TITLE
Unable to delete a calendar entry

### ISSUE THREAD

**Issue by hawaiianmetal** [pnp/sp-dev-fx-webparts#2693]
### Disclaimer

Yes

### Sample

react-calendar 

### Author(s)

@Abderahman88, @Eli-Schei, @mohammadamer, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### What happened?

You are unable to delete an event (simple or recurring) from any calendar. This is a duplicate of #2510. When trying to delete, instead of seeing the confirmation dialog, you get this error message:

in t in n in Styledn in t in n in Dialog in div in div in div in div in div in t in div in div in t in div in t in Styledt in span in t in CustomizedLayer in StyledCustomizedLayer in t in Styledt in div in t in div in t in t

The error message occurs within the control that should open for delete confirmation. Note that changing the code to bypass the confirmation (change onclick event in event.tsx line 520 from this.onDelete to this.confirmDelete successfully removes the item, but it is not desirable to remove the confirmation check. Thus, the problem is not deleting the item, but simply having the dialog. I messed with the code a while but couldn't find a fix. Maybe it's a conflict with the dialog showing within the panel?

![react-calendar-screenshot1](https://user-images.githubusercontent.com/11828453/166290324-6a3d5bd2-00e3-483b-b686-35da7d66aca2.jpg)

### Steps to reproduce

1. Download sample
2. npm install
3. gulp build, gulp bundle, gulp package-solution
4. Add and deploy .sppkg to appcatalog in SPOL
5. Add web part to page
6. Connect to calendar
7. Create event and then try to delete it.

### Expected behavior

The confirmation dialog should display and after confirming, the item should delete.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

√ SharePoint Framework v1.12.1
√ Node v14.15.5
√ yo v3.1.1
√ gulp v4.0.2
× react v16.9.0 found, v16.9.36 required
× typescript v3.2.4 installed in the project

### Additional environment details

As recommended by Hugo from my previously logged issue #2658, I downgraded Node.js to v 14.15.5. I've re-opened this because the problem still occurs.

**Comment by Abderahman88** [comment]
@hawaiianmetal I'll take a look at it

**Comment by hawaiianmetal** [comment]
Any update on this item? This should be an easy fix for someone familiar with the code.

**Comment by hawaiianmetal** [comment]
Reopening. Didn't mean to close.

**Comment by mohammadamer** [comment]
Hi @hawaiianmetal 

I tried the Calendar WebPart in my local machine, and I got issue with deleting events. The error is different but still there is an issue with delete events. I'm working on fix it. @hugoabernier please assign it to me.

![image](https://user-images.githubusercontent.com/19314043/197360462-a529c566-150f-42ae-9ddc-60cf88cc9ee4.png)

**Comment by mohammadamer** [comment]
Hi @Abderahman88 
So sorry, I haven't noticed that it's assigned to you.
Have you investigated the issue or do you have the same issue.

**Comment by Abderahman88** [comment]
@mohammadamer I've just created a PR for this problem. Thank you for the support.
