### ISSUE TITLE
react-tree-orgchart - How to use filter

### ISSUE THREAD

**Issue by FMC-gclifford** [pnp/sp-dev-fx-webparts#2696]
### Disclaimer

Yes

### Sample

react-tree-orgchart

### Author(s)

@joaojmendes @petkir

### Question

I'm trying to understand how to use the Filter in this webpart.  If I want to exclude users who have a username of a or b how would I do this?

if I type in a then it will filter out a, but unclear how to filter out a AND b.  I've tried using the word OR and also tried delimiters like comma, pipe, semicolon.

![image](https://user-images.githubusercontent.com/70153952/166938204-4c844883-ef0a-4ec9-adac-71c65df87745.png)

**Comment by petkir** [comment]
Hi @FMC-gclifford 

Thanks for your question.

the logic behind is very simple.
1. the filter  has to be set
2. the value of the filter has to be (or not) in the userPrincipalName (upn).

The use case was to filter accounts out of the result list (srv_.....) as far I remember. i think it was #1727.


exclude
```
user.userPrincipalName?.toLowerCase().indexOf(filter.toLowerCase()) === -1
```
include:
```
user.userPrincipalName?.toLowerCase().indexOf(filter.toLowerCase()) !== -1
```


Feel free to improve it ;-) 

contributions are welcome

**Comment by FMC-gclifford** [comment]
Hello,

so it sounds like I cannot do something like userprincipalname=user1 OR userprincipalname=user2 .  Is that correct?

**Comment by petkir** [comment]
Hi @FMC-gclifford ,

yes, it's correct.
But you can extend the web part with your imagine of a dynamic filter option  :-)

currently I don't have a quick fix in my head for a dynamic filter
