### ISSUE TITLE
react-follow-document - Web part loading forever and JS error in the console

### ISSUE THREAD

**Issue by Maya-Mostafa** [pnp/sp-dev-fx-webparts#2700]
### Disclaimer

Yes

### Sample

react-follow-document

### Author(s)

@aaclage

### What happened?

When the user doesn't have followed documents, to begin with, the web part keeps loading forever and there is a script error appears in the console. Once there are followed documents, it works fine.

### Steps to reproduce

1. Unfavorite all your documents
2. Reload the page holding the web part
3. Loading forever with an error in the console.

### Expected behavior

There should be a notification message appearing informing the user that there are no-followed items, instead of the infinite preloader.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.12.1
√ Node v12.22.10
√ yo v3.1.1
√ gulp v4.0.2
√ bundled typescript used

**Comment by aaclage** [comment]
@Maya-Mostafa thank you for reporting will give a look.

**Comment by aaclage** [comment]
Hi @Maya-Mostafa,

You are free to include the fixes/improve in spfx dev webparts repo, this is open to the community :) i only started the webpart

**Comment by Maya-Mostafa** [comment]
Sure, I will submit a PR :)

**Comment by aaclage** [comment]
@Maya-Mostafa 

And thank you helping the community and for improving with this new great features/corrections :)

Great contribution.
