### ISSUE TITLE
react-carousel - 

### ISSUE THREAD

**Issue by kireetijs** [pnp/sp-dev-fx-webparts#2703]
### Disclaimer

Yes

### Sample

react-carousel

### Author(s)

@joaojmendes @rahulsuryawanshi @DonKirkham @Harshagracy @giuleon

### Question

How can i make the image is clickable. I created a new column type hyperlink. Is it possible to add this column value as href to image so that it can be clickable?
Thank you in advance for help

**Comment by Abderahman88** [comment]
Hi @kireetijs,

Yes, this is possible. Some changes need to be made in the code.

1) Create a hyperlink column (for example LinkUrl)
2) spservices.ts --> Add `LinkUrl ` in `getImages`
![image](https://user-images.githubusercontent.com/36161889/167932319-da7c453a-22b4-411f-8919-ae4994ef23a6.png)
3) Carousel.tsx --> Add `LinkUrl ` to garryImages array
![image](https://user-images.githubusercontent.com/36161889/167932793-9c42d181-9163-4f64-af47-a74db812cd9a.png)
4) Carousel.tsx --> Add OnClick-event on Image
![image](https://user-images.githubusercontent.com/36161889/167933084-39f4d4d2-1d27-4038-a54b-ca96fc29402d.png)
5) Carousel.tsx --> Add function to redirect to URL
![image](https://user-images.githubusercontent.com/36161889/167933334-a41d1b64-72e0-4a95-857d-ef22d6c27353.png)


You can test these changes on my repo:
https://github.com/Abderahman88/sp-dev-fx-webparts/tree/patch-2703

**Comment by kireetijs** [comment]
Thank you so much for quick response and help. I will make those changes.
Best regards,
kireeti
________________________________

**Comment by kireetijs** [comment]
It works perfectly. Thank you very much for making the enhancements very quick. But it is not showing the hand cursor like a link when I put the cursor on the image. Should i add anything to css file to show picture is an hyperlink when i put the cursor?
Thank you for all your help

**Comment by Abderahman88** [comment]
@kireetijs

This is a way to get the desired output.

1) Add css class (Carousel.module.scss)
![image](https://user-images.githubusercontent.com/36161889/168154320-efe709d0-fd92-41bf-9682-8a5ed53c159b.png)

2) Add the class to the Image control.
![image](https://user-images.githubusercontent.com/36161889/168154262-5beb0182-4f4c-463d-9cd6-7c2e2ec824b6.png)

These changes will show a hand cursor if a link is present.

**Comment by kireetijs** [comment]
You are the best. Thank you so much.
Best regards
Kireeti

Sent from my iPhone

On May 12, 2022, at 2:39 PM, Abderahman Moujahid ***@***.***> wrote:

﻿

@kireetijs<https://github.com/kireetijs>

This is a way to get the desired output.

  1.  Add css class (Carousel.module.scss)
[image]<https://user-images.githubusercontent.com/36161889/168154320-efe709d0-fd92-41bf-9682-8a5ed53c159b.png>

  2.  Add the class to the Image control.
[image]<https://user-images.githubusercontent.com/36161889/168154262-5beb0182-4f4c-463d-9cd6-7c2e2ec824b6.png>

These changes will show a hand cursor if a link is present.

**Comment by Abderahman88** [comment]
@kireetijs My pleasure. Can you close this issue?

**Comment by kireetijs** [comment]
Thank you for all the enhancements.
