### ISSUE TITLE
react-global-news - 

### ISSUE THREAD

**Issue by blaired** [pnp/sp-dev-fx-webparts#2704]
### Disclaimer

Yes

### Sample

react-global-news

### Author(s)

@joaojmendes

### Question

Can this be used for news created in SharePoint or is there another solution like this but just for SPO?

**Comment by joaojmendes** [comment]
Hi,

No, you can’t , use specific API  (https:/newsapi.org) to get news from RSS feeds.

Thanks.

From: Mike Blair ***@***.***>
Date: Wednesday, 11 May 2022 at 11:49
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: [pnp/sp-dev-fx-webparts] react-global-news - (Issue #2704)
Disclaimer

Yes

Sample

react-global-news

Author(s)

@joaojmendes<https://github.com/joaojmendes>

Question

Can this be used for news created in SharePoint or is there another solution like this but just for SPO?
