### ISSUE TITLE
Can we add locale files in .json format instead of .js format?

### ISSUE THREAD

**Issue by v-ashrirao** [pnp/sp-dev-fx-webparts#2705]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-teams-message

### Author(s)

Microsoft

### Question

Is it possible to have locale files in .json format instead of .js format??

**Comment by Abderahman88** [comment]
@v-ashrirao Do you mean translation files?

**Comment by v-ashrirao** [comment]
@Abderahman88, Yes

**Comment by Abderahman88** [comment]
No
