### ISSUE TITLE
react-birthdays - 

### ISSUE THREAD

**Issue by CIsakN** [pnp/sp-dev-fx-webparts#2709]
### Disclaimer

Yes

### Sample

react-birthdays

### Author(s)

@smaity @joaojmendes

### What happened?

The Webpart displays next 5 birthdays but not from todya, instead it looks like its from 01-01-2022

### Steps to reproduce

1.setup application
2.add user data 
3.View Webpart

### Expected behavior

todays date is 18-05-2022(Danish format, but also tried En-US) and it shows the 5 i Jan who have birthdays and not the real upcomming

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

dont have time or skills sorry

### Additional environment details

![bug](https://user-images.githubusercontent.com/24935475/169141647-8f617f10-06dc-4fe1-ba98-eff25c53a577.jpg)

Its Online

**Comment by Abderahman88** [comment]
Hi @CIsakN,

I tested this webpart out and I agree there are some faulty date calculations.

Can you tell me:
1) What version of this webpart are you using?
2) Can you give some example Birthday dates you are using? I'm interested in the year you are inputting in the list.
(f.e. Do you input 18/05/2022 or 18/08/1978?)
