### ISSUE TITLE
react-page-navigator - Leading space in heading causes incorrect navigation link

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#2715]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-page-navigator

### Author(s)

@Jwaegebaert

### What happened?

@Jwaegebaert ,
I created this as a separate issue from https://github.com/pnp/sp-dev-fx-webparts/issues/2698 because that issue has pull request and notes saying they will be closed and I didn't want it to get lost.

In our real life testing using the updates talked about a couple weeks ago, we found the current scenario where the links in the web part do not match the page.

On the one hand, I think this may only encourage the end user to be a little sloppy and where do you draw the line.  On the other hand, it is different than OOTB SharePoint link so I wanted to at least report it.

## Issue description -

If you have a **heading that starts with spaces**, the regex adds a single hypen to the front of the #hash link.
SharePoint however does not have a leading hash.  I have not tested but it may also trim trailing ones just to keep things clean.

So in the case of my screenshot, url the web part takes me to is 
#-6.3.3.-impairment-test - page-navigator link
#6.3.3.-impairment-test  - ootb SharePoint link
(Note, I could not find a way to remove the link to that issue and keep the actual example)

It might be easier to just clean up any leading hyphens than build it into a single regex if SharePoint always does that.

Anyway, thanks for your efforts to date, this was a great example and really does work nice!

![image](https://user-images.githubusercontent.com/49648086/170116767-6593d068-0899-4cb8-aa7c-efab6a796272.png)

### Steps to reproduce

1. Create a heading link that starts with spaces

### Expected behavior

The web part should take you to the correct #link 

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

I'm not on a computer that can run SPFx doctor at the moment.

**Comment by mikezimm** [comment]
## Confirmation that trailing heading spaces add extra hypen to #link making it not work

![image](https://user-images.githubusercontent.com/49648086/170121018-d7433168-bfe0-48e5-8507-711e0d7f1709.png)

**Comment by Jwaegebaert** [comment]
Wow, another great catch @mikezimm. If we take a look at all the issues that are occurring, we can conclude that the regex approach to create an anchor link isn't the most efficient way. To avoid all complex scenarios, we need to refactor the function a bit. Here it will be easier that we use the `id` attribute directly within the header tag and not the innerHTML value. 

![afbeelding](https://user-images.githubusercontent.com/38426621/170215057-ec88080f-a365-46ae-9483-ee96fbc0d678.png)

What do you think about this?

**Comment by mikezimm** [comment]
@Jwaegebaert ,
To be honest, I never really knew much about the header feature until I came across a scenario that had a migrated classic site with a editor web part that I wanted to get rid of.

So I don't know how it all works or what the id would do.

What would you propose?

**Comment by mikezimm** [comment]
@Jwaegebaert ,
I was just doing a little more testing with some common and uncommon characters...

# Tested these type of headings and here are some results:

## Does Not work:  SharePoint removes leading/trailing hyphens:
--- Starts with hyphen
Ends with hypen ---

## Does NOT work:  SharePoint KEEPS !Exclaimation Points!! but regex removes them:
Ends with Exclaimation point!

## Does work - SharePoint and regex keep and use ; and :
This is heading with colon:
This is heading with semi-colon;

**Comment by Jwaegebaert** [comment]
No problem, I will try to redesign a few parts within the code. All of the samples you gave, I can use them within the testing.

**Comment by mikezimm** [comment]
For my case, I may just daisy chain onto your original regex because it's a little more readable....

I replaced the first regex line:
Was
.replace( [^a-zA-Z0-9.,()\-& ]/g , "")

Is now - to keep the !
.replace( [^a-zA-Z0-9.,()!\-& ]/g , "")


To trim leading and trailing hyphens (after all other substitutions), I added this as a new replace before the toLowerCase():
.replace( /^\-*|\-*$/g , "")

## Final result:
    let anchorUrl = `#${headingValue
      .replace(/[^a-zA-Z0-9.,()!\-& ]/g, "")
      .replace(/\'|\?|\\|\/| |\&/g, "-")
      .replace(/--+/g, "-")}
      .replace( /^\-*|\-*$/g , "") //This line must be last to clean up any leading-trailing -
      `.toLowerCase();
