### ISSUE TITLE
react-page-info:  capability to find collapsible section headers

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#2772]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-page-navigator

### Author(s)

@Jwaegebaert

## Add capability to collapsible accordions in modern pages

@Jwaegebaert , I was showing off my web part to someone today and came across this potential improvement.

I noticed when you create collapsible sections, it creates a heading navigation link like regular headings but the web part does not pick it up.

Full disclosure, I think my code is one iteration behind your latest but I think the result will be the same.

If your not familiar with the feature, create a new section, edit section and you can make it collapsable.
When you do that it gives you a new heading element where you can put a label.

## Here's a screenshot of a typical collapsable section html
![image](https://user-images.githubusercontent.com/49648086/172656101-f8b43fb1-4966-41b1-8679-d96b72fa108d.png)

### Are you willing to help?

Yes

**Comment by Jwaegebaert** [comment]
Well caught @mikezimm. This won't be the simplest feature to implement. Currently the page navigator looks purely at the content of the canvas and the collapsible section is nested at a higher level than the canvas content. This will make it difficult to retrieve but I will look into it and see what is possible. 😄

**Comment by Jwaegebaert** [comment]
Pardon me for the late response, just found a way to check if a section has a collapsible header and fetch the related title. I will create a PR shortly so you can see what adjuments had to be made to make this possible.
