### ISSUE TITLE
SharePoint Online error after React-Page-Navigator web part upload Original error: Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version "16.14.0".

### ISSUE THREAD

**Issue by ElephantLathe** [pnp/sp-dev-fx-webparts#2778]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-page-navigator

### Author(s)

@aakashbhardwaj619   hugoabernier

### What happened?

After uploading to SharePoint Online app store and placing the Page Navigator web part on a page I get this error. The same happens in Gulp Serve. I'm a SharePoint Admin who wants to extend some features, not a developer and this is my first attempt to package a webpart from the code, so my lack of full understanding may have a bearing on this. I have spent quite a few hours trying to work it through and troubleshooting before reaching out though.

[SPLoaderError.loadComponentError]:
Failed to load component "bcac4d9d-adf5-4462-97c5-e5f3e97dd518" (PageNavigatorWebPart). Original error: Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version "16.14.0".

INNERERROR:
Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version "16.14.0".
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_687b3e926fe09e98426dacac72314020.js:70:214569)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_687b3e926fe09e98426dacac72314020.js:72:7680)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_687b3e926fe09e98426dacac72314020.js:72:44944)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_687b3e926fe09e98426dacac72314020.js:72:41035)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_8ba778ca573ea69fc754.js:1:6012

### Steps to reproduce

1. Install Node.JS https://nodejs.org/download/release/v14.16.1/node-v14.16.1-x64.msi  )

2. Open node.js command prompt
3. npm install --global gulp-cli
4. Install [Git - Downloading Package (git-scm.com)](https://git-scm.com/download/win)
5. Install [GitHub CLI | Take GitHub to the command line](https://cli.github.com/)
6. Open Windows CMD prompt
7. gh auth login   
8. git clone https://github.com/pnp/sp-dev-fx-webparts.git     
9. cd sp-dev-fx-webparts/samples     --browse to the solution you want to create a package for
10. Run 'NPM Install'   called node_modules
11. Gulp bundle --ship
12. gulp package-solution --ship         
13. Upload .sppkg file in SharePoint/solution folder to SharePoint Online App store and deploy
14. Add Page Navigator app to home site
15. Add a site page with a vertical section adding text and headings on left and Page Navigator on the right

### Expected behavior

When a site page is created, and content added in a Text web part on the left with various headings, when Page Navigator web part is added to the right on a 'vertical section', a tree of content appears matching the headings

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

m365 spfx doctor -o text

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.14.0
√ Node v14.16.1
√ yo v4.3.0
√ gulp v4.0.2
√ bundled typescript used

### Additional environment details

SharePoint Online

**Comment by tor-axbit** [comment]
I got the same issue, for a previously working solution, not using PnP though:
```
[SPLoaderError.loadComponentError]:
Failed to load component "29b1dc77-a5c0-4bf3-8256-a26f033bda4a" (CarbonFootprintWebPart). Original error: Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version "16.14.0".

INNERERROR:
Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version "16.14.0".
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_14d92b4af8934fdefe8cf7f82a27b3e8.js:70:215028)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_14d92b4af8934fdefe8cf7f82a27b3e8.js:72:7680)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_14d92b4af8934fdefe8cf7f82a27b3e8.js:72:44944)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-gb_14d92b4af8934fdefe8cf7f82a27b3e8.js:72:41035)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_2b7c6d12ca54d8302d17.js:1:6012
```

**Comment by Jwaegebaert** [comment]
PR #2773 will fix your build issues. This is due to a conflict with the React version. 

> I got the same issue, for a previously working solution, not using PnP though:

I suspect the same goes for your issue @tor-axbit. Try to update the React package within your `package.json` file from `^16.14.0` to `16.13.1`.  More info about the React version compatibility can be found [here](https://docs.microsoft.com/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility).

**Comment by ravikadri** [comment]
I tried upgrading react and I still get the same issue...is there anything else i need. I did the same changes as you did in the pull request and still get the same error.

Ravi

**Comment by Jwaegebaert** [comment]
@ravikadri, you could possibly try to run `npm ci` to do a clean install of your dependencies. If this doesn't solve your issue, I would suggest to execute one of the following commands to see if they give more insight to a possible solution. `m365 spfx doctor -o text` or `m365 spfx project doctor -o text`. [More info](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-doctor/)

**Comment by ravikadri** [comment]
@Jwaegebaert , yes. It worked. Thank you for the instructions.

Thanks!
Ravi

**Comment by ElephantLathe** [comment]
Thanks so much @Jwaegebaert that has worked for me too. I found a post that made a similar suggestion, but it needed that npm ci command to get everything working properly afterwards.

**Comment by Jwaegebaert** [comment]
No problem! 😄 
Good luck with your projects @ElephantLathe and @ravikadri!
