### ISSUE TITLE
react-birthdays - 

### ISSUE THREAD

**Issue by BenVdP** [pnp/sp-dev-fx-webparts#2779]
### Disclaimer

Yes

### Sample

react-birthdays

### Author(s)

@smaity @joaojmendes

### Question

Hi,

I am curious of the webpart also can fetch birthdays from Delve? As this is where employees can state if they want to have their birthday publicly displayed or not?

**Comment by gretchunkim** [comment]
@BenVdP 
I was curious about this information as well, and noticed that user profile information is fetched all from Azure AD hence all properties in Graph user profile will be available. 

Which means, if user updated info on Delve it will be synced to user profile/Azure AD anyways. If user marked their birthday to be hidden then it won't show as a valid date on User profile.
