### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by Tochey** [pnp/sp-dev-fx-webparts#2783]
### Disclaimer

Yes

### Sample

Samples folder

### Author(s)

n/a

### Question

having an array of issues, any ideas as to why the following is happening?
![image](https://user-images.githubusercontent.com/54341970/174919713-1ea837ce-d73c-49d3-9174-7abaff3451a8.png)
![image](https://user-images.githubusercontent.com/54341970/174919735-1694ae9a-811c-4f32-8362-38a491188f78.png)

**Comment by ravikadri** [comment]
Is this related to any solution that we have in this repository? Also to speed up the responses please use the issue template to raise any issues/questions. 

If you are just looking to set up the SPFx dev environment, I suggest you start with the MS article. 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

Ravi
