### ISSUE TITLE
Accordion Site Pages Selection Issue

### ISSUE THREAD

**Issue by Goonie78** [pnp/sp-dev-fx-webparts#2792]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-dynamic-section

### Author(s)

@ejbenke @mikezimm @jyasir @AriGunawan

### What happened?

When selecting Site Pages from lists and creating the correct columns according to directions for the accordion, it will not display. Create a list and it will display. Would like to create an accordion based on the Site Pages list.

### Steps to reproduce

1. Create Columns for Site Pages List (Choice, Body,) Title is already avilable
2. Add Accordion to Page
3. Select Site Pages
4. Select Choice
5. Select Title
6. Select Body
7. Only Choice will be filled

### Expected behavior

Expect to see what we see with other lists.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

Build actually completes, but we see in debugging on the tenant possible API issues.

**Comment by AriGunawan** [comment]
Hi @Goonie78,
I've just tried to select the **Site Pages** as the list source (after creating **Category** choice column on the Site Pages list).
It works as expected on showing columns on the web part configuration panel and also showing the correct value based on the field value on the list. I'm using Title as title and content on the accordion.
![image](https://user-images.githubusercontent.com/8691985/184632916-3ec75385-c00c-4d63-bbc9-b238c6ed3e05.png)
Are you having an issue on showing the options on the web part configuration panel? Or the value from the list doesn't show up?
