### ISSUE TITLE
`react-directory` card hover and click no longer works

### ISSUE THREAD

**Issue by tamerlein** [pnp/sp-dev-fx-webparts#2801]
### Disclaimer

Yes

### Sample

react-directory

### Author(s)

@joaojmendes

### What happened?

react-directory. Hover over and clicking personas no longer does anything. Tested on multiple tenants, no console log error apart from "IDLE cookie missing", which seems to be unrelated to this issue.

### Steps to reproduce

1. gulp build
2. gulp bundle --ship
3. gulp package-solution --ship
4. deploy sppkg
5. any card does not hover now, clicking also does not bring up modal

### Expected behavior

On hover over a profile (persona) , details should expand into a persona card.
On click of a profile, a modal should appear with the details of the person and contact info.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

builds fine, error in deployment

### Additional environment details

node 10.x

**Comment by Jitenparmar** [comment]
Even I have tried on many tenants but it's not working.

**Comment by brannmar** [comment]
@Jitenparmar how did you resolve this?

**Comment by Jitenparmar** [comment]
Microsoft has changed the internal property of the Live Persona card in our code Initially we had a property upn which is now changed to legacyUpn. 

![image](https://user-images.githubusercontent.com/7124132/176952600-bff86322-f4ce-423b-8713-07c687606595.png)

Reference link:
https://github.com/pnp/sp-dev-fx-controls-react/issues/1241

**Comment by sympmarc** [comment]
Also see: https://github.com/pnp/sp-dev-fx-controls-react/issues/1241#issuecomment-1164231797

**Comment by petkir** [comment]
Thanks, @Jitenparmar can you are absolutely right, thanks for digging it out

I tested it and it was working with the old Property (upn)

But from the description, it should be ```legacyUpn```
I added it to RP #3040.

**Comment by brannmar** [comment]
Thanks!

//Johan
________________________________
Från: Marc D Anderson ***@***.***>
Skickat: Friday, July 1, 2022 8:51:01 PM
Till: pnp/sp-dev-fx-webparts ***@***.***>
Kopia: Johan Brännmar ***@***.***>; Comment ***@***.***>
Ämne: Re: [pnp/sp-dev-fx-webparts] `react-directory` card hover and click no longer works (Issue #2801)


Also see: pnp/sp-dev-fx-controls-react#1241 (comment)<https://github.com/pnp/sp-dev-fx-controls-react/issues/1241#issuecomment-1164231797>
