### ISSUE TITLE
react-page-navigator: Collapsible heading issues with naming and order

### ISSUE THREAD

**Issue by Jwaegebaert** [pnp/sp-dev-fx-webparts#2805]
### Disclaimer

Yes

### Sample

react-page-navigator

### Author(s)

@aakashbhardwaj619, @Jwaegebaert

### What happened?

Issues originates from @mikezimm 
- https://github.com/pnp/sp-dev-fx-webparts/pull/2804#issuecomment-1171752184

----

Yet again, @mikezimm did some great extensive research & testing onto the new feature that's available on the webpart `react-page-navigator`. A few issues originated from this testing.

#### 1# - Retaining collapsible headings when the collapsible section has been turned off

If you make a section collapsible, then give it a 'name' and settings, then toggle 'collapsible' section off, it retains the properties I set (like the section name) and they still show up in the Navigator as a heading.

#### 2 # - Collapsible sections without a name

If you create a collapsible section without giving it a name, the navigator does not find any navigation tags at all.
The reason for that is because 'headingValue' in GetAnchorUrl is undefined and errors out on the .toLowerCase() line in the regex. To fix that, just set 'headingValue' to a default value like 'Empty Heading' if it is undefined. NOTE if you do that, it will show as a heading in the Navigator web part but you will not be able to click on it since the tag does not exist.

#### 1# - Retaining collapsible headings when the collapsible section has been turned off

- Create a collapsible section with a name and few settings.
- Toggle the collapsible section off

#### 2 # - Collapsible sections without a name

- Create a collapsible section without a name

#### 1# - Retaining collapsible headings when the collapsible section has been turned off

The removed collapsible section shouldn't be visible anymore

#### 2 # - Collapsible sections without a name

WebPart should catch this error.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

``` text
CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.14.0
√ Node v14.18.1
× yo not found
× gulp not found
√ bundled typescript used

Recommended fixes:

- npm i -g yo@4
- npm i -g gulp@4
```

**Comment by Jwaegebaert** [comment]
Do you have an idea maybe to why it's rendering two `Collapsed Expandel section`?

![afbeelding](https://user-images.githubusercontent.com/38426621/176865643-bf892531-c1f6-4520-a3b5-81c89a8b4c6f.png)

**Comment by mikezimm** [comment]
@Jwaegebaert ,
I spent a good hour or more just stepping through the console etc but could not explain that one.
My web part is slightly different, so I can't totally exclude that the issue could be there.  But I am reusing your sample for all the core logic of getting the links.

I could create an account for you on my dev tenant and give you access to my test site?  Then you could gulp-serve your web part on the same page.  Might be worth it.

Then again, some things may just not be worth the effort.

For instance, the other question about turning on collapsible headings, set properties and then disable them.

In those cases, it might be better to just have a disclaimer and recognize that is a limitation.

**Comment by Jwaegebaert** [comment]
Fair point @mikezimm. The reason why I asked the question was mainly because of curiosity and so I could possibly replicate it.

> In those cases, it might be better to just have a disclaimer and recognize that is a limitation.

We could indeed add it as a limition but I'm gonna dubble check if there's anyway way we can avoid this scenario. 😄 
So I will do some testing, and come back to you when I find out more.

**Comment by Jwaegebaert** [comment]
Hi @mikezimm, after a lot of brainstorming, I've found a way to tackle several of the current bugs. I was able te reproduce the bug you had that several links are created for a single collapsible heading. The PR with a work around has been created for it. Hope this helps 😄
