### ISSUE TITLE
react-script-editor - 

### ISSUE THREAD

**Issue by MeShare115** [pnp/sp-dev-fx-webparts#2807]
### Disclaimer

Yes

### Sample

react-script-editor

### Author(s)

@wobba 

### What happened?

I am using script editor in modern SharePoint page and adding responsive HTML . HTML is referring CSS from SharePoint style library. The HTML is rendering fine for me one time . If I change anything in custom CSS file it is not reflecting in the page . 

Also what I am getting the look and feel from HTML, for my colleagues they are getting some older referred HTML/CSS. It's not changing for everyone  .All users are having access and page is published . Please suggest .

### Steps to reproduce

1. Change CSS and save in style library
2.  Refresh the page where script editor is added.

### Expected behavior

Page should reflect the updated CSS for all users.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

NA

**Comment by wobba** [comment]
Where are you storing your css file and how are you loading it? Seems to be client caching from what you describe. If the web part is used one place you could always drop the CSS into the web part instead.

**Comment by MeShare115** [comment]
Sure I will try with Site Assets and let you know the results.

**Comment by MeShare115** [comment]
Hi @wobba, Just to inform you I have tried putting the files in Site Assets but still browser is caching the files and changes are not reflecting not only for CSS but also for images.
Also one more question I am sharing the pages to external guest users but script editor is throwing error from them. I have gone through some blogs where it is mentioned to enable App Catalog for them . Can you please assist on this too.

**Comment by wobba** [comment]
@MeShare115 see @LauraKokkarinen awesome post about getting web parts to work for external users https://laurakokkarinen.com/sharepoint-online-guest-user-troubles-and-how-to-get-past-them/#custom-share-point-apps-dont-load-for-guest-users-by-default
