### ISSUE TITLE
Issue cloning React-Directory

### ISSUE THREAD

**Issue by joshburns49** [pnp/sp-dev-fx-webparts#2808]
### Disclaimer

Yes

### Sample

React-Directory

### Author(s)

@petkir_at @sudharsank

### What happened?

Cloned repo, tried npm install and get the following error

npm ERR! code 1
npm ERR! path C:\users\me\Documents\sp-dev-fx-webparts-main\samples\react-directory\node_modules\deasync
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\method4.la\AppData\Local\Temp\install6572539.cmd
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.15.1 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\Documents\\sp-dev-fx-webparts-main\\samples\\react-directory\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\users\me\Documents\sp-dev-fx-webparts-main\samples\react-directory\node_modules\deasync
npm ERR! gyp ERR! node -v v16.15.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\method4.la\AppData\Local\npm-cache\_logs\2022-07-06T12_20_22_219Z-debug-0.log

### Steps to reproduce

1.clone repo
2.npm install

### Expected behavior

install node modules and dependencies successfully

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

PS C:\Users\me\Documents\sp-dev-fx-webparts-main\samples\react-directory> m365 spfx doctor     
m365: The term 'm365' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by Jwaegebaert** [comment]
Hi @joshburns49. The sample `React-Directory` makes use of SPFx v1.10. To build solutions in this version you will [Node v10](https://docs.microsoft.com/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility). Currently, you're using Node v16.15.1

**Comment by joshburns49** [comment]
Thanks @Jwaegebaert, see below.

ERROR: npm is known not to run on Node.js v10.24.1
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/

Cheers

Josh

**Comment by Jwaegebaert** [comment]
Mmh, that's annoying ofcourse.

Could you possible give this a try https://stackoverflow.com/questions/71956940/error-npm-is-known-not-to-run-on-node-js-v10-24-1-and-how-to-fix-it-dont-updat

**Comment by Jwaegebaert** [comment]
Don't forget to reboot your computer after installing node. That's something that can help 😄

**Comment by Jwaegebaert** [comment]
Another thing that's good to double check, is to see if Nodejs has been linked to you environment variables.

**Comment by hugoabernier** [comment]
@joshburns49 did you try moving the folder where you want to clone to a shorter path? Like `c:\spfx`

**Comment by DonKirkham** [comment]
@joshburns49 Were you able to get this to work? I use nvm to hot-swap NodeJS versions (which includes npm). I installed NodeJS v10.24.1 and everything worked normally.

Please respond so we can continue helping you or resolve the issue!  Thanks!
