### ISSUE TITLE
Sections are not included in the PageNavigator

### ISSUE THREAD

**Issue by xLyxx** [pnp/sp-dev-fx-webparts#2809]
### Disclaimer

Yes

### Sample

react-page-navigator

### Author(s)

@xLyxx

### What happened?

The section name is not taken over in the page navigator

### Steps to reproduce

1. The page navigator must be added
2. Create a Section
3. Then the SharePoint page must be published

(Now the section name is not entered in the page navigator)

### Expected behavior

That the section name is entered in the page navigator and the section name serves as H1

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

√ SharePoint Framework v1.9.1
√ Node v10.24.1
× yo not found
× gulp not found
√ bundled typescript used
 
Recommended fixes:

- npm i -g yo@3
- npm i -g gulp@3

**Comment by xLyxx** [comment]
Hello @Jwaegebaert, yes exactly the one I mean.

**Comment by Jwaegebaert** [comment]
Then I would suggest trying to use the latest version. This is a feature that recently was implemented in the sample 😄 

[Version history](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-page-navigator#version-history)

**Comment by Jwaegebaert** [comment]
No problem 😄 
Good luck with the implementation.
