### ISSUE TITLE
react-accordion-dynamic-section - not get it working

### ISSUE THREAD

**Issue by florianbommarius** [pnp/sp-dev-fx-webparts#2814]
### Disclaimer

Yes

### Sample

react-accordion-dynamic-section

### Author(s)

@mikezimm @jyasir @AriGunawan

### Question

Hi Dear Community,

I'm about to freak out! Sorry! I've been working frustrated for days and weeks on the simple walk-through:
download zip sample
extract
npm install
gulp serve

But nothing works! I've been digging through hundreds of forum posts, going from error message to error message. It started with incomplete tools and setups, missing SharePoint framework.
After I had also worked through the instructions, I worked my way from downgrade to downgrade with very many error messages.
In the end I compiled the sample with a NodeJS 8.14, an ancient npm-5, and the rest was also old.
But it still didn't work: the WebPart was empty!

Now I'm running in circles:
With NodeJS 16 (and SharePoint Framework 1.15 https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility) it tells me:
spfx Error: Your dev environment is running NodeJS version v16

(Further it says in the error message that it should be between 10.13 and <11.0).

When I downgrade to v12, I always get the same error message.
And with NodeJS v10.24, npm then tells me: 
npm is known to not work with NodeJS v.10.24

Now I'm stuck!
After so many hours upon hours and reading and trying around, I don't get what I'm doing wrong.

The base I tried to orient myself to:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
https://sharepointstuff.com/2019/06/17/how-to-deploy-spfx-sample-webparts/
https://sharepointstuff.com/2019/02/04/how-to-provision-and-deploy-the-sharepoint-starter-kit-part-one/

**Comment by florianbommarius** [comment]
Hi everyone, colleagues of me, who where able to compile this package some years ago, experience the same problem right now. Currently it seems for us impossible to get this example code running.

**Comment by AriGunawan** [comment]
Hi @florianbommarius, I've just reinstalled the app from scratch and it's working as expected so far.
![image](https://user-images.githubusercontent.com/8691985/184629838-85c881f6-9ef3-4006-aabb-04e0c9a7d7da.png)

Please follow the Compatibility information from the [readme](https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-accordion-dynamic-section/README.md): 
![image](https://user-images.githubusercontent.com/8691985/184629763-2e359a1d-e867-4049-9677-2aaffdaa5e19.png)
This sample is using SPFx 1.10 that compatible with node v.10.
I'm using node v10.20.1 when reinstalled this today.

Please try again with correct node version and make sure to install the node correctly.
Your error message `npm is known to not work with NodeJS v.10.24` seems weird to me as every node version should also install the npm for it. You might not install the node correctly.
My suggestion is to use the [nvm (node version manager)](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows) if you want to have multiple node version in your local machine.
