### ISSUE TITLE
react-page-sections-navigation - 

### ISSUE THREAD

**Issue by blogmom** [pnp/sp-dev-fx-webparts#2816]
### Disclaimer

Yes

### Sample

react-page-sections-navigation

### Author(s)

@AJIXuMuK

### What happened?

Unfortunately, this web part does not appear in the list of web parts that can be added to a page.  It does not show up.

### Steps to reproduce

1. Create a new page, add a web part, and in the list of possible web parts, this one just is not there.
2. Confirmed that the app has been added to the Site, In fact, "Monitor" shows no errors with it.
3. Just cannot add it to a page, because it is not listed as a web part.  Help.  This looks like such an awesome web part, I was so excited to use it.

### Expected behavior

Well, just expected it to appear as an available web part that can be added to a page.  

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

I dd not think this was applicable because it compiled perfectly fine.

**Comment by mohammadamer** [comment]
Hi @blogmom,

I have tried to build and debug this webpart and it worked well with in my development environment
What node JS version are you using?
Are you trying to add it locally if so, please try to add it to different site.


![image](https://user-images.githubusercontent.com/19314043/194860916-595b80a5-7e63-4824-a56b-6ddc77fc043e.png)

**Comment by blogmom** [comment]
I don't know what happened, but the web part suddenly started appearing after a few months of posting this.  I am able to add it to pages.  Must have been something in our tenant.  I apologize for any inconvenience caused by this bug report.
