### ISSUE TITLE
Not able to download zip file. Folder unavailable when cloned from Github

### ISSUE THREAD

**Issue by MCSDaspirant** [pnp/sp-dev-fx-webparts#2833]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/e1e1921323dbba636228a453f1dca5ce4f959987/samples/react-tabacordion

### Author(s)

Arun Kumar Perumal
@arunkumarperumal 

### What happened?

Unable to download the zip file of react-tabacordion code as mentioned on the page. It also doesn't appear under the list of folders when cloned, 

### Steps to reproduce

1. Cloned https://github.com/pnp/sp-dev-fx-webparts/ on desktop
2. Navigated to Samples folder
3. Could not locate React-TabAcordion folder 

1. Navigated to https://github.com/pnp/sp-dev-fx-webparts/tree/e1e1921323dbba636228a453f1dca5ce4f959987/samples/react-tabacordion and scrolled down to Instructions under "Minimal path to awesome"
2. Clicked on the link provided  to download this solution as a .ZIP file (https://pnp.github.io/download-partial/?url=https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-tabaccordion).
3. No files to download error message

### Expected behavior

Expected to see a zip file or locate it in the samples cloned folder

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

Cannot do this step because folder cannot be located

**Comment by arunkumarperumal** [comment]
@MCSDaspirant Seems like you are referring to the wrong path for the code. You should always use the main branch. react-tabaccordion was renamed to react-accordion-with-richtext. Use the below link to access the sample code.

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-with-richtext
