### ISSUE TITLE
react-company-stories - 

### ISSUE THREAD

**Issue by minhphuc2k21** [pnp/sp-dev-fx-webparts#2916]
### Disclaimer

Yes

### Sample

react-company-stories

### Author(s)

@luismanez

### Question

Hi. After i add web part to sharepoint it shows error Something went wrong then i go to see detail: 
[SPLoaderError.loadComponentError]:
Failed to load component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Manifest not found for component id "78b11c7d-7ca8-47cb-a93c-d3beabb519a1" and version "2.4.0".
INNERERROR:
Manifest not found for component id "78b11c7d-7ca8-47cb-a93c-d3beabb519a1" and version "2.4.0".
Could you help me fix it
Thank you
![webpartstories](https://user-images.githubusercontent.com/86236803/180631896-95c0249e-6f9e-48a0-a127-127cd919a060.png)

**Comment by luismanez** [comment]
This is an issue with the Graph Toolkit (mgt-spfx). Have you deployed the ```@microsoft/mgt-spfx``` package first to your AppCatalog?

Have a look to this link:
https://docs.microsoft.com/en-us/graph/toolkit/get-started/mgt-spfx

it says:
> Before deploying your SharePoint Framework package to your tenant, you will need to deploy the @microsoft/mgt-spfx SharePoint Framework package to your tenant. You can download the package corresponding to the version of @microsoft/mgt-spfx that you used in your project, from the [Releases](https://github.com/microsoftgraph/microsoft-graph-toolkit/releases) section on GitHub.

Hope it helps.
