### ISSUE TITLE
react-company-stories - 

### ISSUE THREAD

**Issue by minhphuc2k21** [pnp/sp-dev-fx-webparts#2918]
### Disclaimer

Yes

### Sample

react-company-stories

### Author(s)

@luismanez

### Question

Hi.Could you help me fix it. It doesn't show stories but only login accounts.

![sharepointstories](https://user-images.githubusercontent.com/86236803/181036219-9fec4ee8-7fb3-4762-8f2c-47feeb06e3bb.png)

**Comment by luismanez** [comment]
Have you created the SharePoint list with the Stories content, as specified in the readme.md file? Can you open DevTools and see if there´s any issue with the Requests in the Network tab? Also, you need to configure Permissions to MS Graph, did you do it? (more info in the readme file too)

**Comment by minhphuc2k21** [comment]
I have done everything but still not working. 
![sharepoint2](https://user-images.githubusercontent.com/86236803/181136360-43540dd9-47bd-4ec9-85ef-7edce366e188.png)
![sharepoint1](https://user-images.githubusercontent.com/86236803/181136362-cc9fafe2-fc6b-4f39-b7d8-599e5f45d928.png)

**Comment by minhphuc2k21** [comment]
I don't know what's wrong with it. 

![webpart-stories-console](https://user-images.githubusercontent.com/86236803/181199323-3ab62a92-5ab0-4f0f-bf70-2329abfa8499.png)
![webpart-stories-network](https://user-images.githubusercontent.com/86236803/181199335-3e6ec87d-c485-4899-b10b-c838e5f131e6.png)

**Comment by luismanez** [comment]
This is weird. One of the first things the webpart does, is to call SP REST API to get the items from the Stories list ```/_api/web/lists/GetByTitle('Stories')/RenderListDataAsStream```, but I don´t see that call in your Network trace. I suggest you to run the webpart locally from the SP Workbench, and try to debug the code using the _Sources_ tab in DevTools.
