### ISSUE TITLE
Recat-directory not working 

### ISSUE THREAD

**Issue by Shravansahi** [pnp/sp-dev-fx-webparts#2925]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-directory

### Author(s)

@petkir_at

### What happened?

Unable to use react Directory webpart i have installed node v10 as the spfx version is 1.11.o but i receive the error npm is known not to run on Node.js v10.24.1

### Steps to reproduce

Clone the react directory,
Install node v10
npm install

### Expected behavior

it should install he node modules to the directory but i receive error

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

m365 spfx doctor

╭───────────────────────────────────────────────╮
│ │
│ Update available 5.4.0 → 5.5.0 │
│ Run npm i @pnp/cli-microsoft365 to update │
│ │
╰───────────────────────────────────────────────╯

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

× SharePoint Framework

Error: SharePoint Framework not found

**Comment by Jwaegebaert** [comment]
Hi @Shravansahi, when executing the command `npm install` is your terminal in the webpart directory? 

To dubble check it, you can execute `ls` which would then display the following:

![afbeelding](https://user-images.githubusercontent.com/38426621/183427479-78326924-2e06-4d8b-aaa5-8fc368952886.png)

**Comment by petkir** [comment]
@Shravansahi 

works like expected

**Comment by DonKirkham** [comment]
@Shravansahi Were you able to get this to wor? I use nvm to hot-swap NodeJS version (which includes npm.)  I installed NodeJS v10.24.1 and everything worked fine.  

Please respond so we can continue helping you or resolve (i.e., close) this issue
