### ISSUE TITLE
react-page-navigator - 

### ISSUE THREAD

**Issue by StefanGebhardtAtBeca** [pnp/sp-dev-fx-webparts#2929]
### Disclaimer

Yes

### Sample

react-page-navigator

### Author(s)

@aakashbhardwaj619

### What happened?

Hi,
We are interested in using the page navigator webpart but we came across an issue and one suggestion for an inprovement...

Issue: 
The web part does not work for us if we don't use collapsable sections on a page. As soon we add collapsable sections it is working as adverised. Is there a chance to look into this issue, please?

Suggestion:
The background color of the content displayed in the web part is fixed white. Is there a chance to make the background transparent or to let the user select the background color? We are normally adjusting the background color on the right hand side and noticed this 'shortcoming'

Thanks in advance,
Stefan
<img width="1668" alt="Screenshot 2022-08-11 at 00 31 16" src="https://user-images.githubusercontent.com/111023793/184032322-b1c8dcce-4882-430c-93a9-5ae8d50f3ec3.png">
<img width="1668" alt="Screenshot 2022-08-11 at 00 33 42" src="https://user-images.githubusercontent.com/111023793/184032331-7ddb3a8e-2313-4ed1-81b6-76019d85df54.png">
n

### Steps to reproduce

1. Create new page (without collapsable sections)
2. Add headings
3. Publish the page
4. Web part stays blank

### Expected behavior

Table of contens will be displayed for standard pages using headings

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.14.0
√ Node v14.20.0
√ yo v4.3.0
√ gulp v4.0.2
√ bundled typescript used

**Comment by Jwaegebaert** [comment]
Hey @StefanGebhardtAtBeca, thanks for creating this issue. These are both issues that should get resolved within the sample. For your suggestion to let the users pick the background color, I think it will be more interesting if the WebPart would adjust itself towards the current theme variant. This is something that can easily be achieved with the SPFx `ThemeProvider`.

I'll create a PR shortly that will resolve these issues. Hope this will help. 😄

**Comment by StefanGebhardtAtBeca** [comment]
Hi Jasey,
Thanks for the feedback. We are looking forward to your update and appreciate your quick response. And yes I agree with your comment about the background color adjusting to the current theme variant.
Take care,
Stefan

On 17. Aug 2022, at 13:42, Jasey Waegebaert ***@***.***> wrote:

﻿

Hey @StefanGebhardtAtBeca<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStefanGebhardtAtBeca&data=05%7C01%7Cstefan.gebhardt%40beca.com%7Cd4ac64883703499d66df08da80458292%7Cbb0f7126b1c54f3e8ca12b24f0f74620%7C0%7C0%7C637963333282436209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0IcEyXaO%2FN1%2B3Iug7nbJRJZ4mQluxSlMepS1V9CvKPI%3D&reserved=0>, thanks for creating this issue. These are both issues that should get resolved within the sample. For your suggestion to let the users pick the background color, I think it will be more interesting if the WebPart would adjust itself towards the current theme variant. This is something that can easily be achieved with the SPFx ThemeProvider.

I'll create a PR shortly that will resolve these issues. Hope this will help. 😄

—
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpnp%2Fsp-dev-fx-webparts%2Fissues%2F2929%23issuecomment-1217898378&data=05%7C01%7Cstefan.gebhardt%40beca.com%7Cd4ac64883703499d66df08da80458292%7Cbb0f7126b1c54f3e8ca12b24f0f74620%7C0%7C0%7C637963333282592094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mEQUvsGZpweeg7Nas1kS%2BTUnQMvI1HdRqsMbE9rrReo%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2PBNML7T7LZYMVII5Z4CX3VZTFYXANCNFSM56HBU76Q&data=05%7C01%7Cstefan.gebhardt%40beca.com%7Cd4ac64883703499d66df08da80458292%7Cbb0f7126b1c54f3e8ca12b24f0f74620%7C0%7C0%7C637963333282592094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=66RVJS6ZitTjllldZlfDNc59Ng2B69WSaUud8ZI3TPE%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

NOTICE: This email, if it relates to a specific contract, is sent on behalf of the Beca company which entered into the contract. Please contact the sender if you are unsure of the contracting Beca company or visit our web page http://www.beca.com for further information on the Beca Group. If this email relates to a specific contract, by responding you agree that, regardless of its terms, this email and the response by you will be a valid communication for the purposes of that contract, and may bind the parties accordingly. This e-mail together with any attachments is confidential, may be subject to legal privilege and applicable privacy laws, and may contain proprietary information, including information protected by copyright. If you are not the intended recipient, please do not copy, use or disclose this e-mail; please notify us immediately by return e-mail and then delete this e-mail.
