### ISSUE TITLE
React-list-form failing to render rich text editor control when the page is toggled Edit/Republish

### ISSUE THREAD

**Issue by utsavsth** [pnp/sp-dev-fx-webparts#2932]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-list-form

### Author(s)

@DanyWyss 
@Harshagracy 
@sharepointknight 
@Abderahman88 
@Kman1131 

### What happened?

When using a New and Edit Form Type, the rich text editor does not render the control when you edit the form. Moreover, this behaviour is consistent when you republish the form.
![image](https://user-images.githubusercontent.com/18415966/185025110-ffd16479-083b-4c3d-b458-46de8d13e840.png)

I have configured the field as multi-line which allow rich text as below.
![image](https://user-images.githubusercontent.com/18415966/185025443-aff3a709-4731-4c07-abcf-58bbae0f82c7.png)

If I refresh the page it renders the rich text editor correctly.
![image](https://user-images.githubusercontent.com/18415966/185025888-b4b0e1ef-65c4-443f-b4d9-8fa61d231790.png)

### Steps to reproduce

1. Create a List and add a field of type multi-line allowing rich text.
2. Add the react-list-form web part.
3. Select the list.
4. Check if the multi-line field not rendering the rich text editor.

### Expected behavior

The rich text editor should render correctly.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

![image](https://user-images.githubusercontent.com/18415966/185029340-08486563-b6b2-459d-b33f-5910bfc380d2.png)

**Comment by utsavsth** [comment]
@DanyWyss @Harshagracy @sharepointknight

**Comment by sharepointknight** [comment]
Let me see if I can duplicate this issue.
