### ISSUE TITLE
Problems with adding third party JavaScript Snippet

### ISSUE THREAD

**Issue by Martin-125** [pnp/sp-dev-fx-webparts#2936]
### Disclaimer

Yes

### Sample

react-script-editor

### Author(s)

Mikael Svenson

### Question

Hi guys, 

we have a problem with adding a third party JavaScript Snippet from Job Searching site. It has worked before in SharePoint OnPrem and now we are trying to get it to work on SharePoint Online. The snippet can be found here: https://concludis.atlassian.net/wiki/spaces/WIKI/pages/16634190/Integration+per+JavaScript+Snippet (german)

```
> <script type="text/javascript">
> (function(a,b,c,d,e,f,g){a[d]=a[d]||function(){(a[d].q=a[d].q||[]).push(arguments)},a[d].host=e;
> f=b.createElement(c),g=b.getElementsByTagName(c)[0];f.defer=true;
> f.src='//'+e+'/bewerber/jobportal.js';g.parentNode.insertBefore(f,g);
> })(window,document,'script','concludis','kunde.concludis.de');
> concludis('setMainContainer', 'concludis_kunde_stellenangebote');
> //concludis('scrollOnLoad', 'container' oder 'top');
> //concludis('setJobBoard', '1');
> //concludis('setLanguage', 'en_GB');
> //concludis('setIntern', '1');
> //concludis('setCountry', 'DE');
> //concludis('setState', 'NW');
> //concludis('setProvince', '05315|05334');
> //concludis('setCity', '10|4');
> //concludis('setJobGroup1', '4|5');
> //concludis('setJobGroup2', '1');
> //concludis('setJobGroup3', '2');
> //concludis('setCompany', '7');
> //concludis('setSeniority', '6');
> //concludis('setClassification', '5');
> //concludis('setSchedule', '4');
> //concludis('setCategory', '3');
> //concludis('setYearsOfExperience', '2');
> //concludis('setRegion', '1');
> //concludis('setRadiusZip', '12345');
> //concludis('setRadiusKm', 50);
> </script>
> <div id="concludis_kunde_stellenangebote">Job board is loading ...</div>
```

The script editor otherwise works fine, just with this script nothing is happening. Maybe one of you has a solution or can guide me in the right way.

**Comment by Abderahman88** [comment]
Hi @Martin-125,

I've tried the Javascript outside SharePoint and I can't get it working.
This is not SP specific. I think they've changed something.

**Comment by hugoabernier** [comment]
Unfortunately, this can't be fixed due to recent changes to SharePoint. Will add notes to the README indicating so
