### ISSUE TITLE
Web part should stay align with anchor navigations.

### ISSUE THREAD

**Issue by koppele2005** [pnp/sp-dev-fx-webparts#2956]
### Disclaimer

Yes

### Sample

react-page-navigator

### Author(s)

NA

### Suggestion

Awesome web part but I wish after I click on links in the web part , web part still be in the view. I dont have to scroll up to start again. It will be very helpful if you can implement that feature. 

### Are you willing to help?

Yes

**Comment by ssocias** [comment]
Agreed! This would be very helpful!
