### ISSUE TITLE
Clicking on the 'my teams' button make the webpart invisible

### ISSUE THREAD

**Issue by MoeIcI** [pnp/sp-dev-fx-webparts#3032]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-groups-teams

### Author(s)

@SamC148 @ReactIntern

### What happened?

The Button for Micrsosoft 365 Groups works perfectly fine.
The other button makes the webpart invisible. It's not crashing (according to the monitored details for the app). After reloading the page with this webpart, its visible again, but clicking the 'My Teams' Button makes it disappear again.

I'm running these tests on a tenant provided by the developer program

![example](https://user-images.githubusercontent.com/108660028/190958930-35ac4978-ade2-41e1-ba86-ed86802480b9.gif)

### Steps to reproduce

1. Clone the repo
2. install dependencies (including some fixed due to the sample's age)
3. gulp bundle & package-solution
4. Adding to app catalog
5. approving the requested API permission
6. putting the webpart on a site.

### Expected behavior

Running the webpart as shown in the sample's page.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

√ SharePoint Framework v1.12.1
√ Node v14.19.3
√ yo v3.1.1
√ gulp v4.0.2
√ bundled typescript used

**Comment by mohammadamer** [comment]
Hi @MoeIcI 
I tried to add the webpart in dev Tenant, but it worked fine.
Could you please send a screenshot of the console of your browser after the webpart becomes invisible.

**Comment by MoeIcI** [comment]
Hi @mohammadamer 

I tried it in my dev tenant again, but still the same results.
Here is a screenshot in my console:

![Screenshot](https://user-images.githubusercontent.com/108660028/194810050-61ae6cbf-0775-4134-bd17-bcda8c1afdf3.png)

It seems to be this part, but I don't know how to deal with that:
`{this.state.MyGroupsresultsFiltered.map(Team => {
          Team.Visibility = Team.Visibility.substr(0, 1).toUpperCase() + Team.Visibility.substr(1);
          var GroupEmailSplit = Team.Mail.split("@");
          var Mail = GroupEmailSplit[0];
          return (
            <div className={styles.rowStyle}>
              <div className={styles.ToolTipName}>{Team.Name}<span className={styles.ToolTip}>{Team.Description}</span></div>
              <a className={styles.Center} href={`https://outlook.office.com/mail/group/${this.TenantEmail}/${Mail.toLowerCase()}/email`}>
                <Icon className={iconClass} style={{ color: '#087CD7' }} iconName="OutlookLogo"></Icon></a>
              <a className={styles.Center} href={`https://${this.TenantPathname}/sites/${Mail}`}>
                <Icon className={iconClass} style={{ color: '#068B90' }} iconName="SharePointLogo"></Icon>
              </a>
              <a className={styles.Center} href={`https://outlook.office.com/calendar/group/${this.TenantEmail}/${Team.Name.replace(Replaceregex, '')}/view/week`}>
                <Icon className={iconClass} style={{ color: '#119AE2' }} iconName="Calendar"></Icon>
              </a>
              <div className={styles.Center}>
                {Team.Planner === undefined ? <div></div> : <a href={Team.Planner}>
                  <Icon className={iconClass} style={{ color: '#077D3F' }} iconName="ViewListTree"></Icon>
                </a>}
              </div>
              <a className={styles.Center} href={`${Team.WebUrl}`}>
                <Icon className={iconClass} style={{ color: '#424AB5' }} iconName="TeamsLogo"></Icon>
              </a>
              <div className={styles.Center} style={{ borderRight: 'none' }}>{Team.Visibility}</div>
            </div>
          );`
          
          Thanks for helping me out! I appreciate it!

**Comment by mohammadamer** [comment]
Hi @MoeIcI 
Thanks for the info. Ok, let me double check this part of the code.
