### ISSUE TITLE
react-directory - Issue with worker_threads

### ISSUE THREAD

**Issue by eprach** [pnp/sp-dev-fx-webparts#3039]
### Disclaimer

Yes

### Sample

react-directory

### Author(s)

@joaojmendes, @Abderahman88, @sudharsank, @petkir

### What happened?

Hi Team!

First of all, thanks for your great work!

I would like to test the react-directory webpart but get an issue when trying to run gulp build

`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\atc\Documents\Projects\PNP_SPFX\pnpSPFX\sp-dev-fx-webparts\samples\react-directory\node_modules\@rushstack\worker-pool\lib\WorkerPool.js:6:26)                                                                                                                          pool\lib\WorkerPool.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

spfx doctor looks good.

Did I miss something or is there an issue with this webpart?

If I did something wrong, would it be possible to share the .spkg file directly?

### Steps to reproduce

1. Clone the repo
2. npm i
3. gulp build

### Expected behavior

I expect to be able to run gulp and package the webpart as it is

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

√ SharePoint Framework v1.11.0
√ Node v10.24.0
√ yo v3.1.1
√ gulp v3.9.1
√ bundled typescript used

**Comment by petkir** [comment]
Hi @eprach 

i checked out the repo

changed to the folder to  ```/samples/ react-directory```
```

npm i
gulp build
gulp bundle --ship
gulp package-solution --ship
```
all working as expected

My environment
```nvm use v10```

**Comment by petkir** [comment]
@eprach 

I build it locally and via DevOps Pipeline cannot find an error.
I have pushed the sppkg file to your Repo.
what you can also try is to build it in a docker image.
https://hub.docker.com/r/waldekm/spfx/

**Comment by eprach** [comment]
Very interesting, I didn't know this docker image for SPFx!

Thanks a lot for your help, I will close the ticket!

**Comment by cfinnberg** [comment]
@petkir @joaojmendes 

Sorry to bump, but I have the same problem with different samples I'm trying. I tried the docker images (waldekm/spfx and also m365pnp/spfx) but I get same results. Actually in the docker image SPFx doctor does not like that docker is installed globally (but I can't uninstall it)

SPFx doctor output in docker image (m365pnp/spfx:1.11.0):
```
✔ SharePoint Framework v1.11.0
✔ Node v10.22.0
✔ yo v3.1.1
✖ gulp should be removed
✖ gulp-cli not found
✔ bundled typescript used
```

In my own system SPFx doctor passes, but I still get the worker_threads error:
```
✔ SharePoint Framework v1.11.0
✔ Node v10.24.1
✔ yo v3.1.1
✔ gulp-cli v2.3.0
✔ bundled typescript used
```

**Comment by Spaider** [comment]
Also getting hard times trying to build samples: switching between node versions v10 and v12 and succeed only for quite a few samples. Every node.js version fails at different stages with different errors. One of them for node v10 is exactly this "Error: Cannot find module 'worker_threads'".

**Comment by kee23** [comment]
For me, the fix is to use node v16.13.0. With this version, I can run both 'npm i' and 'gulp build' without any errors.

**Comment by petkir** [comment]
@Spaider 

can you write me which samples have this problem too?
with a new installed environment i can reproduce this error

**Comment by petkir** [comment]
I found the problem

short explanation dev-tool in different versions

![image](https://user-images.githubusercontent.com/13123689/197257171-196701dc-9da9-4820-8f78-b15c7575e27e.png)

![image](https://user-images.githubusercontent.com/13123689/197257559-a3dacb27-ff69-4fb2-a87f-d6db89853d1f.png)

**Comment by Spaider** [comment]
> I found the problem
> 
> short explanation dev-tool in different versions

I am trying to build `react-adaptive-cards-image-gallery` and this sample already has package versions you specified. Still no luck with node.js versions 10, 12, and 14 :(

**Comment by petkir** [comment]
Hi @Spaider 

for ```react-adaptive-cards-image-gallery```  please try:
package.json set the version 1.10.0

```
 "@microsoft/sp-build-web": "1.10.0",
 "@microsoft/sp-webpart-workbench": "1.10.0",
```

delete ```package-lock.json``` file  and delete  the ```node_modules``` folder
use node 10 

```npm i```

will work

**Comment by Spaider** [comment]
Many thanks, @petkir, this helped!
I wonder, if there's a way to discover, which recipe will work for which sample?

**Comment by petkir** [comment]
@Spaider

A security fix broke some dependencies. I think in some days it is repaired.
