### ISSUE TITLE
I would like to request an app from samples

### ISSUE THREAD

**Issue by Genti81** [pnp/sp-dev-fx-webparts#3053]
### Disclaimer

Yes

### Sample description

Dear SPFX/PnP team

I am working on a solution for client and they request is to change their entire tenent env. font style and size to specific values. I came accross a specific app on your site here on github. The app I am aiming for is:
 **react-add-js-css-ref**, where it references from (https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-add-js-css-ref). I have tried to use this in 2 ways and it still fail to run on workbench.

1. The first one is going through the Readme guide from https://github.com/pnp/sp-dev-fx-webparts and following all the steps until executing 'gulp serve'. It is there where I get an error. See image "webpart - react-add-js-css-ref".
<img width="1088" alt="webpart - react-add-js-css-ref" src="https://user-images.githubusercontent.com/24244509/195347377-70720f72-736d-4df7-8086-2e23aabed723.png">

I have tried many ways to solve this but has been time consuming actually. I need help with this to make this run.

2. I want to run the sample (or samples) from Docker Desktop and I start with to clone the solution and I go to the sample in this case is the "react-add-js-css-ref" I want to test.
I open the sample on VS Code and after I get prompted "Reopen in Container" I click on the button and It opens. So far so good. It runs and installes the dependences see image "react-add-js-css-ref - run in Container".
<img width="484" alt="react-add-js-css-ref - run in Container" src="https://user-images.githubusercontent.com/24244509/195354708-53777193-993b-442f-ba5b-6c2505718469.png">

 During this process installing the dependecies it skips some steps like installing the cert and this is where i get stuck.
I have tried to update node, run "gulp trust-dev-cert" and then gulp serve. I have tried to run locally "gulp trust-dev-cert". Nothig works.
Keep in mind that I have already executed "gulp trust-dev-cert" earlier on my local machine and have already tried some getting started tutorials for Web Parts and Extentions from Vesa Juvonen. Great tutorials by the way!

The other issue is that the node is outdated and has version 10 installed from the host. Node needs to be updated between version >=12 and < 13 from host for this sample. I cannot update node neither run the command 'gulp serve'

============================================================================
Other issues I have found from samples folder are that some samples (apps) runs good without any issues meaning it sets up dependencies and installs cert, and some other samples fails during the installment of the dependencies.

I need assistans and guide to set this up. I would be very happy to make this work because I love working with SPFX and SharePoint. Also I follow you monthly on Youtube channel for PNP SharePoint. 

### SPFx version

1.15.2

### Are you willing to help?

Yes

**Comment by bcameron1231** [comment]
1. The first error is likely because you are using the wrong version of node. That sample is using SPFx 1.9.1 which required Node v8 or Node v10. If you are unable to install lower versions of node on your machine, but still want to use this sample, you could update the solution yourself (or request someone in the community to update, but this could take time). O365 CLI has some very helpful commands to guide you through the upgrade. https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade/

2. I would check out @DonKirkham 's blog about using SPFx with Docker. You may find some helpful information especially in regard to setting up certs. https://www.donkirkham.com/blog/spfx-docker

Finally, the samples repository consists of a lot of different SPFx versions from 1.1 all the way to 1.15+ So in order to run all of the samples, you need to make sure you have the proper versions of Node/Npm installed. If you are working on multiple versions, I highly suggest using NVM to set up multiple node environments on your machine (or in your case, multiple docker images for each type of node you may need for the samples). 

Take a look at the Compatibility Matrix for more information https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility


Finally, my 2 cents. The current sample you're trying to implement is a great example, but use caution. Using this to override the SharePoint Online or Modern Styles and Fonts **is unsupported** and we don't recommend using this Web Part in this way.

**Comment by Genti81** [comment]
Hi!

Thank you for your reply and for taking your time to answer me back. I am
aware of the different versions of my tools like Node / NPM and SPFX. I
also have already started using Docker and have seen @DonKirkham
<https://github.com/DonKirkham> 's blog and his videos regarding Docker
containers and other videos regarding containers.
I have tried many many ways to try to use an app that works for injecting
some css styles. Not that heavy usage just some font-family, font style and
font color.
That would be great.

I have checked out all of the pnp-spfx samples / tutorials and other places
but I just cannot find a simple app that does what I want :).
I hope you have some ideas of this so I can try out and get started.

Talk to you soon

Best regards

Gentrit

**Comment by bcameron1231** [comment]
Hi @Genti81 , thanks for the feedback. Working with @DonKirkham right now, he's going to upgrade this solution to 1.15.2 (He's using Node 16 btw). He'll submit a PR in the next day or so.

With the docker stuff, unfortunately I don't use it, so I can't really help you there.

**Comment by DonKirkham** [comment]
@Genti81, I have submitted the pull request. I'm not sure if you can access it directly before it is approved, but if not, you can clone my fork at https://github.com/DonKirkham/sp-dev-fx-webparts/tree/to-v1.15.2 

I tested the updated solution in WSL and I also updated the devcontainer files to the latest version and tested that successfully.  Hope this helps!

That said, I will repeat @bcameron1231 's warning that the technique of DOM injection/manipulation used by this webpart is not recommended or supported by Microsoft. SPFx is designed to limit the CSS/JS to the solution being developed. Reaching outside of that solution to change other parts of the page based on the OOTB classes, IDs, or other targeting strategies may cause your solution to break if (when!) Microsoft changes the structure of the modern master page. This has happened several times over the last few years, so please use caution.

This solution uses an application customiser to apply CSS/JS to an entire site collection or even tenant. If you just need to make CSS changes for a single page, take a look at the Enhanced List Formattting webpart sample.

Good luck.

**Comment by Genti81** [comment]
Hi Don Kirkham and Pnp Team

Thank you very much for this. You have no idea how much this means to me.
Really! I love SP and SPFX and have been working with them for quite a
while now. I follow you on youtube channels and listen to your videos
(monthly and weekly) and advice.
It would be great if Microsoft actually makes some things simpler for us
that uses SPFX daily because I understand the effort and work you guys put
every day to make our lives easier at work.

The thing is I understand the impact and risks of using webparts like CSS
injections. I test and develop SP sites daily and a lot of my work
involves using web part apps.

Once again thank you very much for doing this. It also helps people around
the globe that use or will use your solutions :)
Sharing is caring!

Best regards

Gentrit Sahiti
