### ISSUE TITLE
react-rss-reader - 

### ISSUE THREAD

**Issue by Genti81** [pnp/sp-dev-fx-webparts#3054]
### Disclaimer

Yes

### Sample

react-rss-reader

### Author(s)

@Abderahman88 @eoverfield

### Question

I would like to use this sample for testing please with the latest spfx.

Thank you in advance.

**Comment by Abderahman88** [comment]
Hi @Genti81,

You can surely use this sample. Do you need some help how the deploy this sample?

**Comment by Genti81** [comment]
Hi Moujahid

Thank you for your reply. I would need some help to deploy this sample
thank you very much :)

**Comment by Cwright86** [comment]
HI there, I am also trying to get the sharepoint package for this. I have downloaded node but no success so far. Any advice?

**Comment by Genti81** [comment]
Hi PNP team

I have already tried the steps many many times and also know the steps to
be taken to make a webpart work on a machine.

The problem that occurs when I try to use your samples are node/npm
packages and other dependencies because more than often the readme text
does not correspond to what to do with webpart.

Best regards

Gentrit

**Comment by Abderahman88** [comment]
*Steps**

1. Check your Node version. This sample is made in SPFx v. 1.11, so it requires Node v10 [see compatibility matrix](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility)
![image](https://user-images.githubusercontent.com/36161889/198382780-047e58d1-811a-4cfc-8ccc-0012e1b879e3.png)
2. Next step is to install all the necessary packages. Run `npm install`
![image](https://user-images.githubusercontent.com/36161889/198383540-a70df545-8e32-41c2-9c22-9e0e05eaecff.png)
3. [_Optional_] If installation is complete, check if you can run the sample. Run `gulp serve`. If you don't have any errors, everything is set to build and package.
![image](https://user-images.githubusercontent.com/36161889/198388739-03e6d8bc-8dc7-4fe8-92a5-970c35e6fbce.png)
4. To bundle the project, run `gulp bundle --ship`
![image](https://user-images.githubusercontent.com/36161889/198389448-8e318968-9710-4b0e-a42d-ae09b854b724.png)
5. To create the sppkg-file , run `gulp package-solution --ship`
![image](https://user-images.githubusercontent.com/36161889/198391041-a169af2a-db4c-4a8f-9662-9da2009172a1.png)
![image](https://user-images.githubusercontent.com/36161889/198391317-967fff2a-8219-4312-a004-9b68088c722b.png)
6. Upload the sppkg file to the (site collection) app catalog and install the app. You'll find enough documentation online how to do this.
7. If the steps are done correctly, the app can be added on a SharePoint page.

![image](https://user-images.githubusercontent.com/36161889/198392180-28156f79-148b-48e7-9af5-1730bcbcd3be.png)
