### ISSUE TITLE
Build error with react-calendar-feed

### ISSUE THREAD

**Issue by StanleyBonhomme** [pnp/sp-dev-fx-webparts#3088]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-calendar-feed

### Author(s)

@hugoabernier , @petkir

### What happened?

When trying build the webPart i get the following error:

**Error - [lint] TypeError: rushStackCompiler.LintRunner is not a constructor
Error - 'lint' sub stask errored after 374 ms
rushStackCompiler.LintRunner is not a constructor**

### Steps to reproduce

1. Run npm i
2. Run gulp build
3. Terminal starts build then exits and displays the following

**Error - [lint] TypeError: rushStackCompiler.LintRunner is not a constructor
Error - 'lint' sub stask errored after 374 ms
rushStackCompiler.LintRunner is not a constructor**

### Expected behavior

The expect behavior would be to build the package.

### Target SharePoint environment

SharePoint Online

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

**Error - [lint] TypeError: rushStackCompiler.LintRunner is not a constructor
Error - 'lint' sub stask errored after 374 ms
rushStackCompiler.LintRunner is not a constructor**

**Comment by petkir** [comment]
@mohammadamer Thanks for the PR 

but the "@microsoft/sp-build-web": "1.15.2", is also at version 1.15.2, so i think it will come to a mismatch
PR #3076 was already done before this issue.

@StanleyBonhomme 
Quick fix is to edit the package.json
Change these 2 DevDependencies to 1.10.0 and it will wok as expected
"@microsoft/sp-build-web": "1.10.0",
"@microsoft/sp-webpart-workbench": "1.10.0",

**Comment by mohammadamer** [comment]
@petkir I didn't know that you have already upgrade this solution. Would it be fine closing my PR.

**Comment by petkir** [comment]
@mohammadamer i haven't linked the pr to this issue, i was away.

So you cannot see it directly, thanks for your support :-). We do the work twice :-)

**Comment by mohammadamer** [comment]
@petkir To make processing PR easier for Hugo I'll close my PR. It doesn't make sense having two PRs.
Thanks @petkir
