### ISSUE TITLE
react-list-search - 

### ISSUE THREAD

**Issue by IrshadPeeran** [pnp/sp-dev-fx-webparts#3092]
### Disclaimer

Yes

### Sample

react-list-search

### Author(s)

@albegut

### Question

getData throw an exception. Error Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The field or property 'OData__ModernAudienceTargetUserField' does not exist."}}}

**Comment by albegut** [comment]
Hi @IrshadPeeran It's seems that the webpart has been configured to use modern audience on one or more list/library and that lists has not audience functionality enabled. 

To check that configuration, please access the webpart properties and uncheck the lists/libraries that has not activated the audience functionality

1. At the _'Select source lists'_

![image](https://user-images.githubusercontent.com/9661096/198238851-6bd75793-884d-4aeb-9f30-dcda70a33cec.png)

2. Uncheck the modern audience for the lists that has the problem

![image](https://user-images.githubusercontent.com/9661096/198239420-90f2694e-d0ad-479a-854a-664a74993a86.png)

**Comment by hugoabernier** [comment]
Hey @IrshadPeeran , did @albegut's answer help you solve the issue? I'll mark this as answered, but feel free to open a new issue with more information if you need any more help.
