### ISSUE TITLE
react-jest-testing - "rushStackCompiler.ListRunner is not a constructor" 

### ISSUE THREAD

**Issue by AmulIndia** [pnp/sp-dev-fx-webparts#3098]
### Disclaimer

Yes

### Sample

Js-Advanced-Commenting

### Author(s)

@sudharsank 

### What happened?

I have changed my node version and now running on 16.x and gulp 4.x.

Now got the error react-jest-testing - "rushStackCompiler.ListRunner is not a constructor"  while running gulp bundle --ship

### Steps to reproduce

1. gulp bundle --ship
2. Now got the error  - "rushStackCompiler.ListRunner is not a constructor"  while running gulp bundle --ship
3.

### Expected behavior

should bundle

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

16.18.0

### What version of Node.js is required by the sample?

10.0.0

### Paste the results of SPFx doctor

cjxcxzj

**Comment by sudharsank** [comment]
Hi @AmulIndia,

I am sorry that you are getting error. The web part was developed using SPFx version 1.9.1 and NodeJS v16 was not supported. Have you tried to update the web part to the latest version and NodeJS v16 is supported only from SPFx version 1.16. Please let me know if you have any clarifications.

**Comment by AmulIndia** [comment]
Thanks for reply @sudharsank can you please confirm if SPFX 1.9.1 with node V 10.20 and gulp 3.9.1 combination will work to run this project sample? please help

**Comment by AmulIndia** [comment]
UPDATE -

When i tried to run this solution with Node 10.20, gulp 3.9.1 and SPFX 1.9.1 then it gives error as below. Can you please guide us to resolve the issue as it is urgent now.

Error: Cannot find module 'worker_threads'

@sudharsank

**Comment by AmulIndia** [comment]
@sudharsank
