### ISSUE TITLE
react-taxonomy-file-explorer: Folder inside the library breaks sample

### ISSUE THREAD

**Issue by MoeIcI** [pnp/sp-dev-fx-webparts#3110]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-taxonomy-file-explorer

### Author(s)

@mmsharepoint

### What happened?

Hello everyone!

I tried to use this webpart as Table of Content  for the Site Pages Library. I was wondering why this solution works perfectly fine with any other Library but not with the Site Pages library. After debugging and testing around I discorverd the problem. An folder inside the chosen library breaks the webpart.

I fixed for me by catching the exception. It might be useful to add this fix or at least mention the problem inside the documentation.

![fix](https://user-images.githubusercontent.com/108660028/199472235-9e1f4006-9284-4ffe-970a-6f67b6ad6483.png)

(I also changed the api from "GetByTitle" to "GetById" since our sharepoint is set up in french and is used in english. Using the GUID instead of title prevents issues by selecting the wrong title ("Site Pages" instead of "Pages du site") Since the SharePoint is set up in french only "Pages du site" works and "Site Pages" is not found.)

### Steps to reproduce

1. Create Templates
2. Templates folder gets created automatically
3. Use 'Site Pages' as Library in the webpart
4. Choose the right field (and hierarchical Termset bound to a managed metadata column)

### Expected behavior

The webpart prints the structure implemented by the hierarchical Termset

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v14.19.3

### What version of Node.js is required by the sample?

v14 | v12 | v10

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.15.0
√ Node v14.19.3
√ yo v4.3.0
√ gulp v4.0.2
√ bundled typescript used

**Comment by mmsharepoint** [comment]
In General I tend to keep those samples as simple as possible to concentrate on the main takeaways. This sample was intended to act on a plain folderless library. 
Nevertheless I slightly remember that I filtered out folders by query in one of my variants. 
Did you consider that?
Will try to find and figure that out once time. 
getByTitle is much more usable than getByID but in fact only works with primary language title. That’s true

**Comment by MoeIcI** [comment]
Hello @mmsharepoint ,

thanks for your reply!
I didn't consider to filter out the folders by query.

The intention of this thread was to share my findings with the community. I fixed them (more or less) myself. Since I spent some time to figure out that this folder and the primary language are causing my problems, it might be a good idea to mention this potential "errors" in the description and documentation.

Thanks for your help. I can close this issue as solved if you want.

Best regards,
MoeIcI

**Comment by mmsharepoint** [comment]
Yes, and you are totally right with reporting your findings. Thanks for that.
And indeed, I was thinking how to best incorporate that.
With documentation only or with slight code adaptations ... let me check and move forward with this issue.

> Hello @mmsharepoint ,
> 
> thanks for your reply! I didn't consider to filter out the folders by query.
> 
> The intention of this thread was to share my findings with the community. I fixed them (more or less) myself. Since I spent some time to figure out that this folder and the primary language are causing my problems, it might be a good idea to mention this potential "errors" in the description and documentation.
> 
> Thanks for your help. I can close this issue as solved if you want.
> 
> Best regards, MoeIcI
