### ISSUE TITLE
react-tinymce build errors - Cannot find module 'typescript' - unable to serve or build webpart

### ISSUE THREAD

**Issue by Bukijon** [pnp/sp-dev-fx-webparts#3116]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-tinymce

### Author(s)

@AustinBreslinDev

### What happened?

Hello there! And thank you to all who read this and are able to provide any sort of help or resolve. I'm new to both posting issues here in Github and also to SPFx development. Any and all constructive criticism is welcome.

The [compatibility section](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-tinymce#compatibility) for the react-tinymce sample states that the project needs Node.js v8 | v6. 

Unfortunately, I was not able to use SPFx doctor with anything less than Node.js v10.24.1. According to the output, everything about my setup looks good except for my node version. I do have v6 and v8 installed through nvm. 

Following the [Minimal Path to Awesome section](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-tinymce#minimal-path-to-awesome) of the sample, I try the following:

1. `npm install`
2. `gulp serve`
3. `add web part to page`
(⬇ animated gif - click to view)
![build-error](https://user-images.githubusercontent.com/12887031/200019665-dd2f1915-c050-4ad2-9507-e41ab75858e7.gif)

**Gulp serve and build produce the same error output:**
```
added 3345 packages in 304.002s
PS C:\solutions\react-tinymce> gulp serve
{ Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\solutions\react-tinymce\node_modules\tslint\lib\linter.js:20:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1
PS C:\solutions\react-tinymce>
```

I'm confused about the error, "Cannot find module 'typescript'" as the SPFx Doctor output shows that the project is using the bundled version of typescript:
![image](https://user-images.githubusercontent.com/12887031/200039621-7280ddd8-5f17-4f28-98bc-9a014e58bc1b.png)

I also ran `npm outdated` to see if I needed to upgrade anything in the project:
![image](https://user-images.githubusercontent.com/12887031/200040295-491920cc-6ad6-45a5-b4ea-bdc90dc3e2f1.png)
I updated the react and react-dom installations as `npm outdated` suggested:
![image](https://user-images.githubusercontent.com/12887031/200040968-55253ed4-4f6e-41ce-8777-14adc6b715bb.png)

After retrying `gulp serve` and `gulp build` I'm met with the same 'typescript' error as before.

### Steps to reproduce

1. Download the [react-tinymce sample](https://pnp.github.io/download-partial/?url=https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-tinymce) from Github as a .zip file
2. Unzip the folder
3. Place the contents of that folder into your dev environment - for me that is inside a folder called "solutions" with a sub folder called **react-tinymce**.
4. Open VS and navigate to the project folder "react-tinymce"
5. Check to make sure you are running the correct version of node based on the compatibility section of the sample - v8 or v6.
6. Check to make sure the rest of your environment is set properly by running SPFx Doctor - 
7. Run SPFx Doctor with the command `m365 spfx doctor -o text`
8. Receive the following error message: 
**m365: The term 'm365' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.**
9. Switch to a version of Node.js that SPFx Doctor runs on - For me it was v10.24.1
10. Run SPFx Doctor with the command `m365 spfx doctor -o text` again
11. Receive the following output:
![image](https://user-images.githubusercontent.com/12887031/200043689-4234384d-302f-4d62-b2dc-28806894ea39.png)
12. Now that I can see that all of the components, other than Node, are good to go for the sample, I switch back to Node.js v8.
13. Run the command `gulp serve`
14. Receive error about missing Typescript module.
15. Run the command `gulp build`
16. Receive the same error about missing Typescript module.

### Expected behavior

I expect that you'll be met with the same Typescript build errors as I am. 🤷‍♂️

I hope that it will be obvious to someone what is happening, hopefully its a simple user error on my part.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [X] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

PS C:\solutions\react-tinymce> nvm ls      18.6.0     16.16.0     14.20.0     10.24.1   * 10.0.0 (Currently using 64-bit executable)     9.0.0     8.17.0     8.16.2     8.0.0

### What version of Node.js is required by the sample?

v^6 || ^8 required

### Paste the results of SPFx doctor

**I tried running SPFx doctor with Node v6, v8, v10 and none of them would run. I had 10.24.1 installed as well and was able to get SPFx doctor to run. The results are below.**

PS C:\solutions\react-tinymce> nvm use 10.24.1
Now using node v10.24.1 (64-bit)
PS C:\solutions\react-tinymce> m365 spfx doctor -o text
 
CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.4.1
× Node v10.24.1 found, v^6 || ^8 required
√ yo v3.1.1
√ gulp-cli v2.3.0
√ bundled typescript used

Recommended fixes:

- Install Node.js v8
![1-spfx-doctor-output](https://user-images.githubusercontent.com/12887031/200005078-15c82a32-ba84-4f5a-a22e-8435333f4dd7.png)

### Additional environment details

**Basic Environment Details**
OS: Windows 10 Pro, 10.0.19044 Build 19044
System Type: x64-based PC

**VS Code Info:**
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

Also using NVM to manage various node versions:
  18.6.0
  16.16.0
  14.20.0
  10.24.1
  10.0.0
  9.0.0
  8.17.0
  8.16.2
_*** 8.0.0 (Currently using 64-bit executable)**_

**Comment by hugoabernier** [comment]
Hi @Bukijon can you try building the sample in Node 8 and see what happens? The sample is not going to work in anything but Node 6 or 8.

**Comment by Bukijon** [comment]
Hi @hugoabernier, I actually have tried it already in v6 and v8. The "module not found" error was occurring when using v8. I only switched to a higher version so I could use SPFx Doctor, to verify all of my other environment components were as they should be. Then I switched right back to v8.

Thanks,

-Buki
