### ISSUE TITLE
React Content Query WebPart - Display HTML field value not as HTML but as formatter text in the webpart

### ISSUE THREAD

**Issue by annajhaveri** [pnp/sp-dev-fx-webparts#3120]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-content-query-online

### Author(s)

@hugoabernier

### Question

I am trying to display HTML field value in the web part, but it is displaying the HTML as text, with HTML text, it is not displaying formatted text? Any idea how to resolve this?

**Comment by chrnel** [comment]
Hi Anna
I had the exact same problem today - by chance.

The solution is to use triple curly braces e.g. 
{{{myFieldName.htmlValue}}}

This seems to be a handlebars thing - I found the solution here:
https://stackoverflow.com/questions/20280601/insert-html-in-a-handlebar-template-without-escaping

**Comment by JohnMoor** [comment]
Thanks @chrnel I had this exact same question! glad you posted it here.
