### ISSUE TITLE
react-calendar - 

### ISSUE THREAD

**Issue by mlutz51** [pnp/sp-dev-fx-webparts#3162]
### Disclaimer

Yes

### Sample

react-calendar

### Author(s)

@Abderahman88, @Eli-Schei, @mohammadamer, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### Question

hello,

I am interested in using this sample however when I try to install it using the command "npm install" I get these errors
and not sure what I'm doing wrong 

npm ERR! code 1
npm ERR! path c:\sp-dev-fx-webparts\samples\react-calendar\node_modules\deasync
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Program Files\Python311\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:412:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\sp-dev-fx-webparts\\samples\\react-calendar\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd c:\sp-dev-fx-webparts\samples\react-calendar\node_modules\deasync
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed

if there is any insight that anyone can give me I would be grateful 
Thank you

**Comment by mohammadamer** [comment]
Hi @mlutz51
Which node version are you using ?

**Comment by hugoabernier** [comment]
Closing this issue due to no response. Feel free to create a new issue if there are new issues related to this.

**Comment by raj2014New** [comment]
Hi @hugoabernier , this is still giving error during npm install
