### ISSUE TITLE
react-accordion-with-richtext - Clicking on Tab Content switches allways back to Tab 1

### ISSUE THREAD

**Issue by Constey** [pnp/sp-dev-fx-webparts#3292]
### Disclaimer

Yes

### Sample

react-accordion-with-richtext

### Author(s)

@arunkumarperumal

### What happened?

Hi Arun,

thanks for that nice sample, its awesome  👍 
I was not sure if this was wanted by you for an example, so I've just created an issue. When clicking within the text of an Tab it switches always back to Tab 1. So you can't copy/paste things for example:
![chrome_zQ1avQstGw](https://user-images.githubusercontent.com/11457386/207009370-f77f4529-7433-49ae-9979-0b617abf7a51.gif)

When I comment out in Tabs.tsx the following part:
![image](https://user-images.githubusercontent.com/11457386/207009669-4043ab15-9633-4e33-b123-fc81c11e589f.png)

Clicking withing the Tab Content works properly:
![chrome_frtGvQUF2Z](https://user-images.githubusercontent.com/11457386/207009714-18ee0c9b-6e80-4610-83f4-1ec17723841c.gif)

So maybe you could change this, so default behaviour is optimum ? :-)

p.s. you can aswell attach this for german localization if wanted:
de-de.js
```
define([], function() {
  return {
    "PropertyPaneDescription": "Passe deine Tab Klappbox an.",
    "BasicGroupName": "Tabs",
    "TitleFieldLabel": "Titel",
    "ManageAccordion": "Verwalte Tabs",
    "Type": "Anzeigeart",
    "Tabs": "Tabs",
  }
});
```

Thanks very much, and have a good week.

### Steps to reproduce

1. Install webpart
2. click within the content of tab 2 or tab 3
3. it switches back to tab 1

### Expected behavior

Should not switch back to Tab 1 // only if we click on the Tab Header.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

not relevant

### What version of Node.js is required by the sample?

not relevant

### Paste the results of SPFx doctor

not relevant

**Comment by arunkumarperumal** [comment]
@Constey please feel free to update the code to include localisation as needed. Since it is a sample just focussed on English
