### ISSUE TITLE
React list - lookup column from SharePoint list more than 5000K items

### ISSUE THREAD

**Issue by supermode** [pnp/sp-dev-fx-webparts#3295]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-list-form

### Author(s)

@Harshagracy

### Question

Hi,

I have dropdown list which using lookup list where the list items are more than 5K. Therefore, it seems some of items are not display in dropdown list. 

Currently the code in **ListFormService.ts**

public async getLookupfieldOptions(fieldSchema: any, webUrl: string): Promise<any[]> {
        const endpoint = `${webUrl}/_api/Web/lists/getbyid('${fieldSchema.LookupListId}')/items?$orderby=${fieldSchema.LookupFieldName}&$top=5000`;

Therefore, I am trying to add a filter to ensure to retrieve items less than 5K using the following code however it seems still does not get the result that filter Colour eq 'Blue'

public async getLookupfieldOptions(fieldSchema: any, webUrl: string): Promise<any[]> {
        const endpoint = `${webUrl}/_api/Web/lists/getbyid('${fieldSchema.LookupListId}')/items?$filter=Colour eq 'Blue' $orderby=${fieldSchema.LookupFieldName}&$top=5000`;

**Comment by omarelanis** [comment]
Can you provide details of the lookup list? Is Colour the name of an indexed column? What type of column is it?

If you do a manual GET request like so are the results filtered as expected?

Https://site/_api/Web/lists/getbyid('list id')/items?$filter=Colour eq 'Blue' 

You have to remember the query cannot do any actions which hit over 5000 items, so if the field Colour has over 5000 records this query will fail

**Comment by supermode** [comment]
Hi Omar, So the colour is a choice field. So the records that have item colour equal to Blue is less than 5000 items. However in dropdown list only showing 18 items. Is there any settings that I missed

**Comment by omarelanis** [comment]
Please can you answer the questions I asked before? it's hard to narrow it down or try to help without much to go on.

Is the Colour field indexed?
How many records exist in the lookup list?
What results are returned if you query the web address in the browser replacing the relevant bits below?

https://{site}/_api/Web/lists/getbyid('{list id}')/items?$filter=Colour eq 'Blue'

Does the above query only return 18 items?

I think the issue is the $top query which the above steps will help to narrow down

**Comment by supermode** [comment]
Hi Omar,

Your answer has helped me resolved the issue. Thank you
