### ISSUE TITLE
REACT-ACCORDION - 

### ISSUE THREAD

**Issue by tedtninety** [pnp/sp-dev-fx-webparts#3421]
### Disclaimer

Yes

### Sample

REACT-ACCORDION

### Author(s)

@AbhishekGarg @gautamdsheth

### Question

Thank you for this great solution.

I'm hoping that you may be able to assist.

This solution was implemented at work by admins, in a work environment where requests regarding solutions are not entertained.

I am utilizing this solution for an FAQ ,exactly like the sample.
My dilemma is that stakeholders want the entries sorted alphabetically and NOT buy ID.
Having limited control, is there a way I may alphabetize the list via script editor?

Thank you kindly.
ted

**Comment by tedtninety** [comment]
Hello and thank you for your reply.
I do not have those options .
The only available options are:

- List Name
- Maximum items to retrieve
- Enable Paging
- Max number of items per page

Our version is "react-accordion-client-side - solution : 2.2.0.0

Thank you for your reply

**Comment by AbhishekGarg** [comment]
You're right, those options were added in version 2.3.0, which itself is more than an year old. If you can use that version, that will be great.
I do not have a better solution atm.

**Comment by tedtninety** [comment]
Thank you so much @AbhishekGarg !
I really appreciate you taking the time to answer.
