### ISSUE TITLE
Spfx teams tab activity notifications 

### ISSUE THREAD

**Issue by SantanuPati** [pnp/sp-dev-fx-webparts#3427]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-teams-send-notification/README.md

### Author(s)

@luismanez 

### Question

Getting error as “multiple teams application is linked with this Azure AAD app”.
What will be the solution for SPFx teams tab for activity notifications …as one AAD app can be linked with only one Teams app for sending activity notifications. So if we want to deploy multiple SPFx teams app in the same tenant with activity notifications what are the options

**Comment by SantanuPati** [comment]
> ## Wrong or missing author @mentions
> Thank you for your submission, but you appear to have forgotten to @mention the sample author(s).
> 
> To help increase your chances of getting assistance from the original authors of the sample, you should make sure to @mention the actual authors (and not the repository maintainers).
> 
> Please note that the sample authors will not get notified about this issue unless you update this issue accordingly.
> 
> You can find the author(s) of each sample in the sample's `README.md`, under **Solution**.
> 
> We'll automatically close this issue in 7 days unless you update the issue.
> 
> For more information on how to create a good issue, refer to our wiki for more information: [How to Create Good Issues](https://github.com/pnp/sp-dev-fx-webparts/wiki/How-to-Create-Good-Issues)

Updated the author

**Comment by luismanez** [comment]
I don't see this is an issue in the sample. Seems more a limitation in SPFx Teams apps and Activity feed notifications. Here https://learn.microsoft.com/en-us/graph/teams-send-activityfeednotifications?tabs=http#requirements-for-using-the-activity-feed-notification-apis it says:

> You might get an error if multiple Teams apps in the same scope (team, chat or user) are using the same Azure AD app. Make sure that you're using unique Azure AD apps.

Which seems exactly your issue. This is an interesting one... I suggest you open it in the SPFx docs repo, and see if someone from MS SPFx team can add any light...

FYI: @VesaJuvonen @AJIXuMuK
