### ISSUE TITLE
react-rhythm-of-business-calendar - 

### ISSUE THREAD

**Issue by JoeAyre** [pnp/sp-dev-fx-webparts#3454]
### Disclaimer

Yes

### Sample

react-rhythm-of-business-calendar

### Author(s)

@d-turley

### What happened?

When a user with 'Read' permissions only views the calendar on a SharePoint Online page, the 'Add event' option still appears. They can click it, and add an event, but once they click 'Save' they are presented with an error:

Error: Error making HttpClient request in queryable [403] Forbidden ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"}}} at new t (<site-collection-url>/sites/appcatalog/ClientSideAssets/37df9a1c-b53e-46ad-9efb-2e4da77a724f/rhythm-of-business-web-parts_2e96af557590db3df174.js:2:1822340) at Function. (<site-collection-url>/sites/appcatalog/ClientSideAssets/37df9a1c-b53e-46ad-9efb-2e4da77a724f/rhythm-of-business-web-parts_2e96af557590db3df174.js:2:1823668) at <site-collection-url>/sites/appcatalog/ClientSideAssets/37df9a1c-b53e-46ad-9efb-2e4da77a724f/rhythm-of-business-web-parts_2e96af557590db3df174.js:2:1823457 at Object.next (<site-collection-url>/sites/appcatalog/ClientSideAssets/37df9a1c-b53e-46ad-9efb-2e4da77a724f/rhythm-of-business-web-parts_2e96af557590db3df174.js:2:1823562) at r (<site-collection-url>/sites/appcatalog/ClientSideAssets/37df9a1c-b53e-46ad-9efb-2e4da77a724f/rhythm-of-business-web-parts_2e96af557590db3df174.js:2:1823841)

### Steps to reproduce

1. Access a SharePoint Online site as a 'Visitor' (or with 'Read' permissions only)
2. Visit a SharePoint Online page with the '(LOCAL) Rhythm of Business Calendar' web part added.
3. Click 'Add event' from either the top button on when hovering in a date cell and clicking 'Add'.
4. Enter event data
5. Click 'Save'

### Expected behavior

I would expect the 'Add event' to be hidden for visitors (or those with 'Read' permission only).

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.19.0

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

This isn't an issue with the build - the solution builds fine. It's just functionality of the actual solution that is missing.

**Comment by EMKody137** [comment]
I'm seeing this exact same behavior, was a solution ever found or implemented?
