### ISSUE TITLE
react-content-query-online .sppkg

### ISSUE THREAD

**Issue by calmkza** [pnp/sp-dev-fx-webparts#3463]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-content-query-online

### Author(s)

@DavidWarnerII @bernierh @PaoloPia

### Question

Is there a download available for this solution?  I am not at all a developer and am having the worst time trying to install everything I need and build this on my own.  Is there a .sppkg file I can download?

Thanks!
Chris

**Comment by hugoabernier** [comment]
Sorry, we cannot provide builds for security reasons. This sample repository is intended to be used for teaching purposes only.

**Comment by lovethakker02** [comment]
https://github.com/lovethakker02/sp-dev-fx-webparts-Sol/tree/main/react-content-query-online

**Comment by calmkza** [comment]
> https://github.com/lovethakker02/sp-dev-fx-webparts-Sol/tree/main/react-content-query-online

@lovethakker02 I appreciate the link but unfortunately, I don't see the .sppkg for this web part.  Just the calendar and carousel.

I'll keep watching, though!

Thanks!

**Comment by shearak** [comment]
@lovethakker02 Would you mind including the .sppkg file for the react-content-query-online. The calendar and carousel worked great. I really appreciate it as will others.
