### ISSUE TITLE
react-datatable - 

### ISSUE THREAD

**Issue by Zoomex9876** [pnp/sp-dev-fx-webparts#3474]
### Disclaimer

Yes

### Sample

react-datatable

### Author(s)

@Abderahman88 @chandaniprajapati

### Question

Hi, Thanks for providing a great react-datatable example, If I need to update the column name in data table, how can I do that??

**Comment by Abderahman88** [comment]
@Zoomex9876 If possible, change the name of the column in the original list.
Then re-configure the webpart.
