### ISSUE TITLE
Build react-script-editor-onprem webpart

### ISSUE THREAD

**Issue by Zerg00s** [pnp/sp-dev-fx-webparts#3479]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor-onprem

### Contributor(s)

@wobba

### Question

I am trying to build the **react-script-editor-onprem** solution, but having issues. Is there something obvious that I'm doing wrong? If needed, I can create a PR. I just don't see where the issue is coming from exactly.

Unfortunately, I can't build the project even though my dev environment is [aligned with the SPFX compatibility matrix](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility).

**Node and npm versions used. (SPFx 1.10.0)**
- node.js version: v8.17.0
- npm version: 6.14.18

**Result**
- `npm install` runs successfully
- `gulp bundle --ship` <- Fails with the following error:

![image](https://user-images.githubusercontent.com/2797648/220241918-26dac5be-43af-4db2-bffe-995e436777ab.png)

> PS C:\sp-dev-fx-webparts\samples\react-script-editor-onprem> gulp bundle --ship
> C:\sp-dev-fx-webparts\samples\react-script-editor-onprem\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\devDeployPlugin\SpDevDeploy.js:165
>             for await (const file of filesIterable) {
>                 ^^^^^
> 
> SyntaxError: Unexpected reserved word
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:617:28)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\sp-dev-fx-webparts\samples\react-script-editor-onprem\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\devDeployPlugin\DevDeployPlugin.js:28:23)

**Node and npm versions used. (SPFx 1.4.1)**
I also tried building the project using the older version of npm compatible with the SPFx 1.4.1:
- node.js version: v8.17.0
- npm version: 4.6.1

However, in this case I can't even run npm install without an error:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/2797648/220238924-c53373bf-b88e-4bcd-92e2-ab22b3546956.png">

> 2380 verbose stack Error: Unsupported URL Type: npm:@microsoft/teams-js@2.4.1
> 2380 verbose stack     at parseUrl (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:186:13)
> 2380 verbose stack     at npa (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:79:12)
> 2380 verbose stack     at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\realize-package-specifier\index.js:12:15)
> 2380 verbose stack     at childDependencySpecifier (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:104:3)
> 2380 verbose stack     at addDependency (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:454:3)
> 2380 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:405:5
> 2380 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
> 2380 verbose stack     at Array.forEach (<anonymous>)
> 2380 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
> 2380 verbose stack     at Array.forEach (<anonymous>)
> 2380 verbose stack     at asyncMap (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
> 2380 verbose stack     at loadDeps (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:397:3)
> 2380 verbose stack     at Array.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
> 2380 verbose stack     at LOOP (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
> 2380 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
> 2380 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\and-finish-tracker.js:8:8

Any help will be greatly appreciated! If needed - I can do more tests or provide more details.

**Comment by wobba** [comment]
Not sure what happens. I would use nvm, set up with the versions listed for SPFx v1.4.1 and see if that works.

Or just create a new on-prem webpart and add the logic you plan to paste in as a script in the web part ;) Script editor wp's are evil.

**Comment by Zerg00s** [comment]
Thank you, @wobba. I was able to create a new script editor webpart for on-prem (SP SE) that works. I copied some of the files from the /src folders to a brand-new SPFx project and did some tweaking. Although I had to remove the property pane because it was causing multiple issues :(

If I have time, I might be able to submit a PR for react-script-editor-onprem. Although I can't promise it.
