### ISSUE TITLE
react-chat-gpt - 

### ISSUE THREAD

**Issue by vibhushukla93** [pnp/sp-dev-fx-webparts#3480]
### Disclaimer

Yes

### Sample

react-chat-gpt

### Contributor(s)

@nicodecleyre

### What happened?

I am getting an error while implementing the code in .tsx file. The error is follows - **_"No overload matches this call.
  The last overload gave the following error.
    Argument of type 'typeof Chatgpt' is not assignable to parameter of type 'string | ComponentClass<IChatgptProps, any> | FunctionComponent<IChatgptProps>'.
      Type 'typeof Chatgpt' is not assignable to type 'ComponentClass<IChatgptProps, any>'.
        Type 'Chatgpt' is not assignable to type 'Component<IChatgptProps, any, any>'.
          Property 'componentDidMount' is private in type 'Chatgpt' but not in type 'Component<IChatgptProps, any, any>'.ts(2769)"_**

### Steps to reproduce

1. I have created a new project.
2. I have Imported the ChatgptWebpart.ts in .tsx 
3.

### Expected behavior

I was not expecting this type of error

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.16.0

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

No overload matches this call.
  The last overload gave the following error.
    Argument of type 'typeof Chatgpt' is not assignable to parameter of type 'string | ComponentClass<IChatgptProps, any> | FunctionComponent<IChatgptProps>'.
      Type 'typeof Chatgpt' is not assignable to type 'ComponentClass<IChatgptProps, any>'.
        Type 'Chatgpt' is not assignable to type 'Component<IChatgptProps, any, any>'.
          Property 'componentDidMount' is private in type 'Chatgpt' but not in type 'Component<IChatgptProps, any, any>'.ts(2769)

**Comment by nicodecleyre** [comment]
Hi @vibhushukla93, 

Thank you for reaching out! I don't really understand what you are trying to do with 'Importing the ChatgptWebpart.ts in .tsx', but if I understand correctly you:
- created a new SPFx project
- you want to use the ChatGPT component in your new solution

In that case, you don't have to copy the `ChatgptWebpart.ts` file. this can be obtained by copying the ChatGPT component files into a new folder in your new solution:
- Chatgpt.module.scss
- Chatgpt.tsx
- IChatgpt.ts
- IChatgptProps.ts
- IChatgptState.ts

Then your file structure should look like this:
![image](https://user-images.githubusercontent.com/35696168/220672579-1462b4c3-2382-43fa-acb4-a1186c12e4a6.png)

After that you can use the ChatGPT component in another component (for instance from the `HelloWorld.tsx` file. Where you can import the component like:
`import Chatgpt from './ChatGPT/Chatgpt';`

after that you can use the ChatGPT component in your react element:
`<Chatgpt apiKey='YOURAPIKEY' isDarkTheme={false} hasTeamsContext={false} context={context}/>`

![image](https://user-images.githubusercontent.com/35696168/220674091-9fb87777-85d2-4eef-88fa-e66f1d5c6781.png)

Please let us know if this solves your problem, if not can you give more details on how your code is written?

**Comment by vibhushukla93** [comment]
Hi,

As you suggested I have done the changes however on the time of build the
project I am getting an error that you can see in attached screenshot.

[image: image.png]

Below you can see how's my project looks like.

[image: image.png]


Thanks & Regards
Vibhu Shukla

**Comment by nicodecleyre** [comment]
Hi @vibhushukla93,

Thank you for your answer. I can't see your images about how your project looks like, possibly because your comment was send via mail. Can you try again with the images?

Thank you in advance!
