### ISSUE TITLE
Rss Reader won't work with direct request

### ISSUE THREAD

**Issue by djsladi** [pnp/sp-dev-fx-webparts#3493]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-rss-reader

### Contributor(s)

@eoverfield @Abderahman88

### What happened?

When having a RSS feed without CORS, we do not need Rss2Json (or similiar) feed service. When using Direct request, we can get a good response: 
![image](https://user-images.githubusercontent.com/39775012/222447672-da0343cd-c5af-4265-8391-2462dd7c6d7f.png)

but the spinner will spin and settings cannot be saved. In the console there are error: "TypeError: Cannot read properties of undefined (reading '$')":
![image](https://user-images.githubusercontent.com/39775012/222448369-f4ce7ffe-56b3-4c1e-b7fb-8bbe3a418f59.png)

which is caused by:
![image](https://user-images.githubusercontent.com/39775012/222448527-ccd80ede-32e1-435c-bc81-9682401dddff.png)

### Steps to reproduce

1. Install RSS-web part and open settings
2. Place some CORS-free RSS-feed url to **Feed Url** -field (for example https://www.is.fi/rss/tuoreimmat.xml )
3. Set **Feed Retrival Service** to Direct Request
4. Push **Use** -button

### Expected behavior

RSS Feed should be visible.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v10.24.1

### What version of Node.js is required by the sample?

v10

### Paste the results of SPFx doctor

√ SharePoint Framework v1.11.0
√ Node v10.24.1
× yo not found
× gulp-cli not found
√ bundled typescript used

Recommended fixes:

- npm i -g yo@3
- npm i -g gulp-cli@2

### Additional environment details

I'm using NVM to handle different Node versions. Yo is installed using Node 16.x.

**Comment by Abderahman88** [comment]
@hugoabernier Can you assign this one to me?

**Comment by djsladi** [comment]
Any progress on the PR?

**Comment by djsladi** [comment]
This is not completely fixed, if the feed is Atom -feed. @Abderahman88 your fix can be applied to rssXmlParserService.ts as well to check if Atom -feed is array or not:

```
//if (channel['atom:link']) feed.feedUrl = channel['atom:link'][0].$.href;
if (Array.isArray(channel['atom:link'])) {
  feed.feedUrl = channel['atom:link'][0].$;
}
else {
  feed.feedUrl = channel['atom:link'].$;
}
```
