### ISSUE TITLE
react-birthdays - Birthday 

### ISSUE THREAD

**Issue by Pandas4Peace** [pnp/sp-dev-fx-webparts#3552]
### Disclaimer

Yes

### Sample

react-birthdays

### Contributor(s)

@smaity @joaojmendes

### What happened?

After packaging and deploying the modern birthdays web part, no birthdays are displayed. 
![image](https://user-images.githubusercontent.com/126006139/223465621-eed1d01a-0a2a-47e6-af6f-99b2a856caa8.png)

### Steps to reproduce

1. Create list "Birthdays" on root of SharePoint Site. 
![image](https://user-images.githubusercontent.com/126006139/223468619-85612039-63bf-4903-8b72-7dd54025cb95.png)

2. Create index on column "Birthday"
3. Clone Repository
4. npm install
5. gulp build
6. gulp bundle --ship
7. gulp package-solution --ship
8. Add and deploy package to App Catalog
9. Approve API Scopes in API Management
10. Add Web Part to Site Page

### Expected behavior

Expected web part to display a list of 4 birthdays. Instead, no upcoming birthdays
![image](https://user-images.githubusercontent.com/126006139/223469755-695606fa-16d4-4e98-b4f1-eac622e47731.png)

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.19.1

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

√ SharePoint Framework v1.16.1
√ Node v16.19.1
√ yo v4.3.1
√ gulp-cli v2.3.0
√ bundled typescript used

**Comment by joaojmendes** [comment]
Please verify if the year of birthday is 2000 the date must be.   Example   05/01/2000

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: msftbot[bot] ***@***.***>
Enviado: Tuesday, March 7, 2023 4:48:39 PM
Para: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] react-birthdays - Birthday (Issue #3552)


Thank you for reporting this issue. We will be triaging your incoming issue as soon as possible.

**Comment by Pandas4Peace** [comment]
@joaojmendes 
I did see a post that mentioned that bug. Please see this sample of my list: 
![image](https://user-images.githubusercontent.com/126006139/223499005-fae64850-2d40-4667-aa9e-ecf1632eadd6.png)

**Comment by joaojmendes** [comment]
You have errors on console ?

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Pandas4Peace ***@***.***>
Enviado: Tuesday, March 7, 2023 5:19:33 PM
Para: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] react-birthdays - Birthday (Issue #3552)


@joaojmendes<https://github.com/joaojmendes>
I did see a post that mentioned that bug. Please see this sample of my list:
[image]<https://user-images.githubusercontent.com/126006139/223499005-fae64850-2d40-4667-aa9e-ecf1632eadd6.png>

**Comment by joaojmendes** [comment]
Let me do some test on my side , thank you

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Pandas4Peace ***@***.***>
Enviado: Tuesday, March 7, 2023 5:28:06 PM
Para: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] react-birthdays - Birthday (Issue #3552)


Yes, please see screenshot:
[image]<https://user-images.githubusercontent.com/126006139/223501234-69fbb177-ff13-4ed3-83ca-69949005e9e6.png>

**Comment by joaojmendes** [comment]
Seems some column name is wrong

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: João Mendes ***@***.***>
Enviado: Tuesday, March 7, 2023 5:30:35 PM
Para: pnp/sp-dev-fx-webparts ***@***.***>; pnp/sp-dev-fx-webparts ***@***.***>
Cc: Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] react-birthdays - Birthday (Issue #3552)

Let me do some test on my side , thank you

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Pandas4Peace ***@***.***>
Enviado: Tuesday, March 7, 2023 5:28:06 PM
Para: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] react-birthdays - Birthday (Issue #3552)


Yes, please see screenshot:
[image]<https://user-images.githubusercontent.com/126006139/223501234-69fbb177-ff13-4ed3-83ca-69949005e9e6.png>

**Comment by Pandas4Peace** [comment]
@joaojmendes 
That was it! Somehow, the "Birthday" column was showing as "Field" in the url. Thank you!

Now the dates are showing up, but there's no profile pictures. Are there instructions on how to do that?

**Comment by samirnela500** [comment]
@Pandas4Peace I have the same issue as you, but I deleted the column and created a new one with date and time, yet the problem persists. Can you explain me how you fixed this.
