### ISSUE TITLE
react-content-query-online - Errors trying to build

### ISSUE THREAD

**Issue by calmkza** [pnp/sp-dev-fx-webparts#3572]
### Disclaimer

Yes

### Sample

react-content-query-online

### Contributor(s)

@DavidWarnerII @bernierh @PaoloPia

### What happened?

- I downloaded the repository and unzipped.
- I installed Node.js v10 (using NVM) along with gulp-cli and yo.
- I ran "npm install" which completed successfully.
- I ran "gulp build" which did not.  I got the error below.

![image](https://user-images.githubusercontent.com/27428031/223861002-ff5a1cb0-3ce4-40f3-b505-db9c60802b35.png)

I looked at SPBuildRig.js that was referenced in the error and it's definitely not looking for the version the web part was created with.  So, I installed version 12.13.0 even though it's not listed as compatible with 1.11.0, switched over to it and started again.

This time I got the error below.

![image](https://user-images.githubusercontent.com/27428031/223865154-2fe024ec-04f3-4929-811d-e227b307aa70.png)

Am I doing something wrong or is it possible that this web part is just too outdated?  Or am I simply a moron?  :)

I'm running Windows 10 version 20H2 (OS Build 19042.2604).

### Steps to reproduce

1.  Download repository and unzip.
2. Install NVM
3. Install Node.js v10.18.0. (nvm install 10.18.0)
4. Install gulp-cli (npm install -g gulp-cli@2)
5. Install yo (npm install -g yo@3)
6. Change to the projects folder (with package.json in it)
7. Run "npm install"
8. Run "gulp build"

### Expected behavior

I expected to be able to build the project and ultimately able to deploy it to my sites and pages.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v10.18.0

### What version of Node.js is required by the sample?

v10

### Paste the results of SPFx doctor

Using Node.js 10.18.0...
    √ SharePoint Framework v1.11.0
    √ Node v10.18.0
    √ yo v3.1.1
    √ gulp-cli v2.3.0
    √ bundled typescript used

Using Node.js 12.13.0...
    √ SharePoint Framework v1.11.0
    × Node v12.13.0 found, v^10 required
    √ yo v3.1.1
    √ gulp-cli v2.3.0
    √ bundled typescript used

Recommended fixes:

- Install Node.js v10

**Comment by benschowe** [comment]
I had the same problem. Installed node v10.24.1 with nvs. Did a
```
npm install gulp --global
npm install
gulp build
```
But all I get is
```
{ Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Source\pnp\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\@rushstack\worker-pool\lib\WorkerPool.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

```

**Comment by calmkza** [comment]
What I ended up doing was, starting from a fresh download of the repo:
- installing node v12.13.0 and running:

`m365 spfx project upgrade --toVersion 1.12.1 --output json > "Upgrade.json"`

- Performed everything listed in the file.
- Ran:

`npm  dedupe`

- I did find that in the devDependencies section of package.json I had to change "@microsoft/sp-build-web": "1.16.1" to "@microsoft/sp-build-web": "1.12.1".
- I also had to exclude the "tests" folder in "src" > "webparts" > "contentQuery".

After that, for the first time, I was able to build, package and deploy the webpart.

However, the problem I have now is that I can't actually type anything into the "Value" box if I pick a text field from the drop-down.  I can click into it and give it focus, I just can't type.

![image](https://user-images.githubusercontent.com/27428031/225338616-24a8881f-edc0-48e3-8e69-9687b5c7df35.png)

**Comment by Maya-Mostafa** [comment]
I am having the same issue. I tried using node versions: 10.13.0, 10.24.1 & 10.5.0 same issue.

**Comment by nemortu** [comment]
> What I ended up doing was, starting from a fresh download of the repo:
> 
> * installing node v12.13.0 and running:
> 
> `m365 spfx project upgrade --toVersion 1.12.1 --output json > "Upgrade.json"`
> 
> * Performed everything listed in the file.
> * Ran:
> 
> `npm dedupe`
> 
> * I did find that in the devDependencies section of package.json I had to change "@microsoft/sp-build-web": "1.16.1" to "@microsoft/sp-build-web": "1.12.1".
> * I also had to exclude the "tests" folder in "src" > "webparts" > "contentQuery".
> 
> After that, for the first time, I was able to build, package and deploy the webpart.
> 
> However, the problem I have now is that I can't actually type anything into the "Value" box if I pick a text field from the drop-down. I can click into it and give it focus, I just can't type.
> 
> ![image](https://user-images.githubusercontent.com/27428031/225338616-24a8881f-edc0-48e3-8e69-9687b5c7df35.png)

if it help also did an update sop SPFX 1.18.2 and had the same issue. It's a code issue. Did a pull request and hope it passes (if not the sample is not usable) : https://github.com/nemortu/sp-dev-fx-webparts/tree/update-spfx-version-react-content-query-online
