### ISSUE TITLE
react-chatgpt-app: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by schneika** [pnp/sp-dev-fx-webparts#3585]
### Disclaimer

Yes

### Sample

sp-dev-fx-webparts/samples/react-chatgpt-app/ deployment with error on Grant SharePoint API Permission für OpenAIFunctionsapp for Permission "user_impersonation"

### Contributor(s)

@joaojmendes

### What happened?

Please see screenshots
![image](https://user-images.githubusercontent.com/11440416/225006467-b772c483-0ccc-40d4-baf6-ff833fbddfc6.png)

![image](https://user-images.githubusercontent.com/11440416/225006520-87a34eb2-a05b-4db9-a5da-c8e950b371de.png)

### Steps to reproduce

1. Build and deploy SPFX WebPart Solution
2. Try to Grant API Access in SharePoint Admin Center = Error in Screenshot
3. Try to use the SPFx WebPart in SharePoint or Teams = Error in Screenshot
4. What i am missing?

### Expected behavior

Working Solution

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.18.1

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

× SharePoint Framework v1.16.1

Error: spfx doctor doesn't support SPFx v1.16.1 at this moment

**Comment by schneika** [comment]
Yes, but i forgot to change my Custom Function name in the package-solution.json, like this Example from Doc

_Approve the Required App Permissions on SharePoint Admin.
You need to add the required permissions to the App for your Azure App used to secure the Azure Function App, by default the project has the follow defined on the package-solution.json:
"webApiPermissionRequests": [ { "resource": "MyCustomOpenAIFunctionsApp", "scope": "user_impersonation" } ],_

**Comment by joaojmendes** [comment]
I will take a look later ….
Thank you.

From: Karl Gerd Schneider ***@***.***>
Date: Tuesday, 14 March 2023 at 14:25
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-webparts] react-chatgpt-app: Deployment Error on SharePoint API Access for user_impersonation (Issue #3585)

But now i always get an error in Response:

Unexpected non-whitespace character after JSON at position 4

[image]<https://user-images.githubusercontent.com/11440416/225032030-c1799763-2a00-4d56-a647-0f2f9c0d0af2.png>

**Comment by joaojmendes** [comment]
Running from  sp-dev-fx-webpart  locally https://spteck.sharepoint.com/_layouts/15/workbench.aspx

Can you see if you have errors on console, please .

[Graphical user interface, text, application, email  Description automatically generated]
From: João Mendes ***@***.***>
Date: Tuesday, 14 March 2023 at 14:29
To: pnp/sp-dev-fx-webparts ***@***.***>, pnp/sp-dev-fx-webparts ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-webparts] react-chatgpt-app: Deployment Error on SharePoint API Access for user_impersonation (Issue #3585)
I will take a look later ….
Thank you.

From: Karl Gerd Schneider ***@***.***>
Date: Tuesday, 14 March 2023 at 14:25
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-webparts] react-chatgpt-app: Deployment Error on SharePoint API Access for user_impersonation (Issue #3585)

But now i always get an error in Response:

Unexpected non-whitespace character after JSON at position 4

[image]<https://user-images.githubusercontent.com/11440416/225032030-c1799763-2a00-4d56-a647-0f2f9c0d0af2.png>

**Comment by joaojmendes** [comment]
@schneika  , can you get the latest update from sp-dev-fx-webparts ? try to run npm serve or gulp serve .
See if you have some errors on console.

Thank you!

**Comment by joaojmendes** [comment]
You have the latest version of azure function deployed ?

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: João Mendes ***@***.***>
Enviado: Tuesday, March 14, 2023 3:37:13 PM
Para: pnp/sp-dev-fx-webparts ***@***.***>; pnp/sp-dev-fx-webparts ***@***.***>
Cc: Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-webparts] react-chatgpt-app: Unexpected non-whitespace character after JSON at position 4 (Issue #3585)


Can you see the network tab and find error on call of API ? Please



From: Karl Gerd Schneider ***@***.***>
Date: Tuesday, 14 March 2023 at 15:31
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-webparts] react-chatgpt-app: Unexpected non-whitespace character after JSON at position 4 (Issue #3585)

I am running the latest version from yesterday (with Chat-GPT3.5-Turbo). Try to debug in the workbench:

[image]<https://user-images.githubusercontent.com/11440416/225052668-8ecfc9d6-a22b-4534-8d3a-e90b83f4f33f.png>
