### ISSUE TITLE
React-page-navigator - Version 1.6 or 1.7?

### ISSUE THREAD

**Issue by Dahnic** [pnp/sp-dev-fx-webparts#3586]
### Disclaimer

Yes

### Sample

react-page-navigator

### Contributor(s)

@aakashbhardwaj619

### Question

I had the 1,6 version installed since previously and saw that an updated, 1.7 was available. However, after downloading, creating new sppkg ([Using this instruction](https://github.com/pnp/sp-dev-fx-webparts/tree/020737c970dfc2c7c2dd116dd5e7610f377f9636/samples/react-page-navigator#minimal-path-to-awesome)) and installing on tenant, the sharepoint app store still says is  version 1.6.0.0.

Is this just a miss to adjust the version in the updated sample or am I missing something here? The App details in the sharepoint store also says version 1.6.0.0 but release says 'March 2023'.

![image](https://user-images.githubusercontent.com/85103942/225061192-233c190d-d636-41df-8cfa-de04025c8412.png)

<img width="522" alt="image" src="https://user-images.githubusercontent.com/85103942/225062995-ec36f7ff-bcaa-48a3-8372-11274b667b3e.png">

**Comment by a1mery** [comment]
From what I can see in the sample, the version number has not been updated to 1.7.

**Comment by Abderahman88** [comment]
I've added a PR to rectify this one
