### ISSUE TITLE
IFramePanel sample on spfx 1.16

### ISSUE THREAD

**Issue by n1t3w0lf** [pnp/sp-dev-fx-webparts#3632]
### Disclaimer

Yes

### Sample description

Hi All 

I am new to spfx and programming in general, I have tried to implement the pnp spfx control IFramePanel unsuccessfully 

I am extremely confused as to link between fluentui and the spfx controls as well as how to to use / implement the this._onIframeLoaded and this._onDismiss methods mentioned in the documentation related to this control 

I am for a simple sample showing how to implement / use this control on spfx 1.16 react framework , if anyone is able to provide this it would be greatly appreciated as i have tried several samples and spent over a week trying to implement this but have not been able to so far 

i would create a webpart with a simple heading and button that when clicked opens a modal that i would like to use the frame to capture user input and then submit and save the information into a SharePoint list 

thank you kindly for reading and potentially hope that someone would be so kind as to provide me with a sample of how to implement this 

### SPFx version

1.16.0

### Are you willing to help?

Yes

**Comment by ValerasNarbutas** [comment]
I am up for the challenge @hugoabernier, 
will build a simple example. Can be assigned to me.

**Comment by n1t3w0lf** [comment]
thanks for trying to look into this, i can offer my services as a general here, i am a QA so if there is every any need for someone to test any of the fixes or work being developed i am happy to help out and test :)

**Comment by ValerasNarbutas** [comment]
> thanks for trying to look into this, i can offer my services as a general here, i am a QA so if there is every any need for someone to test any of the fixes or work being developed i am happy to help out and test :)

Thanks @n1t3w0lf , i got some interesting thoughts when creating your sample. I might just do all available controls in one sample. And update when ever new ones are added. I might when ask for your time to test ;)

**Comment by ValerasNarbutas** [comment]
> awesomeness, i am ready to assist just tag me and i will test, just fair warning i am useless at coding so i wont be able to do any code

no problem!
