### ISSUE TITLE
I have a really difficult time installing 'react-accordion-dynamic-section'... Has anyone succeeded?

### ISSUE THREAD

**Issue by superhotfireman** [pnp/sp-dev-fx-webparts#3637]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-dynamic-section

### Contributor(s)

Erik Benke, Ari Gunawan

### Question

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-dynamic-section

Hello, I found the webpart above and was delighted to give it a try to add to my sharepoint. I cloned the repository and pulled the folder for 'react-accordion-dynamic-section' so I can start working on it. 

Below is my current enviornment set up: 
**Node**: 10.24.1  
**NPM**:  6.14.12
**Gulp**: 3.9.1 
**spfx**: 1.10.0  
**react**: 16.8.5
**react-dom**: 16.8.5

[Result from Running 'npm ls --depth=0'. It matches the projects package.json file ](https://github.com/pnp/sp-dev-fx-webparts/files/11043012/Result.from.Running.npm.ls.--depth.0.txt)

Good thing is when i run 'npm i', it runs fine and cause no issue. However, when I proceed to use 'gulp serve', then I get a below error: 
`Error: Cannot find module 'worker_threads'`

I searched in various forums and saw some solutions being recommended but none would work. 
1. Upgraded my gulp to gulp version 4 but that didn't work because it doesn't support Node 10... 
2. Someone adviced me on using '--experimental-worker' but that also fails because that's only for Node 12 or greater... 

Any helps will be great.

Edit 1: I just read on stackoverflow that 'workers' are supported after 10.5 so I installed 10.13.0 (using nvm) but I still got the same exact error. I really want this webpart will keep trying.

**Comment by ValerasNarbutas** [comment]
hey @superhotfireman 
i will try on my machine also and let you know

**Comment by ValerasNarbutas** [comment]
@hugoabernier can you assign this one to me? I have upgraded the version of this web part. works as expected.
@superhotfireman you can grab it as soon as it available :)
