### ISSUE TITLE
Rhythm of business calendar - time changes after after refresh on adding a new event 

### ISSUE THREAD

**Issue by skambam-exelixis** [pnp/sp-dev-fx-webparts#3658]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-rhythm-of-business-calendar

### Contributor(s)

@d-turley

### What happened?

As soon as  a new event(say for example 4PM to 5 PM) is saved, the item gets created but once I refresh it changed to 4 Am to 5 AM. I am creatingg this event from India IST(GMT +5.30) time zone. FYI the SPO site is in UTC-08:00 US & Canada Pacific Time
SPO Site Timezone
![image](https://user-images.githubusercontent.com/123719349/232538510-c0905705-c465-43a5-bff5-239e5a217c7f.png)

New Event - on Save
![image](https://user-images.githubusercontent.com/123719349/232538597-1713292f-0599-44ba-9488-16d1ca2c32cf.png)

After refreshing the page
![image](https://user-images.githubusercontent.com/123719349/232538641-8bc80f48-a18f-4c48-b16d-a92fade02e8b.png)

### Steps to reproduce

Add a new event, have a look the time and date the event is created
Refresh the page and see the time is converted to the site's time zone
Edit the same event and change the event time , the time do not get changed to site's timezone

### Expected behavior

time has to be converted to the site's time zone  through out the web part or 
time has to be converted to the browser's timezone

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.18.1

### What version of Node.js is required by the sample?

v16.18.1

### Paste the results of SPFx doctor

NA

### Additional environment details

{
    "name": "rhythm-of-business-calendar",
    "version": "1.0.0",
    "main": "lib/index.js",
    "private": true,
    "scripts": {
        "build": "gulp bundle",
        "clean": "gulp clean",
        "deploy": "gulp deploy",
        "package": "gulp package",
        "test": "./node_modules/.bin/jest",
        "serve": "gulp bundle --custom-serve --max_old_space_size=4096 && fast-serve"
    },
    "resolutions": {
        "@types/react": "~16.9.51"
    },
    "dependencies": {
        "@fluentui/react": "^8.77.2",
        "@fluentui/react-hooks": "^8.6.0",
        "@fluentui/react-icons-mdl2": "^1.3.11",
        "@microsoft/sp-component-base": "^1.15.2",
        "@microsoft/sp-core-library": "^1.15.2",
        "@microsoft/sp-http": "^1.15.2",
        "@microsoft/sp-list-subscription": "^1.15.2",
        "@microsoft/sp-loader": "^1.15.2",
        "@microsoft/sp-property-pane": "1.15.2",
        "@microsoft/sp-webpart-base": "1.15.2",
        "@pnp/common": "^2.13.0",
        "@pnp/graph": "^2.13.0",
        "@pnp/logging": "^2.13.0",
        "@pnp/odata": "^2.13.0",
        "@pnp/sp": "^2.13.0",
        "compressed-json": "^1.0.16",
        "he": "^1.2.0",
        "hoist-non-react-statics": "^3.3.0",
        "lodash": "^4.17.21",
        "moment-timezone": "^0.5.34",
        "office-ui-fabric-react": "7.185.7",
        "react": "~16.13.1",
        "react-beautiful-dnd": "^13.1.1",
        "react-dom": "~16.13.1",
        "react-router-dom": "^6.3.0",
        "sanitize-html": "^2.7.1",
        "spfx-fast-serve": "^3.0.6",
        "swiped-events": "^1.1.6"
    },
    "devDependencies": {
        "@microsoft/eslint-config-spfx": "^1.15.2",
        "@microsoft/eslint-plugin-spfx": "^1.15.2",
        "@microsoft/gulp-core-build": "3.17.19",
        "@microsoft/rush-stack-compiler-4.5": "0.2.2",
        "@microsoft/sp-build-core-tasks": "^1.15.2",
        "@microsoft/sp-build-web": "^1.15.2",
        "@microsoft/sp-module-interfaces": "^1.15.2",
        "@rushstack/eslint-config": "2.5.1",
        "@testing-library/jest-dom": "^5.14.1",
        "@testing-library/react": "^11.2.7",
        "@types/he": "^1.1.2",
        "@types/hoist-non-react-statics": "^3.3.1",
        "@types/jest": "^26.0.24",
        "@types/react": "~16.9.51",
        "@types/react-beautiful-dnd": "^13.1.2",
        "@types/react-dom": "~16.9.8",
        "@types/react-router-dom": "^5.3.3",
        "@types/react-test-renderer": "~16.9.5",
        "@types/sanitize-html": "^2.3.2",
        "@types/sharepoint": "^2016.1.10",
        "@types/webpack-env": "^1.16.2",
        "acorn": "^8.4.1",
        "ajv": "^8.6.1",
        "enhanced-resolve": "^5.8.2",
        "eslint-plugin-react-hooks": "^4.3.0",
        "gulp": "^4.0.2",
        "gulp-zip": "^5.1.0",
        "identity-obj-proxy": "^3.0.0",
        "jest": "^26.6.3",
        "json5": "^2.2.2",
        "raf": "^3.4.1",
        "react-test-renderer": "~16.13.1",
        "stateful-process-command-proxy": "^1.0.1",
        "ts-jest": "^26.5.6",
        "spfx-fast-serve-helpers": "~1.15.0"
    },
    "engines": {
        "node": ">=16.15.1"
    }
}

**Comment by Emmanueladegor** [comment]
I am experiencing same @skambam-exelixis

**Comment by d-turley** [comment]
I'll try to have a look at it this weekend.  It should keep and display events in the site's time zone, like the calendar view on the SharePoint events list.  Also, it should be possible to update the code so that events are created and displayed in the current user's local time, regardless of the site's time zone setting.  Our intention was to make either behavior easy to build with the accelerator, and it would just depend on the requirements of the app you are building.

**Comment by Emmanueladegor** [comment]
@d-turley - Thank you!

**Comment by skambam-exelixis** [comment]
@d-turley thanks for the response I totally get the intention, we will try to fix as well from our side.

**Comment by d-turley** [comment]
I have a [commit](https://github.com/d-turley/sp-dev-fx-webparts/commit/945f89a2ede2c263a842bea245eddb789719c192) in my fork that I believe resolves the issue.   Will you let me know if those changes work for you?  The important pieces are the changes in EventLoader.ts and SPField.ts.  I'll see if I can get some additional testing support before submitting a PR.

Is there any interest in the alternate scenario - displaying & editing times in the user's local time zone, regardless of the time zone settings on the SPO site?

**Comment by Emmanueladegor** [comment]
@d-turley - Thank you very much. Well, while that makes sense for some scenarios, I think it might be an issue for some event types.

So let's say I'm on EST timezone and have an event for Thurday - 8am to 5pm EST. If it shows the event based on the user's timezone, it means if someone in IST timezone, should view that event, they will see: 5:30pm to 2:30am, which will make that event span from Thursday to Friday on their view, which is misleading. So I will suggest using SharePoint's timezone, or let's maybe have a switch, to toggle, to switch between both options if its possible
