### ISSUE TITLE
react-calendar - 

### ISSUE THREAD

**Issue by metkhoo** [pnp/sp-dev-fx-webparts#3660]
### Disclaimer

Yes

### Sample

react-calendar

### Contributor(s)

@Abderahman88, @Eli-Schei, @mohammadamer, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### Question

Hi developers,

Would it be possible to add a "Filter" mechanism that allowed the calender to show only events of a particular category.  Obviously there would be an "All items" filter too.
This would vastly improve the UX when there are very many events.
This feature would turn this webpart into a corporate events capability where one can filter by region/counrty etc.

**Comment by mohammadamer** [comment]
@hugoabernier Could you please assign it me.

**Comment by mohammadamer** [comment]
Hi @metkhoo 

Just to keep the issue updated, I'm working with implementing a multi-selection dropdown to add a filter functionality to the calendar webpart.

**Comment by metkhoo** [comment]
Brilliant news.  Thanks

**Comment by cGarganoR** [comment]
> Hi @metkhoo
> 
> Just to keep the issue updated, I'm working with implementing a multi-selection dropdown to add a filter functionality to the calendar webpart.

Great to hear that, I'm too interested to this feature, thanks for taking this updated

**Comment by CollinHunterGOC** [comment]
Any updates on this?

**Comment by mohammadamer** [comment]
Hi @metkhoo @CollinHunterGOC 
Apologies for being late!
I'm progressing with this change. I'll complete it soon and let you know.

**Comment by metkhoo** [comment]
@mohammadamer  Brilliant!  Thanks for your work on this.

**Comment by mohammadamer** [comment]
Hello @metkhoo and @CollinHunterGOC 

I have to announce that I have done the update for filtering by category. I'll create a PR for this change Today.

**Comment by CollinHunterGOC** [comment]
Thank you

**Comment by metkhoo** [comment]
Brilliant! Well done indeed sir!
