### ISSUE TITLE
react-feedback - 

### ISSUE THREAD

**Issue by drswan1** [pnp/sp-dev-fx-webparts#3661]
### Disclaimer

Yes

### Sample

react-feedback

### Contributor(s)

@perr124 @Abderahman88

### What happened?

When a user other than the feedback owner submits feedback, no email is sent.

### Steps to reproduce

1. Have a random user other than the owner submit feedback.
2. Check feedback on the feedback owner email.

### Expected behavior

When the user submits feedback, it should appear in the feedback owner's mailbox.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

10.24.1

### What version of Node.js is required by the sample?

v10

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.11.0
√ Node v10.24.1

**Comment by Abderahman88** [comment]
Hi @drswan1 

I've tested it and got the mail (after a couple minutes delay) in the feedback owner mailbox.

Did you create the 'Feedback Owners' SharePoint group?

**Comment by hugoabernier** [comment]
Hi @drswan1 did @Abderahman88 's suggestion solve your issue? 

I'll go ahead and close this issue due to lack of activity. Feel free to open a new issue if you need more help.

Thank you @Abderahman88 for your help!

**Comment by drswan1** [comment]
> Hi @drswan1
> 
> I've tested it and got the mail (after a couple minutes delay) in the feedback owner mailbox.
> 
> Did you create the 'Feedback Owners' SharePoint group?

I sure did!
