### ISSUE TITLE
Make it sticky! ;)

### ISSUE THREAD

**Issue by Dahnic** [pnp/sp-dev-fx-webparts#3662]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-page-navigator

### Contributor(s)

@aakashbhardwaj619 @Jwaegebaert @RedEchidnaUK

### Suggestion

I really like this webpart, easy to use, smooth and looks good. I have just one, no two (!), suggestions for improvements (freshly borrowed  from this webpart: https://github.com/RedEchidnaUK/Table-of-Contents): 

1: Add 'Sticky' feature with toggle for on/off 
2: Add 'Return to previous page' feature with toggle on/off

### Are you willing to help?

No

**Comment by Jwaegebaert** [comment]
Great idea, @Dahnic! I'll try to incorporate those suggestions into the solution.
