### ISSUE TITLE
Modern Script Editor fails for Tenant Guest accounts

### ISSUE THREAD

**Issue by Danny-Engelman** [pnp/sp-dev-fx-webparts#3668]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@wobba

### What happened?

I allow Guest access for Tenant-**B** AND Tenant-**C** to Tenant-**A** site.

For Tenant-**A** users all script works fine.
For Tenant-**B** users (accessing Tenant-**A**) all script works fine.

For Tenant-**C** users (accessing Tenant-**A**) all scripts error:
So it must be a configuration or license error??

![](https://i.imgur.com/OSanklW.png)

### Steps to reproduce

1. Allow Guest access to a Tenant
2. Open page with a (React) Script Editor WebPart

### Expected behavior

All Guests  to Tenants should be able to use the Script Editor WebPart

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

n/a

### What version of Node.js is required by the sample?

n/a

### Paste the results of SPFx doctor

n/a

**Comment by Danny-Engelman** [comment]
Note: similar error with the SPJS Content Editor WebPart

![](https://i.imgur.com/6sZ67gO.png)

**Comment by wobba** [comment]
This seems access related to the CDN, not web part specific. If it's a new install give it some time. If not, clear caches etc, or check if there are access policies for the one tenant.

**Comment by wobba** [comment]
Noticed this from your screenshot: `Either Guest user or Cortex is not enabled!`

You might be better off asking this at https://github.com/SharePoint/sp-dev-docs/issues as the two questions on SO did not give much information what could cause this. The web part is not using anything weird. Do you have other web parts or extensions on the page? Possibly try from a clean site collection where you invite the guest?

**Comment by wobba** [comment]
@Danny-Engelman are you referencing externals script or all script in the web part?

**Comment by Danny-Engelman** [comment]
I tried both the PnP and SPJS Script editor WebParts, on a brand new created SiteCollection.

Both only do ``console.log(666)``

I will get a new 30day free tenant thursday, and see what happens with another guest account.

The situation is weird, it is like the admins in the next door building, can control what _their_ employees can do when they walk into _our_ building.

**Comment by wobba** [comment]
I would still explore CDN or no CDN as you haven't said anything about your setup. Tenant app catalog, site app catalog etc. Other SPFx parts/customizers on the page.

**Comment by Danny-Engelman** [comment]
Was to cumbersome to create another Tenant.

I tried it by giving Guest access to new @outlook.com accounts.

All content display fine; but both Script Editor WebParts error

That means I have only one tenant/accounts for which Script actually works. 

Only difference I can think of, this tenant/these accounts are one of the earliest Office365 Tenants, which of course didn't have Modern Experiences.

For now my conclusion is: Script Editor WebParts **do not work** for Guest accounts.

**Comment by wobba** [comment]
What settings have you built it with? Require script on the site? And other spfx parts work? Would be good to know details of your setup and install.

**Comment by Danny-Engelman** [comment]
I used the PnP and SPJS .pkkg files to add them to the App Catalog.

Mail me an accountname to danny@engelman.nl, I can give you admin access

tnx

**Comment by wobba** [comment]
For one, someone must have built the sppkg file. If nothing was changed then someone must also have enabled script for the site. Maybe this affects guest users? I would try to follow the readme https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites and see if this helps.
