### ISSUE TITLE
react-adaptivecards -  Simple way to override inherited style attributes in SharePoint Online

### ISSUE THREAD

**Issue by gretchunkim** [pnp/sp-dev-fx-webparts#3682]
### Disclaimer

Yes

### Sample

react-adaptivecards

### Contributor(s)

@hugoabernier

### Question

Is there a simple way to override inherited style attribute that flows into Adaptive Cards? 
I have tried modifying "Template JSON" using SharePoint list as a data source, and all texts are showing up with these ugly blue hyperlinks which is inherited from SharePoint (or Office 365) stylesheet.  

{
            "type": "TextBlock",
            "text": "[${creator.name}](https://google.com)",
            "color": "Dark"
        } 

![image](https://user-images.githubusercontent.com/8564035/236527997-d063fd15-b858-4ac4-b7ab-9b18f9f57ca9.png)

Showing up as this in Office 365/SharePoint Online: ugly hyperlink blue line
![image](https://user-images.githubusercontent.com/8564035/236528101-790d51c7-f869-4929-8e45-7c4702bf20bc.png)

**Comment by hugoabernier** [comment]
Hi @gretchunkim , the web part uses the renderer provided by the Adaptive Cards library, and adds the Fluent UI theme to it.

Would suggest that you test using the preview at https://adaptivecards.io/explorer/TextBlock.html or https://adaptivecards.io/explorer/RichTextBlock.html to change the styles to meet your needs in the Adaptive Card template; if it works there, the web part _should_ respect the styles.

If not, you can always inject the styles you need within the code (take a look at the [_adjustThemeColor](https://github.dev/pnp/sp-dev-fx-webparts/blob/089162f74072d612ac8d1ad17647f3277e09045a/samples/react-adaptivecards/src/controls/AdaptiveCard/AdaptiveCard.tsx#L202) function, where you could add the styles you want.

I hope this helps?

**Comment by gretchunkim** [comment]
Thank you @hugoabernier I'll try both of them.
