### ISSUE TITLE
react-script-editor-onprem

### ISSUE THREAD

**Issue by Gennady-G** [pnp/sp-dev-fx-webparts#3705]
### Disclaimer

Yes

### Sample

react-script-editor-onprem

### Contributor(s)

@wobba

### Question

Greetings Mikael!

Don't You have compiled version of react-script-editor-onprem (react-script-editor-onprem.sppkg)?

I successfully created SPO version, but give tons of errors trying to build parallel stack for SharePoint 2019 (I tried to use NVM to install node/gulp/yoeman/etc as described [here](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-and-subscription-edition-support) but no luck.) Can You please share package for SP2019?

Best regards, Gennady

**Comment by wobba** [comment]
Sorry I don't. Guess it's a matter of getting the right SPFx + node working.

**Comment by Gennady-G** [comment]
Thank You Mikael!

Yes, imho the  problem is to have both versions for O365 and 2019..
I'll try to use virtual machine or my notebook to install 2019 Dev environment from scratch..

Best regards, Gennady

**Comment by Gennady-G** [comment]
> You can try to update the parts to SPFx v1.10 as well which works for 2019.

Thank You Mikael!

**Comment by Gennady-G** [comment]
Also tried to install versions from 1.4.1 from here: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-and-subscription-edition-support

But also get error: gulp is not found at all

![gulp-2023-05-25_213339](https://github.com/pnp/sp-dev-fx-webparts/assets/5569346/73b02742-79af-4c6e-ad82-dd23acdb986f)

Maybe I need to use different command for old gulp-CLI?..

--

> enabling script to anyone editing a page is a bad idea :)

Yes You are right.. But Your webpart could be fantastically useful for small fixes and something like "modern masterpages" - Yes they do not exist but sometimes it is cool to have something like few responsive links on homepage, etc.

So I can quickly make html/js/css markup and drop it to page. It is very long process to make a new webpart for every link fix/change

![markup-2023-05-25_203902](https://github.com/pnp/sp-dev-fx-webparts/assets/5569346/846a7899-26b6-4ed7-806a-127ed86bc5b1)

**Comment by Gennady-G** [comment]
Thank You Mikael! 
I'll keep You posted if I had luck with this build

**Comment by Gennady-G** [comment]
Thank You @wobba! I ended up recreating new webpart from generator for SPFx1.10, and migrated Your code there. 
Thank You again for these webparts! 👍

**Comment by AdamantiumWolverine** [comment]
> Hi again @wobba!
> 
> Strange - I added new VM with Windows 11, installed Node.js v8.17.0 there, and other versions compatible with SP 2019:
> 
> > npm install gulp-cli@2.3.0 yo@3.1.1 @microsoft/generator-sharepoint@1.10.0 --global
> 
> like described Andrew Connell here: https://www.voitanos.io/blog/definitive-guide-sharepoint-framework-sharepoint-server-2019/
> 
> Also fired "Set-ExecutionPolicy Unrestricted" in powershell ISE. But when I run "gulp serve" after 'npm install' - I get an error:
> 
> ```
> PS C:\prj\react-script-editor-onprem> gulp serve
> C:\prj\react-script-editor-onprem\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\devDeployPlugin\SpDevDeploy.js:165
>             for await (const file of filesIterable) {
>                 ^^^^^
> 
> SyntaxError: Unexpected reserved word
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:617:28)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\prj\react-script-editor-onprem\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\devDeployPlugin\DevDeployPlugin.js:28:23)
> PS C:\prj\react-script-editor-onprem>
> ```
> 
> ![err-2-2023-05-25_200709](https://private-user-images.githubusercontent.com/5569346/240971780-9e6db3e3-0850-43b4-bbaf-a2c397b4e98f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NzYwMzYsIm5iZiI6MTcxOTg3NTczNiwicGF0aCI6Ii81NTY5MzQ2LzI0MDk3MTc4MC05ZTZkYjNlMy0wODUwLTQzYjQtYmJhZi1hMmMzOTdiNGU5OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMjMxNTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE0ODhkOGRkNmIwM2Q1MmZjODRmMDg3OGJhMWVmMTc2NWJkNTZmODgwYzY5MzI2NjFhYzQzNjM5ZmQxNDg4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yVsUJQaoZvB8oYLDb3qXtOqjyXhM5S5luJnvs4eqxZg)
> 
> Maybe I do something wrong?

I had the same error after running "npm install" and it added a bunch of node_modules to the project.

The error is because gulp 2.3.0 doesn't understand the asynchronous command syntax used in the @microsoft\spfx-heft-plugins.   I wound up doing something similar to what you did.   

1) Create a new SharePoint web part based on the yo generator for SharePoint using the versions specified in the definitive guide to SPFX environment.  https://www.voitanos.io/blog/definitive-guide-sharepoint-framework-sharepoint-server-subscription-edition/

I selected react as the framework.

2) I, then, replaced the gulpfile.js, package.config, package-lock.config file with the one from the new default web part project and node_modules folder with the one from the new default web part project.

This ensured that only the necessary, spFX 1.4.1 compatible modules were added to the project.

3) Then, I ran gulp serve and was able to test the script editor web part on the workbench.
