### ISSUE TITLE
react-script-editor - 

### ISSUE THREAD

**Issue by borgy3377** [pnp/sp-dev-fx-webparts#3716]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@wobba @salascz @felixbohnacker

### Question

Hi, is there a way to selectively enable caching of external scripts coming from CDN's. It looks like the script editor is appending a new query string on every page load. Example below. It's fine for smaller scripts but large ones slow the page load.

https://mycdn.com/js/site.js?pnp=1685413679754

Thanks

**Comment by wobba** [comment]
The reason for appending is if you navigate from page to page, to ensure the script is loaded on each page. @borgy3377 can you share your scenario?

**Comment by borgy3377** [comment]
Hi @wobba , we use a framework from Telerik called Kendo UI. Two main scripts are loaded, a specific version of jQuery and the Kendo framework which both add up to about a second to load. From the script, some basic calls are made to various REST endpoints.  It doesn't sound like much but with all the other SharePoint stuff going on, the page has a noticeable delay before showing the content. We've isolated just the calls to the endpoints without the above scripts and there is no noticeable delay.

There are a few other JS files that are loaded too but are quite small so not significant. I guess it would be good to just remove the pnp query string and let the user control the caching because we would still like to append our own version number when the site.js file changes.

![screen1](https://github.com/pnp/sp-dev-fx-webparts/assets/10804595/9f207562-4888-497f-b4f1-05e71b07c10c)

```
// Original URL changed for demonstration purposes
<script src="https://mycdn.com/js/jquery.min.js"></script>
<script src="https://mycdn.com/js/kendo.all.min.js"></script>
<script src="https://mycdn.com/js/cultures/kendo.culture.en-AU.min.js"></script>
<script src="https://mycdn.com/js/messages/kendo.messages.en-AU.min.js"></script>
<script src="https://mycdn.com/js/site.js"></script>
<div id="content"></div>
<script>
  $(function () {
    // Some AJAX calls here
  });
</script>

```


Thanks

**Comment by wobba** [comment]
If you add this to your page A, and navigate between page A and B and back to A, does the script still work if you don't have the random part? If the last script tag is what does app bootstrapping then you might be ok. You have two options:

* Modify the code before you build it to remove the random part
* Do a PR on the project to add a config option if you should add a random part or not (I prefer this as it benefits all)
   * Either a toggle
   * Preferably an attribute on the script tag to parse

**Comment by borgy3377** [comment]
Thanks @wobba . I'll just add a config option to toggle the random part. I just raised it in case it was an option that would be included in a later release. Thanks again.

**Comment by wobba** [comment]
@borgy3377 will you add it as a pull request to this repo so other can benefit as well?
