### ISSUE TITLE
Unable to load the Advanced Commenting web part 

### ISSUE THREAD

**Issue by tri-thai** [pnp/sp-dev-fx-webparts#3718]
### Disclaimer

Yes

### Sample

js-advanced-commenting

### Contributor(s)

@hugoabernier

### What happened?

I can build and package the sample successfully.
When adding the Advanced Commenting web part to a page. I get the following error message:

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/26533695/a87ff901-6671-4186-8be7-347188083b19)

Please help review and advise what I should check. Thanks

### Steps to reproduce

1. Run command lines to install, build and package the solution.
2. Add and enable the package in app catalog.
3. Add "Advanced Comments Box" to a site
4. In a site page, add the "Advanced Comments" web part

### Expected behavior

The "Advanced Comments" web part should load successfully without any error message.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.18.1

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

js-advanced-commenting> m365 spfx doctor -o text
m365 : The term 'm365' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ m365 spfx doctor -o text
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (m365:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by tri-thai** [comment]
Might I know what the exact version of Node.js?

**Comment by TheThomasOne** [comment]
I've got exactly the same error message while adding the webpart to a web page. I have the same environment as tri-thai (Windows, SharePoint Online, Microsoft Edge). The result of SPFx doctor is the following:
<img width="644" alt="image" src="https://github.com/pnp/sp-dev-fx-webparts/assets/129587387/3f123c92-1859-4225-9dd6-3c5c635ec8aa">
This should meet the requirements. Do I have to install an exact version of Node.js?

**Comment by ibrrah** [comment]
I have the same issue spfx doctor returns all ok, but still i get this error

**Comment by a1mery** [comment]
I was able to reproduce the issue.
I've upgraded the sample to SPFx 1.17.0 and made other updates that solved the issue.

**Comment by TheThomasOne** [comment]
@a1mery : This worked for me. Thanks a lot for fixing.
