### ISSUE TITLE
What are the URLs you showed in your demo?

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-webparts#3731]
### Disclaimer

Yes

### Sample

react-spfx-control-iframepanel

### Contributor(s)

@ValerasNarbutas

### Question

I do not see here the example URLs you used in the demo. could you list them please?

**Comment by ValerasNarbutas** [comment]
hey @Ofer-Gal , you mean links under buttons? or sample solution itself?

**Comment by Ofer-Gal** [comment]
Links under buttons.  the way to get the file view, metadata and other examples you showed.
The code is in the project, I downloaded.
Thank you

**Comment by ValerasNarbutas** [comment]
@Ofer-Gal they are just links in my environment. For example i just copied file link in my sharepoint site and added it in property pane of this app.
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/16476453/cb153b60-38e2-46af-8d9b-f501c1d4b73d)

**Comment by Ofer-Gal** [comment]
Thank you much
