### ISSUE TITLE
react-advanced-page-properties - No support for Multiline field

### ISSUE THREAD

**Issue by NishkalankBezawada** [pnp/sp-dev-fx-webparts#3732]
### Disclaimer

Yes

### Sample

react-advanced-page-properties

### Contributor(s)

@Abderahman88 @mhomol @ValerasNarbutas 

### What happened?

Would be nice if the webpart supports multiline text fields. 

### Steps to reproduce

1. Add a column with Multiline text field. 
2. Add the webpart on the page
3. Try to add the available properties of the page, in which Multiline field is not available

### Expected behavior

Should support Multiline text field too

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

14.18.0

### What version of Node.js is required by the sample?

v16 | v14 | v12

### Paste the results of SPFx doctor

***

**Comment by NishkalankBezawada** [comment]
Hello @mhomol @Abderahman88 @ValerasNarbutas,

Greetings for the day. 

I anticipate that adding a multiline text field to this webpart will have numerous advantages for clients. Please share your thoughts on this; I'm willing to put in a pull request as well. 

Below is the screen shot, with the changes i have done in my dev environment.
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/47456098/17029b5b-2432-4c51-84b0-ca9f835c6544)


Regards,
Nishkalank

**Comment by Abderahman88** [comment]
@NishkalankBezawada Good one 👌
