### ISSUE TITLE
react-fluentui-9 - can't handle multiple fluentproviders in different webparts on same page

### ISSUE THREAD

**Issue by thomassteinerch** [pnp/sp-dev-fx-webparts#3735]
### Disclaimer

Yes

### Sample

react-fluentui-9

### Contributor(s)

@techienickb

### What happened?

We built and published an SPFx WebPart using Fluent UI 9, and it works fine. But as soon as we place a second WebPart with Fluent UI 9 on the same page, there is a problem with the FluentProvider. If I place the same WebPart multiple times on the same page, the FluentProvider is numbered correctly. If I place two different WebParts, the numbering no longer works and the two WebParts use the same Provider ID. The result of this is that the UI no longer renders correctly.

By the way, the problem can also be reproduced with the sample code published here. We have published the SPFx under two different names/IDs: Each one works fine by itself, but not together.
![two_webparts_error](https://github.com/pnp/sp-dev-fx-webparts/assets/99405463/b1d03265-61da-47b9-85f4-9e7dfe70ec85)
![one_webpart_ok](https://github.com/pnp/sp-dev-fx-webparts/assets/99405463/0537042a-b45e-4382-9267-9711754edceb)

### Steps to reproduce

1. Place two independent SPFx webparts using Fluent UI 9 on one page 
2. Check FluentProvider IDs

### Expected behavior

I suppose that each webpart should be using its own fluentprovider with unique IDs.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.13.2

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

na

**Comment by canturan** [comment]
Why is this issue closed. I am seeing the same issue on our web parts, after we started to use FluentUI v9. It messes up the design completely. 
The other problem is, if the given id of the FluentProvider has a conflict with the one from SharePoint (because SharePoint is also injecting some FluentProviders) it also messes up the design of the standart SharePoint elements on the page.

**Comment by techienickb** [comment]
> Why is this issue closed. I am seeing the same issue on our web parts, after we started to use FluentUI v9. It messes up the design completely. The other problem is, if the given id of the FluentProvider has a conflict with the one from SharePoint (because SharePoint is also injecting some FluentProviders) it also messes up the design of the standart SharePoint elements on the page.

If you don't put a fluentprovider in your code and use a headless implementation it will work fine, just reference your components, when I get some free time I'll update the sample

**Comment by canturan** [comment]
I found a better solution. It is explained here and easier to implement: [https://github.com/microsoft/fluentui/issues/27976](https://github.com/microsoft/fluentui/issues/27976)
IdPrefixProvider
I have tested it yesterday. It works perfectly fine.
