### ISSUE TITLE
react-rss-reader - Feed is not fetched if 'Max Count' is more than 10

### ISSUE THREAD

**Issue by NishkalankBezawada** [pnp/sp-dev-fx-webparts#3768]
### Disclaimer

Yes

### Sample

react-rss-reader

### Contributor(s)

@Abderahman88 @eoverfield @djsladi

### What happened?

The webpart is not fetching results if `Max Count` setting is changed to more than 10. It works if  `Max Count` is less than 10.

### Steps to reproduce

1. Change the `Max Count` in property pane of the webpart to more than 10 (Lets say 15)
2. Click apply
3. Publish the page, but the feed shows only 10 articles even if we have set this to 15
4. Change the `Max Count` in property pane of the webpart to less than 10 (Lets say 5)
5. Click apply to see the feed
6. Feed shows 5 articles as set in the `Max Count`

### Expected behavior

1. Change the `Max Count` in property pane of the webpart to more than 10 (Lets say 15)
2. Click apply
3. Publish the page, The feed should show the count which is set in the Property Pane

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

10.24.1

### What version of Node.js is required by the sample?

v10.16.3

### Paste the results of SPFx doctor

*

**Comment by NishkalankBezawada** [comment]
As per the api documentation, the ```Maxcount``` is only allowed upto 10. Hence closing the issue

**Comment by djsladi** [comment]
Just clarifying here to save time in the future: yes, **rss2json** without api_key is limited to 10 items only. You can sign up to rss2json or even buy some of their plans to have more items.

Direct request doesn't have this limitation, if you can use that option.
