### ISSUE TITLE
Rhythm of Business Calendar change locale

### ISSUE THREAD

**Issue by vatsake** [pnp/sp-dev-fx-webparts#3769]
### Disclaimer

Yes

### Sample

Rhythm of Business Calendar

### Contributor(s)

Dan Turley

### Question

By default the language is set to english and weeks start with Sunday.
How to change?

**Comment by d-turley** [comment]
For general UI strings, you would need to create the localized strings under:
- src/common/components/loc
- src/components/loc
- src/webparts/rhythmOfBusinessCalendar/loc

For dates and start of week, that is configured through [MomentJS locale](https://momentjs.com/docs/#/i18n/changing-locale/), and the locales would need to be loaded and selected during startup.
