### ISSUE TITLE
react-script-editor - sppkg uploaded & working | can not edit settings afterwards, though

### ISSUE THREAD

**Issue by jeroenbrussich** [pnp/sp-dev-fx-webparts#3771]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@wobba @salascz @felixbohnacker

### What happened?

I succesfully followed the steps in the README, and build the .sppkg for _react-script-editor_
I only edited **package-solution.json** (_skipFeatureDeployment:$true_); I left _initialPage:$null_ in **write-manifests.json**

The package builds without errors and I get a nice .sppkg which I uploaded to my SharePoint Apps.
I got a nice config screen (deploy site wide, integrate with Teams) which I clicked through.

I modified my site to allow scripts, imported the webpart and made some css tweaks.
**everything up to now seems to work as expected!**

however; when I try to edit my **Modern Script Editor Web Part v. 1.0.22.0** settings (Let's say I want to toggle the Teams setting), I get an error. `It looks like the webpage at [ url ] might be having issues, or it may have moved permanently to a new web address`.

### Steps to reproduce

1. Go to the sharepoint admin-center
2. Go to More Features -> Apps
3. Select _Modern Script Editor Web Part_,
4. Click on the three dots
5. Choose Settings

### Expected behavior

I would like to have the initial settings screen again, in which I can choose whether this app is deployed SharePoint wide; and/or can be integrated with teams.

For what it's worth: PnP Modern Search v4 has this expected behaviour

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.18.1

### What version of Node.js is required by the sample?

v16 | v14 | v12

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.13.1
× Node v16.18.1 found, v^12 || ^14 required ## EDIT BY USER: README ALSO MENTIONS V.16
√ yo v4.3.1
√ gulp-cli v2.3.0
√ bundled typescript used

Recommended fixes:

- Install Node.js v12 or v14

**Comment by wobba** [comment]
If you want to change how it's deployed, remove the old sppkg and add it again.

That said, your repro steps does not match adding the web part to a page and edit web part settings. What if you delete the web part and add it again on the page? Have not seen issues with re-edit a page and the web part before. And should be sufficient to install the sppkg once.

**Comment by jeroenbrussich** [comment]
Hi @wobba, sorry I was not clear enough in my explanation.

The webpart works just fine on any SitePage, That's not the issue.
It's when I try to edit its settings through the adminportal I get an error.

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/245972/4f26ca54-fdf7-4098-b475-89eafb6b3306)
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/245972/40f60bd8-ded6-4606-8e36-e4c341314a8e)
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/245972/e6852787-d9d8-4fdc-8353-962d35c42c98)

**Comment by jeroenbrussich** [comment]
Same action, but with PnP Search v4

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/245972/6a0a53b4-92f8-4e4b-ba37-1d880cc7dd2c)
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/245972/06ac8ee6-2978-46c4-b9d8-3582521b2bae)

**Comment by wobba** [comment]
I'll take a look. Never had a need to click ... on an spkg before :) Did you try to delete and re-add? That should likely be a workaround.

**Comment by wobba** [comment]
@jeroenbrussich can you test the latest version which was updated to latest SPFx as well.
