### ISSUE TITLE
js-advanced-commenting -  Attachment not working

### ISSUE THREAD

**Issue by gauravkochar87** [pnp/sp-dev-fx-webparts#3775]
### Disclaimer

Yes

### Sample

js-advanced-commenting

### Contributor(s)

@sudharsank

### What happened?

I can install the sample successfully.
When adding the attachments  in Advanced Commenting web part, it doesn't display any image, video, hyperlink or file.  I get the following error message:
![Error](https://github.com/pnp/sp-dev-fx-webparts/assets/59512491/0315e809-091f-4fa2-858d-99cb0da835f0)

An image appears broken and when I click on it it shows the error "hmm can't reach the page". I checked the browser url and my SharePoint tenant is not prefixed to it. is there something that I need to change in the source code?

Please help review and advise what I should check. Thanks

### Steps to reproduce

1.Run command lines to install, build and package the solution.
2.Add and enable the package in app catalog.
3.Add "Advanced Comments Box" to a site
4.In a site page, add the "Advanced Comments" web part

### Expected behavior

The "Advanced Comments" web part attachments should display successfully without any error message. 

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.19.1

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

√ SharePoint Framework v1.17.0
√ Node v16.19.1
√ yo v4.3.1
√ gulp-cli v2.3.0
√ bundled typescript used

**Comment by a1mery** [comment]
I'm not able to reproduce the issue :(
Has you file been successfully uploaded to the library ? Can you successfully access it directly from the library ?

**Comment by gauravkochar87** [comment]
> I'm not able to reproduce the issue :( Has you file been successfully uploaded to the library ? Can you successfully access it directly from the library ?
Hi, Thanks for looking into it. Yes the file gets uploaded to the document library and I can open it from the library but not from the webpart. I tested it on another site and it works fine. 

Could the error be because I am using it my home site which is also a hub site?

Because the link doesn't have home site url prefixed to the images and maybe that's why it appears broken.
