### ISSUE TITLE
React-Directory: Error while trying to build

### ISSUE THREAD

**Issue by IsmaelDev1** [pnp/sp-dev-fx-webparts#3777]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-directory

### Contributor(s)

@petkir , @joaojmendes

### What happened?

When trying to build the project, I am getting the following error.

{ Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

### Steps to reproduce

1. Clone the react directory
2. npm install
3. gulp build

### Expected behavior

Complete construction and continue with the next steps.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

10.24.1

### What version of Node.js is required by the sample?

10

### Paste the results of SPFx doctor

√ SharePoint Framework v1.11.0
√ Node v10.24.1
√ yo v3.1.1
√ gulp-cli v2.3.0
√ bundled typescript used

**Comment by IsmaelDev1** [comment]
@joaojmendes  @petkir  @sudharsank @Abderahman88

**Comment by petkir** [comment]
@IsmaelDev1 

Thanks for using this sample.

I see in the package.json is a mismatch of the spfx version 
All @microsoft/sp- packages should have the same version number in this case it should be1.11.1 

2 dependencies  and 2 devDependencies are at version 1.16.1 or  1.12.1

as QuickFix:
change it and the build should work again

```
"dependencies": {
...
    "@microsoft/sp-property-pane": "1.11.1",
    "@microsoft/sp-webpart-base": "1.11.1",
...
```
```
"devDependencies": {
 ...
    "@microsoft/sp-build-web": "1.11.1",
    "@microsoft/sp-webpart-workbench": "1.11.1",
...
```

**Comment by petkir** [comment]
I will upgrade this solution to 1.17.2.

I struggled with Debounce and one super lovely ESLint error 
```
Error - [lint] Unexpected STDERR output from ESLint: DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.
```

**Comment by IsmaelDev1** [comment]
hi @petkir,
Thanks for your response , I was able to continue with the process and reached the next step specified in the project, in which I get a new error.

I get this error when I run the command **gulp bundle --ship**.

`[10:10:47] Starting subtask 'copy-assets'...
[10:10:47] Error - [copy-assets] Error: Invalid glob argument:
[10:10:47] Error - 'copy-assets' sub task errored after 114 ms
 Invalid glob argument:
[10:10:47] 'bundle' errored after 1.05 min
[10:10:47]`

**Comment by IsmaelDev1** [comment]
Hi,

Using the new update, I have updated all my resources to the required version, but when I try to build it I got the same error that you posted in a comment.

`Error - [lint] Unexpected STDERR output from ESLint: DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.`

**Comment by petkir** [comment]
@IsmaelDev1  thanks for testing, this warning was not relevant in `gulp serve`

In the devDependencies to `eslint` had the wrong version, and it is not required to be in the devDependencies.
So I change the `package.json` and I upgraded to 1.17.3 (why stay on an old version).

* node 16 
* node-modules folder should be empty before `npm install`

I'm waiting on your feedback, good night  😄

**Comment by IsmaelDev1** [comment]
Hi @petkir,

Using the latest update I was able to build the project, thanks for your help.
