### ISSUE TITLE
Display react-dashboards sample in https://pnp.github.io/sp-dev-fx-webparts/

### ISSUE THREAD

**Issue by kkazala** [pnp/sp-dev-fx-webparts#3781]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-dashboards

### Contributor(s)

@kkazala

### Question

My PR has already been approved 3 weeks ago but I still don't see my WebPart on the samples list. 
Could you let me know if I still have to do something?

thx!

**Comment by hugoabernier** [comment]
thanks for bringing it to my attention. Issue is now fixed.
