### ISSUE TITLE
Rhythm of Business Calendar does not show sunday events

### ISSUE THREAD

**Issue by dignus93** [pnp/sp-dev-fx-webparts#3787]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-rhythm-of-business-calendar

### Contributor(s)

@d-turley

### What happened?

Hello there,
I install the app from the sharepoint catalog to one of my subsite. The app worked well but I have a issue:
The events created on Sundays don't show in the app.

I can see them in the list 
https://MyTenant.sharepoint.com/sites/MySite/MySubSite/Lists/RoB Calendar Events/All RoB Events.aspx

But not in the app installed in my home mage 
https://MyTenant.sharepoint.com/sites/MySite/MySubSite

### Steps to reproduce

1. From a sharepoint subsite click on the gear top right, add an app
2. Search for Rhythm of Business Calendar (ROB), add it to your site
3. On the home page of your subsite go in edit (top right click on the pencil), 
4. Click plus button in a section, add the ROB
5. Add events on a Sunday

### Expected behavior

I must see the event on the list MySite/Lists/RoB Calendar Events and in the app installed in my page MySite

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.16.0

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

I did not clone the repo, I just install the version from the catalog

**Comment by hugoabernier** [comment]
This issue list is intended for issues with samples built in this repository. The samples in this repository are to be used as is and not supported.
