### ISSUE TITLE
Can the initial size of the react script editor webpart be defined at page loading? 

### ISSUE THREAD

**Issue by tz4g** [pnp/sp-dev-fx-webparts#3792]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor

### Contributor(s)

@waldekmastykarz
@wobba 

### Question

I have noticed that with colored section background the script editor webpart appears very high at page loading and collapses after a second or so. This is not a problem until the section background is colored, because then the whole section appears huge for a second. Is there anything I can do against it?

**Comment by wobba** [comment]
I guess adding support for colored sections might be a solution if someone looks into it and PR the support/change needed.
