### ISSUE TITLE
react-add-js-css-ref - No .sppkg package file available for download

### ISSUE THREAD

**Issue by robertcaretta** [pnp/sp-dev-fx-webparts#3845]
### Disclaimer

Yes

### Sample

react-add-js-css-ref

### Contributor(s)

Siddharth Vaghasia, Don Kirkham

### What happened?

No .sppkg file is available for download.  In the section here it mentions downloading the package from the file, but it doesn't exist. I would very much like to just download the file. 

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-add-js-css-ref#package-and-deploy

### Steps to reproduce

1. Go to this section in the documentation.
https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-add-js-css-ref#package-and-deploy
2. Click the link called "location".
3. Does not exist. 404 - page not found error.

### Expected behavior

Link is available download the pre-built .sppkg package. 
(I already have a dev environment configured for the SP Starter Kit. The requirements for this sample are different.)

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.20.1

### What version of Node.js is required by the sample?

v16 | v14 | v12

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework
 
× SharePoint Framework v1.15.2
 
Error: spfx doctor doesn't support SPFx v1.15.2 at this moment

### Additional environment details

I attempted to build this on my own but ran into some compatibility issues. 
The build failed because a task wrote output to stderr.
Exiting with exit code: 1

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/1613085/0474c715-68b4-4d50-ad15-1ce418c71576)

Using this command I have the following:  npm list -g --depth 0
├── @microsoft/generator-sharepoint@1.17.4
├── @pnp/cli-microsoft365@3.11.0
├── gulp-cli@2.3.0
├── npm@9.7.2
└── yo@4.3.1

**Comment by hugoabernier** [comment]
Sorry, the link to the .sppkg was added in error. This repository is for sample purposes only and does not provide the .sppkg. You can, however, use this sample to build your own web part.
