### ISSUE TITLE
react-add-js-css-ref - Builds but does not deploy correctly to app center

### ISSUE THREAD

**Issue by robertcaretta** [pnp/sp-dev-fx-webparts#3846]
### Disclaimer

Yes

### Sample

react-add-js-css-ref

### Contributor(s)

Siddharth Vaghasia, Don Kirkham

### What happened?

I used the Docker container method with WSL on Windows 11 to build the package.  
https://github.com/pnp/sp-dev-fx-webparts/wiki/Opening-a-sample-using-a-development-container

When I upload and deploy the .sppkg file to the SharePoint Apps admin panel I receive this error regarding validating the app manifest.
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/1613085/32370599-637e-42d3-b953-98b738733c41)

### Steps to reproduce

1.  Follow these instructions to set up a virtualized Docker workspace.
https://github.com/pnp/sp-dev-fx-webparts/wiki/Opening-a-sample-using-a-development-container
2.  Run these commands.  
gulp bundle --ship
gulp package-solution --ship
3. Upload the .sppkg file the App center.
4. Review the error

### Expected behavior

App should compile, build, and deploy without errors.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

N/A  (Virtualized via Docker, WSL, VS Code Extention)

### What version of Node.js is required by the sample?

v16 | v14 | v12

### Paste the results of SPFx doctor

-

**Comment by CollinHunterGOC** [comment]
I got the same results
