### ISSUE TITLE
react-json-form - 

### ISSUE THREAD

**Issue by makaylacmac2** [pnp/sp-dev-fx-webparts#3847]
### Disclaimer

Yes

### Sample

react-json-form

### Contributor(s)

@Tanddant

### Suggestion

I'd like to help implement a people picker field type for this webpart, and eventually a list lookup column feature, but I am new to SPFx development and I need some direction. If that can't be built into the webpart, how could I work with a choice field and javascript embedded on the page to allow the selection of people in my directory?

### Are you willing to help?

Yes

**Comment by Tanddant** [comment]
Hi @makaylacmac2 that's definitely possible!

I can absolutely implement this whenever I have time (not for at least another few weeks), but if you want to get started yourself, the [PnP Reusable controls](https://pnp.github.io/sp-dev-fx-controls-react/) is a great starting point!

The key to a person vs. lookup field is that a UserField is just a lookup field looking at the hidden 'User Information List' list that's on every site collection, so storing the ID should be enough 😊

I would love to help you learn, rather then me just doing it for you! - feel free to catch me @tanddant over on Twitter and I'll be happy to help along 😊

**Comment by makaylacmac2** [comment]
I will definitely dive into it! Thanks for your reply. I’ll get back to you when I think I’ve made progress.

Makayla Harder
________________________________

**Comment by Tanddant** [comment]
Hi @makaylacmac2,

Have you made any progress on this? 😊

Do you need help getting started?
