### ISSUE TITLE
Script does not run after adding and refreshing page

### ISSUE THREAD

**Issue by TecharyAdam** [pnp/sp-dev-fx-webparts#4004]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor

### Contributor(s)

Mikael Svenson

### Question

I am having some issues with this WebPart. May be what I am doing but would like some help to get this working.

When I put the javascript code in, it initially works, but after I refresh the page or visit the page again it then does not load the script. I was wondering if there is anything that I may be doing wrong or if you could help with this. I can provide more details when needed.

**Comment by omarelanis** [comment]
What browser are you using?
What is the output of the console debugger in the browser?
What is the code you are actually using? Are you calling a JS file or using code directly in the editor?
Are you hard refreshing the page and the script is not showing as having loaded in the the sources tab within Networking tab in Chrome/Edge browser? Or does it show as the script has been loaded but the code isn't called?

What debugging steps have you actually taken so far?

**Comment by TecharyAdam** [comment]
Hi,

Thank you for the quick reply on this. I have had a longer look at this and this was due to my code, I have now go this sorted, appreciate the swiftness on getting back to me.

**Comment by TecharyAdam** [comment]
Hi,

Thank you for the quick reply on this. I have had a longer look at this and this was due to my code, I have now go this sorted, appreciate the swiftness on getting back to me.
