### ISSUE TITLE
react-interactive-map - markers from list

### ISSUE THREAD

**Issue by swimmerbhs** [pnp/sp-dev-fx-webparts#4016]
### Disclaimer

Yes

### Sample

react-interactive-map

### Contributor(s)

@SPFxAppDev

### Question

Is there away that this sample can pull information from a specific list? 

This list contains, latitude and longitude and other items. We have office location list that needs to be plotted on a map. but it is dynamic so it should also be async.

**Comment by SPFxAppDev** [comment]
Hi @swimmerbhs,

Currently the webpart does not support aggregation of locations from a list. The web part and the settings for a location have some more information like markerColor, iconName, iconColor, type (what should happen on click) and the "content" when the marker was clicked on.

If no other items are added to the list (or updated), I'd be happy to help generate a script that reads the data from the list and then places the Maps Web Part with the correct values. But for this you have to agree on a standard "marker type". So e.g. all markers have color A and have icon B with IconColor C. When clicking always a panel opens (e.g.) and there is a content from column X

Regards

Seryoga (spfx-app.dev)

**Comment by Krodgersminto** [comment]
Hi,

Just wondering if you ever completed this request to read from a list?

Thank you

**Comment by SPFxAppDev** [comment]
Hi @Krodgersminto,

No, unfortunately not. I thought about it, but since my web part supports a variety of settings, the list should have the same settings. But since you're not the only ones who need this feature, I'll try to think of something and implement it
