### ISSUE TITLE
CssSyntaxErrors When Building

### ISSUE THREAD

**Issue by ckipr15** [pnp/sp-dev-fx-webparts#4026]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-calendar

### Contributor(s)

@Abderahman88 @Eli-Schei @hugoabernier @joaojmendes @derhallim @mohammadamer @nanddeepn

### What happened?

The calendar app looks correct in workbench, but once it's published to SharePoint, there are a couple issues with how the calendar displays.  The two issues that I notice immediately on the published calendar are:
1.  The name of the calendar month doesn't display at the top of the calendar, no matter which month you are displaying
2.  There's a blue background color for the calendar squares of the month currently displayed

There are two "problems" that appear when running 'gulp build' and 'gulp bundle --ship' that I think may be related:

**src/controls/Event/Event.module.scss
 67:8  ✖  Unknown word  CssSyntaxError

src/webparts/calendar/components/Calendar.module.scss
 158:8  ✖  Unknown word  CssSyntaxError**

The attached images show how the app looks in workbench vs. how it appears when published on a SharePoint page.
![Workbench-Calendar-Screenshot](https://github.com/pnp/sp-dev-fx-webparts/assets/50888198/a19c343b-93ce-4743-91cb-0a8f4e626da2)

![Published-Calendar-Screenshot](https://github.com/pnp/sp-dev-fx-webparts/assets/50888198/844a11c6-3abc-4a2c-b1c3-ae24e2f11829)

### Steps to reproduce

1.  Install:  Node v14.17.0, npm@6.14.13, gulp@4.0.2
2.  Execute install npm on sample
3.  Execute gulp build
4.  Execute gulp bundle --ship
5.  Execute gulp package-solution --ship
6.  Upload to app catalog, add the app to a SharePoint site, publish the calendar web part on a site page.

### Expected behavior

I would expect the workbench version of the web part to match the published version of the web part.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [X] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

14.17.0

### What version of Node.js is required by the sample?

v10

### Paste the results of SPFx doctor

Unable to run SPFx doctor at this time.

**Comment by ckipr15** [comment]
This is not a Node.js version issue, as I have tried to build the solution with many different versions of Node.js (including v10).

My issue has to do with the theme that's being used on the Site I'm publishing the calendar on.  On the calendar, the month is white text on a white background, and I'm not sure where the blue color is coming from on the calendar's background, as that blue color is not part of the Site's selected theme.

Any more assistance on this would be greatly appreciated.

**Comment by JonoSuave** [comment]
@hugoabernier @wobba do you have any suggestions? I'm running into the exact same issue as @ckipr15

**Comment by JonoSuave** [comment]
This may not be the best approach, but I ended up taking out the default colors from the _themes.scss, like so:

$ms-greenLight: "[theme:greenLight]";
$ms-neutralSecondaryAlt: "[theme:info]";
$ms-neutralLight: "[theme:infoBackground]";
$ms-magenta: "[theme:magenta]";
$ms-magentaDark: "[theme:magentaDark]";
$ms-magentaLight: "[theme:magentaLight]";
$ms-neutralDark: "[theme:neutralDark]";
$ms-neutralLight: "[theme:neutralLight]";
$ms-neutralLighter: "[theme:neutralLighter]";
$ms-neutralLighterAlt: "[theme:neutralLighterAlt]";
$ms-neutralPrimary: "[theme:neutralPrimary]";
$ms-neutralPrimaryAlt: "[theme:neutralPrimaryAlt]";
$ms-neutralQuaternary: "[theme:neutralPrimaryTranslucent50]";
$ms-neutralQuaternaryAlt: "[theme:neutralQuaternary]";
$ms-neutralSecondary: "[theme:neutralQuaternaryAlt]";
$ms-neutralSecondaryAlt: "[theme:neutralSecondary]";
$ms-neutralTertiary: "[theme:neutralSecondaryAlt]";
$ms-neutralTertiaryAlt: "[theme:neutralTertiary]";
$ms-white: "[theme:neutralTertiaryAlt]";
$ms-orange: "[theme:orange]";
$ms-orangeLight: "[theme:orangeLight]";
$ms-orangeLighter: "[theme:orangeLighter]";
$ms-primaryBackground: "[theme:primaryBackground]";
$ms-primaryText: "[theme:primaryText]";
$ms-purple: "[theme:purple]";
$ms-purpleDark: "[theme:purpleDark]";
$ms-purpleLight: "[theme:purpleLight]";
$ms-red: "[theme:red]";
$ms-redDark: "[theme:redDark]";
$ms-success: "[theme:success]";
$ms-successBackground: "[theme:successBackground]";
$ms-teal: "[theme:teal]";
$ms-tealDark: "[theme:tealDark]";
$ms-tealLight: "[theme:tealLight]";
$ms-themeAccent: "[theme:themeAccent]";
$ms-themeAccentTranslucent10: "[theme:themeAccentTranslucent10]";
$ms-themeDark: "[theme:themeDark]";
$ms-themeDarkAlt: "[theme:themeDarkAlt]";
$ms-themeDarker: "[theme:themeDarker]";
$ms-themeLight: "[theme:themeLight]";
$ms-themeLightAlt: "[theme:themeLightAlt]";
$ms-themeLighter: "[theme:themeLighter]";
$ms-themeLighterAlt: "[theme:themeLighterAlt]";
$ms-themePrimary: "[theme:themePrimary]";
$ms-themeSecondary: "[theme:themeSecondary]";
$ms-themeTertiary: "[theme:themeTertiary]";
$ms-themeTertiaryAlt: "[theme:themeTertiaryAlt]";
$ms-white: "[theme:white]";
$ms-whiteTranslucent40: "[theme:whiteTranslucent40]";
$ms-yellow: "[theme:yellow]";
$ms-yellowLight: "[theme:yellowLight]";

**Comment by mohammadamer** [comment]
@JonoSuave @ckipr15 
I think the reason why you have the blue background in the WebPart is the themes in the _themes.scss file.
Regarding the month text, it's white text on a white background on your site because most likely in your site there is another CSS style that overwrites the default style for the month text.

You can use the developer tools to inspect the styles and adjust them accordingly.
