### ISSUE TITLE
CssSyntaxErrors - Month title not displaying, blue background color instead of white

### ISSUE THREAD

**Issue by ckipr15** [pnp/sp-dev-fx-webparts#4029]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-calendar

### Contributor(s)

@Abderahman88 @Eli-Schei @hugoabernier @joaojmendes @derhallim @mohammadamer @nanddeepn

### What happened?

The calendar app looks correct in workbench, but once it's published to SharePoint, there are a couple issues with how the calendar displays.  I believe this has to do with the Theme applied to the site where the calendar is published. The two issues that I notice immediately on the published calendar are:

The name of the calendar month doesn't display at the top of the calendar, no matter which month you are displaying (white text on white background).
There's a blue background color for the calendar squares of the month currently displayed.

There are two "problems" that appear when running 'gulp build' and 'gulp bundle --ship' that I think may be related:

src/controls/Event/Event.module.scss
67:8 ✖ Unknown word CssSyntaxError

src/webparts/calendar/components/Calendar.module.scss
158:8 ✖ Unknown word CssSyntaxError

The attached images show how the app looks in workbench vs. how it appears when published on a SharePoint page.
![Workbench-Calendar-Screenshot](https://github.com/pnp/sp-dev-fx-webparts/assets/50888198/c1d8354b-3404-4a2f-8ce2-430ba20e0324)

![Published-Calendar-Screenshot](https://github.com/pnp/sp-dev-fx-webparts/assets/50888198/27b405e2-a801-4c06-92e1-ba5565ca7938)

### Steps to reproduce

1. Execute install npm on sample
2. Execute gulp build
3. Execute gulp bundle --ship
4. Execute gulp package-solution --ship
5. Upload to app catalog, add the app to a SharePoint site, publish the calendar web part on a site page.
6. Add the calendar to a page with a theme applied.

### Expected behavior

I would expect the name of the month to be visible on the top of the calendar (currently white text on a white background, only visible when highlighted), and I would expect the background color to be white, not blue.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [X] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v10

### What version of Node.js is required by the sample?

v10

### Paste the results of SPFx doctor

Unable to run SPFx doctor at this time.

**Comment by JonoSuave** [comment]
Did anyone ever find the solution to this?

**Comment by mohammadamer** [comment]
@JonoSuave 
I got the same issue locally and right now I'm trying to resolve it.

**Comment by itzsnyder** [comment]
Any progress?

**Comment by hugoabernier** [comment]
> Any progress?

Based on this chat history, it looks like @mohammadamer submitted an update that was merged on December 29th of last year. The issue is now closed.

If you're still experiencing the issue, please don't hesitate to open a new issue with more details so we can get to the bottom of this.
