### ISSUE TITLE
Users Not returning in react-directory webpart

### ISSUE THREAD

**Issue by Jburnss491** [pnp/sp-dev-fx-webparts#4035]
### Disclaimer

Yes

### Sample

react-directory

### Contributor(s)

@Abderahman88 @petkir @joaojmendes @SudharsanK

### What happened?

Certain Users are not being returned in the react-directory web part.

When i search their names they don't appear, office location they don't appear however when i search for them using the SharePoint people search in the UI, they appear in the results. 

Users with a specific officeNumber are not displaying in the react-directory webpart, When i search for that office no users are being returned

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/115488701/93545585-6ea5-43d7-86e2-97cc39cc0a8e)

However, when i replicate the search query and parameters from the console into the SharePoint UI. It returns the users from that officeNumber

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/115488701/5eb5e4ec-0713-408e-8bc6-d4a5ac83b8fd)

### Steps to reproduce

1.Go to page with Search Directory Webpart
2.Search for username
3.Search for Office location

### Expected behavior

Users to return in the react-directory web part results

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v20.7.0

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

m365: The term 'm365' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by gretchunkim** [comment]
Try this directory instead and see if your issue is reproducible: 
[sp-starter-kit people directory](https://github.dev/pnp/sp-starter-kit/blob/master/source/react-people-directory/src/webparts/peopleDirectory/components/PeopleDirectory/PeopleDirectory.tsx)

No issue on my side using the above.  

If your issue is reproducible in the sp-starter-kit, then it's likely the tenant  sp user profile data is the culprit.
