### ISSUE TITLE
react-my-approvals - Error when adding the webpart to the sharepoint page

### ISSUE THREAD

**Issue by BenjaminGournay83** [pnp/sp-dev-fx-webparts#4091]
### Disclaimer

Yes

### Sample

react-my-approvals

### Contributor(s)

@karamem0

### What happened?

When i add the webpart to the page, I get that error message:

AADSTS65001: The user or administrator has not consented to use the application with ID '155f63d3-805a-4b87-9deb-c8ade6918ed3' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.

### Steps to reproduce

1. I deployed the webpart
2. I add the webpart to a page
3. I get the error message

### Expected behavior

I am supposed to see my approvals from powerautomate

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.15.0

### What version of Node.js is required by the sample?

Node.js s v16 | v14 | v12

### Paste the results of SPFx doctor

Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.15.2
√ Node v16.15.0
√ yo v4.3.0
√ gulp-cli v2.3.0
√ bundled typescript used

**Comment by a1mery** [comment]
Did you approve the API requests after deploying the web part (Approvals.Read.All and Flows.Read.All)?
You can go there to do it: https://_yourtenant_-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement
