### ISSUE TITLE
react-directory - 

### ISSUE THREAD

**Issue by lpgru1** [pnp/sp-dev-fx-webparts#4105]
### Disclaimer

Yes

### Sample

react-directory

### Contributor(s)

@joaojmendes @petkir @sudharsank @Abderahman88

### Question

Is it at all possible to limit the People results that appear to only come from a particular group or department? I am looking for a way to display a live directory at a school, but I only want to display 'Staff' and not 'Students', however by default they all display due to all being members of the Organization.

I currently use SharePoint Term Store Taxonomy to differentiate between "Staff" and "Students" elsewhere, and I feel like this would be the optimal way to use this react-directory if I could get it to only display organization members listed as "Staff" in the Term Store?

Thank you all for the excellent community and webparts.

**Comment by petkir** [comment]
Hi @lpgru1 

Thanks for your message.
The fastest way is to customize the code of this sample
in the File ```/src/SPServices/spservices.ts```you find the method ```searchUsers``` and you can add additional query parameter for your needs to the variable ```_search```

i think the query property is ```Department``` but I'm not sure please look at your tenant ```{your ulr}/_layouts/15/listmanagedproperties.aspx?level=sitecol```

as result it should be something like this (this code is not tested)
``` 
_search += ' and Department: Staff'
``` 
The other way is to add a web part property to inject the query over the UI.
Feel free to make a contribution
