### ISSUE TITLE
USing SPServices with react-script-editor

### ISSUE THREAD

**Issue by NPrice99** [pnp/sp-dev-fx-webparts#411]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I am using SPServices to get announcements out of an Announcements list 👎 

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.SPServices/2014.02/jquery.SPServices.min.js"></script>
<script type="text/javascript"> 
  $(document).ready(function (){
   var emptyResults = "<li>There are no current announcements.</li>";
   var toShow = false;
   $().SPServices({
    operation: "GetListItems",
    async: false,
    listName: "Announcements",
    CAMLViewFields: "<ViewFields><FieldRef Name='Title' /><FieldRef Name='Body' /><FieldRef Name='Modified' /></ViewFields>",
    CAMLQuery: "<Query><OrderBy><FieldRef Name='Created' /></OrderBy>" +
               "<Where><Or><Geq><FieldRef Name='Expires' /><Value Type='DateTime'>" +
               "<Today /></Value></Geq><IsNull><FieldRef Name='Expires' /></IsNull></Or></Where></Query>",
    completefunc: function (xData, Status) {
     var itemCount = $(xData.responseXML).find("[nodeName='rs:data']").attr("ItemCount");
     if(itemCount > 0){
      toShow = true;
       $(xData.responseXML).find("[nodeName='z:row']").each(function() {
        var bodyHtml = "<li>" + $(this).attr("ows_Body");+ "</li>";
        $("#marquee").append(bodyHtml);
       });
      }
     else { 
        $("#marquee").append(emptyResults);
     }
     }
   });
    if (toShow == true) {
     $("#marquee").marquee();
    }
  }); 
</script>

<ul id="marquee" class="marquee" />

#### Observed Behavior
I am getting these errors in the Edge F12 debugger - 
SCRIPT7016: SCRIPT7016: Use of XMLHttpRequest with the synchronous flag set to true is deprecated due to its impact on user-perceived site performance.

HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)POST - https://<mytenant>.sharepoint.com/XXXX/_vti_bin/Lists.asmx

#### Steps to Reproduce
Put above script into the react-script-editor

SO can I use SPServices from within the react-script-editor.??

**Comment by hugoabernier** [comment]
@NPrice99 did you ever resolve your issue?

I'll go ahead and close it, as this issue list is intended for issues related to the SharePoint Framework web part samples.
