### ISSUE TITLE
Change the myRecentDocuments from using GraphQuery api to insights api

### ISSUE THREAD

**Issue by RobinBreman** [pnp/sp-dev-fx-webparts#416]
#### Category
- [ ] Question
- [x] Bug
- [x] Enhancement

#### Expected or Desired Behavior
Get list of recent documents

#### Observed Behavior
The myRecentDocuments sample webparts implements  the _api/search/query .. GraphQuery 
This api is discontinued per 31/8/17 [https://msdn.microsoft.com/en-us/office/office365/howto/query-office-graph-using-gql-with-search-rest-api]

Webpart should now be implementing insights  https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/insights

**Comment by narulasrinivas** [comment]
@RobinBreman - Can you please provide the sample webpart (myRecentDocuments) link?

I was looking at it at [samples ](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples) folder. Couldn't get send me link to sample webpart folder to look where we need update code.

**Comment by RobinBreman** [comment]
@narulasrinivas This issue is over 2 years old.. I don't have the exact details anymore.
Might have been this one: https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-officegraph/lib/webparts/myRecentDocuments

**Comment by narulasrinivas** [comment]
@RobinBreman - Do you still want this one to be fixed? or close from your end. 

As per my understanding, current graph api has given this api in a far better than earlier. Hope this helps.
