### ISSUE TITLE
can we reuse custom SPFx webpart?

### ISSUE THREAD

**Issue by HelloPnP** [pnp/sp-dev-fx-webparts#422]
I've created some SPFx webparts for SharePoint On Premises, i've a master page where i need to place top navigation control that would be same for all the inner or detail pages.....how can i place it on master page

**Comment by HelloPnP** [comment]
@patrick-rodgers can you please reply on it if you see the post ;)

**Comment by marcelaopimenta** [comment]
+1  same issue

**Comment by HelloPnP** [comment]
@marcelaopimenta 
actually it was my misunderstanding, we can easily apply the same SPFx webpart to any page once you deploy it.

**Comment by mindlabco** [comment]
Hello @HelloPnP,

Yes, We can use re-use SPFx web parts. Web parts work with the site and classic sites. Once you deploy the SPFx to any site, we can add that to all the pages of that site. If you want to use that web part to all subsites then there is a feature called tenant level deployment which we can set to true so it is available to entire tenant.
