### ISSUE TITLE
Error notification in "React List Form" WebPart

### ISSUE THREAD

**Issue by Ashikpaul** [pnp/sp-dev-fx-webparts#425]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
<b>React List Form WebPart</b> - When an non existing ID is entered error notification should be seen and when the ID is changed the error should go.

#### Observed Behavior
When an existing ID is entered previous error notification doesn't disappear. Clicking the cross button doesn't work.

#### Steps to Reproduce
1. Select a List.
2. Choose edit page and enter a non existing ID.
3. An error notification should be seen and now change to an existing ID. Or enter again a non existing ID. Or change the list.

![image](https://user-images.githubusercontent.com/17526871/36408137-7994a46a-1629-11e8-9c98-5b3ee3dbf9b9.png)
Sorry, I am not allowed to show you the full screenshot.

<h3>Brilliant web-part. Thank you so much.</h3> :100:

**Comment by hugoabernier** [comment]
@Ashikpaul did you ever get this issue resolved?

I'll go ahead and close this issue as it is pretty old. If you're still experiencing the issue, feel free to open a new one. Hopefully we can get a fresh set of eyes on this and help you better.

And thank you for the positive comments.
