### ISSUE TITLE
Monaco instead of TinyMCE

### ISSUE THREAD

**Issue by Danny-Engelman** [pnp/sp-dev-fx-webparts#434]
#### Category
- [ ] Question
- [ ] Bug
- [X] Enhancement

Interesting choice using TinyMCE, 
but Microsoft provides Monaco (which also powers VSCode)

https://github.com/Microsoft/monaco-editor

**Comment by AustinBreslinDev** [comment]
Monaco is a browser based code editor, TinyMCE is not aimed at that market it is aimed at users who don't know how to write code/markdown.

**Comment by hugoabernier** [comment]
@Danny-Engelman I know this is an old issue, but @PopWarner  and yours truly recently uploaded the [Enhanced List Formatting](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-enhanced-list-formatting) sample which shows using Monaco inside of a web part.

If anyone is interested in create a sample as Danny described, feel free to take this issue and submit a contribution. #SharingIsCaring
