### ISSUE TITLE
react-rss-reader - Cannot run minimal path to awsome

### ISSUE THREAD

**Issue by gabbsmo** [pnp/sp-dev-fx-webparts#4454]
### Disclaimer

Yes

### Sample

react-rss-reader

### Contributor(s)

@Abderahman88 @eoverfield @djsladi

### What happened?

```
PS C:\Users\user\Downloads\sp-dev-fx-webparts-main\samples\react-rss-reader> gulp bundle --ship
C:\Users\user\Downloads\sp-dev-fx-webparts-main\samples\react-rss-reader\node_modules\@azure\core-util\dist\index.js:259
let uuidFunction = typeof ((_a$1 = globalThis === null || globalThis === void 0 ? void 0 : globalThis.crypto) === null || _a$1 === void 0 ? void 0 : _a$1.randomUUID) === "function"
                   ^

ReferenceError: globalThis is not defined
    at Object.<anonymous> (C:\Users\user\Downloads\sp-dev-fx-webparts-main\samples\react-rss-reader\node_modules\@azure\core-util\dist\index.js:259:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\user\Downloads\sp-dev-fx-webparts-main\samples\react-rss-reader\node_modules\@azure\core-http\dist\index.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
PS C:\Users\user\Downloads\sp-dev-fx-webparts-main\samples\react-rss-reader> node -v
v10.16.3
```

### Steps to reproduce

1. Installed Node v10.16.3 on Windows 10
2. Run `npm install gulp@3.9.1 -g`, otherwise there is no global gulp available, this is the version in package.json. Seems to be a missing step in README
3. Run `npm install`
4. Run `gulp bundle --ship`

### Expected behavior

The SPFx solution being bundled.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v10.16.3

### What version of Node.js is required by the sample?

v10

### Paste the results of SPFx doctor

Cannot run SPFx doctor on Node v10.

**Comment by sknnrd** [comment]
i also ran into this exact error today and yesterday as well. I also tried hand full of other tests like running node 12 which from what I see could be the issue since node 10 doesnt have globalThis apparently from posts I have seen, I also tried troubleshooting through spfx doctor and did build through dev containers as well.

**Comment by tristian2** [comment]
i have this problem also, any fix?

**Comment by eoverfield** [comment]
I just submitted a PR (https://github.com/pnp/sp-dev-fx-webparts/pull/4692) that upgrades the rss reader to spfx 1.18.2 and Node V18. This worked much better for me. Let us know how this goes once the PR has been merged.
