### ISSUE TITLE
Using axios vs AadHttpClient tapping into AAD Secured API in react-apim-tablestorage - 

### ISSUE THREAD

**Issue by gretchunkim** [pnp/sp-dev-fx-webparts#4459]
### Disclaimer

Yes

### Sample

react-apim-tablestorage

### Contributor(s)

@ejazhussain

### Question

I'm also trying to utilize API Management Service to expose API in SPFX and came across using AadHttpClient, HttpClientResponse while the API Management Service is considered Azure AD-secured APIs.  

Do you have any insight to why you have chosen to use "axios" instead of using "AadHttpClient, HttpClientResponse" from '@microsoft/sp-http'? 

Thank you!

**Comment by ejazhussain** [comment]
In this case, I am using public endpoint of the Azure API management which is secured using the inbound policies. There is no direct connection between the Azure AD app and the API management.

So, I am using `context.aadTokenProviderFactory` to grab the token and then passing the token as well as subscription key to call the API management public endpoint. I chose to use `axios` for API requests. You can use `this.context.httpClient`
