### ISSUE TITLE
react-list-search - Caml Query

### ISSUE THREAD

**Issue by xescjpp** [pnp/sp-dev-fx-webparts#4460]
### Disclaimer

Yes

### Sample

.

### Contributor(s)

.

### What happened?

Hello:

When I use caml query, some fields in list doesn't show their values, specially multichoice values, also taxonomy
I use following query:

`<View><ViewFields><FieldRef Name='Title'/><FieldRef Name='Estat'/></ViewFields><Query><Where><Eq><FieldRef Name="Estat"/><Value Type='Choice'>enviada</Value></Eq></Where></Query></View>
`

Anybody knows what's happening?

Thank you very much.

### Steps to reproduce

1.
2.
3.
er

### Expected behavior

.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [X] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

.

### What version of Node.js is required by the sample?

.

### Paste the results of SPFx doctor

.

### Additional environment details

.

**Comment by ac33y** [comment]
if this package is still the same as last year, the issue that i encountered on CAML query might still be happening. Anyway, i have a reply on this issue https://github.com/pnp/sp-dev-fx-webparts/issues/1804 where i included option to fix it, Hope it helps you in anyway
