### ISSUE TITLE
react-birthdays - Doesn't present the information

### ISSUE THREAD

**Issue by IvanRamos01** [pnp/sp-dev-fx-webparts#4484]
### Disclaimer

Yes

### Sample

react-birthdays

### Contributor(s)

@smaity @joaojmendes

### What happened?

Hi, I've followed the steps in the file and successfully added the app to the tenant's SharePoint site, the web part appears blank when added to a site page.

![Screenshot 2023-11-25 093326](https://github.com/pnp/sp-dev-fx-webparts/assets/151647475/635f92b4-d4d9-4b99-869d-391eea2ac3d9)

### Steps to reproduce

1. Create a list in the contents of the tenant index with the name "Birthdays" and the required columns:

![imagen](https://github.com/pnp/sp-dev-fx-webparts/assets/151647475/8872b65b-4654-433b-af62-5ddf2f0a4204)
![imagen](https://github.com/pnp/sp-dev-fx-webparts/assets/151647475/4de34894-70ac-4080-aae1-03cb32827d03)
![Screenshot 2023-11-25 093951](https://github.com/pnp/sp-dev-fx-webparts/assets/151647475/fd9a2358-4f70-4b6b-84c4-185231d2086b)

### Expected behavior

1. Expect entries to show per day, but nothing ever fills up.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

14

### What version of Node.js is required by the sample?

v16 | v14

### Paste the results of SPFx doctor

No response

**Comment by PrinsMild** [comment]
Have you tried to change to '2000' as the year of ANY birthday in the list? That was the issue for me.

**Comment by IvanRamos01** [comment]
Yes!
