### ISSUE TITLE
react-advanced-page-properties - Script Error

### ISSUE THREAD

**Issue by PretoPlasma** [pnp/sp-dev-fx-webparts#4490]
### Disclaimer

Yes

### Sample

react-advanced-page-properties

### Contributor(s)

@Abderahman88 @mhomol

### What happened?

When adding the web part to a website this error occurs directly in the edit mode:
```
TECHNISCHE DETAILS
FEHLER: 
Script error for: bdbcb04e-9c90-4adb-b0f0-d025e4eb6cb5_0.0.1/AdvancedPagePropertiesWebPartStrings
http://requirejs.org/docs/errors.html#scripterror
AUFRUFLISTE: 
Error: Script error for: bdbcb04e-9c90-4adb-b0f0-d025e4eb6cb5_0.0.1/AdvancedPagePropertiesWebPartStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_8d5ae3ea9dc6345216d587991e6f37d7.js:1:1), <anonymous>:8:252)
at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_8d5ae3ea9dc6345216d587991e6f37d7.js:1:1), <anonymous>:30:244)
```

### Steps to reproduce

1. Open Website in edit mode
2. Select and Add WebPart

### Expected behavior

There should not be an error message.
The webpart should be available for further usage.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

16.14.2

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

```
D:\projects\m365\sp-dev-fx-webparts\samples\react-advanced-page-properties>m365 spfx doctor -o 
text
 
CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.16.1
√ Node v16.14.2
√ yo v4.3.1
√ gulp-cli v2.3.0
√ bundled typescript used
```

**Comment by PretoPlasma** [comment]
Hello!
Possibly you are very busy working on issue or just have missed out this one here.
However we are really looking forward for any help to get this particular web parts running.
Is there any chance to get any reply soon?
Regards,
pp

**Comment by PretoPlasma** [comment]
Hello @hugoabernier it is now more than 2 weeks ago that I have posted this issue and it is know one week ago that you have worked on it - as far as i can see.

Do you have any update for me on that issue? We really like to use your webpart however we do not know how to solve this error message. Any help or hint is highly appreciated.
Kind regards,
pp

**Comment by hugoabernier** [comment]
No updates, because I simply review issues once in a while to make sure they are accurate and that the original author is tagged, because ultimately they are the best people to help you here.

Unfortunately, all the people who participate in the repository, including v me, volunteer their time to do so. There are no SLAs around how quickly your issue will get resolved -- if it can get resolved.

Our best hope is that the original author will receive the notification caused by your initial @ mention, and that they'll take time to help you

Best of luck!

**Comment by mhomol** [comment]
I'm sorry guys, I'm woefully behind on keeping up with this web part and I'm keenly aware that it needs updating for the newest versions of SPFx and PnPjs.  I'm also just very swamped right now with some important customer work within Dataverse.  I have not even looked at this issue to try and diagnose what it is.  I've put it on my list of to-do's and I wish I could give you a timeframe, but unfortunately, I can't right now.

**Comment by hugoabernier** [comment]
Hi @mhomol no worries at all. I was not trying to pressure you, but instead to manage expectations. We understand that you're busy and have other priorities. 

Thank you again for all the good work you do in this community, we're lucky to have you among us!

**Comment by mhomol** [comment]
@hugoabernier , thank you so much and I totally understand.  I don't mind a little fire being lit. :) Still, @PretoPlasma , I can't make any promises, but it is on my radar now :)

**Comment by PretoPlasma** [comment]
@hugoabernier and @mhomol : thank you very much for your kind and honest reply. I am very happy to know that you have it on your radar! :) As a professioinal web app developer on nuxt3 I really understand what you are talking about and I really admire what you all achieve as volunteers. So don't worry and best wishes to you. :)
