### ISSUE TITLE
Create Page Dialog shows "Script editor web part" as App Page

### ISSUE THREAD

**Issue by paxvas2023** [pnp/sp-dev-fx-webparts#4500]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-script-editor/README.md

### Contributor(s)

wobba

### What happened?

While creating a new page a new tab "APPS" is presented and in it the "Script editor web part" as App Page. As this is misleading customers and me please explain, why this is visible here.
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/128728143/847c753a-d856-4985-9ac2-970973da6723)

### Steps to reproduce

1.Deployed "Script editor web part" in Tenant
2.Create Page on communication page 
3.Choose "Apps" Tab
4.Here the Webpart is visible as App Page

### Expected behavior

I expect to see the webpart only in the edit page dialog while inserting webparts.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

-

### What version of Node.js is required by the sample?

-

### Paste the results of SPFx doctor

-

### Additional environment details

-

**Comment by Tanddant** [comment]
This makes sense for some scenarios (i.e you want to built a full page experience, where you're in charge of everything)

You can remove the `SharePointFullPage` from the `supportedHosts` in the web part manifest [here](https://github.com/pnp/sp-dev-fx-webparts/blob/8d3b71495f1469668523076967baf512bc9e2a6a/samples/react-script-editor/src/webparts/scriptEditor/ScriptEditorWebPart.manifest.json#L9C46-L9C64)

**Comment by paxvas2023** [comment]
Hi,

Thx for the help and the information.

Kind regards janko
