### ISSUE TITLE
react-utility-extensions - Question about Package Availability

### ISSUE THREAD

**Issue by chasquad** [pnp/sp-dev-fx-webparts#4503]
### Disclaimer

Yes

### Sample

react-utility-extensions

### Contributor(s)

@HarminderSethi

### Question

Hi,  I really appreciate the community and the solutions that you and others provide.  I'm not a developer, just an old SP admin.  I don't understand the SharePoint Framework.  I do know how to add solution packages!  Do you know if a solution package is available for the react utility extension?  It would be so nice to have the option to copy the item path!  Thanks!

**Comment by HarminderSethi** [comment]
Hi @chasquad , Thanks for appreciating the work. I understand your problem so to make it easy for you, I have published the sample with the solution package on my personal respository. You can find the solution file(.sppkg) from [here](https://github.com/HarminderSethi/SPFx-Samples/tree/main/react-utility-extensions/sharepoint/solution). Please let me know if you face any issues. I will be happy to help :)

**Comment by chasquad** [comment]
Thanks so much!  Take care.
