### ISSUE TITLE
react-aad-implicitflow: Callback is not called after trying to get graph token in Internet explorer

### ISSUE THREAD

**Issue by jpdc-developer** [pnp/sp-dev-fx-webparts#453]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I am making a SharePoint web part on a classic SharePoint page that has the same structure as react-aad-implicitflow. In Internet Explorer 11, after executing `this.authCtx.acquireToken(graphResource, (error: string, token: string)` from `getGraphAccessToken()`, the callback does not get called. I expect it to get called, then the token (or error) be accessible from inside the callback. It works in Google Chrome.

#### Observed Behavior
Testing on IE on a classic page. Callback is not being called back with token or error. Setting a break point inside the callback does not get hit in IE but gets hit in Chrome.

#### Steps to Reproduce

1. Make a classic SharePoint page.
2. Use the sample react-aad-implicitflow. Set it up using [these instructions](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-aad-implicitflow)
3. Add your webpart to your classic page.
4. Open in IE 11.
5. Set a break point inside the callback of 
```
this.authCtx.acquireToken(graphResource, (error: string, token: string) => {
        if (error) {
          reject(error);
          return;
        }
        if (token) {
          resolve(token);
        }
        else {
          reject('Couldn\'t retrieve access token');
        }
      });
```
6. It will not get hit.

**Comment by hugoabernier** [comment]
@jpdc-developer did you ever resolve this issue?

I'll go ahead and close it this issues list is intended for issues with the SPFx Web Part samples.

If you're still running into this issue, feel free to open a new issue in the [sp-dev-docs](https://github.com/sharepoint/sp-dev-docs) issue list.
