### ISSUE TITLE
api-scopes tutorial - the reply address does not match

### ISSUE THREAD

**Issue by tnsholding** [pnp/sp-dev-fx-webparts#461]
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Trying to use the tutorial api-scopes (https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/tutorials/api-scopes) and follow the guide https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial. 

Expecting to see the web-part working in the workbench.

#### Observed Behavior
When running the webpart in the workbench on my test tenant (using the AadHttpClient), I keep getting the following error when the webpart launches pop-up to authenticate:

> AADSTS50011: The reply address 'https://dev365x889872-admin.sharepoint.com/_forms/spfxsinglesignon.aspx' does not match the reply addresses configured for the application: 'c58637bb-e2e1-4312-8a00-04b5ffcd3403'. More details: not specified

#### Steps to Reproduce
Download source from https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/tutorials/api-scopes and follow guide from https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial to load webpart in workbench.

**Comment by waldekmastykarz** [comment]
Does it fail only when using the AsdHttpClient or also when using the MSGraphClient?

**Comment by cveld** [comment]
@tnsholding @waldekmastykarz It looks like I figured it out. Refer to the instruction on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient section "Deploy the solution and grant permissions".

After having deployed the app to the Tenant App Catalog. I went to the SharePoint Admin Center's API Management section and spotted a pending approval of the required Graph API permission for our app. After having approved this pending approval, the app was suddenly able to query the Graph API. 

What I am wondering, can we conclude that to have the required permissions be approved, it is required to have deployed at least one app requesting these and confirm the pending approvals?

**Comment by waldekmastykarz** [comment]
By default, you have no permissions to MS Graph or any other services secured with AAD. The error message seems confusing for this scenario, but it could be indeed that it's how SharePoint responds if you try to retrieve an access token and you've never approved any permissions.
