### ISSUE TITLE
Cannot make ListView command button dynamic based on pnp REST sp-pnp-js

### ISSUE THREAD

**Issue by Naveenrerd** [pnp/sp-dev-fx-webparts#466]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I would like to add a list view command set button dynamically based on the selected row

#### Observed Behavior
The button is not being shown/hidden dynamically

#### Steps to Reproduce
I'm using @microsoft/sp-listview-extensibility. I used the tutorial from [link](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api). 
I'm checking if the selected row is present in **FavouritesList**(a SP list having all the favourite files/folders). If present, donot show the button else show the button. PFB the piece of code under **onListViewUpdated** method.

```
const addFavButton: Command = this.tryGetCommand('AddFavourite');
addFavButton.visible = false;
var selectedFavInList;

if (addFavButton) {
  if (event.selectedRows.length === 1) {
    var url = this.context.pageContext.web.absoluteUrl;
    let web = new Web(url);
    web.currentUser.get().then((user) => {
      this.currentUserId = user.Id;
      web.lists.getByTitle(FavouriteSource).items
       .filter("(UserNameStringId eq " + this.currentUserId + ")")
        .select("FolderUri,Id").get().then(favItems => {
            this.favouriteItems = favItems;
            selectedFavInList = jQuery.grep(this.favouriteItems, favItem => {
                return favItem.FolderUri == event.selectedRows[0].getValueByName("FileRef");
            });
            
            if (selectedFavInList.length > 0) {
            addFavButton.visible = false;
            }
            else {
            addFavButton.visible = true;
            }
        });
    });
  }
}
```
Please help me understand how to accomplish the same.

**Comment by hugoabernier** [comment]
@Naveenrerd did you ever resolve this issue?

I'll go ahead and close it as this issue list is intended for issues with SharePoint web part samples. If you're still experiencing issues, feel free to open a new issue in the https://github.com/pnp/sp-dev-fx-extensions issue list.
