### ISSUE TITLE
React Yammer API webpart, cannot authenticate

### ISSUE THREAD

**Issue by MFSWE** [pnp/sp-dev-fx-webparts#467]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

I've developed a webpart that gets Yammer conversations through the Yammer API. I'm using your YammerProvider code. Everything works fine except for the authentication. Every time a user opens his browser he is prompted to login to Yammer. Navigating to Yammer.com automatically authenticates the user. If reloading the page with my webpart the login prompt disappears and conversations are shown. Clicking the login button will also work but i do not want the user to need to login each time he opens his browser.

When using the built in MS Yammer webpart this does not happen. Conversations are loaded immediately without a login prompt.

According to the comments in the YammerProvider.ts the "_iframeAuthentication" function is the same as the one used in the built in MS Yammer webpart. When calling this function i get a CORS error. Why would my webpart work differently than the built in webpart?

Note that we do **not** have Enforce Office 365 Identity enabled.

**Comment by VelinGeorgiev** [comment]
The iframe authentication would not work if `Yammer Office 365 Identity Enforcement` is *disabled*.
