### ISSUE TITLE
react-news-extension - Missing metadata tags

### ISSUE THREAD

**Issue by whiteprw** [pnp/sp-dev-fx-webparts#4681]
### Disclaimer

Yes

### Sample

react-news-extension

### Contributor(s)

@ejazhussain

### Question

Hi, web part deploys and pulls through, metadata filters show. Can even occasionally get the news to show however they are never tagged with the relevant metadata properties. Are there particular settings the Managed property needs to make this work?

Thanks
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/140618885/4b806d51-fb20-4caf-84a7-8838539ae80f)

**Comment by ejazhussain** [comment]
@whiteprw   

If I understand correctly, some news pages are being shown in a web part even though pages are not tagged with relevant metadata. 

1. Can you confirm you have your preference saved in the Graph Extension?
2. Clear your cache to fetch the fresh preference from Graph
3. I have not created any managed property. Instead, I am using the following one which is get created automatically for your metadata site column.

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/19267065/428518cd-8d98-4fe4-be4f-cf346c7f0026)


I hope the above helps. Let me know if you still experience any issue

**Comment by ejazhussain** [comment]
@whiteprw   

If I understand correctly, some news pages are being shown in a web part even though pages are not tagged with relevant metadata. 

1. Can you confirm you have your preference saved in the Graph Extension?
2. Clear your cache to fetch the fresh preference from Graph
3. I have not created any managed property. Instead, I am using the following one which is created automatically for your metadata site column.

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/19267065/428518cd-8d98-4fe4-be4f-cf346c7f0026)


I hope the above helps. Let me know if you still experience any issue

**Comment by whiteprw** [comment]
Thanks for getting back to me - using any property in this area doesn't
bring the item through into search.

Whats the best way to debug this?


[image: image.png]
[image: image.png]

Thanks again
Cheers
Peter

**Comment by ejazhussain** [comment]
I would suggest to SharePoint Search Query tool to confirm that your data is available in the search and tagged properly. See below link

https://github.com/pnp/PnP-Tools/releases/tag/v2.10.0-Search-QueryTool

Once your content is available within the Search then you can construct the Search query within the react-news-extension sample.

I hope this helps
