### ISSUE TITLE
REACT-ACCORDION - 

### ISSUE THREAD

**Issue by Nee4ok** [pnp/sp-dev-fx-webparts#4700]
### Disclaimer

Yes

### Sample

REACT-ACCORDION

### Contributor(s)

@AbhishekGarg @gautamdsheth

### Question

Hello,
How do I build this into an app to be used in SharePoint online.
Please forgive me. I am a newbie!!
Thank you in advance.

**Comment by a1mery** [comment]
Hi,

You can follow steps there: [Minimal Path to Awesome](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion#minimal-path-to-awesome).

And if you want more guidance, you can read this really useful article: [SharePoint Framework - Getting started](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant)
