### ISSUE TITLE
react-fluentui-9 - SPFx 1.18 compatibility with react 17 and Fluent 2 (v9) -> console errors.

### ISSUE THREAD

**Issue by eskildbrobak** [pnp/sp-dev-fx-webparts#4744]
### Disclaimer

Yes

### Sample

react-fluentui-9

### Contributor(s)

@techienickb

### Question

![Screenshot 2024-02-21 at 08 50 11](https://github.com/pnp/sp-dev-fx-webparts/assets/159005563/853c0212-a6c1-44d2-8d92-b44812fce22c)

When using Fluent 2 and the component Accordion I get this error on my extension. Have you encountered this before? I am also using some components from fluent 1 (v8), maybe that has something to do with it. I just wanted to know if you've experienced something similar before.

**Comment by techienickb** [comment]
Fluent 2?  Do you meant fluent 9?  If so you may want to see if there is an issue on the fluent ui 9 issues list.  I've not seen this issue personally

**Comment by eskildbrobak** [comment]
Yeah I meant fluent 9, Ill check out the issues list. Okey, thanks!
