### ISSUE TITLE
react-list-form webpart multi lookup field

### ISSUE THREAD

**Issue by isawek** [pnp/sp-dev-fx-webparts#476]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

It should be possible to select multiple values for a multi lookup column.

## Observed Behavior

It works fine if i only select one option but if i try to select multiple values, the second checkbox is not checked and after deselecting the first option, no checkbox can be checked.

## Steps to Reproduce

- Create lists
- Create a list-column of type lookup 
-- Select an other list with some items in it
-- Select "allow multiple values",
- Select the created list in the web part config and try to select multiple values in the webpart

 **Thank you for your help : )**

**Comment by isawek** [comment]
i noticed that in the "src\webparts\listForm\components\formFields\SPFieldLookupEdit.tsx" the var oldValues var has wrong values on the third update.

my values look like this:

### first select as expected:
[]

### second select as expected:
[
{ key: 1, text: 'FirstValueText' }
]

### third select:
[
     { key: 1, text: 'FirstValueText2' },
     { key: NaN, text: 'SecondValueText' }
]

so the key of the second selected item was addet to the text of the first and its own key is NaN...
@VesaJuvonen  do you have an idea?

**Comment by hugoabernier** [comment]
@isawek did you ever resolve this issue?

I'll go ahead and close this issue as it is pretty old. If you're still experiencing problems, feel free to open a new issue and hopefully we can get a fresh set of eyes on this and get you the help you deserve.
