### ISSUE TITLE
Error when trying to run api-scopes webpart

### ISSUE THREAD

**Issue by georgechr** [pnp/sp-dev-fx-webparts#482]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Expected result: api-scopes webpart runs and fetches user's data using Graph API

## Observed Behavior

Actual result: api-scopes webpart fails locally with:
"This operation cannot be performed until the AadTokenProvider is initialized."
and on Sharepoint Online with:
"The requested operation is part of an experimental feature that is not supported in the current environment."

## Steps to Reproduce

1. Checkout repository
2. npm install
3. gulp serve

**Comment by hugoabernier** [comment]
@georgechr did you ever get this issue resolved?

I'll go ahead and close this issue as it is pretty old. If you're still having problems with this, feel free to open a new issue and, hopefully, we can get a fresh set of eyes to look at this and get you the help you deserve.
