### ISSUE TITLE
SPFx React Slide Swiper :: Swiper is not a constructor

### ISSUE THREAD

**Issue by EA12** [pnp/sp-dev-fx-webparts#483]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Should be initialize

## Observed Behavior

Uncaught (in promise) TypeError: request_provider_service_1.Swiper is not a constructor

## Steps to Reproduce
I adobted the [sample ](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-slide-swiper) to a SPFx React-WebPart. 

At first, I have a shared Library ("componentType": "Library") where I installed [Swiper ](http://idangero.us/swiper/get-started/) by npm i swiper --save

As Swiper exports its module by export={...}, I need to reexport Swiper in the index.ts of my shared library:
`export import Swiper = require("swiper");`

I ran gulp build, gulp bundle --ship and npm pack.

I then installed the .tgz of my shared library to a SPFx-Web-Part-Project (React).

In my package-lock.json I can find swiper, swiper types and my library.

`"swiper": {
      "version": "4.2.2",
      "resolved": "https://registry.npmjs.org/swiper/-/swiper-4.2.2.tgz",
      "integrity": "sha512-cyAhdc8vyz2H0dXOYFSvrCJHsj/JH1p41nwTEyvNZXYR8ssIGTBOSR3xdpJ0dF1UGowLcctjG8jXBdz/+Q1rmg==",
      "requires": {
        "dom7": "2.0.5",
        "ssr-window": "1.0.0"
      }
    }`

`"@types/swiper": {
      "version": "4.2.0",
      "resolved": "https://registry.npmjs.org/@types/swiper/-/swiper-4.2.0.tgz",
      "integrity": "sha512-ILd+xcg+Ui+XOt0rxH3W0I0Z6kYgTaMDL1fbaVUMHphCyGuu3W0/jefxd9rgzOyOaMsxrDdWsRi0fBaZAkPCdA=="
    },`

`"request-provider-service": {
      "version": "file:../removed for brevity/request-provider-service-0.0.1.tgz",
      "integrity": "sha512-O7UpstUB3hohJlSqs8oG3bXdQBCko5/aTl1A2cHLLuw7t0Z0ovNkcYsPbjGUn7B+iDwOjGSejxsVCam0B71xCg==",
      "requires": {
        "@microsoft/sp-core-library": "1.4.1",
        "@microsoft/sp-lodash-subset": "1.4.1",
        "@microsoft/sp-office-ui-fabric-core": "1.4.1",
        "@microsoft/sp-webpart-base": "1.4.1",
        "@types/swiper": "4.2.0",
        "@types/webpack-env": "1.13.5",
        "axios": "0.18.0",
        "lodash": "4.17.5",
        "moment": "2.22.1",
        "sp-pnp-js": "3.0.7",
        "swiper": "4.2.2"
      }`

In my WebPart I then Import Swiper from my library
`import { Swiper } from "request-provider-service";`

If I then try to let Swiper do its Job by calling following from componentDidMount() in my component:
`let oSwiper = new Swiper(`.container-${this.uniqueId}`, storeState.dataReducer.swiperOptions);`

i get: Uncaught (in promise) TypeError: request_provider_service_1.Swiper is not a constructor

If log the Swiper before I try to create the instance to the console I get:
 {default: ƒ, __esModule: true}
	default:class Swiper
	__esModule:	true
	__proto__:	Object

## Submission Guidelines

There must be something wrong in the way I try to use Swiper in a library to share this amongst multiple Webparts (to resize the solution bundle size and improve Site Page load times).

**Comment by VelinGeorgiev** [comment]
If you download the ReactSlideSwiper sample and run `npm i`, it should work just fine, no additional imports are needed. I am not quite sure why are you trying to import it like `import { Swiper } from "request-provider-service";`. I am almost sure that if you use `const Swiper = require('swiper/dist/js/swiper.min');` instead of `import { Swiper } from "request-provider-service";` that will work properly.

**Comment by VelinGeorgiev** [comment]
Since Swiper is added as non module, it could be tricky to turn it into a module and reference it as module. I have not done that so far. 

Another way to reduce the size is with custom build of Swiper http://idangero.us/swiper/api/#custom-build, will still bundle it, but the swiper js file will be smaller size if you build it with just the stuff you need.

**Comment by EA12** [comment]
Yes, I saw this. To me it looks like an almost one year old post. And as I said, we have a library running on serveral tenants (not Workbench). Sorry, I don't get it :(

**Comment by EA12** [comment]
Hi Velin, besides the 'componentType' it should work to export swiper as a module.
From the index.d.ts of swiper you can seen that the Swiper-Class is exported like so:
`module 'swiper' { export = Swiper; }`

So, What might be the reason that although the class is exported by
`export import Swiper = require("swiper");` within my library and I can see all
properties while debugging my webpart, I cannot instantiate the class?

My understanding of exporting and importing modules is missing something?
Any hint is appreciated.

**Comment by EA12** [comment]
Hi Velin,
I decided to remove swiper from my library and added it directly to my webpart. I can confirm that swiper is working if I use it like you do it in your demo.

Sorry, for disturbing you..
