### ISSUE TITLE
The Advanced Comments Box solution did not work for the users with the read access. 

### ISSUE THREAD

**Issue by tatikhokh** [pnp/sp-dev-fx-webparts#4830]
### Disclaimer

Yes

### Sample

Advanced Comments Box

### Contributor(s)

Sergey Shiroky

### Question

Is it possible to make it work for users with the read access without providing them the edit permissions?  Thank you.

**Comment by Sandeep-FED** [comment]
Hi @tatikhokh,

Try creating a new permission level to allow create & view items, by restricting edit & delete.
