### ISSUE TITLE
Create a Deprecated folder for samples

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/sp-dev-fx-webparts#489]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Create a Deprecated folder for samples that use deprecated features or represent functionality that is now offered by default or by other tools. 
This would create a better experience when searching for samples.

**Comment by hugoabernier** [comment]
@joelfmrodrigues thanks again for this suggestion -- it was part of the inspiration for the samples browser at aka.ms/spfx-webparts.

I'll go ahead and close this issue, but if you have more ideas on how to improve this (or the samples browser), feel free to open a new issue.
