### ISSUE TITLE
If possible, another mobx sample please?

### ISSUE THREAD

**Issue by trillian74** [pnp/sp-dev-fx-webparts#505]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

Hi
I'd love if you could provide maybe another mobx sample. I'm a newbie using mobx and would love som more guidance on using it together with sharepoint fx

Ole

**Comment by bcameron1231** [comment]
Hi! There is a new sample in the repo for Mobx! Check it out! 

https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-mobx-multiple-stores
