### ISSUE TITLE
Build Error in SPF for DocumentCardExampleWebPart

### ISSUE THREAD

**Issue by lumpypuppy** [pnp/sp-dev-fx-webparts#510]
Keep getting error below when running gulp serve on Tutorial for SPF DocumentCardExampleWebPart:

![image](https://user-images.githubusercontent.com/16402918/40077764-a0ddc8bc-5850-11e8-8f7b-2eac68e855b6.png)

**Comment by hugoabernier** [comment]
Hey @lumpypuppy did you ever resolve this issue?

I'll go ahead and close it as there has been no activities here for a while. Feel free to open a new issue if you're still having troubles.
