### ISSUE TITLE
RoB Events List

### ISSUE THREAD

**Issue by EMKody137** [pnp/sp-dev-fx-webparts#5110]
### Disclaimer

Yes

### Sample

react-rhythm-of-business-calendar

### Contributor(s)

@d-turley

### What happened?

I have an Events Webpart that is in the sidebar of our Intranet site, and the RoB calendar in the main section of our homepage. The events webpart is configured so that it shows the next 10 events in the RoB Calendar Events list for the next 7 days. The issue that I have run into, is we are trying to use the calendar to display work anniversaries, but whenever an event is set up as a recurring event, they do not display in the Event webpart.

### Steps to reproduce

1. Add RoB webpart to page.
2. Add Events webpart to page and configure it to pull from RoB list.
3. Create recurring event in RoB.

### Expected behavior

Single occurance and recurring events in the RoB event list appearing in the Events webpart.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [X] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

N/A

### What version of Node.js is required by the sample?

N/A

### Paste the results of SPFx doctor

N/A, distributed through App Source

**Comment by d-turley** [comment]
It doesn't appear that the Events web part supports recurring events.
https://techcommunity.microsoft.com/t5/sharepoint/modern-page-events-web-part-missing-reoccurring-events/m-p/207009

**Comment by EMKody137** [comment]
Don't know how I didn't come across that thread in my searching, I feel like I was searching it verbatim! I guess off to find a different solution, thanks for the link @d-turley!
