### ISSUE TITLE
react-tree-orgchart - facing issue while running webpart 

### ISSUE THREAD

**Issue by abhijeetjawale1** [pnp/sp-dev-fx-webparts#5126]
### Disclaimer

Yes

### Sample

react-tree-orgchart

### Contributor(s)

@joaojmendes @petkir

### What happened?

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/97285066/e02553cd-a437-44fd-aa18-683dfc3277c1)

### Steps to reproduce

1. Cloned repo
2. npm i
3. gulp build
4. gulp serve

### Expected behavior

it should run without error and show the webparts on workbench 

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

10.24.1

### What version of Node.js is required by the sample?

Node.js LTS 10 | LTS 8

### Paste the results of SPFx doctor

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/97285066/8ca9b73e-205f-4b74-bbeb-dcee424b4bf1)

**Comment by petkir** [comment]
Hi @abhijeetjawale1 ,

thanks for your message, can you give me the output from the command line of this command?

```node --version```

greets and thank you
