### ISSUE TITLE
react-azure-openai-api-stream - 

### ISSUE THREAD

**Issue by raphking2** [pnp/sp-dev-fx-webparts#5128]
### Disclaimer

Yes

### Sample

react-azure-openai-api-stream

### Contributor(s)

@luismanez @thechriskent

### What happened?

Hi , please i this webpart works if i am running it on local workbench like running the command gulp serve and then try it on workbench it works but if i bundle and package the solution, it throws error and does work after being uploaded in app catalogue it says  something went wrong if i add the webpart to a site.
**Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Cannot read properties of undefined (reading 'id')

CALL STACK:
TypeError: Cannot read properties of undefined (reading 'id')
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0e5b786098148c2556f5398c123087e9.js:192:10989
    at new Promise (<anonymous>)
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0e5b786098148c2556f5398c123087e9.js:192:10957)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0e5b786098148c2556f5398c123087e9.js:192:13165
    at async Promise.all (index 0)**

### Steps to reproduce

1.npm install
2.gulp bundle --ship
3.gulp package-solution --ship

### Expected behavior

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Cannot read properties of undefined (reading 'id')

CALL STACK:
TypeError: Cannot read properties of undefined (reading 'id')
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0e5b786098148c2556f5398c123087e9.js:192:10989
    at new Promise (<anonymous>)
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0e5b786098148c2556f5398c123087e9.js:192:10957)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0e5b786098148c2556f5398c123087e9.js:192:13165
    at async Promise.all (index 0)

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.20.2

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

n/a

**Comment by luismanez** [comment]
can't help much, as I cannot reproduce it. However, per my experience, these kind of issues are almost always related with versions of NodeJS, or SPFx libraries. My Node version when developed the sample was 16.18.1. You can also try to stack to the exact version of the npm packages removing the caret symbol, for example:

```
    "@microsoft/fetch-event-source": "2.0.1",
    "@microsoft/mgt-react": "3.0.1",
```

Pretty sure is a versioning thing...

**Comment by SapiensID** [comment]
I'm facing the same issue. Web part works in development. When I deploy it to production, I get the same error message and the console shows something similar "TypeError: Cannot read properties of undefined (reading 'id')".  

I actually changed my dev environment to use node 16.18.1 after reading this post. After running gulp bundle --ship I was having an issue about my canuse-lit browser list being outdated. I updated it and it clear the gulp bundle --ship command. Apart from this, all the rest is the same.

This is what I get when I run spfx doctor:

[
  {
    "check": "SharePoint Framework",
    "passed": true,
    "version": "1.18.2",
    "message": "SharePoint Framework v1.18.2 valid."
  },
  {
    "check": "SharePoint Framework",
    "passed": true,
    "version": "1.18.2",
    "message": "SharePoint Framework v1.18.2"
  },
  {
    "check": "Node",
    "passed": true,
    "message": "Node v16.18.1",
    "version": "16.18.1"
  },
  {
    "check": "yo",
    "passed": true,
    "message": "yo v5.1.0",
    "version": "5.1.0"
  },
  {
    "check": "gulp-cli",
    "passed": true,
    "message": "gulp-cli v2.3.0",
    "version": "2.3.0"
  },
  {
    "check": "typescript",
    "passed": true,
    "message": "bundled typescript used"
  }
]

**Comment by luismanez** [comment]
Hi,
it's very difficult to provide any help without reproducing it. This is what I'd do:
- create a new SPFx project (react webpart)
- ensure you can deploy it and works fine (with just the code provided by the template)
- start moving code from my sample to your new webpart, bit by bit, and deploying it on each step to ensure it still works until it breaks, then provide the error here.

thanks!

**Comment by SapiensID** [comment]
I actually saw another similar reported issue (https://github.com/pnp/sp-dev-fx-webparts/issues/5305).  Basically, the problem is that the web part, as it is in the repo now, won't work because @microsoft/mgt-spfx is discontinued. 

I replaced mgt-spfx with the following, and was able to make it work in productions:

`
import {SharePointProvider} from '@microsoft/mgt-sharepoint-provider';
import { Providers } from '@microsoft/mgt-element/dist/es6/providers/Providers';
`
