### ISSUE TITLE
react-script-editor - Component ID exist in another solution

### ISSUE THREAD

**Issue by IfEyeOnlyKnew** [pnp/sp-dev-fx-webparts#5129]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@wobba @salascz @felixbohnacker

### What happened?

We have the classic version of the script editor web part, but installing the modern script editor the app packaage error message shows up: <
Component ID {3A328F0A-99C4-4B28-95AB-FE0847F657A3} exists in solution 1425175f-3ed8-44d2-8fc4-dd1497191294 already.

I did run through the instructions to Deploy.  Can I have both classic version script editor and modern? I wondering can I change the Component ID on the Modern version somewhere - https://github.com/pnp/sp-dev-fx-webparts/issues/620?

Thanks

### Steps to reproduce

Just installed in the app catalog.

### Expected behavior

Both versions work. 

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v20.12.1

### What version of Node.js is required by the sample?

v20.12.1

### Paste the results of SPFx doctor

Don't have anything to paste

### Additional environment details

Thanks for looking into this.

**Comment by IfEyeOnlyKnew** [comment]
Well, we do have the classic version of the script editor web part. I would agree with you partially, but I am getting the same issue in both our Dev and Prod tenants for M365 after installing. Can you comment on what to use to change the Guid value. 

I am not sure what you mean by " (a solution you should not use btw :) "???

![scripteditor](https://github.com/pnp/sp-dev-fx-webparts/assets/12399849/1f575710-52c9-453f-adde-e479a9c848ca)
![scripteditorfile](https://github.com/pnp/sp-dev-fx-webparts/assets/12399849/ea7ac639-1347-47d4-ac21-e28d11215233)

**Comment by IfEyeOnlyKnew** [comment]
So, I have modern script editor installed on our Development, but not the older version of script editor web part (classic). It is the opposite in our Prod tenant, but the same issue pops up for both when installing the one that is not installed.

Thanks for your response. Do you have some insights for your comment?

"...solution id of the modern script editor web part (a solution you should not use btw :)"

I am not familiar with creating a new Guid for package-solution.json. Do you have some advice?

**Comment by wobba** [comment]
What do you mean old/new? Classic has a built-in webpart, nothing to do with SPFx. The error points to an existing .sppkg being installed in your app catalog. My assumption would be under a different filename.

**Comment by wobba** [comment]
That's a SPFx modern web part used on a classic page 🙂 You can use the same web part on modern pages. No need to readd the sppkg unless you have changed some config building it (https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-script-editor/README.md#deploy-to-non-script-sites--modern-team-sites) 

You also might want to read my blog post https://www.techmikael.com/2024/03/allowing-arbitrary-custom-scripting-in.html

**Comment by IfEyeOnlyKnew** [comment]
Thank you for your comments, Mikael! I appreciate the feedback. Closing the case. 

Thank you for the links as well.
