### ISSUE TITLE
react-aad-implicitflow workaround for the login button

### ISSUE THREAD

**Issue by AMEspino** [pnp/sp-dev-fx-webparts#513]
- [x] Question
- [ ] Bug
- [ ] Enhancement

I am creating an spfx application wherein I have 2 webparts that are connecting to Azure Active Directory and both are trying to connect to Office 365 Exchange Online (Microsoft.Exchange) API particularly trying to get Calendar and Tasks. 

The Scenario: 
1. User will be signed in with their O365 account. 
2. The page will load as well as the two webparts.
3. On page load, the webparts must show me the list of tasks and calendar automatically.

I was actually able to get the data correctly by having separate authentication for each webpart using this block of code:
![image](https://user-images.githubusercontent.com/34465866/40218189-c61c1c38-5aa2-11e8-9fdb-7f10a9911376.png)

But the thing is I need to have only one authentication for the 2 webparts and save the token somewhere in the local storage and have it refreshed seamlessly when it expires. 

I tried to use ADAL.JS but unfortunately I do not need to have that login button. Is there anyway to do this?

**Comment by hugoabernier** [comment]
@AMEspino  did you ever get this issue resolved?

I'll go ahead and close this issue as it is pretty old. If you're still having problems with this, feel free to open a new issue and, hopefully, we can get a fresh set of eyes to look at this and get you the help you deserve.
