### ISSUE TITLE
TenantDomain Error

### ISSUE THREAD

**Issue by sirlaugher** [pnp/sp-dev-fx-webparts#5144]
### Disclaimer

Yes

### Sample

React-Tiles

### Contributor(s)

@hugoabernier

### Question

I am getting an error when I do gulp serve on react-tiles. The error is when the page opens I get this URL: https://{tenantdomain}/_layouts/workbench.aspx)/_layouts/workbench.aspx. I do not see a config folder in React-Tiles so I am unsure where to enter the tenantdomain for the sample. I am obviously very new to SPFx and need some guidance on this. I appreciate any help you can provide!! THANKS

**Comment by sirlaugher** [comment]
I would like to add the mentions but I see no authors listed in the readme file.

**Comment by sirlaugher** [comment]
Using version 2 of react-tiles I did not previously see

**Comment by hugoabernier** [comment]
Hello @sirlaugher, were you able to resolve this issue using version 2?

I'll go ahead and close this, but if you have more questions, please do not hesitate to open a new issue and provide more information.
