### ISSUE TITLE
how to perform programmatic redirect in spfx reactjs webpart using react-router? 

### ISSUE THREAD

**Issue by prabhat9999** [pnp/sp-dev-fx-webparts#515]
i tried to do this using react router was not able to do could you please help me out or any other way to do so.
import * as React from 'react'; 
import { browserHistory } from "react-router-dom"
 import Title from './app'

**export default class TestRoute extends React.Component<ITestRouteProps, {}> {
 handleClick = () => {
 browserHistory.push('/Title')

};
public render(): React.ReactElement<ITestRouteProps> {

    return (

        <div>
          <h1>Simple SPA</h1>
          <button onClick={this.handleClick} type="button">/*this should take me to another page
                 click me   </button>
            </div>
        );
  }
}

**Comment by hugoabernier** [comment]
Closing this issue as it relates to general SPFx dev. Feel free to re-open issue to https://github.com/sharepoint/sp-dev-docs.
