### ISSUE TITLE
react-azure-openai-connector - Not working after deployment

### ISSUE THREAD

**Issue by navasdeveloper** [pnp/sp-dev-fx-webparts#5151]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-azure-openai-connector

### Contributor(s)

@luismanez 

### Question

I am able to replicate the solution in workbench but it is not working after deployment. Can you please provide some suggestion?
I am getting "something went wrong- Cannot read property of undefined-(Read 'Id')" error.
I cloned the solution having same package.json

**Comment by luismanez** [comment]
What you mean by having the same package.json? ...

Can you try what I said here: https://github.com/pnp/sp-dev-fx-webparts/issues/5128#issuecomment-2074470740

**Comment by navasdeveloper** [comment]
I cloned the solution and ran npm install and made necessary changes. It works in local workbench. But when deployed throwing same error mentioned in above comment[https://github.com/pnp/sp-dev-fx-webparts/issues/5128#issuecomment-2074470740](url). Any suggesions

**Comment by luismanez** [comment]
My only suggestion is trying to set exact npm versions, and for that, you need to edit the package.json and leave only the version number of all packages (removing the symbols like ^ or ~, etc).
