### ISSUE TITLE
react-kanban-board - Error: Cannot find module 'node:os'

### ISSUE THREAD

**Issue by spawninho10** [pnp/sp-dev-fx-webparts#5157]
### Disclaimer

Yes

### Sample

react-kanban-board

### Contributor(s)

@RamPrasadMeenavalli @westerdaled @petkir @AJIXuMuK

### What happened?

My node version is 14.17.5 and I run npm install. This seems to run just fine. then when I run gulp serve, I get the error...
Error: Cannot find module 'node:os'
here is what my terminal looks like 
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/170979130/bc51198e-9456-4205-8b54-2970abdddeaa)

my package.json looks like this...
![image](https://github.com/pnp/sp-dev-fx-webparts/assets/170979130/b0950c66-eba4-4c90-9078-5702f782d102)

### Steps to reproduce

1. Switched to node version 14.17.5
2. run npm install
3. run gulp serve

### Expected behavior

I expected that I would be able to serve using the specified node version to my dev tenant.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v14.17.5

### What version of Node.js is required by the sample?

v14 | v12

### Paste the results of SPFx doctor

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/170979130/e9c3e5b5-a7ed-4ba7-8478-72fe7c65c6d8)

**Comment by petkir** [comment]
Hi @spawninho10,

thanks for the error Report ;-)

I can reproduce the Error 👍

**Comment by petkir** [comment]
Alter thinking about the error.

it's better to upgrade the project to SPFX 1.19.0 /Node 18 and Change PnPJSV2 to V4

Working on it

**Comment by petkir** [comment]
so I Upgraded everything, but during testing I got some strange errors with the property controls 
```module cannot be found @fluentui/lib/utils/dragdrop.js```
it's something with webpack or node 18 i don't know.

I have to take a deeper look!
First I moved that two controls to the source. This is not my preferred way, but currently a solution.

**Comment by spawninho10** [comment]
Thanks for the fix
