### ISSUE TITLE
Missing code or module

### ISSUE THREAD

**Issue by christ76** [pnp/sp-dev-fx-webparts#516]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Compile error. 
Msg: Error - typescript - src/webparts/modernCalendar/ModernCalendarWebPart.ts(310,26): error TS2503: Cannot find namespace ' FC'.

## Steps to Reproduce

run  'Gulp serve'

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by JayakumarB** [comment]
Hi @christ76 ,
It seems some node modules package is missing, did u try to delete the node_modules folder and re-install again by using command npm-install ?

**Comment by christ76** [comment]
Yes i did, i also tried to get the exact version of each package instead of the last packages and i have the same errror. are you able to compile the solution?

**Comment by hugoabernier** [comment]
Hey @christ76 did you ever resolve this issue?

I'll go ahead and close this issue as it is pretty old and hasn't had any activity for a while. If you're still experiencing this issue, please feel free to open a new web part.
