### ISSUE TITLE
react-list-search - 

### ISSUE THREAD

**Issue by vdykcj** [pnp/sp-dev-fx-webparts#5167]
### Disclaimer

Yes

### Sample

react-list-search

### Contributor(s)

@albegut

### Question

How can I configure the webpart to retrieve **more** than 5000 documents?
I have tried all the filtering options and combinations thereof but the maximum number of documents returned is 5000. The Document Library currently has 11000 documents with many more to be added.

**Comment by albegut** [comment]
Hi @vdykcj ,the current development only gets the first 5000 items in the list. This is done for performance and to simplify the filtering functionality of the component.   

All the elements (up to the limit of 5000) are obtained and the component is in charge of filtering.

Sorry for the inconvenience
