### ISSUE TITLE
Script editor web part for modern pages stopped working

### ISSUE THREAD

**Issue by snailCorpse** [pnp/sp-dev-fx-webparts#5179]
### Disclaimer

Yes

### Sample

Script editor web part for modern pages

### Contributor(s)

@waldekmastykarz

### What happened?

Script Editor no longer works as expected. Started 1st July. 

Script manager displays blank gaps in page where there would be the result of the javascript editor. When you edit the page, the webpart does not load correctly, and when you configure the part, the error message 

"No settings available. The web part or dashboard card using this property pane was deleted."

Cannot add the editor again, as it is no longer displaying in the list of webparts to add. However in the application catalog the webpart is still showing as added and enabled

### Steps to reproduce

1. Load webpage that has modern web editor added
2. Click on edit page
3. Select webpart and click the pencil icon

### Expected behavior

On edit page, I expect to see the heading of Modern Javascript editor, and be able to configure the javascript when clicking the pencil icon

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

18

### What version of Node.js is required by the sample?

18

### Paste the results of SPFx doctor

not run

### Additional environment details

none

**Comment by mrzosia** [comment]
I am also experiencing the same issue across multiple sites.

**Comment by icusick** [comment]
We are also experiencing this issue.

**Comment by BlazeOfFeathers** [comment]
Microsoft has updated its settings related to custom scripts. From now on, custom scripts will only remain active for 24 hours. When you activate this feature, the custom script will be available again, but only for a 24-hour ...

**Comment by TheOlfer** [comment]
found this: https://learn.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script

**Comment by debresnick** [comment]
I've tried using Powershell but it still disables after 24 hours. Does anyone know of a way to make it retain the setting?

**Comment by gdelgiovine** [comment]
What version are you using? The one that allow to load the script from URL?

**Comment by spg-iwilson** [comment]
You should be able to prevent the 24 hour reset by using:

`Set-SPOTenant -DelayDenyAddAndCustomizePagesEnforcement $True`

This will stop working from November 2024
