### ISSUE TITLE
react-calendar - 

### ISSUE THREAD

**Issue by ebentivegna** [pnp/sp-dev-fx-webparts#5190]
### Disclaimer

Yes

### Sample

react-calendar

### Contributor(s)

@Abderahman88, @Eli-Schei, @mohammadamer, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### Question

Does this calendar support searching of events by keywords?

**Comment by mohammadamer** [comment]
Hi @ebentivegna,

Currently the calendar webpart supports filtering events by category.

https://github.com/user-attachments/assets/2227fd99-b63f-4275-b41a-b509d1625973
