### ISSUE TITLE
Twitter feed not appearing on React Twitter webpart after configuring profile.

### ISSUE THREAD

**Issue by vaibhavgg** [pnp/sp-dev-fx-webparts#5191]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-twitter

### Contributor(s)

Alex Terentiev, Reshmee Auckloo

### What happened?

We built the React Twitter webpart and tried it from local workbench. We got the property pane and configured the profile. But its not showing any feed in webpart.

We are getting error as per attached screenshot in chrome console.
![MicrosoftTeams-image (4)](https://github.com/user-attachments/assets/e265d863-1921-401d-907d-3d04f0b5e470)

Is it because Twitter (X) 's new policy? 

### Steps to reproduce

1. Build and deploy solution.
2. Try on local workbench

### Expected behavior

See the twitter feed of the profile entered.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

16.17.1

### What version of Node.js is required by the sample?

v16.13+

### Paste the results of SPFx doctor

-

### Additional environment details

-

**Comment by AriGunawan** [comment]
I just checked out and ran the code on my local machine. It's working as expected.
How did you configure the web part? I can try to apply the same configuration locally to see the results.
![Web capture_1-9-2024_202216_784h80 sharepoint com](https://github.com/user-attachments/assets/f80d2adb-a4ab-4309-9476-974004acb8e8)
