### ISSUE TITLE
react-script-editor - Will this still work post November 2024?

### ISSUE THREAD

**Issue by LeonArmston** [pnp/sp-dev-fx-webparts#5204]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@wobba @salascz @felixbohnacker

### Question

Hi

https://learn.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script

I have used the Modern Script Editor webpart in the past with a few clients in Modern Sites and they loved it!

However I'm unsure what's going to happen post November 2024?

https://learn.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script

![image](https://github.com/user-attachments/assets/3deb7fb0-ca13-4fbc-baec-20ce9c4f296b)
Does this mean if I run -DelayDenyAddAndCustomizePagesEnforcement before November 2024 the existing script enabled sites will continue to work with the script editor webpart and be enabled for custom scripting? I assume custom scripting going to be eventually turned off and this web part will cease to work?

Thanks so much!

**Comment by wobba** [comment]
Depends.. see https://www.techmikael.com/2024/03/allowing-arbitrary-custom-scripting-in.html
