### ISSUE TITLE
React Rhythm of Business Calendar not correctly rendering recurring events on month view

### ISSUE THREAD

**Issue by butugruv** [pnp/sp-dev-fx-webparts#5205]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-rhythm-of-business-calendar

### Contributor(s)

d-turley

### What happened?

![Screenshot 2024-08-14 223408](https://github.com/user-attachments/assets/8745b69a-f6e2-45ee-a901-17ccce5435bc)

### Steps to reproduce

Please see the attached screenshot
![Screenshot 2024-08-14 223408](https://github.com/user-attachments/assets/1341ede2-0aee-4c71-9680-f714acad92c3)

### Expected behavior

It should show the recurring event on mon and tues. Currently, it only shows on mon.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

16.20.2

### What version of Node.js is required by the sample?

16

### Paste the results of SPFx doctor

m365: The term 'm365' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by d-turley** [comment]
I think this is the correct behavior.  In the screenshot it says the recurrence is set "for 1 ourrence", so after the one instance on Mon the series is done.  Does the calendar view on SharePoint Events list behave differently?

**Comment by butugruv** [comment]
Hi @d-turley, sorry about that I misunderstood how that functionality worked. There is actually a problem when you create an event, be it recurring or single, on a Saturday. It will create a duplicate event that spans the whole next week. I think this has to do with the logic that checks if the event overlaps into the next week.

**Comment by butugruv** [comment]
it may be related to time zone issues I think, still troubleshooting on my end

**Comment by butugruv** [comment]
![Capture2](https://github.com/user-attachments/assets/511f1725-2089-40c5-bcd9-442c56891ce5)
![Capture](https://github.com/user-attachments/assets/cef0bb29-28b5-4284-bae7-eb79969371c4)

**Comment by butugruv** [comment]
this saturday 4am-6pm is spanning the whole of next week when it shouldn't

**Comment by d-turley** [comment]
Thanks for digging into this one.  It looks like it's more of a rendering issue in the Month view as opposed to a data issue?

This web part also exists as [an app in the store](https://appsource.microsoft.com/sr-latn-rs/product/office/WA200004833?tab=Overview). There is a support e-mail that can help with issues in the published app: ProdStudioHarvesting@microsoft.com

To be blunt, I didn't really intend this SPFx sample code to be just a calendar app.  My hope was that people could use the code as a reference solution for building any kind of app with SPFx.  It's more a framework that I've been calling the [SPFx Solution Accelerator](https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-rhythm-of-business-calendar/documentation/README.md).  I've used it to build a wine app for personal use, sort of like cellar tracker.  Another idea I've had is to build a RAID log app for project management.

**Comment by butugruv** [comment]
Ah I see. You've done awesome work Daniel!

Actually, I reached out to Julio Lopez Hernandez a couple days ago and he said he would check with the offshore team to see if we could get the source code for the app source version. It looks like there are additional capabilities like the list view in this one which is really nice.
