### ISSUE TITLE
REST API List Properties call getting HTTP 400

### ISSUE THREAD

**Issue by jerrycote** [pnp/sp-dev-fx-webparts#521]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Looking for a list of document, getting the spinning "Loading Documents" instead.

## Observed Behavior

A web API call en route to the desired result is coming back with an HTTP 400 error.  This is the call:

(CompanyURL)/_api/web/GetFolderByServerRelativePath(decodedurl='/documents')/Properties

so this fails and I'm stuck at the "Loading Documents" message.

Yet I can paste that same URL into a fresh tab on the same authenticated browser, and (on Chrome at least) I get the proper JSON response.

Checking in with Fiddler, the raw text from the error is:

{"error":{"code":"-2146233086, System.ArgumentOutOfRangeException","message":"The UTC time represented when the offset is applied must be between year 0 and 10,000.\r\nParameter name: offset"}}

I updated the references to work with SPFx 1.4.1 so I could package the scripts to run from the CDN.  I'm only mentioning it as part of the picture but I don't think it's related to the error.

## Steps to Reproduce

1. Revise package,json to work with 1.4.1.  I added in everything that "npm ls" was griping about, likely some of it not necessary (I replaced @ signs with % in this sample because the @ sign wasn't translating correctly in the preview window here):

{
  "name": "react-documents",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "typescript": ">=2.1.0",
    "mkdirp": "0.5.1",
    "minimist": "0.0.8",
    "minimatch": "3.0.4",
    "brace-expansion": "1.1.11",
    "balanced-match": "1.0.0",
    "concat-map": "0.0.1",
    "console-control-strings": "1.1.0",
    "inherits": "2.0.3",
    "safe-buffer": "5.1.1",
    "string-width": "1.0.2",
    "strip-ansi": "3.0.1",
    "code-point-at": "1.1.0",
    "is-fullwidth-code-point": "1.0.0",
    "number-is-nan": "1.0.1",
    "ansi-regex": "2.1.1",
    "once": "1.4.0",
    "wrappy": "1.0.2",
    "minipass": "2.2.4",
    "yallist": "3.0.2",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "#types/react": "15.6.6",
    "#types/react-dom": "15.5.6",
    "#microsoft/sp-core-library": "~1.4.0",
    "#microsoft/sp-webpart-base": "~1.4.0",
    "#microsoft/sp-lodash-subset": "~1.4.0",
    "#microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "#microsoft/office-ui-fabric-react-bundle": "~1.4.0",
    "#types/webpack-env": ">=1.12.1 <1.14.0",
    "#types/es6-collections": "0.5.31",
    "#types/react-addons-shallow-compare": "0.14.21",
    "#types/react-addons-test-utils": "0.14.21",
    "#types/react-addons-update": "0.14.19",
    "npm-list-dependencies": "^1.0.0",
    "chai": "^3.2.0"
  },
  "devDependencies": {
    "#microsoft/sp-build-web": "~1.4.0",
    "#microsoft/sp-module-interfaces": "~1.4.0",
    "#microsoft/sp-webpart-workbench": "~1.4.0",
    "gulp": "~3.9.1",
    "#types/chai": ">=3.4.34 <3.6.0",
    "#types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2"
  }
}

2. package and upload to the app catalog on your SharePoint tenant:
- gulp build --ship
- gulp package-solution --ship
- Upload the file to the catalog

3. Add the app to a SharePoint Online site in Site Contents
4. Add the Library Documents web part to a modern page
5. Set the absolute doc library URL property in the web part
6. Save and Close, then refresh

SO...the question is, what could cause an error having something to do with a UTC offset, and why is it only happening when the call is from the script, but with a simple REST API GET, it's fine?

Thanks for your contribution! Sharing is caring.

**Comment by jerrycote** [comment]
Just in case the Request/Response is of any use in the analysis:

REQUEST:
GET https://mdsnyc.sharepoint.com/_api/web/GetFolderByServerRelativePath(decodedurl='/documents')/Properties HTTP/1.1
odata-version: 4.0
Accept: application/json;odata.metadata=minimal
Referer: https://mdsnyc.sharepoint.com/SitePages/Power%20BI%20test.aspx
Accept-Language: en-US
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
Host: mdsnyc.sharepoint.com
DNT: 1
Connection: Keep-Alive
Cookie: FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjQsMGguZnxtZW1iZXJzaGlwfDEwMDMzZmZmOWZiNTExYjFAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfGpfY290ZUBtZHNueS5jb20sMTMxNzIwMzAzNzcwMDAwMDAwLDEzMTM2NDc1MjE0MDAwMDAwMCwxMzE3MjQ2MjM4MjQyNTM5MjIsMC4wLjAuMCwzLDJjY2EzZTY3LTc5YzItNDZkNS1iNDNjLTdmYzU0MWZiNDNiYSwsVjIhMTAwMzNGRkY5RkI1MTFCMSExMzE3MjAzMDM3Nyw3OWJhNmI5ZS1lMDA4LTUwMDAtNmJkNC1jMzhmMTBkZTljMmYsNzliYTZiOWUtZTAwOC01MDAwLTZiZDQtYzM4ZjEwZGU5YzJmLCwwLDAsMCxhdnkxUURaU1lYTUgyS3VUeTVObFh4R0xMRWE2S2VCRVpGbjFGUkpEOVJSN3l6YlpveVBXWWZTTEpuUHdmSXExbVNybHFOT1F6dlZ0Sjd6U2ZUNE0zOGlUblE5Y2luWTdwUTd6TWdKMTVpVUFrcTdXYnh3VTI2cWU3MEM0SGhqVGZQM1o3cFlsY3R5LzdzMUx1NGVQQXJ3UDFFRE9MQko4ZFNHTHRtRXdLeHpKVVFIbUYvS2tESWxSTy9Hc0J3MG5TbHNkc1lRU1RCdEdqVElBV0RadGh1V2t0QWI3dU1wcmt0RmlhYlNNdzl5MmZLODZhdFVlaWRJQm9qckUzdEFxak50aGhZSzVGdCtYdmpFVUFSMzd2K3YzbDFoZWU5Yy9VVGdtZ2IraXN5cTNhQWhmYlV5eldHWkJOR1dhVWRwOElXVDlPeTgyL2VJTVZwZDg0dy84Qnc9PTwvU1A+; WSS_FullScreenMode=false; odbn=1; SPWorkLoadAttribution=Url=https://mdsnyc.sharepoint.com/SitePages/Power%20BI%20test.aspx&AppTitle=RenderClientSideBasePage; rtFa=xD0f+E6FzGn3UOB/MXAwADsehcqxRpdl4KX0dHm/t4kmMkNDQTNFNjctNzlDMi00NkQ1LUI0M0MtN0ZDNTQxRkI0M0JBOoullLPQ8hsw094wqHrJUsfKl+CzE5wGNnxzK+SXlR1PBJ4vvNLJHfGSe3P1TdPlibgmIxbxbZY0sXY89MoMUuhX1DS9qLc2zOyMJAP3izQYCHRRuln8iHsoISc3Jhm53MbfrxmGwAVyp2n3VzoxNTWdWnVqpF0nX2bgr3xu88ALFn3Utntmqk3dWkaLBGHIW8i3XJuNq3FPDVKwOZY9GLSYCJ42kMtjij7l1ArCsges2a2wtzSi7Mz5vcynqqBTnpqYnj7B+OJSgNf36w0kkIQCyQy/ESgDFXVXwfyTVDVOAsLFuaNVVK0hgT8WRl/IGSQaa+hbAciddvTDfBggw0UAAAA=

Response:
HTTP/1.1 400 Bad Request
Cache-Control: private, max-age=0
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Mon, 14 May 2018 02:17:42 GMT
Last-Modified: Tue, 29 May 2018 02:17:42 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Set-Cookie: rtFa=xD0f+E6FzGn3UOB/MXAwADsehcqxRpdl4KX0dHm/t4kmMkNDQTNFNjctNzlDMi00NkQ1LUI0M0MtN0ZDNTQxRkI0M0JBOoullLPQ8hsw094wqHrJUsfKl+CzE5wGNnxzK+SXlR1PBJ4vvNLJHfGSe3P1TdPlibgmIxbxbZY0sXY89MoMUuhX1DS9qLc2zOyMJAP3izQYCHRRuln8iHsoISc3Jhm53MbfrxmGwAVyp2n3VzoxNTWdWnVqpF0nX2bgr3xu88ALFn3Utntmqk3dWkaLBGHIW8i3XJuNq3FPDVKwOZY9GLSYCJ42kMtjij7l1ArCsges2a2wtzSi7Mz5vcynqqBTnpqYnj7B+OJSgNf36w0kkIQCyQy/ESgDFXVXwfyTVDVOAsLFuaNVVK0hgT8WRl/IGSQaa+hbAciddvTDfBggw0UAAAA=; domain=sharepoint.com; expires=Sun, 03-Jun-2018 01:19:42 GMT; path=/; secure; HttpOnly
Set-Cookie: FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjQsMGguZnxtZW1iZXJzaGlwfDEwMDMzZmZmOWZiNTExYjFAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfGpfY290ZUBtZHNueS5jb20sMTMxNzIwMzAzNzcwMDAwMDAwLDEzMTM2NDc1MjE0MDAwMDAwMCwxMzE3MjQ2MjM4MjQyNTM5MjIsMC4wLjAuMCwzLDJjY2EzZTY3LTc5YzItNDZkNS1iNDNjLTdmYzU0MWZiNDNiYSwsVjIhMTAwMzNGRkY5RkI1MTFCMSExMzE3MjAzMDM3Nyw3OWJhNmI5ZS1lMDA4LTUwMDAtNmJkNC1jMzhmMTBkZTljMmYsNzliYTZiOWUtZTAwOC01MDAwLTZiZDQtYzM4ZjEwZGU5YzJmLCwwLDAsMCxhdnkxUURaU1lYTUgyS3VUeTVObFh4R0xMRWE2S2VCRVpGbjFGUkpEOVJSN3l6YlpveVBXWWZTTEpuUHdmSXExbVNybHFOT1F6dlZ0Sjd6U2ZUNE0zOGlUblE5Y2luWTdwUTd6TWdKMTVpVUFrcTdXYnh3VTI2cWU3MEM0SGhqVGZQM1o3cFlsY3R5LzdzMUx1NGVQQXJ3UDFFRE9MQko4ZFNHTHRtRXdLeHpKVVFIbUYvS2tESWxSTy9Hc0J3MG5TbHNkc1lRU1RCdEdqVElBV0RadGh1V2t0QWI3dU1wcmt0RmlhYlNNdzl5MmZLODZhdFVlaWRJQm9qckUzdEFxak50aGhZSzVGdCtYdmpFVUFSMzd2K3YzbDFoZWU5Yy9VVGdtZ2IraXN5cTNhQWhmYlV5eldHWkJOR1dhVWRwOElXVDlPeTgyL2VJTVZwZDg0dy84Qnc9PTwvU1A+; expires=Sun, 03-Jun-2018 01:19:42 GMT; path=/; secure; HttpOnly
X-SharePointHealthScore: 2
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 35
SPRequestDuration: 165
X-AspNet-Version: 4.0.30319
SPRequestGuid: cabd6b9e-30a2-5000-f96f-88d68ad22107
request-id: cabd6b9e-30a2-5000-f96f-88d68ad22107
MS-CV: nmu9yqIwAFD5b4jWitIhBw.0
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.7709
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: 97A26B0BFD9B4236835F089D8023FCE2 Ref B: BL2EDGE1013 Ref C: 2018-05-29T02:17:42Z
Date: Tue, 29 May 2018 02:17:42 GMT
Content-Length: 193

{"error":{"code":"-2146233086, System.ArgumentOutOfRangeException","message":"The UTC time represented when the offset is applied must be between year 0 and 10,000.\r\nParameter name: offset"}}

**Comment by jerrycote** [comment]
Also, this is the view of the v1 config object when the exception takes place:

![image](https://user-images.githubusercontent.com/25130726/40636065-3d015022-62cb-11e8-966c-81d3459b0c1b.png)

**Comment by jerrycote** [comment]
Well - other than needing to widen the viewport, I have this web part working against another document library.  I suspect the one I'm pointing to that's failing, because it's a few years old, functions but is corrupted, causing a configuration glitch that messes up the API call.

You can go ahead and close this, unless you think it's a broader problem worth working on.  I don't see it as such from my end.

Thanks.

**Comment by marcelaopimenta** [comment]
Hi @jerrycote!

I have the same problem. If in list have a Taxonomy field, the issue occurs.

In Odata V4 with parameters specified in SPHttpClientHelper

'Content-Type', 'application/json;charset=utf-8'
Accept', 'application/json;odata.metadata=minimal'

![image](https://user-images.githubusercontent.com/3244062/40706265-8b00f57a-63ed-11e8-8106-6d395250edac.png)

*PS : Error occurs both in V3 or V4 

Best Regards

**Comment by hugoabernier** [comment]
@jerrycote did you ever resolve this issue?

I'll go ahead and close it as there has been no activities here for a while. Feel free to open a new issue if you're still having troubles.
