### ISSUE TITLE
React Content Query Online - Stops Working

### ISSUE THREAD

**Issue by rockxl1** [pnp/sp-dev-fx-webparts#5211]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-content-query-online

### Contributor(s)

@PopWarner @PaoloPia @hugoabernier

### What happened?

This addin stops working for no reason. I saw that my sharepoint online is now a bit different:

![Screenshot 2024-08-20 080754](https://github.com/user-attachments/assets/7031c888-0706-4149-b2ce-5f5af461ef03)

Any Ideia?

### Steps to reproduce

Just add the webpart into any page. Make sure that you tenant is up t date.

![Screenshot 2024-08-20 080924](https://github.com/user-attachments/assets/5c749d7b-f551-43fd-8d19-1032184b9b82)

### Expected behavior

Show the list that we need to pick from.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v18.20.3

### What version of Node.js is required by the sample?

v18.20.3

### Paste the results of SPFx doctor

RESPONSE WITH NO ISSUES

  Text

  CLI for Microsoft 365 SharePoint Framework doctor
  Verifying configuration of your system for working with the SharePoint Framework

      √ SharePoint Framework v1.15.0
      √ Node v16.13.0
      √ yo v4.3.0
      √ gulp-cli v2.3.0
      √ bundled typescript used

RESPONSE WITH ISSUES REPORTED

When the installed version of Yeoman is lower than expected to run SharePoint Framework v1.15.0

  Text

  CLI for Microsoft 365 SharePoint Framework doctor
  Verifying configuration of your system for working with the SharePoint Framework

      √ SharePoint Framework v1.15.0
      √ Node v16.16.0
      × yo v3.1.1 found, v^4 required
      √ gulp-cli v2.3.0
      √ bundled typescript used

      Recommended fixes:

      - npm i -g yo@4

**Comment by sam575815** [comment]
I am also experiencing the same issue, The issue is related to public CDN

**Comment by rockxl1** [comment]
> I am also experiencing the same issue, The issue is related to public CDN

how we fix?

**Comment by maximkol** [comment]
Same issue for me. Any ideas?
