### ISSUE TITLE
react-list-form - Naming Convention on App Build

### ISSUE THREAD

**Issue by robertcaretta** [pnp/sp-dev-fx-webparts#522]
## Category
- [x] Question
- [ ] Bug
- [x] Enhancement

## Expected or Desired Behavior
Should the naming convention on all built items include "PnP" prefix?  I understand this could be viewed as nit picky (sorry). Just thought perhaps when they are deployed to the AppCatalog site they would be grouped together better. 

## Observed Behavior
When I build one app it is prefixed with PnP. Another is not.
https://i.imgur.com/75eE99u.png

## Steps to Reproduce
Build and deploy the "react-form-webpart".

**Comment by robertcaretta** [comment]
Could you please note in the documentation that there are field limitations?  I wasn't aware of that and found a couple that did not work for me.  TaxonomyField and User.

**Comment by hugoabernier** [comment]
Closing this issue as it relates to general SharePoint dev. Feel free to open a new issue in https://github.com/sharepoint/sp-dev-docs if you're still experiencing the issue.
