### ISSUE TITLE
react-script-editor - Module build failed (@microsoft/loader-load-themed-styles)

### ISSUE THREAD

**Issue by Tetronic** [pnp/sp-dev-fx-webparts#5221]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@wobba @salascz @felixbohnacker @waldekmastykarz

### What happened?

The command "gulp bundle --ship" leads to a build error:

![image](https://github.com/user-attachments/assets/621bc48d-2973-4803-afae-56897815f8ad)

### Steps to reproduce

1. Download the Repo and Unzip
2. Open VS Code, open a terminal and go to the directory of the sample (sp-dev-fx-webparts-main\samples\react-script-editor)
3. Install dependencies (npm install)
4. Execute "gulp clean"
5. Execute "gulp bundle --ship"

### Expected behavior

The "gulp bundle --ship" command shouldn't lead to errors in the console. It should instead create the "dist"-folder properly. 

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.13.0

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.18.2
√ Node v16.13.0
× yo not found
√ gulp-cli v2.3.0
√ bundled typescript used
Recommended fixes:

- npm i -g yo@5

### Additional environment details

1. VS Code (v. 1.90.1)
2. OS: Windows Server 2022

**Comment by wobba** [comment]
Follow https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment to have a correct SPFx environment set up.

**Comment by Tetronic** [comment]
@wobba : Thanks for your response!
I double checked the guide https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment and unfortunately I can't see anything missing. I installed also the yeoman, but this didn't help. The guide says that I should use a LTS-Version of Node, but the SPFX code is only tested for Node 16, so I wouldn't upgrade my node version.

Probably you see something odd at my environment according to the issue details I provided and I assume you can build the react-script-editor in your environment.
Could you please tell me which component in my enviroment is wrong?

**Comment by Tetronic** [comment]
@wobba: Could you please briefly respond to my question? Or maybe should I open a new issue, because for me it is not solved.
