### ISSUE TITLE
react-script-editor - Can this webpart be updated to include the Audience Targeting feature?

### ISSUE THREAD

**Issue by stormanh** [pnp/sp-dev-fx-webparts#5223]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@wobba @salascz @felixbohnacker

### Question

This is a powerful webpart that we would like to limit to a group of selected users only by leveraging the audience targeting feature that would make this webpart available for selected users, or a given security group.  Could you add this in the next update please? Thank you for your consideration!

**Comment by wobba** [comment]
I assume you want to target the web part to uses/groups, not the List/Library audience targeting feature?

**Comment by stormanh** [comment]
@wobba That is correct.  Allow specified:
SharePoint Security groups
AAD groups
Users

Thank you!

**Comment by stormanh** [comment]
@wobba That's great to hear!  Appreciate you implementing this important functionality.  Can't wait to use it... thx again!

**Comment by wobba** [comment]
@stormanh Code is updated in the repo, enjoy :)

**Comment by stormanh** [comment]
@wobba Thanks for updating the webpart.  I have tested and confirmed it's working with audience targeting.  However, my original request (sorry if it was unclear) was to restrict actual usage of the webpart (by hiding it from the list of available webparts that are available to be added to the page) based on user account, SharePoint Group, or Entra Security Group.  Again, sorry for the confusion.  Hopefully the below screenshot clarifies the original ask.
![image](https://github.com/user-attachments/assets/479e1a53-0147-44a9-b0a4-7f8260a80146)

**Comment by wobba** [comment]
@stormanh it's all in the SPFx docs :) https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/hide-web-part-from-toolbox Set that flag and add the webpart programatically instead.
