### ISSUE TITLE
Upgrade RSS Reader web part to latest version of SPFx - Refresh Rangers Hacktoberfest Event

### ISSUE THREAD

**Issue by Adam-it** [pnp/sp-dev-fx-webparts#5254]
##  🎯Aim

The aim of this issue is to upgrade the [RSS Reader](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-rss-reader) web part sample to the latest version of [SPFx (1.20)](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.20)

## 🤔 Tips how to get started

To support you in this issue you may use the below tooling:
- [CLI for Microsoft 365](https://pnp.github.io/cli-microsoft365) has a command that will [generate upgrade guidance](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade) for this SPFx project `m365 spfx project upgrade`
- [SPFx Toolkit VS Code extension](https://github.com/pnp/vscode-viva) has an [Upgrade Project](https://github.com/pnp/vscode-viva/wiki/5.5-Actions#upgrade-project) action which generates an `.md` report with upgrade guidance to the latest supported SPFx version

## 📣 What's this event all about

Refresh Rangers is a unique [Hacktoberfest](https://hacktoberfest.com/) event aiming to update our most popular samples 🚀. 
During this, you may obtain a unique Microsoft 365 & Power Platform Community badge - Refresh Rangers 🎖️
To obtain this badge besides opening a PR you also need to [opt-in  the Microsoft 365 & Power Platform Community Recognition Program](https://pnp.github.io/recognitionprogram/#overview) and fill out [this form ](https://aka.us11.list-manage.com/subscribe?u=b3df03dd2b64a3bc8a2a200e8&id=4a558f9e2b)

**Comment by reshmee011** [comment]
I can work on this one:).

**Comment by Adam-it** [comment]
> I can work on this one:).

All yours.
Please do double check if the we part still works after upgrading to latest version of SPFx.
To get a badge from Microsoft 365 & Power Platform community you need to join the recognition program: https://pnp.github.io/recognitionprogram/
You only need to do that one time so if you done already in the past you don't need to fill the form again.

To get a badge from the Hacktoberfest organizers you need to register to Hacktoberfest event: https://hacktoberfest.com/participation/

You Rock 🤩👏👏👏

**Comment by reshmee011** [comment]
@Adam-it : I am stuck with a weird dependencies/environment version upgrade issue. Assign it to @a1mery who is willing to take it forward and I will try to learn from it.

**Comment by Adam-it** [comment]
> @Adam-it : I am stuck with a weird dependencies/environment version upgrade issue. Assign it to @a1mery who is willing to take it forward and I will try to learn from it.

Roger that

**Comment by Adam-it** [comment]
@reshmee011, @a1mery what is the status on this one?
The event is ending with October and this will mean that this won't count toward the Hacktoberfest event if you participated in this one (here there is nothing we may do about it) 
BUT a PR for this issue will be created even after October this will still count to get the [Refresh Ranger badge from the Microsoft 365 and Power Platform Community ](https://www.credly.com/org/m365pnp/badge/refresh-rangers-microsoft-365-power-platform-commun)

**Comment by reshmee011** [comment]
@Adam-it : I have reached a dead-end, not sure what else to try to make it work. @a1mery is facing some challenges with the upgrade as well. Let's hope we find a way. 

I have written a post about my challenges https://reshmeeauckloo.com/posts/spfx-upgrade-to-latest-version/ , it's my lack of knowledge of front end programming , gulp, node and webpack, I am unable to progress.

**Comment by Adam-it** [comment]
> @Adam-it : I have reached a dead-end, not sure what else to try to make it work. @a1mery is facing some challenges with the upgrade as well. Let's hope we find a way. 
> 
> I have written a post about my challenges https://reshmeeauckloo.com/posts/spfx-upgrade-to-latest-version/ , it's my lack of knowledge of front end programming , gulp, node and webpack, I am unable to progress. 

Yes I saw that blog post 👍. TBH I would need to have a deep dive on this myself before I could be able to advise anything. 
There is no pressure 👍 we may complete it later on

**Comment by reshmee011** [comment]
@Adam-it : Thanks so much for your understanding. I need a break to be inspired to get back to it. It would have ideal to do it as part of Hacktoberfest. There is some dependency version issue with the upgrade and can't figure it out with no obvious error messages. The gulp file has been modified to make it work with the older version, I am guessing the gulp file needs further updates. No rush, you got a lot on your plate.

**Comment by a1mery** [comment]
@Adam-it @reshmee011 I apologize for the late update.
As Reshmee said there are custom webpack configurations. So when switching to Webpack 5 (from SPFx 1.19) it stops working :(
I've tried making some updates follwing this: [official Webpack documentation](https://webpack.js.org/migrate/5/) but no luck for now..

**Comment by Adam-it** [comment]
> @Adam-it @reshmee011 I apologize for the late update.
> As Reshmee said there are custom webpack configurations. So when switching to Webpack 5 (from SPFx 1.19) it stops working :(
> I've tried making some updates follwing this: [official Webpack documentation](https://webpack.js.org/migrate/5/) but no luck for now..

No problem, thanks for the update 👍.

**Comment by ferrarirosso** [comment]
@Adam-it let me know if i can help with this one, looks like a good challenge

**Comment by reshmee011** [comment]
@ferrarirosso : I am happy for you to dive into it.

**Comment by Adam-it** [comment]
> @Adam-it let me know if i can help with this one, looks like a good challenge

I guess it's for @reshmee011 and @a1mery to decide. I just do 'house cleaning' 🧹 here 😅

**Comment by reshmee011** [comment]
@a1mery : can @ferrarirosso take over the upgrade?

**Comment by a1mery** [comment]
Yes, sure!
Good luck @ferrarirosso ;)

**Comment by ferrarirosso** [comment]
@reshmee011 @a1mery 
- I had to remove the handlebar-helpers package which was last updated 7 years ago and I did replace most of the helpers with lodash or js native.
- Did also some changes in Gulp for Webpack 5 compatiblity with new npm packages
- Fixed a bug with custom template which  caused the webpart tab to freeze (render loop), so I suppose custom template were not so intensively used.

Happy to help

**Comment by reshmee011** [comment]
@ferrarirosso : That's awesome, I would have never thought of those changes. Thanks for sharing your findings and workarounds.

**Comment by a1mery** [comment]
Congrats @ferrarirosso!! You're the best!
I actually had nightmare about that handlebar-helpers package :(

**Comment by ferrarirosso** [comment]
@a1mery that was also a nightmare for me until I decided to rewrite part of the code, a good experience

**Comment by ferrarirosso** [comment]
@reshmee011 thank you for your kind words
Community rocks !

**Comment by Adam-it** [comment]
@ferrarirosso, @a1mery, @reshmee011 Awesome Team Work 🤩 
You all Rock 👏👏👏👏👏👏
