### ISSUE TITLE
Spfx Webpart not working on the classic pages with Customization (Double JQuery)

### ISSUE THREAD

**Issue by Masood10** [pnp/sp-dev-fx-webparts#526]
- [x] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

I have an angular 1.x webpart application in the spfx 1.4 version. The webpart works in the modern sites pages. It should also work in the classic pages with customization.

## Observed Behavior

The webpart is not working on the classic site pages and I am getting the following error in chrome and sometimes in Firefox.

    [SPWebPartErrorCode.IncorrectBoostrapModule]:

    Bootstrap module for web part WebPart.CsTaskBoardWebPart.g_76cddb14_eed9_4284_81a4_b8db3ff64e8c not of the correct type. Make sure to export your web part as 'export default WebPartName'.
    ***CALLSTACK:

    t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-classic-page-assembly_en-us_9bd26145452b8a6a140c7ec7a2b736fb.js:201:15770
    t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-classic-page-assembly_en-us_9bd26145452b8a6a140c7ec7a2b736fb.js:301:9108
    ......

Error changes on refresh in Firefox
`Error: Error loading https://relative-path.invalid/jquery as "jquery" from https://code.jquery.com/ui/1.12.0/jquery-ui.js Unable to load script https://relative-path.invalid/jquery`

if Again Refresh. I get the following error 
`TypeError: $ is undefined`

if Again Refresh.
`TypeError: $ is not a function`

From my understanding I believe there is a custom extension in the classic page and it is loading the jQuery as global and it is causing the problem. I can  not change the custom extension. Is there was to fix this problem?

I am loading jQuery in webpart by 
```
    path: "https://code.jquery.com/jquery-2.1.1.js",
    globalName: "jQuery",
    get isLoaded() { return checkGlobalObject(this.globalName); },
    dependents: [
      {
        path: "https://code.jquery.com/ui/1.12.0/jquery-ui.js",
        globalName: "jQuery",
        get isLoaded() { return checkGlobalObject(this.globalName, "ui"); },
......
```
Any solution how to fix it?

**Comment by JayakumarB** [comment]
Since SPFx webparts are injected into the page as a JavaScript there could be chances that other script references in your classic pages may affect loading SPFx webparts try to re-order the scripts referred in your classic pages and check.

**Comment by Masood10** [comment]
I fixed the double JQuery issue but now I am getting the following error randomly on every 3rd 4th refresh.
```
Uncaught (in promise) Error: Bootstrap module for web part WebPart.CsTaskBoardWebPart.g_ae39aedb_88eb_428f_bfa2_c6870d20662f not of the correct type. Make sure to export your web part as 'export default WebPartName'.
    at t [as constructor] (sp-classic-page-assembly_en-us_f2c01c253c2ef24569720eb8e0a6d5f9.js:201)
    at new t (sp-classic-page-assembly_en-us_f2c01c253c2ef24569720eb8e0a6d5f9.js:301)
    at Function.t.createWithLogProperties (sp-classic-page-assembly_en-us_f2c01c253c2ef24569720eb8e0a6d5f9.js:301)
    at e._instantiateWebPart (sp-classic-page-assembly_en-us_f2c01c253c2ef24569720eb8e0a6d5f9.js:301)
    at e._initializeAndRenderWebPart (sp-classic-page-assembly_en-us_f2c01c253c2ef24569720eb8e0a6d5f9.js:301)
    at sp-classic-page-assembly_en-us_f2c01c253c2ef24569720eb8e0a6d5f9.js:301
```

Why the error is coming randomly?

**Comment by mindlabco** [comment]
Hello @Masood10 ,

SPFx Web parts work with the classic and modern pages. First, let understand the SPFx behavior. When you add a web part into any classic or modern page. It injects directly to the DOM of the page. Modern pages don't support master pages so there are no conflicts and it works fine, however, if you are planning to use SPFx web parts in the Classic site or page it will have all the references from the master pages. 

It seems that you have used custom master page and bootstrap reference on the master page. Your web part also has the bootstrap reference. So it conflicts with the master page's bootstrap. 

**Resolution:**

1.  If you are using SPFx web parts on the classic page then remove the bootstrap reference from SPFx web parts.

2. We need to add JQuery reference in both Master page and web part. You can use the latest JQuery3.2.1 in the master page so its better compatible with bootstrap and use JQuery1.2.0 on the SPFx web parts. So it will not conflict with the master page's JQuery. We suggest the lower version of the JQuery in web part so you can do JQuery code in SPFx web part and does not conflict with the master page JS. 

I had the same issue and resolved as described above. Do let me know in case you will have any other issue.

**Comment by hugoabernier** [comment]
@Masood10 did @mindlabco's instruction help you solve this issue?

I'll go ahead and close the issue, but if you're still running into problems feel free to open a new issue.

Thanks @mindlabco for your help with this one.
