### ISSUE TITLE
react-content-query-online - Web part is throwing [Object Object] Error from last 1 month

### ISSUE THREAD

**Issue by sam575815** [pnp/sp-dev-fx-webparts#5268]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-content-query-online

### Contributor(s)

@spplante, @sebastienlevert, @PopWarner, @hugoabernier , @PaoloPia, @Abderahman88

### What happened?

When using the latest version of Content Query webpart for Online.
The webpart throws an error when added to the page

![2024-09-29_18-19-51](https://github.com/user-attachments/assets/c30e05b3-a0c5-4681-8bee-38e8d48a04c4)

I tried to build the project even that is giving the following error,

./node_modules/handlebars-helpers/lib/utils/utils.js 3:34-41
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### Steps to reproduce

1. Clone the latest sample repo
2. Build the content query webpart in local environment
3. Upload the sppkg file to app center. Add the app to the site collection. Add the app to the page

### Expected behavior

Should render the Content Query webpart.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v18.20.4

### What version of Node.js is required by the sample?

Node.js v16 | v18

### Paste the results of SPFx doctor

√ SharePoint Framework v1.18.2
√ Node v18.20.4
√ yo v5.0.0
√ gulp-cli v2.3.0
√ bundled typescript used
[
  {
    "check": "SharePoint Framework",
    "passed": true,
    "version": "1.18.2",
    "message": "SharePoint Framework v1.18.2 valid."
  },
  {
    "check": "SharePoint Framework",
    "passed": true,
    "version": "1.18.2",
    "message": "SharePoint Framework v1.18.2"
  },
  {
    "check": "Node",
    "passed": true,
    "message": "Node v18.20.4",
    "version": "18.20.4"
  },
  {
    "check": "yo",
    "passed": true,
    "message": "yo v5.0.0",
    "version": "5.0.0"
  },
  {
    "check": "gulp-cli",
    "passed": true,
    "message": "gulp-cli v2.3.0",
    "version": "2.3.0"
  },
  {
    "check": "typescript",
    "passed": true,
    "message": "bundled typescript used"
  }
]

**Comment by mauricework** [comment]
@sam575815 did you fix this or ??  I am getting this as well when I do a  gulp bundle --ship getting

Warning - [webpack] 'dist':
./node_modules/handlebars-helpers/lib/utils/utils.js 3:34-41
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings (C:/Junk3/SPFX/sp-dev-fx-webparts/samples/react-content-query-online/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)

Not sure what I am doing wrong or if this is an issue in the code.
Thanks.

**Comment by aliiamar** [comment]
Hi @sam575815 did you managed to fix this error? We are still facing this issue in our tenant with error message:

_Could not load content-query-web-part in require. TypeError: i.default.acequire is not a function_

Please let us know how this can be fixed, thanks!
