### ISSUE TITLE
Latest release doesn't appear to respect the "remove padding" setting 

### ISSUE THREAD

**Issue by lordneeko** [pnp/sp-dev-fx-webparts#5279]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor

### Contributor(s)

Wobba

### What happened?

I noticed with the latest release of the modern script editor that my script web parts even when I have selected for it to remove padding, it does not seem to respect that. The web parts are still taking up all of their space when I publish the page.

### Steps to reproduce

1. Edit page
2. Add modern script editor Web part 
3. Turn on "remove padding"
4. Save draft or publish
5. Notice that the entire script part's size is being blocked out on the page

### Expected behavior

When padding is removed. I expect the page to not have any padding around a script web part that doesn't have size. For example, I have code that is just JavaScript and has no actual size on the HTML page yet it is still taking up the same size as the block for the web part. This is only happening on the Chrome browser. It does not happen on Edge browser.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

NA

### What version of Node.js is required by the sample?

NA

### Paste the results of SPFx doctor

NA

**Comment by lordneeko** [comment]
I just noticed the issue only exists when you "save as draft" not when you publish. Closing

**Comment by Adam-it** [comment]
@lordneeko thanks for the heads up and the double check. You Rock 👏👏🤩
