### ISSUE TITLE
Versioning Is Incorrect

### ISSUE THREAD

**Issue by BenedictCard** [pnp/sp-dev-fx-webparts#5280]
### Disclaimer

Yes

### Sample

react-add-js-css-ref

### Contributor(s)

me

### What happened?

In the original package-json the version is set to only 3 chars, but I'm not sure if it's an isolated issue, my tenant requires 4 numbers as per:
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "react-add-js-css-ref-client-side-solution",
    "id": "d9c30e1a-bf06-46fa-807d-ce5182d9c91c",
    "version": "1.0.0.0",  // Changed to include a fourth segment
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "developer": {
      "name": "Your Name",
      "privacyUrl": "https://yourprivacyurl.com",
      "termsOfUseUrl": "https://yourtermsofuse.com",
      "websiteUrl": "https://yourwebsite.com",
      "mpnId": "Undefined-1.14.0"
    },
    "metadata": {
      "shortDescription": {
        "default": "react-add-js-css-ref description"
      },
      "longDescription": {
        "default": "react-add-js-css-ref description"
      },
      "screenshotPaths": [],
      "videoUrl": "",
      "categories": []
    },
    "features": [
      {
        "title": "Application Extension - Deployment of custom action.",
        "description": "Deploys a custom action with ClientSideComponentId association",
        "id": "201c7969-a60d-492a-83d2-db3088515c51",
        "version": "1.0.0.0",
        "assets": {
          "elementManifests": [
            "elements.xml",
            "clientsideinstance.xml"
          ]
        }
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/react-add-js-css-ref.sppkg"
  }
}

### Steps to reproduce

1.deploy to appcatalog
2.view the error of version
3.

### Expected behavior

Success

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v16.16.0

### What version of Node.js is required by the sample?

v16

### Paste the results of SPFx doctor

There were errors when validating the App manifest.: Xml Validation Exception: 'The 'Version' attribute is invalid - The value '1.0.0' is invalid according to its datatype 'http://schemas.microsoft.com/sharepoint/2012/app/manifest:VersionDefinition' - The Pattern constraint failed.' on line '1', position '268'

### Additional environment details

Updated the version to 4 integers and works perfectly, thank you for all the effort.

**Comment by Tanddant** [comment]
@BenedictCard This issue should be solved now 😊 - thanks for reporting it!
