### ISSUE TITLE
Web part is not available on the modern page despite of the deployment on the site.

### ISSUE THREAD

**Issue by Ajay196488** [pnp/sp-dev-fx-webparts#5318]
### Disclaimer

Yes

### Sample

react-script-editor

### Contributor(s)

@Mikael Svenson, Felix Bohnacker, salascz, Waldek Mastykarz, Luccas Castro

### What happened?

Web part is not available on the modern page. I have used the latest version of the web part.

### Steps to reproduce

1. Add the webpart in app the catalog.
2. Add the app on the site.
3. Webpart is not showing on the Modern page

### Expected behavior

It should be available on the modern pages.

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

18

### What version of Node.js is required by the sample?

18

### Paste the results of SPFx doctor

![image](https://github.com/user-attachments/assets/261cc33a-2e75-48ce-8cb1-3dbfbb59759b)

**Comment by Adam-it** [comment]
@Ajay196488 I think this webpart shows up when custom scripts is enabled on sites. 
could you enable it for your site and recheck
![image](https://github.com/user-attachments/assets/3c0f8f4b-aeb1-448d-85a3-a5faf9e30fc6)

if you want to enable it for all sites also for no-script sites you need to set the following as it is stated in protect readme
![image](https://github.com/user-attachments/assets/ba90bc1d-7285-48e7-8d21-52b9019f0016)

**Comment by hugoabernier** [comment]
Hi @Ajay196488, were you able to resolve this issue? 

I'll go ahead and close this, but if you have more questions, please do not hesitate to open a new issue and provide more information.

**Comment by tedtninety** [comment]
@Ajay196488 Thank you.

Will I be able to rely on using this solution to customize select pages using Modern Script Editor? After all it was created with SPFX by the awesome Mikael, or is this something that is on MS roadmap to sunset?

I had read somewhere about having to renew something by script every 24 hrs to keep the webpart  functioning after this week?

**Comment by Adam-it** [comment]
> @Ajay196488 Thank you.
> 
> Will I be able to rely on using this solution to customize select pages using Modern Script Editor? After all it was created with SPFX by the awesome Mikael, or is this something that is on MS roadmap to sunset?
> 
> I had read somewhere about having to renew something by script every 24 hrs to keep the webpart functioning after this week?

@tedtninety I would recommend not relying on this approach to do regular customization of Modern SharePoint Pages. Custom scripting is by default turned of and only few classic pages has it turned on. You may of course turn on custom scripting on your own but it will only last for 24 after that you will need to switch it back on again.
You may read more about it here
https://learn.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script

![image](https://github.com/user-attachments/assets/a217ba0e-1927-4bdd-bff3-da21fb7c7c61)

**Comment by tedtninety** [comment]
> > @Ajay196488 Thank you.
> > Will I be able to rely on using this solution to customize select pages using Modern Script Editor? After all it was created with SPFX by the awesome Mikael, or is this something that is on MS roadmap to sunset?
> > I had read somewhere about having to renew something by script every 24 hrs to keep the webpart functioning after this week?
> 
> @tedtninety I would recommend not relying on this approach to do regular customization of Modern SharePoint Pages. Custom scripting is by default turned of and only few classic pages has it turned on. You may of course turn on custom scripting on your own but it will only last for 24 after that you will need to switch it back on again. You may read more about it here https://learn.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script
> 
> ![image](https://private-user-images.githubusercontent.com/58668583/387002727-a217ba0e-1927-4bdd-bff3-da21fb7c7c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Nzc0MzYsIm5iZiI6MTczMTg3NzEzNiwicGF0aCI6Ii81ODY2ODU4My8zODcwMDI3MjctYTIxN2JhMGUtMTkyNy00YmRkLWJmZjMtZGEyMWZiN2M3YzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDIwNTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjc1ZDMxYTQ2YmJjZjVlMGYzOTkxNGZiY2Q3YjY2NGViMDc4NDJlM2ZiNzU1ODgzYThmY2JlYWE0Yzc4NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1jiQrfTYeUFKdD581hKTJOkMd6BuZC_6K5y6UovNcVQ)

Thank you @Adam-it  ( apologies I tagged you incorrectly prior ).

"This setting affects all sites. There are no options to preserve changes to custom script settings only on some specific sites. This parameter will be available until November 2024. After that date, it will no longer be possible to prevent SharePoint in resetting custom script settings to its original value for all sites. "

To clarify, this ability will only work until November 2024, regardless of whether the persistent script was run or not?

So there is no way otherwise to customize modern pages with CSS?

**Comment by Adam-it** [comment]
@tedtninety I think you may always apply custom css using SPFx extension like an application customizer

**Comment by tedtninety** [comment]
> @tedtninety I think you may always apply custom css using SPFx extension like an application customizer

Thank you @Adam-it
