### ISSUE TITLE
react-taxonomypicker doesn't preserve selections

### ISSUE THREAD

**Issue by undomil** [pnp/sp-dev-fx-webparts#532]
Category

- [x] Bug

Expected or Desired Behavior

Expected behaviour is that when a page with a webpart containing a taxonomy picker property is edited and the property pane for that web part is opened, the taxonomy picker will show the current property value(s) as selected.
Observed Behavior

When a page with a webpart containing a taxonomy picker property is edited and the property pane for that web part is opened, the taxonomy picker shows the 'Type here to search...' placeholder instead of the selected item.
Steps to Reproduce

I was having this problem with a web part I created which used the react-taxonomypicker module. When it was deployed to SP and added to a page, saving and re-editing the page caused the setting to be lost.

This can be repeated more easily with the OOTB sample though:

    Clone the sp-dev-fx-webparts git repo locally then

    cd samples/react-taxonomypicker
    npm install
    gulp serve

The https://localhost:4321/temp/workbench.html page opens (in chrome)

    Add the TaxonomyPickerSample web part to the workbench page.

    Edit the properties for this web part and select 'English' then close the properties pane. The web part correctly shows 'Selected Language: English'
    Reopen the properties pane - the picker correctly shows English as selected.

    Hit F5 to refresh the page - the web part still correctly shows 'Selected Language: English'
    Edit the properties for this web part - the picker doesn't know about the English selection and just shows 'Type here to search...'

The problem may be due to how the componentDidMount is handled in the react-taxonomypicker TaxonomyPicker.tsx file or perhaps an issue with the Custom control handling in the sample?

**Comment by hugoabernier** [comment]
@undomil  did you ever get this issue resolved?

I'll go ahead and close this issue as it is pretty old. If you're still having problems with this, feel free to open a new issue and, hopefully, we can get a fresh set of eyes to look at this and get you the help you deserve.

Please note that we welcome pull requests in this repository. If you fixed this issue yourself and would like to share your solution with others, feel free to share your solution.

Thanks again for bringing this issue to our attention.
