### ISSUE TITLE
Are spfx webparts supported in the sharepoint mobile app

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-webparts#541]
- [X] Question
Are spfx webparts supported in the sharepoint mobile app? 
I have an spfx webpart on the welcome page of a web. It works fin in the browser, but not in the mobile app. It displays ok, but no events get fired-- it is unusable. It relies heavily on fabric.

Is this supported?

I could create a powerapp and embed that on the welcome page instead. Would that be a 'more supported' way to do this.

**Comment by russgove** [comment]
Ideally I do not want to have to maintain a power app for mobile use and an spfx webpart for use on the web.

**Comment by PopWarner** [comment]
We are in the process of cleaning up the issues on this repo. This does not appear to be an issue for an SPFx Sample Web Part. Closing at this time. Thank you.
