### ISSUE TITLE
Modern Form

### ISSUE THREAD

**Issue by jleckard007** [pnp/sp-dev-fx-webparts#542]
## Category

- [X] Question
- [ ] Bug
- [x] Enhancement

The instructions to deploy the react-modern-charts seem to be missing several key steps to include the location of files to copy to CDN.  Please help.
.

**Comment by zhinigami** [comment]
Hi, I'm new to SPFx. I am facing the problem in when deploy **react-modern-charts** with cmd "gulp bundle --ship". Error message: Additional properties not allowed: IsDomainIsolated. Appreciate for any advice.

**Comment by hugoabernier** [comment]
@jleckard007 did you ever resolve this issue?

`isDomainIsolated` was a new property added in later versions of SPFx. It probably means that you tried to run a sample intended for a newer version of SPFx than what you had installed on your workstation.

I'll go ahead and close it as there has been no activities here for a while. Feel free to open a new issue if you're still having troubles.
