### ISSUE TITLE
Provisioning SharePoint Lists using SPFX web part

### ISSUE THREAD

**Issue by giveitaGo** [pnp/sp-dev-fx-webparts#543]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Build SPFx web part solution, and add XML templates for asset deployment. Deploy solution to app catalog, then add the app to a site. Lists with added OOB columns will be created based on XML template(s) provided. We all dance with joy and elation.

_How do you deploy a custom list with added OOB columns without using content types/site columns?_

## Observed Behavior

App deploys to app catalog just fine. When the app is added to the site, it fails after a few minutes. In classic experience, you see "Something went wrong with adding the app." with a "Click to retry" link. No lists are created, the web part is also not available. I hang my head in sadness, bottle of champagne are put back in their respective boxes. 

When I go into the app catalog and monitor apps, I can see failed installs. When I click the number, I see the message "The content database on the server is temporarily unavailable."

I've tried this on both demo tenants and live production tenants. 

## Steps to Reproduce

Following the steps in this article worked fine, but when I tried to add columns to a list without using content types is when I saw the error. 
[Provision SharePoint assets from your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)

Follow the steps in that article, but use Visual Studio SharePoint project to generate some XML for the list definitions. Drop that XML into the schema.xml file.

**Elements.xml**
`<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <ListInstance 
        CustomSchema="schema.xml"
        FeatureId="1d09aa92-c808-4b79-a214-7010172284cc"
        Title="Categories" 
        OnQuickLaunch="TRUE" 
        TemplateType="100" 
        Url="Lists/Categories" 
        Description="List of categories used by the FAQs list">
    </ListInstance>    
</Elements>`

**Schema.xml**
`<?xml version="1.0" encoding="utf-8"?>
<List xmlns:ows="Microsoft SharePoint" Title="Categories" FolderCreation="FALSE" Direction="$Resources:Direction;" Url="Lists/Categories" BaseType="0" 
    xmlns="http://schemas.microsoft.com/sharepoint/">
    <MetaData>
        <ContentTypes>
            <ContentType ID="0x0100c9d6d3235e6c4118a5a8bf93764f58e1" Name="ListFieldsContentType">
                <FieldRefs>
                    <FieldRef ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" Name="Title" />
                </FieldRefs>
            </ContentType>
            <ContentTypeRef ID="0x01">
                <Folder TargetName="Item" />
            </ContentTypeRef>
            <ContentTypeRef ID="0x0120" />
        </ContentTypes>
        <Fields>
            <Field ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" Type="Text" Name="Title" DisplayName="Category" Required="TRUE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="Title" MaxLength="255" />
        </Fields>
        <Views>
            <View BaseViewID="0" Type="HTML" MobileView="TRUE" TabularView="FALSE">
                <Toolbar Type="Standard" />
                <XslLink Default="TRUE">main.xsl</XslLink>
                <RowLimit Paged="TRUE">30</RowLimit>
                <ViewFields>
                    <FieldRef Name="LinkTitleNoMenu"></FieldRef>
                </ViewFields>
                <Query>
                    <OrderBy>
                        <FieldRef Name="Modified" Ascending="FALSE"></FieldRef>
                    </OrderBy>
                </Query>
                <ParameterBindings>
                    <ParameterBinding Name="AddNewAnnouncement" Location="Resource(wss,addnewitem)" />
                    <ParameterBinding Name="NoAnnouncements" Location="Resource(wss,noXinviewofY_LIST)" />
                    <ParameterBinding Name="NoAnnouncementsHowTo" Location="Resource(wss,noXinviewofY_ONET_HOME)" />
                </ParameterBindings>
            </View>
            <View BaseViewID="1" Type="HTML" WebPartZoneID="Main" DisplayName="$Resources:core,objectiv_schema_mwsidcamlidC24;" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" SetupPath="pages\viewpage.aspx" ImageUrl="/_layouts/15/images/generic.png?rev=23" Url="AllItems.aspx">
                <Toolbar Type="Standard" />
                <XslLink Default="TRUE">main.xsl</XslLink>
                <JSLink>clienttemplates.js</JSLink>
                <RowLimit Paged="TRUE">30</RowLimit>
                <ViewFields>
                    <FieldRef Name="LinkTitle"></FieldRef>
                </ViewFields>
                <Query>
                    <OrderBy>
                        <FieldRef Name="ID"></FieldRef>
                    </OrderBy>
                </Query>
                <ParameterBindings>
                    <ParameterBinding Name="NoAnnouncements" Location="Resource(wss,noXinviewofY_LIST)" />
                    <ParameterBinding Name="NoAnnouncementsHowTo" Location="Resource(wss,noXinviewofY_DEFAULT)" />
                </ParameterBindings>
            </View>
        </Views>
        <Forms>
            <Form Type="DisplayForm" Url="DispForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
            <Form Type="EditForm" Url="EditForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
            <Form Type="NewForm" Url="NewForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
        </Forms>
    </MetaData>
</List>`

Apologies for the ugly code, I tried to format a different way, but no joy.

 #spfx-webparts

**Comment by russgove** [comment]
Hey, I'm having this same issue. You ever get it resolved?

**Comment by hugoabernier** [comment]
I'll go ahead and close it as there has been no activities here for a while and no response from the author. Feel free to open a new issue if you're still having troubles.
