### ISSUE TITLE
How to redirect the modern searchbox to the custom page build using react-search-refiners

### ISSUE THREAD

**Issue by mmohamedbasith** [pnp/sp-dev-fx-webparts#564]
I am using communication site . Customer want to have search with filters , i can use the ;react-search-refiners' webpart . But when i search from OOTB search , search has to go the custom page that has the react-search-refiners' webpart

**Comment by rbarten** [comment]
@FranckyC: I noticed that the 'Send query to a new page' functionality is recently changed in the SearchBoxContainer and doesn't work anymore. Is there a particular reason why the hashtag approach is used?

Previous code:
``` 
if (this.props.searchInNewPage) {
      // Send the query to the a new via the query string
      const url = UrlHelper.addOrReplaceQueryStringParam(this.props.pageUrl, 'q', encodeURIComponent(queryText));
```
Changed code:
``` 
if (this.props.searchInNewPage) {
        
        // Send the query to the a new via the hash
        const url = `${this.props.pageUrl}#${encodeURIComponent(queryText)}`;
```

**Comment by FranckyC** [comment]
Hi @rbarten. The change reason is because there was issues with the browser history state and SharePoint when using query string parameters. The hashtag is easier to manipulate and integrates well with the  browser history and default SPFx dynamic data source 'URL Fragment'

**Comment by holylander** [comment]
@FranckyC  Do you know if there is any way to send the query from the ootb sharepoint online webpart, to another page ? 
![image](https://user-images.githubusercontent.com/2032683/71581884-ccdca880-2b07-11ea-8f0d-64698a81361b.png)
Since I need more custom refiners in my site search, I wanted to leverage the spfx custom search webpart, so it takes the query that is forwarded from the ootb searchbox. Thanks

**Comment by MGoelles24** [comment]
Hi @holylander. Have you found a solution or a workaround?

**Comment by holylander** [comment]
> 
> 
> Hi @holylander. Have you found a solution or a workaround?

Not really. All I can think is to modify its behaviour with some spfx extension that changes the click/enter action...

**Comment by hugoabernier** [comment]
@mmohamedbasith did you ever get this issue resolved?

I'll go ahead and close this issue as it is pretty old. If you're still having problems with this, feel free to open a new issue and, hopefully, we can get a fresh set of eyes to look at this and get you the help you deserve.

Please note that we welcome pull requests in this repository. If you came up with a solution that you'd like to share with others, feel free to submit a sample.

Thanks again for bringing this to our attention.
