### ISSUE TITLE
Adding additional webparts to react-search-refiner project

### ISSUE THREAD

**Issue by jumpei-yamauchi** [pnp/sp-dev-fx-webparts#565]
Hi,

I am not sure I should be posting this issue here. If you could redirect to me an appropriate site if that is the case, that would be much appreciated. 

We'd like to add an additional webpart to the react-search-refiners project. However when an webpart is added with the sharepoint yeoman generator (1.5.1), the build process for the project starts to fail. 

 src\webparts\searchBox\SearchBoxWebPart.ts(49,18): error TS2551: Property 'dynamicDataSourceManager' does not exist on type 'WebPartContext'. Did you mean '_dynamicDataSourceManager'?

When 'sp-webpart-base' under node-module -> microsoft is rolled back to the state before the yeoman runs, the project starts to build again. 

What would cause this?

Thank you in advance
Jumpei

**Comment by hugoabernier** [comment]
@jumpei-yamauchi did you ever resolve this issue?

I'll go ahead and close it as there has been no activities here for a while. Feel free to open a new issue if you're still having troubles.
