### ISSUE TITLE
PnP PeoplePicker control doesn't work in a Listview Command Set extension

### ISSUE THREAD

**Issue by rchivert** [pnp/sp-dev-fx-webparts#570]
## Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

## Expected or Desired Behavior

Launching a custom Dialog box from a Listview Command Set extension - where the custom dialog box contains a peoplepicker control - should work. 

## Observed Behavior

The peoplepicker control requires a WebPartContext property... which isn't available in a List View Command Set extension.

## Steps to Reproduce

In the [demo ](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx) - add a pnp spfx peoplepicker control.  There is no (obvious) way to get a  WebPartContext property to pass into the peoplepicker control.

**Comment by mohababu009** [comment]
Hi,
Is there any update on how to use PnP People Picker in List View Commandset. 
Thanks in advance - Mohan

**Comment by hugoabernier** [comment]
@rchivert did you ever resolve this issue?

I'll go ahead and close it as there has been no activities here for a while. I encourage you to open a new issue in the [sp-dev-fx-controls-react/ repo](https://github.com/pnp/sp-dev-fx-controls-react/) if you're still having troubles.

**Comment by rchivert** [comment]
Please close

On May 19, 2020, at 8:43 PM, Hugo Bernier <notifications@github.com> wrote:

﻿

@rchivert<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frchivert&data=02%7C01%7C%7Cccabccf4b78c4917ab7f08d7fc56d920%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637255322243266918&sdata=EqileHQGc%2FoWHPG3cIH9G8mCu0lkGDJz1BlRBlMGKJg%3D&reserved=0> did you ever resolve this issue?

I'll go ahead and close it as there has been no activities here for a while. I encourage you to open a new issue in the sp-dev-fx-controls-react/ repo<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpnp%2Fsp-dev-fx-controls-react%2F&data=02%7C01%7C%7Cccabccf4b78c4917ab7f08d7fc56d920%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637255322243276913&sdata=wLjMu3l4e3peCk6jV%2FN%2FHIU2JSoJyQeOx3wFyGpiPd4%3D&reserved=0> if you're still having troubles.
