### ISSUE TITLE
Elevated Privileges as User

### ISSUE THREAD

**Issue by gbminnock** [pnp/sp-dev-fx-webparts#579]
## Category

- [ x ] Question
- [ ] Bug
- [ ] Enhancement

## Authors
**@joelfmrodrigues**
**@VesaJuvonen**
**@waldekmastykarz**

## Expected or Desired Behavior / Question
> I have followed the code sample for elevated privileges from here: [react-sp-elevatedprivileges](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-sp-elevatedprivileges) which makes http requests from the spfx webpart to a rest api (aspnet webapi) which uses app-only permissions. The permissions are gained in the webapi using:
>
```typescript
OfficeDevPnP.Core.AuthenticationManager authMgr = new OfficeDevPnP.Core.AuthenticationManager();
ClientContext ctx = authMgr.GetAppOnlyAuthenticatedContext(siteUrl, clientID, clientSecret);
```
>It works fine and I can see items are modified with the user "SharePoint App".
I wanted to perform the same sorts of operation but on behalf of a user. Is this something that is possible? 
I have tried the same using AddIns however I've run into a block because I need to call the appredirect.aspx on sharepoint with a httpContext to create the 'SPAppToken' which gets sent to the provider hosted addin.
Would you be able to provide any guidance on achieving my use-case? 
Many Thanks,
Gary
>

**Comment by waldekmastykarz** [comment]
To perform an operation on behalf of a user, you would have to have that user's credentials and either create a CSOM context or get an OAuth access token.
