### ISSUE TITLE
AadTokenProvider is not initialized

### ISSUE THREAD

**Issue by douglasromao** [pnp/sp-dev-fx-webparts#582]
Hello guys,

I'm trying to create a webpart to consume endpoints from an Azure API but I'm facing an issue trying to use the AadHttpClient. When I try to call the endpoint from my API it hits this error:

**This operation cannot be performed until the AadTokenProvider is initialized.**

I created my own webpart and was facing this issue so I tried to use the sample project **react-3rd-party-api** and it is hitting the same issue.

Do you know anything about it?

Thanks!

**Comment by hugoabernier** [comment]
Closing this issue as it relates to general SPFx development. Feel free to re-open this issue to the sp-dev-docs repository at https://github.com/sharepoint/sp-dev-docs
