### ISSUE TITLE
Is there a way to get React-Search-Refiners results to show the same icons as the Modern Search?

### ISSUE THREAD

**Issue by AndyBolam** [pnp/sp-dev-fx-webparts#602]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors

@FranckCornu
@mikaelsvenson

## Expected or Desired Behavior

Hi, am new to GitHub so apologies if this is not the right place to raise this.  I've been using this web part for a while to support consistency between Modern sites and so that they can tie in with a refinable search - these web parts are amazing work and help do this so much.  

I have noticed however that there is some inconsistency visually between the icons the React web part returns and the icons that OOTB Modern Search returns.  For example a document library result in Modern Search provides a folder icon whereas the web part returns a document 'like' icon.  Is there any way I can align the web part to pull the same stock icon set as Modern Search?  

Although my knowledge is very limited in terms of spFX I am willing to learn and would be grateful if you can point me in the direction in terms of where I should be looking to potentially make this change.  Is this something I can change in the Template or would it require a change to the source code?

Kind regards
Andy

**Comment by FranckyC** [comment]
Hi @AndyBolam , sorry for the late response (vacation:)). Unfortunately, I didn't find a way to get the 'right' icons. For now, I use the `mapToIcon()` method within the code, which is an old method working on both On-Prem and Online versions. Probably the OOTB Web Part uses an other method but not documented yet and probably not intended to be used by developers.
