### ISSUE TITLE
react-list-form: People (Users) & Attachments are "Unsupported field types"?

### ISSUE THREAD

**Issue by spo-theworst** [pnp/sp-dev-fx-webparts#613]
** Is there a workaround? A fix? Awesome Web Part, but if People fields and Attachment fields aren't supported, it's not very useful for most users (since these 2 fields are built-in to every single list by default). Or are these critical features missing by design to further the PowerApps/Flow initiative?

## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Add React List Form to Modern page, connect to list, display fields for CRUD ops

## Observed Behavior

React List Form displays "Unsupported field type User" for People field, and "Unsupported field type Attachments" for Attachment field

## Steps to Reproduce

Copy folder "react-list-form". Open folder with VSCode. Run npm shrinkwrap, npm install, gulp bundle --ship, gulp package-solution --ship, upload sppkg to app library, copy contents of temp\deploy to primary site collection CDN. Create list with People field, enable attachments. Add page to Modern site. Add React List Form Web Part. Click pencil icon to edit Web Part, Turn on unsupported field types. Any People fields or Attachment fields will be noted with error messages in Observed Behavior and in screenshot below.

![image](https://user-images.githubusercontent.com/40704690/45172884-7d0ffa80-b1bb-11e8-83fc-12f7c113f1db.png)

**Comment by bubbleswap** [comment]
We just pushed the react-list-form web part and have the same question as you. The version we used has (Latest commit b84a8e6  on Dec 8, 2018), and the "people picker" and "attachments" fields will not show in 'New' and 'Edit' mode, but will in 'Display'. 

While the web part will serve our users greatly, without at least the 'people picker' field available in all modes, we'll be unable to use this web part. Over 80% of our lists use the 'people picker' field. 

Likely there must be good reasons the people and attachments fields are not included, though any tips to try adding people picker field would be much appreciated!

**Comment by Matej4386** [comment]
I would really appreciate in PeoplePicker (Person) could be implemented in edit and new mode ...

**Comment by jcollinsks** [comment]
I was looking for the same thing and will get started on the solution.

**Comment by JenniferUXWeb** [comment]
> I was looking for the same thing and will get started on the solution.

Thank you so much @jcollinsks – I can't express how much this is appreciated!

**Comment by sharepointknight** [comment]
I believe this has already been completed, @hugoabernier
