### ISSUE TITLE
Link to calendars  ? 

### ISSUE THREAD

**Issue by americo2015** [pnp/sp-dev-fx-webparts#618]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

Is there a way to link the labels at the bottom of the calendar to the calendar lists? 
<img width="439" alt="calendar" src="https://user-images.githubusercontent.com/9434799/45325107-543b8c80-b550-11e8-9d77-777d6c3cc8ba.png">

Best regards
Americo

**Comment by Gspot81** [comment]
Hi americo. You should be able to link them if you use a pointer from list 1 to list 2 via request executor. We did that in school. Remember?
