### ISSUE TITLE
React Update

### ISSUE THREAD

**Issue by ravenboilinux** [pnp/sp-dev-fx-webparts#621]
## Category

- [ X] Question

I wanted to know if SPfx works with React 16+ or not, and if so how to update the react and react-dom to 16+.

**Comment by VelinGeorgiev** [comment]
SharePoint Framewrok version 1.7 is suppose to work wit React 16 (at least this is the plan), but it is not released yet. You might have to wait until Microsoft releases SPFx  1.7.

**Comment by VelinGeorgiev** [comment]
@ravenboilinux, 1.7 version of the SharePoint Framework comes with React 16 by default so you can now upgrade your solution to 1.7 to support it.
