### ISSUE TITLE
SPHttpClient CORS preflight - Invalid headers 

### ISSUE THREAD

**Issue by frnk01** [pnp/sp-dev-fx-webparts#622]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Using SPHttpClient there is added SharePoint specific headers, which isnt allowed in preflight CORS request ([https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)).

`Request header field odata-version is not allowed by Access-Control-Allow-Headers in preflight response.`

Is there a way to get rid of this headers? I can't use es6 fetch with SPFX, so I guess I`m left with the SPHttpClient approach.

## Steps to Reproduce

```
    this.props.context.spHttpClient.fetch(this.props.feedUrl, SPHttpClient.configurations.v1, {
        method: "GET"
    }).then(rss => { 
      console.log("Feed", rss);
    });
```

**Comment by hugoabernier** [comment]
Closing this issue as it relates to general SPFx development. If you're still experiencing this issue, feel free to re-open it in the sp-dev-docs repo at https://github.com/sharepoint/sp-dev-docs, where we can better help you.

**Comment by Otrozone** [comment]
You can allow the "odata-version" by adding the header `"Access-Control-Allow-Headers": "odata-version"` in the response.

If you don't want to use share point headers in a request, you can try to define your own [XmlHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest).
