### ISSUE TITLE
React-search - problem when running

### ISSUE THREAD

**Issue by jbk75** [pnp/sp-dev-fx-webparts#623]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

Im getting error 
Cannot find module '@microsoft/sp-build-web' when running gulp serve

**Comment by hugoabernier** [comment]
Closing this issue as incomplete.

If you're still running into this problem, feel free to open a new issue. When you do, I encourage you to fill the issue template provided so that we can help you accordingly.
