### ISSUE TITLE
Sorry, this site can't be saved as a template. It contains apps that don't work in templates: Modern Script Editor web part by Puzzlepart

### ISSUE THREAD

**Issue by johnGu123** [pnp/sp-dev-fx-webparts#624]
I am working on a sharepoint online classic team sub-site, and i added this "sp-dev-fx-webparts" from https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor to allow me to add custom scripts inside modern pages. so i went to the subsite's site content link >> i add the web part app.

After that i reference the web part inside the sub-site's home page, and i added a javascript inside it. then i tried to save the sub-site as template but i got this error:-

**Sorry, something went wrong
Sorry, this site can't be saved as a template. It contains apps that don't work in templates: 
Modern Script Editor web part by Puzzlepart**

so my question is; if there is a way to add the web part to my sub-site and be able to save the sub-site as template?

Thanks

**Comment by mindlabco** [comment]
Hello @johnGu123,

Microsoft doesn't provide facility to save the major customization as site template. Please verify the same with below link reference. 
[](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-pages#supported-customizations-for-modern-pages)
I would suggest you follow the below steps:

1. Remove the Modern script editor from the site.
2. Save site as the template.
3. again add modern script editor to your new site.
