### ISSUE TITLE
Suggestion: Samples Directory List

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-fx-webparts#625]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Expected or Desired Behavior

There are really great samples in this repo and I have great respect for the effort and work going into these. 

Can I offer a suggest to have a Samples Directory List in the readme file in the samples directory to include the title, description and image of each sample? Much like the starter intranet contains list of the web parts used and description.

I was thinking given that you have a standard format for the readme for each sample, its possible that a script can be made to crawl through the samples and extract the heading, first paragraph and image. 

I don't know the build process behind this repo or whether there is CI process in  place where this function could be integrated and automated.

## Observed Behavior

I have seen some examples where the directory of the sample doesn't quite match the sample itself, for example: 

"react-sitepages-metadata" by @olegrumiancev is really good sample for a News Roll Up - This is something I get asked about a lot, so there is lots of value in this sample, but I only discovered this by accident as the name of the directory doesn't quite represent the content. 

Whilst it maybe easier to just update the directory name, it might be better to have a listing of the samples that you have in the repo, making the work and effort more visible to those who are new or don't know the ins and outs of the repo.

Just a idea.

Thanks
Paul

**Comment by hugoabernier** [comment]
@pkbullock -- thanks for this feedback. Partly thanks to your suggestion, we've created the samples browser at aka.ms/spfx-webparts to help meet this need.

We're going to continue improving the samples browser. If you have more great ideas on how to improve it, feel free to share them in this issue list.

Thanks!

**Comment by pkbullock** [comment]
@hugoabernier thanks Hugo, always a pleasure to add to the workload ;-) 

The samples site and your social media work is awesome for highlighting - well beyond my expectations for the outcome of this request.
