### ISSUE TITLE
Is there anything like a field picker

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-webparts#639]
- [x] Question
We have a list picker control. Is there anything like a field picker? I want to let the user select a list and then set some values for each field in the list. 

The goal, the user selects a list, and then based on the list selected the proprtypane would present all the field in the list and ask user if he wanted them to be included

**Comment by hugoabernier** [comment]
@russgove, great idea. I encourage you to open a feedback entry to the PnP reusable controls repo.
