### ISSUE TITLE
Cannot get partial data from Modern Sharepoint List to show on the page

### ISSUE THREAD

**Issue by NoKnowNo** [pnp/sp-dev-fx-webparts#657]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

I am using this webpart to get list item's data in a modern sharepoint list.

## Observed Behavior

I cannot get partial list item data from the modern sharepoint list. For example, I can get data from the "Employee Name" list column but I cannot get the "# of vacation days".

## Steps to Reproduce

I used the webpart in a modern sharepoint page to create a table. I used the list contains all my data and chose the list columns I need in the Display Section. 
![image](https://user-images.githubusercontent.com/44440302/47440341-f370b800-d77b-11e8-8a2f-91e0f407936c.png)
Then I checked the code in the template editor to make sure they are the same with what shown in the display section: 
![image](https://user-images.githubusercontent.com/44440302/47440412-1a2eee80-d77c-11e8-93f4-b6b1363b7912.png)
They are exactly the same but in the actual page, these columns' data are not showing:
![image](https://user-images.githubusercontent.com/44440302/47440451-32067280-d77c-11e8-9ac3-889b03bd5bbf.png)
I checked these list items which should have something to list under these list columns.

I am wondering how to get these columns' data from the list using this webpart.

**Comment by hugoabernier** [comment]
Closing this issue as it appears to be related to general SPFx dev. 

If you're still experiencing this issue, I encourage you to open a new issue in the sp-dev-docs repository at https://github.com/sharepoint/sp-dev-docs.
