### ISSUE TITLE
EventAggregator functionality is no longer working

### ISSUE THREAD

**Issue by priyankocts** [pnp/sp-dev-fx-webparts#659]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Background Information

> We have developed two SPFX webparts that communicate with each other and deployed them in SharePoint Online. We followed 'EventAggregator' sample to build these webparts and establish communication across them. We used spfx 1.4.1 framework (please refer to package.json file for reference). The communication between broadcaster and receiver webparts were working fine. However, since yesterday (24 Oct 2018) we found the communication is no longer working. It is important to specify that we did not make any changes to the code in our test environment before it ceased to work automatically.

> Upon detailed analysis we observed that the context.eventAggregator property is coming 'undefined' which accounts for the issue. Please refer to the FilteredEventsListWebPart.ts.txt file and render event.

**Receiver webpart file (TS)**
[FilteredEventsListWebPart.ts.txt](https://github.com/SharePoint/sp-dev-fx-webparts/files/2513915/FilteredEventsListWebPart.ts.txt)

**Package.JSON**
[package.json.txt](https://github.com/SharePoint/sp-dev-fx-webparts/files/2514032/package.json.txt)

## Expected or Desired Behavior

> We expect that the context.eventAggregator property would not be undefined.

## Observed Behavior

> context.eventAggregator property is coming as undefined. This version of code was working until 23rd Oct. Since 24th the code is breaking due to the fact that context.eventAggregator property is undefined. Please note that this behavior is same in both the broadcaster and receiver webparts.

## Steps to Reproduce

> Please refer to the attached files that should be sufficient to analyze the issue.

**Comment by VelinGeorgiev** [comment]
@priyankocts the context.eventAggregator was a feature in ALPHA state and never made it to general availability state. The recommendation was to NOTuse it in production since it was experimental feature.

There is a replacement for the event aggregator, but it is yet NOT officially released. Please have a look at that https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data

Again, the new dynamic data is also in PREVIEW and you should not use it in production until it is generally available.

**Comment by priyankocts** [comment]
@VelinGeorgiev Thanks for your reply. 

Could you advise if we can use react-rxjs-event-emitter to achieve communication between webparts?
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-rxjs-event-emitter

**Comment by VelinGeorgiev** [comment]
Yes, it should be part of 1.7 version, but it is never official until Microsoft announces it.

**Comment by ashishshukla1183** [comment]
> @patmill Do we have any tentative dates on when 1.7 will be released. It would help to communicate to our team on when they can expect an upgrade.

Any new updates on 1.7 release timelines?

**Comment by VelinGeorgiev** [comment]
@priyankocts, @ashishshukla1183  the dynamic data functionality is now officially releaced. You can use it instead of the event aggregator.

https://twitter.com/SharePoint/status/1060619788744097793?s=19

**Comment by maximreynaud** [comment]
I had the same problem.
I use "[Events]( https://developer.mozilla.org/fr/docs/Web/Guide/DOM/Events/Creating_and_triggering_events)" (+ [polyfill for old navigator like IE11](https://www.npmjs.com/package/custom-event-polyfill)) for the moment. I will wait for 1.7 to use dynamic data.

Cheers,

**Comment by VelinGeorgiev** [comment]
@maximreynaud , 1.7 is out! You can upgrade your project (using the [office 365 cli](https://pnp.github.io/office365-cli/cmd/spfx/project/project-upgrade/)) and migrate to dynamic data.
