### ISSUE TITLE
Script Editor Web Part is missing in the list of web parts to add

### ISSUE THREAD

**Issue by NagJoshi** [pnp/sp-dev-fx-webparts#660]
## Category

- [ X] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behaviour

Script Editor Web Part should be available to add it to a Modern Page

## Observed Behaviour
Can't find the Script Editor Web Part in the list of Web Parts even after successful build, package and deploy

## Steps to Reproduce

- Enabled office 365 public CDN
- npm install
- gulp serve - Workbench opens, can add the webpart successfully, it works fine.
- Updated the cdnBasePath in the write-manifests.json. 
- gulp server --ship
- gulp serve package-solution --ship
- Copied the Temp\Deploy folder contents to CDN Folder in Site Assets
- Uploaded .sppkg file to app catalog. Deployed successfully.
- Opened the Modern Site Collection (same site as mentioned in the cdn path above)
- Site Contents >> Added Modern Script Editor Webpart. No errors, app added successfully.
- Edited a page in the Site, tried to add the Script Editor Web Part but it's not there in the list.

Am I missing anything? Please suggest. Thanks!

**Comment by stijnbrouwers** [comment]
I am having the same issue.

**Comment by fcatinot** [comment]
@NagJoshi I had the same problem. I've created a new web part solution with same name from scratch, copy files from Script Editor Web Part and it works now.

**Comment by dbrys1** [comment]
@fcatinot Can you elaborate more on what you did. I've been having the same issue and have tried replacing all the necessary files in the CDN folder as well as the .sppkg file on the app catalog. Any more information would be helpful. Thanks

**Comment by fcatinot** [comment]
@dbrys1  default settings are to require a script enabled site. If you you change this parameter, set variable called "requiresCustomScript" to false in ScriptEditorWebPart.manifest.json
[https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites) or you can enable custom script on yout site [https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script)

**Comment by CRTSEMINOLE** [comment]
I am having the same issue as described above. The web part is working on existing sites but not any new sites that get created. I downloaded the files again, deployed them to another environment. The package deploys successfully, but once again the web part will not show for any new Communication sites I create. Any assistance will greatly be appreciated as I really need this webpart deployed to a new site as soon as possible. Thanks!

**Comment by amhrj** [comment]
> > I am having the same issue as described above. The web part is working on existing sites but not any new sites that get created. I downloaded the files again, deployed them to another environment. The package deploys successfully, but once again the web part will not show for any new Communication sites I create. Any assistance will greatly be appreciated as I really need this webpart deployed to a new site as soon as possible. Thanks!
> 
> Finally got this working. As fcatinot said above I had to set the variable called "requiresCustomScript" to false in ScriptEditorWebPart.manifest.json. I specified the CDN path to the files from temp/deploy that I put in the SiteAssets of the app catalog site from the new build. The I got this error when running gulp --ship: "The build failed because a task wrote output to stderr". To fix this:
> 
> 1. go to config/tslint.json and modify as follows
> 2. "no-duplicate-case" -> "no-duplicate-switch-case"
> 3. delete "valid-typeof" line
> 4. set "semicolon" to false
>    save
>    Run gulp --ship
>    Run gulp package-solution --ship
> 
> Hope this helps anyone else that is having the same issue. If anyone needs help after following the steps I wrote above let me know and I am happy to assist.

Followed the step and now the script editor is in communication site as well. Cheers.
