### ISSUE TITLE
react-search-refiners - Hover panel

### ISSUE THREAD

**Issue by shaysil** [pnp/sp-dev-fx-webparts#679]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior
Hi,
is it possible to add the Hover Panel to the Tiles layout?

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
Hi @shaysil. Thank you for the feedback. By hover panel, I guess you mean previews like the list layout?

Unfortunately, this feature is not so easy to implement since we can't benefit of Office UI Fabric React components in templates. We'll see what we can do but can't guarantee anything.

**Comment by shaysil** [comment]
Hi @FranckyC 
Thank you for that answer.
