### ISSUE TITLE
Replace New\Edit\Display forms with custom SPFX webpart in New Experience.

### ISSUE THREAD

**Issue by enti333** [pnp/sp-dev-fx-webparts#686]
- [x] Question
- [ ] Bug
- [ ] Enhancement

Hello. I have very simple scenario but I am not able to solve my problem. In classic design I have no problem to add some webparts to NEW\EDIT\DISPLAY forms...So I could simple create for example SPFX webpart and replace the standard form webpart and the user is working with list item data on my spfx webparts...This is great if you need some logic in your forms....Ok so in classic design this is not a problem.... But I didn't find any solution how to achive this in new experience design....I want to simple replace the form with my custom spfx webpart form...Yes yes I can use power apps but there are many limitations so this is also not the right way for me....I just want to create my own new\edit\display forms and replace the forms in new experience...Hmm...Thank you for your help....

**Comment by zplume** [comment]
The ability to create custom SPFx new/edit/display list forms (and have these associated with the list instead of the default forms) would be fantastic, is this on the roadmap?

**Comment by Jke-A** [comment]
This should be the go-to way to customize forms in SharePoint. PowerApps just doesn't cut it when we need heavily customized forms.

**Comment by jonathaneckman** [comment]
+1 We need this.

**Comment by selvaaforu** [comment]
Is any update for this activities?

**Comment by Jke-A** [comment]
> 
> 
> Is any update for this activities?

[This one](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/37169995-allow-us-to-develop-custom-modern-forms) has more votes and should be getting some attention soon.

**Comment by AHBAPAKA** [comment]
This is life saving feature in O365 LOB App Development

**Comment by sanjayadsure** [comment]
This is must have

**Comment by z0loy** [comment]
This will saves many lives ! I hope we'll find it soon

**Comment by hugoabernier** [comment]
@enti333 this is a great idea, but this issue list is intended for issues with SPFx web part samples. I encourage you to use the [SharePoint UserVoice](https://sharepoint.uservoice.com/) to route your suggestion to the appropriate channels.
