### ISSUE TITLE
How to use an extension as consumer of dynamic data?

### ISSUE THREAD

**Issue by tanwarShobhraj** [pnp/sp-dev-fx-webparts#724]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Authors

@waldekm

How to use a SPFx extension as consumer of Dynamic data from a provider(webpart/extension)?

**Comment by hugoabernier** [comment]
@tanwarShobhraj did you ever solve this issue?

I'll go ahead and close this issue. If you still need help, I recommend you open a new issue with the [sp-dev-docs](https://github.com/sharepoint/sp-dev-docs) repository as this issue list is intended for issues related to web part samples in this repository.
