### ISSUE TITLE
react-calendar-feed sort order option?

### ISSUE THREAD

**Issue by elephant-33** [pnp/sp-dev-fx-webparts#735]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

@hugoabernier, @VesaJuvonen 

## Expected or Desired Behavior

Would it be possible to add a sort option when referencing a SharePoint List? It would be nice if it would sort by start date. 

## Observed Behavior

When I reference a SharePoint event list with 51 events (of imported data), it is sorting it in what seems to be a random order, maybe id#? I'd like to be able to sort it by date. I tried to reference a view sorted by date but that didn't seem to work either.

## Steps to Reproduce

Create a large event list and link it to this web part.

**Comment by elephant-33** [comment]
![example](https://user-images.githubusercontent.com/19228044/50527862-bba22b80-0ab0-11e9-9cac-e66d9e7f0928.jpg)
Just wanted to show a print screen of my situation. I should mention that I'm importing data into the Event List via a Flow so sorting by ID won't work for this use case (assuming that is how it is being done by default)

**Comment by AMEspino** [comment]
> ![example](https://user-images.githubusercontent.com/19228044/50527862-bba22b80-0ab0-11e9-9cac-e66d9e7f0928.jpg)
> Just wanted to show a print screen of my situation. I should mention that I'm importing data into the Event List via a Flow so sorting by ID won't work for this use case (assuming that is how it is being done by default)


You may need to modify SharePointCalendarService.ts and orderBy('EventDate',true). In addition to this, you need to change getAll() to get(). Please see below changes that I've done:

![image](https://user-images.githubusercontent.com/34465866/59906739-02f3ee00-943c-11e9-878e-58ee9363acb6.png)

**Comment by hugoabernier** [comment]
Hey @AMEspino, sorry I had missed this issue until today. I'll include your suggestions in my next update and submit a PR. Good catch!

**Comment by prathimapilli** [comment]
> Hey @AMEspino, sorry I had missed this issue until today. I'll include your suggestions in my next update and submit a PR. Good catch!

Hi @hugoabernier for me react calendar events are not working in ie.. it is working fine in chrome..If you have any thoughts please let me know

**Comment by petkir** [comment]
Hi @prathimapilli  and @hugoabernier 

I have taken a look at the IE 11 problem. 

[rss-parser](https://github.com/rbren/rss-parser#readme) requires polyfills, in the description only Promise is standing, but this is not the Error in IE in this Sample. 

You can comment out the ```RSSCalendarService``` in ```CalendarServiceProviderList``` and it will work as expected in IE. 

I tried pnp/polyfill-ie11, but this little change hasn't worked for me and IE11.

@hugoabernier  should I take a deeper look to Support IE ?

**Comment by hugoabernier** [comment]
@petkir it would be great if you have the time to do so!

**Comment by petkir** [comment]
Hi @hugoabernier 
It's not so a funny thing, you can find in the build  Webpart Souce this code ```class Parser``` this is not supported in IE.
You have to translate class Parser to var Parser ..., normally Webpack does this job.

My current solution is to use babel-loader and extend the webpack config to solve this issue.

link to [branch](https://github.com/petkir/sp-dev-fx-webparts/tree/petkir-react-calendar-feed-735/samples/react-rss-reader)  the magic is in the gulpfile.js file.

I will think about these few lines again because the webpack time increase from 6.66s to 36s and this is too much in my opinion.

**Comment by petkir** [comment]
Hi @hugoabernier 

Sorry for the delay but now I have a solution that is ok for the webpack time in my opinion.

Short description what's happened

With the webpack ```RuleSetRule``` exclude  the webpack time is  5 times slower than without 
```
exclude: [/node_modules\/(?!(rss-parser))/],
```
with the ```include``` the time is nearly the same than before
