### ISSUE TITLE
SPFx React Slide Swiper: Not able to edit the cards in the webpart

### ISSUE THREAD

**Issue by rajivsr23** [pnp/sp-dev-fx-webparts#771]
I have successfully deployed and added the React Slide Swiper to a page. I can edit options like autoplay, number of slides etc. But, I cannot change the Images or edit the text on the slider. 

Kindly help!

**Comment by BertrandLagarde** [comment]
If I'm not wrong, there is a "SharePoint List Name" field. This field defines which list in your site is given the data to the webpart.
You have to create a list in your site (named "Swiper Content") with those three columns "Title", "Description", "ImageUrl".
Then when you will add an item in that list it should appears in your slider.

But I don't know what I should put in the ImageUrl field. I have tried many different things but I still have a slider from a blank image to another blank image...

**Comment by jackpoz** [comment]
I opened a PR at https://github.com/SharePoint/sp-dev-fx-webparts/pull/1044 with some more info and fixes.
>When using the webpart in SharePoint, either in the SharePoint Workbench or deployed, the webpart reads by default from a List called "Swiper Content" with fields Title, ImageUrl, Description of type Single line of text. The list has to be created manually.
