### ISSUE TITLE
Connect SPFx webpart and SP list using dynamic data

### ISSUE THREAD

**Issue by HeinPauwelyn** [pnp/sp-dev-fx-webparts#773]
- [x] Question
- [ ] Bug
- [x] Enhancement

I know a SPFx webpart can be connected to another SPFx webpart using `PropertyPaneDynamicFieldSet` and `PropertyPaneDynamicField`. My question is can a webpart being connected to a SP list?

I'll connect a webpart to a list to create or edit items from that list. This I'll do because the webpart contains a form where some fields depends on another field and repeating sections.

**Comment by clechner77** [comment]
Unfortunately you can't add another web part on to a list. There is the list web part but I don't see any hooks into that yet. One option is building a list based on the SharePoint react list control.

I'm curious if SharePoint search saves the query into session storage or local storage.  If it did, it might help with search integration and custom web parts. Maybe there are better techniques out there.
