### ISSUE TITLE
SPLoaderError.loadComponentError

### ISSUE THREAD

**Issue by MohamedMusthaque** [pnp/sp-dev-fx-webparts#785]
- [ ] Question
- [x] Bug
- [ ] Enhancement

[SPLoaderError.loadComponentError]:
***Failed to load component "41e37f03-2ea8-4f19-b77a-f2121a1e7c45" (SpSecurityWebPart).
Original error: ***loadComponent() returned an empty object for component "41e37f03-2ea8-4f19-b77a-f2121a1e7c45" (SpSecurityWebPart).

***INNERERROR:
***loadComponent() returned an empty object for component "41e37f03-2ea8-4f19-b77a-f2121a1e7c45" (SpSecurityWebPart).
***CALLSTACK:
t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-01.006/sp-webpart-workbench-assembly_en-us_ab51ffb0e2576c31246f5ed33d950474.js:272:16049
t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-01.006/sp-webpart-workbench-assembly_en-us_ab51ffb0e2576c31246f5ed33d950474.js:1143:21050
__WEBPACK_AMD_DEFINE_RESULT__</</s</e.buildErrorWithVerboseLog@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-01.006/sp-webpart-workbench-assembly_en-us_ab51ffb0e2576c31246f5ed33d950474.js:1143:16214
__WEBPACK_AMD_DEFINE_RESULT__</</s</e.buildLoadComponentError@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-01.006/sp-webpart-workbench-assembly_en-us_ab51ffb0e2576c31246f5ed33d950474.js:1143:12240
i/<@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-01.006/sp-webpart-workbench-assembly_en-us_ab51ffb0e2576c31246f5ed33d950474.js:1143:59389

Please Advice regarding this issue.

**Comment by russgove** [comment]
Hi Mohammed ,
what version of SPFX are you using?

Russell

**Comment by MohamedMusthaque** [comment]
Hi Russel,

Sorry for the late reply due to bike accident.
The SPFX version is 1.4.1

Regards,
<https://about.me/MohamedMusthaque?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>
Mohamed Musthaque
about.me/MohamedMusthaque
<https://about.me/MohamedMusthaque?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>

**Comment by hugoabernier** [comment]
Closing this issue as invalid.

If you're still experiencing this issue, feel free to open a new issue. When you do, please take the time to fill the issue template provided so that we can help you better. Information such as sample, author, and environment information help us diagnose the issues.

Thanks for your understanding.
