### ISSUE TITLE
Failed to load entry point from component 

### ISSUE THREAD

**Issue by MohamedMusthaque** [pnp/sp-dev-fx-webparts#792]
[ ]  Question
[x] Bug
[ ]  Enhancement

Did clone the following (React-security grid webpart)
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-securitygrid
and did a npm install.
But after gulp serve I got the following issue.

![1](https://user-images.githubusercontent.com/9990475/53298908-0beffc80-385a-11e9-8cf7-04a3ec898a6d.PNG)
![2](https://user-images.githubusercontent.com/9990475/53298909-0c889300-385a-11e9-815e-767ca4eb7605.PNG)

-------------------------------------------------------------------------------------------------------------------
SharePoint Workbench error:
[SPLoaderError.loadComponentError]:

***Failed to load component "41e37f03-2ea8-4f19-b77a-f2121a1e7c45" (SpSecurityWebPart).

Original error: ***Failed to load entry point from component "41e37f03-2ea8-4f19-b77a-f2121a1e7c45" (SpSecurityWebPart).

Original error: Error loading https://component-id.invalid/41e37f03-2ea8-4f19-b77a-f2121a1e7c45_0.0.1
	Cannot find module "./spSecurity.css"

***INNERERROR:

***Failed to load entry point from component "41e37f03-2ea8-4f19-b77a-f2121a1e7c45" (SpSecurityWebPart).

Original error: Error loading https://component-id.invalid/41e37f03-2ea8-4f19-b77a-f2121a1e7c45_0.0.1
	Cannot find module "./spSecurity.css"

***CALLSTACK:

SPError@https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:24
SPLoaderError@https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:4211:21
__WEBPACK_AMD_DEFINE_RESULT__</</ErrorBuilder</ErrorBuilder.buildErrorWithVerboseLog@https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3821:21
__WEBPACK_AMD_DEFINE_RESULT__</</ErrorBuilder</ErrorBuilder.buildLoadComponentError@https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3743:16
_loadComponentImpl/<@https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:7952:15

Terminal error:
 Error - [webpack] 'dist':
./lib/webparts/spSecurity/components/SpSecurity.js
Module not found: Error: Can't resolve './spSecurity.css' in 'C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components'
resolve './spSecurity.css' in 'C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components'
  using description file: C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\package.json (relative path: ./lib/webparts/spSecurity/components)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\package.json (relative path: ./lib/webparts/spSecurity/components)
    using description file: C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\package.json (relative path: ./lib/webparts/spSecurity/components/spSecurity.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components\spSecurity.css doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components\spSecurity.css.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components\spSecurity.css.json doesn't exist
      as directory
        C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components\spSecurity.css doesn't exist
[C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components\spSecurity.css]
[C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components\spSecurity.css.js]
[C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components\spSecurity.css.json]
[C:\Users\spdev.groupit.HEMAS\Videos\react-securitygrid\lib\webparts\spSecurity\components\spSecurity.css]
 @ ./lib/webparts/spSecurity/components/SpSecurity.js 36:0-27
 @ ./lib/webparts/spSecurity/SpSecurityWebPart.js

Please help me resolve this issue.
SPFX version: 1.4.1
Node version: 8.15.0
npm version: 6.4.1

**Comment by zachroberts8668** [comment]
I am running into the same issue, anyone have a solution?

Thanks,
Zach

**Comment by suryarsp** [comment]
I am also getting the same issue. 
Do I need to reduce my typescript version? Currently, I am using 3.4.5
[SPLoaderError.loadComponentError]:
***Failed to load component "00000000-2017-4bc3-9a39-18dfdd167e1b" (DocumentNavigationWebPart).
Original error: ***Failed to load entry point from component "00000000-2017-4bc3-9a39-18dfdd167e1b" (DocumentNavigationWebPart).
Original error: Error loading https://component-id.invalid/00000000-2017-4bc3-9a39-18dfdd167e1b_0.0.1
	Cannot find module "classlist.js"

***INNERERROR:
***Failed to load entry point from component "00000000-2017-4bc3-9a39-18dfdd167e1b" (DocumentNavigationWebPart).
Original error: Error loading https://component-id.invalid/00000000-2017-4bc3-9a39-18dfdd167e1b_0.0.1
	Cannot find module "classlist.js"
***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:8776:24)
    at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:4270:28)
    at Function.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:3946:21)
    at Function.ErrorBuilder.buildLoadComponentError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:3854:21)
    at https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:7048:47

**Comment by Ankit7992** [comment]
I am also running into the same issue. Kindly help.

**Comment by l-Marty-l** [comment]
In my case `gulp clean` helped me.

**Comment by russgove** [comment]
Hi, With later versions of spfx you need to comment out the line 24
//require('./spSecurity.css'); // loads the SpSecurity,css with unmodified names
from componeens/spsecurity.tsx  it works.  I'm not sure how that got in there..

**Comment by russgove** [comment]
After looking into it further, after commenting out the line above the column headers don't display at an angle as they should. 

It turns out that the file SoSecurity.scss got removed from the components folder. 
To fix it correctly kust add the above file to the components folder with this content:
@import 'node_modules/office-ui-fabric-react/dist/sass/Fabric.scss';
//*Set the Header are to 140px so it can hold the rotated headers
.SPFXSecurityGrid .ms-DetailsHeader { //* when adjusting line hieight also need to adjust second parameter to transform:translate below
    height: 140px;
    white-space: nowrap;
}
//*Set the wrappers around the headers to display at 45degree angles
.ms-DetailsHeader-cell.rotatedColumnHeader{
    transform:  translate(25px,40px ) //*Change second parameter when adjusting line height
    rotate(315deg);
    padding-bottom: 90px;
    width: 36px !important;
   
    
}
.ms-DetailsHeader-cell{
    vertical-align: bottom;  
}
.ms-DetailsHeader-cell span  {
    overflow: visible;
 }
 .ms-List-cell:nth-child(even) .ms-DetailsRow {
    background: #EEE;
  }

Then you get no errors and the headers display at an angle:
![image](https://user-images.githubusercontent.com/2412956/60747251-f5695880-9f51-11e9-924f-43a2fa1c5413.png)

**Comment by russgove** [comment]
Ill push an update soon.

**Comment by russgove** [comment]
Not sure who,closes,issues here, but this can be closed.  the missing file was added back in july,
