### ISSUE TITLE
react-rss-reader does not install all necessary files

### ISSUE THREAD

**Issue by clohigh** [pnp/sp-dev-fx-webparts#793]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@eoverfield 

## Expected or Desired Behavior
So what I expect to happen is that once I run npm install on the solution for it not to return any errors or files missing.

## Observed Behavior

However, when I run npm install on the solution it runs fine until I get several errors along the lines of

"npm WARN tar ENOENT: no such file or directory" about 60 times,

## Steps to Reproduce

Clone or download the "sp-dev-fx-weparts" directory.

Navigate to the samples and then finally the react-rss reader sample.

Then while in the directory run npm install.

**Comment by eoverfield** [comment]
@[clohigh] you should definitely not be seeing such errors. What version of node are using?

node -v

**Comment by clohigh** [comment]
Hi Eric thank you for the quick response. I'm on v8.12.0

Carloz

**Comment by eoverfield** [comment]
Good version, I used 8.11.4 to test, 8.12.0 should work. I will check to see if something is missing.

**Comment by clohigh** [comment]
Sounds great, thank you sir.

Carloz

**Comment by otaconwow** [comment]
I was getting the same behavior, doing the steps mentioned in [this](https://stackoverflow.com/questions/53578201/npm-err-404-not-found-event-stream3-3-6) post on stackoverflow solved the issue. Maybe it can help you guys adress this issue.

Regards,

Otacon

**Comment by eoverfield** [comment]
Thank you for sharing this fix.

**Comment by clohigh** [comment]
That fixed it thank you sir @otaconwow

**Comment by jackpoz** [comment]
I created a PR for this issue https://github.com/SharePoint/sp-dev-fx-webparts/pull/1032

**Comment by jackpoz** [comment]
The PR got accepted, this issue can be closed
