### ISSUE TITLE
React Content Query WebPart - lookup column additional fields value

### ISSUE THREAD

**Issue by Brian78912** [pnp/sp-dev-fx-webparts#805]
Installed on SharePoint 365. 
Very nice application :)
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

@spplante

## Expected or Desired Behavior

Return value of additional fields on lookup column.

## Observed Behavior

> _If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Steps to Reproduce

Create a list, add a text column, create a secondary list add a lookup column and select the text column as additional column. 

Columns:
![food](https://user-images.githubusercontent.com/48408624/54089414-ef2eeb00-4368-11e9-88b7-59dc3773bf4f.png)

Result :
![food2](https://user-images.githubusercontent.com/48408624/54089468-71b7aa80-4369-11e9-8a0a-472a614f297a.png)

Edit template content:
![food3](https://user-images.githubusercontent.com/48408624/54089478-81cf8a00-4369-11e9-8f16-c9c27a4ad187.png)

**Comment by PopWarner** [comment]
@Brian78912, thank you for submitting this issue.

We have tested this with the newest version of the web part and it appears to be working successfully. Can you please test with the newest version of the web part and if you are still experiencing the issue submit a new issue?

Thank you again! 💜🧡
