### ISSUE TITLE
React - Custom Property Pane Controls Build Errors with SPFx 1.8

### ISSUE THREAD

**Issue by heliste2** [pnp/sp-dev-fx-webparts#824]
## Category

- [ ] Question
- [X] Bug
- [ ] Enhancement

## Authors
@waldekm

## Observed Behavior

The React - Custom Property Pane Controls does not work with SPFx 1.8. There are many tslint errors that prevent the project from being built and this is the example for extending the property pane also used on the Microsoft Docs site (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/build-custom-property-pane-controls).

**Comment by hugoabernier** [comment]
@heliste2 did you ever resolve this issue?

I'll go ahead and close it as this appears to be a general SPFx dev issue, and this issue list is intended for issues with the SPFx web part samples.

If you're still experiencing problems, feel free to open a new issue in the [sp-dev-docs](https://github.com/sharepoint/sp-dev-docs) repository.
