### ISSUE TITLE
List form webpart gives error in SharePoint Online

### ISSUE THREAD

**Issue by Ooste** [pnp/sp-dev-fx-webparts#833]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

I have tested the 'List form' sample from github in workbench and it worked. When i uploaded the app and tried it in SharePoint Online I got the following error:

![image](https://user-images.githubusercontent.com/49239989/55779268-48438900-5aa5-11e9-9376-e5cfc25b7051.png)

Anyone an idea what I am doing wrong?

Thanks for your contribution! Sharing is caring.

**Comment by jindalv10** [comment]
The error is related to 'FormFieldStrings' under your en-us.js file.

Please check, if you are you able to reference string value under en-us.js file?

**Comment by AndrewCarterBreakwaterIT** [comment]
I had a similar issue I think I had to make an update to the config.json to map to the location of the string files

**Comment by hikmatune** [comment]
I had same issue, I wasn't packaging the solution properly, I used the following commands to package the solution and works like a charm!
```
clone
cd react-list-form
npm install
gulp build --ship
gulp bundle --ship
gulp package-solution --ship
```
