### ISSUE TITLE
This does not work in SharePoint 2019 On Premise Environment

### ISSUE THREAD

**Issue by nehasha** [pnp/sp-dev-fx-webparts#835]
I follow all the instructions on this for deployment but when I add the webpart, it gives below error. PLease confirm if this is compatible with On Prem version? I am using SharePoint 2019

[SPLoaderError.loadComponentError]:
***Failed to load component "3a328f0a-99c4-4b28-95ab-fe0847f657a3" (ScriptEditorWebPart).
Original error: ***Manifest not found for component id "974a7777-0990-4136-8fa6-95d80114c2e0" and version "1.5.1".

***INNERERROR:
***Manifest not found for component id "974a7777-0990-4136-8fa6-95d80114c2e0" and version "1.5.1".
***CALLSTACK:
Error
    at t [as constructor] (http://site/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=2g4QD:356:15766)
    at new t (http://site/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=2g4QD:807:22174)
    at Function.e.buildErrorWithVerboseLog (http://site/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=2g4QD:807:14408)
    at Function.e.buildLoadComponentError (http://site/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=2g4QD:807:10829)
    at http://site/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=2g4QD:807:62084

**Comment by atakhantamer** [comment]
did u find the solution? i have the same problem.

**Comment by scfrederic** [comment]
Hello,
Please find here my guide to make compatible SharePoint Online Modern Webparts with SharePoint 2019 :
https://github.com/scfrederic/from-sponline-to-sp2019/blob/master/README.md

**Comment by RMcode** [comment]
has anyone found the solution for this issue? @scfrederic  I have tried your suggestion but unfortunately, it did not work :(
@nehasha  have you found a workaround?

**Comment by nehasha** [comment]
> Hello,
> Please find here my guide to make compatible SharePoint Online Modern Webparts with SharePoint 2019 :
> https://github.com/scfrederic/from-sponline-to-sp2019/blob/master/README.md

Did it work for you?

**Comment by scfrederic** [comment]
Hello, this solution works for me. Please can you tell me what issue you encounter?

**Comment by scfrederic** [comment]
Hello, the solution described [here](https://github.com/scfrederic/from-sponline-to-sp2019/blob/master/README.md) works for me.
Please can you tell me what issue you encounter?

**Comment by nehasha** [comment]
This is deployed but not available to add on webpage.

**Comment by jcschmidt31** [comment]
I was able to take the zipped 1.4 package and apply it to my 2019 on prem environment without issue.

**Comment by SharePointGuys** [comment]
@jcschmidt31 could you advise where to find "zipped 1.4 package"? I have the exact issue as @nehasha mentioned. I'm testing this web part on my SP2019 DEV. 

- SP URL of testing site collection:  http://sp2019dev/sites/communicationsite
- APP Domain: sp2019devapps (added an entry in local host file: 127.0.0.1  sp2019devapps)
- APP prefix: apps
- Microsoft SharePoint Foundation Subscription Settings Service installed and started.
- APP Management Service installed and started
- This web part package is successfully built (thanks to https://github.com/SharePoint/sp-dev-fx-webparts/issues/672)
- This web part is successfully installed in Apps for SharePoint (no errors)
- To add apps in site collection under http://sp2019dev/sites/communicationsite/_layouts/15/addanapp.aspx
![image](https://user-images.githubusercontent.com/43420322/60297071-6cb93f80-98f5-11e9-8882-568c4476ae88.png)
- Click "Find Out Why": 
![image](https://user-images.githubusercontent.com/43420322/60297116-83f82d00-98f5-11e9-9b1c-96547e4cc9ef.png)
- To add the web part in a modern page, cannot find the web part:
![image](https://user-images.githubusercontent.com/43420322/60297158-9ecaa180-98f5-11e9-9610-e4515a7773fd.png)


Any suggestion or a piece of hint would be much appreciated. Thank you very much.

BTW, this DEV environment is a single server.

**Comment by SharePointGuys** [comment]
One more screenshot, which shows that the web part has been added to the site collection; however, it's just not shown from the Toolbox. :( 

![image](https://user-images.githubusercontent.com/43420322/60297865-2cf35780-98f7-11e9-92bf-f1540f25973b.png)

![image](https://user-images.githubusercontent.com/43420322/60297880-35e42900-98f7-11e9-903f-21a6ad48ac53.png)

**Comment by jcschmidt31** [comment]
https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-content-query-webpart/content-query-webpart-1.4.1.zip

**Comment by SharePointGuys** [comment]
@jcshmidt31 Thank you very much. I will try this version and will update the thread.

**Comment by SharePointGuys** [comment]
@jcschmidt31 Thank you very much. the zip 1.4.1 works for me.
