### ISSUE TITLE
SPFX-React using office-ui-fabric giving "Error - [tsc] IStyleSet.d.ts(18,67): error TS1005: ';' expected" when gulp build...

### ISSUE THREAD

**Issue by gonadn** [pnp/sp-dev-fx-webparts#843]
- [x] Question
- [ ] Bug
- [x] Enhancement

**Expected or Desired Behavior**
Webpart should build/compile with Office-ui-fabric styles...

**Observed Behavior**

When i run "gulp build" i get therese errors shown in picture:
![image](https://user-images.githubusercontent.com/3224441/56274287-c4217f00-60fe-11e9-8ee9-90dbb86e62ad.png)

**Dependencies**

![image](https://user-images.githubusercontent.com/3224441/56274821-c6380d80-60ff-11e9-8f0e-805af61deae6.png)

tsc version: 3.4.3
node: v8.15.0
@microsoft/sharepoint-genertator  LATEST

How can i fix this issue/error with bulding fabric styles in webpart?

**Comment by Suresh-Lakum** [comment]
I am facing same issue. Any update on this?

**Comment by O365DevHero** [comment]
@gonadn  @Suresh-Lakum 

Have you looked at this issues https://github.com/OfficeDev/office-ui-fabric-react/issues/6126

It could be with version conflict,can we downgrade the version and see if that works instead of commenting the line in IStyleSet.d.ts file?

**Comment by hugoabernier** [comment]
Closing this issue as invalid.

If you're still experiencing this issue, feel free to open a new issue in the [sp-dev-docs](https://github.com/sharepoint/sp-dev-docs) repository, as this issue list is intended for issues with SPFx web part samples in this repository.
