### ISSUE TITLE
Phantomjs development frozen - new headless server suggested

### ISSUE THREAD

**Issue by ghost** [pnp/sp-dev-fx-webparts#856]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Expected or Desired Behavior
Phantomjs development has been frozen with no effort or packages available for ARM64 or other future OSs.  A new headless server should be incorporated to maximize compatibility now and in the future.  I was unable to see where the dependency is declared to try to replace it with puppeteer.

## Observed Behavior
I would like the ability to use the template in VsCode with  newer OSs like Debian 9 Stretch ARM64. Build fails because no eligible packages are available for ARM64 

## Steps to Reproduce
Attempt  to run "npm install" on a sample in VsCode on Debian 9 ARM64.  
# Submission Guidelines
Please make the packages like Phantomjs a part of the normal module dependencies so they can be modified.

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
This issue list is intended for issues related to SPFx web part samples. 

If you're still experiencing issues, feel free to open a new issue in the [sp-dev-docs repository](https://github.com/sharepoint/sp-dev-docs).
