### ISSUE TITLE
TaxonomyFieldType is still unsupported types in React List Form web part

### ISSUE THREAD

**Issue by guptarajesh001** [pnp/sp-dev-fx-webparts#874]
Could any one know when TaxonomyFieldType will be supported in React List Form web part?
![ListForm](https://user-images.githubusercontent.com/13049898/58851445-6d710400-86b0-11e9-8066-7834afbff596.png)

**Comment by jindalv10** [comment]
I able to get this working and will be update code soon.

**Comment by hugoabernier** [comment]
@jindalv10 were you still working on this fix?

**Comment by jindalv10** [comment]
Hi @hugoabernier 

I have already finished this feature but I don't know how to update the web part and commit on github.

Thanks
Varun

**Comment by hugoabernier** [comment]
@jindalv10 you should sign up for an upcoming [Sharing Is Caring](https://github.com/pnp/sharing-is-caring) session. We walk you through how to create contributions.

Alternatively, feel free to reach out to me directly and I can work with you to submit your changes.

Thanks for working on this!

**Comment by sharepointknight** [comment]
This was completed in a recent pull request, #1501

**Comment by bcameron1231** [comment]
Closing as this was fixed with #1501
