### ISSUE TITLE
What is this error?Not sure how it came suddenly

### ISSUE THREAD

**Issue by ymihir** [pnp/sp-dev-fx-webparts#954]
Target environment: SP2019. 
SPFx version 1.4.1

![image](https://user-images.githubusercontent.com/7568187/63368561-c68d3180-c39b-11e9-9b03-86ead4f9c0a6.png)

**Comment by hugoabernier** [comment]
Closing this issue as there isn't enough information to help you.

If you're still experiencing this issue, feel free to open a new issue. When you do, please take the time to fill the issue template that's provided so that we can help you appropriately.
