### ISSUE TITLE
react-rss-reader - ampersands (&amp;) not being decoded in links

### ISSUE THREAD

**Issue by furler** [pnp/sp-dev-fx-webparts#956]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@VesaJuvonen

## Expected or Desired Behavior
I have RSS feeds where if an ampersand is in the link/title it is encoded as "&amp;" - I believe this is correct for RSS/XML feeds, however the web part does not decode them, so they are displayed as "&amp;" instead of "&" like they should

## Observed Behavior
"&amp;" is rendered as is, instead of being converted to "&"

## Steps to Reproduce
Any RSS feed that contains "&amp;" in a title

**Comment by hugoabernier** [comment]
@furler the author for this sample is @ericoverfield, not Vesa.

**Comment by AbhishekGarg** [comment]
@eoverfield 
Calling a small decode function for each ListRow item (reference from an [old stackoverflow answer](https://stackoverflow.com/a/7394787/1293256)) might be useful in solving this issue.

If this seems like a good idea, I can send in a PR.
Example of feed having '&' in an item's title: https://www.pbs.org/wgbh/nova/rss/all/

**Comment by furler** [comment]
> @eoverfield 
> If this seems like a good idea, I can send in a PR.
> Example of feed having '&' in an item's title: https://www.pbs.org/wgbh/nova/rss/all/

This would be most appreciated - as I mentioned, decoded ampersands are correct RSS - and I just happen to be using this to grab headlines mentioning the company I work for, which, can you guess, has an ampersand in its name.

**Comment by AbhishekGarg** [comment]
@eoverfield your thoughts please.

**Comment by eoverfield** [comment]
@AbhishekGarg please submit that PR if you could. Thank you for finding and reporting.

**Comment by hugoabernier** [comment]
@AbhishekGarg I'll make sure to process the PR quickly. Thanks for contributing!
