### ISSUE TITLE
Deploy to Non-Script Sites

### ISSUE THREAD

**Issue by rdkumar** [pnp/sp-dev-fx-webparts#999]
Every time I set the requiresCustomScript to false and run gulp bundle  --ship, the value seems to revert back to true. not sure If I'm going anything wrong here.

Do I even need to run the bundle --ship or can just run the package -solution --ship and deploy the file? 

Any help would be appreciated. Thanks

**Comment by wradez** [comment]
We're experiencing this same issue. Would love to hear if any progress has been made on this issue.

**Comment by hugoabernier** [comment]
This issue list is intended for issues with SharePoint web part samples, I encourage you to open a new issue with the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs)
